<?php
$page_title = 'Angular Quiz – 100 Levels – CodeFoundry';
$active_page = 'training';
$quiz_title  = 'Angular';
$quiz_slug   = 'angular';
$quiz_tiers  = [
    [
        'label' => 'Introduction',
        'questions' => [
            ['question' => 'What is Angular?', 'options' => ['A CSS framework', 'A TypeScript-based web application framework by Google', 'A database library', 'A Node.js server framework'], 'correct' => 1],
            ['question' => 'What language is Angular primarily built with?', 'options' => ['JavaScript', 'CoffeeScript', 'TypeScript', 'Dart'], 'correct' => 2],
            ['question' => 'What Angular CLI command creates a new project?', 'options' => ['ng start', 'ng create', 'ng init', 'ng new'], 'correct' => 3],
            ['question' => 'What Angular CLI command serves an application locally?', 'options' => ['ng run', 'ng serve', 'ng start', 'ng launch'], 'correct' => 1],
            ['question' => 'What decorator marks a class as an Angular component?', 'options' => ['@Module', '@Injectable', '@Component', '@Directive'], 'correct' => 2],
            ['question' => 'What decorator marks a class as an Angular module?', 'options' => ['@Component', '@NgModule', '@Injectable', '@Module'], 'correct' => 1],
            ['question' => 'What is the root module in a default Angular application?', 'options' => ['RootModule', 'MainModule', 'AppModule', 'CoreModule'], 'correct' => 2],
            ['question' => 'What is the root component in a default Angular application?', 'options' => ['RootComponent', 'MainComponent', 'IndexComponent', 'AppComponent'], 'correct' => 3],
            ['question' => 'What is the purpose of a selector in @Component metadata?', 'options' => ['To define component styles', 'To specify the HTML tag name that renders the component', 'To import other modules', 'To declare dependencies'], 'correct' => 1],
            ['question' => 'What does ngOnInit do?', 'options' => ['Destroys the component', 'Is called after the component is constructed and inputs are set', 'Handles HTTP requests', 'Creates a new module'], 'correct' => 1],
            ['question' => 'What is interpolation in Angular templates?', 'options' => ['Property binding with []', 'Event binding with ()', 'Displaying data using {{ }} syntax', 'Two-way binding with [()]'], 'correct' => 2],
            ['question' => 'What is the declarations array in @NgModule used for?', 'options' => ['Importing other modules', 'Registering services', 'Registering components, directives, and pipes belonging to this module', 'Defining the root component'], 'correct' => 2],
            ['question' => 'What is the imports array in @NgModule used for?', 'options' => ['Importing other Angular modules', 'Declaring components', 'Providing services', 'Bootstrapping the app'], 'correct' => 0],
            ['question' => 'What is the bootstrap array in @NgModule used for?', 'options' => ['Starting Node.js', 'Declaring the root component to launch on app start', 'Importing CSS', 'Registering services'], 'correct' => 1],
            ['question' => 'What is the main entry point file of an Angular application?', 'options' => ['app.ts', 'index.ts', 'main.ts', 'bootstrap.ts'], 'correct' => 2],
            ['question' => 'What module provides BrowserModule for Angular browser apps?', 'options' => ['CommonModule', 'HttpClientModule', 'FormsModule', '@angular/platform-browser'], 'correct' => 3],
            ['question' => 'What CLI command generates a new component?', 'options' => ['ng make component', 'ng add component', 'ng generate component', 'ng create component'], 'correct' => 2],
            ['question' => 'What does the providers array in @NgModule do?', 'options' => ['Provides CSS', 'Registers services at the module level', 'Lists declared components', 'Imports HTTP methods'], 'correct' => 1],
            ['question' => 'What is the template in an Angular component?', 'options' => ['The TypeScript class', 'The CSS file', 'The HTML that defines the component\'s view', 'The module declaration'], 'correct' => 2],
            ['question' => 'What Angular version first introduced the Ivy renderer?', 'options' => ['Angular 6', 'Angular 7', 'Angular 8', 'Angular 9'], 'correct' => 3],
            ['question' => 'What file extension do Angular component class files use?', 'options' => ['.js', '.html', '.ts', '.ng'], 'correct' => 2],
            ['question' => 'What does the Angular CLI build command produce?', 'options' => ['A development server', 'Compiled output ready for deployment', 'A new project scaffold', 'Unit test results'], 'correct' => 1],
            ['question' => 'What is a module in Angular?', 'options' => ['A CSS class', 'A container grouping components, directives, pipes, and services', 'A database connection', 'A router outlet'], 'correct' => 1],
            ['question' => 'What does BrowserModule provide?', 'options' => ['HTTP methods', 'Core Angular directives like NgIf and NgFor for browser apps', 'Reactive forms', 'Animation support'], 'correct' => 1],
            ['question' => 'Which file is the default HTML entry point in an Angular project?', 'options' => ['app.html', 'main.html', 'index.html', 'root.html'], 'correct' => 2],
        ]
    ],
    [
        'label' => 'Beginner',
        'questions' => [
            ['question' => 'What syntax is used for property binding in Angular?', 'options' => ['{{ property }}', '[property]="expression"', '(property)="handler"', '[(property)]="value"'], 'correct' => 1],
            ['question' => 'What syntax is used for event binding in Angular?', 'options' => ['[click]="handler()"', '{{click}}', '(click)="handler()"', '[(click)]="handler()"'], 'correct' => 2],
            ['question' => 'What syntax is used for two-way data binding in Angular?', 'options' => ['[value]="x"', '(value)="x"', '{{value}}', '[(ngModel)]="property"'], 'correct' => 3],
            ['question' => 'Which module must be imported to use ngModel?', 'options' => ['HttpClientModule', 'RouterModule', 'ReactiveFormsModule', 'FormsModule'], 'correct' => 3],
            ['question' => 'What does *ngIf do?', 'options' => ['Repeats an element', 'Applies CSS classes', 'Conditionally includes or removes an element from the DOM', 'Handles click events'], 'correct' => 2],
            ['question' => 'What does *ngFor do?', 'options' => ['Conditionally shows an element', 'Iterates over a collection and renders a template for each item', 'Applies inline styles', 'Handles form submission'], 'correct' => 1],
            ['question' => 'What does [ngClass] do?', 'options' => ['Iterates over CSS files', 'Conditionally adds or removes CSS classes on an element', 'Binds to the class constructor', 'Applies global styles'], 'correct' => 1],
            ['question' => 'What does [ngStyle] do?', 'options' => ['Imports a style sheet', 'Conditionally applies inline styles to an element', 'Declares scoped styles', 'Sets the component style URL'], 'correct' => 1],
            ['question' => 'What is a pipe in Angular?', 'options' => ['A network protocol', 'A function that transforms displayed values in templates', 'An HTTP middleware', 'A module connector'], 'correct' => 1],
            ['question' => 'Which built-in pipe formats a date value?', 'options' => ['time', 'format', 'date', 'dateFormat'], 'correct' => 2],
            ['question' => 'What decorator marks a class as an Angular service that can be injected?', 'options' => ['@Service', '@Provider', '@Component', '@Injectable'], 'correct' => 3],
            ['question' => 'How is a service typically injected into a component?', 'options' => ['By importing its file', 'By adding it to declarations', 'As a constructor parameter', 'Through the template'], 'correct' => 2],
            ['question' => 'What is Angular dependency injection?', 'options' => ['Injecting HTML into templates', 'A design pattern where Angular provides class dependencies automatically', 'Importing npm packages', 'Linking CSS stylesheets'], 'correct' => 1],
            ['question' => 'Which directive renders the matched route\'s component in Angular Router?', 'options' => ['router-link', 'ng-outlet', 'router-outlet', 'route-view'], 'correct' => 2],
            ['question' => 'Which directive creates a router navigation link?', 'options' => ['href', 'navigate', 'routerLink', 'navLink'], 'correct' => 2],
            ['question' => 'What module must be imported to use Angular Router?', 'options' => ['NavigationModule', 'HttpClientModule', 'RouterModule', 'BrowserModule'], 'correct' => 2],
            ['question' => 'What does the uppercase pipe do?', 'options' => ['Formats currency', 'Converts text to uppercase', 'Makes text bold', 'URL-encodes a string'], 'correct' => 1],
            ['question' => 'What does the async pipe do?', 'options' => ['Makes a function asynchronous', 'Subscribes to an Observable and returns the latest emitted value', 'Delays template rendering', 'Handles errors automatically'], 'correct' => 1],
            ['question' => 'What is the purpose of trackBy in *ngFor?', 'options' => ['Tracks user clicks', 'Improves performance by providing a unique identifier per list item', 'Counts list items', 'Tracks HTTP requests'], 'correct' => 1],
            ['question' => 'What does CommonModule provide?', 'options' => ['HTTP support', 'Common directives like NgIf and NgFor (used in feature modules)', 'Animation utilities', 'Testing utilities'], 'correct' => 1],
            ['question' => 'What does providedIn: \'root\' in @Injectable mean?', 'options' => ['Service is private', 'Service is provided at the root injector, making it a singleton app-wide', 'Service is lazy loaded', 'Service requires a module import'], 'correct' => 1],
            ['question' => 'What is a Route object in Angular?', 'options' => ['An HTTP endpoint', 'A configuration object mapping a URL path to a component', 'A DOM element', 'A module declaration'], 'correct' => 1],
            ['question' => 'Which lifecycle hook is called when Angular checks input properties for changes?', 'options' => ['ngOnInit', 'ngAfterViewInit', 'ngOnChanges', 'ngDoCheck'], 'correct' => 2],
            ['question' => 'What does the currency pipe do?', 'options' => ['Converts units', 'Formats a number as currency', 'Multiplies numbers', 'Parses currency strings'], 'correct' => 1],
            ['question' => 'What does *ngIf with else template allow?', 'options' => ['Running JavaScript else blocks', 'Showing a fallback template when the condition is false', 'Multiple conditions', 'Handling errors'], 'correct' => 1],
        ]
    ],
    [
        'label' => 'Intermediate',
        'questions' => [
            ['question' => 'What class is used to represent a group of form controls in Reactive Forms?', 'options' => ['FormArray', 'FormBuilder', 'FormControl', 'FormGroup'], 'correct' => 3],
            ['question' => 'What class represents a single form control in Reactive Forms?', 'options' => ['FormGroup', 'FormControl', 'FormBuilder', 'FormArray'], 'correct' => 1],
            ['question' => 'Which module must be imported to use Reactive Forms?', 'options' => ['FormsModule', 'CommonModule', 'ReactiveFormsModule', 'HttpClientModule'], 'correct' => 2],
            ['question' => 'What built-in validator checks that a field is not empty?', 'options' => ['Validators.min', 'Validators.pattern', 'Validators.required', 'Validators.email'], 'correct' => 2],
            ['question' => 'What method updates some form control values without affecting others?', 'options' => ['setValue()', 'reset()', 'update()', 'patchValue()'], 'correct' => 3],
            ['question' => 'What service is used to make HTTP requests in Angular?', 'options' => ['FetchService', 'RequestService', 'HttpClient', 'AjaxService'], 'correct' => 2],
            ['question' => 'Which module must be imported to use HttpClient?', 'options' => ['BrowserModule', 'RouterModule', 'CommonModule', 'HttpClientModule'], 'correct' => 3],
            ['question' => 'What is an Observable in RxJS?', 'options' => ['A synchronous data store', 'A lazy stream of values or events over time', 'A static configuration object', 'A Promise wrapper'], 'correct' => 1],
            ['question' => 'What RxJS operator transforms each emitted value with a projection function?', 'options' => ['filter', 'reduce', 'map', 'tap'], 'correct' => 2],
            ['question' => 'What RxJS operator emits only values that pass a test function?', 'options' => ['map', 'scan', 'filter', 'take'], 'correct' => 2],
            ['question' => 'What RxJS operator cancels the previous inner Observable and switches to a new one?', 'options' => ['mergeMap', 'concatMap', 'exhaustMap', 'switchMap'], 'correct' => 3],
            ['question' => 'What lifecycle hook runs just before the component is destroyed?', 'options' => ['ngOnInit', 'ngAfterViewChecked', 'ngOnDestroy', 'ngDoCheck'], 'correct' => 2],
            ['question' => 'What lifecycle hook runs after the component\'s view and child views are initialised?', 'options' => ['ngOnInit', 'ngAfterViewInit', 'ngAfterContentInit', 'ngOnChanges'], 'correct' => 1],
            ['question' => 'What decorator is used to pass data from a parent component to a child?', 'options' => ['@Output', '@Inject', '@HostBinding', '@Input'], 'correct' => 3],
            ['question' => 'What decorator allows a child component to emit events to its parent?', 'options' => ['@Input', '@Output', '@ViewChild', '@ContentChild'], 'correct' => 1],
            ['question' => 'What class is used together with @Output to emit custom events?', 'options' => ['Subject', 'Observable', 'BehaviorSubject', 'EventEmitter'], 'correct' => 3],
            ['question' => 'What is lazy loading in Angular routing?', 'options' => ['Loading images slowly', 'Loading a feature module only when its route is accessed', 'Deferring HTTP calls', 'Using async pipes'], 'correct' => 1],
            ['question' => 'How do you configure a lazily loaded route?', 'options' => ['Using loadComponent()', 'Using preload: true', 'Using loadChildren with a dynamic import', 'Using defer in the template'], 'correct' => 2],
            ['question' => 'What service provides information about the currently activated route?', 'options' => ['RouterState', 'RouteInfo', 'ActivatedRoute', 'CurrentRoute'], 'correct' => 2],
            ['question' => 'What FormArray method adds a control to the array?', 'options' => ['insert()', 'add()', 'push()', 'append()'], 'correct' => 2],
            ['question' => 'What method subscribes to route parameters in ActivatedRoute?', 'options' => ['snapshot.params', 'paramMap.subscribe()', 'params.get()', 'route.listen()'], 'correct' => 1],
            ['question' => 'What does the RxJS tap operator do?', 'options' => ['Transforms values', 'Filters values', 'Performs side effects without altering the stream', 'Combines streams'], 'correct' => 2],
            ['question' => 'What does FormGroup.get() return?', 'options' => ['The form value', 'A specific AbstractControl by name', 'A validation error', 'A DOM element'], 'correct' => 1],
            ['question' => 'What does ngAfterContentInit do?', 'options' => ['Initialises the template', 'Called after projected content (ng-content) is initialised', 'Runs HTTP requests', 'Destroys child components'], 'correct' => 1],
            ['question' => 'What is the purpose of RxJS catchError?', 'options' => ['Retries the Observable', 'Handles errors in an Observable stream gracefully', 'Logs all values', 'Completes the stream'], 'correct' => 1],
        ]
    ],
    [
        'label' => 'Advanced',
        'questions' => [
            ['question' => 'What is NgRx?', 'options' => ['An Angular HTTP client', 'A reactive state management library for Angular based on Redux', 'A CSS-in-JS solution', 'An Angular testing framework'], 'correct' => 1],
            ['question' => 'In NgRx, what are actions?', 'options' => ['HTTP interceptors', 'Plain objects with a type property describing a state change', 'CSS animations', 'Component lifecycle hooks'], 'correct' => 1],
            ['question' => 'In NgRx, what are reducers?', 'options' => ['HTTP response transformers', 'Components that reduce the DOM', 'Pure functions that take current state and an action and return new state', 'Services that reduce bundle size'], 'correct' => 2],
            ['question' => 'In NgRx, what are selectors?', 'options' => ['CSS selectors used in templates', 'Memoised functions for extracting slices of state', 'Component decorators', 'Route matchers'], 'correct' => 1],
            ['question' => 'In NgRx, what are effects?', 'options' => ['CSS visual effects', 'Side-effect handlers that listen to actions and perform async operations', 'DOM event listeners', 'Template animations'], 'correct' => 1],
            ['question' => 'What decorator is used to create a custom Angular directive?', 'options' => ['@Component', '@Pipe', '@Directive', '@NgModule'], 'correct' => 2],
            ['question' => 'What class provides access to the host DOM element inside a directive?', 'options' => ['DomSanitizer', 'Renderer2', 'ElementRef', 'TemplateRef'], 'correct' => 2],
            ['question' => 'What service should be used instead of direct DOM manipulation for security?', 'options' => ['ElementRef', 'Renderer2', 'DomAdapter', 'NativeElement'], 'correct' => 1],
            ['question' => 'What interface must a custom pipe class implement?', 'options' => ['OnInit', 'Observable', 'PipeTransform', 'Transform'], 'correct' => 2],
            ['question' => 'What is a CanActivate guard used for?', 'options' => ['Preloading data before routing', 'Preventing navigation to a route based on a condition', 'Intercepting HTTP requests', 'Caching route components'], 'correct' => 1],
            ['question' => 'What is a CanDeactivate guard used for?', 'options' => ['Blocking HTTP requests', 'Preventing the user from leaving a route (e.g., unsaved changes)', 'Restricting service injection', 'Deactivating lazy modules'], 'correct' => 1],
            ['question' => 'What is an Angular Resolve guard?', 'options' => ['Resolves TypeScript types', 'Pre-fetches data before a route is activated', 'Resolves component dependencies', 'Clears the router cache'], 'correct' => 1],
            ['question' => 'What is an HTTP interceptor in Angular?', 'options' => ['A directive that intercepts clicks', 'A class that intercepts and modifies outgoing requests or incoming responses', 'An error boundary component', 'A route guard'], 'correct' => 1],
            ['question' => 'What is the Default change detection strategy?', 'options' => ['Checks only when inputs change', 'Checks the entire component tree on every change detection cycle', 'Uses Observables exclusively', 'Checks only on async events'], 'correct' => 1],
            ['question' => 'What is the OnPush change detection strategy?', 'options' => ['Pushes changes to a server', 'Only checks a component when its inputs change, an event originates from it, or async pipe emits', 'Detects changes on every mouse move', 'Runs change detection manually only'], 'correct' => 1],
            ['question' => 'What decorator queries a single element or component inside a component\'s view?', 'options' => ['@ContentChild', '@ViewChildren', '@QueryList', '@ViewChild'], 'correct' => 3],
            ['question' => 'What does @ContentChild query?', 'options' => ['Elements inside the component\'s own template', 'Elements projected via ng-content', 'Child routes', 'Nested modules'], 'correct' => 1],
            ['question' => 'What does ng-content do?', 'options' => ['Displays component metadata', 'Projects (transcludes) external content into a component\'s template', 'Defines module content', 'Provides route content'], 'correct' => 1],
            ['question' => 'What decorator listens to DOM events on the host element of a directive or component?', 'options' => ['@HostBinding', '@ViewChild', '@HostListener', '@ContentChild'], 'correct' => 2],
            ['question' => 'What decorator binds a host element property or class in a directive?', 'options' => ['@HostListener', '@HostBinding', '@Input', '@Output'], 'correct' => 1],
            ['question' => 'What does ChangeDetectorRef.markForCheck() do?', 'options' => ['Forces immediate synchronous change detection', 'Marks an OnPush component and its ancestors for checking in the next cycle', 'Detaches the component from change detection', 'Resets form validation'], 'correct' => 1],
            ['question' => 'What does ChangeDetectorRef.detach() do?', 'options' => ['Destroys the component', 'Removes the component from the DOM', 'Detaches the component from the change detection tree', 'Unsubscribes all Observables'], 'correct' => 2],
            ['question' => 'What is the purpose of zone.js in Angular?', 'options' => ['Provides timezone support', 'Patches async browser APIs to trigger Angular change detection automatically', 'Manages module zones', 'Isolates component styles'], 'correct' => 1],
            ['question' => 'What RxJS subject type replays the last emitted value to new subscribers?', 'options' => ['AsyncSubject', 'ReplaySubject', 'Subject', 'BehaviorSubject'], 'correct' => 3],
            ['question' => 'What is the purpose of createFeatureSelector in NgRx?', 'options' => ['Creates a new NgRx module', 'Creates a memoised selector for a specific feature state slice', 'Generates NgRx effects', 'Bootstraps a feature module'], 'correct' => 1],
        ]
    ],
    [
        'label' => 'Expert',
        'questions' => [
            ['question' => 'What is Angular Universal?', 'options' => ['A universal component library', 'Angular\'s solution for server-side rendering (SSR)', 'A cross-platform build tool', 'A universal testing framework'], 'correct' => 1],
            ['question' => 'What primary benefit does SSR with Angular Universal provide?', 'options' => ['Faster unit tests', 'Improved SEO and faster initial page load (FCP)', 'Smaller bundle size', 'Reduced TypeScript compilation time'], 'correct' => 1],
            ['question' => 'What is the Ivy renderer in Angular?', 'options' => ['A CSS-in-JS library', 'Angular\'s next-generation compilation and rendering pipeline (default since Angular 9)', 'A state management solution', 'An RxJS scheduler'], 'correct' => 1],
            ['question' => 'What are Angular standalone components?', 'options' => ['Components that have no child components', 'Components that declare standalone: true and do not require an NgModule', 'Components isolated in separate packages', 'Components with no template'], 'correct' => 1],
            ['question' => 'What property in @Component metadata makes a component standalone?', 'options' => ['module: false', 'isolated: true', 'standalone: true', 'independent: true'], 'correct' => 2],
            ['question' => 'What are Angular Signals?', 'options' => ['HTTP event streams', 'WebSocket messages', 'A reactive primitive for fine-grained state management introduced in Angular 16', 'Custom DOM events'], 'correct' => 2],
            ['question' => 'What function creates a writable signal in Angular?', 'options' => ['reactive()', 'ref()', 'computed()', 'signal()'], 'correct' => 3],
            ['question' => 'What function creates a derived, read-only signal from other signals?', 'options' => ['effect()', 'signal()', 'derived()', 'computed()'], 'correct' => 3],
            ['question' => 'What function registers a side effect that re-runs when its signal dependencies change?', 'options' => ['watch()', 'subscribe()', 'effect()', 'reaction()'], 'correct' => 2],
            ['question' => 'What architectural pattern breaks a large frontend into independently deployable apps?', 'options' => ['Monorepo', 'Micro-frontends', 'Domain-driven design', 'Modular monolith'], 'correct' => 1],
            ['question' => 'What Webpack feature is commonly used to implement micro-frontends in Angular?', 'options' => ['Code Splitting', 'Tree Shaking', 'Module Federation', 'Dynamic Imports'], 'correct' => 2],
            ['question' => 'What is AOT (Ahead-of-Time) compilation?', 'options' => ['Compiling templates at runtime in the browser', 'Compiling templates and TypeScript during the build step before deployment', 'Optimising assets automatically', 'Compiling on the server for each request'], 'correct' => 1],
            ['question' => 'What is the default testing framework used by Angular CLI?', 'options' => ['Jest with Mocha', 'Mocha with Chai', 'Jasmine with Karma', 'Vitest with Playwright'], 'correct' => 2],
            ['question' => 'What Angular testing utility creates a module-like environment for testing components?', 'options' => ['ComponentFactory', 'NgTestBed', 'TestBed', 'TestModule'], 'correct' => 2],
            ['question' => 'What does ComponentFixture provide in Angular tests?', 'options' => ['A mock HTTP server', 'Access to the component instance, its DOM, and change detection', 'Automatic test generation', 'Browser automation'], 'correct' => 1],
            ['question' => 'What does fixture.detectChanges() do in an Angular test?', 'options' => ['Resets the component', 'Runs a single change detection cycle on the component', 'Destroys the fixture', 'Runs all pending HTTP requests'], 'correct' => 1],
            ['question' => 'What is a Jasmine spy?', 'options' => ['A debugging tool in DevTools', 'A function that tracks calls, arguments, and return values, and can stub behaviour', 'A test reporter', 'An HTTP mock'], 'correct' => 1],
            ['question' => 'What does tree shaking do at build time?', 'options' => ['Generates dependency trees', 'Removes unused exported code from the final bundle', 'Shakes the virtual DOM', 'Reorganises imports alphabetically'], 'correct' => 1],
            ['question' => 'What does the @defer block (Angular 17+) do in a template?', 'options' => ['Delays component initialisation by a fixed time', 'Lazily loads a part of the template and its dependencies on a trigger', 'Defers HTTP requests', 'Delays change detection'], 'correct' => 1],
            ['question' => 'What build tool replaced Webpack as the default in Angular 17+?', 'options' => ['Rollup', 'Parcel', 'esbuild with Vite', 'Turbopack'], 'correct' => 2],
            ['question' => 'What is the inject() function in Angular?', 'options' => ['A template directive for DI', 'A function that retrieves a dependency from the current injection context without constructor injection', 'An RxJS operator', 'A testing utility'], 'correct' => 1],
            ['question' => 'What is the Angular CDK (Component Dev Kit)?', 'options' => ['A CLI extension', 'A set of behaviour primitives for building accessible custom UI components', 'A state management library', 'A server-side rendering package'], 'correct' => 1],
            ['question' => 'What does the toSignal() function do?', 'options' => ['Converts a signal to an Observable', 'Converts an Observable to a signal', 'Creates a computed signal', 'Registers a signal effect'], 'correct' => 1],
            ['question' => 'What is the purpose of the APP_INITIALIZER token?', 'options' => ['Bootstraps a module lazily', 'Provides functions that run during application initialisation before the app starts', 'Initialises the Angular compiler', 'Sets the default route'], 'correct' => 1],
            ['question' => 'What does provideRouter() do in a standalone Angular app?', 'options' => ['Creates a new router module', 'Provides the Angular Router without needing to import RouterModule in a NgModule', 'Generates route files', 'Configures HTTP routing'], 'correct' => 1],
        ]
    ],
];
require_once __DIR__ . '/quiz-engine.php';
