<?php
$page_title = 'Bash Quiz – 100 Levels – CodeFoundry';
$active_page = 'training';
$quiz_title  = 'Bash';
$quiz_slug   = 'bash';
$quiz_tiers  = [
    [
        'label' => 'Introduction',
        'questions' => [
            ['question' => 'What is Bash?', 'options' => ['A text editor for Linux', 'A Unix shell and command language used as the default login shell on many Linux distributions', 'A compiled programming language', 'A network protocol'], 'correct' => 1],
            ['question' => 'What does Bash stand for?', 'options' => ['Basic Automated Shell Handler', 'Bourne Again SHell', 'Binary Application Shell Host', 'Bash Automated Script Handler'], 'correct' => 1],
            ['question' => 'What command lists files and directories in the current directory?', 'options' => ['dir', 'list', 'ls', 'show'], 'correct' => 2],
            ['question' => 'What command prints the current working directory?', 'options' => ['cd', 'dir', 'cwd', 'pwd'], 'correct' => 3],
            ['question' => 'What command changes the current directory?', 'options' => ['move', 'dir', 'goto', 'cd'], 'correct' => 3],
            ['question' => 'What command creates a new directory?', 'options' => ['newdir', 'createdir', 'touch', 'mkdir'], 'correct' => 3],
            ['question' => 'What command removes an empty directory?', 'options' => ['delete', 'rmdir', 'rm', 'removedir'], 'correct' => 1],
            ['question' => 'What command removes a file?', 'options' => ['del', 'remove', 'rm', 'erase'], 'correct' => 2],
            ['question' => 'What command copies a file?', 'options' => ['copy', 'cp', 'mv', 'clone'], 'correct' => 1],
            ['question' => 'What command moves or renames a file?', 'options' => ['cp', 'rename', 'mv', 'move'], 'correct' => 2],
            ['question' => 'What command displays the contents of a file?', 'options' => ['show', 'print', 'cat', 'read'], 'correct' => 2],
            ['question' => 'What command displays the first 10 lines of a file?', 'options' => ['top', 'head', 'first', 'start'], 'correct' => 1],
            ['question' => 'What command displays the last 10 lines of a file?', 'options' => ['bottom', 'last', 'end', 'tail'], 'correct' => 3],
            ['question' => 'What command prints text to the terminal?', 'options' => ['print', 'write', 'echo', 'say'], 'correct' => 2],
            ['question' => 'What does the "~" symbol represent in a file path?', 'options' => ['The root directory', 'The previous directory', 'The current user\'s home directory', 'The parent directory'], 'correct' => 2],
            ['question' => 'What does ".." represent in a file path?', 'options' => ['The home directory', 'The current directory', 'The root directory', 'The parent directory'], 'correct' => 3],
            ['question' => 'What does "." represent in a file path?', 'options' => ['The home directory', 'The current directory', 'The parent directory', 'The root directory'], 'correct' => 1],
            ['question' => 'What is the root directory in Linux?', 'options' => ['~', '/home', '/root', '/'], 'correct' => 3],
            ['question' => 'What command searches for text within files?', 'options' => ['find', 'search', 'grep', 'look'], 'correct' => 2],
            ['question' => 'What command displays a manual (help page) for a command?', 'options' => ['help', 'info', 'man', 'docs'], 'correct' => 2],
            ['question' => 'What command creates an empty file or updates a file\'s timestamp?', 'options' => ['new', 'create', 'touch', 'make'], 'correct' => 2],
            ['question' => 'What symbol is used to redirect command output to a file (overwriting it)?', 'options' => ['|', '>>', '<', '>'], 'correct' => 3],
            ['question' => 'What symbol appends command output to a file?', 'options' => ['>', '|', '>>', '&'], 'correct' => 2],
            ['question' => 'What symbol is used to pipe the output of one command as input to another?', 'options' => ['>', '&', '|', '>>'], 'correct' => 2],
            ['question' => 'What command clears the terminal screen?', 'options' => ['wipe', 'clean', 'cls', 'clear'], 'correct' => 3],
        ],
    ],
    [
        'label' => 'Beginner',
        'questions' => [
            ['question' => 'What flag makes "ls" list files in long format with details?', 'options' => ['-a', '-h', '-r', '-l'], 'correct' => 3],
            ['question' => 'What flag makes "ls" show hidden files?', 'options' => ['-l', '-h', '-a', '-r'], 'correct' => 2],
            ['question' => 'How do you make a file executable?', 'options' => ['chmod +x filename', 'exec filename', 'chown +x filename', 'enable filename'], 'correct' => 0],
            ['question' => 'What does "chmod 755 file" set?', 'options' => ['Read-only for everyone', 'Full permissions for owner, read and execute for group and others', 'Full permissions for everyone', 'No permissions for anyone'], 'correct' => 1],
            ['question' => 'What command shows currently running processes?', 'options' => ['jobs', 'tasks', 'ps', 'list'], 'correct' => 2],
            ['question' => 'What command provides a dynamic real-time view of running processes?', 'options' => ['ps aux', 'jobs', 'htop or top', 'proclist'], 'correct' => 2],
            ['question' => 'What command terminates a process by its PID?', 'options' => ['stop', 'terminate', 'kill', 'end'], 'correct' => 2],
            ['question' => 'What command displays disk usage of the file system?', 'options' => ['disk', 'storage', 'du', 'df'], 'correct' => 3],
            ['question' => 'What command shows disk usage of files and directories?', 'options' => ['df', 'ls -s', 'du', 'size'], 'correct' => 2],
            ['question' => 'How do you run a shell script named "script.sh"?', 'options' => ['run script.sh', 'execute script.sh', 'bash script.sh', 'start script.sh'], 'correct' => 2],
            ['question' => 'What is the shebang line in a script?', 'options' => ['A comment describing the script', 'The first line starting with #! that specifies the interpreter for the script', 'A line that imports libraries', 'A special error handling directive'], 'correct' => 1],
            ['question' => 'What is the correct shebang for a Bash script?', 'options' => ['#!/usr/bin/python', '#! /bin/sh only', '#!/bin/bash', '#/bin/bash'], 'correct' => 2],
            ['question' => 'How do you assign a variable in Bash?', 'options' => ['var name = value', 'let name = value', 'name=value', 'set name = value'], 'correct' => 2],
            ['question' => 'How do you reference (use) a variable named "name" in Bash?', 'options' => ['@name', '%name%', '&name', '$name'], 'correct' => 3],
            ['question' => 'What does the "&&" operator do between two commands?', 'options' => ['Runs the second command regardless of the first result', 'Runs both commands in parallel', 'Runs the second command only if the first succeeds', 'Pipes the output to the second command'], 'correct' => 2],
            ['question' => 'What does the "||" operator do between two commands?', 'options' => ['Runs the second command only if the first succeeds', 'Runs the second command only if the first fails', 'Pipes output between commands', 'Combines the outputs of both commands'], 'correct' => 1],
            ['question' => 'What command searches for files and directories by name?', 'options' => ['locate', 'search', 'grep -r', 'find'], 'correct' => 3],
            ['question' => 'What command displays your command history?', 'options' => ['log', 'past', 'history', 'cmds'], 'correct' => 2],
            ['question' => 'What keyboard shortcut searches command history interactively in Bash?', 'options' => ['Ctrl+R', 'Ctrl+H', 'Ctrl+F', 'Ctrl+S'], 'correct' => 0],
            ['question' => 'What does "wc -l filename" count?', 'options' => ['The number of words', 'The number of characters', 'The number of lines in the file', 'The file size in bytes'], 'correct' => 2],
            ['question' => 'What command sorts the lines of a file?', 'options' => ['order', 'rank', 'sort', 'arrange'], 'correct' => 2],
            ['question' => 'What command removes duplicate adjacent lines from a sorted file?', 'options' => ['distinct', 'dedup', 'nodup', 'uniq'], 'correct' => 3],
            ['question' => 'What does "grep -i" do?', 'options' => ['Searches in included files only', 'Inverts the match', 'Performs a case-insensitive search', 'Searches only integer values'], 'correct' => 2],
            ['question' => 'What does "grep -r" do?', 'options' => ['Searches in reverse', 'Reverses the output', 'Searches recursively through directories', 'Searches using regex only'], 'correct' => 2],
            ['question' => 'What does the "which" command do?', 'options' => ['Lists installed packages', 'Displays the full path of a command\'s executable', 'Shows which user is logged in', 'Lists available commands'], 'correct' => 1],
        ],
    ],
    [
        'label' => 'Intermediate',
        'questions' => [
            ['question' => 'How do you write an if statement in Bash?', 'options' => ['if condition; then ... fi', 'if (condition) { ... }', 'if condition then ... end', 'if condition: ... endif'], 'correct' => 0],
            ['question' => 'What is the correct syntax for a for loop in Bash?', 'options' => ['for i in list do ... done', 'for (i in list) { ... }', 'for i in list; do ... done', 'for i: list; ... end'], 'correct' => 2],
            ['question' => 'What is the correct syntax for a while loop in Bash?', 'options' => ['while condition; do ... done', 'while (condition) { ... }', 'while condition do ... end', 'while condition: ... done'], 'correct' => 0],
            ['question' => 'How do you define a function in Bash?', 'options' => ['function myfunc() { ... }', 'def myfunc() { ... }', 'func myfunc() { ... }', 'sub myfunc() { ... }'], 'correct' => 0],
            ['question' => 'What variable holds the exit status of the last command?', 'options' => ['$STATUS', '$ERR', '$EXIT', '$?'], 'correct' => 3],
            ['question' => 'What exit code indicates success in Bash?', 'options' => ['1', '-1', '0', '255'], 'correct' => 2],
            ['question' => 'What does "$#" hold in a Bash script?', 'options' => ['The name of the script', 'The last argument', 'The number of positional parameters passed to the script', 'All positional parameters'], 'correct' => 2],
            ['question' => 'What does "$@" expand to in a Bash script?', 'options' => ['The number of arguments', 'The script name', 'All positional parameters as separate quoted strings', 'The last argument only'], 'correct' => 2],
            ['question' => 'What does "$0" hold in a Bash script?', 'options' => ['The first argument', 'The exit status', 'The process ID', 'The name of the script itself'], 'correct' => 3],
            ['question' => 'What does "$1" hold in a Bash script?', 'options' => ['The number of arguments', 'The first positional argument passed to the script', 'The exit status', 'The PID of the script'], 'correct' => 1],
            ['question' => 'What does command substitution $( ) do?', 'options' => ['Creates a subshell that cannot modify the parent', 'Runs a command and substitutes its output as a string in place', 'Substitutes a variable value', 'Escapes special characters in a command'], 'correct' => 1],
            ['question' => 'What is an environment variable?', 'options' => ['A variable only accessible inside a function', 'A variable defined in the script header only', 'A variable exported to child processes and available to the process environment', 'A variable storing system configuration permanently'], 'correct' => 2],
            ['question' => 'What command exports a variable to the environment?', 'options' => ['set', 'env VAR=value', 'export VAR', 'declare -g VAR'], 'correct' => 2],
            ['question' => 'What does "set -e" do in a Bash script?', 'options' => ['Enables extended globbing', 'Exports all variables automatically', 'Causes the script to exit immediately if any command returns a non-zero exit code', 'Enables error logging'], 'correct' => 2],
            ['question' => 'What does "set -u" do in a Bash script?', 'options' => ['Makes the script run as the current user', 'Causes the script to exit if an undefined variable is used', 'Sets user permissions', 'Updates the script file'], 'correct' => 1],
            ['question' => 'What does "set -x" do in a Bash script?', 'options' => ['Enables extended regex', 'Exits the script on errors', 'Prints each command and its arguments as they are executed (trace mode)', 'Sets execute permission'], 'correct' => 2],
            ['question' => 'What does the "tee" command do?', 'options' => ['Redirects stderr to stdout', 'Reads from standard input and writes to both standard output and one or more files simultaneously', 'Splits input into two streams', 'Appends output to a file only'], 'correct' => 1],
            ['question' => 'How do you redirect stderr to a file in Bash?', 'options' => ['command &> file', 'command 2> file', 'command 1> file', 'command err> file'], 'correct' => 1],
            ['question' => 'How do you redirect both stdout and stderr to the same file?', 'options' => ['command > file 1>&2', 'command 2>&1 > file', 'command > file 2>&1', 'command | file 2>&1'], 'correct' => 2],
            ['question' => 'What is a here document (heredoc) in Bash?', 'options' => ['A way to import a file into a script', 'A multiline string literal starting with << DELIMITER that passes multiple lines as input to a command', 'A way to define multiline functions', 'A special comment block'], 'correct' => 1],
            ['question' => 'What does "test -f filename" check?', 'options' => ['Whether the file is executable', 'Whether the path is a directory', 'Whether the file exists and is a regular file', 'Whether the file is empty'], 'correct' => 2],
            ['question' => 'What does "test -d path" check?', 'options' => ['Whether the path is a regular file', 'Whether the path is a directory', 'Whether the directory is empty', 'Whether the directory is writable'], 'correct' => 1],
            ['question' => 'What does "test -z string" check?', 'options' => ['Whether the string contains zero digits', 'Whether the string is exactly "0"', 'Whether the string has zero characters (is empty)', 'Whether the string is undefined'], 'correct' => 2],
            ['question' => 'What does "cut -d: -f1 /etc/passwd" do?', 'options' => ['Cuts the first byte of the file', 'Extracts the first field from each line of /etc/passwd using : as delimiter', 'Removes the first line of the file', 'Counts colons in the file'], 'correct' => 1],
            ['question' => 'What does the "awk" command do?', 'options' => ['Only renames files', 'A pattern scanning and processing language that processes text line by line', 'Archives files into a tarball', 'Monitors system resources'], 'correct' => 1],
        ],
    ],
    [
        'label' => 'Advanced',
        'questions' => [
            ['question' => 'What does "sed -i" do?', 'options' => ['Runs sed interactively', 'Edits files in-place, modifying the original file directly', 'Performs case-insensitive substitution', 'Inserts a new line'], 'correct' => 1],
            ['question' => 'What does the sed command "s/foo/bar/g" do?', 'options' => ['Replaces the first occurrence of foo with bar per line', 'Replaces foo with bar globally, replacing all occurrences per line', 'Deletes all lines containing foo', 'Swaps foo and bar throughout the file'], 'correct' => 1],
            ['question' => 'What is a subshell in Bash?', 'options' => ['A background process', 'A child shell process created in a separate environment; changes inside do not affect the parent shell', 'A shell with reduced permissions', 'A function that runs asynchronously'], 'correct' => 1],
            ['question' => 'What does running a command inside parentheses ( ) do?', 'options' => ['Groups commands without a subshell', 'Runs the commands in a subshell', 'Expands the command output', 'Runs the commands with elevated privileges'], 'correct' => 1],
            ['question' => 'What does running commands inside curly braces { } do?', 'options' => ['Creates a subshell', 'Groups commands in the current shell without creating a subshell', 'Creates a function automatically', 'Defers the commands until end of script'], 'correct' => 1],
            ['question' => 'What is process substitution in Bash?', 'options' => ['Replacing one process with another using exec', 'A feature using <(command) or >(command) that treats command output as a file descriptor', 'Substituting a command name with an alias', 'Running a command and capturing its PID'], 'correct' => 1],
            ['question' => 'What does the "trap" command do in Bash?', 'options' => ['Traps user input in a variable', 'Specifies commands to run when the script receives a signal or exits', 'Creates a temporary file', 'Catches exceptions from subshells'], 'correct' => 1],
            ['question' => 'What signal does "trap ... EXIT" catch?', 'options' => ['SIGTERM only', 'SIGINT only', 'Any exit from the script, whether normal or due to a signal', 'SIGHUP only'], 'correct' => 2],
            ['question' => 'What is the difference between single quotes and double quotes in Bash?', 'options' => ['No difference', 'Single quotes preserve every character literally; double quotes allow variable expansion and command substitution', 'Double quotes prevent all expansion; single quotes allow variable expansion', 'Single quotes are for numbers; double quotes for strings'], 'correct' => 1],
            ['question' => 'What does "declare -a" do?', 'options' => ['Declares a global variable', 'Declares an indexed array variable', 'Declares an associative array', 'Makes a variable read-only'], 'correct' => 1],
            ['question' => 'What does "declare -A" do?', 'options' => ['Declares an indexed array', 'Marks a variable as an integer', 'Declares an associative (hash) array', 'Exports a variable'], 'correct' => 2],
            ['question' => 'What does "${array[@]}" expand to in Bash?', 'options' => ['The length of the array', 'The first element of the array', 'All elements of the array as separate words', 'The array variable name'], 'correct' => 2],
            ['question' => 'What does "${#array[@]}" return?', 'options' => ['The last index of the array', 'The first element', 'All array elements joined', 'The number of elements in the array'], 'correct' => 3],
            ['question' => 'What is the purpose of "readonly" in Bash?', 'options' => ['Makes a file read-only in the filesystem', 'Marks a variable or function as immutable so it cannot be changed or unset', 'Sets file permissions to 444', 'Creates a constant in the current script only'], 'correct' => 1],
            ['question' => 'What does "local" do inside a Bash function?', 'options' => ['Exports the variable to child processes', 'Restricts the variable\'s scope to the function, preventing it from affecting the global scope', 'Creates a read-only variable', 'Declares an array variable'], 'correct' => 1],
            ['question' => 'What does "xargs" do?', 'options' => ['Extends the ARG_MAX limit', 'Reads items from standard input and executes a command with those items as arguments', 'Parses command-line arguments', 'Expands variables in arguments'], 'correct' => 1],
            ['question' => 'What is the purpose of "/dev/null"?', 'options' => ['A null device that discards all data written to it and returns EOF when read', 'A temporary storage device', 'A special device for debugging', 'The current terminal device'], 'correct' => 0],
            ['question' => 'What does "2>/dev/null" do?', 'options' => ['Redirects stdout to /dev/null', 'Redirects both stdout and stderr to /dev/null', 'Suppresses error messages by redirecting stderr to /dev/null', 'Discards the last command exit code'], 'correct' => 2],
            ['question' => 'What is brace expansion in Bash?', 'options' => ['Expanding variables inside curly braces', 'A shorthand to generate multiple strings or sequences: e.g., {a,b,c} or {1..5}', 'Running a group of commands', 'Accessing array elements'], 'correct' => 1],
            ['question' => 'What does "!!" expand to in Bash?', 'options' => ['Negates the exit status', 'The last command run', 'Runs the command in debug mode', 'Forces a command to run regardless of errors'], 'correct' => 1],
            ['question' => 'What does "nohup command &" do?', 'options' => ['Runs a command with higher priority', 'Runs a command in the foreground, ignoring signals', 'Runs a command in the background, immune to SIGHUP so it persists after logout', 'Prevents a command from writing output'], 'correct' => 2],
            ['question' => 'What is globbing in Bash?', 'options' => ['Running multiple commands in parallel', 'Filename expansion using wildcard characters like *, ?, and [...]', 'Global variable expansion', 'A method of searching files with grep'], 'correct' => 1],
            ['question' => 'What does the glob pattern "*.txt" match?', 'options' => ['Files that start with .txt', 'Any file with exactly one character before .txt', 'Any file ending in .txt', 'Only files named .txt'], 'correct' => 2],
            ['question' => 'What does "read -p" do in Bash?', 'options' => ['Reads a file path from stdin', 'Reads input from the user and displays a prompt string before reading', 'Reads in parallel mode', 'Reads and prints a variable'], 'correct' => 1],
            ['question' => 'What does the "source" command (or ".") do in Bash?', 'options' => ['Compiles a script', 'Creates a new subshell to run the script', 'Reads and executes commands from a file in the current shell environment', 'Imports only functions from a script'], 'correct' => 2],
        ],
    ],
    [
        'label' => 'Expert',
        'questions' => [
            ['question' => 'What is the difference between "exec" and running a subshell in Bash?', 'options' => ['No difference', 'exec replaces the current shell process with the specified command without forking a new process', 'exec always runs a command as root', 'exec runs a command in a subshell'], 'correct' => 1],
            ['question' => 'What does "exec 3<> file" do in Bash?', 'options' => ['Creates file descriptor 3 for both reading and writing on the given file', 'Executes the file with descriptor 3', 'Appends to the file using descriptor 3', 'Redirects stderr to the file'], 'correct' => 0],
            ['question' => 'What is the purpose of "set -o pipefail"?', 'options' => ['Makes all pipes use subshells', 'Causes a pipeline to return a failure exit code if any command in the pipeline fails, not just the last', 'Disables pipes in strict mode', 'Enables pipeline tracing'], 'correct' => 1],
            ['question' => 'What does the "wait" command do in Bash?', 'options' => ['Pauses execution for a fixed time', 'Waits for all background jobs (or a specific PID) to finish and returns their exit statuses', 'Waits for user input', 'Pauses until a file changes'], 'correct' => 1],
            ['question' => 'What is a named pipe (FIFO) in Linux?', 'options' => ['A pipe with a label attached to its output', 'A special file that acts as a pipe with a name in the filesystem, allowing unrelated processes to communicate', 'A faster version of the | pipe', 'A pipe used only with named commands'], 'correct' => 1],
            ['question' => 'What does "mkfifo mypipe" create?', 'options' => ['A regular file named mypipe', 'A named pipe (FIFO) special file named mypipe', 'A directory named mypipe', 'A symbolic link named mypipe'], 'correct' => 1],
            ['question' => 'What does the Bash option "noclobber" (set -C) do?', 'options' => ['Prevents the script from overwriting itself', 'Prevents overwriting existing files with output redirection using >', 'Prevents deletion of files with rm', 'Makes all writes append-only'], 'correct' => 1],
            ['question' => 'What is the purpose of "ulimit" in Bash?', 'options' => ['Sets user account limits in /etc/passwd', 'Controls resource limits (such as file size and number of open files) for the current shell and its child processes', 'Limits the number of user logins', 'Sets the maximum memory available to the shell'], 'correct' => 1],
            ['question' => 'What does "disown" do in Bash?', 'options' => ['Removes ownership of a file', 'Removes a job from the shell\'s job table so it is no longer managed by the shell and won\'t receive SIGHUP on shell exit', 'Changes the owner of a background process', 'Detaches a process from the terminal only'], 'correct' => 1],
            ['question' => 'What is the significance of IFS in Bash?', 'options' => ['It stands for Internal Field Separator and controls how Bash splits words when expanding unquoted variables and when reading input', 'It sets the encoding for international files', 'It controls the behavior of the if statement', 'It is the index of the first array element'], 'correct' => 0],
            ['question' => 'What does "printf" offer over "echo" in Bash scripting?', 'options' => ['printf is always faster', 'printf provides more precise formatting control and predictable behavior across implementations, unlike echo which varies by implementation', 'echo cannot print variables', 'printf prints to files only'], 'correct' => 1],
            ['question' => 'What is the "coprocess" feature in Bash?', 'options' => ['Running two scripts in parallel', 'A feature using "coproc" that runs a command as a background process with file descriptors connected to the parent shell for two-way communication', 'Running a command in a subshell with shared variables', 'A way to execute multiple commands simultaneously using &'], 'correct' => 1],
            ['question' => 'What does "$(( ))" do in Bash?', 'options' => ['Performs command substitution', 'Performs arithmetic expansion, evaluating the expression as an integer', 'Runs a subshell', 'Expands a glob pattern'], 'correct' => 1],
            ['question' => 'What is the purpose of "mapfile" (or "readarray") in Bash?', 'options' => ['Maps environment variables to an array', 'Reads lines from stdin or a file into an indexed array variable', 'Maps a file to memory', 'Reads a configuration file'], 'correct' => 1],
            ['question' => 'What does "${var:-default}" do in Bash parameter expansion?', 'options' => ['Assigns default to var if var is unset', 'Returns the value of var if set and non-empty, otherwise returns default without modifying var', 'Removes the suffix matching default from var', 'Returns default only if var is explicitly empty'], 'correct' => 1],
            ['question' => 'What does "${var:=default}" do?', 'options' => ['Returns default but does not assign it', 'Returns and assigns default to var if var is unset or empty', 'Returns an error if var is unset', 'Substitutes var only if default is set'], 'correct' => 1],
            ['question' => 'What does "${var#pattern}" do?', 'options' => ['Removes the longest matching prefix from var', 'Removes the shortest matching prefix of pattern from the value of var', 'Removes the shortest matching suffix from var', 'Returns the length of var'], 'correct' => 1],
            ['question' => 'What does "${var%%pattern}" do?', 'options' => ['Removes the shortest matching suffix', 'Removes the shortest matching prefix', 'Returns the length of the matching part', 'Removes the longest matching suffix from the value of var'], 'correct' => 3],
            ['question' => 'What does "declare -i" do in Bash?', 'options' => ['Declares an indexed array', 'Marks a variable as an integer so arithmetic is performed automatically on assignment', 'Makes a variable immutable', 'Declares an inline variable'], 'correct' => 1],
            ['question' => 'What is the purpose of "flock" in shell scripting?', 'options' => ['Locking file permissions', 'Managing file locks to ensure mutually exclusive access to a resource by multiple script instances', 'Blocking network access', 'Locking a user account'], 'correct' => 1],
            ['question' => 'What does "strace" do?', 'options' => ['Shows CPU usage of a process', 'Traces system calls and signals made by a process', 'Profiles memory allocation', 'Traces network packets'], 'correct' => 1],
            ['question' => 'What is the effect of quoting "$@" (double-quoted) vs $* in Bash?', 'options' => ['No difference', '"$@" expands each argument as a separate quoted word; "$*" expands all arguments as a single word joined by the first IFS character', '"$*" preserves each argument; "$@" joins them', 'Both expand identically when IFS is a space'], 'correct' => 1],
            ['question' => 'What does "command -v name" do?', 'options' => ['Runs name in verbose mode', 'Outputs the path or type of the command if it exists, without executing it — useful for checking if a command is available', 'Lists the version of a command', 'Validates the command syntax'], 'correct' => 1],
            ['question' => 'What is "bash -n script.sh" used for?', 'options' => ['Runs the script with no output', 'Reads the script and checks it for syntax errors without executing it', 'Runs the script with null environment', 'Runs the script ignoring traps'], 'correct' => 1],
            ['question' => 'What does the "getopts" built-in do in Bash?', 'options' => ['Gets system options from /etc/config', 'Parses positional parameters as short options in a portable way within a script', 'Reads options from a configuration file', 'Sets global options for the shell'], 'correct' => 1],
        ],
    ],
];
require_once __DIR__ . '/quiz-engine.php';
