<?php
$page_title = 'Bootstrap Quiz – 100 Levels – CodeFoundry';
$active_page = 'training';
$quiz_title  = 'Bootstrap';
$quiz_slug   = 'bootstrap';
$quiz_tiers  = [
    ['label' => 'Introduction', 'questions' => [
        ['question' => 'What is Bootstrap?', 'options' => ['A JavaScript framework', 'A CSS framework for responsive design', 'A database system', 'A server technology'], 'correct' => 1],
        ['question' => 'Which company created Bootstrap?', 'options' => ['Google', 'Twitter', 'Facebook', 'Microsoft'], 'correct' => 1],
        ['question' => 'How can you include Bootstrap via CDN?', 'options' => ['Install npm package', 'Link CSS and JS files from CDN', 'Download source code', 'Use PHP include'], 'correct' => 1],
        ['question' => 'What class is used for a full-width container?', 'options' => ['.container', '.container-fluid', '.full-width', '.container-full'], 'correct' => 1],
        ['question' => 'What class creates a Bootstrap row?', 'options' => ['.row', '.grid-row', '.flex-row', '.line'], 'correct' => 0],
        ['question' => 'What class creates a column?', 'options' => ['.column', '.col', '.grid-col', '.cell'], 'correct' => 1],
        ['question' => 'What does .col-md-6 mean?', 'options' => ['6 pixels wide', '6 of 12 columns on medium+ screens', '6 rows', '6 containers'], 'correct' => 1],
        ['question' => 'What class creates a button?', 'options' => ['.button', '.btn', '.btn-default', '.click'], 'correct' => 1],
        ['question' => 'What class makes a primary (blue) button?', 'options' => ['.btn-blue', '.btn-primary', '.btn-main', '.primary'], 'correct' => 1],
        ['question' => 'What class makes a secondary button?', 'options' => ['.btn-secondary', '.btn-gray', '.btn-alt', '.secondary'], 'correct' => 0],
        ['question' => 'What class centers text?', 'options' => ['.center', '.text-center', '.align-center', '.center-text'], 'correct' => 1],
        ['question' => 'What class hides an element?', 'options' => ['.hide', '.d-none', '.hidden', '.invisible'], 'correct' => 1],
        ['question' => 'What class creates a flex container?', 'options' => ['.flex', '.d-flex', '.flexbox', '.flex-container'], 'correct' => 1],
        ['question' => 'What class creates a Bootstrap navbar?', 'options' => ['.nav', '.navbar', '.navigation', '.menu'], 'correct' => 1],
        ['question' => 'What is a jumbotron in Bootstrap 4?', 'options' => ['A button', 'A large showcase component', 'A table', 'A form'], 'correct' => 1],
        ['question' => 'Is jumbotron available in Bootstrap 5?', 'options' => ['Yes, unchanged', 'No, removed', 'Yes, renamed', 'Yes, improved'], 'correct' => 1],
        ['question' => 'What class creates a card component?', 'options' => ['.card', '.panel', '.box', '.container'], 'correct' => 0],
        ['question' => 'What class is for the card body?', 'options' => ['.card-content', '.card-body', '.card-main', '.body'], 'correct' => 1],
        ['question' => 'What class creates a badge?', 'options' => ['.badge', '.label', '.tag', '.chip'], 'correct' => 0],
        ['question' => 'What class creates an alert?', 'options' => ['.alert', '.message', '.notification', '.notice'], 'correct' => 0],
        ['question' => 'What class makes a success alert?', 'options' => ['.alert-green', '.alert-success', '.success', '.alert-ok'], 'correct' => 1],
        ['question' => 'What class makes images responsive?', 'options' => ['.responsive-img', '.img-fluid', '.img-responsive', '.fluid-img'], 'correct' => 1],
        ['question' => 'What is the default Bootstrap grid column count?', 'options' => ['10', '12', '16', '24'], 'correct' => 1],
        ['question' => 'Which breakpoint represents small devices?', 'options' => ['xs', 'sm', 'md', 'lg'], 'correct' => 1],
        ['question' => 'Which breakpoint represents medium devices?', 'options' => ['sm', 'md', 'lg', 'xl'], 'correct' => 1],
        ['question' => 'Which breakpoint represents large devices?', 'options' => ['md', 'lg', 'xl', 'xxl'], 'correct' => 1],
        ['question' => 'What does .mt-3 do?', 'options' => ['Margin top 3 units', 'Margin 3 on all sides', 'Padding top 3', 'Border 3'], 'correct' => 0],
        ['question' => 'What does .p-2 do?', 'options' => ['Margin 2', 'Padding 2 on all sides', 'Position 2', 'Priority 2'], 'correct' => 1],
        ['question' => 'What class adds primary text color?', 'options' => ['.text-primary', '.color-primary', '.primary', '.text-blue'], 'correct' => 0],
        ['question' => 'What class adds danger background color?', 'options' => ['.bg-danger', '.background-danger', '.danger-bg', '.red-bg'], 'correct' => 0],
    ]],
    ['label' => 'Beginner', 'questions' => [
        ['question' => 'How many columns are in the Bootstrap grid?', 'options' => ['10', '12', '16', '24'], 'correct' => 1],
        ['question' => 'What does .col-lg-4 mean?', 'options' => ['4 pixels', '4 of 12 columns on large screens', '4 breakpoints', '4 containers'], 'correct' => 1],
        ['question' => 'Can you nest rows inside columns?', 'options' => ['No', 'Yes', 'Only in Bootstrap 5', 'Only with special class'], 'correct' => 1],
        ['question' => 'What class offsets a column by 2?', 'options' => ['.offset-2', '.col-offset-2', '.push-2', '.margin-2'], 'correct' => 0],
        ['question' => 'What class changes column order?', 'options' => ['.order-*', '.sort-*', '.sequence-*', '.position-*'], 'correct' => 0],
        ['question' => 'What does .justify-content-center do?', 'options' => ['Aligns items vertically', 'Centers flex items horizontally', 'Centers text', 'Aligns content to right'], 'correct' => 1],
        ['question' => 'What does .align-items-center do?', 'options' => ['Centers horizontally', 'Centers flex items vertically', 'Centers text', 'Aligns to bottom'], 'correct' => 1],
        ['question' => 'What class enables flex wrapping?', 'options' => ['.wrap', '.flex-wrap', '.wrap-flex', '.d-wrap'], 'correct' => 1],
        ['question' => 'What class creates a display-1 heading?', 'options' => ['.h1', '.display-1', '.heading-1', '.title-1'], 'correct' => 1],
        ['question' => 'What class creates a lead paragraph?', 'options' => ['.lead', '.intro', '.lead-text', '.p-lead'], 'correct' => 0],
        ['question' => 'What class makes text muted?', 'options' => ['.muted', '.text-muted', '.gray', '.text-gray'], 'correct' => 1],
        ['question' => 'What class makes text bold?', 'options' => ['.bold', '.fw-bold', '.font-bold', '.text-bold'], 'correct' => 1],
        ['question' => 'What class makes text italic?', 'options' => ['.italic', '.fst-italic', '.font-italic', '.text-italic'], 'correct' => 1],
        ['question' => 'What class creates an outline button?', 'options' => ['.btn-outline', '.btn-outline-primary', '.outline-btn', '.btn-border'], 'correct' => 1],
        ['question' => 'What class makes a large button?', 'options' => ['.btn-large', '.btn-lg', '.btn-big', '.large-btn'], 'correct' => 1],
        ['question' => 'What class makes a small button?', 'options' => ['.btn-small', '.btn-sm', '.btn-tiny', '.small-btn'], 'correct' => 1],
        ['question' => 'What class creates a button group?', 'options' => ['.btn-group', '.button-group', '.group-btn', '.btn-cluster'], 'correct' => 0],
        ['question' => 'What class styles form controls?', 'options' => ['.input', '.form-control', '.control', '.form-input'], 'correct' => 1],
        ['question' => 'What class styles form labels?', 'options' => ['.label', '.form-label', '.input-label', '.control-label'], 'correct' => 1],
        ['question' => 'What class styles select elements?', 'options' => ['.select', '.form-select', '.dropdown', '.form-dropdown'], 'correct' => 1],
        ['question' => 'What class creates checkboxes?', 'options' => ['.checkbox', '.form-check', '.check', '.form-checkbox'], 'correct' => 1],
        ['question' => 'What class creates input groups?', 'options' => ['.input-group', '.group-input', '.form-group', '.control-group'], 'correct' => 0],
        ['question' => 'What class creates floating labels (BS5)?', 'options' => ['.float-label', '.form-floating', '.floating-label', '.label-float'], 'correct' => 1],
        ['question' => 'What class creates a striped table?', 'options' => ['.table-striped', '.striped', '.zebra', '.table-zebra'], 'correct' => 0],
        ['question' => 'What class creates a hoverable table?', 'options' => ['.table-hover', '.hover', '.table-highlight', '.hoverable'], 'correct' => 0],
        ['question' => 'What class creates a bordered table?', 'options' => ['.table-bordered', '.bordered', '.table-border', '.border-table'], 'correct' => 0],
        ['question' => 'What class makes a table responsive?', 'options' => ['.responsive-table', '.table-responsive', '.responsive', '.table-fluid'], 'correct' => 1],
        ['question' => 'What class creates a list group?', 'options' => ['.list-group', '.group-list', '.list', '.group'], 'correct' => 0],
        ['question' => 'What class creates breadcrumbs?', 'options' => ['.breadcrumb', '.breadcrumbs', '.nav-breadcrumb', '.crumb'], 'correct' => 0],
        ['question' => 'What class creates pagination?', 'options' => ['.pagination', '.pages', '.pager', '.page-nav'], 'correct' => 0],
        ['question' => 'What class creates a progress bar?', 'options' => ['.progress', '.progress-bar', '.bar', '.loading'], 'correct' => 0],
        ['question' => 'What class creates a spinner?', 'options' => ['.spinner', '.spinner-border', '.loading', '.spin'], 'correct' => 1],
        ['question' => 'Do tooltips require JavaScript initialization?', 'options' => ['No', 'Yes', 'Only in BS4', 'Only in BS5'], 'correct' => 1],
        ['question' => 'What class creates a modal?', 'options' => ['.modal', '.dialog', '.popup', '.overlay'], 'correct' => 0],
        ['question' => 'What class creates an accordion?', 'options' => ['.accordion', '.collapse-group', '.expand', '.toggle-group'], 'correct' => 0],
        ['question' => 'What class creates a dropdown?', 'options' => ['.dropdown', '.drop', '.menu-drop', '.select-drop'], 'correct' => 0],
        ['question' => 'What is offcanvas in Bootstrap 5?', 'options' => ['A table', 'A sidebar component', 'A button', 'A form'], 'correct' => 1],
    ]],
    ['label' => 'Intermediate', 'questions' => [
        ['question' => 'How do you customize Bootstrap with Sass?', 'options' => ['Modify CSS', 'Override Sass variables', 'Use inline styles', 'Edit source HTML'], 'correct' => 1],
        ['question' => 'What file structure does Bootstrap Sass use?', 'options' => ['Single file', 'Modular @import/@use', 'Inline styles', 'No structure'], 'correct' => 1],
        ['question' => 'Can you customize Bootstrap breakpoints?', 'options' => ['No', 'Yes, via Sass variables', 'Only in BS4', 'Only via JavaScript'], 'correct' => 1],
        ['question' => 'Does Bootstrap 5 use CSS variables?', 'options' => ['No', 'Yes', 'Only for colors', 'Only for spacing'], 'correct' => 1],
        ['question' => 'Which Bootstrap version introduced dark mode?', 'options' => ['Bootstrap 4', 'Bootstrap 5.0', 'Bootstrap 5.3', 'Bootstrap 6'], 'correct' => 2],
        ['question' => 'What does .d-md-block do?', 'options' => ['Display block always', 'Display block on medium+ screens', 'Display block on mobile', 'Hide on medium'], 'correct' => 1],
        ['question' => 'What does .d-lg-none do?', 'options' => ['Hide always', 'Hide on large+ screens', 'Show on large', 'Display none always'], 'correct' => 1],
        ['question' => 'What is container-fluid?', 'options' => ['Fixed width', 'Full width container', 'Centered container', 'Fluid typography'], 'correct' => 1],
        ['question' => 'What is container-md?', 'options' => ['Medium padding', 'Responsive container at md breakpoint', 'Medium width', 'Fixed medium'], 'correct' => 1],
        ['question' => 'What does .w-50 do?', 'options' => ['Width 50px', 'Width 50%', 'Weight 50', 'Wrap 50'], 'correct' => 1],
        ['question' => 'What does .w-100 do?', 'options' => ['Width 100px', 'Width 100%', 'Weight 100', 'Wrap 100'], 'correct' => 1],
        ['question' => 'What does .w-auto do?', 'options' => ['Width 0', 'Width 100%', 'Automatic width', 'Width 50%'], 'correct' => 2],
        ['question' => 'What does .position-relative do?', 'options' => ['position: absolute', 'position: relative', 'position: fixed', 'position: static'], 'correct' => 1],
        ['question' => 'What does .sticky-top do?', 'options' => ['Fixed position', 'Sticky top positioning', 'Absolute top', 'Relative top'], 'correct' => 1],
        ['question' => 'What does .fixed-top do?', 'options' => ['Sticky top', 'Fixed to top', 'Absolute top', 'Relative top'], 'correct' => 1],
        ['question' => 'Does Bootstrap have a z-index system?', 'options' => ['No', 'Yes, predefined values', 'Only in BS5', 'Only for modals'], 'correct' => 1],
        ['question' => 'What utility adds borders?', 'options' => ['.border', '.border-1', '.b-1', '.outline'], 'correct' => 0],
        ['question' => 'What utility adds shadows?', 'options' => ['.shadow', '.box-shadow', '.shade', '.depth'], 'correct' => 0],
        ['question' => 'What does .overflow-hidden do?', 'options' => ['overflow: visible', 'overflow: hidden', 'overflow: scroll', 'overflow: auto'], 'correct' => 1],
        ['question' => 'What does .overflow-auto do?', 'options' => ['overflow: hidden', 'overflow: visible', 'overflow: auto', 'overflow: scroll'], 'correct' => 2],
        ['question' => 'What is the ratio utility for?', 'options' => ['Font ratios', 'Aspect ratio containers', 'Grid ratios', 'Spacing ratios'], 'correct' => 1],
        ['question' => 'What class creates a 16:9 ratio?', 'options' => ['.ratio-16x9', '.aspect-16-9', '.ratio-16-9', '.ar-16-9'], 'correct' => 0],
        ['question' => 'What does .visible do?', 'options' => ['Shows element', 'Bootstrap 5 removed it', 'Hides element', 'Toggles visibility'], 'correct' => 1],
        ['question' => 'What library does Bootstrap use for dropdowns?', 'options' => ['jQuery', 'Popper.js', 'Bootstrap.js only', 'No library'], 'correct' => 1],
        ['question' => 'Does Bootstrap 5 require jQuery?', 'options' => ['Yes', 'No', 'Optional', 'Only for some components'], 'correct' => 1],
        ['question' => 'What component is scrollspy?', 'options' => ['Scroll button', 'Navigation highlighting based on scroll', 'Scroll animation', 'Lazy loading'], 'correct' => 1],
        ['question' => 'What is a toast component?', 'options' => ['Button', 'Non-blocking notification', 'Modal', 'Alert'], 'correct' => 1],
        ['question' => 'What is the placeholder component for?', 'options' => ['Form placeholders', 'Loading animation/skeleton', 'Empty states', 'Image placeholders'], 'correct' => 1],
        ['question' => 'Can you customize spacing utilities?', 'options' => ['No', 'Yes, via Sass', 'Only in BS5', 'Only CSS'], 'correct' => 1],
        ['question' => 'What does .mb-0 do?', 'options' => ['Margin bottom 0', 'Margin 0', 'Padding bottom 0', 'Border 0'], 'correct' => 0],
        ['question' => 'What does .px-3 do?', 'options' => ['Padding 3', 'Padding left and right 3', 'Padding x-axis 3', 'Position x 3'], 'correct' => 1],
        ['question' => 'What does .py-4 do?', 'options' => ['Padding 4', 'Padding top and bottom 4', 'Padding y-axis 4', 'Position y 4'], 'correct' => 1],
        ['question' => 'What does .mx-auto do?', 'options' => ['Margin auto', 'Margin left and right auto', 'Max width auto', 'Mix auto'], 'correct' => 1],
        ['question' => 'What does .text-truncate do?', 'options' => ['Removes text', 'Truncates text with ellipsis', 'Shortens text', 'Hides text'], 'correct' => 1],
        ['question' => 'What does .text-nowrap do?', 'options' => ['Wraps text', 'Prevents text wrapping', 'No text', 'Narrow text'], 'correct' => 1],
    ]],
    ['label' => 'Advanced', 'questions' => [
        ['question' => 'What Sass modules does Bootstrap use?', 'options' => ['@import only', '@use and @forward', '@include only', 'No modules'], 'correct' => 1],
        ['question' => 'Can you customize individual component variables?', 'options' => ['No', 'Yes, via Sass variables', 'Only colors', 'Only spacing'], 'correct' => 1],
        ['question' => 'How do you create custom components in Bootstrap style?', 'options' => ['Copy HTML', 'Follow Bootstrap Sass patterns', 'Use inline styles', 'JavaScript only'], 'correct' => 1],
        ['question' => 'Does Bootstrap 5 support RTL?', 'options' => ['No', 'Yes, built-in', 'Only with plugin', 'Only in BS6'], 'correct' => 1],
        ['question' => 'Does Bootstrap 5.1+ support CSS Grid?', 'options' => ['No', 'Yes, opt-in grid mode', 'Only flexbox', 'Only in BS6'], 'correct' => 1],
        ['question' => 'What is Bootstrap Icons?', 'options' => ['Font Awesome', 'Official Bootstrap icon library', 'Image sprites', 'CSS shapes'], 'correct' => 1],
        ['question' => 'How does Bootstrap 5 implement theming?', 'options' => ['Sass only', 'CSS custom properties', 'JavaScript', 'Inline styles'], 'correct' => 1],
        ['question' => 'How can you optimize Bootstrap bundle size?', 'options' => ['Use full bundle', 'Import only needed components', 'Compress CSS', 'Use CDN'], 'correct' => 1],
        ['question' => 'What are data-bs-* attributes for?', 'options' => ['Styling', 'JavaScript plugin initialization', 'SEO', 'Accessibility'], 'correct' => 1],
        ['question' => 'Can you initialize Bootstrap plugins via JavaScript?', 'options' => ['No', 'Yes', 'Only data attributes', 'Only in BS4'], 'correct' => 1],
        ['question' => 'How do you extend Bootstrap plugins?', 'options' => ['Cannot extend', 'Extend plugin classes', 'Copy source', 'Fork repository'], 'correct' => 1],
        ['question' => 'What event fires when modal is shown?', 'options' => ['show.bs.modal', 'shown.bs.modal', 'open.bs.modal', 'display.bs.modal'], 'correct' => 1],
        ['question' => 'What event fires before modal shows?', 'options' => ['before.bs.modal', 'show.bs.modal', 'opening.bs.modal', 'pre.bs.modal'], 'correct' => 1],
        ['question' => 'What event fires when modal is hidden?', 'options' => ['hide.bs.modal', 'hidden.bs.modal', 'close.bs.modal', 'closed.bs.modal'], 'correct' => 1],
        ['question' => 'Are Bootstrap components accessible by default?', 'options' => ['No', 'Yes, ARIA patterns included', 'Only in BS5', 'Requires plugin'], 'correct' => 1],
        ['question' => 'Can you use Bootstrap with React?', 'options' => ['No', 'Yes, with react-bootstrap', 'Only vanilla JS', 'Not recommended'], 'correct' => 1],
        ['question' => 'Can you use Bootstrap with Angular?', 'options' => ['No', 'Yes, with ng-bootstrap', 'Only vanilla JS', 'Not recommended'], 'correct' => 1],
        ['question' => 'Can you use Bootstrap with Vue?', 'options' => ['No', 'Yes, with bootstrap-vue', 'Only vanilla JS', 'Not recommended'], 'correct' => 1],
        ['question' => 'What changed in Bootstrap 5 from 4?', 'options' => ['Nothing', 'Dropped jQuery, added utilities, updated components', 'Only colors', 'Only grid'], 'correct' => 1],
        ['question' => 'Was jQuery removed in Bootstrap 5?', 'options' => ['No, still required', 'Yes, vanilla JS', 'Optional', 'Only for some components'], 'correct' => 1],
        ['question' => 'What replaced .form-group in Bootstrap 5?', 'options' => ['.form-control', 'Margin utilities', 'Nothing', '.group'], 'correct' => 1],
        ['question' => 'What replaced .form-row in Bootstrap 5?', 'options' => ['.form-group', '.row with .g-* gutters', '.form-line', 'Nothing'], 'correct' => 1],
        ['question' => 'What replaced .jumbotron in Bootstrap 5?', 'options' => ['New component', 'Custom utility classes', '.hero', '.showcase'], 'correct' => 1],
        ['question' => 'Were .ml-* and .mr-* classes renamed in Bootstrap 5?', 'options' => ['No', 'Yes, to .ms-* and .me-*', 'Removed', 'Deprecated'], 'correct' => 1],
        ['question' => 'What does .ms-3 mean in Bootstrap 5?', 'options' => ['Margin left 3', 'Margin start 3', 'Margin 3', 'Margin spacing 3'], 'correct' => 1],
        ['question' => 'What does .me-2 mean in Bootstrap 5?', 'options' => ['Margin right 2', 'Margin end 2', 'Margin 2', 'Margin edge 2'], 'correct' => 1],
        ['question' => 'Does Bootstrap 5 use libsass or dart-sass?', 'options' => ['libsass', 'dart-sass', 'node-sass', 'ruby-sass'], 'correct' => 1],
        ['question' => 'Can you use Bootstrap without Sass?', 'options' => ['No', 'Yes, use compiled CSS', 'Only in development', 'Not recommended'], 'correct' => 1],
        ['question' => 'What is the Bootstrap reboot?', 'options' => ['Reset CSS', 'Normalize + opinionated styles', 'Bootstrap restart', 'Version update'], 'correct' => 1],
        ['question' => 'Can you disable Bootstrap reboot?', 'options' => ['No', 'Yes, don\'t import it', 'Only in BS4', 'Not recommended'], 'correct' => 1],
        ['question' => 'What is the Bootstrap utilities API?', 'options' => ['JavaScript API', 'Sass-based utility generator', 'REST API', 'Plugin API'], 'correct' => 1],
        ['question' => 'Can you add custom utilities via utilities API?', 'options' => ['No', 'Yes', 'Only in BS6', 'Only colors'], 'correct' => 1],
        ['question' => 'Does Bootstrap support print styles?', 'options' => ['No', 'Yes', 'Only in BS4', 'Requires plugin'], 'correct' => 1],
        ['question' => 'What is the default Bootstrap font?', 'options' => ['Arial', 'Native font stack', 'Roboto', 'Helvetica'], 'correct' => 1],
        ['question' => 'Can you customize the Bootstrap color palette?', 'options' => ['No', 'Yes, via Sass', 'Only primary color', 'Only in BS5'], 'correct' => 1],
    ]],
    ['label' => 'Expert', 'questions' => [
        ['question' => 'How does Bootstrap generate utilities?', 'options' => ['Manual CSS', 'Sass maps and loops', 'JavaScript', 'Preprocessor'], 'correct' => 1],
        ['question' => 'What are Sass maps in Bootstrap?', 'options' => ['Navigation', 'Data structures for configuration', 'Stylesheets', 'Mixins'], 'correct' => 1],
        ['question' => 'What are Bootstrap mixins?', 'options' => ['Variables', 'Reusable Sass code blocks', 'Utilities', 'Components'], 'correct' => 1],
        ['question' => 'How are responsive utilities generated?', 'options' => ['Manual code', 'Loop over breakpoints map', 'JavaScript', 'CSS Grid'], 'correct' => 1],
        ['question' => 'What is the utilities map in Bootstrap?', 'options' => ['Navigation map', 'Configuration for utility generation', 'Site map', 'Component map'], 'correct' => 1],
        ['question' => 'Can you add responsive variants to custom utilities?', 'options' => ['No', 'Yes, via utilities API', 'Only default utilities', 'Requires plugin'], 'correct' => 1],
        ['question' => 'Can you add print variants to utilities?', 'options' => ['No', 'Yes, via utilities API', 'Only default utilities', 'Not supported'], 'correct' => 1],
        ['question' => 'Can you add state variants (hover, focus) to utilities?', 'options' => ['No', 'Yes, via utilities API', 'Only default utilities', 'Requires JavaScript'], 'correct' => 1],
        ['question' => 'How does CSS specificity work in Bootstrap?', 'options' => ['Random', 'Controlled via Sass organization', 'High specificity', 'Inline styles'], 'correct' => 1],
        ['question' => 'What is critical CSS for Bootstrap?', 'options' => ['All CSS', 'Above-fold CSS extracted', 'Important CSS', 'Core CSS'], 'correct' => 1],
        ['question' => 'What is PurgeCSS?', 'options' => ['CSS validator', 'Removes unused CSS', 'CSS optimizer', 'CSS minifier'], 'correct' => 1],
        ['question' => 'Can you use PurgeCSS with Bootstrap?', 'options' => ['No', 'Yes, for production optimization', 'Only BS4', 'Not recommended'], 'correct' => 1],
        ['question' => 'What module format does Bootstrap JS use?', 'options' => ['CommonJS only', 'ES modules and UMD', 'AMD only', 'No modules'], 'correct' => 1],
        ['question' => 'What is BaseComponent in Bootstrap JS?', 'options' => ['HTML element', 'Base class for plugins', 'Component library', 'Framework'], 'correct' => 1],
        ['question' => 'How do you create a custom Bootstrap plugin?', 'options' => ['Copy code', 'Extend BaseComponent', 'Write from scratch', 'Fork repository'], 'correct' => 1],
        ['question' => 'What ARIA patterns does Bootstrap implement?', 'options' => ['None', 'WAI-ARIA for components', 'Custom patterns', 'Basic patterns'], 'correct' => 1],
        ['question' => 'Are Bootstrap modals keyboard accessible?', 'options' => ['No', 'Yes, with keyboard trap', 'Only with plugin', 'Manually add'], 'correct' => 1],
        ['question' => 'Do Bootstrap dropdowns follow ARIA practices?', 'options' => ['No', 'Yes, with ARIA attributes', 'Partially', 'Requires manual setup'], 'correct' => 1],
        ['question' => 'How does Bootstrap compare to Tailwind in performance?', 'options' => ['Always faster', 'Depends on usage and purging', 'Always slower', 'Same'], 'correct' => 1],
        ['question' => 'How does Bootstrap bundle size compare to others?', 'options' => ['Smallest', 'Medium, depends on tree-shaking', 'Largest', 'Same as all'], 'correct' => 1],
        ['question' => 'Can Bootstrap work with CSP nonces?', 'options' => ['No', 'Yes, with configuration', 'Only BS5', 'Not supported'], 'correct' => 1],
        ['question' => 'What is data-bs-theme attribute?', 'options' => ['Styling', 'Theme mode control', 'Plugin setting', 'Data attribute'], 'correct' => 1],
        ['question' => 'How are theme modes implemented in Bootstrap 5.3+?', 'options' => ['JavaScript only', 'CSS variables and data attribute', 'Sass only', 'Not supported'], 'correct' => 1],
        ['question' => 'Does Bootstrap provide print utilities?', 'options' => ['No', 'Yes, .d-print-* classes', 'Only in BS4', 'Requires plugin'], 'correct' => 1],
        ['question' => 'Can you customize scroll behavior in Bootstrap?', 'options' => ['No', 'Yes, via Sass and CSS', 'Only JavaScript', 'Not supported'], 'correct' => 1],
        ['question' => 'What is smooth scrolling in Bootstrap?', 'options' => ['Animation', 'CSS scroll-behavior', 'JavaScript scroll', 'Not supported'], 'correct' => 1],
        ['question' => 'Does Bootstrap support reduced motion preferences?', 'options' => ['No', 'Yes, via prefers-reduced-motion', 'Only BS5', 'Requires plugin'], 'correct' => 1],
        ['question' => 'How does Bootstrap handle focus management?', 'options' => ['No handling', 'Focus trap in modals, focus indicators', 'JavaScript only', 'Manual setup'], 'correct' => 1],
        ['question' => 'What is the Bootstrap container query strategy?', 'options' => ['Not supported', 'Future consideration, uses media queries', 'Fully supported', 'Plugin available'], 'correct' => 1],
        ['question' => 'Can Bootstrap be used with Web Components?', 'options' => ['No', 'Yes, with considerations', 'Only BS5', 'Not recommended'], 'correct' => 1],
        ['question' => 'How does Bootstrap handle browser compatibility?', 'options' => ['No support', 'Modern browsers + graceful degradation', 'IE11 only', 'All browsers'], 'correct' => 1],
        ['question' => 'What preprocessor does Bootstrap use?', 'options' => ['Less', 'Sass', 'PostCSS', 'Stylus'], 'correct' => 1],
        ['question' => 'Can you use Bootstrap with PostCSS?', 'options' => ['No', 'Yes, after Sass compilation', 'Replace Sass', 'Not needed'], 'correct' => 1],
        ['question' => 'What is Bootstrap\'s approach to vendor prefixes?', 'options' => ['Manual prefixes', 'Autoprefixer via build', 'No prefixes', 'Sass mixins'], 'correct' => 1],
        ['question' => 'How does Bootstrap handle breakpoint calculations?', 'options' => ['Fixed values', 'Sass functions and maps', 'JavaScript', 'CSS calc'], 'correct' => 1],
    ]],
];
require_once __DIR__ . '/quiz-engine.php';
