<?php
$page_title = 'C Quiz – 100 Levels – CodeFoundry';
$active_page = 'training';
$quiz_title  = 'C';
$quiz_slug   = 'c-lang';
$quiz_tiers  = [
    ['label' => 'Introduction', 'questions' => [
        ['question' => 'Who created the C programming language?', 'options' => ['Bjarne Stroustrup', 'Dennis Ritchie', 'Ken Thompson', 'Brian Kernighan'], 'correct' => 1],
        ['question' => 'Which is the first compilation step?', 'options' => ['Linking', 'Assembly', 'Preprocessing', 'Compilation'], 'correct' => 2],
        ['question' => 'What is the correct signature of main()?', 'options' => ['void main()', 'int main()', 'main()', 'function main()'], 'correct' => 1],
        ['question' => 'Which function outputs formatted text?', 'options' => ['print()', 'printf()', 'cout', 'echo'], 'correct' => 1],
        ['question' => 'Which function reads formatted input?', 'options' => ['scanf()', 'input()', 'read()', 'cin'], 'correct' => 0],
        ['question' => 'Which directive includes a header file?', 'options' => ['#import', '#include', '#using', '#require'], 'correct' => 1],
        ['question' => 'Which data type stores a single character?', 'options' => ['string', 'char', 'character', 'byte'], 'correct' => 1],
        ['question' => 'Which format specifier is for integers?', 'options' => ['%s', '%d', '%c', '%f'], 'correct' => 1],
        ['question' => 'Which format specifier is for floats?', 'options' => ['%d', '%i', '%f', '%lf'], 'correct' => 2],
        ['question' => 'Which format specifier is for characters?', 'options' => ['%s', '%c', '%ch', '%char'], 'correct' => 1],
        ['question' => 'Which operator is for addition?', 'options' => ['+', 'add', 'plus', '&'], 'correct' => 0],
        ['question' => 'Which operator checks equality?', 'options' => ['=', '==', 'eq', 'equals'], 'correct' => 1],
        ['question' => 'Which is the logical AND operator?', 'options' => ['&', 'AND', '&&', 'and'], 'correct' => 2],
        ['question' => 'Which is the logical OR operator?', 'options' => ['|', 'OR', '||', 'or'], 'correct' => 2],
        ['question' => 'Which keyword starts a conditional?', 'options' => ['check', 'if', 'when', 'condition'], 'correct' => 1],
        ['question' => 'Which keyword handles multiple cases?', 'options' => ['select', 'switch', 'case', 'choose'], 'correct' => 1],
        ['question' => 'Which loop executes at least once?', 'options' => ['for', 'while', 'do-while', 'loop'], 'correct' => 2],
        ['question' => 'Which statement exits a loop?', 'options' => ['exit', 'break', 'stop', 'end'], 'correct' => 1],
        ['question' => 'Which statement skips to next iteration?', 'options' => ['skip', 'next', 'continue', 'pass'], 'correct' => 2],
        ['question' => 'How do you declare an array of 10 ints?', 'options' => ['int arr[10]', 'array int[10]', 'int[10] arr', 'array arr[10]'], 'correct' => 0],
        ['question' => 'What terminates a string in C?', 'options' => ['\\n', '\\0', 'NULL', 'EOF'], 'correct' => 1],
        ['question' => 'Which keyword makes a variable unchangeable?', 'options' => ['final', 'const', 'static', 'readonly'], 'correct' => 1],
        ['question' => 'Which comment style is single-line?', 'options' => ['<!-- -->', '//', '/* */', '#'], 'correct' => 1],
        ['question' => 'Which operator returns the size in bytes?', 'options' => ['size()', 'sizeof', 'length()', 'bytes()'], 'correct' => 1],
        ['question' => 'How do you cast int to float?', 'options' => ['(float)x', 'float(x)', 'x.float', 'cast(x, float)'], 'correct' => 0],
        ['question' => 'Which header provides math functions?', 'options' => ['stdlib.h', 'math.h', 'numeric.h', 'calc.h'], 'correct' => 1],
        ['question' => 'Which format specifier is for long double?', 'options' => ['%f', '%lf', '%Lf', '%ld'], 'correct' => 2],
        ['question' => 'Which keyword makes a variable unsigned?', 'options' => ['positive', 'unsigned', 'uint', 'natural'], 'correct' => 1],
    ]],
    ['label' => 'Beginner', 'questions' => [
        ['question' => 'How do you declare a function that returns int?', 'options' => ['function int name()', 'int name()', 'def name() -> int', 'name() int'], 'correct' => 1],
        ['question' => 'Which keyword makes a function recursive?', 'options' => ['recursive', 'No keyword needed', 'self', 'repeat'], 'correct' => 1],
        ['question' => 'How do you declare a pointer to int?', 'options' => ['int *ptr', 'pointer int ptr', 'int ptr*', '*int ptr'], 'correct' => 0],
        ['question' => 'Which operator dereferences a pointer?', 'options' => ['&', '*', '->', '.'], 'correct' => 1],
        ['question' => 'Which operator gets the address of a variable?', 'options' => ['*', '@', '&', 'addr'], 'correct' => 2],
        ['question' => 'What is the value of a NULL pointer?', 'options' => ['1', '0', '-1', 'Undefined'], 'correct' => 1],
        ['question' => 'Which function gets string length?', 'options' => ['length()', 'strlen()', 'size()', 'len()'], 'correct' => 1],
        ['question' => 'Which function copies a string?', 'options' => ['copy()', 'strcpy()', 'strdup()', 'memcpy()'], 'correct' => 1],
        ['question' => 'Which function compares two strings?', 'options' => ['compare()', 'strcmp()', 'strcompare()', 'equals()'], 'correct' => 1],
        ['question' => 'Which function allocates memory?', 'options' => ['alloc()', 'malloc()', 'new()', 'create()'], 'correct' => 1],
        ['question' => 'Which function allocates and zeroes memory?', 'options' => ['calloc()', 'zalloc()', 'malloc_zero()', 'new_zero()'], 'correct' => 0],
        ['question' => 'Which function resizes allocated memory?', 'options' => ['resize()', 'realloc()', 'expand()', 'grow()'], 'correct' => 1],
        ['question' => 'Which function frees allocated memory?', 'options' => ['delete()', 'free()', 'release()', 'dealloc()'], 'correct' => 1],
        ['question' => 'How do you define a structure?', 'options' => ['struct name { }', 'structure name { }', 'class name { }', 'record name { }'], 'correct' => 0],
        ['question' => 'Which operator accesses struct members?', 'options' => ['::', '->', '.', '->*'], 'correct' => 2],
        ['question' => 'Which operator accesses pointer-to-struct members?', 'options' => ['.', '->', '::', '*'], 'correct' => 1],
        ['question' => 'Which keyword creates a type alias?', 'options' => ['alias', 'typedef', 'type', 'define'], 'correct' => 1],
        ['question' => 'Which keyword defines named constants?', 'options' => ['const', 'enum', 'define', 'constant'], 'correct' => 1],
        ['question' => 'What is a union?', 'options' => ['Multiple structs', 'Shared memory for members', 'Array of structs', 'Linked structs'], 'correct' => 1],
        ['question' => 'Which function opens a file?', 'options' => ['open()', 'fopen()', 'file_open()', 'fileopen()'], 'correct' => 1],
        ['question' => 'Which function closes a file?', 'options' => ['close()', 'fclose()', 'file_close()', 'fileclose()'], 'correct' => 1],
        ['question' => 'How do you access command-line arguments?', 'options' => ['args[]', 'argv[]', 'arguments[]', 'cmdline[]'], 'correct' => 1],
        ['question' => 'Which is the bitwise AND operator?', 'options' => ['&&', '&', 'AND', 'and'], 'correct' => 1],
        ['question' => 'Which is the bitwise OR operator?', 'options' => ['||', '|', 'OR', 'or'], 'correct' => 1],
        ['question' => 'Which is the bitwise XOR operator?', 'options' => ['^', 'xor', 'XOR', '^^'], 'correct' => 0],
        ['question' => 'Which directive defines a macro?', 'options' => ['#macro', '#define', '#const', '#set'], 'correct' => 1],
        ['question' => 'Which directive checks if defined?', 'options' => ['#if', '#ifdef', '#check', '#defined'], 'correct' => 1],
        ['question' => 'How do you create a 2D array of 3x4 ints?', 'options' => ['int arr[3][4]', 'int arr[3,4]', 'int[3][4] arr', 'array int[3][4]'], 'correct' => 0],
    ]],
    ['label' => 'Intermediate', 'questions' => [
        ['question' => 'What is a pointer to pointer?', 'options' => ['Invalid syntax', 'Pointer storing address of another pointer', 'Array of pointers', 'Struct member'], 'correct' => 1],
        ['question' => 'How do you declare a function pointer?', 'options' => ['int (*fptr)()', 'int *fptr()', 'pointer fptr()', 'function *fptr'], 'correct' => 0],
        ['question' => 'What is a void pointer?', 'options' => ['Null pointer', 'Generic pointer type', 'Invalid pointer', 'Function pointer'], 'correct' => 1],
        ['question' => 'What does const int *ptr mean?', 'options' => ['Constant pointer', 'Pointer to constant int', 'Both constant', 'Invalid'], 'correct' => 1],
        ['question' => 'What is an array of pointers?', 'options' => ['Pointer to array', 'Array where each element is a pointer', 'Multi-dimensional array', 'Struct array'], 'correct' => 1],
        ['question' => 'How do you dynamically allocate a 2D array?', 'options' => ['Single malloc', 'Array of pointers, each malloc\'d', 'Not possible', 'calloc only'], 'correct' => 1],
        ['question' => 'What is a linked list node?', 'options' => ['Array element', 'Struct with data and pointer to next', 'Function pointer', 'Union'], 'correct' => 1],
        ['question' => 'What is a doubly linked list?', 'options' => ['Two lists', 'Node with next and prev pointers', 'Circular list', 'Array-based list'], 'correct' => 1],
        ['question' => 'What is a self-referential structure?', 'options' => ['Recursive function', 'Struct with pointer to same type', 'Union', 'Enum'], 'correct' => 1],
        ['question' => 'What are bit fields?', 'options' => ['Bitwise operators', 'Struct members with bit-level size', 'Binary arrays', 'Flags'], 'correct' => 1],
        ['question' => 'What causes struct padding?', 'options' => ['Compiler error', 'Memory alignment requirements', 'Array overflow', 'Pointer arithmetic'], 'correct' => 1],
        ['question' => 'What is the stack in memory?', 'options' => ['Heap space', 'Function call and local variable storage', 'Global data', 'Code segment'], 'correct' => 1],
        ['question' => 'What is the heap in memory?', 'options' => ['Stack space', 'Dynamic memory allocation area', 'Global data', 'Code segment'], 'correct' => 1],
        ['question' => 'What is static storage duration?', 'options' => ['Temporary', 'Exists for program lifetime', 'Heap allocated', 'Stack allocated'], 'correct' => 1],
        ['question' => 'What does extern declare?', 'options' => ['Local variable', 'Variable defined elsewhere', 'Constant', 'Function'], 'correct' => 1],
        ['question' => 'What does inline suggest to compiler?', 'options' => ['Make function static', 'Expand function code at call site', 'Optimize loop', 'Use assembly'], 'correct' => 1],
        ['question' => 'What are variadic functions?', 'options' => ['Multiple returns', 'Variable number of arguments', 'Template functions', 'Recursive functions'], 'correct' => 1],
        ['question' => 'Which header defines va_list?', 'options' => ['stdio.h', 'stdarg.h', 'stdlib.h', 'var.h'], 'correct' => 1],
        ['question' => 'What does signal() do?', 'options' => ['Send signal', 'Register signal handler', 'Block signal', 'Ignore signal'], 'correct' => 1],
        ['question' => 'What is setjmp/longjmp for?', 'options' => ['File operations', 'Non-local jumps/exception-like handling', 'String processing', 'Math operations'], 'correct' => 1],
        ['question' => 'What is the # operator in macros?', 'options' => ['Concatenation', 'Stringification', 'Comment', 'Conditional'], 'correct' => 1],
        ['question' => 'What is the ## operator in macros?', 'options' => ['Stringification', 'Token pasting/concatenation', 'Comment', 'Arithmetic'], 'correct' => 1],
        ['question' => 'What are header guards for?', 'options' => ['Security', 'Preventing multiple inclusion', 'Optimization', 'Documentation'], 'correct' => 1],
        ['question' => 'What is separate compilation?', 'options' => ['Compiling twice', 'Compiling source files independently', 'Using multiple compilers', 'Parallel compilation'], 'correct' => 1],
        ['question' => 'What does a Makefile define?', 'options' => ['Constants', 'Build rules and dependencies', 'Functions', 'Variables only'], 'correct' => 1],
        ['question' => 'What is gdb?', 'options' => ['Compiler', 'Debugger', 'Linker', 'Profiler'], 'correct' => 1],
        ['question' => 'What does fseek() do?', 'options' => ['Read file', 'Set file position', 'Close file', 'Open file'], 'correct' => 1],
        ['question' => 'What does ftell() return?', 'options' => ['File size', 'Current file position', 'Number of lines', 'File permissions'], 'correct' => 1],
    ]],
    ['label' => 'Advanced', 'questions' => [
        ['question' => 'What is undefined behavior (UB)?', 'options' => ['Compiler warning', 'Behavior not specified by standard', 'Runtime error', 'Syntax error'], 'correct' => 1],
        ['question' => 'What is the strict aliasing rule?', 'options' => ['Naming convention', 'Restriction on pointer type punning', 'Memory allocation rule', 'Function calling rule'], 'correct' => 1],
        ['question' => 'What does volatile keyword indicate?', 'options' => ['Constant', 'Value may change unexpectedly', 'Temporary', 'Pointer'], 'correct' => 1],
        ['question' => 'What does restrict keyword do?', 'options' => ['Limits scope', 'Indicates no pointer aliasing', 'Makes constant', 'Prevents inheritance'], 'correct' => 1],
        ['question' => 'What is memory alignment?', 'options' => ['Sorting memory', 'Starting address divisible by size', 'Zero padding', 'Heap organization'], 'correct' => 1],
        ['question' => 'Which header defines atomic operations?', 'options' => ['atomic.h', 'stdatomic.h', 'thread.h', 'sync.h'], 'correct' => 1],
        ['question' => 'What are pthreads?', 'options' => ['Processes', 'POSIX threads', 'Pointers', 'Protocols'], 'correct' => 1],
        ['question' => 'What is a mutex?', 'options' => ['Memory unit', 'Mutual exclusion lock', 'Function', 'Macro'], 'correct' => 1],
        ['question' => 'What is a condition variable?', 'options' => ['Boolean', 'Thread synchronization primitive', 'Loop condition', 'Preprocessor condition'], 'correct' => 1],
        ['question' => 'What does mmap() do?', 'options' => ['Allocate heap', 'Memory-map file or device', 'Merge memory', 'Move memory'], 'correct' => 1],
        ['question' => 'What is a pipe in IPC?', 'options' => ['File type', 'Unidirectional data channel', 'Function pointer', 'Data structure'], 'correct' => 1],
        ['question' => 'What is shared memory in IPC?', 'options' => ['Heap', 'Memory accessible by multiple processes', 'Stack', 'Global variables'], 'correct' => 1],
        ['question' => 'What is endianness?', 'options' => ['End of file', 'Byte order in memory', 'String termination', 'Loop ending'], 'correct' => 1],
        ['question' => 'What is big-endian?', 'options' => ['Large files', 'Most significant byte first', 'Least significant byte first', 'Random order'], 'correct' => 1],
        ['question' => 'What is integer overflow in signed int?', 'options' => ['Defined behavior', 'Undefined behavior', 'Wraps around', 'Throws error'], 'correct' => 1],
        ['question' => 'What is pointer provenance?', 'options' => ['Pointer size', 'Origin/validity of pointer', 'Pointer type', 'Pointer alignment'], 'correct' => 1],
        ['question' => 'Which C standard introduced VLAs?', 'options' => ['C89', 'C99', 'C11', 'C17'], 'correct' => 1],
        ['question' => 'What is a designated initializer?', 'options' => ['Default value', 'Explicit member initialization', 'Constructor', 'Macro'], 'correct' => 1],
        ['question' => 'What is a compound literal?', 'options' => ['String', 'Unnamed object created in expression', 'Array', 'Struct'], 'correct' => 1],
        ['question' => 'What is a flexible array member?', 'options' => ['Pointer array', 'Array as last struct member with no size', 'Dynamic array', 'Multi-dimensional array'], 'correct' => 1],
        ['question' => 'What is _Generic in C11?', 'options' => ['Template', 'Type-generic selection', 'Function', 'Macro'], 'correct' => 1],
        ['question' => 'What does _Static_assert do?', 'options' => ['Runtime check', 'Compile-time assertion', 'Optimization hint', 'Debug macro'], 'correct' => 1],
        ['question' => 'What is _Complex in C99?', 'options' => ['Difficult code', 'Complex number type', 'Struct type', 'Pointer type'], 'correct' => 1],
        ['question' => 'What is _Thread_local in C11?', 'options' => ['Global variable', 'Thread-local storage', 'Static variable', 'Heap variable'], 'correct' => 1],
        ['question' => 'What is mtx_t in C11?', 'options' => ['Matrix', 'Mutex type', 'Memory type', 'Macro type'], 'correct' => 1],
        ['question' => 'What is Annex K in C11?', 'options' => ['Appendix', 'Bounds-checking interfaces', 'Optional features', 'Deprecated features'], 'correct' => 1],
        ['question' => 'What does POSIX file I/O use?', 'options' => ['FILE*', 'File descriptors (int)', 'Handles', 'Streams'], 'correct' => 1],
        ['question' => 'What is a semaphore?', 'options' => ['Signal', 'Synchronization primitive', 'Memory segment', 'Function'], 'correct' => 1],
    ]],
    ['label' => 'Expert', 'questions' => [
        ['question' => 'What is the C abstract machine?', 'options' => ['Virtual machine', 'Theoretical execution model in standard', 'Compiler', 'Debugger'], 'correct' => 1],
        ['question' => 'What are sequence points in C99?', 'options' => ['Breakpoints', 'Points where side effects are complete', 'Line numbers', 'Function calls'], 'correct' => 1],
        ['question' => 'What replaced sequence points in C11?', 'options' => ['Breakpoints', 'Sequencing relationships', 'Barriers', 'Checkpoints'], 'correct' => 1],
        ['question' => 'What is unspecified behavior?', 'options' => ['Undefined', 'Multiple valid options, implementation picks', 'Error', 'Warning'], 'correct' => 1],
        ['question' => 'What is implementation-defined behavior?', 'options' => ['Undefined', 'Implementation must document choice', 'Standard defines it', 'Error'], 'correct' => 1],
        ['question' => 'What is LLVM IR?', 'options' => ['Infrared', 'Intermediate Representation', 'Internal Register', 'Instruction Rate'], 'correct' => 1],
        ['question' => 'What is constant folding?', 'options' => ['Const variables', 'Compile-time constant evaluation', 'Memory optimization', 'Loop optimization'], 'correct' => 1],
        ['question' => 'What is dead code elimination?', 'options' => ['Removing comments', 'Removing unreachable code', 'Removing bugs', 'Code cleanup'], 'correct' => 1],
        ['question' => 'What is loop unrolling?', 'options' => ['Removing loops', 'Duplicating loop body to reduce overhead', 'Optimizing conditions', 'Parallelizing loops'], 'correct' => 1],
        ['question' => 'What is vectorization?', 'options' => ['Array operations', 'SIMD optimization for parallel data', 'Pointer arithmetic', 'Memory alignment'], 'correct' => 1],
        ['question' => 'What is LTO?', 'options' => ['Late Type Optimization', 'Link-Time Optimization', 'Loop Transformation Optimization', 'Load Time Optimization'], 'correct' => 1],
        ['question' => 'What is PGO?', 'options' => ['Pointer Go Optimization', 'Profile-Guided Optimization', 'Parallel Generation Optimization', 'Pre-compile Generation Optimization'], 'correct' => 1],
        ['question' => 'What is AddressSanitizer (ASan)?', 'options' => ['Memory formatter', 'Memory error detector', 'Address allocator', 'Pointer validator'], 'correct' => 1],
        ['question' => 'What does Valgrind memcheck detect?', 'options' => ['Syntax errors', 'Memory leaks and errors', 'Logic errors', 'Performance issues'], 'correct' => 1],
        ['question' => 'What is CFI?', 'options' => ['C Function Interface', 'Control Flow Integrity', 'Code Format Instructions', 'Compiler Feature Integration'], 'correct' => 1],
        ['question' => 'What are stack canaries?', 'options' => ['Debug symbols', 'Stack overflow detection values', 'Function pointers', 'Return addresses'], 'correct' => 1],
        ['question' => 'What is ASLR?', 'options' => ['Array Sorting Logic', 'Address Space Layout Randomization', 'Automatic Stack Loading', 'Advanced Source Linking'], 'correct' => 1],
        ['question' => 'What is PIC?', 'options' => ['Picture', 'Position Independent Code', 'Pointer Instruction Code', 'Process Isolation Code'], 'correct' => 1],
        ['question' => 'What is GOT in ELF?', 'options' => ['Global Object Table', 'Global Offset Table', 'General Object Type', 'Goto Table'], 'correct' => 1],
        ['question' => 'What is PLT in ELF?', 'options' => ['Procedure Linkage Table', 'Pointer Lookup Table', 'Program Load Table', 'Process Link Table'], 'correct' => 0],
        ['question' => 'What is ELF format?', 'options' => ['Error Log File', 'Executable and Linkable Format', 'Extended Library File', 'Execution Link Format'], 'correct' => 1],
        ['question' => 'What is DWARF?', 'options' => ['Data format', 'Debugging information format', 'Executable format', 'Archive format'], 'correct' => 1],
        ['question' => 'What is System V AMD64 ABI?', 'options' => ['OS', 'Calling convention specification', 'Instruction set', 'Memory model'], 'correct' => 1],
        ['question' => 'What is the red zone in x86-64?', 'options' => ['Error region', '128-byte area below stack pointer', 'Heap overflow area', 'Code segment'], 'correct' => 1],
        ['question' => 'What is tail call optimization?', 'options' => ['Removing function end', 'Reusing stack frame for tail calls', 'Inlining last call', 'Loop optimization'], 'correct' => 1],
        ['question' => 'What are SSE intrinsics?', 'options' => ['String functions', 'SIMD instruction wrappers', 'System calls', 'Error handlers'], 'correct' => 1],
        ['question' => 'What is false sharing?', 'options' => ['Wrong pointer', 'Cache line contention in multithreading', 'Memory leak', 'Data race'], 'correct' => 1],
        ['question' => 'What is CAS operation?', 'options' => ['Cast', 'Compare-And-Swap', 'Compile And Store', 'Call And Switch'], 'correct' => 1],
        ['question' => 'What is the ABA problem?', 'options' => ['Syntax error', 'Lock-free data structure issue', 'Memory leak', 'Race condition'], 'correct' => 1],
        ['question' => 'What are hazard pointers?', 'options' => ['Null pointers', 'Safe memory reclamation technique', 'Dangerous pointers', 'Function pointers'], 'correct' => 1],
    ]],
];
require_once __DIR__ . '/quiz-engine.php';
