<?php
$page_title = 'C++ Quiz – 100 Levels – CodeFoundry';
$active_page = 'training';
$quiz_title  = 'C++';
$quiz_slug   = 'cpp';
$quiz_tiers  = [
    ['label' => 'Introduction', 'questions' => [
        ['question' => 'Who created C++?', 'options' => ['Dennis Ritchie', 'Bjarne Stroustrup', 'Ken Thompson', 'Linus Torvalds'], 'correct' => 1],
        ['question' => 'Which operator is used for input in C++?', 'options' => ['<<', '>>', 'cin', 'input'], 'correct' => 1],
        ['question' => 'Which operator is used for output in C++?', 'options' => ['<<', '>>', 'cout', 'output'], 'correct' => 0],
        ['question' => 'Which namespace contains standard C++ library?', 'options' => ['standard', 'std', 'stdlib', 'sys'], 'correct' => 1],
        ['question' => 'What type is the string class?', 'options' => ['char*', 'class', 'array', 'struct'], 'correct' => 1],
        ['question' => 'Which type is for boolean values?', 'options' => ['boolean', 'bool', 'bit', 'flag'], 'correct' => 1],
        ['question' => 'What is a reference in C++?', 'options' => ['Pointer', 'Alias to variable', 'Copy', 'Address'], 'correct' => 1],
        ['question' => 'What is function overloading?', 'options' => ['Too many functions', 'Same name, different parameters', 'Recursive function', 'Virtual function'], 'correct' => 1],
        ['question' => 'How do you specify a default argument?', 'options' => ['void f(int x = 5)', 'void f(default int x)', 'void f(int x := 5)', 'void f(int x default 5)'], 'correct' => 0],
        ['question' => 'What does inline suggest?', 'options' => ['Static function', 'Expand at call site', 'Private function', 'Template'], 'correct' => 1],
        ['question' => 'Which operator allocates memory in C++?', 'options' => ['malloc', 'new', 'alloc', 'create'], 'correct' => 1],
        ['question' => 'Which operator deallocates memory in C++?', 'options' => ['free', 'delete', 'remove', 'destroy'], 'correct' => 1],
        ['question' => 'Which keyword defines a class?', 'options' => ['struct', 'class', 'object', 'type'], 'correct' => 1],
        ['question' => 'What is the default visibility in a class?', 'options' => ['public', 'private', 'protected', 'internal'], 'correct' => 1],
        ['question' => 'What is a constructor?', 'options' => ['Destructor', 'Initialization function', 'Builder', 'Factory'], 'correct' => 1],
        ['question' => 'What is a destructor?', 'options' => ['Constructor', 'Cleanup function', 'Deleter', 'Finalizer'], 'correct' => 1],
        ['question' => 'What does the this pointer refer to?', 'options' => ['Parent object', 'Current object', 'Base class', 'Null'], 'correct' => 1],
        ['question' => 'What does const after a member function mean?', 'options' => ['Returns const', 'Doesn\'t modify object', 'Static function', 'Pure function'], 'correct' => 1],
        ['question' => 'What is a static member?', 'options' => ['Constant', 'Shared by all instances', 'Private', 'Immutable'], 'correct' => 1],
        ['question' => 'What is vector<T>?', 'options' => ['Math vector', 'Dynamic array container', 'Fixed array', 'Linked list'], 'correct' => 1],
        ['question' => 'What is range-based for loop syntax?', 'options' => ['for(int i=0; i<n; i++)', 'for(auto x : container)', 'for each x in container', 'foreach(x in container)'], 'correct' => 1],
        ['question' => 'What is nullptr?', 'options' => ['Zero', 'Null pointer literal', 'Void pointer', 'Invalid pointer'], 'correct' => 1],
        ['question' => 'What does auto keyword do?', 'options' => ['Automatic storage', 'Type deduction', 'Auto increment', 'Automation'], 'correct' => 1],
        ['question' => 'What is initializer list syntax?', 'options' => ['(1, 2, 3)', '{1, 2, 3}', '[1, 2, 3]', '<1, 2, 3>'], 'correct' => 1],
        ['question' => 'What is enum class?', 'options' => ['Enumeration', 'Scoped enumeration', 'Class of enums', 'Enum container'], 'correct' => 1],
        ['question' => 'What does constexpr indicate?', 'options' => ['Constant', 'Compile-time constant expression', 'Expression', 'Inline'], 'correct' => 1],
        ['question' => 'What file extension is common for C++ headers?', 'options' => ['.c', '.h or .hpp', '.cpp', '.cc'], 'correct' => 1],
        ['question' => 'What is #pragma once?', 'options' => ['Optimization', 'Include guard', 'Compiler directive', 'Preprocessor macro'], 'correct' => 1],
    ]],
    ['label' => 'Beginner', 'questions' => [
        ['question' => 'What is encapsulation in OOP?', 'options' => ['Wrapping data', 'Hiding implementation details', 'Inheritance', 'Polymorphism'], 'correct' => 1],
        ['question' => 'What is inheritance?', 'options' => ['Code reuse', 'Deriving from base class', 'Polymorphism', 'Encapsulation'], 'correct' => 1],
        ['question' => 'What is polymorphism?', 'options' => ['Many forms', 'Different behavior via same interface', 'Inheritance', 'Templates'], 'correct' => 1],
        ['question' => 'What makes a function virtual?', 'options' => ['virtual keyword', 'pure keyword', 'abstract keyword', 'override keyword'], 'correct' => 0],
        ['question' => 'What is a vtable?', 'options' => ['Variable table', 'Virtual function table', 'Value table', 'Vector table'], 'correct' => 1],
        ['question' => 'How do you declare a pure virtual function?', 'options' => ['virtual void f()', 'virtual void f() = 0', 'pure virtual void f()', 'abstract void f()'], 'correct' => 1],
        ['question' => 'What is an abstract class?', 'options' => ['Class with no members', 'Class with pure virtual function', 'Template class', 'Final class'], 'correct' => 1],
        ['question' => 'What does override keyword indicate?', 'options' => ['New function', 'Overriding virtual function', 'Overloading', 'Final function'], 'correct' => 1],
        ['question' => 'What does final keyword do on a method?', 'options' => ['Last method', 'Cannot be overridden', 'Destructor', 'Static'], 'correct' => 1],
        ['question' => 'What is the diamond problem?', 'options' => ['Shape issue', 'Multiple inheritance ambiguity', 'Template issue', 'Pointer issue'], 'correct' => 1],
        ['question' => 'What is virtual inheritance?', 'options' => ['Virtual functions', 'Solving diamond problem', 'Abstract inheritance', 'Template inheritance'], 'correct' => 1],
        ['question' => 'What is a copy constructor?', 'options' => ['Copies class', 'Constructs from another object', 'Clones object', 'Assignment'], 'correct' => 1],
        ['question' => 'What is move semantics?', 'options' => ['Moving objects', 'Transferring resources', 'Copying', 'Deleting'], 'correct' => 1],
        ['question' => 'What is the rule of three?', 'options' => ['Three classes', 'Destructor, copy constructor, copy assignment', 'Three functions', 'Three members'], 'correct' => 1],
        ['question' => 'What is the rule of five?', 'options' => ['Five classes', 'Rule of three + move constructor/assignment', 'Five functions', 'Five parameters'], 'correct' => 1],
        ['question' => 'What is RAII?', 'options' => ['Design pattern', 'Resource Acquisition Is Initialization', 'Algorithm', 'Data structure'], 'correct' => 1],
        ['question' => 'What is unique_ptr?', 'options' => ['Unique value', 'Exclusive ownership smart pointer', 'Shared pointer', 'Raw pointer'], 'correct' => 1],
        ['question' => 'What is shared_ptr?', 'options' => ['Shared value', 'Shared ownership smart pointer', 'Unique pointer', 'Weak pointer'], 'correct' => 1],
        ['question' => 'What is weak_ptr?', 'options' => ['Weak reference', 'Non-owning shared_ptr observer', 'Unique pointer', 'Raw pointer'], 'correct' => 1],
        ['question' => 'What is a template?', 'options' => ['Design pattern', 'Generic programming mechanism', 'Class type', 'Function type'], 'correct' => 1],
        ['question' => 'What is vector in STL?', 'options' => ['Math vector', 'Dynamic array', 'Linked list', 'Hash table'], 'correct' => 1],
        ['question' => 'What is map in STL?', 'options' => ['Array', 'Associative container', 'List', 'Vector'], 'correct' => 1],
        ['question' => 'What is an iterator?', 'options' => ['Loop', 'Object to traverse container', 'Counter', 'Index'], 'correct' => 1],
        ['question' => 'What does std::sort do?', 'options' => ['Searches', 'Sorts a range', 'Filters', 'Maps'], 'correct' => 1],
        ['question' => 'What is a lambda expression?', 'options' => ['Greek letter', 'Anonymous function', 'Template', 'Macro'], 'correct' => 1],
        ['question' => 'What is std::function?', 'options' => ['Function pointer', 'General-purpose function wrapper', 'Lambda', 'Functor'], 'correct' => 1],
        ['question' => 'What is structured binding (C++17)?', 'options' => ['Struct definition', 'Decomposing tuples/structs', 'Binding functions', 'Template binding'], 'correct' => 1],
        ['question' => 'What does begin() return?', 'options' => ['First element', 'Iterator to first element', 'Index 0', 'Size'], 'correct' => 1],
    ]],
    ['label' => 'Intermediate', 'questions' => [
        ['question' => 'What is template specialization?', 'options' => ['Special template', 'Custom implementation for specific type', 'Template inheritance', 'Template alias'], 'correct' => 1],
        ['question' => 'What is partial template specialization?', 'options' => ['Incomplete template', 'Specialization for subset of parameters', 'Template default', 'Template overload'], 'correct' => 1],
        ['question' => 'What are variadic templates?', 'options' => ['Variable templates', 'Templates with variable arguments', 'Array templates', 'Optional templates'], 'correct' => 1],
        ['question' => 'What are fold expressions (C++17)?', 'options' => ['Folding code', 'Expanding parameter packs with operators', 'Template recursion', 'Lambda folding'], 'correct' => 1],
        ['question' => 'What is SFINAE?', 'options' => ['Error type', 'Substitution Failure Is Not An Error', 'Template rule', 'Compiler bug'], 'correct' => 1],
        ['question' => 'What is std::enable_if?', 'options' => ['Enabling features', 'Conditional type selection', 'Macro', 'Function'], 'correct' => 1],
        ['question' => 'What are type traits?', 'options' => ['Type properties', 'Compile-time type information', 'Runtime types', 'Type aliases'], 'correct' => 1],
        ['question' => 'What does decltype do?', 'options' => ['Declares type', 'Deduces type of expression', 'Defines type', 'Deletes type'], 'correct' => 1],
        ['question' => 'What is a trailing return type?', 'options' => ['Last return', 'auto f() -> int syntax', 'Multiple returns', 'Return after function'], 'correct' => 1],
        ['question' => 'What is perfect forwarding?', 'options' => ['Perfect copy', 'Preserving value category with std::forward', 'Optimal passing', 'Forward declaration'], 'correct' => 1],
        ['question' => 'What is a universal reference?', 'options' => ['Global reference', 'T&& in template (forwarding reference)', 'Rvalue reference', 'Const reference'], 'correct' => 1],
        ['question' => 'What is std::move?', 'options' => ['Moves memory', 'Casts to rvalue reference', 'Transfers ownership', 'Copies'], 'correct' => 1],
        ['question' => 'What is exception safety?', 'options' => ['Safe exceptions', 'Guarantees about program state', 'No exceptions', 'Catching all'], 'correct' => 1],
        ['question' => 'What is strong exception guarantee?', 'options' => ['No exceptions', 'Operation succeeds or no effect', 'Basic guarantee', 'No-throw'], 'correct' => 1],
        ['question' => 'What does noexcept specify?', 'options' => ['No exceptions thrown', 'Function doesn\'t throw', 'Catch all', 'Ignore exceptions'], 'correct' => 1],
        ['question' => 'What is std::optional (C++17)?', 'options' => ['Optional parameter', 'May or may not contain value', 'Nullable type', 'Pointer wrapper'], 'correct' => 1],
        ['question' => 'What is std::variant (C++17)?', 'options' => ['Variable', 'Type-safe union', 'Optional', 'Tuple'], 'correct' => 1],
        ['question' => 'What is std::any (C++17)?', 'options' => ['Any value', 'Type-safe container for any type', 'Void pointer', 'Variant'], 'correct' => 1],
        ['question' => 'What is std::string_view?', 'options' => ['String copy', 'Non-owning string reference', 'String pointer', 'Substring'], 'correct' => 1],
        ['question' => 'What is std::span (C++20)?', 'options' => ['Time span', 'Non-owning array view', 'Array copy', 'Range'], 'correct' => 1],
        ['question' => 'What is if constexpr?', 'options' => ['Constant if', 'Compile-time conditional', 'Runtime if', 'Const if'], 'correct' => 1],
        ['question' => 'What is std::tuple?', 'options' => ['Two elements', 'Fixed-size heterogeneous collection', 'Array', 'Vector'], 'correct' => 1],
        ['question' => 'What is std::pair?', 'options' => ['Two pairs', 'Two-element tuple', 'Array of 2', 'Double'], 'correct' => 1],
        ['question' => 'What does std::apply do?', 'options' => ['Applies function', 'Invokes function with tuple as arguments', 'Maps', 'Filters'], 'correct' => 1],
        ['question' => 'What are ranges (C++20)?', 'options' => ['Number ranges', 'Composable view/algorithm library', 'Iterators', 'Containers'], 'correct' => 1],
        ['question' => 'What is a coroutine (C++20)?', 'options' => ['Core routine', 'Suspendable function', 'Thread', 'Async function'], 'correct' => 1],
        ['question' => 'What is co_await?', 'options' => ['Wait function', 'Suspend until ready', 'Async wait', 'Thread wait'], 'correct' => 1],
        ['question' => 'What is co_yield?', 'options' => ['Return', 'Suspend and produce value', 'Yield thread', 'Generate'], 'correct' => 1],
    ]],
    ['label' => 'Advanced', 'questions' => [
        ['question' => 'What is template metaprogramming?', 'options' => ['Meta templates', 'Compile-time computation with templates', 'Runtime templates', 'Template optimization'], 'correct' => 1],
        ['question' => 'What is CRTP?', 'options' => ['Create Template', 'Curiously Recurring Template Pattern', 'Class Runtime Type', 'Compile-time Polymorphism'], 'correct' => 1],
        ['question' => 'What is policy-based design?', 'options' => ['Design rules', 'Using templates for customization', 'Design pattern', 'Architecture'], 'correct' => 1],
        ['question' => 'What are expression templates?', 'options' => ['Template expressions', 'Lazy evaluation via templates', 'Math expressions', 'Lambda templates'], 'correct' => 1],
        ['question' => 'What does consteval do (C++20)?', 'options' => ['Const evaluation', 'Forces compile-time evaluation', 'Runtime const', 'Eval constant'], 'correct' => 1],
        ['question' => 'What are concepts (C++20)?', 'options' => ['Ideas', 'Named template constraints', 'Type traits', 'Template requirements'], 'correct' => 1],
        ['question' => 'What is a requires clause?', 'options' => ['Requirement', 'Template constraint specification', 'Precondition', 'Assertion'], 'correct' => 1],
        ['question' => 'What are modules (C++20)?', 'options' => ['Libraries', 'Alternative to headers', 'Packages', 'Namespaces'], 'correct' => 1],
        ['question' => 'What is the spaceship operator <=>?', 'options' => ['Rocket', 'Three-way comparison', 'Greater or less', 'Compare'], 'correct' => 1],
        ['question' => 'What is std::format (C++20)?', 'options' => ['File format', 'Type-safe string formatting', 'Printf', 'Sprintf'], 'correct' => 1],
        ['question' => 'What is std::atomic?', 'options' => ['Small type', 'Atomic operation type', 'Thread-safe type', 'Lock-free type'], 'correct' => 1],
        ['question' => 'What is memory_order_seq_cst?', 'options' => ['Sequential', 'Sequentially consistent ordering', 'Memory sequence', 'Order constant'], 'correct' => 1],
        ['question' => 'What is memory_order_acquire?', 'options' => ['Get memory', 'Acquire synchronization', 'Lock memory', 'Read barrier'], 'correct' => 1],
        ['question' => 'What is memory_order_release?', 'options' => ['Free memory', 'Release synchronization', 'Unlock memory', 'Write barrier'], 'correct' => 1],
        ['question' => 'What is std::mutex?', 'options' => ['Mutable', 'Mutual exclusion lock', 'Multiple access', 'Memory mutex'], 'correct' => 1],
        ['question' => 'What is std::lock_guard?', 'options' => ['Lock function', 'RAII mutex wrapper', 'Guard clause', 'Lock manager'], 'correct' => 1],
        ['question' => 'What is std::unique_lock?', 'options' => ['Unique mutex', 'Flexible mutex wrapper', 'Lock guard', 'Exclusive lock'], 'correct' => 1],
        ['question' => 'What is std::shared_mutex?', 'options' => ['Shared lock', 'Reader-writer mutex', 'Multiple mutex', 'Shared resource'], 'correct' => 1],
        ['question' => 'What is a condition variable?', 'options' => ['Conditional', 'Thread synchronization primitive', 'Boolean', 'Wait condition'], 'correct' => 1],
        ['question' => 'What is std::async?', 'options' => ['Async keyword', 'Launches async task', 'Async function', 'Thread creator'], 'correct' => 1],
        ['question' => 'What is std::future?', 'options' => ['Future value', 'Result of async operation', 'Promise', 'Async return'], 'correct' => 1],
        ['question' => 'What is std::promise?', 'options' => ['Promised value', 'Sets future value', 'Async promise', 'Future setter'], 'correct' => 1],
        ['question' => 'What are parallel algorithms (C++17)?', 'options' => ['Parallel code', 'STL algorithms with execution policies', 'Multi-threaded', 'Concurrent algorithms'], 'correct' => 1],
        ['question' => 'What is an execution policy?', 'options' => ['Run policy', 'Sequential/parallel execution specification', 'Thread policy', 'Execution rule'], 'correct' => 1],
        ['question' => 'What is an allocator?', 'options' => ['Memory allocator', 'Custom memory management for containers', 'Malloc wrapper', 'New operator'], 'correct' => 1],
        ['question' => 'What is PMR?', 'options' => ['Pointer Management', 'Polymorphic Memory Resource', 'Persistent Memory', 'Pool Memory Resource'], 'correct' => 1],
        ['question' => 'What does co_return do?', 'options' => ['Return', 'Return from coroutine', 'Yield', 'Await'], 'correct' => 1],
        ['question' => 'What is SIMD?', 'options' => ['Simple Instructions', 'Single Instruction Multiple Data', 'Simultaneous Instructions', 'Parallel Processing'], 'correct' => 1],
    ]],
    ['label' => 'Expert', 'questions' => [
        ['question' => 'What is ABI stability?', 'options' => ['API stability', 'Binary interface compatibility', 'Compiler compatibility', 'Standard compatibility'], 'correct' => 1],
        ['question' => 'What is name mangling?', 'options' => ['Name corruption', 'Encoding names for linker', 'Name encryption', 'Obfuscation'], 'correct' => 1],
        ['question' => 'What is Itanium C++ ABI?', 'options' => ['Intel ABI', 'Common C++ ABI specification', 'CPU architecture', 'Compiler ABI'], 'correct' => 1],
        ['question' => 'How is vtable typically laid out?', 'options' => ['Random', 'Array of function pointers', 'Hash table', 'Tree structure'], 'correct' => 1],
        ['question' => 'What is devirtualization?', 'options' => ['Removing virtual', 'Optimizing virtual calls to direct', 'Making non-virtual', 'Inline virtual'], 'correct' => 1],
        ['question' => 'What is whole-program optimization?', 'options' => ['Full optimization', 'Optimizing entire program together', 'Maximum optimization', 'All optimizations'], 'correct' => 1],
        ['question' => 'What is LTCG?', 'options' => ['Late Type Check', 'Link-Time Code Generation', 'Long Term Code', 'Link Time Compilation'], 'correct' => 1],
        ['question' => 'What are zero-cost abstractions?', 'options' => ['Free features', 'No runtime overhead for abstraction', 'Compile-time only', 'Optimized abstractions'], 'correct' => 1],
        ['question' => 'What is std::coroutine_handle?', 'options' => ['Coroutine pointer', 'Low-level coroutine control', 'Coroutine manager', 'Async handle'], 'correct' => 1],
        ['question' => 'What is coroutine frame?', 'options' => ['Function frame', 'Coroutine state storage', 'Stack frame', 'Heap allocation'], 'correct' => 1],
        ['question' => 'What is strict aliasing in C++?', 'options' => ['Naming rule', 'Type-based aliasing restriction', 'Pointer rule', 'Reference rule'], 'correct' => 1],
        ['question' => 'What is UBSan?', 'options' => ['USB scanner', 'Undefined Behavior Sanitizer', 'Unit test tool', 'Code analyzer'], 'correct' => 1],
        ['question' => 'What is TSan?', 'options' => ['Test sanitizer', 'Thread Sanitizer', 'Type sanitizer', 'Trace sanitizer'], 'correct' => 1],
        ['question' => 'What is MSan?', 'options' => ['Memory sanitizer', 'Memory Sanitizer (uninitialized reads)', 'Malloc sanitizer', 'Multi sanitizer'], 'correct' => 1],
        ['question' => 'What are debug/release build differences?', 'options' => ['Symbols only', 'Optimization level and debug info', 'Speed only', 'Size only'], 'correct' => 1],
        ['question' => 'What is epoch-based reclamation?', 'options' => ['Time-based GC', 'Lock-free memory reclamation', 'Garbage collection', 'Reference counting'], 'correct' => 1],
        ['question' => 'What are hazard pointers in C++?', 'options' => ['Dangerous pointers', 'Safe memory reclamation for lock-free', 'Null pointers', 'Wild pointers'], 'correct' => 1],
        ['question' => 'What is reflection (proposed)?', 'options' => ['Mirror', 'Compile-time introspection', 'Runtime type info', 'Metaprogramming'], 'correct' => 1],
        ['question' => 'What are metaclasses (proposed)?', 'options' => ['Meta programming', 'Generative class templates', 'Class factories', 'Template classes'], 'correct' => 1],
        ['question' => 'What is P0709?', 'options' => ['Proposal number', 'Deterministic exception handling proposal', 'Standard section', 'Error code'], 'correct' => 1],
        ['question' => 'What is CppFront?', 'options' => ['Front end', 'Experimental C++ syntax (Cpp2)', 'Compiler', 'Preprocessor'], 'correct' => 1],
        ['question' => 'What is libcxx?', 'options' => ['Library', 'LLVM C++ standard library', 'Compiler', 'Linker'], 'correct' => 1],
        ['question' => 'What is std::pmr allocator?', 'options' => ['PMR type', 'Polymorphic memory resource allocator', 'Pool allocator', 'Memory allocator'], 'correct' => 1],
        ['question' => 'What is a lock-free queue?', 'options' => ['Unlocked queue', 'Queue without mutex using atomics', 'Thread-safe queue', 'Concurrent queue'], 'correct' => 1],
        ['question' => 'What is custom RTTI alternative?', 'options' => ['No RTTI', 'User-implemented type info', 'Dynamic cast', 'Type traits'], 'correct' => 1],
        ['question' => 'What overhead does virtual dispatch have?', 'options' => ['None', 'Indirect call via vtable lookup', 'Double call', 'Extra parameter'], 'correct' => 1],
        ['question' => 'What is allocator-aware container?', 'options' => ['Smart container', 'Container using custom allocators', 'Standard container', 'Memory container'], 'correct' => 1],
        ['question' => 'What is profile-guided optimization in C++?', 'options' => ['Debug profiling', 'Using runtime profile for optimization', 'Static analysis', 'Manual optimization'], 'correct' => 1],
        ['question' => 'What does signed overflow cause in C++?', 'options' => ['Wraps around', 'Undefined behavior', 'Exception', 'Saturates'], 'correct' => 1],
        ['question' => 'What is use-after-free?', 'options' => ['Reuse', 'Accessing freed memory', 'Memory leak', 'Double free'], 'correct' => 1],
    ]],
];
require_once __DIR__ . '/quiz-engine.php';
