<?php
$page_title = 'C# Quiz – 100 Levels – CodeFoundry';
$active_page = 'training';
$quiz_title  = 'C#';
$quiz_slug   = 'csharp';
$quiz_tiers  = [
    ['label' => 'Introduction', 'questions' => [
        ['question' => 'What is C# primarily used for?', 'options' => ['Web scraping only', 'Building .NET applications', 'Only database management', 'Hardware programming only'], 'correct' => 1],
        ['question' => 'Which company developed C#?', 'options' => ['Google', 'Apple', 'Microsoft', 'Oracle'], 'correct' => 2],
        ['question' => 'What is the .NET Framework?', 'options' => ['A text editor', 'A runtime and library for building applications', 'A database', 'An operating system'], 'correct' => 1],
        ['question' => 'Which method is used to output text to the console?', 'options' => ['Print()', 'Console.WriteLine()', 'Display()', 'Output()'], 'correct' => 1],
        ['question' => 'What data type is used for whole numbers?', 'options' => ['float', 'int', 'string', 'char'], 'correct' => 1],
        ['question' => 'What data type stores decimal numbers with high precision?', 'options' => ['int', 'bool', 'decimal', 'char'], 'correct' => 2],
        ['question' => 'Which keyword allows the compiler to infer the data type?', 'options' => ['auto', 'var', 'let', 'type'], 'correct' => 1],
        ['question' => 'What symbol is used for string interpolation in C#?', 'options' => ['#', '@', '$', '%'], 'correct' => 2],
        ['question' => 'How do you embed variables in string interpolation?', 'options' => ['${variable}', '{variable}', '$(variable)', '{{variable}}'], 'correct' => 1],
        ['question' => 'Which statement is used for conditional branching?', 'options' => ['loop', 'if', 'select', 'branch'], 'correct' => 1],
        ['question' => 'What keyword provides multiple case-based branching?', 'options' => ['cases', 'switch', 'select', 'choice'], 'correct' => 1],
        ['question' => 'Which loop guarantees at least one iteration?', 'options' => ['for', 'while', 'do-while', 'foreach'], 'correct' => 2],
        ['question' => 'What loop is best for iterating through a collection?', 'options' => ['for', 'foreach', 'do-while', 'goto'], 'correct' => 1],
        ['question' => 'How do you declare an array of integers?', 'options' => ['int[] arr', 'array<int> arr', 'int arr[]', 'Array int arr'], 'correct' => 0],
        ['question' => 'What is List<T> in C#?', 'options' => ['A static array', 'A dynamic collection', 'A database table', 'A string type'], 'correct' => 1],
        ['question' => 'What keyword is used to define a method?', 'options' => ['function', 'def', 'method', 'No special keyword'], 'correct' => 3],
        ['question' => 'What does a method return if it has no return value?', 'options' => ['null', 'void', 'empty', 'none'], 'correct' => 1],
        ['question' => 'What are properties in C#?', 'options' => ['Variables only', 'Methods with get/set accessors', 'Constants', 'Attributes'], 'correct' => 1],
        ['question' => 'What is a namespace used for?', 'options' => ['Organizing code', 'Storing data', 'Running loops', 'Error handling'], 'correct' => 0],
        ['question' => 'Which directive imports a namespace?', 'options' => ['import', 'include', 'using', 'require'], 'correct' => 2],
        ['question' => 'Which access modifier makes a member accessible only within the same class?', 'options' => ['public', 'private', 'protected', 'internal'], 'correct' => 1],
        ['question' => 'Which access modifier makes a member accessible from anywhere?', 'options' => ['private', 'protected', 'public', 'internal'], 'correct' => 2],
        ['question' => 'What is a class in C#?', 'options' => ['A function', 'A blueprint for objects', 'A variable', 'A loop'], 'correct' => 1],
        ['question' => 'What is a constructor?', 'options' => ['A destructor', 'A special method that initializes objects', 'A property', 'A namespace'], 'correct' => 1],
        ['question' => 'What does null represent?', 'options' => ['Zero', 'Empty string', 'Absence of a value/reference', 'False'], 'correct' => 2],
        ['question' => 'What is the difference between const and readonly?', 'options' => ['No difference', 'const is compile-time, readonly can be set at runtime', 'readonly is faster', 'const is deprecated'], 'correct' => 1],
        ['question' => 'What is an Enum used for?', 'options' => ['Defining named constants', 'Creating loops', 'Error handling', 'Type conversion'], 'correct' => 0],
        ['question' => 'What is the purpose of try-catch?', 'options' => ['Loop control', 'Exception handling', 'Variable declaration', 'Method definition'], 'correct' => 1],
        ['question' => 'How do you write a single-line comment?', 'options' => ['# comment', '// comment', '/* comment', '-- comment'], 'correct' => 1],
        ['question' => 'How do you write a multi-line comment?', 'options' => ['/* comment */', '<!-- comment -->', '# comment #', '// comment //'], 'correct' => 0],
    ]],
    ['label' => 'Beginner', 'questions' => [
        ['question' => 'What is inheritance in OOP?', 'options' => ['Copying code', 'A class deriving from another class', 'A loop structure', 'A namespace feature'], 'correct' => 1],
        ['question' => 'What is polymorphism?', 'options' => ['Multiple inheritance', 'Ability to take multiple forms', 'Single responsibility', 'Data hiding'], 'correct' => 1],
        ['question' => 'What is encapsulation?', 'options' => ['Inheritance mechanism', 'Hiding internal details', 'Method overloading', 'Interface implementation'], 'correct' => 1],
        ['question' => 'What is abstraction?', 'options' => ['Showing implementation details', 'Hiding complexity and showing only essential features', 'Creating objects', 'Data type conversion'], 'correct' => 1],
        ['question' => 'What is an abstract class?', 'options' => ['A sealed class', 'A class that cannot be instantiated', 'A static class', 'A generic class'], 'correct' => 1],
        ['question' => 'What is an interface?', 'options' => ['A concrete class', 'A contract defining members without implementation', 'A namespace', 'A data type'], 'correct' => 1],
        ['question' => 'What does the virtual keyword do?', 'options' => ['Makes a method static', 'Allows a method to be overridden', 'Prevents inheritance', 'Creates an interface'], 'correct' => 1],
        ['question' => 'What does override do?', 'options' => ['Creates a new method', 'Provides a new implementation for a virtual method', 'Hides a method', 'Seals a class'], 'correct' => 1],
        ['question' => 'What does sealed prevent?', 'options' => ['Method overriding or class inheritance', 'Object creation', 'Variable assignment', 'Namespace usage'], 'correct' => 0],
        ['question' => 'What is the base keyword used for?', 'options' => ['Accessing derived class members', 'Accessing base class members', 'Creating objects', 'Defining interfaces'], 'correct' => 1],
        ['question' => 'What is a static class?', 'options' => ['A class that can be instantiated', 'A class that cannot be instantiated and contains only static members', 'An abstract class', 'An interface'], 'correct' => 1],
        ['question' => 'What are extension methods?', 'options' => ['Virtual methods', 'Methods that extend existing types without modification', 'Abstract methods', 'Constructor methods'], 'correct' => 1],
        ['question' => 'What is a generic type?', 'options' => ['A sealed type', 'A type parameterized with other types', 'A primitive type', 'An interface'], 'correct' => 1],
        ['question' => 'What is List<T>?', 'options' => ['A static array', 'A generic dynamic list', 'A dictionary', 'A queue'], 'correct' => 1],
        ['question' => 'What is Dictionary<TKey, TValue>?', 'options' => ['A list', 'A key-value collection', 'An array', 'A queue'], 'correct' => 1],
        ['question' => 'What is Queue<T> used for?', 'options' => ['LIFO structure', 'FIFO structure', 'Random access', 'Key-value storage'], 'correct' => 1],
        ['question' => 'What is Stack<T> used for?', 'options' => ['FIFO structure', 'LIFO structure', 'Key-value storage', 'Ordered list'], 'correct' => 1],
        ['question' => 'What does LINQ stand for?', 'options' => ['Language Integrated Query', 'Linear Query', 'List Query', 'Logic Query'], 'correct' => 0],
        ['question' => 'What does the Where() LINQ method do?', 'options' => ['Sorts elements', 'Filters elements', 'Counts elements', 'Reverses elements'], 'correct' => 1],
        ['question' => 'What does Select() do in LINQ?', 'options' => ['Filters elements', 'Projects/transforms elements', 'Sorts elements', 'Groups elements'], 'correct' => 1],
        ['question' => 'What does OrderBy() do?', 'options' => ['Filters elements', 'Sorts elements in ascending order', 'Groups elements', 'Counts elements'], 'correct' => 1],
        ['question' => 'What is a lambda expression?', 'options' => ['A loop', 'An anonymous function', 'A class', 'A namespace'], 'correct' => 1],
        ['question' => 'What is a delegate?', 'options' => ['An interface', 'A type-safe function pointer', 'A class', 'A property'], 'correct' => 1],
        ['question' => 'What is Action<T>?', 'options' => ['A delegate that returns a value', 'A delegate that returns void', 'An interface', 'A class'], 'correct' => 1],
        ['question' => 'What is Func<T>?', 'options' => ['A delegate that returns void', 'A delegate that returns a value', 'A class', 'An interface'], 'correct' => 1],
        ['question' => 'What are events used for?', 'options' => ['Data storage', 'Notification mechanism', 'Loop control', 'Type conversion'], 'correct' => 1],
        ['question' => 'What is int??', 'options' => ['Double integer', 'Nullable integer', 'Integer array', 'Integer pointer'], 'correct' => 1],
        ['question' => 'What does the null-conditional operator ?. do?', 'options' => ['Throws exception', 'Returns null if operand is null', 'Converts to string', 'Checks equality'], 'correct' => 1],
        ['question' => 'What does the null-coalescing operator ?? do?', 'options' => ['Checks null', 'Returns right operand if left is null', 'Throws exception', 'Converts type'], 'correct' => 1],
        ['question' => 'What does DateTime represent?', 'options' => ['Time zone only', 'Date and time', 'Duration', 'Time span'], 'correct' => 1],
        ['question' => 'What is IDisposable used for?', 'options' => ['Inheritance', 'Resource cleanup', 'Type conversion', 'Event handling'], 'correct' => 1],
        ['question' => 'What does the using statement do with IDisposable?', 'options' => ['Imports namespace', 'Automatically calls Dispose()', 'Creates objects', 'Defines methods'], 'correct' => 1],
        ['question' => 'What does File.ReadAllText() do?', 'options' => ['Writes to file', 'Reads entire file as string', 'Deletes file', 'Creates file'], 'correct' => 1],
        ['question' => 'What is StreamReader used for?', 'options' => ['Writing files', 'Reading files line by line', 'Deleting files', 'Creating files'], 'correct' => 1],
        ['question' => 'What does ToList() do in LINQ?', 'options' => ['Converts to array', 'Converts to List<T>', 'Converts to dictionary', 'Converts to string'], 'correct' => 1],
    ]],
    ['label' => 'Intermediate', 'questions' => [
        ['question' => 'What does GroupBy() do in LINQ?', 'options' => ['Sorts elements', 'Groups elements by a key', 'Filters elements', 'Joins elements'], 'correct' => 1],
        ['question' => 'What does Join() do in LINQ?', 'options' => ['Concatenates strings', 'Joins two sequences based on keys', 'Groups elements', 'Sorts elements'], 'correct' => 1],
        ['question' => 'What does SelectMany() do?', 'options' => ['Selects one element', 'Flattens nested sequences', 'Sorts elements', 'Groups elements'], 'correct' => 1],
        ['question' => 'What does Distinct() do?', 'options' => ['Sorts elements', 'Removes duplicates', 'Counts elements', 'Groups elements'], 'correct' => 1],
        ['question' => 'What does Aggregate() do?', 'options' => ['Groups elements', 'Accumulates values', 'Sorts elements', 'Filters elements'], 'correct' => 1],
        ['question' => 'What is the async keyword used for?', 'options' => ['Static methods', 'Marking methods as asynchronous', 'Locking resources', 'Creating threads'], 'correct' => 1],
        ['question' => 'What does await do?', 'options' => ['Blocks thread', 'Asynchronously waits for task completion', 'Creates tasks', 'Cancels operations'], 'correct' => 1],
        ['question' => 'What is Task<T>?', 'options' => ['A thread', 'A promise of a value', 'A collection', 'A delegate'], 'correct' => 1],
        ['question' => 'What is ConfigureAwait(false) used for?', 'options' => ['Canceling tasks', 'Not capturing synchronization context', 'Creating tasks', 'Blocking threads'], 'correct' => 1],
        ['question' => 'What is CancellationToken used for?', 'options' => ['Creating tasks', 'Canceling async operations', 'Locking resources', 'Error handling'], 'correct' => 1],
        ['question' => 'What does where T : class mean?', 'options' => ['T must be struct', 'T must be reference type', 'T must be interface', 'T must be sealed'], 'correct' => 1],
        ['question' => 'What does where T : struct mean?', 'options' => ['T must be class', 'T must be value type', 'T must be interface', 'T must be nullable'], 'correct' => 1],
        ['question' => 'What does where T : new() mean?', 'options' => ['T is abstract', 'T has parameterless constructor', 'T is sealed', 'T is interface'], 'correct' => 1],
        ['question' => 'What is covariance (out)?', 'options' => ['Input parameter variance', 'Output parameter variance', 'No variance', 'Invariance'], 'correct' => 1],
        ['question' => 'What is contravariance (in)?', 'options' => ['Output parameter variance', 'Input parameter variance', 'No variance', 'Covariance'], 'correct' => 1],
        ['question' => 'What is pattern matching with is?', 'options' => ['Equality check', 'Type checking with pattern', 'Assignment', 'Casting'], 'correct' => 1],
        ['question' => 'What are switch expressions (C# 8+)?', 'options' => ['Traditional switch', 'Expression-based switch', 'If statement', 'Loop'], 'correct' => 1],
        ['question' => 'What is a record (C# 9+)?', 'options' => ['A class', 'An immutable reference type with value semantics', 'An interface', 'A struct'], 'correct' => 1],
        ['question' => 'What are init-only setters?', 'options' => ['Normal setters', 'Setters that work only during initialization', 'Getters', 'Private setters'], 'correct' => 1],
        ['question' => 'What does the with expression do?', 'options' => ['Deletes records', 'Creates modified copy of record', 'Checks equality', 'Converts types'], 'correct' => 1],
        ['question' => 'What is ValueTuple?', 'options' => ['A class', 'A value type tuple', 'A reference type', 'An interface'], 'correct' => 1],
        ['question' => 'What is deconstruction?', 'options' => ['Object deletion', 'Breaking tuple/object into parts', 'Type conversion', 'Serialization'], 'correct' => 1],
        ['question' => 'What are local functions?', 'options' => ['Global methods', 'Functions defined inside methods', 'Static methods', 'Extension methods'], 'correct' => 1],
        ['question' => 'What does ref parameter do?', 'options' => ['Copies value', 'Passes by reference', 'Makes parameter optional', 'Returns value'], 'correct' => 1],
        ['question' => 'What does out parameter do?', 'options' => ['Input parameter', 'Output parameter', 'Optional parameter', 'Default parameter'], 'correct' => 1],
        ['question' => 'What does in parameter do?', 'options' => ['Output parameter', 'Read-only reference parameter', 'Value parameter', 'Optional parameter'], 'correct' => 1],
        ['question' => 'What is Span<T>?', 'options' => ['A list', 'A contiguous memory region', 'A dictionary', 'A queue'], 'correct' => 1],
        ['question' => 'What is Memory<T>?', 'options' => ['A span', 'An ownable memory region', 'A list', 'An array'], 'correct' => 1],
        ['question' => 'What is ArrayPool<T>?', 'options' => ['Array creator', 'Shared array buffer pool', 'Array sorter', 'Array copier'], 'correct' => 1],
        ['question' => 'What is unsafe code?', 'options' => ['Buggy code', 'Code using pointers', 'Uncompiled code', 'Deprecated code'], 'correct' => 1],
        ['question' => 'What does the fixed statement do?', 'options' => ['Fixes bugs', 'Prevents GC from moving object', 'Locks resources', 'Seals classes'], 'correct' => 1],
        ['question' => 'What is Expression<Func<T>>?', 'options' => ['A function', 'An expression tree', 'A delegate', 'A class'], 'correct' => 1],
        ['question' => 'What is reflection?', 'options' => ['Code optimization', 'Runtime type inspection and invocation', 'Compilation', 'Debugging'], 'correct' => 1],
        ['question' => 'What is a custom attribute?', 'options' => ['A property', 'Metadata attached to code elements', 'A method', 'A class'], 'correct' => 1],
        ['question' => 'What is the dynamic type?', 'options' => ['Static type', 'Runtime-bound type', 'Compiled type', 'Value type'], 'correct' => 1],
    ]],
    ['label' => 'Advanced', 'questions' => [
        ['question' => 'What is the .NET memory model?', 'options' => ['Unmanaged memory only', 'Managed heap with garbage collection', 'Stack only', 'No memory management'], 'correct' => 1],
        ['question' => 'How many generations does the GC have?', 'options' => ['2', '3', '4', '5'], 'correct' => 1],
        ['question' => 'What is the LOH?', 'options' => ['Low Object Heap', 'Large Object Heap', 'Last Object Heap', 'Locked Object Heap'], 'correct' => 1],
        ['question' => 'What is the SOH?', 'options' => ['Small Object Heap', 'Static Object Heap', 'Sealed Object Heap', 'Single Object Heap'], 'correct' => 0],
        ['question' => 'What size threshold triggers LOH allocation?', 'options' => ['42KB', '85KB', '128KB', '256KB'], 'correct' => 1],
        ['question' => 'What is finalization?', 'options' => ['Constructor', 'Destructor/cleanup before GC', 'Compilation', 'Optimization'], 'correct' => 1],
        ['question' => 'What is the Dispose pattern?', 'options' => ['Creation pattern', 'Deterministic resource cleanup pattern', 'Singleton pattern', 'Factory pattern'], 'correct' => 1],
        ['question' => 'What is IAsyncDisposable?', 'options' => ['Synchronous disposal', 'Asynchronous disposal', 'No disposal', 'Automatic disposal'], 'correct' => 1],
        ['question' => 'What is the Thread class?', 'options' => ['Task wrapper', 'Low-level thread representation', 'Async method', 'Delegate'], 'correct' => 1],
        ['question' => 'What is ThreadPool?', 'options' => ['Thread creator', 'Managed thread pool', 'Thread destroyer', 'Thread counter'], 'correct' => 1],
        ['question' => 'What is Monitor used for?', 'options' => ['Debugging', 'Thread synchronization', 'Performance monitoring', 'Memory profiling'], 'correct' => 1],
        ['question' => 'What is Mutex?', 'options' => ['Task', 'Cross-process lock', 'Thread', 'Delegate'], 'correct' => 1],
        ['question' => 'What is Semaphore?', 'options' => ['Unlimited access', 'Limited concurrent access control', 'Single access', 'No access'], 'correct' => 1],
        ['question' => 'What is SemaphoreSlim?', 'options' => ['Heavy semaphore', 'Lightweight async-friendly semaphore', 'Process semaphore', 'Named semaphore'], 'correct' => 1],
        ['question' => 'What is the Parallel class?', 'options' => ['Sequential operations', 'Parallel operations helper', 'Thread pool', 'Task factory'], 'correct' => 1],
        ['question' => 'What is PLINQ?', 'options' => ['Sequential LINQ', 'Parallel LINQ', 'Async LINQ', 'Lazy LINQ'], 'correct' => 1],
        ['question' => 'What is Channel<T>?', 'options' => ['Network channel', 'Producer-consumer queue', 'Event system', 'Task scheduler'], 'correct' => 1],
        ['question' => 'What is IAsyncEnumerable?', 'options' => ['Sync enumeration', 'Async stream', 'List', 'Array'], 'correct' => 1],
        ['question' => 'What is System.IO.Pipelines?', 'options' => ['File system', 'High-performance IO', 'Network library', 'Serialization'], 'correct' => 1],
        ['question' => 'Why is Span<T> performant?', 'options' => ['Heap allocated', 'Stack allocated, no GC', 'Slow but safe', 'Thread-safe'], 'correct' => 1],
        ['question' => 'What does stackalloc do?', 'options' => ['Heap allocation', 'Stack allocation', 'Static allocation', 'No allocation'], 'correct' => 1],
        ['question' => 'What is NativeMemory (C# 10+)?', 'options' => ['Managed memory', 'Unmanaged memory API', 'Stack memory', 'Heap memory'], 'correct' => 1],
        ['question' => 'What are source generators?', 'options' => ['Runtime code', 'Compile-time code generation', 'Reflection', 'IL emission'], 'correct' => 1],
        ['question' => 'What is Roslyn?', 'options' => ['Runtime', 'C# compiler platform', 'IDE', 'Database'], 'correct' => 1],
        ['question' => 'What are Roslyn analyzers?', 'options' => ['Performance tools', 'Code analysis tools', 'Debuggers', 'Profilers'], 'correct' => 1],
        ['question' => 'What is dependency injection?', 'options' => ['Tight coupling', 'Inversion of control pattern', 'Inheritance', 'Encapsulation'], 'correct' => 1],
        ['question' => 'What is middleware pipeline?', 'options' => ['Data structure', 'Request processing chain', 'Thread pool', 'Event system'], 'correct' => 1],
        ['question' => 'What is Entity Framework Core?', 'options' => ['Web framework', 'ORM', 'Database', 'Compiler'], 'correct' => 1],
        ['question' => 'What is RyuJIT?', 'options' => ['Interpreter', 'Just-in-time compiler', 'AOT compiler', 'Debugger'], 'correct' => 1],
        ['question' => 'What is NativeAOT?', 'options' => ['JIT compilation', 'Ahead-of-time compilation', 'Interpretation', 'Reflection'], 'correct' => 1],
        ['question' => 'What is tiered compilation?', 'options' => ['Single tier', 'Multiple optimization tiers', 'No optimization', 'Manual optimization'], 'correct' => 1],
        ['question' => 'What is PGO in .NET?', 'options' => ['Garbage collection', 'Profile-guided optimization', 'Compilation mode', 'Runtime mode'], 'correct' => 1],
        ['question' => 'What does ManualResetEvent do?', 'options' => ['Auto-resets', 'Manual signal reset', 'No reset', 'Timed reset'], 'correct' => 1],
        ['question' => 'What is ReaderWriterLockSlim?', 'options' => ['Single lock', 'Multi-reader single-writer lock', 'No lock', 'Read-only lock'], 'correct' => 1],
        ['question' => 'What is the purpose of ConfigureAwait?', 'options' => ['Create tasks', 'Control context capture', 'Cancel tasks', 'Wait synchronously'], 'correct' => 1],
    ]],
    ['label' => 'Expert', 'questions' => [
        ['question' => 'What is CoreCLR?', 'options' => ['Framework', 'Cross-platform .NET runtime', 'Compiler', 'IDE'], 'correct' => 1],
        ['question' => 'What is MethodTable?', 'options' => ['Method list', 'CLR type representation', 'Stack frame', 'Heap structure'], 'correct' => 1],
        ['question' => 'What is EEClass?', 'options' => ['Base class', 'CLR class metadata', 'Interface', 'Struct'], 'correct' => 1],
        ['question' => 'What is TypeHandle?', 'options' => ['Type reference', 'CLR type handle', 'Class pointer', 'Method pointer'], 'correct' => 1],
        ['question' => 'What is in an object header?', 'options' => ['Data only', 'Sync block index and MethodTable pointer', 'Methods', 'Properties'], 'correct' => 1],
        ['question' => 'What is a sync block?', 'options' => ['Code block', 'Object synchronization data', 'Method body', 'Type info'], 'correct' => 1],
        ['question' => 'What is the mark phase in GC?', 'options' => ['Memory allocation', 'Identifying live objects', 'Memory compaction', 'Object deletion'], 'correct' => 1],
        ['question' => 'What is the plan phase in GC?', 'options' => ['Allocation', 'Determining relocation', 'Marking', 'Finalizing'], 'correct' => 1],
        ['question' => 'What is the relocate phase?', 'options' => ['Marking', 'Updating references', 'Deleting', 'Creating'], 'correct' => 1],
        ['question' => 'What is the compact phase?', 'options' => ['Expanding heap', 'Moving objects together', 'Fragmenting', 'Allocating'], 'correct' => 1],
        ['question' => 'What is a card table?', 'options' => ['Data structure', 'GC optimization for tracking references', 'Type table', 'Method table'], 'correct' => 1],
        ['question' => 'What is a write barrier?', 'options' => ['Read protection', 'GC reference write tracking', 'Compilation step', 'Optimization'], 'correct' => 1],
        ['question' => 'What is pinning in GC?', 'options' => ['Heap allocation', 'Preventing object movement', 'Object deletion', 'Object creation'], 'correct' => 1],
        ['question' => 'What are hardware intrinsics?', 'options' => ['Software features', 'Direct CPU instruction access', 'Virtual methods', 'Abstract classes'], 'correct' => 1],
        ['question' => 'What is Vector<T>?', 'options' => ['List', 'SIMD vector type', 'Array', 'Dictionary'], 'correct' => 1],
        ['question' => 'What is Vector256<T>?', 'options' => ['256 elements', '256-bit SIMD vector', 'Array', 'List'], 'correct' => 1],
        ['question' => 'What is SIMD?', 'options' => ['Sequential processing', 'Single Instruction Multiple Data', 'Single Data Multiple Instruction', 'Sequential Data'], 'correct' => 1],
        ['question' => 'What is P/Invoke?', 'options' => ['C# method', 'Platform Invocation for native code', 'Property', 'Interface'], 'correct' => 1],
        ['question' => 'What is MarshalAs?', 'options' => ['Serialization', 'Controlling data marshaling', 'Type conversion', 'Reflection'], 'correct' => 1],
        ['question' => 'What is GCHandle?', 'options' => ['Garbage collector', 'Handle to managed object for unmanaged code', 'Thread handle', 'Process handle'], 'correct' => 1],
        ['question' => 'What is COM interop?', 'options' => ['Network protocol', 'Component Object Model interoperability', 'File format', 'Database connection'], 'correct' => 1],
        ['question' => 'What is devirtualization?', 'options' => ['Adding virtual methods', 'Replacing virtual call with direct call', 'Removing methods', 'Interface implementation'], 'correct' => 1],
        ['question' => 'What is loop cloning?', 'options' => ['Loop removal', 'Duplicating loop for optimization', 'Loop unrolling', 'Loop merging'], 'correct' => 1],
        ['question' => 'What is bounds check elimination?', 'options' => ['Adding checks', 'Removing array bounds checks', 'Type checking', 'Null checking'], 'correct' => 1],
        ['question' => 'What is GCInfo?', 'options' => ['User info', 'GC metadata format', 'Type info', 'Method info'], 'correct' => 1],
        ['question' => 'What is a stack frame?', 'options' => ['Heap structure', 'Method call context on stack', 'Type definition', 'Object instance'], 'correct' => 1],
        ['question' => 'What is tail call optimization?', 'options' => ['No optimization', 'Eliminating stack frame for tail recursion', 'Loop optimization', 'Inlining'], 'correct' => 1],
        ['question' => 'What is EventPipe?', 'options' => ['Event system', 'Cross-platform tracing mechanism', 'Pipeline library', 'Stream processor'], 'correct' => 1],
        ['question' => 'What is DiagnosticSource?', 'options' => ['Compiler diagnostic', 'Runtime instrumentation API', 'Debugger', 'Logger'], 'correct' => 1],
        ['question' => 'What is dotnet-trace?', 'options' => ['Compiler', 'Performance tracing tool', 'Debugger', 'Profiler'], 'correct' => 1],
        ['question' => 'What is dotnet-dump?', 'options' => ['Data dump', 'Memory dump analyzer', 'Code generator', 'Compiler'], 'correct' => 1],
        ['question' => 'What is EventSource?', 'options' => ['Event handler', 'ETW event provider', 'Delegate', 'Interface'], 'correct' => 1],
        ['question' => 'What is EventListener?', 'options' => ['Event sender', 'Event consumer', 'Event creator', 'Event deleter'], 'correct' => 1],
        ['question' => 'What is a constrained call?', 'options' => ['Unconstrained call', 'Generic interface call optimization', 'Virtual call', 'Static call'], 'correct' => 1],
        ['question' => 'What is Vector512<T> (AVX-512)?', 'options' => ['512 elements', '512-bit SIMD vector', 'Array', 'List'], 'correct' => 1],
    ]],
];
require_once __DIR__ . '/quiz-engine.php';
