<?php
$page_title = 'CSS Quiz – 100 Levels – CodeFoundry';
$active_page = 'training';
$quiz_title  = 'CSS';
$quiz_slug   = 'css';
$quiz_tiers  = [
    [
        'label' => 'Introduction',
        'questions' => [
            ['question' => 'What does CSS stand for?', 'options' => ['Cascading Style Sheets', 'Creative Style System', 'Computer Style Sheets', 'Colorful Style Sheets'], 'correct' => 0],
            ['question' => 'Which CSS property changes text color?', 'options' => ['text-color', 'font-color', 'color', 'text-style'], 'correct' => 2],
            ['question' => 'Which CSS property changes background color?', 'options' => ['bgcolor', 'background-color', 'color', 'bg-color'], 'correct' => 1],
            ['question' => 'How do you select an element with id="header"?', 'options' => ['.header', '#header', 'header', '*header'], 'correct' => 1],
            ['question' => 'How do you select elements with class="menu"?', 'options' => ['#menu', '.menu', 'menu', '*menu'], 'correct' => 1],
            ['question' => 'Which property controls font size?', 'options' => ['text-size', 'font-size', 'text-style', 'font-weight'], 'correct' => 1],
            ['question' => 'Which property sets the font family?', 'options' => ['font-family', 'font-name', 'font', 'typeface'], 'correct' => 0],
            ['question' => 'Which property aligns text?', 'options' => ['text-align', 'align', 'text-position', 'alignment'], 'correct' => 0],
            ['question' => 'Which property adds space inside an element?', 'options' => ['margin', 'padding', 'spacing', 'border'], 'correct' => 1],
            ['question' => 'Which property adds space outside an element?', 'options' => ['padding', 'margin', 'spacing', 'border'], 'correct' => 1],
            ['question' => 'How do you add a border in CSS?', 'options' => ['border: 1px solid black;', 'border-style: solid;', 'outline: 1px;', 'edge: 1px;'], 'correct' => 0],
            ['question' => 'Which property sets element width?', 'options' => ['size', 'width', 'element-width', 'w'], 'correct' => 1],
            ['question' => 'Which property sets element height?', 'options' => ['size', 'height', 'element-height', 'h'], 'correct' => 1],
            ['question' => 'How do you make text bold?', 'options' => ['font-weight: bold;', 'text-style: bold;', 'font: bold;', 'bold: true;'], 'correct' => 0],
            ['question' => 'How do you make text italic?', 'options' => ['font-weight: italic;', 'font-style: italic;', 'text-style: italic;', 'italic: true;'], 'correct' => 1],
            ['question' => 'How do you create a CSS comment?', 'options' => ['// comment', '/* comment */', '&lt;!-- comment --&gt;', '# comment'], 'correct' => 1],
            ['question' => 'Where should CSS be placed in HTML?', 'options' => ['In &lt;body&gt;', 'In &lt;head&gt;', 'In &lt;footer&gt;', 'Anywhere'], 'correct' => 1],
            ['question' => 'What is inline CSS?', 'options' => ['CSS in a file', 'CSS in &lt;style&gt; tag', 'CSS in style attribute', 'CSS inline with text'], 'correct' => 2],
            ['question' => 'What is internal CSS?', 'options' => ['CSS in external file', 'CSS in &lt;style&gt; tag in HTML', 'CSS in style attribute', 'Internal styling'], 'correct' => 1],
            ['question' => 'What is external CSS?', 'options' => ['CSS outside page', 'CSS in separate .css file', 'CSS in &lt;style&gt;', 'External styles'], 'correct' => 1],
            ['question' => 'Which CSS property removes underline from links?', 'options' => ['text-decoration: none;', 'underline: none;', 'link-style: none;', 'decoration: none;'], 'correct' => 0],
            ['question' => 'What is the default display value for &lt;div&gt;?', 'options' => ['inline', 'block', 'flex', 'grid'], 'correct' => 1],
            ['question' => 'What is the default display value for &lt;span&gt;?', 'options' => ['block', 'inline', 'flex', 'inline-block'], 'correct' => 1],
            ['question' => 'How do you hide an element with CSS?', 'options' => ['visibility: none;', 'display: none;', 'hidden: true;', 'hide: yes;'], 'correct' => 1],
            ['question' => 'What does the cascade in CSS mean?', 'options' => ['Waterfall effect', 'Style priority/inheritance rules', 'Cascading colors', 'Cascading layout'], 'correct' => 1],
            ['question' => 'Which selector has highest specificity?', 'options' => ['Element', 'Class', 'ID', 'Universal'], 'correct' => 2],
            ['question' => 'What unit is px?', 'options' => ['Percentage', 'Pixel', 'Point', 'Pica'], 'correct' => 1],
            ['question' => 'What is em unit relative to?', 'options' => ['Root element', 'Parent element font-size', 'Viewport', 'Nothing'], 'correct' => 1],
        ]
    ],
    [
        'label' => 'Beginner',
        'questions' => [
            ['question' => 'What is the CSS box model?', 'options' => ['A box element', 'Content, padding, border, and margin', 'Box shadow', 'Boxing layout'], 'correct' => 1],
            ['question' => 'What does display: flex do?', 'options' => ['Makes element flexible', 'Enables flexbox layout', 'Flexible sizing', 'Flex animation'], 'correct' => 1],
            ['question' => 'What is position: relative?', 'options' => ['Relative to parent', 'Positioned relative to its normal position', 'Related position', 'Relatively positioned'], 'correct' => 1],
            ['question' => 'What is position: absolute?', 'options' => ['Absolutely positioned', 'Positioned relative to nearest positioned ancestor', 'Fixed position', 'Absolute center'], 'correct' => 1],
            ['question' => 'What is position: fixed?', 'options' => ['Fixed size', 'Positioned relative to viewport', 'Cannot move', 'Fixed layout'], 'correct' => 1],
            ['question' => 'What does z-index control?', 'options' => ['Z axis rotation', 'Stacking order of positioned elements', 'Zoom index', 'Z coordinate'], 'correct' => 1],
            ['question' => 'What is the :hover pseudo-class?', 'options' => ['Hovering element', 'Styles when mouse is over element', 'Hover effect', 'Mouse over'], 'correct' => 1],
            ['question' => 'What is the :focus pseudo-class?', 'options' => ['Focused view', 'Styles when element has focus', 'Focus effect', 'Focused element'], 'correct' => 1],
            ['question' => 'What is the ::before pseudo-element?', 'options' => ['Before element', 'Inserts content before element', 'Previous element', 'Before styles'], 'correct' => 1],
            ['question' => 'What is the ::after pseudo-element?', 'options' => ['After element', 'Inserts content after element', 'Next element', 'After styles'], 'correct' => 1],
            ['question' => 'What does border-radius do?', 'options' => ['Border size', 'Rounds corners', 'Border color', 'Radius property'], 'correct' => 1],
            ['question' => 'What does box-shadow create?', 'options' => ['Box outline', 'Shadow effect around element', 'Dark box', 'Shadow box'], 'correct' => 1],
            ['question' => 'What does text-shadow create?', 'options' => ['Text outline', 'Shadow effect on text', 'Dark text', 'Text effect'], 'correct' => 1],
            ['question' => 'What does opacity control?', 'options' => ['Openness', 'Transparency level', 'Operation', 'Opacity color'], 'correct' => 1],
            ['question' => 'What is rgba() for?', 'options' => ['RGB array', 'RGB color with alpha (transparency)', 'Red green blue array', 'RGBA format'], 'correct' => 1],
            ['question' => 'What does overflow: hidden do?', 'options' => ['Hides element', 'Clips content that overflows', 'Hidden overflow', 'Overflow hidden'], 'correct' => 1],
            ['question' => 'What is float used for?', 'options' => ['Floating animation', 'Positioning element left or right with text wrap', 'Float data type', 'Floating element'], 'correct' => 1],
            ['question' => 'What does clear do?', 'options' => ['Clears content', 'Controls behavior next to floated elements', 'Clear style', 'Clears float'], 'correct' => 1],
            ['question' => 'What is calc() used for?', 'options' => ['Calculator', 'Perform calculations in CSS', 'Calculate values', 'Calculation function'], 'correct' => 1],
            ['question' => 'What are CSS variables?', 'options' => ['Variable styles', 'Custom properties for reusable values', 'Variable names', 'Style variables'], 'correct' => 1],
            ['question' => 'How do you declare a CSS variable?', 'options' => ['var-name: value;', '--var-name: value;', '$var-name: value;', '@var-name: value;'], 'correct' => 1],
            ['question' => 'How do you use a CSS variable?', 'options' => ['variable(--name)', 'var(--name)', 'use(--name)', 'get(--name)'], 'correct' => 1],
            ['question' => 'What is a media query?', 'options' => ['Media element', 'CSS for different screen sizes/devices', 'Query media', 'Media detection'], 'correct' => 1],
            ['question' => 'What is vh unit?', 'options' => ['Very high', 'Viewport height', 'Vertical height', 'View height'], 'correct' => 1],
            ['question' => 'What is vw unit?', 'options' => ['Very wide', 'Viewport width', 'Vertical width', 'View width'], 'correct' => 1],
            ['question' => 'What does line-height control?', 'options' => ['Line width', 'Height of line boxes', 'Line style', 'Line spacing'], 'correct' => 1],
            ['question' => 'What is the :first-child pseudo-class?', 'options' => ['First element', 'Selects first child of parent', 'Child element', 'First selector'], 'correct' => 1],
            ['question' => 'What is the :last-child pseudo-class?', 'options' => ['Last element', 'Selects last child of parent', 'Child element', 'Last selector'], 'correct' => 1],
        ]
    ],
    [
        'label' => 'Intermediate',
        'questions' => [
            ['question' => 'What does justify-content do in flexbox?', 'options' => ['Justifies text', 'Aligns items along main axis', 'Justified layout', 'Content justify'], 'correct' => 1],
            ['question' => 'What does align-items do in flexbox?', 'options' => ['Aligns text', 'Aligns items along cross axis', 'Item alignment', 'Align property'], 'correct' => 1],
            ['question' => 'What does flex-wrap do?', 'options' => ['Wraps text', 'Controls if flex items wrap to new lines', 'Flex wrapping', 'Wrap flex'], 'correct' => 1],
            ['question' => 'What does flex-grow control?', 'options' => ['Growth rate', 'How much item grows relative to others', 'Flex size', 'Growing flex'], 'correct' => 1],
            ['question' => 'What does flex-shrink control?', 'options' => ['Shrink rate', 'How much item shrinks relative to others', 'Flex size', 'Shrinking flex'], 'correct' => 1],
            ['question' => 'What is grid-template-columns for?', 'options' => ['Column template', 'Defines column tracks in grid', 'Template columns', 'Column layout'], 'correct' => 1],
            ['question' => 'What is grid-gap?', 'options' => ['Grid spacing', 'Spacing between grid rows and columns', 'Gap in grid', 'Grid distance'], 'correct' => 1],
            ['question' => 'What does @keyframes do?', 'options' => ['Key frames', 'Defines animation steps', 'Frame animation', 'Keyframe property'], 'correct' => 1],
            ['question' => 'What is transition used for?', 'options' => ['Transitioning pages', 'Smooth property changes', 'Transition effect', 'Property transition'], 'correct' => 1],
            ['question' => 'What does transform: rotate() do?', 'options' => ['Rotates page', 'Rotates element', 'Rotation effect', 'Transform rotation'], 'correct' => 1],
            ['question' => 'What does transform: scale() do?', 'options' => ['Scales page', 'Scales element size', 'Scaling effect', 'Transform scale'], 'correct' => 1],
            ['question' => 'What does transform: translate() do?', 'options' => ['Translates text', 'Moves element position', 'Translation effect', 'Transform move'], 'correct' => 1],
            ['question' => 'What is clip-path used for?', 'options' => ['Clipping content', 'Creating clipping regions/shapes', 'Path clipping', 'Clip element'], 'correct' => 1],
            ['question' => 'What does filter: blur() do?', 'options' => ['Blurs text', 'Applies blur effect', 'Blur filter', 'Blurred element'], 'correct' => 1],
            ['question' => 'What is mix-blend-mode?', 'options' => ['Mixing colors', 'How element content blends with background', 'Blend effect', 'Mode mixing'], 'correct' => 1],
            ['question' => 'What is a linear-gradient?', 'options' => ['Linear color', 'Gradient along a line', 'Linear effect', 'Gradient line'], 'correct' => 1],
            ['question' => 'What is a radial-gradient?', 'options' => ['Radial color', 'Gradient radiating from center', 'Radial effect', 'Gradient radius'], 'correct' => 1],
            ['question' => 'What does object-fit control?', 'options' => ['Object size', 'How replaced content fits its container', 'Fit property', 'Object fitting'], 'correct' => 1],
            ['question' => 'What is will-change used for?', 'options' => ['Future changes', 'Hints browser about upcoming changes for optimization', 'Change property', 'Will change'], 'correct' => 1],
            ['question' => 'What does contain property do?', 'options' => ['Contains content', 'Provides performance isolation hints', 'Container property', 'Content contain'], 'correct' => 1],
            ['question' => 'What are logical properties?', 'options' => ['Logic-based styles', 'Properties based on writing mode (inline/block)', 'Logical layout', 'Property logic'], 'correct' => 1],
            ['question' => 'What is auto-fit in grid?', 'options' => ['Automatic fitting', 'Fits columns, collapsing empty tracks', 'Auto layout', 'Fit grid'], 'correct' => 1],
            ['question' => 'What is auto-fill in grid?', 'options' => ['Automatic filling', 'Fits columns, keeping empty tracks', 'Auto layout', 'Fill grid'], 'correct' => 1],
            ['question' => 'What does grid-template-areas define?', 'options' => ['Template areas', 'Named grid areas', 'Area template', 'Grid areas'], 'correct' => 1],
            ['question' => 'What is flex-basis?', 'options' => ['Flex base', 'Initial size of flex item', 'Base flex', 'Basis property'], 'correct' => 1],
            ['question' => 'What does align-self do?', 'options' => ['Self alignment', 'Aligns individual flex/grid item', 'Self align', 'Align property'], 'correct' => 1],
            ['question' => 'What is order property in flexbox?', 'options' => ['Order items', 'Controls order of flex items', 'Item order', 'Flex order'], 'correct' => 1],
            ['question' => 'What does isolation property do?', 'options' => ['Isolates element', 'Creates new stacking context', 'Isolation effect', 'Element isolation'], 'correct' => 1],
        ]
    ],
    [
        'label' => 'Advanced',
        'questions' => [
            ['question' => 'What is BEM methodology?', 'options' => ['Best Element Method', 'Block Element Modifier naming convention', 'Better Element Markup', 'Block Enhancement Model'], 'correct' => 1],
            ['question' => 'What is SMACSS?', 'options' => ['Small CSS', 'Scalable and Modular Architecture for CSS', 'Smart CSS', 'Style Module and Class System'], 'correct' => 1],
            ['question' => 'What is the :has() selector?', 'options' => ['Has property', 'Selects parent based on children', 'Has class', 'Selector has'], 'correct' => 1],
            ['question' => 'What does :is() do?', 'options' => ['Is selector', 'Matches any selector in list', 'Is property', 'Identity selector'], 'correct' => 1],
            ['question' => 'What does :where() do?', 'options' => ['Where clause', 'Like :is() but with zero specificity', 'Where selector', 'Location selector'], 'correct' => 1],
            ['question' => 'What is scroll-snap?', 'options' => ['Scroll effect', 'Controls scroll snapping behavior', 'Snap scroll', 'Scroll property'], 'correct' => 1],
            ['question' => 'What are container queries?', 'options' => ['Container size queries', 'Media queries based on container size', 'Query containers', 'Container detection'], 'correct' => 1],
            ['question' => 'What is CSS Houdini?', 'options' => ['Magic CSS', 'Low-level APIs to extend CSS', 'Houdini framework', 'CSS tricks'], 'correct' => 1],
            ['question' => 'What is @layer for?', 'options' => ['Layer styles', 'Cascade layers for managing specificity', 'Layer property', 'CSS layers'], 'correct' => 1],
            ['question' => 'What is aspect-ratio property?', 'options' => ['Ratio aspect', 'Defines preferred aspect ratio', 'Aspect property', 'Ratio setting'], 'correct' => 1],
            ['question' => 'What is subgrid?', 'options' => ['Sub-grid layout', 'Grid item inherits parent grid tracks', 'Nested grid', 'Grid subdivision'], 'correct' => 1],
            ['question' => 'What does overscroll-behavior control?', 'options' => ['Over scrolling', 'Behavior when scrolling beyond boundaries', 'Scroll overflow', 'Overscroll effect'], 'correct' => 1],
            ['question' => 'What is @property used for?', 'options' => ['Property definition', 'Registering custom properties with type/inheritance', 'Property rule', 'CSS property'], 'correct' => 1],
            ['question' => 'What is font-display?', 'options' => ['Font showing', 'Controls how font is displayed while loading', 'Display font', 'Font property'], 'correct' => 1],
            ['question' => 'What is @font-face?', 'options' => ['Font interface', 'Defines custom fonts', 'Face font', 'Font definition'], 'correct' => 1],
            ['question' => 'What is a stacking context?', 'options' => ['Stack context', 'Independent layer for z-index ordering', 'Context stack', 'Stacking order'], 'correct' => 1],
            ['question' => 'What creates a new stacking context?', 'options' => ['Any element', 'Positioned elements with z-index, opacity < 1, transforms, etc.', 'Z-index only', 'Stack property'], 'correct' => 1],
            ['question' => 'What are composite-only animations?', 'options' => ['Combined animations', 'Animations that only affect compositor (transform, opacity)', 'Composite effect', 'Animation composition'], 'correct' => 1],
            ['question' => 'How to prevent CLS with CSS?', 'options' => ['Clear styles', 'Reserve space with size properties, aspect-ratio', 'CLS property', 'Layout prevention'], 'correct' => 1],
            ['question' => 'What is implicit grid?', 'options' => ['Implicit layout', 'Auto-created grid tracks', 'Implied grid', 'Grid implication'], 'correct' => 1],
            ['question' => 'What is explicit grid?', 'options' => ['Explicit layout', 'Defined grid tracks with grid-template', 'Expressed grid', 'Grid definition'], 'correct' => 1],
            ['question' => 'What is native CSS nesting?', 'options' => ['Nested styles', 'Writing selectors inside others (upcoming)', 'Nesting CSS', 'CSS hierarchy'], 'correct' => 1],
            ['question' => 'What is @scope?', 'options' => ['Scope styles', 'Scoped style rules (proposal)', 'Scope definition', 'CSS scope'], 'correct' => 1],
            ['question' => 'What is CSS Typed OM?', 'options' => ['Type system', 'API for typed CSS value manipulation', 'OM typing', 'CSS types'], 'correct' => 1],
            ['question' => 'What is a paint worklet?', 'options' => ['Paint function', 'CSS Houdini API to programmatically draw images', 'Paint worker', 'Worklet painting'], 'correct' => 1],
            ['question' => 'What does :not() selector do?', 'options' => ['Not selector', 'Selects elements that don\'t match', 'Negation', 'Not matching'], 'correct' => 1],
            ['question' => 'What are grid named lines?', 'options' => ['Named grid', 'Custom names for grid lines', 'Line names', 'Grid naming'], 'correct' => 1],
            ['question' => 'What is masonry layout in CSS?', 'options' => ['Brick layout', 'Grid masonry for Pinterest-style layouts', 'Mason layout', 'Masonry grid'], 'correct' => 1],
        ]
    ],
    [
        'label' => 'Expert',
        'questions' => [
            ['question' => 'What is the CSS cascade algorithm?', 'options' => ['Cascading styles', 'Algorithm determining which styles apply (origin, importance, specificity, order)', 'Cascade process', 'Style cascade'], 'correct' => 1],
            ['question' => 'What is specificity calculation?', 'options' => ['Specific calculation', 'Inline(1000), IDs(100), classes/attrs(10), elements(1)', 'Specific weight', 'Selector specificity'], 'correct' => 1],
            ['question' => 'What is the CSSOM?', 'options' => ['CSS Object', 'CSS Object Model - programmatic representation', 'CSS System', 'Object CSS'], 'correct' => 1],
            ['question' => 'What is a reflow?', 'options' => ['Flow again', 'Recalculation of layout', 'Reflowing content', 'Layout reflow'], 'correct' => 1],
            ['question' => 'What is a repaint?', 'options' => ['Paint again', 'Redrawing pixels without layout changes', 'Repainting screen', 'Paint update'], 'correct' => 1],
            ['question' => 'What causes forced synchronous layout?', 'options' => ['Forced layout', 'Reading layout properties after modifying DOM in same frame', 'Synchronous force', 'Layout forcing'], 'correct' => 1],
            ['question' => 'What is layout containment?', 'options' => ['Layout container', 'contain: layout - isolates layout calculations', 'Contained layout', 'Layout isolation'], 'correct' => 1],
            ['question' => 'What is paint containment?', 'options' => ['Paint container', 'contain: paint - isolates painting', 'Contained paint', 'Paint isolation'], 'correct' => 1],
            ['question' => 'What is size containment?', 'options' => ['Size container', 'contain: size - isolates size calculations', 'Contained size', 'Size isolation'], 'correct' => 1],
            ['question' => 'What is style containment?', 'options' => ['Style container', 'contain: style - prevents style side effects', 'Contained style', 'Style isolation'], 'correct' => 1],
            ['question' => 'How does browser compositing work?', 'options' => ['Combining elements', 'Combining painted layers on GPU', 'Composite render', 'Layer composition'], 'correct' => 1],
            ['question' => 'What triggers compositor layer creation?', 'options' => ['Layer request', '3D transforms, will-change, video, canvas, etc.', 'Composite property', 'Layer trigger'], 'correct' => 1],
            ['question' => 'What is the initial value in CSS?', 'options' => ['Initial style', 'Default value defined in CSS spec', 'Starting value', 'Initial property'], 'correct' => 1],
            ['question' => 'What does inherit do?', 'options' => ['Inherits from parent', 'Uses computed value from parent', 'Inheritance', 'Parent value'], 'correct' => 1],
            ['question' => 'What does unset do?', 'options' => ['Unsets value', 'Acts as inherit or initial based on property', 'Remove value', 'Unset property'], 'correct' => 1],
            ['question' => 'What does revert do?', 'options' => ['Reverts change', 'Reverts to user agent stylesheet', 'Revert value', 'Reverting style'], 'correct' => 1],
            ['question' => 'What does revert-layer do?', 'options' => ['Revert layer', 'Reverts to previous cascade layer', 'Layer revert', 'Reverting cascade'], 'correct' => 1],
            ['question' => 'What is critical CSS?', 'options' => ['Critical styles', 'CSS needed for above-the-fold content', 'Important CSS', 'Critical path'], 'correct' => 1],
            ['question' => 'How to extract critical CSS?', 'options' => ['Extract styles', 'Tools like Critical, Penthouse analyze and extract', 'CSS extraction', 'Critical extract'], 'correct' => 1],
            ['question' => 'What is CSS-in-JS performance impact?', 'options' => ['JS performance', 'Runtime cost vs static CSS, bundle size', 'CSS JS speed', 'Performance trade'], 'correct' => 1],
            ['question' => 'What is shadow DOM style encapsulation?', 'options' => ['Shadow styles', 'Styles scoped to shadow tree', 'Encapsulated style', 'Shadow CSS'], 'correct' => 1],
            ['question' => 'How does registerProperty() work?', 'options' => ['Property registration', 'Registers custom property with type, syntax, inheritance', 'Register CSS', 'Property API'], 'correct' => 1],
            ['question' => 'What is layout worklet?', 'options' => ['Layout function', 'CSS Houdini API to define custom layout algorithms', 'Layout worker', 'Worklet layout'], 'correct' => 1],
            ['question' => 'What is the block formatting context?', 'options' => ['Block format', 'Independent layout environment for block boxes', 'Block context', 'Formatting blocks'], 'correct' => 1],
            ['question' => 'What creates a BFC?', 'options' => ['Block element', 'Float, position absolute/fixed, overflow not visible, display flow-root, flex/grid items', 'BFC property', 'Context creation'], 'correct' => 1],
            ['question' => 'What is the inline formatting context?', 'options' => ['Inline format', 'Layout environment for inline boxes', 'Inline context', 'Formatting inline'], 'correct' => 1],
            ['question' => 'What is CSS inheritance?', 'options' => ['Inheriting styles', 'Child elements inherit certain parent properties', 'Style inheritance', 'CSS inherit'], 'correct' => 1],
            ['question' => 'Which properties inherit by default?', 'options' => ['All properties', 'Text-related (color, font-*, text-*, line-height, etc.)', 'No properties', 'Layout properties'], 'correct' => 1],
        ]
    ],
];
require_once __DIR__ . '/quiz-engine.php';
