<?php
$page_title = 'Django Quiz – 100 Levels – CodeFoundry';
$active_page = 'training';
$quiz_title  = 'Django';
$quiz_slug   = 'django';
$quiz_tiers  = [
    [
        'label' => 'Introduction',
        'questions' => [
            ['question' => 'What is Django?', 'options' => ['A JavaScript framework', 'A Python web framework', 'A database', 'A web server'], 'correct' => 1],
            ['question' => 'What pattern does Django follow?', 'options' => ['MVC', 'MTV', 'MVVM', 'Flux'], 'correct' => 1],
            ['question' => 'What does MTV stand for?', 'options' => ['Music Television', 'Model-Template-View', 'Model-Type-View', 'Multiple-Template-View'], 'correct' => 1],
            ['question' => 'How do you create a new Django project?', 'options' => ['django create project', 'django-admin startproject', 'python manage.py create', 'django new'], 'correct' => 1],
            ['question' => 'How do you create a new app?', 'options' => ['django-admin startapp', 'python manage.py startapp', 'django create app', 'python startapp'], 'correct' => 1],
            ['question' => 'Where are project settings stored?', 'options' => ['config.py', 'settings.py', 'setup.py', 'init.py'], 'correct' => 1],
            ['question' => 'What setting lists installed apps?', 'options' => ['APPS', 'INSTALLED_APPS', 'APPLICATIONS', 'APP_LIST'], 'correct' => 1],
            ['question' => 'What setting configures database?', 'options' => ['DB', 'DATABASE', 'DATABASES', 'DB_CONFIG'], 'correct' => 2],
            ['question' => 'What file defines URL patterns?', 'options' => ['routes.py', 'urls.py', 'paths.py', 'routing.py'], 'correct' => 1],
            ['question' => 'What function includes other URL configs?', 'options' => ['import()', 'include()', 'add()', 'extend()'], 'correct' => 1],
            ['question' => 'What file contains view functions?', 'options' => ['controllers.py', 'views.py', 'handlers.py', 'actions.py'], 'correct' => 1],
            ['question' => 'What does HttpResponse return?', 'options' => ['JSON', 'HTTP response', 'HTML only', 'Template'], 'correct' => 1],
            ['question' => 'What function renders templates?', 'options' => ['template()', 'render()', 'display()', 'show()'], 'correct' => 1],
            ['question' => 'How do you output variables in templates?', 'options' => ['<% var %>', '{{ var }}', '{var}', '$var'], 'correct' => 1],
            ['question' => 'How do you use template tags?', 'options' => ['{{ tag }}', '{% tag %}', '<% tag %>', '{# tag #}'], 'correct' => 1],
            ['question' => 'What file defines models?', 'options' => ['database.py', 'models.py', 'schema.py', 'entities.py'], 'correct' => 1],
            ['question' => 'What class do models inherit from?', 'options' => ['Model', 'models.Model', 'BaseModel', 'Entity'], 'correct' => 1],
            ['question' => 'What field type stores text?', 'options' => ['StringField', 'CharField', 'TextField', 'TextType'], 'correct' => 1],
            ['question' => 'What command runs development server?', 'options' => ['python manage.py run', 'python manage.py runserver', 'python manage.py start', 'python manage.py serve'], 'correct' => 1],
            ['question' => 'What command creates migrations?', 'options' => ['python manage.py makemigrations', 'python manage.py create_migrations', 'python manage.py migrate', 'python manage.py migrations'], 'correct' => 0],
            ['question' => 'What command applies migrations?', 'options' => ['python manage.py makemigrations', 'python manage.py migrate', 'python manage.py apply', 'python manage.py update'], 'correct' => 1],
            ['question' => 'What command opens Django shell?', 'options' => ['python manage.py console', 'python manage.py shell', 'python manage.py python', 'python manage.py interactive'], 'correct' => 1],
            ['question' => 'What command creates superuser?', 'options' => ['python manage.py createadmin', 'python manage.py createsuperuser', 'python manage.py superuser', 'python manage.py admin'], 'correct' => 1],
            ['question' => 'How do you register model in admin?', 'options' => ['admin.add()', 'admin.site.register()', 'admin.register()', 'register()'], 'correct' => 1],
            ['question' => 'How do you get all objects?', 'options' => ['Model.all()', 'Model.objects.all()', 'Model.get_all()', 'Model.query.all()'], 'correct' => 1],
            ['question' => 'How do you filter objects?', 'options' => ['Model.filter()', 'Model.objects.filter()', 'Model.where()', 'Model.objects.where()'], 'correct' => 1],
            ['question' => 'How do you get single object?', 'options' => ['Model.objects.get()', 'Model.get()', 'Model.objects.find()', 'Model.find()'], 'correct' => 0],
            ['question' => 'How do you create object?', 'options' => ['Model.create()', 'Model.objects.create()', 'Model.new()', 'Model.objects.new()'], 'correct' => 1],
            ['question' => 'How do you save model instance?', 'options' => ['.save()', '.update()', '.commit()', '.persist()'], 'correct' => 0],
            ['question' => 'How do you delete object?', 'options' => ['.remove()', '.delete()', '.destroy()', '.drop()'], 'correct' => 1],
        ]
    ],
    [
        'label' => 'Beginner',
        'questions' => [
            ['question' => 'What does filter() return?', 'options' => ['List', 'QuerySet', 'Array', 'Dict'], 'correct' => 1],
            ['question' => 'What does exclude() do?', 'options' => ['Removes fields', 'Filters out matching objects', 'Deletes objects', 'Hides objects'], 'correct' => 1],
            ['question' => 'What does values() return?', 'options' => ['QuerySet of dicts', 'List of values', 'Value array', 'Dict'], 'correct' => 0],
            ['question' => 'What does values_list() return?', 'options' => ['QuerySet of tuples', 'List of lists', 'Array', 'Dict'], 'correct' => 0],
            ['question' => 'What does distinct() do?', 'options' => ['Removes all', 'Removes duplicate results', 'Makes unique', 'Filters distinct'], 'correct' => 1],
            ['question' => 'What does order_by() do?', 'options' => ['Sorts QuerySet', 'Orders by ID', 'Arranges fields', 'Groups by'], 'correct' => 0],
            ['question' => 'What does count() return?', 'options' => ['QuerySet', 'Number of objects', 'Count object', 'Array length'], 'correct' => 1],
            ['question' => 'What does exists() return?', 'options' => ['QuerySet', 'Boolean', 'Count', 'Object'], 'correct' => 1],
            ['question' => 'What is ForeignKey?', 'options' => ['Primary key', 'Many-to-one relationship', 'Unique key', 'Index'], 'correct' => 1],
            ['question' => 'What is OneToOneField?', 'options' => ['Single field', 'One-to-one relationship', 'Unique field', 'Primary key'], 'correct' => 1],
            ['question' => 'What is ManyToManyField?', 'options' => ['Multiple fields', 'Many-to-many relationship', 'Array field', 'List field'], 'correct' => 1],
            ['question' => 'What is TextField?', 'options' => ['Short text', 'Large text field', 'Text type', 'String field'], 'correct' => 1],
            ['question' => 'What is IntegerField?', 'options' => ['Int type', 'Integer field', 'Number field', 'Digit field'], 'correct' => 1],
            ['question' => 'What is BooleanField?', 'options' => ['True/false field', 'Boolean type', 'Checkbox', 'Binary field'], 'correct' => 0],
            ['question' => 'What is DateField?', 'options' => ['Date type', 'Date field', 'Timestamp', 'Time field'], 'correct' => 1],
            ['question' => 'What is DateTimeField?', 'options' => ['Date and time field', 'Timestamp', 'DateTime type', 'Time field'], 'correct' => 0],
            ['question' => 'What is EmailField?', 'options' => ['Text field', 'Email validation field', 'Email type', 'Validated text'], 'correct' => 1],
            ['question' => 'What is URLField?', 'options' => ['Text field', 'URL validation field', 'Link field', 'Web field'], 'correct' => 1],
            ['question' => 'What is SlugField?', 'options' => ['Text field', 'URL-friendly string field', 'Slug type', 'ID field'], 'correct' => 1],
            ['question' => 'What is JSONField?', 'options' => ['Text field', 'JSON data field', 'Object field', 'Dict field'], 'correct' => 1],
            ['question' => 'What is ordering in Meta?', 'options' => ['Sort method', 'Default ordering', 'Query order', 'Field order'], 'correct' => 1],
            ['question' => 'What is verbose_name in Meta?', 'options' => ['Long name', 'Human-readable name', 'Display name', 'Full name'], 'correct' => 1],
            ['question' => 'What is TemplateView?', 'options' => ['Template function', 'Renders template', 'Template class', 'View template'], 'correct' => 1],
            ['question' => 'What is ListView?', 'options' => ['List function', 'Displays list of objects', 'List view', 'Object list'], 'correct' => 1],
            ['question' => 'What is DetailView?', 'options' => ['Detail function', 'Displays single object', 'Detail page', 'Object view'], 'correct' => 1],
            ['question' => 'What is CreateView?', 'options' => ['Create function', 'Creates object', 'Create form', 'New object'], 'correct' => 1],
            ['question' => 'What is UpdateView?', 'options' => ['Update function', 'Updates object', 'Edit form', 'Modify view'], 'correct' => 1],
            ['question' => 'What is DeleteView?', 'options' => ['Delete function', 'Deletes object', 'Remove view', 'Delete form'], 'correct' => 1],
            ['question' => 'What is ModelForm?', 'options' => ['Model class', 'Form from model', 'Form type', 'Model validator'], 'correct' => 1],
            ['question' => 'What does path() do in urls?', 'options' => ['Creates path', 'Defines URL pattern', 'URL route', 'Path string'], 'correct' => 1],
        ]
    ],
    [
        'label' => 'Intermediate',
        'questions' => [
            ['question' => 'What is Django REST Framework?', 'options' => ['REST library', 'Toolkit for building APIs', 'API framework', 'REST API'], 'correct' => 1],
            ['question' => 'What is Serializer in DRF?', 'options' => ['JSON converter', 'Converts data to/from JSON', 'Serialization class', 'Data format'], 'correct' => 1],
            ['question' => 'What is ModelSerializer?', 'options' => ['Model converter', 'Serializer from model', 'Auto serializer', 'Model format'], 'correct' => 1],
            ['question' => 'What is ViewSet?', 'options' => ['View collection', 'Combines logic for related views', 'View group', 'API views'], 'correct' => 1],
            ['question' => 'What is Router in DRF?', 'options' => ['URL router', 'Auto-generates URL conf', 'Route mapper', 'URL generator'], 'correct' => 1],
            ['question' => 'What is TokenAuthentication?', 'options' => ['Token system', 'Token-based auth', 'API auth', 'Token login'], 'correct' => 1],
            ['question' => 'What is SessionAuthentication?', 'options' => ['Session system', 'Session-based auth', 'Cookie auth', 'Login session'], 'correct' => 1],
            ['question' => 'What is LoginRequiredMixin?', 'options' => ['Login check', 'Requires authentication', 'Login mixin', 'Auth required'], 'correct' => 1],
            ['question' => 'What is AbstractUser?', 'options' => ['Abstract class', 'Base for custom user', 'User model', 'User template'], 'correct' => 1],
            ['question' => 'What is AbstractBaseUser?', 'options' => ['Base class', 'Minimal custom user base', 'User foundation', 'Basic user'], 'correct' => 1],
            ['question' => 'What is pre_save signal?', 'options' => ['Before save', 'Fired before saving', 'Save trigger', 'Pre-save hook'], 'correct' => 1],
            ['question' => 'What is post_save signal?', 'options' => ['After save', 'Fired after saving', 'Save callback', 'Post-save hook'], 'correct' => 1],
            ['question' => 'What is middleware?', 'options' => ['Middle layer', 'Processes request/response', 'Hook system', 'Interceptor'], 'correct' => 1],
            ['question' => 'What does select_related() do?', 'options' => ['Selects fields', 'SQL JOIN for ForeignKey', 'Related query', 'Select related'], 'correct' => 1],
            ['question' => 'What does prefetch_related() do?', 'options' => ['Prefetches data', 'Separate query for many relations', 'Cache related', 'Load related'], 'correct' => 1],
            ['question' => 'What does only() do?', 'options' => ['Limits to fields', 'Loads only specified fields', 'Field filter', 'Select fields'], 'correct' => 1],
            ['question' => 'What does defer() do?', 'options' => ['Delays load', 'Defers loading fields', 'Lazy load', 'Skip fields'], 'correct' => 1],
            ['question' => 'What is atomic decorator?', 'options' => ['Atomic operation', 'Database transaction', 'Transaction block', 'Atomic query'], 'correct' => 1],
            ['question' => 'What is on_commit()?', 'options' => ['Commit hook', 'Runs after transaction commits', 'Post-commit', 'Commit callback'], 'correct' => 1],
            ['question' => 'What is custom manager?', 'options' => ['Manager class', 'Custom QuerySet methods', 'Object manager', 'Query helper'], 'correct' => 1],
            ['question' => 'What is caching framework?', 'options' => ['Cache system', 'Django caching', 'Cache layer', 'Cache tool'], 'correct' => 1],
            ['question' => 'What cache backend is fastest?', 'options' => ['Database', 'Memcached/Redis', 'File', 'Local memory'], 'correct' => 1],
            ['question' => 'What is per-site cache?', 'options' => ['Site caching', 'Caches entire site', 'Full cache', 'Site-wide cache'], 'correct' => 1],
            ['question' => 'What is per-view cache?', 'options' => ['View caching', 'Caches view output', 'View cache', 'Page cache'], 'correct' => 1],
            ['question' => 'What is Celery?', 'options' => ['Task library', 'Async task queue', 'Background jobs', 'Worker system'], 'correct' => 1],
        ]
    ],
    [
        'label' => 'Advanced',
        'questions' => [
            ['question' => 'What is F() expression?', 'options' => ['Function', 'Field reference', 'Filter', 'Foreign key'], 'correct' => 1],
            ['question' => 'What is Q() object?', 'options' => ['Query', 'Complex query conditions', 'QuerySet', 'Filter object'], 'correct' => 1],
            ['question' => 'What is Subquery?', 'options' => ['Sub-query', 'Nested query expression', 'Inner query', 'Query within query'], 'correct' => 1],
            ['question' => 'What is OuterRef?', 'options' => ['External reference', 'References outer query field', 'Outer join', 'External field'], 'correct' => 1],
            ['question' => 'What is Exists()?', 'options' => ['Existence check', 'Subquery existence test', 'Check query', 'Exists filter'], 'correct' => 1],
            ['question' => 'What is Window expression?', 'options' => ['Window function', 'SQL window functions', 'Windowed query', 'Window calc'], 'correct' => 1],
            ['question' => 'What is Coalesce?', 'options' => ['Combine', 'Returns first non-null', 'Merge', 'Join values'], 'correct' => 1],
            ['question' => 'What is Case/When?', 'options' => ['Switch case', 'Conditional expressions', 'If/else', 'Conditional query'], 'correct' => 1],
            ['question' => 'What is connection.cursor()?', 'options' => ['Database cursor', 'Raw SQL cursor', 'DB connection', 'SQL executor'], 'correct' => 1],
            ['question' => 'What is Model.objects.raw()?', 'options' => ['Raw data', 'Raw SQL query', 'Direct SQL', 'SQL execute'], 'correct' => 1],
            ['question' => 'What are migration operations?', 'options' => ['Migration steps', 'Database change operations', 'Schema changes', 'DB operations'], 'correct' => 1],
            ['question' => 'What is RunSQL operation?', 'options' => ['SQL runner', 'Executes raw SQL in migration', 'SQL migration', 'Custom SQL'], 'correct' => 1],
            ['question' => 'What is RunPython operation?', 'options' => ['Python runner', 'Executes Python in migration', 'Python migration', 'Custom code'], 'correct' => 1],
            ['question' => 'What is squashmigrations?', 'options' => ['Compress migrations', 'Combines migrations', 'Merge migrations', 'Reduce migrations'], 'correct' => 1],
            ['question' => 'What is Django Channels?', 'options' => ['Channel system', 'WebSocket/async support', 'Communication', 'Real-time'], 'correct' => 1],
            ['question' => 'What is ASGI?', 'options' => ['Async server', 'Async Server Gateway Interface', 'Web protocol', 'Async interface'], 'correct' => 1],
            ['question' => 'What are async views?', 'options' => ['Async functions', 'Async def view functions', 'Non-blocking views', 'Concurrent views'], 'correct' => 1],
            ['question' => 'What is CSRF protection?', 'options' => ['Security', 'Cross-site request forgery protection', 'Token system', 'Form security'], 'correct' => 1],
            ['question' => 'How does Django prevent XSS?', 'options' => ['Validation', 'Auto-escaping templates', 'Sanitization', 'Input filtering'], 'correct' => 1],
            ['question' => 'How does Django prevent SQL injection?', 'options' => ['Validation', 'Parameterized queries in ORM', 'Input escape', 'Query sanitization'], 'correct' => 1],
            ['question' => 'What is X-Frame-Options?', 'options' => ['Frame setting', 'Clickjacking protection', 'Header security', 'Frame control'], 'correct' => 1],
            ['question' => 'What is Content Security Policy?', 'options' => ['Content policy', 'XSS protection header', 'Security policy', 'Content rules'], 'correct' => 1],
            ['question' => 'What is gunicorn?', 'options' => ['Web server', 'WSGI HTTP server', 'Python server', 'App server'], 'correct' => 1],
            ['question' => 'What is uwsgi?', 'options' => ['Web server', 'WSGI server', 'Application server', 'Python server'], 'correct' => 1],
            ['question' => 'What is whitenoise?', 'options' => ['Static server', 'Serves static files', 'File server', 'Asset server'], 'correct' => 1],
        ]
    ],
    [
        'label' => 'Expert',
        'questions' => [
            ['question' => 'What is Django request/response cycle?', 'options' => ['Request flow', 'Complete request handling pipeline', 'HTTP cycle', 'Request path'], 'correct' => 1],
            ['question' => 'What is BaseHandler?', 'options' => ['Base class', 'Core request handler', 'Handler base', 'Request processor'], 'correct' => 1],
            ['question' => 'What is middleware chain?', 'options' => ['Middleware list', 'Sequential middleware processing', 'Middleware stack', 'Handler chain'], 'correct' => 1],
            ['question' => 'What is Query object?', 'options' => ['Query builder', 'Internal query representation', 'Query class', 'SQL builder'], 'correct' => 1],
            ['question' => 'What is SQLCompiler?', 'options' => ['SQL compiler', 'Compiles Query to SQL', 'Query compiler', 'SQL generator'], 'correct' => 1],
            ['question' => 'What is deferred loading?', 'options' => ['Lazy loading', 'Delays loading fields', 'Load later', 'Deferred fetch'], 'correct' => 1],
            ['question' => 'What is PgBouncer?', 'options' => ['PostgreSQL tool', 'Connection pooler', 'Database proxy', 'Pool manager'], 'correct' => 1],
            ['question' => 'What is template lexer?', 'options' => ['Template parser', 'Tokenizes template', 'Template scanner', 'Token reader'], 'correct' => 1],
            ['question' => 'What is template Node?', 'options' => ['Template element', 'Compiled template component', 'Template part', 'Render node'], 'correct' => 1],
            ['question' => 'What is ContentType framework?', 'options' => ['Content system', 'Generic relations system', 'Type system', 'Content types'], 'correct' => 1],
            ['question' => 'What is GenericForeignKey?', 'options' => ['Generic relation', 'Relation to any model', 'Any foreign key', 'Generic link'], 'correct' => 1],
            ['question' => 'What is ArrayField?', 'options' => ['Array type', 'PostgreSQL array field', 'List field', 'Array column'], 'correct' => 1],
            ['question' => 'What is HStoreField?', 'options' => ['Hash store', 'PostgreSQL key-value field', 'Dict field', 'Store field'], 'correct' => 1],
            ['question' => 'What is SearchVector?', 'options' => ['Search field', 'Full-text search vector', 'Search index', 'Text search'], 'correct' => 1],
            ['question' => 'What is SearchQuery?', 'options' => ['Search term', 'Full-text search query', 'Query search', 'Search filter'], 'correct' => 1],
            ['question' => 'What is SearchRank?', 'options' => ['Search score', 'Ranks search results', 'Relevance rank', 'Search order'], 'correct' => 1],
            ['question' => 'What is TrigramSimilarity?', 'options' => ['Similarity measure', 'Text similarity function', 'Fuzzy match', 'String similarity'], 'correct' => 1],
            ['question' => 'What is GinIndex?', 'options' => ['Gin index', 'PostgreSQL GIN index', 'Index type', 'Search index'], 'correct' => 1],
            ['question' => 'What is GeoDjango?', 'options' => ['Geography', 'Geographic framework', 'Geo library', 'Spatial Django'], 'correct' => 1],
            ['question' => 'What is custom database backend?', 'options' => ['Custom DB', 'Custom database adapter', 'DB backend', 'Database driver'], 'correct' => 1],
            ['question' => 'What is HTTP/2 support?', 'options' => ['HTTP version', 'HTTP/2 protocol support', 'New HTTP', 'Protocol upgrade'], 'correct' => 1],
            ['question' => 'What is horizontal scaling?', 'options' => ['Scaling out', 'Multiple server instances', 'Distributed', 'Scale horizontal'], 'correct' => 1],
            ['question' => 'What is cache stampede?', 'options' => ['Cache rush', 'Multiple simultaneous cache misses', 'Cache overload', 'Cache problem'], 'correct' => 1],
            ['question' => 'What are read replicas?', 'options' => ['Read copies', 'Database read copies', 'Replica databases', 'Read-only DB'], 'correct' => 1],
            ['question' => 'What is zero-downtime deployment?', 'options' => ['No downtime', 'Deploy without downtime', 'Continuous deploy', 'Live deploy'], 'correct' => 1],
        ]
    ],
];
require_once __DIR__ . '/quiz-engine.php';
