<?php
$page_title = 'Docker Quiz – 100 Levels – CodeFoundry';
$active_page = 'training';
$quiz_title  = 'Docker';
$quiz_slug   = 'docker';
$quiz_tiers  = [
    [
        'label' => 'Introduction',
        'questions' => [
            ['question' => 'What is Docker?', 'options' => ['A virtual machine manager', 'A platform for developing, shipping, and running applications in containers', 'A cloud hosting service', 'A Linux kernel'], 'correct' => 1],
            ['question' => 'What is a Docker container?', 'options' => ['A virtual machine', 'A lightweight, standalone executable package that includes code and dependencies', 'A Docker image', 'A Docker registry'], 'correct' => 1],
            ['question' => 'How do containers differ from virtual machines?', 'options' => ['Containers are slower', 'Containers share the host OS kernel and are more lightweight than VMs', 'Containers require a hypervisor', 'Containers have their own OS kernel'], 'correct' => 1],
            ['question' => 'What is Docker Hub?', 'options' => ['A Docker command', 'A cloud-based registry for sharing Docker images', 'A Docker network', 'A Docker volume'], 'correct' => 1],
            ['question' => 'Which command pulls an image from Docker Hub?', 'options' => ['docker get', 'docker fetch', 'docker pull', 'docker download'], 'correct' => 2],
            ['question' => 'Which command runs a Docker container?', 'options' => ['docker start', 'docker run', 'docker exec', 'docker launch'], 'correct' => 1],
            ['question' => 'Which command lists running containers?', 'options' => ['docker list', 'docker containers', 'docker ps', 'docker show'], 'correct' => 2],
            ['question' => 'Which command lists all containers including stopped ones?', 'options' => ['docker ps -a', 'docker ps --all', 'docker list -a', 'docker ps -a and docker ps --all'], 'correct' => 3],
            ['question' => 'Which command lists locally available Docker images?', 'options' => ['docker images', 'docker list images', 'docker show images', 'docker pull --list'], 'correct' => 0],
            ['question' => 'What is a Dockerfile?', 'options' => ['A running container', 'A Docker registry', 'A text file with instructions to build a Docker image', 'A Docker volume'], 'correct' => 2],
            ['question' => 'What does the FROM instruction do in a Dockerfile?', 'options' => ['Copies files into the image', 'Sets the base image for subsequent instructions', 'Runs a command in the image', 'Specifies metadata'], 'correct' => 1],
            ['question' => 'What does the RUN instruction do in a Dockerfile?', 'options' => ['Runs the container', 'Executes a command during the image build process', 'Sets the default command', 'Copies files'], 'correct' => 1],
            ['question' => 'What does the CMD instruction do in a Dockerfile?', 'options' => ['Copies files into the container', 'Provides the default command to run when a container starts', 'Runs a command during build', 'Sets environment variables'], 'correct' => 1],
            ['question' => 'What does the COPY instruction do in a Dockerfile?', 'options' => ['Copies files from the host into the image', 'Copies containers', 'Duplicates layers', 'Copies environment variables'], 'correct' => 0],
            ['question' => 'What is a Docker image?', 'options' => ['A running instance of a container', 'A read-only template used to create containers', 'A Docker Hub account', 'A Dockerfile'], 'correct' => 1],
            ['question' => 'What is the relationship between an image and a container?', 'options' => ['They are the same thing', 'A container is a running instance of an image', 'An image is a running instance of a container', 'They are unrelated'], 'correct' => 1],
            ['question' => 'Which command removes a Docker image?', 'options' => ['docker delete', 'docker rm', 'docker rmi', 'docker remove image'], 'correct' => 2],
            ['question' => 'Which command removes a stopped container?', 'options' => ['docker rmi', 'docker delete', 'docker rm', 'docker remove'], 'correct' => 2],
            ['question' => 'What flag runs a container in detached (background) mode?', 'options' => ['-b', '-d', '-bg', '-detach'], 'correct' => 1],
            ['question' => 'What does "docker run -it" do?', 'options' => ['Runs in background', 'Runs with interactive terminal', 'Runs with internet access', 'Runs with isolation'], 'correct' => 1],
            ['question' => 'What is the default Docker registry?', 'options' => ['Docker Store', 'Docker Hub (hub.docker.com)', 'GitHub Container Registry', 'Amazon ECR'], 'correct' => 1],
            ['question' => 'What command stops a running container?', 'options' => ['docker kill', 'docker pause', 'docker stop', 'docker halt'], 'correct' => 2],
            ['question' => 'What is the EXPOSE instruction in a Dockerfile?', 'options' => ['Opens a port on the host', 'Documents which port the container listens on at runtime', 'Forces port binding', 'Exposes environment variables'], 'correct' => 1],
            ['question' => 'Which command shows Docker version information?', 'options' => ['docker info', 'docker --version', 'docker version', 'docker --version and docker version both work'], 'correct' => 3],
            ['question' => 'What is the purpose of the .dockerignore file?', 'options' => ['Ignores Docker warnings', 'Lists files and directories to exclude from the build context', 'Ignores Docker commands', 'Disables Docker features'], 'correct' => 1],
        ],
    ],
    [
        'label' => 'Beginner',
        'questions' => [
            ['question' => 'Which command builds a Docker image from a Dockerfile?', 'options' => ['docker create', 'docker build', 'docker make', 'docker compile'], 'correct' => 1],
            ['question' => 'What flag tags an image during docker build?', 'options' => ['-name', '-t', '-tag', '-label'], 'correct' => 1],
            ['question' => 'Which command starts a stopped container?', 'options' => ['docker run', 'docker resume', 'docker start', 'docker launch'], 'correct' => 2],
            ['question' => 'How do you map host port 8080 to container port 80?', 'options' => ['docker run -p 80:8080', 'docker run -p 8080:80', 'docker run --port 8080:80', 'docker run -P 8080:80'], 'correct' => 1],
            ['question' => 'Which flag mounts a host directory as a volume?', 'options' => ['-m', '-v', '--volume-mount', '-vol'], 'correct' => 1],
            ['question' => 'How do you pass an environment variable to a container?', 'options' => ['docker run --env', 'docker run -e KEY=VALUE', 'docker run --set KEY=VALUE', 'docker run -env KEY=VALUE'], 'correct' => 1],
            ['question' => 'Which command executes a command inside a running container?', 'options' => ['docker run', 'docker attach', 'docker exec', 'docker inject'], 'correct' => 2],
            ['question' => 'Which command shows logs of a container?', 'options' => ['docker output', 'docker logs', 'docker print', 'docker trace'], 'correct' => 1],
            ['question' => 'Which command shows detailed info about a container or image?', 'options' => ['docker detail', 'docker describe', 'docker info', 'docker inspect'], 'correct' => 3],
            ['question' => 'How do you name a container when running it?', 'options' => ['docker run -n myname', 'docker run --name myname', 'docker run --label myname', 'docker run -id myname'], 'correct' => 1],
            ['question' => 'What does "docker stop" send to a container first?', 'options' => ['SIGKILL', 'SIGTERM', 'SIGINT', 'SIGHUP'], 'correct' => 1],
            ['question' => 'What does "docker kill" do differently than "docker stop"?', 'options' => ['They are identical', 'docker kill immediately sends SIGKILL without waiting', 'docker kill is slower', 'docker kill removes the container'], 'correct' => 1],
            ['question' => 'Which command tags an existing image with a new name?', 'options' => ['docker rename', 'docker tag', 'docker label', 'docker alias'], 'correct' => 1],
            ['question' => 'How do you push an image to Docker Hub?', 'options' => ['docker upload', 'docker publish', 'docker push', 'docker deploy'], 'correct' => 2],
            ['question' => 'What does the "-P" flag do in "docker run -P"?', 'options' => ['Enables privileged mode', 'Publishes all exposed ports to random host ports', 'Sets a password', 'Enables port scanning'], 'correct' => 1],
            ['question' => 'What command removes all stopped containers?', 'options' => ['docker rm -a', 'docker container prune', 'docker clean', 'docker purge'], 'correct' => 1],
            ['question' => 'What command pauses a running container?', 'options' => ['docker stop', 'docker hold', 'docker pause', 'docker freeze'], 'correct' => 2],
            ['question' => 'How do you follow container logs in real time?', 'options' => ['docker logs -r', 'docker logs -f', 'docker logs --tail', 'docker logs -w'], 'correct' => 1],
            ['question' => 'What does "docker exec -it <id> /bin/bash" do?', 'options' => ['Starts a new container', 'Opens an interactive bash shell in a running container', 'Builds an image', 'Attaches to container output'], 'correct' => 1],
            ['question' => 'What is a Docker volume used for?', 'options' => ['Networking between containers', 'Persisting data generated by containers', 'Limiting CPU usage', 'Image compression'], 'correct' => 1],
            ['question' => 'Which command creates a named Docker volume?', 'options' => ['docker volume create', 'docker create volume', 'docker volume new', 'docker make volume'], 'correct' => 0],
            ['question' => 'How do you remove an image that has dependent containers?', 'options' => ['docker rmi --clean', 'docker rmi --force', 'docker remove --hard', 'docker image delete'], 'correct' => 1],
            ['question' => 'What is the ENTRYPOINT instruction in a Dockerfile?', 'options' => ['Entry point for network', 'Configures the container to run as an executable', 'Sets the working directory', 'Defines build arguments'], 'correct' => 1],
            ['question' => 'What is the WORKDIR instruction in a Dockerfile?', 'options' => ['Sets the CPU affinity', 'Sets the working directory for subsequent instructions', 'Defines the work queue', 'Specifies work threads'], 'correct' => 1],
            ['question' => 'Which command lists all Docker volumes?', 'options' => ['docker volume ls', 'docker list volumes', 'docker volumes', 'docker show volumes'], 'correct' => 0],
        ],
    ],
    [
        'label' => 'Intermediate',
        'questions' => [
            ['question' => 'What is Docker Compose?', 'options' => ['A Docker image', 'A tool for defining and running multi-container Docker applications', 'A container orchestrator', 'A Docker plugin'], 'correct' => 1],
            ['question' => 'What file does Docker Compose use by default?', 'options' => ['docker-compose.json', 'compose.yaml', 'docker-compose.yml', 'docker.yml'], 'correct' => 2],
            ['question' => 'Which command starts services defined in docker-compose.yml?', 'options' => ['docker-compose run', 'docker-compose start', 'docker-compose up', 'docker-compose build'], 'correct' => 2],
            ['question' => 'Which command stops and removes containers from docker-compose?', 'options' => ['docker-compose stop', 'docker-compose rm', 'docker-compose down', 'docker-compose kill'], 'correct' => 2],
            ['question' => 'What does the "services" key define in docker-compose.yml?', 'options' => ['Docker volumes', 'The containers to run as part of the application', 'Network configurations', 'Environment variables'], 'correct' => 1],
            ['question' => 'How do you define a network in docker-compose.yml?', 'options' => ['Under the "connections" key', 'Under the "networks" key', 'Under the "services" key', 'Under the "links" key'], 'correct' => 1],
            ['question' => 'What is a multi-stage Docker build?', 'options' => ['Building multiple images at once', 'A Dockerfile with multiple FROM instructions to reduce final image size', 'A parallel build process', 'A multi-threaded build'], 'correct' => 1],
            ['question' => 'What is the default network driver in Docker?', 'options' => ['host', 'overlay', 'bridge', 'macvlan'], 'correct' => 2],
            ['question' => 'What does the "host" network mode do?', 'options' => ['Creates a separate network', 'Shares the host machine network stack with the container', 'Disables networking', 'Uses a virtual network'], 'correct' => 1],
            ['question' => 'What does the "none" network mode do?', 'options' => ['Uses no CPU', 'Disables all networking for the container', 'Connects to default network', 'Creates an empty network'], 'correct' => 1],
            ['question' => 'What is a HEALTHCHECK instruction in a Dockerfile?', 'options' => ['Checks Docker version', 'Tells Docker how to test if a container is still working', 'Validates the Dockerfile syntax', 'Checks disk health'], 'correct' => 1],
            ['question' => 'What is the difference between a named volume and a bind mount?', 'options' => ['They are identical', 'Named volumes are managed by Docker; bind mounts link to a specific host path', 'Bind mounts are managed by Docker', 'Named volumes only work on Linux'], 'correct' => 1],
            ['question' => 'What does "depends_on" do in docker-compose.yml?', 'options' => ['Defines service dependencies and start order', 'Installs dependencies', 'Links containers directly', 'Sets environment dependencies'], 'correct' => 0],
            ['question' => 'How do you scale a service to 3 replicas with Docker Compose?', 'options' => ['docker-compose scale web=3', 'docker-compose up --scale web=3', 'docker-compose run web 3', 'docker-compose replicate web 3'], 'correct' => 1],
            ['question' => 'What is an overlay network used for?', 'options' => ['Single-host container communication', 'Connecting containers across multiple Docker hosts (Swarm)', 'Connecting to external networks', 'Overlaying IP addresses'], 'correct' => 1],
            ['question' => 'What does the ARG instruction do in a Dockerfile?', 'options' => ['Sets runtime environment variables', 'Defines build-time variables passed with --build-arg', 'Stores arguments for CMD', 'Creates argument files'], 'correct' => 1],
            ['question' => 'What is a Docker layer cache?', 'options' => ['A cache for Docker Hub downloads', 'Reuse of previously built image layers to speed up subsequent builds', 'A disk cache for containers', 'A network cache'], 'correct' => 1],
            ['question' => 'What does the ENV instruction do in a Dockerfile?', 'options' => ['Sets build arguments', 'Sets environment variables that persist in the container', 'Enables environment mode', 'Lists environment modules'], 'correct' => 1],
            ['question' => 'What is a Docker registry?', 'options' => ['A list of Docker commands', 'A storage and distribution system for Docker images', 'Docker\'s config file', 'A container monitoring tool'], 'correct' => 1],
            ['question' => 'What does "docker network ls" show?', 'options' => ['Containers on a network', 'All Docker networks on the host', 'Network traffic stats', 'IP addresses of containers'], 'correct' => 1],
            ['question' => 'What is tmpfs mount in Docker?', 'options' => ['A persistent volume', 'A mount stored in the host memory, not written to disk', 'A temporary Dockerfile', 'A temporary registry'], 'correct' => 1],
            ['question' => 'How do you rebuild images when running docker-compose up?', 'options' => ['docker-compose up --force', 'docker-compose up --build', 'docker-compose rebuild', 'docker-compose up --new'], 'correct' => 1],
            ['question' => 'What does the USER instruction do in a Dockerfile?', 'options' => ['Adds a system user to the host', 'Sets the user name/UID to use when running the image', 'Defines user environment', 'Creates a user account'], 'correct' => 1],
            ['question' => 'What is the purpose of "docker system prune"?', 'options' => ['Removes the Docker daemon', 'Removes all unused containers, images, networks and build cache', 'Resets Docker settings', 'Prunes running containers'], 'correct' => 1],
            ['question' => 'Which Compose key maps host ports to service ports?', 'options' => ['expose', 'ports', 'network', 'bindings'], 'correct' => 1],
        ],
    ],
    [
        'label' => 'Advanced',
        'questions' => [
            ['question' => 'What is Docker Swarm?', 'options' => ['A Docker plugin', 'Docker\'s native clustering and orchestration tool for managing a cluster of Docker hosts', 'A container registry', 'A network driver'], 'correct' => 1],
            ['question' => 'What is a Swarm manager node?', 'options' => ['A node running containers only', 'A node that maintains cluster state and dispatches tasks to worker nodes', 'An admin interface', 'A load balancer'], 'correct' => 1],
            ['question' => 'How do you initialise a Docker Swarm?', 'options' => ['docker swarm create', 'docker swarm start', 'docker swarm init', 'docker cluster init'], 'correct' => 2],
            ['question' => 'What is a Docker secret?', 'options' => ['A hidden environment variable', 'Sensitive data (passwords, keys) managed securely by Docker Swarm', 'An encrypted image layer', 'A private Docker Hub repo'], 'correct' => 1],
            ['question' => 'How do you create a Docker secret?', 'options' => ['docker secret create', 'docker create secret', 'docker secret add', 'docker new secret'], 'correct' => 0],
            ['question' => 'What does --memory flag do in docker run?', 'options' => ['Sets swap memory', 'Sets a hard memory limit for the container', 'Shows memory usage', 'Allocates memory at startup'], 'correct' => 1],
            ['question' => 'What does --cpus flag do in docker run?', 'options' => ['Shows CPU usage', 'Limits the number of CPUs the container can use', 'Sets CPU priority', 'Pins to specific CPU'], 'correct' => 1],
            ['question' => 'What is BuildKit in Docker?', 'options' => ['A Docker plugin', 'An improved build backend with better caching, parallel builds, and secrets', 'A base image', 'A Dockerfile linter'], 'correct' => 1],
            ['question' => 'How do you enable BuildKit for a build?', 'options' => ['docker build --buildkit', 'DOCKER_BUILDKIT=1 docker build', 'docker build --enable-buildkit', 'docker buildkit build'], 'correct' => 1],
            ['question' => 'What is layer caching strategy for optimal builds?', 'options' => ['Put frequently changing instructions first', 'Put rarely changing instructions first (e.g. dependency installs before copying source)', 'Disable caching entirely', 'Always use --no-cache'], 'correct' => 1],
            ['question' => 'What is a private Docker registry?', 'options' => ['A locked Docker Hub repo', 'A self-hosted registry for storing images internally', 'A read-only registry', 'A registry with authentication only'], 'correct' => 1],
            ['question' => 'How do you run the official Docker Registry image locally?', 'options' => ['docker run registry', 'docker run -d -p 5000:5000 registry:2', 'docker start local-registry', 'docker pull registry --local'], 'correct' => 1],
            ['question' => 'What is image optimization in Docker?', 'options' => ['Making images run faster', 'Reducing image size using minimal base images, multi-stage builds, and combining RUN commands', 'Optimising CPU usage', 'Compressing container memory'], 'correct' => 1],
            ['question' => 'Why should RUN commands be chained with && in a Dockerfile?', 'options' => ['For faster execution', 'To reduce the number of layers and keep intermediate files out of the image', 'To ensure order', 'To avoid errors'], 'correct' => 1],
            ['question' => 'What is an overlay network in Swarm mode?', 'options' => ['A host network overlay', 'A distributed network that spans multiple Docker hosts in a Swarm cluster', 'A virtual LAN', 'An IP tunnel'], 'correct' => 1],
            ['question' => 'Which command deploys a stack in Docker Swarm?', 'options' => ['docker stack run', 'docker swarm deploy', 'docker stack deploy', 'docker deploy stack'], 'correct' => 2],
            ['question' => 'What does the --replicas flag do in docker service create?', 'options' => ['Backs up the service', 'Sets the number of replica tasks for the service', 'Replicates volumes', 'Creates mirror services'], 'correct' => 1],
            ['question' => 'What is a Docker service in Swarm mode?', 'options' => ['A running container', 'The definition of tasks to execute on the Swarm, with desired state', 'A Swarm worker', 'A Docker image'], 'correct' => 1],
            ['question' => 'What is a rolling update in Docker Swarm?', 'options' => ['Updating the host OS', 'Updating service tasks incrementally without downtime', 'Rolling back to previous version', 'Updating images in parallel'], 'correct' => 1],
            ['question' => 'What is the purpose of the --no-cache flag in docker build?', 'options' => ['Disables BuildKit', 'Forces a fresh build ignoring all cached layers', 'Removes the image cache', 'Disables layer storage'], 'correct' => 1],
            ['question' => 'What does ONBUILD do in a Dockerfile?', 'options' => ['Runs on container start', 'Adds instructions that execute when the image is used as a base for another build', 'Triggers on health check', 'Runs on image pull'], 'correct' => 1],
            ['question' => 'What is a Docker config object in Swarm?', 'options' => ['Docker daemon configuration', 'Non-sensitive configuration data stored in Swarm and mounted into services', 'A service config file', 'A Swarm setting'], 'correct' => 1],
            ['question' => 'What does "docker service scale" do?', 'options' => ['Adjusts container memory', 'Changes the number of replicas for one or more services', 'Scales resource limits', 'Scales the Swarm cluster'], 'correct' => 1],
            ['question' => 'What is the ingress network in Docker Swarm?', 'options' => ['An external network', 'The special overlay network that handles incoming traffic and load balances across service replicas', 'A management network', 'A private network'], 'correct' => 1],
            ['question' => 'What does "docker node ls" show?', 'options' => ['Container list', 'All nodes in the Docker Swarm cluster', 'Network nodes', 'Volume nodes'], 'correct' => 1],
        ],
    ],
    [
        'label' => 'Expert',
        'questions' => [
            ['question' => 'Which Linux kernel feature do containers use for process isolation?', 'options' => ['Hypervisor', 'Namespaces', 'SELinux only', 'iptables'], 'correct' => 1],
            ['question' => 'Which Linux kernel feature does Docker use for resource limits (CPU, memory)?', 'options' => ['Namespaces', 'cgroups (control groups)', 'seccomp', 'AppArmor'], 'correct' => 1],
            ['question' => 'What union filesystem does Docker use by default on modern Linux?', 'options' => ['AUFS', 'overlay2', 'devicemapper', 'btrfs'], 'correct' => 1],
            ['question' => 'What is containerd?', 'options' => ['A Docker command', 'An industry-standard container runtime that manages container lifecycle', 'A container registry', 'A network driver'], 'correct' => 1],
            ['question' => 'What is the OCI (Open Container Initiative)?', 'options' => ['A Docker company', 'An open governance structure that defines container image and runtime specifications', 'An orchestration tool', 'A cloud provider standard'], 'correct' => 1],
            ['question' => 'What is the OCI image specification?', 'options' => ['A Docker Hub standard', 'A standard defining how container images are structured and stored', 'A Kubernetes spec', 'A runtime configuration'], 'correct' => 1],
            ['question' => 'What is rootless Docker?', 'options' => ['Docker running without a registry', 'Running the Docker daemon and containers without root privileges', 'Docker with no base image', 'Docker with restricted commands'], 'correct' => 1],
            ['question' => 'What is Docker Content Trust (DCT)?', 'options' => ['A billing feature', 'A security feature using digital signatures to verify image integrity and publisher', 'A network trust policy', 'A container audit log'], 'correct' => 1],
            ['question' => 'What is the Docker socket (/var/run/docker.sock)?', 'options' => ['A network socket for containers', 'The Unix socket the Docker daemon listens on for API requests', 'A log file', 'A volume mount point'], 'correct' => 1],
            ['question' => 'Why is mounting the Docker socket into a container a security risk?', 'options' => ['It slows the container', 'It gives the container full control over the Docker daemon, enabling container escape', 'It exposes environment variables', 'It blocks network access'], 'correct' => 1],
            ['question' => 'What is runc?', 'options' => ['A Docker compose tool', 'A low-level CLI tool for spawning and running containers per the OCI runtime spec', 'A registry client', 'A networking utility'], 'correct' => 1],
            ['question' => 'What does seccomp do in Docker container security?', 'options' => ['Encrypts container data', 'Restricts system calls available to processes in a container', 'Secures container networking', 'Manages secrets'], 'correct' => 1],
            ['question' => 'What is AppArmor in the context of Docker?', 'options' => ['A Docker plugin', 'A Linux kernel security module that restricts container capabilities via profiles', 'An image signing tool', 'A Swarm security feature'], 'correct' => 1],
            ['question' => 'What does --cap-drop do in docker run?', 'options' => ['Drops network packets', 'Removes Linux capabilities from a container to reduce its privileges', 'Drops volume mounts', 'Reduces CPU allocation'], 'correct' => 1],
            ['question' => 'How does Kubernetes differ from Docker Swarm?', 'options' => ['They are identical', 'Kubernetes is more feature-rich with auto-scaling, self-healing, and richer scheduling; Swarm is simpler', 'Docker Swarm supports more nodes', 'Kubernetes only supports Docker containers'], 'correct' => 1],
            ['question' => 'What is the GMP model in Go\'s scheduler? (relates to Docker\'s use of Go)', 'options' => ['A Docker network model', 'Go\'s concurrency scheduler using Goroutines, M (OS threads), and P (processors)', 'A Docker container model', 'A GPU memory model'], 'correct' => 1],
            ['question' => 'What is the purpose of BuildKit\'s --secret mount?', 'options' => ['Stores secrets in the image', 'Mounts secrets during build that are NOT stored in the final image layers', 'Encrypts the image', 'Adds secrets to environment'], 'correct' => 1],
            ['question' => 'What does the STOPSIGNAL instruction in a Dockerfile set?', 'options' => ['Sets CPU stop threshold', 'Sets the system call signal sent to the container to stop it', 'Defines stop timeout', 'Stops build on error'], 'correct' => 1],
            ['question' => 'What is Notary in Docker\'s trust framework?', 'options' => ['A billing notary', 'A tool for publishing and managing trusted collections of content using TUF (The Update Framework)', 'A network notary', 'A certificate authority'], 'correct' => 1],
            ['question' => 'What is the difference between COPY and ADD in a Dockerfile?', 'options' => ['They are identical', 'ADD can fetch remote URLs and auto-extract compressed files; COPY only copies local files', 'COPY supports remote URLs', 'ADD is deprecated'], 'correct' => 1],
            ['question' => 'What is the init process issue in containers and how does --init help?', 'options' => ['PID 1 must handle zombie reaping; --init runs a tiny init process (tini) as PID 1', 'Containers have no init process by default', 'init slows container startup', '--init enables systemd in containers'], 'correct' => 0],
            ['question' => 'What is Docker\'s default logging driver?', 'options' => ['syslog', 'journald', 'json-file', 'fluentd'], 'correct' => 2],
            ['question' => 'What does --read-only flag do in docker run?', 'options' => ['Makes logs read-only', 'Mounts the container root filesystem as read-only', 'Prevents image pulls', 'Makes volumes read-only'], 'correct' => 1],
            ['question' => 'What is the purpose of the LABEL instruction in a Dockerfile?', 'options' => ['Labels containers at runtime', 'Adds metadata key-value pairs to the image', 'Marks image as official', 'Labels network interfaces'], 'correct' => 1],
            ['question' => 'What Linux feature underlies overlay filesystems used by Docker?', 'options' => ['FUSE', 'OverlayFS kernel module which merges upper and lower directory layers', 'NFS', 'tmpfs'], 'correct' => 1],
        ],
    ],
];
require_once __DIR__ . '/quiz-engine.php';
