<?php
$page_title = 'DSA Quiz – 100 Levels – CodeFoundry';
$active_page = 'training';
$quiz_title  = 'DSA';
$quiz_slug   = 'dsa';
$quiz_tiers  = [
    [
        'label' => 'Introduction',
        'questions' => [
            ['question' => 'What is an array?', 'options' => ['A collection of key-value pairs', 'A contiguous block of memory storing elements of the same type', 'A dynamic list that resizes automatically', 'A tree-based data structure'], 'correct' => 1],
            ['question' => 'What is the time complexity of accessing an element by index in an array?', 'options' => ['O(n)', 'O(log n)', 'O(1)', 'O(n&sup2;)'], 'correct' => 2],
            ['question' => 'What data structure follows LIFO (Last In, First Out) order?', 'options' => ['Queue', 'Stack', 'Array', 'Linked List'], 'correct' => 1],
            ['question' => 'What data structure follows FIFO (First In, First Out) order?', 'options' => ['Stack', 'Queue', 'Tree', 'Hash Table'], 'correct' => 1],
            ['question' => 'What does Big O notation describe?', 'options' => ['The exact runtime of an algorithm', 'The upper bound on the growth rate of an algorithm', 'The memory used by a program', 'The number of lines of code'], 'correct' => 1],
            ['question' => 'What is the time complexity of searching for an element in an unsorted array?', 'options' => ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], 'correct' => 2],
            ['question' => 'What is a linked list?', 'options' => ['An array with extra memory', 'A data structure where each node contains data and a pointer to the next node', 'A fixed-size collection', 'A stack implemented with arrays'], 'correct' => 1],
            ['question' => 'Which operation adds an element to a stack?', 'options' => ['enqueue', 'push', 'insert', 'add'], 'correct' => 1],
            ['question' => 'Which operation removes an element from a stack?', 'options' => ['dequeue', 'delete', 'pop', 'remove'], 'correct' => 2],
            ['question' => 'What is the head of a linked list?', 'options' => ['The last node', 'The middle node', 'The first node', 'The largest node'], 'correct' => 2],
            ['question' => 'What is the time complexity of inserting at the beginning of a singly linked list?', 'options' => ['O(n)', 'O(log n)', 'O(n&sup2;)', 'O(1)'], 'correct' => 3],
            ['question' => 'What is O(1) time complexity called?', 'options' => ['Linear time', 'Logarithmic time', 'Constant time', 'Quadratic time'], 'correct' => 2],
            ['question' => 'What is O(n) time complexity called?', 'options' => ['Constant time', 'Linear time', 'Quadratic time', 'Logarithmic time'], 'correct' => 1],
            ['question' => 'What does enqueue mean for a queue?', 'options' => ['Remove from front', 'Remove from back', 'Add to the back', 'Add to the front'], 'correct' => 2],
            ['question' => 'What does dequeue mean for a queue?', 'options' => ['Remove from the front', 'Add to the back', 'Check the front element', 'Clear the queue'], 'correct' => 0],
            ['question' => 'What is a doubly linked list?', 'options' => ['A list with two arrays', 'A list where each node has pointers to both next and previous nodes', 'A list with double the capacity', 'A circular linked list'], 'correct' => 1],
            ['question' => 'What is the main disadvantage of an array compared to a linked list?', 'options' => ['Arrays cannot store numbers', 'Arrays have fixed size and insertion/deletion is costly', 'Arrays are always slower', 'Arrays use more memory per element'], 'correct' => 1],
            ['question' => 'What is a circular linked list?', 'options' => ['A linked list shaped like a circle in memory', 'A linked list where the last node points back to the head', 'A doubly linked list', 'A linked list with no head'], 'correct' => 1],
            ['question' => 'Which data structure is commonly used to implement function call management?', 'options' => ['Queue', 'Array', 'Stack', 'Hash Table'], 'correct' => 2],
            ['question' => 'What is O(n&sup2;) time complexity called?', 'options' => ['Quadratic time', 'Linear time', 'Cubic time', 'Polynomial time'], 'correct' => 0],
            ['question' => 'What is the "peek" operation on a stack?', 'options' => ['Removes the top element', 'Adds an element', 'Views the top element without removing it', 'Clears the stack'], 'correct' => 2],
            ['question' => 'What is a priority queue?', 'options' => ['A queue where elements are served in FIFO order only', 'A queue where each element has a priority and higher priority elements are served first', 'A stack disguised as a queue', 'A queue with duplicate elements removed'], 'correct' => 1],
            ['question' => 'What is the time complexity of deletion at the end of a singly linked list (without tail pointer)?', 'options' => ['O(1)', 'O(log n)', 'O(n)', 'O(n&sup2;)'], 'correct' => 2],
            ['question' => 'What is a sparse array?', 'options' => ['An array that stores negative values', 'An array where most elements are zero or empty', 'An unsorted array', 'An array with no fixed size'], 'correct' => 1],
            ['question' => 'Which of the following is NOT a linear data structure?', 'options' => ['Array', 'Linked List', 'Queue', 'Binary Tree'], 'correct' => 3],
            ['question' => 'What does the term "overflow" mean in the context of a stack?', 'options' => ['Stack has too many data types', 'Attempt to push onto a full stack', 'Attempt to pop from a full stack', 'Stack elements are overwritten'], 'correct' => 1],
            ['question' => 'What is the advantage of a linked list over an array for insertions?', 'options' => ['Faster random access', 'Better cache performance', 'O(1) insertion at known position (no shifting needed)', 'Less memory usage'], 'correct' => 2],
        ],
    ],
    [
        'label' => 'Beginner',
        'questions' => [
            ['question' => 'What is the prerequisite for binary search?', 'options' => ['Data must be linked', 'Data must be sorted', 'Data must be unique', 'Data must be in a hash table'], 'correct' => 1],
            ['question' => 'What is the time complexity of binary search?', 'options' => ['O(n)', 'O(n&sup2;)', 'O(log n)', 'O(1)'], 'correct' => 2],
            ['question' => 'How does bubble sort work?', 'options' => ['Picks minimum and moves to front', 'Repeatedly swaps adjacent elements if they are in wrong order', 'Divides and conquers', 'Inserts each element in correct position'], 'correct' => 1],
            ['question' => 'What is the worst-case time complexity of bubble sort?', 'options' => ['O(n log n)', 'O(n)', 'O(n&sup2;)', 'O(log n)'], 'correct' => 2],
            ['question' => 'What does selection sort do in each pass?', 'options' => ['Swaps all adjacent elements', 'Finds the minimum element and places it in its correct position', 'Inserts element in sorted portion', 'Merges two sorted halves'], 'correct' => 1],
            ['question' => 'What is insertion sort best at?', 'options' => ['Large unsorted arrays', 'Nearly sorted arrays', 'Reverse-sorted data', 'Random data of any size'], 'correct' => 1],
            ['question' => 'What is a binary tree?', 'options' => ['A tree where each node has exactly two children', 'A tree where each node has at most two children', 'A tree with two levels only', 'A tree sorted in binary order'], 'correct' => 1],
            ['question' => 'What is the root of a tree?', 'options' => ['The node with no children', 'The topmost node with no parent', 'The leftmost node', 'The node with the most children'], 'correct' => 1],
            ['question' => 'What is a leaf node in a tree?', 'options' => ['A node with no children', 'A node with exactly one child', 'The root node', 'The deepest node'], 'correct' => 0],
            ['question' => 'What is a hash table?', 'options' => ['A table of sorted values', 'A data structure that maps keys to values using a hash function', 'A lookup table for sorting', 'A special type of binary tree'], 'correct' => 1],
            ['question' => 'What is a hash collision?', 'options' => ['When a hash function returns a negative value', 'When two different keys produce the same hash value', 'When the hash table is full', 'When a key has no hash value'], 'correct' => 1],
            ['question' => 'What is the average time complexity for lookup in a hash table?', 'options' => ['O(n)', 'O(log n)', 'O(n&sup2;)', 'O(1)'], 'correct' => 3],
            ['question' => 'What is chaining in hash tables?', 'options' => ['Linking hash tables together', 'Resolving collisions by storing multiple elements in the same bucket using a linked list', 'Sorting values before hashing', 'Double-hashing technique'], 'correct' => 1],
            ['question' => 'What is the height of a tree?', 'options' => ['The number of leaf nodes', 'The total number of nodes', 'The longest path from root to a leaf', 'The number of levels minus one'], 'correct' => 2],
            ['question' => 'What is the depth of a node in a tree?', 'options' => ['Its distance from the deepest leaf', 'The number of children it has', 'Its distance from the root', 'The height of its subtree'], 'correct' => 2],
            ['question' => 'What is a complete binary tree?', 'options' => ['A tree where all nodes have exactly two children', 'A tree where all levels are fully filled except possibly the last, which is filled left to right', 'A tree with no leaf nodes', 'A perfectly balanced binary tree'], 'correct' => 1],
            ['question' => 'What is the time complexity of bubble sort in the best case (already sorted array)?', 'options' => ['O(n&sup2;)', 'O(n log n)', 'O(n)', 'O(1)'], 'correct' => 2],
            ['question' => 'What is open addressing in hash tables?', 'options' => ['Leaving buckets open for any key', 'Resolving collisions by finding another open slot in the table', 'Opening a secondary hash table', 'Using open-source hash functions'], 'correct' => 1],
            ['question' => 'What does a balanced binary tree ensure?', 'options' => ['All nodes have two children', 'The height difference between left and right subtrees is bounded', 'All leaf nodes are at the same level', 'The tree is sorted'], 'correct' => 1],
            ['question' => 'Which sorting algorithm has O(n log n) average time complexity and uses a divide-and-conquer approach?', 'options' => ['Bubble Sort', 'Insertion Sort', 'Merge Sort', 'Selection Sort'], 'correct' => 2],
            ['question' => 'What is the space complexity of merge sort?', 'options' => ['O(1)', 'O(log n)', 'O(n)', 'O(n&sup2;)'], 'correct' => 2],
            ['question' => 'What is linear probing in hash tables?', 'options' => ['Hashing in a linear fashion', 'Resolving collisions by checking the next consecutive slot', 'Using a linear hash function', 'Probing elements in linear time'], 'correct' => 1],
            ['question' => 'What is a perfect binary tree?', 'options' => ['A tree with no duplicate keys', 'A binary tree where all internal nodes have exactly two children and all leaves are at the same level', 'A sorted binary tree', 'A binary tree with minimum height'], 'correct' => 1],
            ['question' => 'In binary search, when is the middle element selected?', 'options' => ['mid = low + high', 'mid = (low + high) / 2', 'mid = (low + high) * 2', 'mid = high - low'], 'correct' => 1],
            ['question' => 'What is the worst-case time complexity of binary search?', 'options' => ['O(1)', 'O(n)', 'O(log n)', 'O(n log n)'], 'correct' => 2],
            ['question' => 'What is a forest in tree terminology?', 'options' => ['A tree with many branches', 'A set of disjoint trees', 'A tree stored on disk', 'A tree with leaves at multiple levels'], 'correct' => 1],
            ['question' => 'What is the time complexity of selection sort?', 'options' => ['O(n log n)', 'O(n)', 'O(n&sup2;)', 'O(log n)'], 'correct' => 2],
        ],
    ],
    [
        'label' => 'Intermediate',
        'questions' => [
            ['question' => 'What is a Binary Search Tree (BST)?', 'options' => ['A binary tree with nodes stored alphabetically', 'A binary tree where left child &lt; parent &lt; right child', 'A tree with exactly two levels', 'A balanced binary tree'], 'correct' => 1],
            ['question' => 'What is the average time complexity of BST search?', 'options' => ['O(n)', 'O(n&sup2;)', 'O(log n)', 'O(1)'], 'correct' => 2],
            ['question' => 'What is the worst-case time complexity of BST search?', 'options' => ['O(log n)', 'O(n log n)', 'O(n)', 'O(1)'], 'correct' => 2],
            ['question' => 'What is BFS (Breadth-First Search)?', 'options' => ['Explores as deep as possible before backtracking', 'Explores all neighbors at current depth before moving deeper', 'Searches in sorted order', 'Uses recursion to explore paths'], 'correct' => 1],
            ['question' => 'What data structure is typically used for BFS?', 'options' => ['Stack', 'Queue', 'Heap', 'Array'], 'correct' => 1],
            ['question' => 'What data structure is typically used for DFS?', 'options' => ['Queue', 'Stack (or recursion)', 'Heap', 'Hash Table'], 'correct' => 1],
            ['question' => 'What is the time complexity of BFS and DFS on a graph with V vertices and E edges?', 'options' => ['O(V)', 'O(E)', 'O(V + E)', 'O(V * E)'], 'correct' => 2],
            ['question' => 'How does quicksort work?', 'options' => ['Divides array into halves and merges', 'Selects a pivot, partitions array, then recursively sorts each partition', 'Builds a sorted array one element at a time', 'Uses a heap to sort elements'], 'correct' => 1],
            ['question' => 'What is the average time complexity of quicksort?', 'options' => ['O(n&sup2;)', 'O(n)', 'O(n log n)', 'O(log n)'], 'correct' => 2],
            ['question' => 'What is the worst-case time complexity of quicksort?', 'options' => ['O(n log n)', 'O(n&sup2;)', 'O(n)', 'O(n log&sup2;n)'], 'correct' => 1],
            ['question' => 'What is the time complexity of mergesort in all cases?', 'options' => ['O(n&sup2;)', 'O(n log n)', 'O(n)', 'O(log n)'], 'correct' => 1],
            ['question' => 'What is a max-heap property?', 'options' => ['Parent node is always smaller than its children', 'Parent node is always greater than or equal to its children', 'Left child is always greater than right child', 'All nodes are equal'], 'correct' => 1],
            ['question' => 'What is the time complexity of inserting into a heap?', 'options' => ['O(1)', 'O(n)', 'O(log n)', 'O(n log n)'], 'correct' => 2],
            ['question' => 'What is the time complexity of extracting the max from a max-heap?', 'options' => ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], 'correct' => 1],
            ['question' => 'What is heap sort\'s time complexity?', 'options' => ['O(n&sup2;)', 'O(n)', 'O(n log n)', 'O(log n)'], 'correct' => 2],
            ['question' => 'What is an in-order traversal of a BST?', 'options' => ['Root, Left, Right', 'Left, Right, Root', 'Left, Root, Right', 'Right, Root, Left'], 'correct' => 2],
            ['question' => 'What is a pre-order traversal?', 'options' => ['Left, Root, Right', 'Root, Left, Right', 'Left, Right, Root', 'Right, Left, Root'], 'correct' => 1],
            ['question' => 'What is a post-order traversal?', 'options' => ['Root, Left, Right', 'Left, Root, Right', 'Left, Right, Root', 'Right, Root, Left'], 'correct' => 2],
            ['question' => 'What does in-order traversal of a BST produce?', 'options' => ['Random order', 'Reverse sorted order', 'Elements in sorted ascending order', 'Elements by level'], 'correct' => 2],
            ['question' => 'What is the time complexity of building a heap from n elements?', 'options' => ['O(n log n)', 'O(n)', 'O(n&sup2;)', 'O(log n)'], 'correct' => 1],
            ['question' => 'Which graph representation uses less memory for sparse graphs?', 'options' => ['Adjacency Matrix', 'Adjacency List', 'Incidence Matrix', 'Edge List'], 'correct' => 1],
            ['question' => 'What is a topological sort?', 'options' => ['Sorting graph nodes alphabetically', 'A linear ordering of vertices such that for every edge u&rarr;v, u comes before v', 'Sorting by edge weights', 'Sorting by vertex degree'], 'correct' => 1],
            ['question' => 'What is a connected graph?', 'options' => ['A graph with no cycles', 'A graph where there is a path between every pair of vertices', 'A graph where all vertices have the same degree', 'A graph with all vertices connected to the root'], 'correct' => 1],
            ['question' => 'What is the difference between a tree and a graph?', 'options' => ['Trees have cycles, graphs do not', 'A tree is a connected graph with no cycles (acyclic)', 'Graphs cannot have weighted edges', 'Trees must be binary'], 'correct' => 1],
            ['question' => 'What is the best case for quicksort (pivot always at median)?', 'options' => ['O(n&sup2;)', 'O(n)', 'O(n log n)', 'O(log n)'], 'correct' => 2],
            ['question' => 'What is a stable sorting algorithm?', 'options' => ['An algorithm that never crashes', 'An algorithm that preserves relative order of equal elements', 'An algorithm with consistent time complexity', 'An algorithm that sorts without extra memory'], 'correct' => 1],
            ['question' => 'Is quicksort a stable sorting algorithm?', 'options' => ['Yes, always', 'No, standard quicksort is not stable', 'It depends on the implementation only trivially', 'Yes, when using median-of-three pivot'], 'correct' => 1],
        ],
    ],
    [
        'label' => 'Advanced',
        'questions' => [
            ['question' => 'What is dynamic programming?', 'options' => ['A programming paradigm using dynamic typing', 'An optimization technique that solves complex problems by breaking them into overlapping subproblems and storing results', 'A method for dynamic memory allocation', 'A technique for real-time algorithm execution'], 'correct' => 1],
            ['question' => 'What are the two key properties required for dynamic programming?', 'options' => ['Greedy choice and optimal substructure', 'Optimal substructure and overlapping subproblems', 'Memoization and iteration', 'Divide and conquer and recursion'], 'correct' => 1],
            ['question' => 'What is memoization?', 'options' => ['Writing detailed comments in code', 'Caching the results of expensive function calls to avoid redundant computation', 'Memorizing algorithm steps', 'A type of dynamic programming only usable top-down'], 'correct' => 1],
            ['question' => 'What is the time complexity of the Fibonacci DP solution with memoization?', 'options' => ['O(2&sup2;)', 'O(n&sup2;)', 'O(n)', 'O(log n)'], 'correct' => 2],
            ['question' => 'What is an AVL tree?', 'options' => ['A type of binary tree sorted alphabetically', 'A self-balancing BST where the height difference between left and right subtrees is at most 1', 'A tree with AVL (Automatic Variable Length) nodes', 'A perfectly balanced tree always'], 'correct' => 1],
            ['question' => 'What is the time complexity of AVL tree insertion?', 'options' => ['O(n)', 'O(log n)', 'O(1)', 'O(n log n)'], 'correct' => 1],
            ['question' => 'What is Dijkstra\'s algorithm used for?', 'options' => ['Finding the minimum spanning tree', 'Finding shortest paths from a source vertex to all other vertices in a weighted graph', 'Detecting cycles in a graph', 'Topological sorting'], 'correct' => 1],
            ['question' => 'What is the time complexity of Dijkstra\'s algorithm with a binary heap?', 'options' => ['O(V&sup2;)', 'O(V + E)', 'O((V + E) log V)', 'O(E log V)'], 'correct' => 2],
            ['question' => 'What is the Bellman-Ford algorithm used for?', 'options' => ['Shortest paths in unweighted graphs', 'Shortest paths in graphs that may have negative edge weights', 'Finding minimum spanning trees', 'Maximum flow problems'], 'correct' => 1],
            ['question' => 'What is a greedy algorithm?', 'options' => ['An algorithm that tries all possibilities', 'An algorithm that makes the locally optimal choice at each step hoping for a global optimum', 'An algorithm based on dynamic programming', 'An algorithm that uses extra memory for speed'], 'correct' => 1],
            ['question' => 'What is Kruskal\'s algorithm used for?', 'options' => ['Shortest path finding', 'Finding the Minimum Spanning Tree by adding edges in increasing weight order', 'Graph coloring', 'Cycle detection'], 'correct' => 1],
            ['question' => 'What is the time complexity of Kruskal\'s algorithm?', 'options' => ['O(V&sup2;)', 'O(E log V)', 'O(E log E)', 'O(V + E)'], 'correct' => 2],
            ['question' => 'What is Prim\'s algorithm used for?', 'options' => ['Shortest path', 'Minimum Spanning Tree starting from a vertex and greedily adding minimum weight edges', 'Maximum flow', 'Topological sort'], 'correct' => 1],
            ['question' => 'What is a rotation in an AVL tree?', 'options' => ['Moving the root to a leaf', 'A structural rearrangement to restore balance after insertion or deletion', 'Reversing the tree order', 'A traversal method'], 'correct' => 1],
            ['question' => 'What are the four rotation types in AVL trees?', 'options' => ['Up, Down, Left, Right', 'LL, RR, LR, RL', 'Single, Double, Triple, Quadruple', 'Clockwise, Counter-clockwise, Double-clockwise, Double-counter-clockwise'], 'correct' => 1],
            ['question' => 'What is the 0/1 Knapsack problem?', 'options' => ['A shortest path problem', 'A problem of selecting items with given weights and values to maximize value within a weight limit, each item used at most once', 'A graph coloring problem', 'A sorting optimization problem'], 'correct' => 1],
            ['question' => 'What is the Longest Common Subsequence (LCS) problem?', 'options' => ['Finding the longest string in an array', 'Finding the longest subsequence present in both given sequences', 'Finding the longest sorted subsequence', 'Finding common elements in two arrays'], 'correct' => 1],
            ['question' => 'What is the time complexity of the LCS DP solution?', 'options' => ['O(m + n)', 'O(m * n)', 'O(m&sup2; + n&sup2;)', 'O(2^(m+n))'], 'correct' => 1],
            ['question' => 'What is Floyd-Warshall algorithm used for?', 'options' => ['Single-source shortest paths', 'All-pairs shortest paths', 'Minimum spanning tree', 'Maximum flow'], 'correct' => 1],
            ['question' => 'What is the time complexity of Floyd-Warshall?', 'options' => ['O(V&sup2;)', 'O(V&sup3;)', 'O(V&sup2; log V)', 'O(V + E)'], 'correct' => 1],
            ['question' => 'What is a Red-Black tree?', 'options' => ['A tree with colored edges for visualization', 'A self-balancing BST with color properties that ensure O(log n) operations', 'A binary tree with red and black nodes for aesthetics', 'An AVL tree variant'], 'correct' => 1],
            ['question' => 'What is the activity selection problem an example of?', 'options' => ['Dynamic programming', 'Greedy algorithm', 'Backtracking', 'Divide and conquer'], 'correct' => 1],
            ['question' => 'What is the Huffman coding algorithm?', 'options' => ['A sorting algorithm', 'A greedy algorithm for lossless data compression', 'A dynamic programming algorithm', 'A graph traversal algorithm'], 'correct' => 1],
            ['question' => 'What does a Union-Find (Disjoint Set Union) data structure support efficiently?', 'options' => ['Sorting sets', 'Finding if two elements are in the same set and merging sets', 'Searching sorted sets', 'Iterating through sets'], 'correct' => 1],
            ['question' => 'What is path compression in Union-Find?', 'options' => ['Compressing path names', 'Flattening the tree by making nodes point directly to root during find operations', 'Reducing path lengths in graphs', 'Compressing edge data'], 'correct' => 1],
            ['question' => 'What is the amortized time complexity per operation in Union-Find with path compression and union by rank?', 'options' => ['O(log n)', 'O(n)', 'O(&alpha;(n)) &ndash; inverse Ackermann, practically constant', 'O(1) always'], 'correct' => 2],
            ['question' => 'What is the coin change problem in DP?', 'options' => ['A graph problem about coin networks', 'Finding the minimum number of coins to make a given amount', 'Counting coins in a tree', 'A greedy problem always solvable optimally'], 'correct' => 1],
        ],
    ],
    [
        'label' => 'Expert',
        'questions' => [
            ['question' => 'What is a segment tree?', 'options' => ['A tree for segments of code', 'A tree data structure for storing intervals/segments, supporting range queries and updates in O(log n)', 'A balanced BST variant', 'A tree used in network routing'], 'correct' => 1],
            ['question' => 'What is the time complexity of a range query on a segment tree?', 'options' => ['O(n)', 'O(log n)', 'O(1)', 'O(n log n)'], 'correct' => 1],
            ['question' => 'What is a Fenwick tree (Binary Indexed Tree)?', 'options' => ['A binary tree with Fenwick nodes', 'A data structure supporting prefix sum queries and point updates in O(log n)', 'A segment tree variant', 'A tree for range maximum queries'], 'correct' => 1],
            ['question' => 'What is the space complexity of a Fenwick tree for n elements?', 'options' => ['O(n log n)', 'O(n)', 'O(log n)', 'O(n&sup2;)'], 'correct' => 1],
            ['question' => 'What is network flow?', 'options' => ['Data flow in computer networks', 'The maximum amount of flow that can be sent from source to sink in a flow network', 'Flow control algorithms', 'Routing table optimization'], 'correct' => 1],
            ['question' => 'What does the Ford-Fulkerson algorithm compute?', 'options' => ['Minimum spanning tree', 'Maximum flow in a flow network', 'Shortest path', 'All-pairs shortest paths'], 'correct' => 1],
            ['question' => 'What is the max-flow min-cut theorem?', 'options' => ['Maximum flow equals the sum of all edge capacities', 'The maximum flow equals the minimum cut capacity in a flow network', 'Minimum cut equals the shortest path', 'Maximum flow equals the number of paths'], 'correct' => 1],
            ['question' => 'What is the time complexity of the Edmonds-Karp algorithm (BFS-based Ford-Fulkerson)?', 'options' => ['O(VE&sup2;)', 'O(V&sup2;E)', 'O(VE log V)', 'O(V&sup3;)'], 'correct' => 0],
            ['question' => 'What is NP-completeness?', 'options' => ['Problems solvable in non-polynomial time', 'Problems in NP that are at least as hard as every problem in NP', 'Problems with no known solution', 'Problems requiring polynomial space'], 'correct' => 1],
            ['question' => 'Which of the following is an NP-complete problem?', 'options' => ['Binary search', 'Sorting', 'Traveling Salesman Problem (decision version)', 'Finding shortest path in unweighted graph'], 'correct' => 2],
            ['question' => 'What is the difference between P and NP?', 'options' => ['P is problems solvable in polynomial time; NP is problems verifiable in polynomial time', 'P is polynomial space; NP is non-polynomial time', 'P uses parallel computation; NP does not', 'P and NP are the same class'], 'correct' => 0],
            ['question' => 'What is a sparse table data structure used for?', 'options' => ['Storing sparse matrices', 'O(1) range minimum/maximum queries after O(n log n) preprocessing', 'Compressed data storage', 'Efficient graph traversal'], 'correct' => 1],
            ['question' => 'What is the Z-algorithm used for?', 'options' => ['Numerical computation', 'Linear-time string pattern matching by computing a Z-array', 'Zero-cost abstractions in algorithms', 'Zipping data structures'], 'correct' => 1],
            ['question' => 'What is the KMP (Knuth-Morris-Pratt) algorithm?', 'options' => ['A sorting algorithm', 'A string matching algorithm running in O(n + m) using a failure function', 'A key-matching protocol', 'A dynamic programming approach to string alignment'], 'correct' => 1],
            ['question' => 'What is a suffix array?', 'options' => ['An array of suffixes sorted in order', 'A sorted array of all suffixes of a string', 'A tree of suffixes', 'A suffix-indexed hash table'], 'correct' => 1],
            ['question' => 'What is matrix chain multiplication in DP?', 'options' => ['Multiplying matrices using chains', 'Finding the optimal parenthesization to minimize scalar multiplications', 'Chain multiplication of integers', 'A graph optimization problem'], 'correct' => 1],
            ['question' => 'What is the time complexity of matrix chain multiplication DP?', 'options' => ['O(n&sup2;)', 'O(n&sup3;)', 'O(n&sup2; log n)', 'O(2&sup2;)'], 'correct' => 1],
            ['question' => 'What is a lazy propagation segment tree?', 'options' => ['A segment tree that delays computation', 'A segment tree that delays range updates, applying them only when necessary to improve performance', 'A segment tree for lazy evaluation languages', 'A segment tree that builds lazily on first query'], 'correct' => 1],
            ['question' => 'What is the Longest Increasing Subsequence (LIS) problem?', 'options' => ['Finding the longest sorted substring', 'Finding the longest subsequence where each element is strictly greater than the previous', 'Finding the maximum sum subsequence', 'Finding the longest repeated subsequence'], 'correct' => 1],
            ['question' => 'What is the time complexity of the optimal LIS solution using patience sorting + binary search?', 'options' => ['O(n&sup2;)', 'O(n log n)', 'O(n)', 'O(n log&sup2;n)'], 'correct' => 1],
            ['question' => 'What is a trie (prefix tree)?', 'options' => ['A tree for numerical tries', 'A tree where each node represents a character, used for efficient string prefix operations', 'A type of hash table', 'A compressed segment tree'], 'correct' => 1],
            ['question' => 'What is the time complexity of trie insertion and search for a string of length m?', 'options' => ['O(m log n)', 'O(m)', 'O(n)', 'O(n + m)'], 'correct' => 1],
            ['question' => 'What is a persistent data structure?', 'options' => ['A data structure stored on disk', 'A data structure that preserves previous versions after updates', 'A data structure with persistent memory', 'A thread-safe data structure'], 'correct' => 1],
            ['question' => 'What is the Aho-Corasick algorithm?', 'options' => ['A single pattern matching algorithm', 'A multi-pattern string matching algorithm built on trie with failure links', 'A graph algorithm for matching', 'A dynamic programming string algorithm'], 'correct' => 1],
            ['question' => 'What is a convex hull?', 'options' => ['The minimum bounding rectangle of a set of points', 'The smallest convex polygon that contains all given points', 'A hull of convex shapes', 'The convex combination of all points'], 'correct' => 1],
            ['question' => 'What is the time complexity of Graham scan for convex hull?', 'options' => ['O(n&sup2;)', 'O(n log n)', 'O(n)', 'O(n log&sup2;n)'], 'correct' => 1],
            ['question' => 'What is an approximation algorithm?', 'options' => ['An algorithm that gives approximate but not exact results randomly', 'An algorithm that finds a solution within a provable factor of the optimal for NP-hard problems', 'A heuristic without guarantees', 'An algorithm using approximate arithmetic'], 'correct' => 1],
        ],
    ],
];
require_once __DIR__ . '/quiz-engine.php';
