<?php
$page_title = 'Git Quiz – 100 Levels – CodeFoundry';
$active_page = 'training';
$quiz_title  = 'Git';
$quiz_slug   = 'git';
$quiz_tiers  = [
    [
        'label' => 'Introduction',
        'questions' => [
            ['question' => 'What is Git?', 'options' => ['A text editor', 'A distributed version control system', 'A programming language', 'A build tool'], 'correct' => 1],
            ['question' => 'What command initializes a new Git repository?', 'options' => ['git start', 'git create', 'git init', 'git new'], 'correct' => 2],
            ['question' => 'What command copies a remote repository to your local machine?', 'options' => ['git pull', 'git download', 'git clone', 'git fetch'], 'correct' => 2],
            ['question' => 'What does git add do?', 'options' => ['Creates a new branch', 'Commits changes', 'Stages changes for the next commit', 'Pushes changes to remote'], 'correct' => 2],
            ['question' => 'What command records staged changes to the repository?', 'options' => ['git save', 'git stage', 'git commit', 'git push'], 'correct' => 2],
            ['question' => 'What does git status show?', 'options' => ['The commit history', 'The current branch and state of working directory and staging area', 'Remote server status', 'Merge conflicts only'], 'correct' => 1],
            ['question' => 'What does git log display?', 'options' => ['File differences', 'The commit history', 'Branch list', 'Staged changes'], 'correct' => 1],
            ['question' => 'What is the working directory in Git?', 'options' => ['The .git folder', 'The local copy of files you are actively editing', 'The staging area', 'The remote repository'], 'correct' => 1],
            ['question' => 'What is the staging area (index) in Git?', 'options' => ['A remote backup', 'A temporary area where changes are prepared before committing', 'The working directory', 'The commit history'], 'correct' => 1],
            ['question' => 'What is the Git repository?', 'options' => ['A file editor', 'The .git directory containing all project history and metadata', 'A remote server', 'A staging area'], 'correct' => 1],
            ['question' => 'What does git add . do?', 'options' => ['Stages a specific file', 'Stages all changes in the current directory and subdirectories', 'Commits all changes', 'Adds a remote'], 'correct' => 1],
            ['question' => 'How do you stage a specific file named app.js?', 'options' => ['git commit app.js', 'git stage app.js', 'git add app.js', 'git include app.js'], 'correct' => 2],
            ['question' => 'What flag adds a message to a commit?', 'options' => ['-msg', '-message', '-m', '-comment'], 'correct' => 2],
            ['question' => 'What does HEAD refer to in Git?', 'options' => ['The first commit', 'A pointer to the current branch\'s latest commit', 'The main branch', 'The remote HEAD'], 'correct' => 1],
            ['question' => 'What file format does Git use to ignore files?', 'options' => ['.gitconfig', '.gitignore', '.gitexclude', '.ignore'], 'correct' => 1],
            ['question' => 'What does git clone create?', 'options' => ['A fork of the repository', 'A local copy of a remote repository with its full history', 'Only the latest commit', 'A mirror repository'], 'correct' => 1],
            ['question' => 'Who created Git?', 'options' => ['James Gosling', 'Guido van Rossum', 'Linus Torvalds', 'Bjarne Stroustrup'], 'correct' => 2],
            ['question' => 'What is a commit in Git?', 'options' => ['A saved snapshot of staged changes with a unique SHA hash', 'A branch name', 'A file upload', 'A remote sync'], 'correct' => 0],
            ['question' => 'What does git log --oneline show?', 'options' => ['Full commit details', 'A condensed view with one line per commit', 'Only the last commit', 'Online commits only'], 'correct' => 1],
            ['question' => 'What does the -u flag in git push -u origin main do?', 'options' => ['Uploads unchanged files', 'Sets the upstream tracking branch', 'Forces the push', 'Updates local references'], 'correct' => 1],
            ['question' => 'What command shows what changes have been made but not yet staged?', 'options' => ['git status', 'git log', 'git diff', 'git show'], 'correct' => 2],
            ['question' => 'What does git init create inside the project folder?', 'options' => ['A README.md file', 'A .git directory', 'A .gitignore file', 'A main branch file'], 'correct' => 1],
            ['question' => 'What is the default name of the main branch in modern Git?', 'options' => ['master', 'main', 'primary', 'trunk'], 'correct' => 1],
            ['question' => 'What does git show do?', 'options' => ['Lists branches', 'Displays details of a specific commit', 'Shows remote URLs', 'Displays staged files'], 'correct' => 1],
            ['question' => 'How do you amend the most recent commit message?', 'options' => ['git commit -edit', 'git commit --amend', 'git amend -m', 'git modify commit'], 'correct' => 1],
        ],
    ],
    [
        'label' => 'Beginner',
        'questions' => [
            ['question' => 'What does git push do?', 'options' => ['Downloads remote changes', 'Uploads local commits to a remote repository', 'Merges branches', 'Stages files'], 'correct' => 1],
            ['question' => 'What does git pull do?', 'options' => ['Uploads local commits', 'Fetches and merges remote changes into the current branch', 'Lists remote branches', 'Pulls a specific file'], 'correct' => 1],
            ['question' => 'What is the difference between git fetch and git pull?', 'options' => ['No difference', 'git fetch downloads changes without merging; git pull fetches and merges', 'git fetch is faster', 'git pull only works with origin'], 'correct' => 1],
            ['question' => 'What command lists all local branches?', 'options' => ['git branches', 'git branch', 'git list branches', 'git show branches'], 'correct' => 1],
            ['question' => 'What command creates a new branch called "feature"?', 'options' => ['git new feature', 'git create feature', 'git branch feature', 'git make feature'], 'correct' => 2],
            ['question' => 'What command switches to an existing branch called "feature"?', 'options' => ['git switch feature', 'git goto feature', 'git checkout feature', 'git move feature'], 'correct' => 2],
            ['question' => 'What does git checkout -b feature do?', 'options' => ['Deletes the feature branch', 'Creates and switches to a new branch named feature', 'Checks out a file', 'Builds the feature'], 'correct' => 1],
            ['question' => 'What is a fast-forward merge?', 'options' => ['A merge that creates a merge commit', 'A merge where the base branch pointer is moved forward to the tip of the feature branch', 'A merge with conflicts', 'An automatic rebase'], 'correct' => 1],
            ['question' => 'What does git merge feature do when on main?', 'options' => ['Deletes the feature branch', 'Integrates commits from feature into main', 'Rebases main onto feature', 'Pushes feature to remote'], 'correct' => 1],
            ['question' => 'What does git diff show when comparing staged changes?', 'options' => ['git diff only shows unstaged changes', 'Differences between staged changes and the last commit', 'Only binary diffs', 'Remote vs local differences'], 'correct' => 1],
            ['question' => 'What is a .gitignore file used for?', 'options' => ['Listing collaborators', 'Specifying files and directories Git should not track', 'Storing Git credentials', 'Configuring Git aliases'], 'correct' => 1],
            ['question' => 'What is "origin" in Git?', 'options' => ['The first commit', 'The default alias for the remote repository URL', 'The main branch', 'The root directory'], 'correct' => 1],
            ['question' => 'What command shows the configured remote repositories?', 'options' => ['git origin', 'git list remotes', 'git remote -v', 'git show remotes'], 'correct' => 2],
            ['question' => 'How do you delete a local branch named "old-feature"?', 'options' => ['git branch --remove old-feature', 'git delete old-feature', 'git branch -d old-feature', 'git remove branch old-feature'], 'correct' => 2],
            ['question' => 'What does git diff HEAD show?', 'options' => ['Changes between HEAD and remote', 'All changes in the working directory since the last commit', 'Differences between two branches', 'Staged changes only'], 'correct' => 1],
            ['question' => 'What does git pull --rebase do?', 'options' => ['Pulls and creates a merge commit', 'Pulls remote changes and rebases local commits on top', 'Pulls without fetching', 'Rebases remote onto local'], 'correct' => 1],
            ['question' => 'What command renames the current branch to "main"?', 'options' => ['git branch -rename main', 'git branch -M main', 'git rename main', 'git checkout -name main'], 'correct' => 1],
            ['question' => 'What does git stash save do?', 'options' => ['Saves all commits', 'Temporarily shelves uncommitted changes', 'Saves to remote stash', 'Saves the branch state'], 'correct' => 1],
            ['question' => 'What does git stash pop do?', 'options' => ['Deletes the stash', 'Applies the most recent stash and removes it from the stash list', 'Pops the last commit', 'Applies stash without removing it'], 'correct' => 1],
            ['question' => 'What does git remote add origin <url> do?', 'options' => ['Creates a new repository at the URL', 'Adds a remote named origin pointing to the URL', 'Clones from the URL', 'Pushes to the URL'], 'correct' => 1],
            ['question' => 'What does the --staged flag do with git diff?', 'options' => ['Shows unstaged differences', 'Shows differences between the staging area and the last commit', 'Shows all differences', 'Compares staged branches'], 'correct' => 1],
            ['question' => 'What does git log --graph show?', 'options' => ['A pie chart of commits', 'An ASCII graph of the branch and merge history', 'A graph of file changes', 'A performance graph'], 'correct' => 1],
            ['question' => 'How do you push a new local branch "feature" to origin?', 'options' => ['git push feature', 'git push origin feature', 'git upload feature', 'git send origin feature'], 'correct' => 1],
            ['question' => 'What is a tracking branch?', 'options' => ['A branch that tracks file changes', 'A local branch linked to a remote branch', 'A monitoring branch', 'An audit branch'], 'correct' => 1],
            ['question' => 'What does git fetch origin do?', 'options' => ['Merges remote changes', 'Downloads all new data from the origin remote without merging', 'Fetches a specific file', 'Fetches the main branch only'], 'correct' => 1],
        ],
    ],
    [
        'label' => 'Intermediate',
        'questions' => [
            ['question' => 'What does git rebase do?', 'options' => ['Creates a merge commit', 'Moves or replays commits on top of another base commit', 'Deletes old commits', 'Renames a branch'], 'correct' => 1],
            ['question' => 'What is the key advantage of rebasing over merging?', 'options' => ['It is faster', 'It produces a linear commit history', 'It preserves merge commits', 'It is safer'], 'correct' => 1],
            ['question' => 'What does interactive rebase (git rebase -i) allow you to do?', 'options' => ['Rebase interactively with a server', 'Reorder, edit, squash, or drop commits', 'Interactively merge branches', 'Interactive conflict resolution only'], 'correct' => 1],
            ['question' => 'What does "squash" do in interactive rebase?', 'options' => ['Compresses binary files', 'Combines a commit with the previous one', 'Deletes empty commits', 'Reduces commit message length'], 'correct' => 1],
            ['question' => 'What does git cherry-pick do?', 'options' => ['Selects the best commit', 'Applies a specific commit from another branch to the current branch', 'Merges selected files', 'Picks a branch to delete'], 'correct' => 1],
            ['question' => 'What is a merge conflict?', 'options' => ['A failed push', 'When the same lines in a file are changed differently in two branches being merged', 'A corrupt repository', 'A denied merge request'], 'correct' => 1],
            ['question' => 'What does git reset --soft HEAD~1 do?', 'options' => ['Deletes the last commit and its changes', 'Undoes the last commit but keeps changes staged', 'Moves HEAD back one and unstages changes', 'Resets remote HEAD'], 'correct' => 1],
            ['question' => 'What does git reset --hard HEAD~1 do?', 'options' => ['Keeps changes staged', 'Moves HEAD back and discards all changes from the last commit', 'Only resets the index', 'Resets to remote HEAD'], 'correct' => 1],
            ['question' => 'What does git reset --mixed HEAD~1 do?', 'options' => ['Discards all changes', 'Undoes the last commit and unstages changes, but keeps them in the working directory', 'Keeps changes staged', 'Resets only tracked files'], 'correct' => 1],
            ['question' => 'What does git revert do?', 'options' => ['Removes a commit from history', 'Creates a new commit that undoes the changes of a specified commit', 'Reverts a file to the original', 'Resets HEAD to a previous state'], 'correct' => 1],
            ['question' => 'What is the difference between git reset and git revert?', 'options' => ['No difference', 'reset rewrites history; revert creates a new undo commit without altering history', 'revert is destructive; reset is safe', 'reset only works locally'], 'correct' => 1],
            ['question' => 'What is git stash list used for?', 'options' => ['Lists stash configuration', 'Displays all stashed changes', 'Lists the stash commands', 'Lists stashed branches'], 'correct' => 1],
            ['question' => 'How do you apply a stash without removing it from the stash list?', 'options' => ['git stash pop', 'git stash apply', 'git stash restore', 'git stash use'], 'correct' => 1],
            ['question' => 'What is a lightweight Git tag?', 'options' => ['A tag with a message', 'A simple pointer to a specific commit without extra metadata', 'A tag on a lightweight branch', 'A tag used in CI/CD only'], 'correct' => 1],
            ['question' => 'What is an annotated Git tag?', 'options' => ['A tag with only a name', 'A tag stored as a full Git object with a message, date, and tagger', 'An annotated branch', 'A tag with a release note'], 'correct' => 1],
            ['question' => 'What branching strategy involves short-lived feature branches merged into main regularly?', 'options' => ['GitFlow', 'Trunk-based development', 'Release branching', 'Environment branching'], 'correct' => 1],
            ['question' => 'In GitFlow, what is the purpose of the "develop" branch?', 'options' => ['It is used for hotfixes', 'It integrates feature branches and serves as a base for releases', 'It is the production branch', 'It tracks remote changes'], 'correct' => 1],
            ['question' => 'What does git diff branch1..branch2 show?', 'options' => ['Commits in both branches', 'Differences between the tips of branch1 and branch2', 'Common ancestors', 'Diverged commits'], 'correct' => 1],
            ['question' => 'What does git merge --no-ff do?', 'options' => ['Prevents fast-forward, always creating a merge commit', 'Disables all merge conflicts', 'Forces a fast-forward merge', 'Merges without fetching'], 'correct' => 0],
            ['question' => 'What is a detached HEAD state?', 'options' => ['A missing HEAD file', 'When HEAD points directly to a commit instead of a branch', 'A corrupted repository', 'When HEAD is at the first commit'], 'correct' => 1],
            ['question' => 'How do you push a tag named "v1.0" to origin?', 'options' => ['git push tag v1.0', 'git push origin v1.0', 'git push --tags v1.0', 'git tag push v1.0'], 'correct' => 1],
            ['question' => 'What does git log --author="Alice" do?', 'options' => ['Shows Alice\'s profile', 'Filters commit log to show only commits by Alice', 'Shows commits reviewed by Alice', 'Lists Alice\'s branches'], 'correct' => 1],
            ['question' => 'What does git clean -fd do?', 'options' => ['Fixes a detached HEAD', 'Removes untracked files and directories from the working directory', 'Cleans the commit history', 'Cleans merge conflicts'], 'correct' => 1],
            ['question' => 'What does git shortlog -s -n show?', 'options' => ['Short commit messages sorted by name', 'Commit counts per author sorted numerically', 'A short branch log', 'A numbered shortlog'], 'correct' => 1],
            ['question' => 'What does the ORIG_HEAD ref point to after a merge or rebase?', 'options' => ['The original branch', 'The previous state of HEAD before the operation', 'The origin\'s HEAD', 'The original remote commit'], 'correct' => 1],
        ],
    ],
    [
        'label' => 'Advanced',
        'questions' => [
            ['question' => 'What does git reflog show?', 'options' => ['Remote log', 'A log of all reference updates, useful for recovering lost commits', 'Refined commit log', 'A log of rebases only'], 'correct' => 1],
            ['question' => 'What is git bisect used for?', 'options' => ['Splitting a branch', 'Binary search through commit history to find the commit that introduced a bug', 'Bisecting merge conflicts', 'Dividing a repository'], 'correct' => 1],
            ['question' => 'What does git blame show?', 'options' => ['Commit errors', 'The author, timestamp, and commit for each line in a file', 'Blame labels for branches', 'Conflicting commits'], 'correct' => 1],
            ['question' => 'What is a Git submodule?', 'options' => ['A module in the .git folder', 'A pointer to a specific commit in another Git repository embedded in the parent repo', 'A sub-branch', 'A partial clone'], 'correct' => 1],
            ['question' => 'What command adds a submodule to a repository?', 'options' => ['git add submodule <url>', 'git submodule add <url>', 'git include <url>', 'git module add <url>'], 'correct' => 1],
            ['question' => 'What are Git hooks?', 'options' => ['GitHub webhooks', 'Scripts that run automatically at specific Git events (e.g., pre-commit, post-merge)', 'Hook references in commits', 'Hooks for CI/CD integrations'], 'correct' => 1],
            ['question' => 'Where are Git hooks stored?', 'options' => ['In the root directory', 'In .git/hooks/', 'In .githooks/', 'In config/hooks/'], 'correct' => 1],
            ['question' => 'What is git worktree used for?', 'options' => ['Managing the work tree permissions', 'Checking out multiple branches simultaneously in separate directories', 'Working with tree data structures', 'Creating a new repository'], 'correct' => 1],
            ['question' => 'What are signed commits in Git?', 'options' => ['Commits with a sign-off message', 'Commits cryptographically signed with a GPG key to verify authorship', 'Commits approved by a reviewer', 'Commits with a digital signature in the message'], 'correct' => 1],
            ['question' => 'Why is git push --force dangerous?', 'options' => ['It pushes too many files', 'It overwrites the remote history, potentially losing commits others have pulled', 'It forces a merge', 'It bypasses authentication'], 'correct' => 1],
            ['question' => 'What does git push --force-with-lease do?', 'options' => ['Forces a push with a timeout', 'Safely force-pushes only if no one else has pushed since your last fetch', 'Leases the push lock', 'Forces push with lease branching'], 'correct' => 1],
            ['question' => 'What is trunk-based development?', 'options' => ['Developing on the trunk operating system', 'A strategy where all developers commit frequently to a single main (trunk) branch', 'A branching model with trunk branches', 'A strategy using long-lived feature branches'], 'correct' => 1],
            ['question' => 'What does git log --follow do?', 'options' => ['Follows a specific author', 'Tracks a file\'s history across renames', 'Follows the main branch', 'Follows remote commits'], 'correct' => 1],
            ['question' => 'What does git archive do?', 'options' => ['Archives old commits', 'Creates a compressed archive of a tree from a commit or branch', 'Moves a repo to archive', 'Archives branches'], 'correct' => 1],
            ['question' => 'What does the --depth flag do in git clone?', 'options' => ['Sets clone directory depth', 'Creates a shallow clone with limited commit history', 'Clones only specific depth branches', 'Limits file system depth'], 'correct' => 1],
            ['question' => 'What is a shallow clone in Git?', 'options' => ['A clone without tags', 'A clone with a truncated commit history for faster cloning', 'A read-only clone', 'A partial file clone'], 'correct' => 1],
            ['question' => 'What does git notes allow you to do?', 'options' => ['Add notes to Git configuration', 'Attach additional metadata to commits without changing the commit hash', 'Create note files in the repository', 'Add reviewer notes to PRs'], 'correct' => 1],
            ['question' => 'What is a pre-commit hook typically used for?', 'options' => ['Sending commit notifications', 'Running linters or tests before a commit is finalized', 'Pre-staging files', 'Preventing pushes'], 'correct' => 1],
            ['question' => 'What does git bisect good and git bisect bad tell Git?', 'options' => ['Marks commits as approved or rejected', 'Tells Git which commits are bug-free and which have the bug during a bisect session', 'Rates commit quality', 'Labels commits for GitFlow'], 'correct' => 1],
            ['question' => 'What is GitFlow?', 'options' => ['A Git GUI tool', 'A branching model using main, develop, feature, release, and hotfix branches', 'A Git data flow diagram', 'A GitHub automation flow'], 'correct' => 1],
            ['question' => 'What does git submodule update --init --recursive do?', 'options' => ['Updates and deletes submodules', 'Initializes and updates all submodules including nested ones', 'Recursively clones submodules', 'Updates submodule configuration'], 'correct' => 1],
            ['question' => 'What is the purpose of a post-receive hook on a server?', 'options' => ['Receives push notifications', 'Runs server-side scripts after a push is received (e.g., deploy)', 'Posts commit messages', 'Triggers pull request reviews'], 'correct' => 1],
            ['question' => 'What does git diff --stat show?', 'options' => ['Full line-by-line diff', 'A summary of changed files with insertion and deletion counts', 'Statistics about commit history', 'Index statistics'], 'correct' => 1],
            ['question' => 'How do you list all tags?', 'options' => ['git list tags', 'git tag --list', 'git show tags', 'git tags --all'], 'correct' => 1],
            ['question' => 'What does git format-patch do?', 'options' => ['Formats a commit message', 'Creates patch files from commits suitable for emailing or applying elsewhere', 'Patches a merge conflict', 'Formats the diff output'], 'correct' => 1],
        ],
    ],
    [
        'label' => 'Expert',
        'questions' => [
            ['question' => 'What are the four core Git object types?', 'options' => ['File, folder, commit, branch', 'Blob, tree, commit, tag', 'Index, commit, ref, pack', 'Object, hash, ref, remote'], 'correct' => 1],
            ['question' => 'What is a blob object in Git?', 'options' => ['A binary large object stored in a database', 'The Git object that stores file content', 'A compressed pack file', 'A binary commit'], 'correct' => 1],
            ['question' => 'What is a tree object in Git?', 'options' => ['A data structure in Git config', 'The Git object that represents a directory listing of blobs and other trees', 'A branch hierarchy', 'A tag tree'], 'correct' => 1],
            ['question' => 'What algorithm does Git use to generate object hashes?', 'options' => ['MD5', 'SHA-256', 'SHA-1 (with SHA-256 support being added)', 'CRC32'], 'correct' => 2],
            ['question' => 'What is a plumbing command in Git?', 'options' => ['A low-level command used for scripting and building tools', 'A command for fixing broken repositories', 'A GUI command', 'A command for plumbing configuration'], 'correct' => 0],
            ['question' => 'What is the difference between plumbing and porcelain commands?', 'options' => ['Plumbing is faster', 'Porcelain commands are user-friendly; plumbing commands are low-level primitives', 'Plumbing commands are deprecated', 'No practical difference'], 'correct' => 1],
            ['question' => 'What is a Git pack file?', 'options' => ['A compressed repository archive', 'A file that stores multiple Git objects compressed together for efficiency', 'A packed branch list', 'A pack of patches'], 'correct' => 1],
            ['question' => 'What does git gc do?', 'options' => ['Garbage-collects invalid commits', 'Runs housekeeping tasks like packing loose objects and pruning unreachable objects', 'Cleans the .git config', 'Resets Git counters'], 'correct' => 1],
            ['question' => 'What does git cat-file -p <hash> do?', 'options' => ['Prints a file\'s content from the working directory', 'Pretty-prints the content of a Git object by its hash', 'Catalogs files by hash', 'Checks file integrity'], 'correct' => 1],
            ['question' => 'What does git hash-object do?', 'options' => ['Hashes the entire repository', 'Computes the Git object hash of a file and optionally writes it to the object store', 'Hashes branch names', 'Creates a hash index'], 'correct' => 1],
            ['question' => 'What is git filter-repo used for?', 'options' => ['Filtering log output', 'Rewriting Git history to remove files, rename paths, or restructure repositories', 'Filtering branches', 'Filtering remotes'], 'correct' => 1],
            ['question' => 'Why is git filter-branch considered deprecated?', 'options' => ['It has been removed from Git', 'It is slow, error-prone, and has been superseded by git filter-repo', 'It only works on Linux', 'It requires root access'], 'correct' => 1],
            ['question' => 'What is Git LFS (Large File Storage)?', 'options' => ['A large file system plugin', 'An extension that replaces large files in the repo with pointers and stores them separately', 'A low-frequency storage system', 'A Git-native file compressor'], 'correct' => 1],
            ['question' => 'What does git ls-tree show?', 'options' => ['Lists the working tree', 'Lists the contents of a tree object (directory) at a given commit', 'Lists all tracked files', 'Shows a tree of commits'], 'correct' => 1],
            ['question' => 'What is the refs/heads/ namespace?', 'options' => ['References to remote heads', 'Where local branch references are stored', 'Where HEAD is stored', 'Where tag references are stored'], 'correct' => 1],
            ['question' => 'What is the refs/tags/ namespace?', 'options' => ['Where branch refs are stored', 'Where tag references are stored', 'Where remote tags are mirrored', 'Where lightweight tags only are stored'], 'correct' => 1],
            ['question' => 'What does the FETCH_HEAD file contain?', 'options' => ['The last fetched branch name', 'A record of what was fetched from a remote during the last git fetch', 'The remote HEAD reference', 'A list of fetched commits'], 'correct' => 1],
            ['question' => 'What does git verify-pack -v show?', 'options' => ['Verifies GPG signatures', 'Shows details of objects stored in a pack file', 'Verifies pack file integrity', 'Shows pack file version'], 'correct' => 1],
            ['question' => 'What is the purpose of the packed-refs file?', 'options' => ['Stores compressed commits', 'Stores references that have been packed for performance instead of individual files', 'Stores pack index data', 'Stores archived refs'], 'correct' => 1],
            ['question' => 'What does git prune do?', 'options' => ['Prunes unused branches', 'Removes Git objects that are no longer reachable from any reference', 'Prunes the pack files', 'Removes stale remote-tracking branches'], 'correct' => 1],
            ['question' => 'What is a partial clone in Git?', 'options' => ['Cloning only some branches', 'A clone that lazily fetches objects on demand, reducing initial clone size', 'Cloning without tags', 'A clone with a subset of commits'], 'correct' => 1],
            ['question' => 'What does git bundle create do?', 'options' => ['Creates a deployment bundle', 'Packs a Git repository or subset into a single file for transport without a network', 'Bundles commits for a PR', 'Creates a compressed backup'], 'correct' => 1],
            ['question' => 'What are Git alternates?', 'options' => ['Alternative remotes', 'A mechanism allowing one repository to borrow objects from another to save disk space', 'Alternate branch names', 'Alternate hash algorithms'], 'correct' => 1],
            ['question' => 'What does git replace allow you to do?', 'options' => ['Replace file content', 'Substitute one Git object for another transparently without changing references', 'Replace a branch name', 'Replace a remote URL'], 'correct' => 1],
            ['question' => 'What is the significance of commit 0000000000000000000000000000000000000000 in Git hooks?', 'options' => ['It represents an empty commit', 'It represents a null/nonexistent reference (e.g., when creating or deleting a branch)', 'It is the root commit hash', 'It marks a corrupted object'], 'correct' => 1],
        ],
    ],
];
require_once __DIR__ . '/quiz-engine.php';
