<?php
$page_title = 'Go Quiz – 100 Levels – CodeFoundry';
$active_page = 'training';
$quiz_title  = 'Go';
$quiz_slug   = 'golang';
$quiz_tiers  = [
    [
        'label' => 'Introduction',
        'questions' => [
            ['question' => 'What is Go (Golang)?', 'options' => ['A scripting language by Mozilla', 'A statically typed, compiled programming language designed at Google', 'A dynamically typed language', 'A Java framework'], 'correct' => 1],
            ['question' => 'Which command runs a Go source file directly?', 'options' => ['go start', 'go exec', 'go run', 'go execute'], 'correct' => 2],
            ['question' => 'Which command compiles a Go program into a binary?', 'options' => ['go compile', 'go build', 'go make', 'go create'], 'correct' => 1],
            ['question' => 'What must every Go executable program\'s package be named?', 'options' => ['program', 'init', 'main', 'start'], 'correct' => 2],
            ['question' => 'What is the entry point function of a Go executable?', 'options' => ['init()', 'start()', 'main()', 'run()'], 'correct' => 2],
            ['question' => 'Which package is used for formatted I/O like printing to the console?', 'options' => ['io', 'os', 'fmt', 'log'], 'correct' => 2],
            ['question' => 'What function prints a line to standard output?', 'options' => ['fmt.Print()', 'fmt.Printf()', 'fmt.Println()', 'fmt.Write()'], 'correct' => 2],
            ['question' => 'What keyword declares a variable in Go?', 'options' => ['let', 'dim', 'var', 'def'], 'correct' => 2],
            ['question' => 'What operator declares and initialises a variable with inferred type?', 'options' => [':=', '==', '=:', '::='], 'correct' => 0],
            ['question' => 'What is the zero value of an integer in Go?', 'options' => ['nil', 'null', '0', 'undefined'], 'correct' => 2],
            ['question' => 'What is the zero value of a string in Go?', 'options' => ['nil', 'null', '""', '" "'], 'correct' => 2],
            ['question' => 'What is the zero value of a bool in Go?', 'options' => ['nil', 'false', '0', 'undefined'], 'correct' => 1],
            ['question' => 'What keyword is used to import packages in Go?', 'options' => ['include', 'require', 'import', 'use'], 'correct' => 2],
            ['question' => 'Which type represents a 64-bit floating-point number in Go?', 'options' => ['float', 'double', 'float32', 'float64'], 'correct' => 3],
            ['question' => 'Which of the following is a valid Go basic type?', 'options' => ['char', 'byte (alias for uint8)', 'number', 'integer'], 'correct' => 1],
            ['question' => 'What is the string concatenation operator in Go?', 'options' => ['..', '&', '+', '~'], 'correct' => 2],
            ['question' => 'How do you declare a constant in Go?', 'options' => ['var x = 5', 'const x = 5', 'final x = 5', 'static x = 5'], 'correct' => 1],
            ['question' => 'What does the blank identifier "_" do in Go?', 'options' => ['Marks a private variable', 'Discards a value', 'Creates an anonymous function', 'Denotes a pointer'], 'correct' => 1],
            ['question' => 'What is the correct way to start a single-line comment in Go?', 'options' => ['#', '--', '//', '/*'], 'correct' => 2],
            ['question' => 'What does "go fmt" do?', 'options' => ['Formats a string', 'Automatically formats Go source code to the standard style', 'Compiles and formats output', 'Formats output to stdout'], 'correct' => 1],
            ['question' => 'Which command downloads dependencies listed in go.mod?', 'options' => ['go get --all', 'go install', 'go mod download', 'go fetch'], 'correct' => 2],
            ['question' => 'What file defines a Go module and its dependencies?', 'options' => ['package.json', 'go.sum', 'go.mod', 'Makefile'], 'correct' => 2],
            ['question' => 'What is the type of a whole number like 42 in Go without explicit typing?', 'options' => ['int32', 'int64', 'int (platform-dependent size)', 'uint'], 'correct' => 2],
            ['question' => 'What is a rune in Go?', 'options' => ['A byte array', 'An alias for int32 representing a Unicode code point', 'A string type', 'A character array'], 'correct' => 1],
            ['question' => 'How do you convert an int to a string in Go?', 'options' => ['string(42)', 'strconv.Itoa(42)', 'fmt.String(42)', 'Both string(42) and strconv.Itoa(42) but with different results'], 'correct' => 3],
        ],
    ],
    [
        'label' => 'Beginner',
        'questions' => [
            ['question' => 'How do you declare an array of 5 integers in Go?', 'options' => ['int[5] arr', 'arr := int[5]{}', 'var arr [5]int', 'arr = array(5, int)'], 'correct' => 2],
            ['question' => 'What is a slice in Go?', 'options' => ['A fixed-size array', 'A dynamically-sized, flexible view into the elements of an array', 'A linked list', 'A map type'], 'correct' => 1],
            ['question' => 'How do you create a slice with make?', 'options' => ['make([]int, 5)', 'slice(int, 5)', 'new([]int, 5)', 'create([]int, 5)'], 'correct' => 0],
            ['question' => 'How do you append an element to a slice s?', 'options' => ['s.append(1)', 's += 1', 's = append(s, 1)', 'append(s, 1)'], 'correct' => 2],
            ['question' => 'What is a map in Go?', 'options' => ['A slice of key-value pairs', 'A built-in hash table / dictionary type', 'A sorted tree structure', 'An array of structs'], 'correct' => 1],
            ['question' => 'How do you create a map with string keys and int values?', 'options' => ['map[string]int{}', 'new map(string, int)', 'make(map[string]int)', 'Both map[string]int{} and make(map[string]int) are valid'], 'correct' => 3],
            ['question' => 'How do you check if a key exists in a map?', 'options' => ['val, ok := m[key]', 'ok := m.has(key)', 'val := m[key]; if val != nil', 'm.exists(key)'], 'correct' => 0],
            ['question' => 'How is a struct defined in Go?', 'options' => ['class MyStruct {}', 'struct MyStruct {}', 'type MyStruct struct {}', 'define MyStruct struct {}'], 'correct' => 2],
            ['question' => 'What is the only looping construct in Go?', 'options' => ['while', 'for', 'loop', 'do-while'], 'correct' => 1],
            ['question' => 'How do you write a for loop equivalent to "while true"?', 'options' => ['while(true){}', 'for true {}', 'for {}', 'loop {}'], 'correct' => 2],
            ['question' => 'Which statement is used for multi-branch selection in Go?', 'options' => ['select', 'case', 'switch', 'match'], 'correct' => 2],
            ['question' => 'Can a Go function return multiple values?', 'options' => ['No', 'Yes, and it is a core language feature', 'Only with tuples', 'Only with structs'], 'correct' => 1],
            ['question' => 'How do you declare a function that returns two ints in Go?', 'options' => ['func f() int, int {}', 'func f() (int, int) {}', 'func f() [int, int] {}', 'func f() -> (int, int) {}'], 'correct' => 1],
            ['question' => 'What is a pointer in Go?', 'options' => ['A reference type', 'A variable that stores the memory address of another variable', 'A null value', 'A constant address'], 'correct' => 1],
            ['question' => 'What operator gets the address of a variable x?', 'options' => ['*x', '&x', '@x', '^x'], 'correct' => 1],
            ['question' => 'What operator dereferences a pointer p?', 'options' => ['&p', '@p', '*p', '^p'], 'correct' => 2],
            ['question' => 'What is the nil value in Go?', 'options' => ['Zero for integers', 'The zero value for pointers, interfaces, maps, slices, channels, and functions', 'An empty string', 'A false boolean'], 'correct' => 1],
            ['question' => 'What does the range keyword do in a for loop?', 'options' => ['Generates a number range', 'Iterates over a slice, array, map, string, or channel', 'Limits loop iterations', 'Calculates a range value'], 'correct' => 1],
            ['question' => 'What does "break" do inside a switch in Go?', 'options' => ['Nothing — switch cases don\'t fall through by default', 'Exits the switch immediately', 'Breaks only if condition is true', 'Falls through to next case'], 'correct' => 0],
            ['question' => 'What keyword causes a switch case to fall through to the next case?', 'options' => ['continue', 'next', 'fallthrough', 'pass'], 'correct' => 2],
            ['question' => 'What does the len() function return for a slice?', 'options' => ['Its capacity', 'The number of elements it contains', 'Its memory size', 'The maximum possible size'], 'correct' => 1],
            ['question' => 'What does the cap() function return for a slice?', 'options' => ['Number of elements', 'The capacity (total allocated space) of the slice', 'Maximum size', 'Memory address'], 'correct' => 1],
            ['question' => 'How do you delete a key from a map?', 'options' => ['m.delete(key)', 'remove(m, key)', 'delete(m, key)', 'm[key] = nil'], 'correct' => 2],
            ['question' => 'What is a variadic function in Go?', 'options' => ['A function with no parameters', 'A function that accepts a variable number of arguments using ...', 'A function returning multiple values', 'A recursive function'], 'correct' => 1],
            ['question' => 'What is the difference between new() and make() in Go?', 'options' => ['They are the same', 'new() allocates zeroed memory and returns a pointer; make() initialises slices, maps, and channels', 'make() returns a pointer; new() does not', 'new() is for primitives only'], 'correct' => 1],
        ],
    ],
    [
        'label' => 'Intermediate',
        'questions' => [
            ['question' => 'What is a Go interface?', 'options' => ['A concrete type', 'A set of method signatures that a type must implement to satisfy the interface', 'A base class', 'An abstract struct'], 'correct' => 1],
            ['question' => 'How does a type implement an interface in Go?', 'options' => ['By declaring "implements Interface"', 'Implicitly, by defining all the methods required by the interface', 'By embedding the interface', 'By using the implements keyword'], 'correct' => 1],
            ['question' => 'How do you define a method on a struct in Go?', 'options' => ['func MyStruct.Method() {}', 'method Method() on MyStruct {}', 'func (s MyStruct) Method() {}', 'def (MyStruct) Method() {}'], 'correct' => 2],
            ['question' => 'What is a goroutine?', 'options' => ['A thread from the OS', 'A lightweight, concurrently executing function managed by the Go runtime', 'A Go coroutine library', 'A parallel process'], 'correct' => 1],
            ['question' => 'How do you start a goroutine?', 'options' => ['goroutine func()', 'go func()', 'async func()', 'spawn func()'], 'correct' => 1],
            ['question' => 'What is a channel in Go?', 'options' => ['A network connection', 'A typed conduit for communication between goroutines', 'A goroutine pool', 'A mutex type'], 'correct' => 1],
            ['question' => 'How do you create a buffered channel with capacity 10?', 'options' => ['make(chan int, 10)', 'chan(int, 10)', 'new(chan int, 10)', 'channel(int, 10)'], 'correct' => 0],
            ['question' => 'What does the select statement do in Go?', 'options' => ['Selects a database row', 'Waits on multiple channel operations and executes the first one ready', 'Selects a goroutine to run', 'Selects a case in a switch'], 'correct' => 1],
            ['question' => 'What does the defer keyword do?', 'options' => ['Delays compilation', 'Schedules a function call to run after the surrounding function returns', 'Defers garbage collection', 'Delays variable initialisation'], 'correct' => 1],
            ['question' => 'In what order do deferred functions execute?', 'options' => ['FIFO (first in, first out)', 'LIFO (last in, first out — like a stack)', 'Random order', 'Alphabetical order'], 'correct' => 1],
            ['question' => 'What does panic() do in Go?', 'options' => ['Exits with code 0', 'Stops normal execution and begins unwinding the stack', 'Logs an error', 'Throws a checked exception'], 'correct' => 1],
            ['question' => 'What does recover() do?', 'options' => ['Restarts the program', 'Regains control of a panicking goroutine when called inside a deferred function', 'Recovers deleted files', 'Restores previous state'], 'correct' => 1],
            ['question' => 'What is the idiomatic error handling pattern in Go?', 'options' => ['try/catch blocks', 'Returning an error as the last return value and checking it with if err != nil', 'Using panic for all errors', 'Using exceptions'], 'correct' => 1],
            ['question' => 'What is the error interface in Go?', 'options' => ['A struct with a message', 'An interface with a single method: Error() string', 'A built-in exception type', 'A special keyword'], 'correct' => 1],
            ['question' => 'What does errors.New() do?', 'options' => ['Creates a new error type', 'Creates a simple error value with a given message string', 'Panics with a message', 'Creates a wrapped error'], 'correct' => 1],
            ['question' => 'What is io.Reader?', 'options' => ['A file reader struct', 'An interface with a Read(p []byte) (n int, err error) method', 'A network socket', 'A buffer type'], 'correct' => 1],
            ['question' => 'What is io.Writer?', 'options' => ['A file writer struct', 'An interface with a Write(p []byte) (n int, err error) method', 'A network connection', 'A logger type'], 'correct' => 1],
            ['question' => 'What does fmt.Errorf do?', 'options' => ['Formats and prints an error', 'Creates a new error with a formatted message string', 'Formats error output only', 'Logs formatted errors'], 'correct' => 1],
            ['question' => 'What is an embedded struct in Go?', 'options' => ['A struct inside a function', 'Promoting a type\'s fields and methods into another struct without naming the field', 'A nested struct literal', 'A pointer to a struct'], 'correct' => 1],
            ['question' => 'What does a nil channel operation do?', 'options' => ['Panics immediately', 'Sends and receives on a nil channel block forever', 'Returns zero value', 'Closes the channel'], 'correct' => 1],
            ['question' => 'What does closing a channel signal?', 'options' => ['The channel is deleted', 'No more values will be sent on it; receivers get zero values after draining', 'All goroutines stop', 'The program exits'], 'correct' => 1],
            ['question' => 'How do you detect if a channel is closed when receiving?', 'options' => ['val, ok := <-ch; if !ok means closed', 'ch.IsClosed()', 'val := <-ch; if val == nil', 'recover() in defer'], 'correct' => 0],
            ['question' => 'What is the strings package used for?', 'options' => ['File string operations', 'Common string manipulation functions like Contains, Split, Replace, ToUpper', 'Network string encoding', 'String to int conversion'], 'correct' => 1],
            ['question' => 'What does strconv.Atoi() do?', 'options' => ['Converts a string to ASCII', 'Converts a string to an integer', 'Converts ASCII to integer', 'Converts an integer to a string'], 'correct' => 1],
            ['question' => 'What is the os.Args variable?', 'options' => ['Operating system arguments', 'A slice of strings containing command-line arguments passed to the program', 'OS environment variables', 'A list of running processes'], 'correct' => 1],
        ],
    ],
    [
        'label' => 'Advanced',
        'questions' => [
            ['question' => 'What is reflection in Go?', 'options' => ['A mirror package', 'The ability to inspect and manipulate types and values at runtime using the reflect package', 'A build tool feature', 'Code generation'], 'correct' => 1],
            ['question' => 'Which function returns the reflect.Type of a value?', 'options' => ['reflect.TypeOf(v)', 'reflect.GetType(v)', 'v.Type()', 'reflect.Kind(v)'], 'correct' => 0],
            ['question' => 'What are generics in Go (introduced in 1.18)?', 'options' => ['A way to generate code', 'Type parameters that allow writing functions and types that work with any type satisfying a constraint', 'Interface embedding', 'Dynamic typing'], 'correct' => 1],
            ['question' => 'What is a type constraint in Go generics?', 'options' => ['A type assertion', 'An interface used to restrict which types can be used as type arguments', 'A compile-time check', 'A type alias'], 'correct' => 1],
            ['question' => 'What is the context package used for?', 'options' => ['HTTP routing', 'Carrying deadlines, cancellation signals, and request-scoped values across API boundaries', 'Configuration management', 'Logging context'], 'correct' => 1],
            ['question' => 'How do you create a cancellable context?', 'options' => ['context.NewCancel()', 'context.WithCancel(parent)', 'context.Cancel()', 'context.Timeout()'], 'correct' => 1],
            ['question' => 'What is sync.Mutex used for?', 'options' => ['Mutually exclusive goroutines', 'Protecting shared data from concurrent access with Lock() and Unlock()', 'Mutual recursion', 'Synchronising channels'], 'correct' => 1],
            ['question' => 'What is sync.WaitGroup used for?', 'options' => ['Waiting for a single channel', 'Waiting for a collection of goroutines to finish', 'Group locking', 'Synchronising network calls'], 'correct' => 1],
            ['question' => 'What is sync.Once used for?', 'options' => ['Running a goroutine once', 'Ensuring a function is executed exactly once even across goroutines', 'Once-per-request middleware', 'Single-use mutexes'], 'correct' => 1],
            ['question' => 'How do you write a test in Go?', 'options' => ['Create a file ending in _spec.go with Test functions', 'Create a file ending in _test.go with functions named TestXxx(t *testing.T)', 'Add @Test annotation', 'Use the test package\'s Register() function'], 'correct' => 1],
            ['question' => 'Which command runs Go tests?', 'options' => ['go test', 'go run test', 'go check', 'go verify'], 'correct' => 0],
            ['question' => 'What does t.Fatal() do in a test?', 'options' => ['Logs a fatal error only', 'Marks the test as failed and stops execution of the current test immediately', 'Panics the test binary', 'Skips remaining tests'], 'correct' => 1],
            ['question' => 'How do you write a benchmark test in Go?', 'options' => ['func BenchXxx(b *testing.B)', 'func BenchmarkXxx(b *testing.B)', 'func TestBench(b *testing.B)', 'func Bench_Xxx(b *testing.B)'], 'correct' => 1],
            ['question' => 'How do you create a simple HTTP server in Go?', 'options' => ['net.Listen and manually parse HTTP', 'http.ListenAndServe(":8080", nil)', 'http.NewServer(":8080").Start()', 'http.Create(":8080")'], 'correct' => 1],
            ['question' => 'What does http.HandleFunc do?', 'options' => ['Creates an HTTP client', 'Registers a handler function for a given URL pattern on DefaultServeMux', 'Handles errors in HTTP requests', 'Configures TLS'], 'correct' => 1],
            ['question' => 'How do you make an HTTP GET request in Go?', 'options' => ['http.Request("GET", url)', 'http.Get(url)', 'net.Get(url)', 'http.Fetch(url)'], 'correct' => 1],
            ['question' => 'How do you marshal a struct to JSON in Go?', 'options' => ['json.Encode(v)', 'json.Marshal(v)', 'json.Stringify(v)', 'json.Format(v)'], 'correct' => 1],
            ['question' => 'How do you unmarshal JSON into a struct?', 'options' => ['json.Decode(data, &v)', 'json.Parse(data, &v)', 'json.Unmarshal(data, &v)', 'json.Read(data, &v)'], 'correct' => 2],
            ['question' => 'What struct tag is used for JSON field naming?', 'options' => ['`xml:"name"`', '`json:"name"`', '`field:"name"`', '`label:"name"`'], 'correct' => 1],
            ['question' => 'What does json.Encoder write to?', 'options' => ['A string', 'An io.Writer', 'A file only', 'A byte slice'], 'correct' => 1],
            ['question' => 'What is the purpose of sync.RWMutex over sync.Mutex?', 'options' => ['It is faster for all use cases', 'It allows multiple concurrent readers or one exclusive writer, improving read-heavy workloads', 'It is simpler to use', 'It is used only for channels'], 'correct' => 1],
            ['question' => 'What does the -race flag do when running tests?', 'options' => ['Runs tests in parallel always', 'Enables the race detector to find data races in concurrent code', 'Makes tests run faster', 'Races goroutines against each other'], 'correct' => 1],
            ['question' => 'What is an http.Handler interface?', 'options' => ['A function type', 'An interface with a ServeHTTP(ResponseWriter, *Request) method', 'A middleware struct', 'An HTTP client interface'], 'correct' => 1],
            ['question' => 'What does context.WithTimeout return?', 'options' => ['A timed goroutine', 'A derived context that cancels after the specified duration, and a cancel function', 'A time.Timer', 'A deadline error'], 'correct' => 1],
            ['question' => 'What is table-driven testing in Go?', 'options' => ['Testing with a database table', 'A pattern where test cases are defined as a slice of structs and iterated in a single test function', 'Testing UI tables', 'A third-party testing style'], 'correct' => 1],
        ],
    ],
    [
        'label' => 'Expert',
        'questions' => [
            ['question' => 'What does GMP stand for in Go\'s scheduler?', 'options' => ['Go, Memory, Process', 'Goroutine, M (OS thread), P (logical processor)', 'Goroutine Management Protocol', 'Global Memory Pool'], 'correct' => 1],
            ['question' => 'What is a P (processor) in Go\'s GMP scheduler model?', 'options' => ['A physical CPU core', 'A logical processor that holds a run queue and is required to execute goroutines', 'A goroutine pool', 'A parallel worker'], 'correct' => 1],
            ['question' => 'What algorithm does Go\'s scheduler use to balance goroutines across Ps?', 'options' => ['Round-robin', 'Work stealing — idle Ps steal goroutines from the run queues of busy Ps', 'Priority queue', 'FIFO queue globally'], 'correct' => 1],
            ['question' => 'What type of garbage collector does Go use?', 'options' => ['Reference counting', 'Stop-the-world mark-and-sweep', 'Concurrent tri-color mark-and-sweep with very short STW pauses', 'Generational GC'], 'correct' => 2],
            ['question' => 'What is escape analysis in Go?', 'options' => ['Analysing goroutine escapes', 'Compiler analysis determining whether a variable should be allocated on the stack or heap', 'Checking for panic escape paths', 'Profile-guided optimisation'], 'correct' => 1],
            ['question' => 'If a variable escapes to the heap, what happens?', 'options' => ['It is garbage collected immediately', 'It is allocated on the heap and managed by GC, adding allocation overhead', 'It is moved to a global variable', 'It panics at runtime'], 'correct' => 1],
            ['question' => 'What is the unsafe package in Go?', 'options' => ['A package that disables security checks', 'A package providing operations that bypass type safety, such as pointer arithmetic', 'An experimental package', 'A package for unsafe concurrency'], 'correct' => 1],
            ['question' => 'What is CGo?', 'options' => ['A C compiler for Go', 'A feature enabling Go programs to call C functions and use C libraries', 'A Go-to-C transpiler', 'A C binding generator'], 'correct' => 1],
            ['question' => 'What are build tags in Go?', 'options' => ['Git tags for Go modules', 'Constraints in source files controlling whether the file is included in a build', 'Build metadata labels', 'Dependency version tags'], 'correct' => 1],
            ['question' => 'What is pprof used for?', 'options' => ['Pretty-printing output', 'Profiling Go programs to analyse CPU, memory, goroutine, and other performance data', 'Unit test profiling only', 'Network profiling'], 'correct' => 1],
            ['question' => 'How do you enable CPU profiling in a Go program?', 'options' => ['go build --profile', 'import _ "net/http/pprof" and use pprof.StartCPUProfile', 'go run -cpu-profile', 'runtime.SetCPUProfileRate and pprof.StartCPUProfile(w)'], 'correct' => 3],
            ['question' => 'What is the Go plugin system?', 'options' => ['A package manager plugin API', 'The ability to build and load .so shared libraries dynamically with the plugin package', 'A VS Code plugin', 'A Docker plugin API'], 'correct' => 1],
            ['question' => 'What does GOGC environment variable control?', 'options' => ['Go compiler version', 'The GC target percentage — the ratio of new heap allocation to live heap triggering a GC cycle', 'Go module caching', 'Goroutine count'], 'correct' => 1],
            ['question' => 'What does GOMAXPROCS control?', 'options' => ['Maximum goroutines', 'The maximum number of OS threads (P logical processors) executing Go code simultaneously', 'Maximum processes', 'Maximum memory'], 'correct' => 1],
            ['question' => 'What is runtime.Gosched()?', 'options' => ['Gets the goroutine schedule', 'Yields the processor, allowing other goroutines to run', 'Gets runtime scheduling info', 'Schedules a deferred function'], 'correct' => 1],
            ['question' => 'What is go:generate?', 'options' => ['A build command', 'A special comment directive that records commands to be run by "go generate" for code generation', 'A test generator', 'An automatic go.mod updater'], 'correct' => 1],
            ['question' => 'What is the go.sum file used for?', 'options' => ['Summarising module info', 'Recording expected cryptographic checksums of module content for verification', 'Storing build tags', 'Listing build dependencies'], 'correct' => 1],
            ['question' => 'What does GOPATH represent in Go modules era?', 'options' => ['The module root', 'The workspace directory used to cache downloaded modules and binaries (less central with modules)', 'The Go installation path', 'The project source path'], 'correct' => 1],
            ['question' => 'What is the runtime package in Go?', 'options' => ['A third-party library', 'A package providing operations that interact with Go\'s runtime system (GC, goroutines, OS, etc.)', 'A test runtime', 'A container runtime'], 'correct' => 1],
            ['question' => 'What does runtime.NumGoroutine() return?', 'options' => ['Maximum goroutine count', 'The number of goroutines currently existing', 'Goroutine ID', 'Total goroutines ever created'], 'correct' => 1],
            ['question' => 'What is atomic package used for?', 'options' => ['Atomic transactions', 'Low-level atomic memory operations for safe concurrent access without mutexes', 'Atomic file writes', 'Atomic channel operations'], 'correct' => 1],
            ['question' => 'What is the difference between sync/atomic and sync.Mutex?', 'options' => ['They are equivalent', 'Atomic ops are faster for simple counter/flag updates; Mutex is needed for complex critical sections', 'Mutex is always faster', 'Atomic is only for int64'], 'correct' => 1],
            ['question' => 'What is a Go workspace (go work)?', 'options' => ['GOPATH workspace', 'A multi-module workspace allowing local development across multiple modules without replace directives', 'A project template', 'A CI workspace'], 'correct' => 1],
            ['question' => 'What does unsafe.Sizeof() return?', 'options' => ['The size of the unsafe package', 'The size in bytes of the value\'s type', 'The pointer size', 'The heap allocation size'], 'correct' => 1],
            ['question' => 'What is the GC write barrier in Go?', 'options' => ['A memory safety fence', 'A mechanism that informs the GC about pointer writes during concurrent marking to maintain heap consistency', 'A goroutine synchronisation primitive', 'A write-once variable guard'], 'correct' => 1],
        ],
    ],
];
require_once __DIR__ . '/quiz-engine.php';
