<?php
$page_title = 'HTML Quiz – 100 Levels – CodeFoundry';
$active_page = 'training';
$quiz_title  = 'HTML';
$quiz_slug   = 'html';
$quiz_tiers  = [
    [
        'label' => 'Introduction',
        'questions' => [
            ['question' => 'What does HTML stand for?', 'options' => ['Hyper Text Markup Language', 'High Tech Modern Language', 'Home Tool Markup Language', 'Hyperlinks and Text Markup Language'], 'correct' => 0],
            ['question' => 'Which HTML tag is used for the largest heading?', 'options' => ['&lt;h6&gt;', '&lt;heading&gt;', '&lt;h1&gt;', '&lt;head&gt;'], 'correct' => 2],
            ['question' => 'What is the correct HTML element for inserting a line break?', 'options' => ['&lt;break&gt;', '&lt;br&gt;', '&lt;lb&gt;', '&lt;newline&gt;'], 'correct' => 1],
            ['question' => 'Which character is used to indicate an end tag?', 'options' => ['*', '&lt;', '^', '/'], 'correct' => 3],
            ['question' => 'What is the correct HTML for creating a hyperlink?', 'options' => ['&lt;a url="http://example.com"&gt;Example&lt;/a&gt;', '&lt;a href="http://example.com"&gt;Example&lt;/a&gt;', '&lt;a&gt;http://example.com&lt;/a&gt;', '&lt;link&gt;http://example.com&lt;/link&gt;'], 'correct' => 1],
            ['question' => 'How can you make a numbered list?', 'options' => ['&lt;ul&gt;', '&lt;ol&gt;', '&lt;list&gt;', '&lt;dl&gt;'], 'correct' => 1],
            ['question' => 'How can you make a bulleted list?', 'options' => ['&lt;ol&gt;', '&lt;list&gt;', '&lt;ul&gt;', '&lt;dl&gt;'], 'correct' => 2],
            ['question' => 'What is the correct HTML for inserting an image?', 'options' => ['&lt;img href="image.jpg"&gt;', '&lt;img src="image.jpg"&gt;', '&lt;image src="image.jpg"&gt;', '&lt;img&gt;image.jpg&lt;/img&gt;'], 'correct' => 1],
            ['question' => 'Which HTML attribute specifies an alternate text for an image?', 'options' => ['title', 'alt', 'src', 'longdesc'], 'correct' => 1],
            ['question' => 'What does the &lt;!DOCTYPE html&gt; declaration define?', 'options' => ['The HTML version', 'The document type', 'The character encoding', 'The page title'], 'correct' => 1],
            ['question' => 'Which HTML element defines the title of a document?', 'options' => ['&lt;meta&gt;', '&lt;head&gt;', '&lt;title&gt;', '&lt;header&gt;'], 'correct' => 2],
            ['question' => 'Which HTML tag is used to define a paragraph?', 'options' => ['&lt;paragraph&gt;', '&lt;p&gt;', '&lt;para&gt;', '&lt;pg&gt;'], 'correct' => 1],
            ['question' => 'Where should the &lt;title&gt; tag be placed in HTML?', 'options' => ['In the &lt;body&gt; section', 'In the &lt;head&gt; section', 'At the beginning of the document', 'At the end of the document'], 'correct' => 1],
            ['question' => 'Which HTML element is used to specify a footer for a document?', 'options' => ['&lt;bottom&gt;', '&lt;section&gt;', '&lt;footer&gt;', '&lt;foot&gt;'], 'correct' => 2],
            ['question' => 'What is the correct HTML element for the largest heading?', 'options' => ['&lt;heading&gt;', '&lt;h6&gt;', '&lt;head&gt;', '&lt;h1&gt;'], 'correct' => 3],
            ['question' => 'Which HTML attribute is used to define inline styles?', 'options' => ['class', 'style', 'font', 'styles'], 'correct' => 1],
            ['question' => 'How do you create a comment in HTML?', 'options' => ['// This is a comment', '/* This is a comment */', '&lt;!-- This is a comment --&gt;', '&lt;comment&gt;This is a comment&lt;/comment&gt;'], 'correct' => 2],
            ['question' => 'Which HTML element is used to define important text?', 'options' => ['&lt;strong&gt;', '&lt;b&gt;', '&lt;i&gt;', '&lt;important&gt;'], 'correct' => 0],
            ['question' => 'Which HTML element is used to define emphasized text?', 'options' => ['&lt;italic&gt;', '&lt;i&gt;', '&lt;em&gt;', '&lt;emphasis&gt;'], 'correct' => 2],
            ['question' => 'What is the correct HTML for adding a background color?', 'options' => ['&lt;body bg="yellow"&gt;', '&lt;background&gt;yellow&lt;/background&gt;', '&lt;body style="background-color:yellow;"&gt;', '&lt;body color="yellow"&gt;'], 'correct' => 2],
            ['question' => 'Which HTML element defines a table?', 'options' => ['&lt;tab&gt;', '&lt;table&gt;', '&lt;tr&gt;', '&lt;td&gt;'], 'correct' => 1],
            ['question' => 'Which HTML element defines a table row?', 'options' => ['&lt;tr&gt;', '&lt;td&gt;', '&lt;row&gt;', '&lt;table-row&gt;'], 'correct' => 0],
            ['question' => 'Which HTML element defines a table cell?', 'options' => ['&lt;cell&gt;', '&lt;tc&gt;', '&lt;td&gt;', '&lt;tr&gt;'], 'correct' => 2],
            ['question' => 'What does the &lt;hr&gt; tag create?', 'options' => ['A horizontal line', 'A header', 'A hard return', 'A hyperlink reference'], 'correct' => 0],
            ['question' => 'Which HTML element is used for a container with no semantic meaning?', 'options' => ['&lt;section&gt;', '&lt;div&gt;', '&lt;container&gt;', '&lt;box&gt;'], 'correct' => 1],
            ['question' => 'What is the difference between &lt;div&gt; and &lt;span&gt;?', 'options' => ['div is inline, span is block', 'div is block, span is inline', 'div is deprecated, span is modern', 'They are the same'], 'correct' => 1],
            ['question' => 'What does the charset attribute in &lt;meta&gt; define?', 'options' => ['The page language', 'The character encoding', 'The page style', 'The page title'], 'correct' => 1],
            ['question' => 'What is the purpose of the viewport meta tag?', 'options' => ['To set page colors', 'To control page layout on mobile browsers', 'To add SEO keywords', 'To define the page title'], 'correct' => 1],
        ]
    ],
    [
        'label' => 'Beginner',
        'questions' => [
            ['question' => 'Which input type is used for password fields?', 'options' => ['text', 'password', 'hidden', 'secure'], 'correct' => 1],
            ['question' => 'What is the correct HTML for making a text input field?', 'options' => ['&lt;input type="text"&gt;', '&lt;textfield&gt;', '&lt;input type="textfield"&gt;', '&lt;textinput&gt;'], 'correct' => 0],
            ['question' => 'What is the purpose of the &lt;label&gt; element?', 'options' => ['To style text', 'To create a caption for form elements', 'To add a tooltip', 'To create a button'], 'correct' => 1],
            ['question' => 'Which HTML element is used to create a dropdown list?', 'options' => ['&lt;list&gt;', '&lt;select&gt;', '&lt;dropdown&gt;', '&lt;input type="dropdown"&gt;'], 'correct' => 1],
            ['question' => 'Which element is used with &lt;select&gt; to define list options?', 'options' => ['&lt;item&gt;', '&lt;option&gt;', '&lt;list&gt;', '&lt;choice&gt;'], 'correct' => 1],
            ['question' => 'What is the correct HTML for a text area?', 'options' => ['&lt;input type="textarea"&gt;', '&lt;textarea&gt;', '&lt;text&gt;', '&lt;input type="textbox"&gt;'], 'correct' => 1],
            ['question' => 'Which HTML element groups related form elements?', 'options' => ['&lt;group&gt;', '&lt;fieldset&gt;', '&lt;formgroup&gt;', '&lt;section&gt;'], 'correct' => 1],
            ['question' => 'What element provides a caption for a &lt;fieldset&gt;?', 'options' => ['&lt;caption&gt;', '&lt;title&gt;', '&lt;legend&gt;', '&lt;label&gt;'], 'correct' => 2],
            ['question' => 'Which element defines a table header?', 'options' => ['&lt;thead&gt;', '&lt;th&gt;', '&lt;header&gt;', '&lt;head&gt;'], 'correct' => 0],
            ['question' => 'Which element defines the body of a table?', 'options' => ['&lt;body&gt;', '&lt;table-body&gt;', '&lt;tbody&gt;', '&lt;tb&gt;'], 'correct' => 2],
            ['question' => 'What does the colspan attribute do?', 'options' => ['Sets column width', 'Merges cells horizontally', 'Colors a column', 'Adds column spacing'], 'correct' => 1],
            ['question' => 'What does the rowspan attribute do?', 'options' => ['Sets row height', 'Merges cells vertically', 'Colors a row', 'Adds row spacing'], 'correct' => 1],
            ['question' => 'How do you create a nested list?', 'options' => ['Use &lt;nested&gt;', 'Place a list inside an &lt;li&gt; element', 'Use the nested attribute', 'Use &lt;sublist&gt;'], 'correct' => 1],
            ['question' => 'What does the target="_blank" attribute do in a link?', 'options' => ['Opens in same window', 'Opens in new tab/window', 'Downloads the file', 'Creates a popup'], 'correct' => 1],
            ['question' => 'Which attribute makes a link downloadable?', 'options' => ['download', 'href', 'save', 'file'], 'correct' => 0],
            ['question' => 'Which HTML element embeds an audio file?', 'options' => ['&lt;sound&gt;', '&lt;audio&gt;', '&lt;music&gt;', '&lt;media&gt;'], 'correct' => 1],
            ['question' => 'Which HTML element embeds a video file?', 'options' => ['&lt;movie&gt;', '&lt;media&gt;', '&lt;video&gt;', '&lt;film&gt;'], 'correct' => 2],
            ['question' => 'What is the &lt;figure&gt; element used for?', 'options' => ['Mathematical figures', 'Self-contained content like illustrations', 'Numeric data', 'User figures'], 'correct' => 1],
            ['question' => 'What element provides a caption for &lt;figure&gt;?', 'options' => ['&lt;caption&gt;', '&lt;legend&gt;', '&lt;figcaption&gt;', '&lt;title&gt;'], 'correct' => 2],
            ['question' => 'What does the &lt;details&gt; element create?', 'options' => ['A tooltip', 'A disclosure widget', 'A modal', 'A dropdown menu'], 'correct' => 1],
            ['question' => 'Which element provides a visible heading for &lt;details&gt;?', 'options' => ['&lt;heading&gt;', '&lt;summary&gt;', '&lt;title&gt;', '&lt;caption&gt;'], 'correct' => 1],
            ['question' => 'Which HTML element embeds another HTML page?', 'options' => ['&lt;embed&gt;', '&lt;frame&gt;', '&lt;iframe&gt;', '&lt;include&gt;'], 'correct' => 2],
            ['question' => 'What does the &lt;abbr&gt; element represent?', 'options' => ['A shortened text', 'An abbreviation or acronym', 'Abstract content', 'An absolute value'], 'correct' => 1],
            ['question' => 'Which element displays code?', 'options' => ['&lt;code&gt;', '&lt;pre&gt;', '&lt;script&gt;', '&lt;program&gt;'], 'correct' => 0],
            ['question' => 'Which element preserves whitespace and line breaks?', 'options' => ['&lt;whitespace&gt;', '&lt;pre&gt;', '&lt;code&gt;', '&lt;preserve&gt;'], 'correct' => 1],
            ['question' => 'What is &lt;blockquote&gt; used for?', 'options' => ['Blocking content', 'Long quotations', 'Code blocks', 'Block-level divs'], 'correct' => 1],
            ['question' => 'Which element represents a navigation section?', 'options' => ['&lt;navigation&gt;', '&lt;nav&gt;', '&lt;menu&gt;', '&lt;navbar&gt;'], 'correct' => 1],
            ['question' => 'Which element represents the main content of a document?', 'options' => ['&lt;content&gt;', '&lt;primary&gt;', '&lt;main&gt;', '&lt;body&gt;'], 'correct' => 2],
        ]
    ],
    [
        'label' => 'Intermediate',
        'questions' => [
            ['question' => 'Which attribute is used to store custom data in HTML5?', 'options' => ['custom-*', 'data-*', 'meta-*', 'user-*'], 'correct' => 1],
            ['question' => 'What does ARIA stand for?', 'options' => ['Advanced Rich Internet Applications', 'Accessible Rich Internet Applications', 'Automated Responsive Internet Access', 'Applied Real Internet Architecture'], 'correct' => 1],
            ['question' => 'Which attribute makes a form field required?', 'options' => ['validate', 'required', 'mandatory', 'necessary'], 'correct' => 1],
            ['question' => 'Which attribute specifies a validation pattern for input?', 'options' => ['regex', 'pattern', 'validate', 'format'], 'correct' => 1],
            ['question' => 'Which input type is for email addresses?', 'options' => ['text', 'email', 'mail', 'e-mail'], 'correct' => 1],
            ['question' => 'Which input type creates a date picker?', 'options' => ['calendar', 'date', 'datetime', 'picker'], 'correct' => 1],
            ['question' => 'Which input type creates a color picker?', 'options' => ['color', 'picker', 'rgb', 'colorpicker'], 'correct' => 0],
            ['question' => 'Which input type creates a range slider?', 'options' => ['slider', 'range', 'number', 'scale'], 'correct' => 1],
            ['question' => 'What is the &lt;picture&gt; element used for?', 'options' => ['Displaying images', 'Responsive images with multiple sources', 'Image galleries', 'Picture frames'], 'correct' => 1],
            ['question' => 'What does the srcset attribute do?', 'options' => ['Sets the image source', 'Provides multiple image sources for responsive images', 'Sets image style', 'Creates an image set'], 'correct' => 1],
            ['question' => 'What is the &lt;template&gt; element used for?', 'options' => ['Page templates', 'HTML content that is not rendered but can be cloned via JavaScript', 'CSS templates', 'Document templates'], 'correct' => 1],
            ['question' => 'What does the contenteditable attribute do?', 'options' => ['Makes content visible', 'Makes content editable by the user', 'Enables content', 'Creates content'], 'correct' => 1],
            ['question' => 'What does the spellcheck attribute control?', 'options' => ['Grammar checking', 'Spell checking for editable content', 'Text validation', 'Language detection'], 'correct' => 1],
            ['question' => 'What does the draggable attribute do?', 'options' => ['Makes elements movable', 'Enables drag and drop functionality', 'Allows element resizing', 'Creates draggable windows'], 'correct' => 1],
            ['question' => 'What does the tabindex attribute control?', 'options' => ['Tab width', 'Tab order for keyboard navigation', 'Number of tabs', 'Tab style'], 'correct' => 1],
            ['question' => 'What is the &lt;canvas&gt; element used for?', 'options' => ['Drawing graphics via JavaScript', 'Creating containers', 'Canvas backgrounds', 'Art galleries'], 'correct' => 0],
            ['question' => 'How is inline SVG different from SVG in &lt;img&gt;?', 'options' => ['No difference', 'Inline SVG can be styled with CSS and manipulated with JS', 'Inline SVG loads faster', 'img SVG has better quality'], 'correct' => 1],
            ['question' => 'What is microdata used for?', 'options' => ['Small data storage', 'Embedding machine-readable data in HTML', 'Micro-optimization', 'Data compression'], 'correct' => 1],
            ['question' => 'What does async attribute do on &lt;script&gt;?', 'options' => ['Loads script asynchronously without blocking HTML parsing', 'Loads script slowly', 'Makes script run faster', 'Delays script execution'], 'correct' => 0],
            ['question' => 'What does defer attribute do on &lt;script&gt;?', 'options' => ['Delays script forever', 'Executes script after HTML parsing completes', 'Removes the script', 'Defers to other scripts'], 'correct' => 1],
            ['question' => 'What is the &lt;base&gt; tag used for?', 'options' => ['Base styling', 'Specifying base URL for relative links', 'Database connection', 'Base template'], 'correct' => 1],
            ['question' => 'What is the &lt;noscript&gt; tag for?', 'options' => ['Disabling scripts', 'Content shown when JavaScript is disabled', 'Script errors', 'Non-scripted content'], 'correct' => 1],
            ['question' => 'Which input type is for telephone numbers?', 'options' => ['phone', 'tel', 'telephone', 'number'], 'correct' => 1],
            ['question' => 'Which input type creates a search field?', 'options' => ['text', 'search', 'find', 'query'], 'correct' => 1],
            ['question' => 'What does the sizes attribute work with?', 'options' => ['Font sizes', 'srcset for responsive images', 'Element dimensions', 'Screen sizes'], 'correct' => 1],
            ['question' => 'Which element represents a definition list?', 'options' => ['&lt;dl&gt;', '&lt;list&gt;', '&lt;def&gt;', '&lt;definition&gt;'], 'correct' => 0],
            ['question' => 'Which element represents a definition term in a definition list?', 'options' => ['&lt;term&gt;', '&lt;dt&gt;', '&lt;def&gt;', '&lt;word&gt;'], 'correct' => 1],
            ['question' => 'Which element represents a definition description?', 'options' => ['&lt;desc&gt;', '&lt;def&gt;', '&lt;dd&gt;', '&lt;description&gt;'], 'correct' => 2],
        ]
    ],
    [
        'label' => 'Advanced',
        'questions' => [
            ['question' => 'What is Shadow DOM?', 'options' => ['A dark theme', 'Encapsulated DOM and styling for web components', 'Hidden elements', 'Deprecated DOM'], 'correct' => 1],
            ['question' => 'What API is used to create custom HTML elements?', 'options' => ['Custom Elements API', 'Web Components API', 'Element API', 'DOM API'], 'correct' => 0],
            ['question' => 'What does WCAG stand for?', 'options' => ['Web Content Accessibility Guidelines', 'World Content Access Group', 'Web Component Architecture Guide', 'Website Compliance and Governance'], 'correct' => 0],
            ['question' => 'What is the purpose of dns-prefetch?', 'options' => ['Prefetch DNS records to reduce latency', 'Fetch DNS settings', 'Prefer DNS', 'DNS configuration'], 'correct' => 0],
            ['question' => 'What does preconnect resource hint do?', 'options' => ['Connects to users', 'Establishes early connection to origin', 'Preferred connection', 'Connects databases'], 'correct' => 1],
            ['question' => 'What is lazy loading for images?', 'options' => ['Slow loading', 'Loading images only when needed/visible', 'Delayed loading', 'Background loading'], 'correct' => 1],
            ['question' => 'What is Content Security Policy (CSP)?', 'options' => ['Content styling rules', 'Security standard to prevent XSS and injection attacks', 'Content storage policy', 'CSS policy'], 'correct' => 1],
            ['question' => 'What are Open Graph tags used for?', 'options' => ['Opening graphs', 'Social media previews and rich sharing', 'Graph databases', 'Data visualization'], 'correct' => 1],
            ['question' => 'What are Twitter Card meta tags for?', 'options' => ['Card games', 'Rich previews on Twitter', 'Payment cards', 'Business cards'], 'correct' => 1],
            ['question' => 'What is structured data with JSON-LD?', 'options' => ['JSON loading', 'Machine-readable data for search engines', 'JSON library', 'Linked data'], 'correct' => 1],
            ['question' => 'What does the canonical link do?', 'options' => ['Creates canons', 'Indicates the preferred URL for duplicate content', 'Standard link', 'Original link'], 'correct' => 1],
            ['question' => 'What is hreflang used for?', 'options' => ['Link language', 'Indicating language and regional targeting', 'Hyperlink reference', 'Language attribute'], 'correct' => 1],
            ['question' => 'What does the robots meta tag control?', 'options' => ['Robot content', 'Search engine crawling and indexing', 'Automated testing', 'Bot detection'], 'correct' => 1],
            ['question' => 'What is the Intersection Observer used for?', 'options' => ['Intersecting lines', 'Detecting when elements enter/exit viewport', 'Element intersection', 'Observer pattern'], 'correct' => 1],
            ['question' => 'What does rel="preload" do?', 'options' => ['Preloads the page', 'Declares resource that will be needed soon', 'Loads before scripts', 'Primary load'], 'correct' => 1],
            ['question' => 'What does rel="prefetch" do?', 'options' => ['Fetches preferences', 'Hints browser to fetch resource for future navigation', 'Fetches data', 'Primary fetch'], 'correct' => 1],
            ['question' => 'What is LCP in Core Web Vitals?', 'options' => ['Least Common Page', 'Largest Contentful Paint', 'Load Complete Point', 'Link Cache Protocol'], 'correct' => 1],
            ['question' => 'What is CLS in Core Web Vitals?', 'options' => ['Content Load Speed', 'Cumulative Layout Shift', 'Cache Level Storage', 'Client-side Script'], 'correct' => 1],
            ['question' => 'What is FID in Core Web Vitals?', 'options' => ['Fast Input Detection', 'First Input Delay', 'Form Input Data', 'File ID'], 'correct' => 1],
            ['question' => 'What is the purpose of X-UA-Compatible meta tag?', 'options' => ['User agent compatibility', 'IE document mode specification', 'Cross-browser compatibility', 'UA tracking'], 'correct' => 1],
            ['question' => 'What does the referrerpolicy attribute control?', 'options' => ['Reference policy', 'How much referrer information is sent with requests', 'Referral tracking', 'Policy documents'], 'correct' => 1],
            ['question' => 'What is the manifest attribute used for?', 'options' => ['Document manifest', 'Progressive Web App manifest', 'File list', 'Manifest destiny'], 'correct' => 1],
            ['question' => 'What is HTTP/2 Server Push?', 'options' => ['Pushing updates', 'Server sends resources before requested', 'Push notifications', 'Server push technology'], 'correct' => 1],
            ['question' => 'How can you register a Service Worker from HTML?', 'options' => ['&lt;serviceworker&gt; tag', 'Via JavaScript referenced in &lt;script&gt;', 'service-worker attribute', 'Worker tag'], 'correct' => 1],
            ['question' => 'What is the loading="lazy" attribute for?', 'options' => ['Slow loading', 'Native lazy loading for images and iframes', 'Loading indicator', 'Lazy initialization'], 'correct' => 1],
            ['question' => 'What does ARIA role="button" indicate?', 'options' => ['A styled button', 'An element that acts as a button', 'A form button', 'A clickable area'], 'correct' => 1],
            ['question' => 'What is aria-label used for?', 'options' => ['Label styling', 'Providing accessible name for screen readers', 'Area labels', 'ARIA configuration'], 'correct' => 1],
            ['question' => 'What is the critical rendering path?', 'options' => ['Critical CSS', 'Steps browser takes to render page', 'Important rendering', 'Critical path algorithm'], 'correct' => 1],
        ]
    ],
    [
        'label' => 'Expert',
        'questions' => [
            ['question' => 'What are the main phases of HTML parsing?', 'options' => ['Parse and render', 'Tokenization, tree construction, and rendering', 'Load and execute', 'Fetch and display'], 'correct' => 1],
            ['question' => 'What is quirks mode in HTML?', 'options' => ['Bug mode', 'Legacy compatibility mode for old browsers', 'Quick mode', 'Testing mode'], 'correct' => 1],
            ['question' => 'What is standards mode?', 'options' => ['Standard features', 'Mode where browser follows modern HTML/CSS specs', 'Normal mode', 'Official mode'], 'correct' => 1],
            ['question' => 'What is speculative parsing?', 'options' => ['Guessing content', 'Parser looks ahead to load resources early', 'Theoretical parsing', 'Experimental parsing'], 'correct' => 1],
            ['question' => 'How does HTML5 parser handle errors?', 'options' => ['Stops parsing', 'Defined error handling with error recovery', 'Shows error message', 'Ignores errors'], 'correct' => 1],
            ['question' => 'Why is document.write() problematic?', 'options' => ['Slow writing', 'Can block parser and harm performance', 'Deprecated method', 'Security risk'], 'correct' => 1],
            ['question' => 'What are blocking resources?', 'options' => ['Blocked content', 'Resources that prevent page rendering', 'Blocking scripts', 'Firewall blocks'], 'correct' => 1],
            ['question' => 'What is a render-blocking resource?', 'options' => ['Blocked renders', 'Resource that delays first paint', 'Rendering error', 'Block-level render'], 'correct' => 1],
            ['question' => 'What are Server-Sent Events (SSE)?', 'options' => ['Server events', 'Server push updates via HTTP', 'Event tracking', 'Server-side events'], 'correct' => 1],
            ['question' => 'What is the &lt;portal&gt; element?', 'options' => ['Web portal', 'Embedding and seamless navigation to other pages', 'Gateway element', 'Portal interface'], 'correct' => 1],
            ['question' => 'What are Signed Exchanges (SXG)?', 'options' => ['Signed documents', 'Cryptographically signed HTTP exchanges for privacy-preserving prefetch', 'Exchange rates', 'Signature system'], 'correct' => 1],
            ['question' => 'How can WebAssembly be loaded from HTML?', 'options' => ['&lt;wasm&gt; tag', 'Via JavaScript in &lt;script&gt; tag', 'wasm attribute', 'Assembly tag'], 'correct' => 1],
            ['question' => 'What are import maps?', 'options' => ['Import configuration', 'Control JavaScript module import resolution', 'Map imports', 'Import routing'], 'correct' => 1],
            ['question' => 'What is HTML sanitization?', 'options' => ['Cleaning HTML', 'Removing dangerous content to prevent XSS', 'HTML validation', 'Sanitize inputs'], 'correct' => 1],
            ['question' => 'What are Trusted Types?', 'options' => ['Type safety', 'API to prevent DOM XSS by validating dangerous operations', 'Trusted content', 'Type checking'], 'correct' => 1],
            ['question' => 'What is CSS containment?', 'options' => ['Containing styles', 'Isolating element rendering for performance', 'Container queries', 'Style isolation'], 'correct' => 1],
            ['question' => 'What is layout thrashing?', 'options' => ['Layout errors', 'Forced synchronous layout causing performance issues', 'Layout breaking', 'Thrashing memory'], 'correct' => 1],
            ['question' => 'What is the accessibility tree?', 'options' => ['Tree structure', 'Browser representation of page for assistive technologies', 'DOM tree', 'Access control'], 'correct' => 1],
            ['question' => 'What is the browser rendering pipeline?', 'options' => ['Render process', 'Parse, Style, Layout, Paint, Composite', 'Pipeline pattern', 'Rendering flow'], 'correct' => 1],
            ['question' => 'What is compositing in browser rendering?', 'options' => ['Combining elements', 'Combining painted layers into final screen image', 'Component composition', 'Composite pattern'], 'correct' => 1],
            ['question' => 'What triggers a reflow?', 'options' => ['Flow changes', 'Changes to layout properties like width/height', 'Content flow', 'Reflowing water'], 'correct' => 1],
            ['question' => 'What triggers a repaint?', 'options' => ['Painting again', 'Changes to visual properties like color', 'Repainting walls', 'Paint refresh'], 'correct' => 1],
            ['question' => 'What is virtual scrolling?', 'options' => ['Virtual reality scrolling', 'Rendering only visible items in long lists', 'Scroll simulation', 'Virtual DOM scrolling'], 'correct' => 1],
            ['question' => 'What is the tree construction phase in HTML parsing?', 'options' => ['Building trees', 'Creating DOM tree from tokens', 'Tree algorithms', 'Construction phase'], 'correct' => 1],
            ['question' => 'What is tokenization in HTML parsing?', 'options' => ['Token security', 'Breaking HTML into tokens (tags, text, etc.)', 'Token generation', 'Creating tokens'], 'correct' => 1],
            ['question' => 'What impacts Cumulative Layout Shift (CLS)?', 'options' => ['Layout changes', 'Unexpected layout shifts of visible content', 'Shift key', 'Content shifts'], 'correct' => 1],
            ['question' => 'What impacts Largest Contentful Paint (LCP)?', 'options' => ['Large content', 'Time to render largest visible content element', 'Content painting', 'Large files'], 'correct' => 1],
            ['question' => 'What impacts First Input Delay (FID)?', 'options' => ['Input speed', 'Time from user interaction to browser response', 'First input', 'Delay time'], 'correct' => 1],
        ]
    ],
];
require_once __DIR__ . '/quiz-engine.php';
