<?php
$page_title = 'Java Quiz – 100 Levels – CodeFoundry';
$active_page = 'training';
$quiz_title  = 'Java';
$quiz_slug   = 'java';
$quiz_tiers  = [
    ['label' => 'Introduction', 'questions' => [
        ['question' => 'When was Java first released?', 'options' => ['1991', '1995', '2000', '1990'], 'correct' => 1],
        ['question' => 'What does JVM stand for?', 'options' => ['Java Virtual Machine', 'Java Visual Manager', 'Java Version Manager', 'Java Variable Method'], 'correct' => 0],
        ['question' => 'What does JDK stand for?', 'options' => ['Java Development Kit', 'Java Deployment Kit', 'Java Design Kit', 'Java Distribution Kit'], 'correct' => 0],
        ['question' => 'What does JRE stand for?', 'options' => ['Java Runtime Environment', 'Java Release Environment', 'Java Reference Engine', 'Java Revision Environment'], 'correct' => 0],
        ['question' => 'What is the correct signature for the main method?', 'options' => ['public void main()', 'public static void main(String[] args)', 'static void main()', 'void main(String args)'], 'correct' => 1],
        ['question' => 'Which statement prints output to console?', 'options' => ['print()', 'System.out.println()', 'console.log()', 'echo()'], 'correct' => 1],
        ['question' => 'Which data type is used for whole numbers in Java?', 'options' => ['int', 'number', 'integer', 'whole'], 'correct' => 0],
        ['question' => 'Which data type stores decimal numbers?', 'options' => ['decimal', 'float', 'real', 'number'], 'correct' => 1],
        ['question' => 'Which data type stores a single character?', 'options' => ['char', 'character', 'chr', 'letter'], 'correct' => 0],
        ['question' => 'Which data type stores true/false values?', 'options' => ['bool', 'boolean', 'bit', 'binary'], 'correct' => 1],
        ['question' => 'How do you declare a variable in Java?', 'options' => ['var x = 5;', 'int x = 5;', 'x = 5;', 'declare int x = 5;'], 'correct' => 1],
        ['question' => 'Which operator is used for addition?', 'options' => ['+', 'add', 'plus', '&'], 'correct' => 0],
        ['question' => 'How do you create a string literal?', 'options' => ['Using single quotes', 'Using double quotes', 'Using backticks', 'Using parentheses'], 'correct' => 1],
        ['question' => 'Which method returns the length of a string?', 'options' => ['length()', 'size()', 'len()', 'count()'], 'correct' => 0],
        ['question' => 'Which method returns the character at a specific index?', 'options' => ['getChar()', 'charAt()', 'char()', 'get()'], 'correct' => 1],
        ['question' => 'Which method extracts a substring?', 'options' => ['substr()', 'substring()', 'slice()', 'extract()'], 'correct' => 1],
        ['question' => 'Which method converts a string to uppercase?', 'options' => ['toUpper()', 'toUpperCase()', 'upper()', 'uppercase()'], 'correct' => 1],
        ['question' => 'Which method converts a string to lowercase?', 'options' => ['toLower()', 'toLowerCase()', 'lower()', 'lowercase()'], 'correct' => 1],
        ['question' => 'Which method finds the index of a substring?', 'options' => ['find()', 'indexOf()', 'search()', 'locate()'], 'correct' => 1],
        ['question' => 'Which method compares two strings for equality?', 'options' => ['compare()', 'equals()', '==', 'isEqual()'], 'correct' => 1],
        ['question' => 'Which method checks if a string contains a substring?', 'options' => ['has()', 'contains()', 'includes()', 'hasSubstring()'], 'correct' => 1],
        ['question' => 'What keyword starts an if statement?', 'options' => ['if', 'when', 'condition', 'check'], 'correct' => 0],
        ['question' => 'What keyword is used for else?', 'options' => ['else', 'otherwise', 'default', 'other'], 'correct' => 0],
        ['question' => 'What keyword starts a switch statement?', 'options' => ['switch', 'case', 'select', 'choose'], 'correct' => 0],
        ['question' => 'What keyword starts a for loop?', 'options' => ['loop', 'for', 'repeat', 'iterate'], 'correct' => 1],
        ['question' => 'What keyword starts a while loop?', 'options' => ['while', 'loop', 'repeat', 'until'], 'correct' => 0],
        ['question' => 'What keyword starts a do-while loop?', 'options' => ['do', 'while', 'repeat', 'loop'], 'correct' => 0],
        ['question' => 'How do you declare an array of integers?', 'options' => ['int[] arr;', 'array int arr;', 'int arr[];', 'Both int[] arr; and int arr[];'], 'correct' => 3],
        ['question' => 'What is widening casting?', 'options' => ['Casting to wider type', 'Automatic conversion to larger type', 'Making wider', 'Expanding type'], 'correct' => 1],
        ['question' => 'What is narrowing casting?', 'options' => ['Casting to narrower type', 'Manual conversion to smaller type', 'Making narrower', 'Reducing type'], 'correct' => 1],
        ['question' => 'Which class is used for console input?', 'options' => ['Input', 'Scanner', 'Console', 'Reader'], 'correct' => 1],
        ['question' => 'Which class contains mathematical functions?', 'options' => ['Math', 'Mathematics', 'Calc', 'Number'], 'correct' => 0],
        ['question' => 'Which Math method returns the absolute value?', 'options' => ['absolute()', 'abs()', 'absValue()', 'absolute()'], 'correct' => 1],
        ['question' => 'Which Math method returns the maximum of two numbers?', 'options' => ['maximum()', 'max()', 'larger()', 'biggest()'], 'correct' => 1],
        ['question' => 'Which Math method returns the square root?', 'options' => ['squareRoot()', 'sqrt()', 'root()', 'square()'], 'correct' => 1],
        ['question' => 'How do you write a single-line comment?', 'options' => ['# comment', '// comment', '/* comment */', '-- comment'], 'correct' => 1],
        ['question' => 'How do you write a multi-line comment?', 'options' => ['/* comment */', '// comment', '# comment', '<!-- comment -->'], 'correct' => 0],
        ['question' => 'What keyword declares a package?', 'options' => ['package', 'namespace', 'module', 'library'], 'correct' => 0],
        ['question' => 'What keyword imports classes?', 'options' => ['include', 'import', 'using', 'require'], 'correct' => 1],
        ['question' => 'What is the default access modifier?', 'options' => ['public', 'private', 'package-private (default)', 'protected'], 'correct' => 2],
    ]],
    ['label' => 'Beginner', 'questions' => [
        ['question' => 'What keyword defines a class?', 'options' => ['class', 'object', 'struct', 'type'], 'correct' => 0],
        ['question' => 'What is a constructor?', 'options' => ['A method', 'A special method to initialize objects', 'A class', 'A variable'], 'correct' => 1],
        ['question' => 'What is a default constructor?', 'options' => ['First constructor', 'No-argument constructor provided by compiler', 'Standard constructor', 'Basic constructor'], 'correct' => 1],
        ['question' => 'What is constructor overloading?', 'options' => ['Too many constructors', 'Multiple constructors with different parameters', 'Constructor duplication', 'Constructor error'], 'correct' => 1],
        ['question' => 'What does "this" refer to?', 'options' => ['The class', 'The current instance', 'The method', 'The package'], 'correct' => 1],
        ['question' => 'What does "static" mean for a field?', 'options' => ['Unchangeable', 'Belongs to class, not instance', 'Final', 'Private'], 'correct' => 1],
        ['question' => 'What does "static" mean for a method?', 'options' => ['Cannot change', 'Can be called without instance', 'Private method', 'Final method'], 'correct' => 1],
        ['question' => 'Can a static method access instance variables?', 'options' => ['Yes', 'No, only static variables', 'Sometimes', 'Only with this'], 'correct' => 1],
        ['question' => 'What is method overloading?', 'options' => ['Too many methods', 'Multiple methods with same name, different parameters', 'Method duplication', 'Method error'], 'correct' => 1],
        ['question' => 'What keyword is used for inheritance?', 'options' => ['inherits', 'extends', 'implements', 'derives'], 'correct' => 1],
        ['question' => 'What does "super" refer to?', 'options' => ['Superior class', 'Parent class', 'Super method', 'Main class'], 'correct' => 1],
        ['question' => 'What is method overriding?', 'options' => ['Changing method', 'Redefining parent class method in subclass', 'Method replacement', 'Method update'], 'correct' => 1],
        ['question' => 'What annotation marks method overriding?', 'options' => ['@Overridden', '@Override', '@Overwrite', '@Replace'], 'correct' => 1],
        ['question' => 'What does "final" mean for a class?', 'options' => ['Last class', 'Cannot be extended', 'Complete class', 'Finished class'], 'correct' => 1],
        ['question' => 'What does "final" mean for a method?', 'options' => ['Last method', 'Cannot be overridden', 'Complete method', 'Finished method'], 'correct' => 1],
        ['question' => 'What does "final" mean for a variable?', 'options' => ['Last variable', 'Cannot be reassigned (constant)', 'Final value', 'End variable'], 'correct' => 1],
        ['question' => 'What is an abstract class?', 'options' => ['Theoretical class', 'Class that cannot be instantiated', 'Incomplete class', 'Virtual class'], 'correct' => 1],
        ['question' => 'What keyword defines an interface?', 'options' => ['interface', 'contract', 'protocol', 'abstract'], 'correct' => 0],
        ['question' => 'What keyword implements an interface?', 'options' => ['extends', 'implements', 'uses', 'adopts'], 'correct' => 1],
        ['question' => 'What does "instanceof" check?', 'options' => ['Instance count', 'If object is instance of a class', 'Object type', 'Class membership'], 'correct' => 1],
        ['question' => 'What is String.format() used for?', 'options' => ['String formatting', 'Creating formatted strings', 'String conversion', 'Format validation'], 'correct' => 1],
        ['question' => 'What is the difference between StringBuilder and StringBuffer?', 'options' => ['No difference', 'StringBuilder is not thread-safe, StringBuffer is', 'StringBuilder is newer', 'StringBuilder is faster only'], 'correct' => 1],
        ['question' => 'When should you use StringBuilder over String concatenation?', 'options' => ['Always', 'When concatenating in loops', 'Never', 'For short strings'], 'correct' => 1],
        ['question' => 'What is ArrayList?', 'options' => ['Array list', 'Resizable array implementation', 'List of arrays', 'Array wrapper'], 'correct' => 1],
        ['question' => 'What is the advantage of ArrayList over arrays?', 'options' => ['Faster', 'Dynamic size', 'Less memory', 'Simpler syntax'], 'correct' => 1],
        ['question' => 'What is LinkedList?', 'options' => ['Linked array', 'Doubly-linked list implementation', 'Array with links', 'List connection'], 'correct' => 1],
        ['question' => 'What is HashMap?', 'options' => ['Hashed map', 'Hash table based key-value map', 'Map with hashing', 'Hash storage'], 'correct' => 1],
        ['question' => 'What is HashSet?', 'options' => ['Hashed set', 'Set implementation using hash table', 'Set with hashing', 'Hash collection'], 'correct' => 1],
        ['question' => 'What is an Iterator?', 'options' => ['Loop counter', 'Object for iterating over collections', 'Iteration tool', 'Loop helper'], 'correct' => 1],
        ['question' => 'What is the enhanced for loop syntax?', 'options' => ['for(int i=0...)', 'for(Type var : collection)', 'foreach(var in collection)', 'for each var'], 'correct' => 1],
        ['question' => 'What is a checked exception?', 'options' => ['Validated exception', 'Exception that must be caught or declared', 'Exception that is checked', 'Verified exception'], 'correct' => 1],
        ['question' => 'What is an unchecked exception?', 'options' => ['Unvalidated exception', 'Runtime exception that doesn\'t need declaration', 'Exception not checked', 'Optional exception'], 'correct' => 1],
        ['question' => 'What does "throws" do in a method signature?', 'options' => ['Throws exception', 'Declares possible exceptions', 'Creates exception', 'Handles exception'], 'correct' => 1],
        ['question' => 'What does "throw" do?', 'options' => ['Declares exception', 'Actually throws an exception', 'Creates exception', 'Catches exception'], 'correct' => 1],
        ['question' => 'What is Comparable interface used for?', 'options' => ['Comparing objects', 'Defining natural ordering', 'Object comparison', 'Equality checking'], 'correct' => 1],
        ['question' => 'What is Comparator interface used for?', 'options' => ['Comparing values', 'Defining custom ordering', 'Comparison logic', 'Sorting helper'], 'correct' => 1],
        ['question' => 'What is autoboxing?', 'options' => ['Automatic boxing', 'Automatic conversion from primitive to wrapper', 'Auto-packaging', 'Automatic wrapping'], 'correct' => 1],
        ['question' => 'What is unboxing?', 'options' => ['Removing box', 'Automatic conversion from wrapper to primitive', 'Unpacking', 'Unwrapping'], 'correct' => 1],
    ]],
    ['label' => 'Intermediate', 'questions' => [
        ['question' => 'What are generics?', 'options' => ['Generic code', 'Type parameters for classes/methods', 'General types', 'Common code'], 'correct' => 1],
        ['question' => 'What does <?> mean in generics?', 'options' => ['Unknown type', 'Unbounded wildcard (any type)', 'Optional type', 'Wildcard type'], 'correct' => 1],
        ['question' => 'What does <? extends T> mean?', 'options' => ['Extended type', 'Upper bounded wildcard (T or subtype)', 'Extension of T', 'Type extending T'], 'correct' => 1],
        ['question' => 'What does <? super T> mean?', 'options' => ['Superior type', 'Lower bounded wildcard (T or supertype)', 'Type above T', 'Super of T'], 'correct' => 1],
        ['question' => 'What is List in Collections?', 'options' => ['A list', 'Ordered collection interface', 'Array list', 'List class'], 'correct' => 1],
        ['question' => 'What is Set in Collections?', 'options' => ['A setter', 'Collection with no duplicates', 'Set class', 'Setting collection'], 'correct' => 1],
        ['question' => 'What is Map in Collections?', 'options' => ['Mapping', 'Key-value pair interface', 'Map class', 'Location map'], 'correct' => 1],
        ['question' => 'What is Queue in Collections?', 'options' => ['A line', 'FIFO collection interface', 'Queue class', 'Waiting list'], 'correct' => 1],
        ['question' => 'What is Deque in Collections?', 'options' => ['Double queue', 'Double-ended queue interface', 'Deck of cards', 'Special queue'], 'correct' => 1],
        ['question' => 'How do you sort with Comparator?', 'options' => ['sort(comparator)', 'Collections.sort(list, comparator)', 'list.sort(comparator)', 'Both Collections.sort() and list.sort()'], 'correct' => 3],
        ['question' => 'What is a lambda expression?', 'options' => ['Greek expression', 'Anonymous function syntax', 'Lambda function', 'Inline function'], 'correct' => 1],
        ['question' => 'What is the syntax for a lambda with one parameter?', 'options' => ['(x) -> x * 2', 'x -> x * 2', 'lambda x: x * 2', 'Both (x) -> x * 2 and x -> x * 2'], 'correct' => 3],
        ['question' => 'What is a functional interface?', 'options' => ['Function interface', 'Interface with exactly one abstract method', 'Functional programming interface', 'Lambda interface'], 'correct' => 1],
        ['question' => 'What is the Function interface?', 'options' => ['Function class', 'Represents function that accepts one argument and produces result', 'Function type', 'Functional interface'], 'correct' => 1],
        ['question' => 'What is the Consumer interface?', 'options' => ['Consumes data', 'Accepts one argument and returns no result', 'Consumer class', 'Data consumer'], 'correct' => 1],
        ['question' => 'What is the Supplier interface?', 'options' => ['Supplies data', 'Takes no arguments and returns a result', 'Supplier class', 'Data provider'], 'correct' => 1],
        ['question' => 'What is the Predicate interface?', 'options' => ['Prediction', 'Takes one argument and returns boolean', 'Predicate class', 'Boolean function'], 'correct' => 1],
        ['question' => 'What is Stream API?', 'options' => ['Streaming data', 'Functional-style operations on collections', 'Stream class', 'Data stream'], 'correct' => 1],
        ['question' => 'What does filter() do in Stream?', 'options' => ['Cleans data', 'Filters elements based on predicate', 'Removes items', 'Selects items'], 'correct' => 1],
        ['question' => 'What does map() do in Stream?', 'options' => ['Creates map', 'Transforms each element', 'Maps values', 'Converts stream'], 'correct' => 1],
        ['question' => 'What does reduce() do in Stream?', 'options' => ['Reduces size', 'Combines elements to single result', 'Minimizes stream', 'Aggregates values'], 'correct' => 1],
        ['question' => 'What does collect() do in Stream?', 'options' => ['Collects data', 'Accumulates elements into collection', 'Gathers stream', 'Saves results'], 'correct' => 1],
        ['question' => 'What does flatMap() do in Stream?', 'options' => ['Flattens map', 'Maps and flattens nested streams', 'Flat mapping', 'Converts to flat structure'], 'correct' => 1],
        ['question' => 'What is Optional class?', 'options' => ['Optional parameter', 'Container that may or may not contain a value', 'Optional value', 'Nullable wrapper'], 'correct' => 1],
        ['question' => 'What does Optional.of() do?', 'options' => ['Creates optional', 'Creates Optional with non-null value', 'Optional factory', 'Wraps value'], 'correct' => 1],
        ['question' => 'What does Optional.ofNullable() do?', 'options' => ['Null optional', 'Creates Optional that may contain null', 'Nullable optional', 'Allows null'], 'correct' => 1],
        ['question' => 'What are method references?', 'options' => ['Method pointers', 'Shorthand for lambdas calling existing methods', 'Method links', 'Function references'], 'correct' => 1],
        ['question' => 'What is the syntax for static method reference?', 'options' => ['Class.method', 'Class::method', 'Class->method', 'Class.method()'], 'correct' => 1],
        ['question' => 'Can interfaces have default methods?', 'options' => ['No', 'Yes, since Java 8', 'Only abstract methods', 'Only in special cases'], 'correct' => 1],
        ['question' => 'Can interfaces have static methods?', 'options' => ['No', 'Yes, since Java 8', 'Only abstract methods', 'Only instance methods'], 'correct' => 1],
        ['question' => 'What is an enum?', 'options' => ['Enumeration', 'Special class for constants', 'Number type', 'List of values'], 'correct' => 1],
        ['question' => 'Can enums have methods?', 'options' => ['No', 'Yes', 'Only static methods', 'Only constructors'], 'correct' => 1],
        ['question' => 'Can enums have fields?', 'options' => ['No', 'Yes', 'Only constants', 'Only static fields'], 'correct' => 1],
        ['question' => 'What are annotations?', 'options' => ['Notes', 'Metadata added to code', 'Comments', 'Documentation'], 'correct' => 1],
        ['question' => 'What is reflection?', 'options' => ['Code mirroring', 'Examining and modifying code at runtime', 'Code analysis', 'Self-examination'], 'correct' => 1],
        ['question' => 'What does Class.forName() do?', 'options' => ['Gets class', 'Loads class dynamically by name', 'Finds class', 'Class lookup'], 'correct' => 1],
        ['question' => 'What is try-with-resources?', 'options' => ['Try with variables', 'Auto-closing resources using try', 'Resource management', 'Try block with resources'], 'correct' => 1],
        ['question' => 'What is multi-catch?', 'options' => ['Multiple catches', 'Catching multiple exception types in one catch', 'Catch multiple times', 'Multi exception'], 'correct' => 1],
        ['question' => 'What is the difference between equals() and ==?', 'options' => ['No difference', 'equals() checks value equality, == checks reference equality', 'equals() is slower', 'equals() is for objects only'], 'correct' => 1],
        ['question' => 'Why override hashCode() when overriding equals()?', 'options' => ['Required by compiler', 'To maintain hashCode-equals contract for hash-based collections', 'For performance', 'For consistency'], 'correct' => 1],
    ]],
    ['label' => 'Advanced', 'questions' => [
        ['question' => 'What is the Java memory model?', 'options' => ['Memory layout', 'Specification of how threads interact through memory', 'Memory structure', 'Memory management'], 'correct' => 1],
        ['question' => 'What is the heap in Java?', 'options' => ['Stack area', 'Memory area for objects', 'Heap sort', 'Memory pile'], 'correct' => 1],
        ['question' => 'What is the young generation?', 'options' => ['New objects', 'Heap area for newly created objects', 'Young space', 'New generation'], 'correct' => 1],
        ['question' => 'What is the old generation?', 'options' => ['Old objects', 'Heap area for long-lived objects', 'Old space', 'Tenured generation'], 'correct' => 1],
        ['question' => 'What is Metaspace?', 'options' => ['Meta data', 'Native memory area for class metadata', 'Class space', 'Metadata storage'], 'correct' => 1],
        ['question' => 'What replaced PermGen in Java 8?', 'options' => ['Heap', 'Metaspace', 'Stack', 'Native area'], 'correct' => 1],
        ['question' => 'What is the Serial GC?', 'options' => ['Serial garbage', 'Single-threaded garbage collector', 'Sequential GC', 'Simple GC'], 'correct' => 1],
        ['question' => 'What is the Parallel GC?', 'options' => ['Parallel processing', 'Multi-threaded garbage collector for throughput', 'Concurrent GC', 'Fast GC'], 'correct' => 1],
        ['question' => 'What is the CMS garbage collector?', 'options' => ['Content Management System', 'Concurrent Mark Sweep (low latency GC)', 'Concurrent Memory System', 'Continuous Mark Sweep'], 'correct' => 1],
        ['question' => 'What is the G1 garbage collector?', 'options' => ['Generation 1', 'Garbage First (balanced throughput and latency)', 'Group 1', 'Good GC'], 'correct' => 1],
        ['question' => 'What is ZGC?', 'options' => ['Zero GC', 'Scalable low-latency garbage collector', 'Z generation GC', 'Fast GC'], 'correct' => 1],
        ['question' => 'What is Thread in Java?', 'options' => ['Thread of execution', 'Smallest unit of execution', 'Execution path', 'Process thread'], 'correct' => 1],
        ['question' => 'What is Runnable interface?', 'options' => ['Running interface', 'Interface for task executed by thread', 'Run interface', 'Execution interface'], 'correct' => 1],
        ['question' => 'What is Callable interface?', 'options' => ['Callable task', 'Task that returns result and can throw exception', 'Call interface', 'Function interface'], 'correct' => 1],
        ['question' => 'What is Future?', 'options' => ['Future time', 'Result of asynchronous computation', 'Future result', 'Async result'], 'correct' => 1],
        ['question' => 'What is ExecutorService?', 'options' => ['Execution service', 'Higher-level thread pool management', 'Service executor', 'Thread service'], 'correct' => 1],
        ['question' => 'What does synchronized do?', 'options' => ['Synchronizes time', 'Provides mutual exclusion for thread safety', 'Syncs threads', 'Coordinates threads'], 'correct' => 1],
        ['question' => 'What does volatile do?', 'options' => ['Makes variable unstable', 'Ensures visibility of changes across threads', 'Volatile memory', 'Thread-safe variable'], 'correct' => 1],
        ['question' => 'What is AtomicInteger?', 'options' => ['Atomic number', 'Thread-safe integer with atomic operations', 'Integer atom', 'Safe integer'], 'correct' => 1],
        ['question' => 'What is Lock interface?', 'options' => ['Locking interface', 'More flexible locking than synchronized', 'Lock object', 'Thread lock'], 'correct' => 1],
        ['question' => 'What is ReentrantLock?', 'options' => ['Reentrant locking', 'Lock that can be acquired multiple times by same thread', 'Recursive lock', 'Multiple lock'], 'correct' => 1],
        ['question' => 'What is ReadWriteLock?', 'options' => ['Read and write lock', 'Separate locks for reading and writing', 'Dual lock', 'RW lock'], 'correct' => 1],
        ['question' => 'What is CountDownLatch?', 'options' => ['Countdown timer', 'Synchronizer allowing threads to wait for operations', 'Latch counter', 'Thread barrier'], 'correct' => 1],
        ['question' => 'What is CyclicBarrier?', 'options' => ['Circular barrier', 'Reusable synchronization point for threads', 'Cycle barrier', 'Thread barrier'], 'correct' => 1],
        ['question' => 'What is Semaphore?', 'options' => ['Signal', 'Controls access to shared resource via permits', 'Semaphore pattern', 'Access controller'], 'correct' => 1],
        ['question' => 'What is ConcurrentHashMap?', 'options' => ['Concurrent map', 'Thread-safe HashMap with better concurrency', 'Parallel map', 'Safe HashMap'], 'correct' => 1],
        ['question' => 'What is CopyOnWriteArrayList?', 'options' => ['Copy list', 'Thread-safe list that copies on modification', 'Write-copy list', 'Safe ArrayList'], 'correct' => 1],
        ['question' => 'What is BlockingQueue?', 'options' => ['Blocking queue', 'Queue that blocks on empty/full conditions', 'Blocked queue', 'Thread queue'], 'correct' => 1],
        ['question' => 'What is the Builder pattern?', 'options' => ['Building pattern', 'Constructs complex objects step by step', 'Construction pattern', 'Object builder'], 'correct' => 1],
        ['question' => 'What is the Factory pattern?', 'options' => ['Factory method', 'Creates objects without specifying exact class', 'Object factory', 'Creation pattern'], 'correct' => 1],
        ['question' => 'What is the Singleton pattern?', 'options' => ['Single object', 'Ensures only one instance of class exists', 'One instance', 'Single pattern'], 'correct' => 1],
        ['question' => 'What is NIO?', 'options' => ['New Input Output', 'Non-blocking I/O with channels and buffers', 'Network I/O', 'New I/O'], 'correct' => 1],
        ['question' => 'What are Channels in NIO?', 'options' => ['Data channels', 'Connections to I/O sources', 'I/O channels', 'Communication channels'], 'correct' => 1],
        ['question' => 'What are Buffers in NIO?', 'options' => ['Data buffers', 'Containers for data during I/O', 'Memory buffers', 'I/O buffers'], 'correct' => 1],
        ['question' => 'What is the module system (Java 9+)?', 'options' => ['Module organization', 'Strong encapsulation with module-info.java', 'Package system', 'Code modules'], 'correct' => 1],
        ['question' => 'What is a record (Java 14+)?', 'options' => ['Data record', 'Immutable data carrier with concise syntax', 'Record class', 'Data class'], 'correct' => 1],
        ['question' => 'What is a sealed class (Java 17)?', 'options' => ['Closed class', 'Class that restricts which classes can extend it', 'Final class', 'Restricted class'], 'correct' => 1],
        ['question' => 'What is pattern matching for instanceof?', 'options' => ['Pattern check', 'instanceof with automatic casting', 'Match pattern', 'Type pattern'], 'correct' => 1],
        ['question' => 'What is var (Java 10+)?', 'options' => ['Variable', 'Local variable type inference', 'Variable type', 'Auto type'], 'correct' => 1],
    ]],
    ['label' => 'Expert', 'questions' => [
        ['question' => 'What is Java bytecode?', 'options' => ['Binary code', 'Platform-independent instruction set for JVM', 'Byte-sized code', 'Compiled Java'], 'correct' => 1],
        ['question' => 'What tool disassembles Java bytecode?', 'options' => ['javac', 'javap', 'java', 'jdb'], 'correct' => 1],
        ['question' => 'What is the class file format?', 'options' => ['Java source', 'Binary format containing bytecode and metadata', 'Class structure', 'Compiled format'], 'correct' => 1],
        ['question' => 'What is the constant pool?', 'options' => ['Constant values', 'Table of constants and references in class file', 'Pool of constants', 'Constant storage'], 'correct' => 1],
        ['question' => 'What is a method descriptor?', 'options' => ['Method description', 'String encoding parameter and return types', 'Method signature', 'Method metadata'], 'correct' => 1],
        ['question' => 'What is JIT compilation?', 'options' => ['Just In Time compilation', 'Runtime compilation of bytecode to native code', 'Quick compilation', 'Immediate compilation'], 'correct' => 1],
        ['question' => 'What is the C1 compiler?', 'options' => ['Client compiler', 'Client compiler for fast startup', 'Compiler 1', 'First compiler'], 'correct' => 1],
        ['question' => 'What is the C2 compiler?', 'options' => ['Server compiler', 'Server compiler for optimized code', 'Compiler 2', 'Second compiler'], 'correct' => 1],
        ['question' => 'What is tiered compilation?', 'options' => ['Layered compilation', 'Uses both C1 and C2 compilers', 'Multi-level compilation', 'Staged compilation'], 'correct' => 1],
        ['question' => 'What is the code cache?', 'options' => ['Cached code', 'Memory area storing compiled native code', 'Code storage', 'Compilation cache'], 'correct' => 1],
        ['question' => 'What is escape analysis?', 'options' => ['Escape detection', 'Determines if object escapes method scope', 'Object analysis', 'Scope analysis'], 'correct' => 1],
        ['question' => 'What is scalar replacement?', 'options' => ['Scalar replacement', 'Optimization that replaces object with scalar fields', 'Object optimization', 'Field replacement'], 'correct' => 1],
        ['question' => 'What is loop unrolling?', 'options' => ['Loop expansion', 'Optimization that expands loop iterations', 'Loop optimization', 'Unroll loops'], 'correct' => 1],
        ['question' => 'What is method inlining?', 'options' => ['Inline method', 'Replacing method call with method body', 'Method optimization', 'Call elimination'], 'correct' => 1],
        ['question' => 'What is the happens-before relationship?', 'options' => ['Execution order', 'Memory ordering guarantee in JMM', 'Sequence relationship', 'Order guarantee'], 'correct' => 1],
        ['question' => 'What is memory ordering?', 'options' => ['Memory sequence', 'Order in which memory operations are visible', 'Operation order', 'Memory sequence'], 'correct' => 1],
        ['question' => 'What is CPU cache coherence?', 'options' => ['Cache consistency', 'Consistency of cached data across CPU cores', 'Cache sync', 'Cache agreement'], 'correct' => 1],
        ['question' => 'What is false sharing?', 'options' => ['Fake sharing', 'Performance issue from cache line sharing', 'Share problem', 'Cache problem'], 'correct' => 1],
        ['question' => 'What is @Contended annotation?', 'options' => ['Contention marker', 'Prevents false sharing with padding', 'Padding annotation', 'Cache annotation'], 'correct' => 1],
        ['question' => 'What is the Bootstrap ClassLoader?', 'options' => ['Boot loader', 'Loads core Java classes', 'First loader', 'System loader'], 'correct' => 1],
        ['question' => 'What is the Extension ClassLoader?', 'options' => ['Extension loader', 'Loads extension classes from ext directory', 'Extra loader', 'Additional loader'], 'correct' => 1],
        ['question' => 'What is the Application ClassLoader?', 'options' => ['App loader', 'Loads application classes from classpath', 'Program loader', 'Main loader'], 'correct' => 1],
        ['question' => 'What is a custom ClassLoader?', 'options' => ['Custom loader', 'User-defined class loader', 'Special loader', 'Personalized loader'], 'correct' => 1],
        ['question' => 'What is the java.lang.instrument package?', 'options' => ['Instrument library', 'API for instrumenting Java programs', 'Tool package', 'Instrumentation API'], 'correct' => 1],
        ['question' => 'What is bytecode manipulation?', 'options' => ['Code manipulation', 'Modifying bytecode at runtime or compile time', 'Bytecode editing', 'Code transformation'], 'correct' => 1],
        ['question' => 'What is ASM library?', 'options' => ['Assembly library', 'Low-level bytecode manipulation library', 'ASM tool', 'Bytecode library'], 'correct' => 1],
        ['question' => 'What is Javassist?', 'options' => ['Java assistant', 'High-level bytecode manipulation library', 'Java tool', 'Bytecode helper'], 'correct' => 1],
        ['question' => 'What is ByteBuddy?', 'options' => ['Byte helper', 'Modern bytecode manipulation library', 'Buddy library', 'Bytecode tool'], 'correct' => 1],
        ['question' => 'What is JVMTI?', 'options' => ['JVM Tool Interface', 'Native interface for JVM monitoring and debugging', 'JVM Tools', 'Tool interface'], 'correct' => 1],
        ['question' => 'What is GraalVM?', 'options' => ['Graal virtual machine', 'High-performance JVM with polyglot support', 'Fast JVM', 'New JVM'], 'correct' => 1],
        ['question' => 'What is native image in GraalVM?', 'options' => ['Native code', 'Ahead-of-time compiled standalone executable', 'Image format', 'Native compilation'], 'correct' => 1],
        ['question' => 'What is Project Loom?', 'options' => ['Loom project', 'Adds virtual threads (lightweight threads)', 'Thread project', 'Concurrency project'], 'correct' => 1],
        ['question' => 'What are virtual threads?', 'options' => ['Virtual execution', 'Lightweight threads managed by JVM', 'Fake threads', 'Simulated threads'], 'correct' => 1],
        ['question' => 'What is Project Panama?', 'options' => ['Panama project', 'Improves connection between JVM and native code', 'Foreign project', 'Native project'], 'correct' => 1],
        ['question' => 'What is Project Valhalla?', 'options' => ['Valhalla project', 'Adds value types and specialized generics', 'Value project', 'Type project'], 'correct' => 1],
        ['question' => 'What is Java Flight Recorder (JFR)?', 'options' => ['Flight recorder', 'Low-overhead profiling and diagnostics tool', 'Recording tool', 'Profiler'], 'correct' => 1],
        ['question' => 'What is JMX?', 'options' => ['Java Management Extensions', 'Framework for monitoring and managing applications', 'Management tool', 'Java monitor'], 'correct' => 1],
        ['question' => 'What is a heap dump?', 'options' => ['Heap snapshot', 'Snapshot of heap memory for analysis', 'Memory dump', 'Heap data'], 'correct' => 1],
        ['question' => 'What tool analyzes heap dumps?', 'options' => ['javap', 'jhat, Eclipse MAT, VisualVM', 'jdb', 'jconsole'], 'correct' => 1],
        ['question' => 'What is VisualVM?', 'options' => ['Visual tool', 'Monitoring, troubleshooting, and profiling tool', 'VM viewer', 'Visual profiler'], 'correct' => 1],
    ]],
];
require_once __DIR__ . '/quiz-engine.php';
