<?php
$page_title  = 'JavaScript Fundamentals Quiz – 100 Levels – CodeFoundry';
$active_page = 'training';
$quiz_title  = 'JavaScript Fundamentals';
$quiz_slug   = 'javascript-fundamentals';
$quiz_tiers  = [
    ['label' => 'Introduction', 'questions' => [
        ['question' => 'What does JavaScript primarily run in?', 'options' => ['Databases', 'Web browsers', 'Desktop apps only', 'Compilers'], 'correct' => 1],
        ['question' => 'Which keyword declares a variable in modern JavaScript?', 'options' => ['var', 'let', 'const', 'Both let and const'], 'correct' => 3],
        ['question' => 'What does const prevent?', 'options' => ['Changing object properties', 'Reassigning the variable binding', 'Calling methods', 'Reading the value'], 'correct' => 1],
        ['question' => 'Which data type represents text?', 'options' => ['number', 'boolean', 'string', 'char'], 'correct' => 2],
        ['question' => 'What is the result of typeof 42?', 'options' => ['"int"', '"number"', '"integer"', '"float"'], 'correct' => 1],
        ['question' => 'What does console.log() do?', 'options' => ['Creates a log file', 'Outputs to browser console', 'Logs users in', 'Clears the screen'], 'correct' => 1],
        ['question' => 'Which operator checks value AND type equality?', 'options' => ['==', '=', '===', '!=='], 'correct' => 2],
        ['question' => 'What is the result of 5 + "3"?', 'options' => ['8', '"53"', 'Error', '15'], 'correct' => 1],
        ['question' => 'What keyword creates a function declaration?', 'options' => ['def', 'func', 'function', 'fn'], 'correct' => 2],
        ['question' => 'How do you write a single-line comment in JavaScript?', 'options' => ['# comment', '-- comment', '// comment', '/* comment */'], 'correct' => 2],
        ['question' => 'What is undefined in JavaScript?', 'options' => ['A variable set to zero', 'A variable declared but not assigned a value', 'An error type', 'The string "undefined"'], 'correct' => 1],
        ['question' => 'How do you create an array?', 'options' => ['{}', '[]', '()', '<>'], 'correct' => 1],
        ['question' => 'How do you access the first element of array arr?', 'options' => ['arr[0]', 'arr[1]', 'arr.first()', 'arr.get(0)'], 'correct' => 0],
        ['question' => 'What is the length property of an array?', 'options' => ['The last index', 'The number of elements', 'The max value', 'A method'], 'correct' => 1],
        ['question' => 'Which method adds an element to the END of an array?', 'options' => ['unshift()', 'shift()', 'push()', 'pop()'], 'correct' => 2],
        ['question' => 'Which method removes the LAST element of an array?', 'options' => ['push()', 'shift()', 'pop()', 'splice()'], 'correct' => 2],
        ['question' => 'How do you create an object literal?', 'options' => ['[]', 'new Object[]', '{}', 'Object()'], 'correct' => 2],
        ['question' => 'How do you access property "name" of object obj?', 'options' => ['obj->name', 'obj::name', 'obj.name', 'obj[name]'], 'correct' => 2],
        ['question' => 'What does NaN stand for?', 'options' => ['Not a Name', 'Not a Number', 'New and Null', 'Null and Null'], 'correct' => 1],
        ['question' => 'What does the ! operator do to a boolean?', 'options' => ['Doubles it', 'Negates it', 'Increments it', 'Converts to string'], 'correct' => 1],
        ['question' => 'What is the result of Boolean("")?', 'options' => ['true', 'null', 'undefined', 'false'], 'correct' => 3],
        ['question' => 'What is the result of Boolean(0)?', 'options' => ['true', 'false', 'null', '0'], 'correct' => 1],
        ['question' => 'Which loop runs while a condition is true?', 'options' => ['for', 'while', 'do...while', 'Both while and do...while'], 'correct' => 3],
        ['question' => 'What does break do in a loop?', 'options' => ['Pauses execution', 'Skips to next iteration', 'Exits the loop', 'Restarts the loop'], 'correct' => 2],
        ['question' => 'What does continue do in a loop?', 'options' => ['Exits the loop', 'Skips to the next iteration', 'Pauses the loop', 'Restarts from beginning'], 'correct' => 1],
        ['question' => 'What does parseInt("10px") return?', 'options' => ['NaN', '"10px"', '10', 'Error'], 'correct' => 2],
        ['question' => 'Which method converts a number to a string?', 'options' => ['String()', 'parseInt()', 'Number()', 'parseFloat()'], 'correct' => 0],
        ['question' => 'What is the ternary operator syntax?', 'options' => ['condition ? a : b', 'condition ! a : b', 'a if condition else b', 'a unless condition'], 'correct' => 0],
        ['question' => 'What does typeof null return?', 'options' => ['"null"', '"undefined"', '"object"', '"boolean"'], 'correct' => 2],
        ['question' => 'What does the && operator return?', 'options' => ['Always true or false', 'The last truthy value or first falsy value', 'Only booleans', 'The left operand only'], 'correct' => 1],
    ]],
    ['label' => 'Beginner', 'questions' => [
        ['question' => 'What is a function expression?', 'options' => ['A function declared with function keyword', 'A function assigned to a variable', 'A built-in function', 'A named function'], 'correct' => 1],
        ['question' => 'What is an arrow function?', 'options' => ['A function created with function keyword', 'A shorthand function syntax using =>', 'A recursive function', 'A generator function'], 'correct' => 1],
        ['question' => 'What is a default parameter?', 'options' => ['A required parameter', 'A parameter with a fallback value', 'The first parameter', 'A read-only parameter'], 'correct' => 1],
        ['question' => 'What does the rest parameter (...args) collect?', 'options' => ['Named keyword arguments', 'Remaining positional arguments into an array', 'Default arguments', 'First argument only'], 'correct' => 1],
        ['question' => 'What does the spread operator (...) do to an array?', 'options' => ['Copies it by reference', 'Expands its elements in place', 'Sorts it', 'Reverses it'], 'correct' => 1],
        ['question' => 'What is destructuring assignment?', 'options' => ['Deleting properties', 'Extracting values from objects/arrays into variables', 'Copying an object', 'Merging two objects'], 'correct' => 1],
        ['question' => 'What is template literal syntax?', 'options' => ['Using single quotes', '"string ${var}"', '`string ${var}`', 'String(var)'], 'correct' => 2],
        ['question' => 'What does Array.map() return?', 'options' => ['The original array', 'A new array with transformed elements', 'The first matching element', 'A boolean'], 'correct' => 1],
        ['question' => 'What does Array.filter() return?', 'options' => ['The first matching element', 'A new array with elements that pass the test', 'true or false', 'The array mutated in place'], 'correct' => 1],
        ['question' => 'What does Array.reduce() do?', 'options' => ['Removes elements', 'Accumulates values into a single result', 'Finds minimum value', 'Flattens nested arrays'], 'correct' => 1],
        ['question' => 'What does Array.find() return?', 'options' => ['All matching elements', 'The index of the match', 'The first matching element', 'true or false'], 'correct' => 2],
        ['question' => 'What does Array.some() return?', 'options' => ['A subset array', 'The first truthy element', 'true if at least one element passes the test', 'The count of matches'], 'correct' => 2],
        ['question' => 'What does Array.every() return?', 'options' => ['Each element one by one', 'true if ALL elements pass the test', 'The count of elements', 'A filtered array'], 'correct' => 1],
        ['question' => 'What does String.includes() return?', 'options' => ['The position of the substring', 'The substring itself', 'true or false', 'An array of matches'], 'correct' => 2],
        ['question' => 'What does String.split() return?', 'options' => ['The string reversed', 'An array of substrings', 'The first part only', 'A number'], 'correct' => 1],
        ['question' => 'What is the difference between == and ===?', 'options' => ['No difference', '== checks only value with type coercion; === checks both value and type', '=== is faster only', '== is stricter'], 'correct' => 1],
        ['question' => 'What does short-circuit evaluation mean?', 'options' => ['Faster code execution', 'The second operand is not evaluated if the first determines the result', 'A syntax shortcut', 'Loop optimization'], 'correct' => 1],
        ['question' => 'What does Object.keys() return?', 'options' => ['The object values', 'An array of the object\'s own property names', 'The prototype chain', 'The object itself'], 'correct' => 1],
        ['question' => 'What does Object.values() return?', 'options' => ['An array of property names', 'An array of the object\'s own values', 'A Map', 'The object stringified'], 'correct' => 1],
        ['question' => 'What does Object.entries() return?', 'options' => ['Property names only', 'Values only', 'An array of [key, value] pairs', 'A new object'], 'correct' => 2],
        ['question' => 'What is the difference between null and undefined?', 'options' => ['They are identical', 'null is intentional absence of value; undefined means not yet assigned', 'undefined is always an error', 'null is a number'], 'correct' => 1],
        ['question' => 'What does typeof function(){}  return?', 'options' => ['"object"', '"function"', '"callable"', '"method"'], 'correct' => 1],
        ['question' => 'What does the in operator check?', 'options' => ['If a value is inside an array', 'If a property exists in an object', 'If a module is loaded', 'If a string contains a character'], 'correct' => 1],
        ['question' => 'What does Array.indexOf() return when not found?', 'options' => ['0', 'null', 'undefined', '-1'], 'correct' => 3],
        ['question' => 'What does the for...of loop iterate over?', 'options' => ['Object properties', 'Iterable values (arrays, strings, etc.)', 'Prototype chain', 'Object keys only'], 'correct' => 1],
        ['question' => 'What does the for...in loop iterate over?', 'options' => ['Array elements', 'Enumerable property keys of an object', 'Iterable values', 'Array indices only'], 'correct' => 1],
        ['question' => 'What does Object.assign() do?', 'options' => ['Creates a deep clone', 'Copies enumerable own properties from source to target', 'Freezes an object', 'Compares two objects'], 'correct' => 1],
        ['question' => 'What is a truthy value?', 'options' => ['A value that equals true', 'Any value that coerces to true in a boolean context', 'Only the boolean true', 'Numbers greater than zero only'], 'correct' => 1],
        ['question' => 'Which of these is a falsy value?', 'options' => ['[]', '{}', '0', '"false"'], 'correct' => 2],
        ['question' => 'What does the nullish coalescing operator (??) return?', 'options' => ['The left side if truthy', 'The right side if left is null or undefined', 'Always the right side', 'null if either side is falsy'], 'correct' => 1],
    ]],
    ['label' => 'Intermediate', 'questions' => [
        ['question' => 'What is a closure in JavaScript?', 'options' => ['A sealed object', 'A function that retains access to its outer scope variables', 'A locked module', 'A self-invoking function'], 'correct' => 1],
        ['question' => 'What does hoisting mean?', 'options' => ['Variables are removed', 'Declarations are moved to the top of their scope before execution', 'Functions are inlined', 'Code is minified'], 'correct' => 1],
        ['question' => 'Are let and const hoisted?', 'options' => ['No, they are never hoisted', 'Yes, but they are not initialized until their declaration (temporal dead zone)', 'Yes, and they are initialized to undefined', 'Only let is hoisted'], 'correct' => 1],
        ['question' => 'What is the prototype chain?', 'options' => ['A chain of imports', 'The mechanism by which objects inherit properties from other objects', 'A debugging technique', 'A list of class hierarchies'], 'correct' => 1],
        ['question' => 'What does the this keyword refer to in a regular function?', 'options' => ['Always the global object', 'The object that called the function', 'The function itself', 'undefined always'], 'correct' => 1],
        ['question' => 'What does this refer to in an arrow function?', 'options' => ['The calling object', 'The arrow function itself', 'The enclosing lexical this', 'undefined'], 'correct' => 2],
        ['question' => 'What is an IIFE?', 'options' => ['A type of import', 'An Immediately Invoked Function Expression', 'An infinite loop', 'An inline if expression'], 'correct' => 1],
        ['question' => 'What does call() do?', 'options' => ['Defines a function', 'Invokes a function with a specified this value and individual arguments', 'Returns a new function', 'Binds arguments only'], 'correct' => 1],
        ['question' => 'What does apply() differ from call() in?', 'options' => ['apply() does not set this', 'apply() takes arguments as an array instead of individually', 'apply() returns a new function', 'They are identical'], 'correct' => 1],
        ['question' => 'What does bind() return?', 'options' => ['The result of calling the function', 'A new function with a fixed this and optionally fixed arguments', 'A Promise', 'The original function'], 'correct' => 1],
        ['question' => 'What is a Promise?', 'options' => ['A data structure', 'An object representing the eventual completion or failure of an async operation', 'A type of callback', 'A synchronous wrapper'], 'correct' => 1],
        ['question' => 'What are the three states of a Promise?', 'options' => ['start, running, done', 'pending, fulfilled, rejected', 'open, processing, closed', 'init, exec, end'], 'correct' => 1],
        ['question' => 'What does Promise.then() receive?', 'options' => ['A rejection handler', 'A fulfillment handler', 'An error object', 'A new Promise'], 'correct' => 1],
        ['question' => 'What does Promise.catch() handle?', 'options' => ['Fulfilled promises', 'Rejected promises', 'Pending promises', 'All promise states'], 'correct' => 1],
        ['question' => 'What does async/await do?', 'options' => ['Adds multithreading', 'Makes asynchronous code look and behave like synchronous code', 'Speeds up Promises', 'Replaces callbacks entirely'], 'correct' => 1],
        ['question' => 'What does the await keyword do?', 'options' => ['Creates a Promise', 'Pauses function execution until a Promise settles', 'Rejects a Promise', 'Runs code in parallel'], 'correct' => 1],
        ['question' => 'What is event delegation?', 'options' => ['Removing event listeners', 'Attaching a single listener to a parent to handle events from children', 'Delegating tasks to workers', 'A pattern for emitting events'], 'correct' => 1],
        ['question' => 'What is the event bubbling phase?', 'options' => ['Events travel from child to parent', 'Events travel from parent to child', 'Events are cancelled', 'Events are queued'], 'correct' => 0],
        ['question' => 'What does event.stopPropagation() do?', 'options' => ['Prevents the default browser action', 'Stops the event from bubbling or capturing further', 'Removes the event listener', 'Cancels the event permanently'], 'correct' => 1],
        ['question' => 'What does event.preventDefault() do?', 'options' => ['Stops propagation', 'Prevents the default browser behavior for the event', 'Removes event listeners', 'Clones the event'], 'correct' => 1],
        ['question' => 'What is a WeakMap?', 'options' => ['A normal Map with fewer features', 'A Map where keys are weakly referenced objects', 'A read-only Map', 'A sorted Map'], 'correct' => 1],
        ['question' => 'What is a Set in JavaScript?', 'options' => ['An object with only methods', 'A collection of unique values', 'A sorted array', 'A key-value store'], 'correct' => 1],
        ['question' => 'What is the difference between Map and Object?', 'options' => ['They are identical', 'Map preserves insertion order, has any key type, and has size property', 'Object is faster always', 'Map only stores strings'], 'correct' => 1],
        ['question' => 'What does Symbol() create?', 'options' => ['A string identifier', 'A unique, immutable primitive value', 'A numeric ID', 'A new object'], 'correct' => 1],
        ['question' => 'What is optional chaining (?.)?', 'options' => ['A conditional import syntax', 'Safe property access that returns undefined instead of throwing on null/undefined', 'A fallback value operator', 'A try-catch shorthand'], 'correct' => 1],
        ['question' => 'What does Array.flat() do?', 'options' => ['Sorts the array', 'Creates a new array with sub-arrays flattened', 'Removes duplicates', 'Converts to a string'], 'correct' => 1],
        ['question' => 'What does Array.flatMap() do?', 'options' => ['Flattens only', 'Maps then flattens one level', 'Flattens all levels deeply', 'Maps without creating a new array'], 'correct' => 1],
        ['question' => 'What does Promise.all() do?', 'options' => ['Runs promises sequentially', 'Resolves when all promises resolve, rejects if any rejects', 'Returns the first resolved promise', 'Ignores rejections'], 'correct' => 1],
        ['question' => 'What does Promise.race() do?', 'options' => ['Resolves with all results', 'Resolves or rejects with the first settled promise', 'Always rejects', 'Runs promises one by one'], 'correct' => 1],
        ['question' => 'What is a generator function (function*)?', 'options' => ['A function that generates objects', 'A function that can pause and resume execution using yield', 'A self-calling function', 'A pure function'], 'correct' => 1],
    ]],
    ['label' => 'Advanced', 'questions' => [
        ['question' => 'What is the JavaScript event loop?', 'options' => ['A looping construct', 'The mechanism that processes call stack and callback queue for async operations', 'An error-handling loop', 'A recursive function pattern'], 'correct' => 1],
        ['question' => 'What is the call stack?', 'options' => ['A list of function calls waiting to execute', 'A LIFO structure tracking currently executing function calls', 'An array of callbacks', 'A thread pool'], 'correct' => 1],
        ['question' => 'What is the microtask queue?', 'options' => ['A queue for setTimeout callbacks', 'A high-priority queue for Promise callbacks, processed before the macrotask queue', 'A thread for micro-optimizations', 'A system-level queue'], 'correct' => 1],
        ['question' => 'What does Object.freeze() do?', 'options' => ['Creates a deep immutable copy', 'Prevents adding, removing, or modifying properties (shallow)', 'Converts to a const', 'Locks the prototype'], 'correct' => 1],
        ['question' => 'What is memoization?', 'options' => ['Memorizing code', 'Caching function results for the same inputs to avoid recomputation', 'A memory-management technique', 'Storing state in localStorage'], 'correct' => 1],
        ['question' => 'What is currying?', 'options' => ['Combining two functions', 'Transforming a function that takes multiple arguments into a series of unary functions', 'Adding spice to code', 'Recursive function calling'], 'correct' => 1],
        ['question' => 'What is function composition?', 'options' => ['Writing a complex function', 'Combining functions so the output of one is the input of the next', 'Extending a class', 'Merging modules'], 'correct' => 1],
        ['question' => 'What is the Proxy object?', 'options' => ['A network proxy', 'An object that intercepts and customizes fundamental operations on another object', 'A frozen object', 'A class decorator'], 'correct' => 1],
        ['question' => 'What is Reflect in JavaScript?', 'options' => ['Mirroring a variable', 'A built-in object providing methods for interceptable operations (mirrors Proxy traps)', 'A DOM API', 'An async utility'], 'correct' => 1],
        ['question' => 'What does Object.create() do?', 'options' => ['Clones an object deeply', 'Creates a new object with the specified prototype', 'Freezes an object', 'Compares two objects'], 'correct' => 1],
        ['question' => 'What is the difference between Object.create(null) and {}?', 'options' => ['No difference', 'Object.create(null) has no prototype chain; {} inherits from Object.prototype', 'Object.create(null) is faster always', '{} creates an empty array'], 'correct' => 1],
        ['question' => 'What is a WeakRef?', 'options' => ['A reference that prevents garbage collection', 'A weak reference that allows the object to be garbage collected', 'A read-only reference', 'A cached reference'], 'correct' => 1],
        ['question' => 'What does FinalizationRegistry do?', 'options' => ['Finalizes a build', 'Registers a callback to run when a weakly-referenced object is garbage collected', 'Closes database connections', 'Prevents memory leaks'], 'correct' => 1],
        ['question' => 'What is tail call optimization?', 'options' => ['Optimizing the last line of code', 'A JS engine optimization reusing the current stack frame when the last action is a function call', 'A compiler trick', 'A loop unrolling technique'], 'correct' => 1],
        ['question' => 'What is the difference between shallow copy and deep copy?', 'options' => ['No difference', 'Shallow copy copies top-level properties by reference; deep copy recursively clones all nested objects', 'Deep copy is always slower', 'Shallow copy only works on arrays'], 'correct' => 1],
        ['question' => 'What is structuredClone()?', 'options' => ['Copies object structure schema', 'A built-in method for deep cloning objects', 'Clones the prototype', 'A polyfill for JSON.parse'], 'correct' => 1],
        ['question' => 'What does the instanceof operator check?', 'options' => ['If a value is a specific primitive type', 'If an object has a constructor in its prototype chain', 'If a module is loaded', 'If a variable is defined'], 'correct' => 1],
        ['question' => 'What is the temporal dead zone (TDZ)?', 'options' => ['A time-based caching strategy', 'The period between let/const hoisting and their actual declaration where access throws ReferenceError', 'A deprecated JS feature', 'A timeout handler'], 'correct' => 1],
        ['question' => 'What is a tagged template literal?', 'options' => ['A template with HTML tags', 'A template literal processed by a function that receives template parts and values', 'A styled-components feature', 'A multi-line string only'], 'correct' => 1],
        ['question' => 'What is the purpose of Symbol.iterator?', 'options' => ['To name symbols', 'To define a custom iteration protocol for an object', 'To iterate over symbol properties', 'To create unique IDs'], 'correct' => 1],
        ['question' => 'What does yield* do inside a generator?', 'options' => ['Returns multiple values at once', 'Delegates to another iterable or generator', 'Creates a nested generator', 'Terminates the generator'], 'correct' => 1],
        ['question' => 'What is lazy evaluation in JavaScript?', 'options' => ['Slow code execution', 'Deferring computation until the value is actually needed', 'Using setTimeout', 'Async evaluation'], 'correct' => 1],
        ['question' => 'What does Object.getOwnPropertyDescriptor() return?', 'options' => ['The property value', 'A descriptor object with value, writable, enumerable, configurable properties', 'The property name', 'The prototype property'], 'correct' => 1],
        ['question' => 'What is a pure function?', 'options' => ['A function with no parameters', 'A function with no side effects that always returns the same output for the same input', 'A function that returns void', 'A built-in function'], 'correct' => 1],
        ['question' => 'What is debouncing?', 'options' => ['Removing bugs', 'Limiting a function to execute only after a specified delay since its last call', 'A caching strategy', 'An event-handling technique only'], 'correct' => 1],
        ['question' => 'What is throttling?', 'options' => ['Slowing down loops', 'Ensuring a function executes at most once in a specified time period', 'A compression technique', 'A memory limit'], 'correct' => 1],
        ['question' => 'What are Atomics in JavaScript?', 'options' => ['Primitive value wrappers', 'Static methods for atomic operations on SharedArrayBuffer', 'Small JavaScript modules', 'A build tool API'], 'correct' => 1],
        ['question' => 'What is SharedArrayBuffer?', 'options' => ['A global shared variable', 'A fixed-length binary buffer that can be shared between multiple workers', 'A shared module cache', 'A cross-tab storage API'], 'correct' => 1],
        ['question' => 'What does Promise.allSettled() do?', 'options' => ['Rejects if any promise rejects', 'Resolves with results of all promises regardless of outcome', 'Only handles rejections', 'Runs promises in sequence'], 'correct' => 1],
        ['question' => 'What does Promise.any() do?', 'options' => ['Rejects if any promise rejects', 'Resolves with the first fulfilled promise, rejects only if all reject', 'Resolves when all settle', 'Returns all results'], 'correct' => 1],
    ]],
    ['label' => 'Expert', 'questions' => [
        ['question' => 'What is the V8 JIT compiler?', 'options' => ['A minification tool', 'A just-in-time compiler that compiles JavaScript to machine code for faster execution', 'A virtual CPU', 'An AOT compiler only'], 'correct' => 1],
        ['question' => 'What are hidden classes in V8?', 'options' => ['Private class fields', 'Internal representations V8 uses to optimize property access on objects with the same shape', 'A CSS concept', 'Prototype chains'], 'correct' => 1],
        ['question' => 'What is inline caching in JavaScript engines?', 'options' => ['Storing HTML in memory', 'An optimization that caches the result of property lookups at a specific call site', 'HTTP caching headers', 'A module bundling strategy'], 'correct' => 1],
        ['question' => 'What is the difference between macrotasks and microtasks?', 'options' => ['Size of the task', 'Microtasks (Promises, queueMicrotask) run after the current task before the next macrotask (setTimeout, I/O)', 'Macrotasks are synchronous', 'They are identical'], 'correct' => 1],
        ['question' => 'What is the module pattern?', 'options' => ['A Node.js feature only', 'An IIFE-based pattern for encapsulation that exposes a public API while hiding internals', 'A class pattern', 'A build tool pattern'], 'correct' => 1],
        ['question' => 'What is tree shaking?', 'options' => ['Removing DOM nodes', 'Dead code elimination during bundling by removing exports that are never imported', 'Clearing event listeners', 'An optimization for trees/graphs'], 'correct' => 1],
        ['question' => 'What is code splitting?', 'options' => ['Refactoring long files', 'Breaking a bundle into smaller chunks loaded on demand to improve performance', 'Splitting a string into tokens', 'Running code in parallel'], 'correct' => 1],
        ['question' => 'What is a Service Worker?', 'options' => ['A background thread for heavy computation', 'A script that runs separately from the page to intercept requests and enable offline capabilities', 'A server-side JavaScript process', 'A DOM worker'], 'correct' => 1],
        ['question' => 'What is the Transferable Objects mechanism?', 'options' => ['Moving objects between modules', 'Transferring ownership of ArrayBuffers between workers without copying', 'Cloning objects across iframes', 'Serializing objects for storage'], 'correct' => 1],
        ['question' => 'What is the Temporal proposal in JavaScript?', 'options' => ['A temporary variable scope', 'A modern API for working with dates and times to replace the Date object', 'A time-travel debugging tool', 'A timer utility'], 'correct' => 1],
        ['question' => 'What is the purpose of Object.defineProperty()?', 'options' => ['Adds a method to a class', 'Defines a property with configurable descriptors (writable, enumerable, configurable, get, set)', 'Freezes a property', 'Copies a property'], 'correct' => 1],
        ['question' => 'What is the Observable pattern vs Promise?', 'options' => ['They are identical', 'Observables are lazy, cancellable, and can emit multiple values over time; Promises are eager and single-value', 'Promises can emit multiple values', 'Observables are only for HTTP'], 'correct' => 1],
        ['question' => 'What is the Abstract Syntax Tree (AST) in JS tooling?', 'options' => ['A UI rendering tree', 'A tree representation of the syntactic structure of source code, used by parsers and compilers', 'The virtual DOM', 'A module dependency graph'], 'correct' => 1],
        ['question' => 'What does the logical assignment operator ||= do?', 'options' => ['Always assigns', 'Assigns the right side only if the left side is falsy', 'Merges two values', 'Checks strict equality'], 'correct' => 1],
        ['question' => 'What is Array.fromAsync()?', 'options' => ['Creates an array from an async function', 'Creates an array from an async iterable or array-like', 'Wraps an array in a Promise', 'Fetches data into an array'], 'correct' => 1],
        ['question' => 'What does the using declaration (explicit resource management proposal) do?', 'options' => ['Imports a module', 'Ensures a resource\'s Symbol.dispose method is called when leaving the block scope', 'Declares a constant', 'Pins a variable to a specific scope'], 'correct' => 1],
        ['question' => 'What is speculative optimization in JS engines?', 'options' => ['Guessing variable names', 'Compiling code with assumptions about types; deoptimizing if assumptions fail', 'An experimental API', 'Predicting user input'], 'correct' => 1],
        ['question' => 'What is the purpose of performance.mark() and performance.measure()?', 'options' => ['CSS animation marks', 'Creating high-resolution timing markers for custom performance measurements', 'Marking code as optimized', 'Setting memory limits'], 'correct' => 1],
        ['question' => 'What is the purpose of queueMicrotask()?', 'options' => ['Queues a macrotask', 'Schedules a callback as a microtask to run after current synchronous code but before the next macrotask', 'Creates a worker thread', 'Delays execution by one frame'], 'correct' => 1],
        ['question' => 'What is the Record and Tuple proposal?', 'options' => ['A TypeScript feature', 'Immutable, deeply-comparable value types for objects and arrays', 'A new loop construct', 'A type annotation syntax'], 'correct' => 1],
        ['question' => 'What is the purpose of globalThis?', 'options' => ['Accesses the global object uniformly across environments (browser, Node.js, workers)', 'Sets global variables', 'A replacement for window', 'A browser-only API'], 'correct' => 0],
        ['question' => 'What is the Garbage Collector\'s generational hypothesis?', 'options' => ['Old objects live longer', 'Most objects die young, so short-lived allocations are collected cheaply in the young generation', 'Memory grows generationally', 'GC runs once per generation'], 'correct' => 1],
        ['question' => 'What is monomorphic vs polymorphic call site in V8?', 'options' => ['One function vs many functions', 'A monomorphic site always sees the same hidden class, enabling better optimization; polymorphic sees multiple', 'A method count difference', 'A class inheritance level'], 'correct' => 1],
        ['question' => 'What is the Error.cause property?', 'options' => ['A deprecated property', 'A way to chain errors by specifying the underlying cause when throwing a new Error', 'The error stack trace', 'A type field for errors'], 'correct' => 1],
        ['question' => 'What is top-level await?', 'options' => ['await used only in top-level functions', 'Using await outside an async function at the top level of an ES module', 'A performance optimization', 'A Node.js-only feature'], 'correct' => 1],
        ['question' => 'What is the purpose of import.meta?', 'options' => ['Imports metadata from npm', 'Provides host-specific metadata about the current module (e.g., import.meta.url)', 'A build tool configuration', 'An import assertion syntax'], 'correct' => 1],
        ['question' => 'What does import() (dynamic import) return?', 'options' => ['The module object directly', 'A Promise that resolves with the module namespace object', 'A string path', 'A synchronous module'], 'correct' => 1],
        ['question' => 'What is the purpose of the Intl API?', 'options' => ['International networking', 'ECMAScript Internationalization API for locale-sensitive string comparison, number formatting, date formatting', 'An integer library', 'A translation service'], 'correct' => 1],
        ['question' => 'What is a Decorator in JavaScript (proposal)?', 'options' => ['A design pattern only', 'A special syntax for annotating or modifying class declarations, methods, and properties', 'A CSS concept', 'A function wrapper utility'], 'correct' => 1],
        ['question' => 'What is the purpose of Array.prototype.at()?', 'options' => ['Checks if index exists', 'Accesses an element by index, supporting negative indices to count from the end', 'Attaches a listener', 'Returns a reference'], 'correct' => 1],
    ]],
];
require_once __DIR__ . '/quiz-engine.php';
