<?php
$page_title = 'JavaScript Quiz – 100 Levels – CodeFoundry';
$active_page = 'training';
$quiz_title  = 'JavaScript';
$quiz_slug   = 'javascript';
$quiz_tiers  = [
    [
        'label' => 'Introduction',
        'questions' => [
            ['question' => 'What is JavaScript?', 'options' => ['A Java framework', 'A programming language for web', 'A database', 'A CSS preprocessor'], 'correct' => 1],
            ['question' => 'Which keyword declares a variable that cannot be reassigned?', 'options' => ['var', 'let', 'const', 'final'], 'correct' => 2],
            ['question' => 'Which keyword declares a block-scoped variable?', 'options' => ['var', 'let', 'const', 'Both let and const'], 'correct' => 3],
            ['question' => 'Which is NOT a JavaScript data type?', 'options' => ['string', 'number', 'boolean', 'character'], 'correct' => 3],
            ['question' => 'What does typeof null return?', 'options' => ['null', 'object', 'undefined', 'number'], 'correct' => 1],
            ['question' => 'What is the result of 5 + "5"?', 'options' => ['10', '55', '"55"', 'Error'], 'correct' => 2],
            ['question' => 'Which operator checks equality without type coercion?', 'options' => ['==', '===', '=', '!=='], 'correct' => 1],
            ['question' => 'What does console.log() do?', 'options' => ['Logs user in', 'Outputs to console', 'Creates log file', 'Logs errors'], 'correct' => 1],
            ['question' => 'How do you create a function?', 'options' => ['function myFunc() {}', 'def myFunc() {}', 'func myFunc() {}', 'create function myFunc() {}'], 'correct' => 0],
            ['question' => 'How do you create an array?', 'options' => ['array = ()', 'array = []', 'array = {}', 'array = new()'], 'correct' => 1],
            ['question' => 'How do you access the first element of array arr?', 'options' => ['arr[0]', 'arr[1]', 'arr.first()', 'arr(0)'], 'correct' => 0],
            ['question' => 'How do you create an object?', 'options' => ['obj = []', 'obj = ()', 'obj = {}', 'obj = new()'], 'correct' => 2],
            ['question' => 'How do you access property "name" of object obj?', 'options' => ['obj->name', 'obj.name', 'obj::name', 'obj[name]'], 'correct' => 1],
            ['question' => 'What does NaN stand for?', 'options' => ['Not a Name', 'Not a Number', 'Null and Null', 'New and Null'], 'correct' => 1],
            ['question' => 'What is the result of typeof undefined?', 'options' => ['undefined', '"undefined"', 'null', 'object'], 'correct' => 0],
            ['question' => 'Which method converts string to integer?', 'options' => ['parseInt()', 'toInt()', 'intParse()', 'convertInt()'], 'correct' => 0],
            ['question' => 'Which method converts string to float?', 'options' => ['parseFloat()', 'toFloat()', 'floatParse()', 'convertFloat()'], 'correct' => 0],
            ['question' => 'What does the length property return for strings?', 'options' => ['Number of words', 'Number of characters', 'Size in bytes', 'String value'], 'correct' => 1],
            ['question' => 'Which method converts string to uppercase?', 'options' => ['upper()', 'toUpper()', 'toUpperCase()', 'upperCase()'], 'correct' => 2],
            ['question' => 'Which method adds element to end of array?', 'options' => ['add()', 'push()', 'append()', 'insert()'], 'correct' => 1],
            ['question' => 'Which method removes last element from array?', 'options' => ['remove()', 'pop()', 'delete()', 'removeLast()'], 'correct' => 1],
            ['question' => 'What are template literals enclosed with?', 'options' => ['Single quotes', 'Double quotes', 'Backticks', 'Parentheses'], 'correct' => 2],
            ['question' => 'How do you write a single-line comment?', 'options' => ['/* comment */', '// comment', '&lt;!-- comment --&gt;', '# comment'], 'correct' => 1],
            ['question' => 'What does the if statement do?', 'options' => ['Loops code', 'Executes code conditionally', 'Defines function', 'Creates variable'], 'correct' => 1],
            ['question' => 'What is a for loop used for?', 'options' => ['Making decisions', 'Repeating code', 'Defining functions', 'Creating objects'], 'correct' => 1],
            ['question' => 'What does Math.round() do?', 'options' => ['Rounds down', 'Rounds to nearest integer', 'Rounds up', 'Returns random number'], 'correct' => 1],
            ['question' => 'What does alert() do?', 'options' => ['Creates alert variable', 'Displays alert dialog', 'Warns about errors', 'Alerts server'], 'correct' => 1],
            ['question' => 'What is the result of 10 % 3?', 'options' => ['3', '1', '0.3', '30'], 'correct' => 1],
        ]
    ],
    [
        'label' => 'Beginner',
        'questions' => [
            ['question' => 'What is an arrow function?', 'options' => ['A pointer', 'A shorter function syntax', 'A function that returns arrows', 'A deprecated function'], 'correct' => 1],
            ['question' => 'Which array method transforms each element?', 'options' => ['forEach()', 'map()', 'filter()', 'reduce()'], 'correct' => 1],
            ['question' => 'Which array method filters elements?', 'options' => ['map()', 'filter()', 'find()', 'select()'], 'correct' => 1],
            ['question' => 'Which array method reduces array to single value?', 'options' => ['map()', 'reduce()', 'sum()', 'combine()'], 'correct' => 1],
            ['question' => 'What does Object.keys() return?', 'options' => ['Object properties', 'Array of property names', 'Object values', 'Object entries'], 'correct' => 1],
            ['question' => 'What does Object.values() return?', 'options' => ['Property names', 'Array of property values', 'Object keys', 'Object entries'], 'correct' => 1],
            ['question' => 'What is destructuring?', 'options' => ['Destroying objects', 'Extracting values from arrays/objects', 'Deleting properties', 'Breaking code'], 'correct' => 1],
            ['question' => 'What does the spread operator ... do?', 'options' => ['Spreads butter', 'Expands iterable elements', 'Creates range', 'Ellipsis operator'], 'correct' => 1],
            ['question' => 'What is the rest parameter?', 'options' => ['Remaining code', 'Collects arguments into array', 'Rest function', 'Pauses execution'], 'correct' => 1],
            ['question' => 'What is optional chaining (?.) ?', 'options' => ['Optional property', 'Safe property access', 'Question mark operator', 'Chain operator'], 'correct' => 1],
            ['question' => 'What is nullish coalescing (??)?', 'options' => ['Null operator', 'Returns right side if left is null/undefined', 'Double question', 'Coalesce operator'], 'correct' => 1],
            ['question' => 'What is a ternary operator?', 'options' => ['Three operators', 'Conditional ? : operator', 'Ternary function', 'Three-way operator'], 'correct' => 1],
            ['question' => 'What is a closure?', 'options' => ['Closed function', 'Function with access to outer scope', 'Function closure', 'Closed scope'], 'correct' => 1],
            ['question' => 'What is an IIFE?', 'options' => ['If expression', 'Immediately Invoked Function Expression', 'Inline function', 'Immediate function'], 'correct' => 1],
            ['question' => 'What is a Promise?', 'options' => ['A guarantee', 'Object representing async operation result', 'Promise function', 'Async promise'], 'correct' => 1],
            ['question' => 'What does .then() do with Promises?', 'options' => ['Then statement', 'Handles fulfilled Promise', 'Next step', 'Then function'], 'correct' => 1],
            ['question' => 'What does .catch() do with Promises?', 'options' => ['Catches errors', 'Handles rejected Promise', 'Catch statement', 'Error catcher'], 'correct' => 1],
            ['question' => 'What is async/await?', 'options' => ['Async function', 'Syntax for handling Promises', 'Await operator', 'Asynchronous await'], 'correct' => 1],
            ['question' => 'What does fetch() do?', 'options' => ['Fetches data', 'Makes HTTP requests', 'Fetch function', 'Gets resources'], 'correct' => 1],
            ['question' => 'What does JSON.parse() do?', 'options' => ['Parses JSON', 'Converts JSON string to object', 'JSON parser', 'Parse function'], 'correct' => 1],
            ['question' => 'What does JSON.stringify() do?', 'options' => ['Stringifies JSON', 'Converts object to JSON string', 'String function', 'JSON string'], 'correct' => 1],
            ['question' => 'What is try/catch used for?', 'options' => ['Trying code', 'Error handling', 'Catching errors', 'Try statement'], 'correct' => 1],
            ['question' => 'What does setTimeout() do?', 'options' => ['Sets timeout', 'Executes code after delay', 'Timeout function', 'Delays execution'], 'correct' => 1],
            ['question' => 'What does getElementById() do?', 'options' => ['Gets ID', 'Selects element by ID', 'ID getter', 'Element by ID'], 'correct' => 1],
            ['question' => 'What is the class keyword for?', 'options' => ['CSS class', 'Defining classes (OOP)', 'Class name', 'Classification'], 'correct' => 1],
            ['question' => 'What is a constructor in a class?', 'options' => ['Class builder', 'Method that initializes instances', 'Constructor function', 'Class method'], 'correct' => 1],
            ['question' => 'What does extends do in classes?', 'options' => ['Extends length', 'Creates subclass', 'Extension', 'Extends class'], 'correct' => 1],
            ['question' => 'What is hoisting?', 'options' => ['Hosting code', 'Moving declarations to top of scope', 'Hoist function', 'Lifting variables'], 'correct' => 1],
        ]
    ],
    [
        'label' => 'Intermediate',
        'questions' => [
            ['question' => 'What is the event loop?', 'options' => ['Event handler', 'Mechanism handling async operations', 'Loop event', 'Event cycle'], 'correct' => 1],
            ['question' => 'What is a microtask?', 'options' => ['Small task', 'Promise callbacks, queued in microtask queue', 'Micro operation', 'Task micro'], 'correct' => 1],
            ['question' => 'What is a macrotask?', 'options' => ['Large task', 'setTimeout, setInterval, queued in task queue', 'Macro operation', 'Task macro'], 'correct' => 1],
            ['question' => 'What does Promise.all() do?', 'options' => ['All promises', 'Waits for all Promises to resolve', 'Promise array', 'All together'], 'correct' => 1],
            ['question' => 'What does Promise.race() do?', 'options' => ['Race promises', 'Resolves/rejects with first settled Promise', 'Promise race', 'Racing promises'], 'correct' => 1],
            ['question' => 'What is the prototype chain?', 'options' => ['Chain of prototypes', 'Inheritance mechanism through prototypes', 'Prototype link', 'Chain prototype'], 'correct' => 1],
            ['question' => 'What is a Symbol?', 'options' => ['Symbol character', 'Unique, immutable primitive value', 'Symbol type', 'Symbolic value'], 'correct' => 1],
            ['question' => 'What is a WeakMap?', 'options' => ['Weak mapping', 'Map with weak key references (GC-friendly)', 'Weak collection', 'Map weak'], 'correct' => 1],
            ['question' => 'What is a WeakSet?', 'options' => ['Weak setting', 'Set with weak value references (GC-friendly)', 'Weak collection', 'Set weak'], 'correct' => 1],
            ['question' => 'What is a generator function?', 'options' => ['Generator code', 'Function that can pause/resume (function*)', 'Generate function', 'Generator type'], 'correct' => 1],
            ['question' => 'What does yield do?', 'options' => ['Yields result', 'Pauses generator and returns value', 'Yield function', 'Generator yield'], 'correct' => 1],
            ['question' => 'What is a Proxy?', 'options' => ['Proxy server', 'Object to intercept and customize operations', 'Proxy pattern', 'Proxy object'], 'correct' => 1],
            ['question' => 'What is Reflect?', 'options' => ['Reflection API', 'Built-in object for interceptable operations', 'Reflect method', 'Reflection'], 'correct' => 1],
            ['question' => 'What is a Map?', 'options' => ['Mapping', 'Collection of keyed data items', 'Map function', 'Map type'], 'correct' => 1],
            ['question' => 'What is a Set?', 'options' => ['Setting', 'Collection of unique values', 'Set function', 'Set type'], 'correct' => 1],
            ['question' => 'What is the difference between for...of and for...in?', 'options' => ['No difference', 'for...of iterates values, for...in iterates keys', 'Different syntax', 'For loops'], 'correct' => 1],
            ['question' => 'What are computed property names?', 'options' => ['Computed properties', 'Dynamic property names in object literals', 'Property computation', 'Computed names'], 'correct' => 1],
            ['question' => 'What is Object.defineProperty()?', 'options' => ['Define property', 'Defines property with descriptor', 'Property definition', 'Define object'], 'correct' => 1],
            ['question' => 'What are getters and setters?', 'options' => ['Get and set', 'Methods to get/set property values', 'Property accessors', 'Getter setter'], 'correct' => 1],
            ['question' => 'What are tagged template literals?', 'options' => ['Tagged templates', 'Function that processes template literal', 'Template tags', 'Tagged strings'], 'correct' => 1],
            ['question' => 'What is a regex?', 'options' => ['Regular text', 'Regular expression pattern', 'Regex function', 'Expression regex'], 'correct' => 1],
            ['question' => 'What is an ES module?', 'options' => ['ES6 module', 'JavaScript module system (import/export)', 'Module ES', 'Export module'], 'correct' => 1],
            ['question' => 'What is CommonJS?', 'options' => ['Common JavaScript', 'Node.js module system (require/module.exports)', 'Common module', 'JS common'], 'correct' => 1],
            ['question' => 'What is dynamic import()?', 'options' => ['Dynamic loading', 'Load modules asynchronously', 'Import dynamic', 'Dynamic module'], 'correct' => 1],
            ['question' => 'What is localStorage?', 'options' => ['Local storage', 'Web API for storing data locally', 'Storage local', 'Local data'], 'correct' => 1],
            ['question' => 'What is sessionStorage?', 'options' => ['Session storage', 'Web API for storing session data', 'Storage session', 'Session data'], 'correct' => 1],
            ['question' => 'What is addEventListener()?', 'options' => ['Add listener', 'Attaches event handler to element', 'Event listener', 'Listen event'], 'correct' => 1],
            ['question' => 'What is event bubbling?', 'options' => ['Bubble event', 'Event propagates from target up to root', 'Bubbling phase', 'Event bubble'], 'correct' => 1],
        ]
    ],
    [
        'label' => 'Advanced',
        'questions' => [
            ['question' => 'What is the V8 engine?', 'options' => ['V8 car engine', 'JavaScript engine used in Chrome/Node.js', 'Version 8', 'Engine V8'], 'correct' => 1],
            ['question' => 'What is JIT compilation?', 'options' => ['Just In Time', 'Just-In-Time compilation to machine code', 'JIT compiler', 'Compilation JIT'], 'correct' => 1],
            ['question' => 'What are hidden classes in V8?', 'options' => ['Hidden objects', 'Internal structures for optimizing property access', 'Class hiding', 'Hidden class'], 'correct' => 1],
            ['question' => 'What is garbage collection?', 'options' => ['Collecting garbage', 'Automatic memory management', 'GC process', 'Memory collection'], 'correct' => 1],
            ['question' => 'What is mark-and-sweep?', 'options' => ['Marking and sweeping', 'GC algorithm marking reachable objects', 'Mark sweep', 'Sweep mark'], 'correct' => 1],
            ['question' => 'What is a WeakRef?', 'options' => ['Weak reference', 'Weak reference to object without preventing GC', 'Ref weak', 'Weak object'], 'correct' => 1],
            ['question' => 'What is FinalizationRegistry?', 'options' => ['Final registry', 'API for cleanup callbacks when objects are GCed', 'Registry finalization', 'Finalize registry'], 'correct' => 1],
            ['question' => 'What is SharedArrayBuffer?', 'options' => ['Shared buffer', 'Shared memory between workers', 'Array buffer shared', 'Shared array'], 'correct' => 1],
            ['question' => 'What are Atomics?', 'options' => ['Atomic operations', 'API for atomic operations on shared memory', 'Atomic functions', 'Atomics API'], 'correct' => 1],
            ['question' => 'What is a Web Worker?', 'options' => ['Web working', 'Background thread for JavaScript', 'Worker web', 'Web thread'], 'correct' => 1],
            ['question' => 'What is a Service Worker?', 'options' => ['Service working', 'Background script for PWAs, caching, offline', 'Worker service', 'Service thread'], 'correct' => 1],
            ['question' => 'What is the Module pattern?', 'options' => ['Module design', 'Design pattern for encapsulation', 'Pattern module', 'Module structure'], 'correct' => 1],
            ['question' => 'What is the Factory pattern?', 'options' => ['Factory design', 'Pattern for creating objects', 'Pattern factory', 'Factory function'], 'correct' => 1],
            ['question' => 'What is the Singleton pattern?', 'options' => ['Single instance', 'Pattern ensuring single instance', 'Pattern singleton', 'Singleton design'], 'correct' => 1],
            ['question' => 'What is a pure function?', 'options' => ['Pure code', 'Function with no side effects, same input = same output', 'Function pure', 'Pure logic'], 'correct' => 1],
            ['question' => 'What is immutability?', 'options' => ['Cannot change', 'Data that cannot be modified', 'Immutable data', 'Not mutable'], 'correct' => 1],
            ['question' => 'What is currying?', 'options' => ['Curry function', 'Transforming function to sequence of single-arg functions', 'Function currying', 'Curry pattern'], 'correct' => 1],
            ['question' => 'What is function composition?', 'options' => ['Composing functions', 'Combining functions to create new function', 'Function compose', 'Composition pattern'], 'correct' => 1],
            ['question' => 'What is memoization?', 'options' => ['Memory function', 'Caching function results', 'Memo pattern', 'Memoize function'], 'correct' => 1],
            ['question' => 'What is debouncing?', 'options' => ['Debounce event', 'Delaying function execution until after wait time', 'Debounce pattern', 'Debounce function'], 'correct' => 1],
            ['question' => 'What is throttling?', 'options' => ['Throttle event', 'Limiting function execution rate', 'Throttle pattern', 'Throttle function'], 'correct' => 1],
            ['question' => 'What is AbortController?', 'options' => ['Abort control', 'API to abort fetch/async operations', 'Controller abort', 'Abort API'], 'correct' => 1],
            ['question' => 'What is ReadableStream?', 'options' => ['Readable stream', 'Stream API for reading data chunks', 'Stream readable', 'Read stream'], 'correct' => 1],
            ['question' => 'What is requestAnimationFrame?', 'options' => ['Request animation', 'API for smooth animations', 'Animation frame', 'Frame request'], 'correct' => 1],
            ['question' => 'What is IntersectionObserver?', 'options' => ['Intersection API', 'API to observe element visibility', 'Observer intersection', 'Intersect observer'], 'correct' => 1],
            ['question' => 'What is MutationObserver?', 'options' => ['Mutation API', 'API to observe DOM changes', 'Observer mutation', 'Mutation observer'], 'correct' => 1],
            ['question' => 'What is ResizeObserver?', 'options' => ['Resize API', 'API to observe element size changes', 'Observer resize', 'Resize observer'], 'correct' => 1],
            ['question' => 'What are typed arrays?', 'options' => ['Array types', 'Arrays for binary data (Int32Array, etc.)', 'Typed data', 'Array typed'], 'correct' => 1],
        ]
    ],
    [
        'label' => 'Expert',
        'questions' => [
            ['question' => 'What is the ECMAScript specification?', 'options' => ['ES spec', 'Standard defining JavaScript language', 'JavaScript specification', 'Spec ES'], 'correct' => 1],
            ['question' => 'What are abstract operations in the spec?', 'options' => ['Abstract functions', 'Internal algorithms in the spec', 'Operations abstract', 'Abstract spec'], 'correct' => 1],
            ['question' => 'What is a Realm?', 'options' => ['Realm concept', 'Execution context with global object and intrinsics', 'Realm execution', 'Context realm'], 'correct' => 1],
            ['question' => 'What is an agent cluster?', 'options' => ['Agent group', 'Group of agents that can share memory', 'Cluster agent', 'Agent sharing'], 'correct' => 1],
            ['question' => 'What is the JavaScript memory model?', 'options' => ['Memory structure', 'Model defining shared memory semantics', 'Model memory', 'Memory semantics'], 'correct' => 1],
            ['question' => 'What is happens-before relationship?', 'options' => ['Before happening', 'Memory ordering guarantee', 'Relationship happens', 'Happens before'], 'correct' => 1],
            ['question' => 'What does Atomics.wait() do?', 'options' => ['Waits atomically', 'Blocks until notified or timeout', 'Wait function', 'Atomic wait'], 'correct' => 1],
            ['question' => 'What does Atomics.notify() do?', 'options' => ['Notifies atomically', 'Wakes agents waiting on location', 'Notify function', 'Atomic notify'], 'correct' => 1],
            ['question' => 'What are cross-realm issues?', 'options' => ['Realm crossing', 'Problems when objects cross realm boundaries', 'Cross realm', 'Realm issues'], 'correct' => 1],
            ['question' => 'What is a lookbehind in regex?', 'options' => ['Look behind', 'Assert what precedes current position', 'Behind regex', 'Lookbehind assertion'], 'correct' => 1],
            ['question' => 'What is a lookahead in regex?', 'options' => ['Look ahead', 'Assert what follows current position', 'Ahead regex', 'Lookahead assertion'], 'correct' => 1],
            ['question' => 'What are named capture groups in regex?', 'options' => ['Named groups', 'Capture groups with names', 'Group naming', 'Named captures'], 'correct' => 1],
            ['question' => 'What is the Temporal proposal?', 'options' => ['Temporal API', 'Modern date/time API for JavaScript', 'Proposal temporal', 'Temporal date'], 'correct' => 1],
            ['question' => 'What is the pipeline operator proposal?', 'options' => ['Pipeline operator', 'Operator for function chaining |&gt;', 'Operator pipeline', 'Pipe proposal'], 'correct' => 1],
            ['question' => 'What is the pattern matching proposal?', 'options' => ['Pattern match', 'Structural pattern matching for JavaScript', 'Matching proposal', 'Pattern proposal'], 'correct' => 1],
            ['question' => 'What is V8 Turbofan?', 'options' => ['Turbo fan', 'V8 optimizing compiler', 'Turbofan compiler', 'V8 optimizer'], 'correct' => 1],
            ['question' => 'What triggers deoptimization?', 'options' => ['Deopt trigger', 'Type changes, assumptions violated', 'Optimization loss', 'Deopt cause'], 'correct' => 1],
            ['question' => 'What is escape analysis?', 'options' => ['Escape detection', 'Optimization determining object scope', 'Analysis escape', 'Escape optimization'], 'correct' => 1],
            ['question' => 'What is inlining in JIT?', 'options' => ['Inline code', 'Replacing function calls with function body', 'Inlining optimization', 'Inline JIT'], 'correct' => 1],
            ['question' => 'What is monomorphism?', 'options' => ['Single form', 'Property always same type/shape', 'Monomorphic code', 'Single shape'], 'correct' => 1],
            ['question' => 'What is polymorphism in V8?', 'options' => ['Multiple forms', 'Property has multiple types/shapes', 'Polymorphic code', 'Multiple shapes'], 'correct' => 1],
            ['question' => 'What is megamorphism?', 'options' => ['Mega form', 'Property has too many types/shapes (slow)', 'Megamorphic code', 'Many shapes'], 'correct' => 1],
            ['question' => 'What is prototype pollution?', 'options' => ['Polluting prototype', 'Security vulnerability modifying Object.prototype', 'Pollution attack', 'Prototype attack'], 'correct' => 1],
            ['question' => 'What is XSS?', 'options' => ['Cross Site Scripting', 'Injecting malicious scripts', 'XSS attack', 'Script injection'], 'correct' => 0],
            ['question' => 'What is eval() security risk?', 'options' => ['Eval danger', 'Executes arbitrary code, security risk', 'Eval risk', 'Code execution'], 'correct' => 1],
            ['question' => 'What is CSP for JavaScript?', 'options' => ['Content Security Policy', 'Prevents XSS by restricting script sources', 'CSP policy', 'Security CSP'], 'correct' => 1],
            ['question' => 'What is a Trusted Type?', 'options' => ['Trusted data', 'API preventing DOM XSS', 'Type trusted', 'Trust API'], 'correct' => 1],
            ['question' => 'What are transducers?', 'options' => ['Transducer pattern', 'Composable algorithmic transformations', 'Transducer function', 'Transform pattern'], 'correct' => 1],
        ]
    ],
];
require_once __DIR__ . '/quiz-engine.php';
