<?php
$page_title = 'jQuery Quiz – 100 Levels – CodeFoundry';
$active_page = 'training';
$quiz_title  = 'jQuery';
$quiz_slug   = 'jquery';
$quiz_tiers  = [
    [
        'label' => 'Introduction',
        'questions' => [
            ['question' => 'What does jQuery primarily simplify?', 'options' => ['CSS styling', 'JavaScript DOM manipulation', 'Server-side scripting', 'Database queries'], 'correct' => 1],
            ['question' => 'What is the most common CDN to include jQuery from?', 'options' => ['Bootstrap CDN', 'Google CDN', 'Facebook CDN', 'Amazon CDN'], 'correct' => 1],
            ['question' => 'What does the $ symbol represent in jQuery?', 'options' => ['A currency symbol', 'An alias for the jQuery function', 'A PHP variable', 'A CSS selector'], 'correct' => 1],
            ['question' => 'Which function ensures code runs after the DOM is ready?', 'options' => ['$(window).load()', '$(document).ready()', '$(body).onload()', '$(html).start()'], 'correct' => 1],
            ['question' => 'What is the shorthand for $(document).ready()?', 'options' => ['$(ready)', '$().start()', '$(function(){})', '$(dom)'], 'correct' => 2],
            ['question' => 'How do you select an element with id="header"?', 'options' => ['$(".header")', '$("#header")', '$("header")', '$(*header)'], 'correct' => 1],
            ['question' => 'How do you select all elements with class="btn"?', 'options' => ['$("#btn")', '$("btn")', '$(".btn")', '$(*btn)'], 'correct' => 2],
            ['question' => 'How do you select all div elements?', 'options' => ['$(".div")', '$("#div")', '$("div")', '$(div)'], 'correct' => 2],
            ['question' => 'What does .html() do?', 'options' => ['Gets or sets HTML content', 'Parses HTML', 'Validates HTML', 'Compiles HTML'], 'correct' => 0],
            ['question' => 'What does .text() do?', 'options' => ['Gets or sets text content without HTML', 'Gets HTML content', 'Sets CSS text property', 'Validates text'], 'correct' => 0],
            ['question' => 'What method gets or sets form input values?', 'options' => ['.value()', '.input()', '.val()', '.get()'], 'correct' => 2],
            ['question' => 'What does .css("color", "red") do?', 'options' => ['Gets the color', 'Sets color to red', 'Removes color', 'Validates color'], 'correct' => 1],
            ['question' => 'Which method adds a CSS class?', 'options' => ['.addClass()', '.addStyle()', '.appendClass()', '.setClass()'], 'correct' => 0],
            ['question' => 'Which method removes a CSS class?', 'options' => ['.deleteClass()', '.removeClass()', '.removeStyle()', '.dropClass()'], 'correct' => 1],
            ['question' => 'What does .toggleClass() do?', 'options' => ['Adds a class', 'Removes a class', 'Adds if absent, removes if present', 'Changes class name'], 'correct' => 2],
            ['question' => 'Which method checks if an element has a class?', 'options' => ['.checkClass()', '.hasClass()', '.containsClass()', '.isClass()'], 'correct' => 1],
            ['question' => 'What does .show() do?', 'options' => ['Displays hidden elements', 'Prints to console', 'Validates visibility', 'Creates a modal'], 'correct' => 0],
            ['question' => 'What does .hide() do?', 'options' => ['Deletes elements', 'Makes elements invisible', 'Removes from DOM', 'Minimizes elements'], 'correct' => 1],
            ['question' => 'What does .toggle() do?', 'options' => ['Shows only', 'Hides only', 'Switches between show and hide', 'Deletes element'], 'correct' => 2],
            ['question' => 'How do you attach a click event handler?', 'options' => ['.onclick()', '.click()', '.addClick()', '.bind("click")'], 'correct' => 1],
            ['question' => 'What is the modern event binding method?', 'options' => ['.bind()', '.on()', '.attach()', '.listen()'], 'correct' => 1],
            ['question' => 'What does .attr("src", "img.jpg") do?', 'options' => ['Gets src attribute', 'Sets src attribute', 'Removes src attribute', 'Validates src'], 'correct' => 1],
            ['question' => 'Which method removes an attribute?', 'options' => ['.deleteAttr()', '.removeAttr()', '.dropAttr()', '.clearAttr()'], 'correct' => 1],
            ['question' => 'What is .prop() used for?', 'options' => ['CSS properties only', 'Element properties like checked/disabled', 'HTML attributes only', 'Style properties'], 'correct' => 1],
            ['question' => 'What is method chaining in jQuery?', 'options' => ['Calling multiple methods in sequence on same object', 'Creating method dependencies', 'Linking multiple files', 'Inheriting methods'], 'correct' => 0],
            ['question' => 'What is a key advantage of jQuery over vanilla JS?', 'options' => ['Faster execution', 'Cross-browser compatibility', 'Better security', 'Smaller file size'], 'correct' => 1],
            ['question' => 'What is the current major version of jQuery (as of 2024)?', 'options' => ['jQuery 1.x', 'jQuery 2.x', 'jQuery 3.x', 'jQuery 4.x'], 'correct' => 2],
            ['question' => 'What does $.noConflict() do?', 'options' => ['Prevents errors', 'Releases the $ shortcut', 'Fixes conflicts', 'Validates code'], 'correct' => 1],
            ['question' => 'What does .find() do?', 'options' => ['Searches parent elements', 'Searches descendant elements', 'Searches sibling elements', 'Searches the entire DOM'], 'correct' => 1],
            ['question' => 'What does .children() return?', 'options' => ['All descendants', 'Direct children only', 'Parent elements', 'Sibling elements'], 'correct' => 1],
            ['question' => 'What does .parent() return?', 'options' => ['All ancestors', 'Direct parent only', 'Root element', 'Document object'], 'correct' => 1],
            ['question' => 'What does .siblings() return?', 'options' => ['Children', 'Parents', 'Elements at same level', 'All related elements'], 'correct' => 2],
            ['question' => 'What does .length property return?', 'options' => ['String length', 'Number of matched elements', 'Array size', 'DOM depth'], 'correct' => 1],
        ]
    ],
    [
        'label' => 'Beginner',
        'questions' => [
            ['question' => 'What does .parents() return?', 'options' => ['Direct parent', 'All ancestor elements', 'Sibling elements', 'Child elements'], 'correct' => 1],
            ['question' => 'What does .closest() do?', 'options' => ['Finds nearest matching ancestor', 'Finds all ancestors', 'Finds nearest child', 'Finds siblings'], 'correct' => 0],
            ['question' => 'What does .next() return?', 'options' => ['All following siblings', 'Immediately following sibling', 'Next parent', 'Next child'], 'correct' => 1],
            ['question' => 'What does .prev() return?', 'options' => ['All previous siblings', 'Immediately preceding sibling', 'Previous parent', 'Previous child'], 'correct' => 1],
            ['question' => 'What does .nextAll() return?', 'options' => ['Next sibling only', 'All following siblings', 'Next generation', 'All descendants'], 'correct' => 1],
            ['question' => 'What does .prevAll() return?', 'options' => ['Previous sibling only', 'All preceding siblings', 'All ancestors', 'Previous generation'], 'correct' => 1],
            ['question' => 'What does .first() return?', 'options' => ['First in document', 'First matched element', 'First child', 'First parent'], 'correct' => 1],
            ['question' => 'What does .last() return?', 'options' => ['Last in document', 'Last matched element', 'Last child', 'Last parent'], 'correct' => 1],
            ['question' => 'What does .eq(2) return?', 'options' => ['Third matched element (0-indexed)', 'Second matched element', 'All equal elements', 'Two elements'], 'correct' => 0],
            ['question' => 'What does .filter(".active") do?', 'options' => ['Removes active class', 'Reduces to elements matching selector', 'Adds active class', 'Filters CSS'], 'correct' => 1],
            ['question' => 'What does .not(".active") do?', 'options' => ['Adds active class', 'Removes elements matching selector', 'Toggles active class', 'Validates selector'], 'correct' => 1],
            ['question' => 'What does .append() do?', 'options' => ['Adds content at beginning', 'Adds content at end', 'Replaces content', 'Removes content'], 'correct' => 1],
            ['question' => 'What does .prepend() do?', 'options' => ['Adds content at beginning', 'Adds content at end', 'Replaces content', 'Removes content'], 'correct' => 0],
            ['question' => 'What does .after() do?', 'options' => ['Inserts content inside at end', 'Inserts content after element', 'Executes after delay', 'Runs after event'], 'correct' => 1],
            ['question' => 'What does .before() do?', 'options' => ['Inserts content inside at start', 'Inserts content before element', 'Executes before event', 'Validates before action'], 'correct' => 1],
            ['question' => 'What is the difference between .append() and .appendTo()?', 'options' => ['No difference', 'Reversed syntax and chaining context', 'One is deprecated', 'One is faster'], 'correct' => 1],
            ['question' => 'What does .remove() do?', 'options' => ['Hides element', 'Removes element from DOM', 'Removes content only', 'Removes attributes'], 'correct' => 1],
            ['question' => 'What does .detach() do?', 'options' => ['Same as hide()', 'Removes element but keeps data/events', 'Deletes permanently', 'Detaches events only'], 'correct' => 1],
            ['question' => 'What does .empty() do?', 'options' => ['Removes element', 'Removes all child content', 'Clears attributes', 'Resets styles'], 'correct' => 1],
            ['question' => 'What does .clone() do?', 'options' => ['Creates element copy', 'Copies attributes only', 'Duplicates events', 'Copies styles'], 'correct' => 0],
            ['question' => 'What does .replaceWith() do?', 'options' => ['Changes text', 'Replaces element with new content', 'Updates attributes', 'Swaps position'], 'correct' => 1],
            ['question' => 'What does .wrap() do?', 'options' => ['Wraps text', 'Wraps element with HTML structure', 'Groups elements', 'Creates wrapper div'], 'correct' => 1],
            ['question' => 'What does .unwrap() do?', 'options' => ['Removes wrapper parent', 'Removes content', 'Unwraps text', 'Reverses wrap'], 'correct' => 0],
            ['question' => 'What does .wrapAll() do?', 'options' => ['Wraps each individually', 'Wraps all matched elements as group', 'Wraps content', 'Wraps in multiple layers'], 'correct' => 1],
            ['question' => 'What does .dblclick() bind?', 'options' => ['Single click', 'Double click event', 'Right click', 'Long press'], 'correct' => 1],
            ['question' => 'What does .mouseenter() detect?', 'options' => ['Mouse down', 'Mouse entering element', 'Mouse leaving', 'Mouse movement'], 'correct' => 1],
            ['question' => 'What does .mouseleave() detect?', 'options' => ['Mouse down', 'Mouse entering', 'Mouse leaving element', 'Mouse up'], 'correct' => 2],
            ['question' => 'What is .hover() shorthand for?', 'options' => ['mouseenter only', 'mouseleave only', 'mouseenter and mouseleave', 'mouseover and mouseout'], 'correct' => 2],
            ['question' => 'What does .keydown() detect?', 'options' => ['Key release', 'Key press start', 'Character input', 'Key combination'], 'correct' => 1],
            ['question' => 'What does .keyup() detect?', 'options' => ['Key press start', 'Key release', 'Character input', 'Arrow keys only'], 'correct' => 1],
            ['question' => 'What does .focus() do when called?', 'options' => ['Blurs element', 'Sets focus or binds focus event', 'Validates input', 'Highlights element'], 'correct' => 1],
            ['question' => 'What does .blur() do?', 'options' => ['Makes blurry', 'Removes focus or binds blur event', 'Hides element', 'Validates input'], 'correct' => 1],
            ['question' => 'What does .change() detect?', 'options' => ['Any modification', 'Value change on form elements', 'Content change', 'Attribute change'], 'correct' => 1],
            ['question' => 'What does .submit() do?', 'options' => ['Sends form', 'Submits or binds submit event', 'Validates form', 'Posts data'], 'correct' => 1],
            ['question' => 'What does .on("click", fn) do?', 'options' => ['Toggles on', 'Binds click event handler', 'Enables element', 'Activates feature'], 'correct' => 1],
            ['question' => 'What does .off("click") do?', 'options' => ['Disables element', 'Removes click event handlers', 'Toggles off', 'Deactivates feature'], 'correct' => 1],
            ['question' => 'What does .one("click", fn) do?', 'options' => ['Binds to one element', 'Binds handler that runs once then removes', 'Binds first event', 'Single-use element'], 'correct' => 1],
            ['question' => 'What does .trigger("click") do?', 'options' => ['Binds click', 'Manually fires click event', 'Enables clicking', 'Validates click'], 'correct' => 1],
            ['question' => 'In event handler, what is "this"?', 'options' => ['Window object', 'The DOM element', 'jQuery object', 'Event object'], 'correct' => 1],
            ['question' => 'What is e.target in event handler?', 'options' => ['Element that triggered', 'Element handler attached to', 'Parent element', 'Document'], 'correct' => 0],
            ['question' => 'What does e.preventDefault() do?', 'options' => ['Stops bubbling', 'Prevents default browser action', 'Removes event', 'Validates event'], 'correct' => 1],
            ['question' => 'What does e.stopPropagation() do?', 'options' => ['Prevents default', 'Stops event bubbling', 'Removes handler', 'Pauses execution'], 'correct' => 1],
            ['question' => 'What does $.ajax() do?', 'options' => ['Validates async', 'Performs asynchronous HTTP request', 'Activates AJAX', 'Loads library'], 'correct' => 1],
            ['question' => 'What does $.get() do?', 'options' => ['Gets element', 'Performs GET request', 'Retrieves data', 'Gets property'], 'correct' => 1],
            ['question' => 'What does $.post() do?', 'options' => ['Posts message', 'Performs POST request', 'Submits form', 'Sends email'], 'correct' => 1],
            ['question' => 'What does .load() do?', 'options' => ['Loads page', 'Loads HTML from server into element', 'Preloads image', 'Loads script'], 'correct' => 1],
            ['question' => 'What does .each() do?', 'options' => ['Selects each', 'Iterates over jQuery object', 'Counts elements', 'Groups elements'], 'correct' => 1],
            ['question' => 'What does $.map() do?', 'options' => ['Creates map', 'Transforms array/object elements', 'Maps coordinates', 'Binds mapping'], 'correct' => 1],
            ['question' => 'What does $.grep() do?', 'options' => ['Searches text', 'Filters array by function', 'Groups elements', 'Validates pattern'], 'correct' => 1],
            ['question' => 'What does $.inArray() do?', 'options' => ['Checks if in array', 'Searches array for value returns index', 'Validates array', 'Converts to array'], 'correct' => 1],
            ['question' => 'What does $.extend() do?', 'options' => ['Extends jQuery', 'Merges objects', 'Adds methods', 'Inherits properties'], 'correct' => 1],
        ]
    ],
    [
        'label' => 'Intermediate',
        'questions' => [
            ['question' => 'What $.ajax() setting specifies the request type?', 'options' => ['type', 'method', 'requestType', 'httpMethod'], 'correct' => 1],
            ['question' => 'What $.ajax() setting specifies the target URL?', 'options' => ['target', 'url', 'endpoint', 'destination'], 'correct' => 1],
            ['question' => 'What $.ajax() setting sends data with request?', 'options' => ['params', 'data', 'body', 'payload'], 'correct' => 1],
            ['question' => 'What $.ajax() setting specifies expected response type?', 'options' => ['responseType', 'dataType', 'contentType', 'format'], 'correct' => 1],
            ['question' => 'What $.ajax() callback runs on success?', 'options' => ['done', 'success', 'complete', 'then'], 'correct' => 1],
            ['question' => 'What $.ajax() callback runs on error?', 'options' => ['fail', 'error', 'catch', 'reject'], 'correct' => 1],
            ['question' => 'What $.ajax() callback runs after success or error?', 'options' => ['always', 'complete', 'finally', 'done'], 'correct' => 1],
            ['question' => 'What $.ajax() callback runs before request?', 'options' => ['before', 'beforeSend', 'preRequest', 'initialize'], 'correct' => 1],
            ['question' => 'What $.ajax() setting adds custom headers?', 'options' => ['header', 'headers', 'customHeaders', 'httpHeaders'], 'correct' => 1],
            ['question' => 'What $.ajax() setting specifies request timeout?', 'options' => ['timeout', 'maxTime', 'duration', 'expire'], 'correct' => 0],
            ['question' => 'What $.ajax() setting controls asynchronous behavior?', 'options' => ['sync', 'async', 'asynchronous', 'nonBlocking'], 'correct' => 1],
            ['question' => 'What does $.ajax() return?', 'options' => ['Promise', 'jqXHR object', 'Response', 'XMLHttpRequest'], 'correct' => 1],
            ['question' => 'What method can you call on jqXHR for success?', 'options' => ['.success()', '.done()', '.then()', '.complete()'], 'correct' => 1],
            ['question' => 'What method can you call on jqXHR for error?', 'options' => ['.error()', '.fail()', '.catch()', '.reject()'], 'correct' => 1],
            ['question' => 'What method runs regardless of jqXHR outcome?', 'options' => ['.complete()', '.always()', '.finally()', '.done()'], 'correct' => 1],
            ['question' => 'What does $.Deferred() create?', 'options' => ['Promise', 'Deferred object', 'Callback', 'Timer'], 'correct' => 1],
            ['question' => 'How do you resolve a deferred?', 'options' => ['.complete()', '.resolve()', '.success()', '.finish()'], 'correct' => 1],
            ['question' => 'How do you reject a deferred?', 'options' => ['.fail()', '.reject()', '.error()', '.cancel()'], 'correct' => 1],
            ['question' => 'What does deferred.promise() return?', 'options' => ['Deferred copy', 'Read-only promise', 'Resolved value', 'Callback'], 'correct' => 1],
            ['question' => 'What does $.when() do?', 'options' => ['Delays execution', 'Waits for multiple deferreds', 'Conditional execution', 'Schedules callback'], 'correct' => 1],
            ['question' => 'What does .animate() do?', 'options' => ['Plays video', 'Animates CSS properties', 'Creates animation', 'Triggers effect'], 'correct' => 1],
            ['question' => 'What does .stop() do?', 'options' => ['Stops script', 'Stops current animation', 'Prevents event', 'Halts execution'], 'correct' => 1],
            ['question' => 'What does .delay() do?', 'options' => ['Slows down', 'Delays next queued item', 'Pauses script', 'Waits for event'], 'correct' => 1],
            ['question' => 'What does .queue() do?', 'options' => ['Creates queue', 'Manipulates animation queue', 'Lines up elements', 'Orders operations'], 'correct' => 1],
            ['question' => 'What does .dequeue() do?', 'options' => ['Removes from line', 'Executes next queued function', 'Clears queue', 'Stops queue'], 'correct' => 1],
            ['question' => 'What does .clearQueue() do?', 'options' => ['Clears cache', 'Removes remaining queued functions', 'Resets state', 'Stops animation'], 'correct' => 1],
            ['question' => 'What jQuery UI interaction enables dragging?', 'options' => ['.drag()', '.draggable()', '.moveable()', '.dragInit()'], 'correct' => 1],
            ['question' => 'What jQuery UI interaction creates drop targets?', 'options' => ['.drop()', '.droppable()', '.dropzone()', '.acceptDrop()'], 'correct' => 1],
            ['question' => 'What jQuery UI interaction enables resizing?', 'options' => ['.resize()', '.resizable()', '.scalable()', '.sizable()'], 'correct' => 1],
            ['question' => 'What jQuery UI interaction enables sorting?', 'options' => ['.sort()', '.sortable()', '.reorder()', '.arrange()'], 'correct' => 1],
            ['question' => 'What jQuery UI widget creates accordion?', 'options' => ['.accordian()', '.accordion()', '.collapse()', '.expandable()'], 'correct' => 1],
            ['question' => 'What jQuery UI widget adds autocomplete?', 'options' => ['.suggest()', '.autocomplete()', '.complete()', '.autofill()'], 'correct' => 1],
            ['question' => 'What jQuery UI widget creates datepicker?', 'options' => ['.calendar()', '.datepicker()', '.dateselect()', '.pickdate()'], 'correct' => 1],
            ['question' => 'What jQuery UI widget creates dialog?', 'options' => ['.modal()', '.dialog()', '.popup()', '.window()'], 'correct' => 1],
            ['question' => 'What does .serialize() do?', 'options' => ['Converts to JSON', 'Encodes form data as query string', 'Saves state', 'Exports data'], 'correct' => 1],
            ['question' => 'What does .serializeArray() return?', 'options' => ['Query string', 'Array of name/value objects', 'JSON string', 'Serialized string'], 'correct' => 1],
            ['question' => 'What does $.param() do?', 'options' => ['Gets parameter', 'Creates query string from object', 'Sets parameter', 'Validates params'], 'correct' => 1],
            ['question' => 'What does .data() do?', 'options' => ['Gets data attribute', 'Stores/retrieves arbitrary data', 'Sends data', 'Validates data'], 'correct' => 1],
            ['question' => 'Where does .data() store information?', 'options' => ['In attribute', 'In jQuery cache', 'In localStorage', 'In cookie'], 'correct' => 1],
            ['question' => 'What is the difference between .closest() and .parents()?', 'options' => ['No difference', '.closest() returns first match including self', 'One is deprecated', '.parents() is faster'], 'correct' => 1],
            ['question' => 'What is event delegation?', 'options' => ['Delegating to other handlers', 'Attaching handler to parent for child events', 'Passing events', 'Sharing handlers'], 'correct' => 1],
            ['question' => 'Why is event delegation efficient?', 'options' => ['Faster execution', 'Fewer handlers needed', 'Better compatibility', 'Smaller code'], 'correct' => 1],
            ['question' => 'What is a performance benefit of caching selectors?', 'options' => ['Saves memory', 'Avoids repeated DOM queries', 'Faster loading', 'Better compression'], 'correct' => 1],
            ['question' => 'What is better for adding multiple elements?', 'options' => ['Individual appends', 'Document fragment', 'innerHTML', 'createElement'], 'correct' => 1],
            ['question' => 'What is batch DOM manipulation?', 'options' => ['Processing batches', 'Making multiple changes before appending', 'Grouping operations', 'Parallel processing'], 'correct' => 1],
            ['question' => 'Should you use .css() for multiple properties?', 'options' => ['Yes, always', 'No, use classes instead', 'Only inline', 'Only for animation'], 'correct' => 1],
            ['question' => 'What is chaining used for?', 'options' => ['Security', 'Calling methods sequentially on same object', 'Linking pages', 'Creating chains'], 'correct' => 1],
            ['question' => 'What breaks a jQuery chain?', 'options' => ['Errors', 'Methods returning non-jQuery values', 'Too many methods', 'Syntax errors'], 'correct' => 1],
            ['question' => 'How do you restore previous selection in chain?', 'options' => ['.prev()', '.end()', '.back()', '.restore()'], 'correct' => 1],
            ['question' => 'What is $.ajax() crossDomain setting for?', 'options' => ['Multiple domains', 'Cross-origin requests', 'Domain validation', 'CORS policy'], 'correct' => 1],
        ]
    ],
    [
        'label' => 'Advanced',
        'questions' => [
            ['question' => 'How do you create a jQuery plugin?', 'options' => ['$.plugin = fn', '$.fn.pluginName = fn', 'jQuery.plugin()', '$.addPlugin()'], 'correct' => 1],
            ['question' => 'What is $.fn?', 'options' => ['Function namespace', 'jQuery prototype', 'Utility namespace', 'Plugin object'], 'correct' => 1],
            ['question' => 'What is common plugin pattern for options?', 'options' => ['Global options', 'Extend default settings with passed options', 'Hard-coded options', 'Option callbacks'], 'correct' => 1],
            ['question' => 'How do plugins expose methods?', 'options' => ['Return functions', 'String first parameter pattern', 'Global methods', 'Callbacks'], 'correct' => 1],
            ['question' => 'What selector engine did jQuery use?', 'options' => ['querySelector', 'Sizzle', 'CSS3 parser', 'XPath'], 'correct' => 1],
            ['question' => 'What does $.Callbacks() manage?', 'options' => ['Event callbacks', 'List of callbacks with control flags', 'Async callbacks', 'Error callbacks'], 'correct' => 1],
            ['question' => 'What does $.Callbacks().add() do?', 'options' => ['Creates callback', 'Adds callback to list', 'Executes callback', 'Registers handler'], 'correct' => 1],
            ['question' => 'What does $.Callbacks().fire() do?', 'options' => ['Triggers event', 'Calls all callbacks in list', 'Removes callbacks', 'Fires once'], 'correct' => 1],
            ['question' => 'What does $.Callbacks().remove() do?', 'options' => ['Deletes list', 'Removes callback from list', 'Disables callback', 'Clears callbacks'], 'correct' => 1],
            ['question' => 'What does $.Callbacks().disable() do?', 'options' => ['Turns off', 'Prevents further callback additions/firing', 'Removes all', 'Locks list'], 'correct' => 1],
            ['question' => 'What does $.Callbacks().lock() do?', 'options' => ['Prevents changes', 'Locks with current callback state', 'Disables', 'Freezes'], 'correct' => 1],
            ['question' => 'What does "once" flag in $.Callbacks() do?', 'options' => ['Single callback', 'List fires only once', 'First callback only', 'One-time use'], 'correct' => 1],
            ['question' => 'What does "memory" flag in $.Callbacks() do?', 'options' => ['Saves to memory', 'Remembers last fire() arguments', 'Caches callbacks', 'Stores history'], 'correct' => 1],
            ['question' => 'What does "unique" flag in $.Callbacks() do?', 'options' => ['Unique ID', 'Prevents duplicate callbacks', 'Single use', 'Distinct values'], 'correct' => 1],
            ['question' => 'What does "stopOnFalse" flag do?', 'options' => ['Stops on error', 'Stops when callback returns false', 'Prevents false', 'Validates result'], 'correct' => 1],
            ['question' => 'How do jQuery promises differ from native?', 'options' => ['No difference', 'Different API (.done/.fail vs .then/.catch)', 'Slower', 'Better compatibility'], 'correct' => 1],
            ['question' => 'Can jQuery promises be rejected after resolving?', 'options' => ['Yes', 'No, state is immutable', 'Only once', 'Only with flag'], 'correct' => 1],
            ['question' => 'What does $.when() return?', 'options' => ['Array', 'Promise', 'Boolean', 'Callback'], 'correct' => 1],
            ['question' => 'How do you namespace events?', 'options' => ['.on("event.namespace")', '.namespace("event")', '.on("event", {ns})', '.addNamespace()'], 'correct' => 0],
            ['question' => 'What is benefit of event namespacing?', 'options' => ['Organization', 'Selective unbinding', 'Performance', 'Security'], 'correct' => 1],
            ['question' => 'What is $.fn.extend() for?', 'options' => ['Extend jQuery', 'Add methods to jQuery.fn', 'Extend objects', 'Inherit methods'], 'correct' => 1],
            ['question' => 'What is $.extend() for?', 'options' => ['Extend jQuery.fn', 'Add methods to jQuery or merge objects', 'Plugin extension', 'Prototype extension'], 'correct' => 1],
            ['question' => 'Was jQuery.sub() deprecated?', 'options' => ['No', 'Yes', 'Not yet', 'Only in 2.x'], 'correct' => 1],
            ['question' => 'What is jQuery.fn.init?', 'options' => ['Initialization', 'Constructor function', 'Setup method', 'Boot function'], 'correct' => 1],
            ['question' => 'What is detached DOM optimization?', 'options' => ['Removing elements', 'Modifying elements before attaching', 'Lazy loading', 'Cache optimization'], 'correct' => 1],
            ['question' => 'Does jQuery use virtual DOM?', 'options' => ['Yes', 'No', 'In 3.x', 'Optional'], 'correct' => 1],
            ['question' => 'Is jQuery still relevant in modern JS?', 'options' => ['No, obsolete', 'Yes, for legacy and rapid development', 'Only for old browsers', 'Being replaced'], 'correct' => 1],
            ['question' => 'What can replace $.ajax()?', 'options' => ['XMLHttpRequest', 'fetch()', 'axios', 'All of above'], 'correct' => 3],
            ['question' => 'What CSP directive affects jQuery?', 'options' => ['script-src', 'unsafe-inline', 'unsafe-eval', 'All of above'], 'correct' => 3],
            ['question' => 'What is JSONP used for?', 'options' => ['JSON parsing', 'Cross-domain requests', 'Data validation', 'Compression'], 'correct' => 1],
            ['question' => 'How does JSONP work?', 'options' => ['XHR', 'Script tag injection', 'iframe', 'WebSocket'], 'correct' => 1],
            ['question' => 'What is jQuery Migrate plugin for?', 'options' => ['Database migration', 'Compatibility with deprecated features', 'Moving projects', 'Version updates'], 'correct' => 1],
            ['question' => 'Should you use jQuery for new projects in 2024?', 'options' => ['Always', 'Depends on requirements', 'Never', 'Only with frameworks'], 'correct' => 1],
            ['question' => 'What replaced .bind()?', 'options' => ['.attach()', '.on()', '.listen()', '.addEventListener()'], 'correct' => 1],
            ['question' => 'What replaced .delegate()?', 'options' => ['.on() with selector', '.bind()', '.attach()', '.listen()'], 'correct' => 0],
            ['question' => 'What replaced .live()?', 'options' => ['.bind()', '.on()', '.delegate()', '.attach()'], 'correct' => 1],
            ['question' => 'What replaced .size()?', 'options' => ['.count()', '.length', '.num()', '.total()'], 'correct' => 1],
            ['question' => 'Is $.browser supported?', 'options' => ['Yes', 'No, removed/deprecated', 'Only in 1.x', 'Only with Migrate'], 'correct' => 1],
            ['question' => 'What is better for feature detection?', 'options' => ['$.browser', 'Modernizr', '$.support', 'User agent'], 'correct' => 1],
            ['question' => 'What does $.support contain?', 'options' => ['Browser info', 'Feature detection results', 'Version info', 'Compatibility data'], 'correct' => 1],
            ['question' => 'How do you handle $.ajax() timeouts?', 'options' => ['Try-catch', 'error callback', 'timeout setting and error handling', 'setTimeout'], 'correct' => 2],
            ['question' => 'Can you cancel $.ajax() requests?', 'options' => ['No', 'Yes with jqXHR.abort()', 'Only synchronous', 'Not directly'], 'correct' => 1],
            ['question' => 'What is $.ajaxSetup() for?', 'options' => ['Setup AJAX', 'Set default AJAX settings', 'Initialize AJAX', 'Configure server'], 'correct' => 1],
            ['question' => 'Should you use $.ajaxSetup()?', 'options' => ['Always', 'Rarely, can cause side effects', 'For all requests', 'Required'], 'correct' => 1],
            ['question' => 'What is progressive enhancement with jQuery?', 'options' => ['Gradual loading', 'Adding JS on top of working HTML', 'Progressive web app', 'Enhancement plugins'], 'correct' => 1],
            ['question' => 'What is unobtrusive JavaScript?', 'options' => ['Hidden JS', 'Separating behavior from markup', 'Quiet execution', 'Background scripts'], 'correct' => 1],
            ['question' => 'What performance tool integrates with jQuery?', 'options' => ['Chrome DevTools', 'jQuery Debug', 'Firebug', 'All of above'], 'correct' => 3],
            ['question' => 'Does jQuery 3.x support IE8?', 'options' => ['Yes', 'No', 'With polyfills', 'Optional'], 'correct' => 1],
            ['question' => 'What jQuery version supports IE6-8?', 'options' => ['3.x', '2.x', '1.x (1.12)', '4.x'], 'correct' => 2],
            ['question' => 'What is Slim build of jQuery?', 'options' => ['Minified', 'Excludes AJAX and effects', 'Compressed', 'Mobile version'], 'correct' => 1],
        ]
    ],
    [
        'label' => 'Expert',
        'questions' => [
            ['question' => 'What is Sizzle\'s tokenize function for?', 'options' => ['Security tokens', 'Breaking selector into tokens', 'Authentication', 'Parsing JSON'], 'correct' => 1],
            ['question' => 'What does Sizzle compile function do?', 'options' => ['Compiles JS', 'Creates matcher function from selector', 'Optimizes code', 'Minifies CSS'], 'correct' => 1],
            ['question' => 'What does Sizzle select function do?', 'options' => ['Selects elements', 'Main entry point for selection', 'Chooses method', 'Picks algorithm'], 'correct' => 1],
            ['question' => 'How does Sizzle parse CSS selectors?', 'options' => ['Regex patterns', 'Tokenization and compilation', 'Built-in parser', 'DOM API'], 'correct' => 1],
            ['question' => 'How are pseudo-classes implemented in Sizzle?', 'options' => ['Native CSS', 'Custom filter functions', 'DOM methods', 'Browser API'], 'correct' => 1],
            ['question' => 'When does jQuery use qSA?', 'options' => ['Always', 'When selector is qSA-compatible', 'Never', 'Only modern browsers'], 'correct' => 1],
            ['question' => 'When does jQuery fall back to Sizzle?', 'options' => ['Never', 'Complex selectors or old browsers', 'Always', 'On error'], 'correct' => 1],
            ['question' => 'What is jQuery\'s event handlers object?', 'options' => ['Event map', 'Internal structure storing handlers', 'Global registry', 'DOM property'], 'correct' => 1],
            ['question' => 'What is delegateCount in jQuery events?', 'options' => ['Number of delegates', 'Count of delegated handlers', 'Event counter', 'Handler limit'], 'correct' => 1],
            ['question' => 'What is $.event.special?', 'options' => ['Special events', 'Custom event behavior definitions', 'Event types', 'Priority events'], 'correct' => 1],
            ['question' => 'How do you create custom special event?', 'options' => ['$.createEvent()', '$.event.special.eventName = {}', '$.addEvent()', 'new $.Event()'], 'correct' => 1],
            ['question' => 'What is fx.queue in jQuery?', 'options' => ['Effect queue', 'Animation queue name', 'FX engine', 'Queue object'], 'correct' => 1],
            ['question' => 'What is fx.interval?', 'options' => ['Time interval', 'Animation frame rate (deprecated)', 'Delay between effects', 'Timer ID'], 'correct' => 1],
            ['question' => 'Does jQuery use requestAnimationFrame?', 'options' => ['No', 'Yes, in modern versions', 'Only in plugins', 'Optional'], 'correct' => 1],
            ['question' => 'What are deferred promise states?', 'options' => ['open/closed', 'pending/resolved/rejected', 'waiting/done', 'idle/active'], 'correct' => 1],
            ['question' => 'How are deferred callbacks stored?', 'options' => ['Single array', 'Multiple arrays for different states', 'Object map', 'Linked list'], 'correct' => 1],
            ['question' => 'What build tool does jQuery use?', 'options' => ['Webpack', 'Grunt', 'Gulp', 'Rollup'], 'correct' => 1],
            ['question' => 'Can you exclude modules in jQuery build?', 'options' => ['No', 'Yes, custom builds possible', 'Only core', 'Only effects'], 'correct' => 1],
            ['question' => 'What modules can be excluded?', 'options' => ['None', 'AJAX, effects, deprecated, etc.', 'Only old features', 'Everything'], 'correct' => 1],
            ['question' => 'How do you profile jQuery performance?', 'options' => ['$.profile()', 'Browser DevTools timeline', 'jQuery Profiler', 'Performance API'], 'correct' => 1],
            ['question' => 'Is jQuery faster than React for DOM updates?', 'options' => ['Yes', 'No, especially for frequent updates', 'Same speed', 'Depends on browser'], 'correct' => 1],
            ['question' => 'Why is React often faster?', 'options' => ['Better code', 'Virtual DOM diffing', 'Newer technology', 'Compilation'], 'correct' => 1],
            ['question' => 'What causes memory leaks with jQuery events?', 'options' => ['Too many events', 'Not unbinding handlers on remove', 'Large handlers', 'Event bubbling'], 'correct' => 1],
            ['question' => 'What are circular references in jQuery?', 'options' => ['Loops', 'Object references preventing garbage collection', 'Recursive calls', 'Event cycles'], 'correct' => 1],
            ['question' => 'Why are detached DOM nodes a leak risk?', 'options' => ['Memory waste', 'Held in memory with attached data/events', 'Slow performance', 'Browser bug'], 'correct' => 1],
            ['question' => 'What is $.ajaxPrefilter() for?', 'options' => ['Filtering results', 'Modifying AJAX options before request', 'Preprocessing data', 'Validating requests'], 'correct' => 1],
            ['question' => 'What is $.ajaxTransport() for?', 'options' => ['Data transport', 'Creating custom AJAX transport', 'Sending data', 'Protocol handler'], 'correct' => 1],
            ['question' => 'Should you use $.ajaxSetup() globally?', 'options' => ['Yes', 'No, avoid side effects', 'Only once', 'For defaults only'], 'correct' => 1],
            ['question' => 'What is jsonpCallback in JSONP?', 'options' => ['Callback name', 'Security feature', 'Data type', 'Response handler'], 'correct' => 0],
            ['question' => 'What security issue exists with JSONP?', 'options' => ['None', 'Arbitrary code execution from untrusted sources', 'XSS only', 'CSRF only'], 'correct' => 1],
            ['question' => 'What XSS vector exists in .html()?', 'options' => ['None', 'Inserting untrusted HTML with scripts', 'CSS injection', 'SQL injection'], 'correct' => 1],
            ['question' => 'How do you safely insert user content?', 'options' => ['.html()', '.text() or sanitize HTML', '.append()', '.prepend()'], 'correct' => 1],
            ['question' => 'What is jQuery\'s data cache?', 'options' => ['localStorage', 'Internal object storing element data', 'Browser cache', 'Session storage'], 'correct' => 1],
            ['question' => 'How do you clear jQuery data cache?', 'options' => ['.clear()', '.removeData()', '.clearCache()', '.clean()'], 'correct' => 1],
            ['question' => 'What happens to data when element removed?', 'options' => ['Persists', 'Cleaned with .remove() but not with .detach()', 'Always persists', 'Always removed'], 'correct' => 1],
            ['question' => 'Can you inspect jQuery internals in console?', 'options' => ['No', 'Yes, via jQuery.cache, etc.', 'Only in dev mode', 'Only with plugin'], 'correct' => 1],
            ['question' => 'What is jQuery.fn.jquery property?', 'options' => ['jQuery function', 'jQuery version string', 'Library object', 'Namespace'], 'correct' => 1],
            ['question' => 'How do you check jQuery version?', 'options' => ['$.version', '$.fn.jquery or jQuery.fn.jquery', '$.getVersion()', 'jQuery.version'], 'correct' => 1],
            ['question' => 'What is jQuery.noConflict(true)?', 'options' => ['Full conflict mode', 'Releases both $ and jQuery', 'Strict mode', 'Error mode'], 'correct' => 1],
            ['question' => 'How do you use jQuery in noConflict?', 'options' => ['Cannot use', 'Assign to custom variable', 'jQuery only', 'Restore later'], 'correct' => 1],
            ['question' => 'What is jQuery.support deprecated for?', 'options' => ['Feature detection', 'Use Modernizr or direct feature tests', 'Browser detection', 'Compatibility'], 'correct' => 1],
            ['question' => 'What changed in jQuery 3.0 promises?', 'options' => ['Nothing', 'Aligned with Promises/A+', 'Removed', 'Deprecated'], 'correct' => 1],
            ['question' => 'What is jQuery.Deferred.exceptionHook?', 'options' => ['Error handler', 'Hook for unhandled rejections', 'Exception catcher', 'Debug tool'], 'correct' => 1],
            ['question' => 'Does jQuery support ES6 modules?', 'options' => ['Yes, natively', 'Via build tools', 'No', 'Only in 4.x'], 'correct' => 1],
            ['question' => 'Can you tree-shake jQuery?', 'options' => ['Yes, easily', 'No, not designed for it', 'Only custom builds', 'With plugins'], 'correct' => 1],
            ['question' => 'What is jQuery.ready promise?', 'options' => ['Ready state', 'Promise that resolves when DOM ready', 'Load promise', 'Init promise'], 'correct' => 1],
            ['question' => 'What is jQuery.holdReady()?', 'options' => ['Pauses execution', 'Delays ready event', 'Holds requests', 'Waits for condition'], 'correct' => 1],
            ['question' => 'Is jQuery.holdReady() deprecated?', 'options' => ['No', 'Yes', 'Only in 3.x', 'Not yet'], 'correct' => 1],
            ['question' => 'What is the future of jQuery?', 'options' => ['Obsolete', 'Maintained but less central', 'Growing', 'Uncertain'], 'correct' => 1],
            ['question' => 'Should new developers learn jQuery?', 'options' => ['Yes, first', 'Learn vanilla JS first, jQuery for legacy', 'No, never', 'Only jQuery'], 'correct' => 1],
        ]
    ],
];
require_once __DIR__ . '/quiz-engine.php';
