<?php
$page_title = 'MongoDB Quiz – 100 Levels – CodeFoundry';
$active_page = 'training';
$quiz_title  = 'MongoDB';
$quiz_slug   = 'mongodb';
$quiz_tiers  = [
    [
        'label' => 'Introduction',
        'questions' => [
            ['question' => 'What type of database is MongoDB?', 'options' => ['Relational', 'NoSQL document database', 'Graph database', 'Key-value store'], 'correct' => 1],
            ['question' => 'What is the basic unit of data storage in MongoDB?', 'options' => ['Row', 'Table', 'Document', 'Record'], 'correct' => 2],
            ['question' => 'What format does MongoDB use to store documents internally?', 'options' => ['JSON', 'XML', 'BSON', 'CSV'], 'correct' => 2],
            ['question' => 'What is a collection in MongoDB?', 'options' => ['A single record', 'A group of documents', 'A database schema', 'An index file'], 'correct' => 1],
            ['question' => 'How does MongoDB differ from a relational database like MySQL?', 'options' => ['MongoDB uses tables and rows', 'MongoDB requires a fixed schema', 'MongoDB stores data as flexible documents instead of rows', 'MongoDB does not support queries'], 'correct' => 2],
            ['question' => 'What is the MongoDB shell tool called?', 'options' => ['mongoterm', 'mongosh', 'mongocli', 'mshell'], 'correct' => 1],
            ['question' => 'Which command inserts a single document into a collection?', 'options' => ['db.collection.insert()', 'db.collection.insertOne()', 'db.collection.add()', 'db.collection.create()'], 'correct' => 1],
            ['question' => 'Which command retrieves a single document from a collection?', 'options' => ['db.collection.getOne()', 'db.collection.findOne()', 'db.collection.fetchOne()', 'db.collection.selectOne()'], 'correct' => 1],
            ['question' => 'Which command updates a single matching document?', 'options' => ['db.collection.update()', 'db.collection.updateOne()', 'db.collection.modify()', 'db.collection.set()'], 'correct' => 1],
            ['question' => 'Which command deletes a single matching document?', 'options' => ['db.collection.remove()', 'db.collection.drop()', 'db.collection.deleteOne()', 'db.collection.erase()'], 'correct' => 2],
            ['question' => 'What does BSON stand for?', 'options' => ['Basic Serialized Object Notation', 'Binary JSON', 'Byte Stored Object Notation', 'Binary Structured Object Notation'], 'correct' => 1],
            ['question' => 'What field does MongoDB automatically add to every document?', 'options' => ['_id', 'id', 'docId', 'mongoId'], 'correct' => 0],
            ['question' => 'What command lists all databases in mongosh?', 'options' => ['list databases', 'show dbs', 'db.list()', 'databases()'], 'correct' => 1],
            ['question' => 'What command shows all collections in the current database?', 'options' => ['list collections', 'show collections', 'db.list()', 'collections()'], 'correct' => 1],
            ['question' => 'How do you switch to a database called "shop" in mongosh?', 'options' => ['switch shop', 'open shop', 'use shop', 'connect shop'], 'correct' => 2],
            ['question' => 'In MongoDB, what is a database?', 'options' => ['A single document', 'A container for collections', 'A table of rows', 'A query language'], 'correct' => 1],
            ['question' => 'What does db.collection.find() return?', 'options' => ['A single document', 'A cursor to all matching documents', 'A count of documents', 'An array of IDs'], 'correct' => 1],
            ['question' => 'Which MongoDB data type represents a date?', 'options' => ['String', 'Date', 'Timestamp', 'DateTime'], 'correct' => 1],
            ['question' => 'What does the insertMany() method do?', 'options' => ['Updates many documents', 'Inserts an array of documents', 'Finds many documents', 'Deletes many documents'], 'correct' => 1],
            ['question' => 'What does the deleteMany() method do?', 'options' => ['Removes one document', 'Removes all documents matching a filter', 'Drops the collection', 'Clears the database'], 'correct' => 1],
            ['question' => 'What is the equivalent of a SQL table in MongoDB?', 'options' => ['Document', 'Field', 'Collection', 'Database'], 'correct' => 2],
            ['question' => 'What is the equivalent of a SQL row in MongoDB?', 'options' => ['Collection', 'Document', 'Field', 'Index'], 'correct' => 1],
            ['question' => 'Does MongoDB enforce a schema by default?', 'options' => ['Yes, always', 'No, documents in a collection can have different fields', 'Only with validation rules', 'Only in Atlas'], 'correct' => 1],
            ['question' => 'What does the updateOne() $set operator do?', 'options' => ['Replaces the whole document', 'Sets or updates specific field values', 'Deletes fields', 'Sets document ID'], 'correct' => 1],
            ['question' => 'Which command drops an entire collection?', 'options' => ['db.collection.delete()', 'db.collection.remove()', 'db.collection.drop()', 'db.collection.clear()'], 'correct' => 2],
        ],
    ],
    [
        'label' => 'Beginner',
        'questions' => [
            ['question' => 'What does the $eq operator do in a query filter?', 'options' => ['Matches values not equal to', 'Matches values equal to a specified value', 'Compares two fields', 'Checks existence'], 'correct' => 1],
            ['question' => 'What does the $gt operator match?', 'options' => ['Values less than', 'Values greater than', 'Values equal to', 'Values not equal to'], 'correct' => 1],
            ['question' => 'What does the $lt operator match?', 'options' => ['Values greater than', 'Values less than', 'Values equal to', 'Values greater than or equal to'], 'correct' => 1],
            ['question' => 'What does the $in operator do?', 'options' => ['Checks if field is inside a document', 'Matches any value in a specified array', 'Performs an inner join', 'Checks field existence'], 'correct' => 1],
            ['question' => 'How do you combine two conditions so both must be true?', 'options' => ['$or', '$not', '$and', '$nor'], 'correct' => 2],
            ['question' => 'How do you match documents where at least one of two conditions is true?', 'options' => ['$and', '$nor', '$not', '$or'], 'correct' => 3],
            ['question' => 'What is projection in a MongoDB find() query?', 'options' => ['Filtering which documents to return', 'Specifying which fields to include or exclude', 'Projecting aggregation results', 'Projecting indexes'], 'correct' => 1],
            ['question' => 'How do you sort results in descending order by the "price" field?', 'options' => ['sort({price: 0})', 'sort({price: -1})', 'sort({price: "desc"})', 'sort({price: false})'], 'correct' => 1],
            ['question' => 'What does the limit() method do?', 'options' => ['Limits document size', 'Limits the number of documents returned', 'Limits field count', 'Limits query time'], 'correct' => 1],
            ['question' => 'What does the skip() method do?', 'options' => ['Skips fields', 'Skips a specified number of documents', 'Skips indexes', 'Skips deleted documents'], 'correct' => 1],
            ['question' => 'What is an index in MongoDB?', 'options' => ['A document ID', 'A data structure that improves query performance', 'A collection list', 'A field name'], 'correct' => 1],
            ['question' => 'What type of index does MongoDB create on _id by default?', 'options' => ['Text index', 'Compound index', 'Unique index', 'Sparse index'], 'correct' => 2],
            ['question' => 'What is an ObjectId in MongoDB?', 'options' => ['A 12-byte unique identifier', 'A UUID string', 'A numeric auto-increment ID', 'A base64 encoded string'], 'correct' => 0],
            ['question' => 'What MongoDB data type stores whole numbers?', 'options' => ['Double', 'Decimal128', 'Int32 or Int64', 'Number'], 'correct' => 2],
            ['question' => 'How do you create a single-field ascending index on the "email" field?', 'options' => ['db.col.addIndex({email: 1})', 'db.col.createIndex({email: 1})', 'db.col.index({email: 1})', 'db.col.buildIndex({email: 1})'], 'correct' => 1],
            ['question' => 'What does the $gte operator match?', 'options' => ['Greater than', 'Less than or equal to', 'Greater than or equal to', 'Not equal'], 'correct' => 2],
            ['question' => 'What does the $ne operator match?', 'options' => ['Values equal to', 'Values not equal to', 'Values near equal', 'Null values'], 'correct' => 1],
            ['question' => 'What does the $exists operator check?', 'options' => ['If a value is null', 'If a field exists in a document', 'If a collection exists', 'If an index exists'], 'correct' => 1],
            ['question' => 'How do you count documents matching a filter?', 'options' => ['db.col.find(filter).size()', 'db.col.countDocuments(filter)', 'db.col.count(filter)', 'db.col.total(filter)'], 'correct' => 1],
            ['question' => 'What does updateMany() do?', 'options' => ['Updates the first matching document', 'Updates all documents matching a filter', 'Updates all documents in a collection', 'Updates schema'], 'correct' => 1],
            ['question' => 'What does the $unset operator do in an update?', 'options' => ['Sets a field to null', 'Removes a field from a document', 'Unsets the document ID', 'Resets a field to default'], 'correct' => 1],
            ['question' => 'What does the $inc operator do?', 'options' => ['Inserts a new document', 'Increments a numeric field by a given amount', 'Includes a field in projection', 'Increases index size'], 'correct' => 1],
            ['question' => 'What is the difference between find() and findOne()?', 'options' => ['No difference', 'find() returns a cursor; findOne() returns a single document', 'findOne() is faster only for large collections', 'find() only works with filters'], 'correct' => 1],
            ['question' => 'How do you exclude the _id field from query results?', 'options' => ['projection({_id: false})', '{_id: 0} in projection', '{_id: -1} in projection', 'hide(_id)'], 'correct' => 1],
            ['question' => 'What does db.collection.distinct() return?', 'options' => ['Sorted unique values of a field', 'An array of distinct values for a field', 'Distinct document count', 'First distinct document'], 'correct' => 1],
        ],
    ],
    [
        'label' => 'Intermediate',
        'questions' => [
            ['question' => 'What is the MongoDB aggregation pipeline?', 'options' => ['A query shortcut', 'A framework for data processing using sequential stages', 'A replication mechanism', 'A sharding strategy'], 'correct' => 1],
            ['question' => 'What does the $match stage do in aggregation?', 'options' => ['Joins collections', 'Filters documents based on conditions', 'Groups documents', 'Projects fields'], 'correct' => 1],
            ['question' => 'What does the $group stage do?', 'options' => ['Filters documents', 'Groups documents by a key and computes aggregations', 'Sorts documents', 'Joins two collections'], 'correct' => 1],
            ['question' => 'What does the $project stage do in aggregation?', 'options' => ['Projects future data', 'Reshapes documents by including, excluding, or adding fields', 'Creates projections for indexes', 'Projects sorted results'], 'correct' => 1],
            ['question' => 'What does the $sort stage do?', 'options' => ['Filters documents', 'Sorts documents by one or more fields', 'Groups results', 'Joins collections'], 'correct' => 1],
            ['question' => 'What does the $limit stage do in aggregation?', 'options' => ['Limits field count', 'Passes only the first N documents to the next stage', 'Limits pipeline depth', 'Limits document size'], 'correct' => 1],
            ['question' => 'What does the $lookup stage perform?', 'options' => ['Looks up a field value', 'A left outer join with another collection', 'Looks up an index', 'A union of two pipelines'], 'correct' => 1],
            ['question' => 'What does the $unwind stage do?', 'options' => ['Reverses a sort', 'Deconstructs an array field into separate documents', 'Ungroups aggregated data', 'Removes nesting'], 'correct' => 1],
            ['question' => 'What is an embedded document in MongoDB?', 'options' => ['A document stored in GridFS', 'A document nested inside another document', 'A document template', 'A read-only document'], 'correct' => 1],
            ['question' => 'What is the maximum document size in MongoDB?', 'options' => ['1 MB', '4 MB', '16 MB', '64 MB'], 'correct' => 2],
            ['question' => 'How do you query a field inside an embedded document?', 'options' => ['Using nested find()', 'Using dot notation (e.g., "address.city")', 'Using $embed operator', 'Using $nested operator'], 'correct' => 1],
            ['question' => 'How do you query for documents where an array field contains a specific value?', 'options' => ['Use $contains', 'Simply match the value in the filter (e.g., {tags: "mongodb"})', 'Use $arrayMatch', 'Use $elemIn'], 'correct' => 1],
            ['question' => 'What does $elemMatch do?', 'options' => ['Matches a single element in a nested document', 'Matches documents where an array element meets all specified criteria', 'Matches element count', 'Matches array length'], 'correct' => 1],
            ['question' => 'What does the $push operator do in an update?', 'options' => ['Pushes a new document', 'Appends a value to an array field', 'Pushes data to Atlas', 'Pushes data to replication'], 'correct' => 1],
            ['question' => 'What does the $pull operator do?', 'options' => ['Pulls data from Atlas', 'Removes matching values from an array field', 'Pulls a document', 'Fetches from replica'], 'correct' => 1],
            ['question' => 'What is denormalization in MongoDB schema design?', 'options' => ['Removing indexes', 'Embedding related data together to reduce joins', 'Normalizing field names', 'Breaking collections apart'], 'correct' => 1],
            ['question' => 'What is the $sum accumulator used for in $group?', 'options' => ['Counts distinct values', 'Computes the sum of numeric values', 'Sums array lengths', 'Summarizes text'], 'correct' => 1],
            ['question' => 'What is the $avg accumulator used for?', 'options' => ['Gets the maximum value', 'Computes the average of numeric values', 'Averages string lengths', 'Gets median value'], 'correct' => 1],
            ['question' => 'How do you reference the current document value in aggregation expressions?', 'options' => ['Using @fieldName', 'Using $fieldName', 'Using #fieldName', 'Using this.fieldName'], 'correct' => 1],
            ['question' => 'What does the $addToSet accumulator do in $group?', 'options' => ['Adds a new document to a set', 'Adds unique values to an array', 'Creates a new collection', 'Adds fields to schema'], 'correct' => 1],
            ['question' => 'What is a "reference" relationship in MongoDB schema design?', 'options' => ['Embedding documents', 'Storing the _id of a related document in another collection', 'A foreign key constraint', 'A virtual reference'], 'correct' => 1],
            ['question' => 'What does the $count stage do in aggregation?', 'options' => ['Counts fields', 'Returns the count of documents as a field', 'Counts array elements', 'Counts pipelines'], 'correct' => 1],
            ['question' => 'What does the $first accumulator return?', 'options' => ['First document in the collection', 'First value encountered in a group', 'First field in a document', 'First index entry'], 'correct' => 1],
            ['question' => 'What is the purpose of the $skip stage?', 'options' => ['Skips invalid documents', 'Skips the first N documents in the pipeline', 'Skips empty fields', 'Skips null values'], 'correct' => 1],
            ['question' => 'Which aggregation stage can add entirely new computed fields to documents?', 'options' => ['$match', '$addFields', '$group', '$lookup'], 'correct' => 1],
        ],
    ],
    [
        'label' => 'Advanced',
        'questions' => [
            ['question' => 'What is a compound index?', 'options' => ['An index on nested documents', 'An index on multiple fields', 'A combination of text and geo indexes', 'An index with custom collation'], 'correct' => 1],
            ['question' => 'What is a text index used for?', 'options' => ['Indexing all string fields', 'Full-text search on string content', 'Indexing by text length', 'Storing text documents'], 'correct' => 1],
            ['question' => 'What is a TTL index?', 'options' => ['An index on time fields', 'An index that automatically deletes documents after a specified time', 'A time-to-load index', 'A temporary index'], 'correct' => 1],
            ['question' => 'What is a geospatial index used for?', 'options' => ['Indexing geographic country codes', 'Querying documents based on location coordinates', 'Storing map images', 'Geo-replication indexing'], 'correct' => 1],
            ['question' => 'What does explain() do in MongoDB?', 'options' => ['Explains the document schema', 'Returns information about query execution plan and performance', 'Explains aggregation results', 'Shows collection statistics'], 'correct' => 1],
            ['question' => 'What does the executionStats mode of explain() provide?', 'options' => ['Index statistics', 'Actual runtime statistics such as documents examined and time', 'Schema explanation', 'Replication stats'], 'correct' => 1],
            ['question' => 'What are MongoDB transactions used for?', 'options' => ['Transferring data between databases', 'Ensuring atomicity across multiple operations on multiple documents', 'Transaction logs', 'Billing operations'], 'correct' => 1],
            ['question' => 'What is a replica set in MongoDB?', 'options' => ['A set of indexes', 'A group of MongoDB instances maintaining the same data for redundancy', 'A replica of a collection', 'A backup set'], 'correct' => 1],
            ['question' => 'In a replica set, what is the primary node?', 'options' => ['The fastest node', 'The node that accepts all write operations', 'The first node created', 'The node with most storage'], 'correct' => 1],
            ['question' => 'What is MongoDB sharding?', 'options' => ['Splitting documents into pieces', 'Distributing data across multiple machines for horizontal scaling', 'Creating sharded indexes', 'Partitioning a collection by time'], 'correct' => 1],
            ['question' => 'What is a shard key?', 'options' => ['An encryption key', 'The field used to distribute documents across shards', 'A unique index', 'A replication key'], 'correct' => 1],
            ['question' => 'What are change streams in MongoDB?', 'options' => ['Streaming aggregation results', 'Real-time event notifications for data changes', 'Log streaming', 'Change log files'], 'correct' => 1],
            ['question' => 'What is GridFS in MongoDB?', 'options' => ['A grid layout system', 'A specification for storing large files exceeding the 16 MB document limit', 'A geospatial file system', 'A distributed file grid'], 'correct' => 1],
            ['question' => 'What does a "covered query" mean?', 'options' => ['A query covered by a transaction', 'A query satisfied entirely by an index without reading documents', 'A query with full text coverage', 'A query covered by a replica'], 'correct' => 1],
            ['question' => 'What does the hint() method do in a query?', 'options' => ['Provides a hint to the user', 'Forces the query to use a specific index', 'Hints at the query plan', 'Optimizes aggregation'], 'correct' => 1],
            ['question' => 'What is an upsert in MongoDB?', 'options' => ['An update that fails if no match found', 'An update that inserts a new document if no match is found', 'An upward sort operation', 'An update with set operations'], 'correct' => 1],
            ['question' => 'What is the mongos process in a sharded cluster?', 'options' => ['A secondary node', 'A query router that routes client requests to appropriate shards', 'A monitoring service', 'A shard manager'], 'correct' => 1],
            ['question' => 'What is the config server in a sharded cluster?', 'options' => ['A configuration file server', 'A replica set that stores sharding metadata', 'A primary node configuration', 'A load balancer'], 'correct' => 1],
            ['question' => 'What does the $out stage do in an aggregation pipeline?', 'options' => ['Outputs results to the console', 'Writes aggregation results to a specified collection', 'Exits the pipeline', 'Outputs to a file'], 'correct' => 1],
            ['question' => 'What does the $merge stage do?', 'options' => ['Merges two pipelines', 'Merges aggregation results into a collection (updating or inserting)', 'Merges replica sets', 'Merges indexes'], 'correct' => 1],
            ['question' => 'What is a partial index?', 'options' => ['An incomplete index', 'An index that only indexes documents meeting a specified filter', 'An index on partial field values', 'A sparse index variant'], 'correct' => 1],
            ['question' => 'What is a sparse index?', 'options' => ['An index with gaps', 'An index that only includes documents where the indexed field exists', 'An index on arrays', 'A low-density index'], 'correct' => 1],
            ['question' => 'What does the $bucket stage do in aggregation?', 'options' => ['Stores documents in buckets', 'Categorizes documents into user-defined ranges', 'Buckets data by time', 'Creates histogram data'], 'correct' => 1],
            ['question' => 'What is the purpose of the oplog in MongoDB?', 'options' => ['Operation logging for debugging', 'A capped collection recording all write operations for replication', 'An optional audit log', 'An operational metadata store'], 'correct' => 1],
            ['question' => 'What does the findOneAndUpdate() method return by default?', 'options' => ['The updated document', 'The document before the update', 'A boolean', 'The update result object'], 'correct' => 1],
        ],
    ],
    [
        'label' => 'Expert',
        'questions' => [
            ['question' => 'What is the WiredTiger storage engine?', 'options' => ['An in-memory engine', 'MongoDB\'s default storage engine supporting document-level concurrency and compression', 'A third-party plugin', 'An SSD-optimized engine'], 'correct' => 1],
            ['question' => 'What is a write concern in MongoDB?', 'options' => ['A write queue', 'The level of acknowledgment requested from MongoDB for write operations', 'A write lock mechanism', 'A write permission level'], 'correct' => 1],
            ['question' => 'What does write concern {w: "majority"} guarantee?', 'options' => ['Writes are acknowledged by any node', 'Writes are acknowledged by a majority of replica set members', 'Writes are logged to disk', 'Writes are committed to all nodes'], 'correct' => 1],
            ['question' => 'What is a read concern in MongoDB?', 'options' => ['Read permissions', 'The isolation level for read operations', 'Read queue priority', 'Read replica preference'], 'correct' => 1],
            ['question' => 'What does read concern "linearizable" provide?', 'options' => ['Linear performance', 'Guarantees reading the most recent committed data reflected by a majority of nodes', 'Linear sort order', 'Linearized query plans'], 'correct' => 1],
            ['question' => 'What is MongoDB Atlas?', 'options' => ['A local MongoDB GUI', 'MongoDB\'s fully managed cloud database service', 'A mapping/geospatial tool', 'An Atlas of MongoDB commands'], 'correct' => 1],
            ['question' => 'How does WiredTiger handle concurrency?', 'options' => ['Global write lock', 'Document-level locking with MVCC (multi-version concurrency control)', 'Collection-level locking only', 'Thread-level locking'], 'correct' => 1],
            ['question' => 'What is schema validation in MongoDB?', 'options' => ['Automatic schema inference', 'Rules that enforce document structure using JSON Schema or query operators', 'A GUI validation tool', 'Import/export validation'], 'correct' => 1],
            ['question' => 'What is a time series collection in MongoDB?', 'options' => ['A collection sorted by time', 'A collection optimized for storing and querying time-series data with automatic bucketing', 'A collection with TTL index', 'A log collection'], 'correct' => 1],
            ['question' => 'What is the aggregation pipeline optimization technique of "pipeline pushdown"?', 'options' => ['Pushing data down to shards', 'Moving $match and $sort stages early in the pipeline to use indexes', 'Pushing aggregation to Atlas', 'Compressing pipeline stages'], 'correct' => 1],
            ['question' => 'What does TLS/SSL provide in MongoDB?', 'options' => ['Faster queries', 'Encrypted communication between clients and the MongoDB server', 'Token-based login', 'Two-level storage'], 'correct' => 1],
            ['question' => 'What is MongoDB\'s SCRAM authentication mechanism?', 'options' => ['A schema-based auth', 'Salted Challenge Response Authentication Mechanism, the default auth protocol', 'Simple Credential Resource Access Method', 'A script-based auth'], 'correct' => 1],
            ['question' => 'What is role-based access control (RBAC) in MongoDB?', 'options' => ['Row-based access control', 'Granting users roles that define their privileges on databases and collections', 'Read-based access control', 'Remote-based access control'], 'correct' => 1],
            ['question' => 'What does the explain() "allPlansExecution" verbosity show?', 'options' => ['Results of all queries', 'Stats for the winning plan and rejected candidate plans', 'All plan files', 'All collection scans'], 'correct' => 1],
            ['question' => 'What is index intersection in MongoDB?', 'options' => ['Two indexes on the same field', 'Using multiple indexes together to satisfy a query', 'Overlapping index ranges', 'Combined text indexes'], 'correct' => 1],
            ['question' => 'What is a zone in MongoDB sharding?', 'options' => ['A geographic region', 'A mapping of a shard key range to specific shards for data locality', 'A network zone', 'A security zone'], 'correct' => 1],
            ['question' => 'What does the $facet stage do in aggregation?', 'options' => ['Creates faceted search UI', 'Runs multiple aggregation pipelines in parallel within a single stage', 'Groups by multiple fields', 'Creates search facets'], 'correct' => 1],
            ['question' => 'What is a capped collection in MongoDB?', 'options' => ['A collection with a field cap', 'A fixed-size collection that overwrites the oldest documents when full', 'A collection with a document count limit', 'A read-only collection'], 'correct' => 1],
            ['question' => 'What is the purpose of the mongodump tool?', 'options' => ['Dumps query results', 'Creates a binary export of a MongoDB database', 'Dumps logs', 'Dumps aggregation results'], 'correct' => 1],
            ['question' => 'What is the difference between $toDate and ISODate() in MongoDB?', 'options' => ['No difference', '$toDate is an aggregation expression; ISODate() is a mongosh helper constructor', '$toDate is for Atlas only', '$toDate requires a schema'], 'correct' => 1],
            ['question' => 'What does the $graphLookup stage do?', 'options' => ['Creates graph visualizations', 'Performs recursive searches on a collection for graph-like data', 'Builds a graph index', 'Looks up GraphQL schemas'], 'correct' => 1],
            ['question' => 'What is Atlas Search in MongoDB Atlas?', 'options' => ['A basic find() wrapper', 'A full-text search engine built on Apache Lucene, integrated with MongoDB Atlas', 'A geospatial search tool', 'A metadata search service'], 'correct' => 1],
            ['question' => 'What does the $setWindowFields stage do?', 'options' => ['Sets field visibility windows', 'Performs window function calculations over a sequence of documents', 'Sets time windows for TTL', 'Configures data windows for shards'], 'correct' => 1],
            ['question' => 'What is the purpose of readPreference in MongoDB?', 'options' => ['Preferred field ordering', 'Determines which replica set member serves read operations', 'Read cache preference', 'Read consistency preference'], 'correct' => 1],
            ['question' => 'What is the MongoDB Stable API (Versioned API)?', 'options' => ['A stable connection protocol', 'An API that guarantees behavior of specified commands across MongoDB versions', 'A stable schema API', 'A versioned REST API'], 'correct' => 1],
        ],
    ],
];
require_once __DIR__ . '/quiz-engine.php';
