<?php
$page_title = 'MySQL Quiz – 100 Levels – CodeFoundry';
$active_page = 'training';
$quiz_title  = 'MySQL';
$quiz_slug   = 'mysql';
$quiz_tiers  = [
    ['label' => 'Introduction', 'questions' => [
        ['question' => 'What is MySQL?', 'options' => ['A programming language', 'A relational database management system', 'A web server', 'An operating system'], 'correct' => 1],
        ['question' => 'What is the difference between MySQL and SQL?', 'options' => ['No difference', 'MySQL is DBMS, SQL is language', 'MySQL is newer', 'SQL is deprecated'], 'correct' => 1],
        ['question' => 'What tool is the MySQL command-line interface?', 'options' => ['MySQL Shell', 'MySQL CLI', 'Both mysql command and Workbench', 'PhpMyAdmin'], 'correct' => 2],
        ['question' => 'How do you create a database?', 'options' => ['CREATE DATABASE dbname', 'NEW DATABASE dbname', 'MAKE DATABASE dbname', 'ADD DATABASE dbname'], 'correct' => 0],
        ['question' => 'How do you select a database to use?', 'options' => ['SELECT dbname', 'USE dbname', 'OPEN dbname', 'CONNECT dbname'], 'correct' => 1],
        ['question' => 'How do you list all databases?', 'options' => ['LIST DATABASES', 'SHOW DATABASES', 'GET DATABASES', 'SELECT DATABASES'], 'correct' => 1],
        ['question' => 'How do you list all tables?', 'options' => ['LIST TABLES', 'SHOW TABLES', 'GET TABLES', 'SELECT TABLES'], 'correct' => 1],
        ['question' => 'How do you show table structure?', 'options' => ['STRUCTURE table', 'SHOW COLUMNS FROM table', 'INFO table', 'DESCRIBE table'], 'correct' => 3],
        ['question' => 'What data type stores integers?', 'options' => ['VARCHAR', 'INT', 'TEXT', 'DECIMAL'], 'correct' => 1],
        ['question' => 'What data type stores variable-length strings?', 'options' => ['CHAR', 'VARCHAR', 'TEXT', 'STRING'], 'correct' => 1],
        ['question' => 'What data type stores large text?', 'options' => ['VARCHAR', 'STRING', 'TEXT', 'BLOB'], 'correct' => 2],
        ['question' => 'What data type stores dates?', 'options' => ['DATE', 'DATETIME', 'TIMESTAMP', 'TIME'], 'correct' => 0],
        ['question' => 'What data type stores decimals?', 'options' => ['INT', 'FLOAT', 'DECIMAL', 'DOUBLE'], 'correct' => 2],
        ['question' => 'What data type stores true/false?', 'options' => ['BOOL', 'BOOLEAN', 'TINYINT(1)', 'All of the above'], 'correct' => 3],
        ['question' => 'How do you insert data?', 'options' => ['INSERT INTO table VALUES', 'ADD TO table', 'PUT INTO table', 'APPEND table'], 'correct' => 0],
        ['question' => 'How do you select all columns?', 'options' => ['SELECT ALL FROM table', 'SELECT * FROM table', 'GET * FROM table', 'FETCH * FROM table'], 'correct' => 1],
        ['question' => 'How do you filter rows?', 'options' => ['FILTER column = value', 'WHERE column = value', 'HAVING column = value', 'IF column = value'], 'correct' => 1],
        ['question' => 'How do you sort results ascending?', 'options' => ['ORDER BY column ASC', 'SORT BY column', 'ARRANGE column', 'ASCENDING column'], 'correct' => 0],
        ['question' => 'How do you sort descending?', 'options' => ['ORDER BY column DESC', 'SORT BY column DESC', 'REVERSE ORDER column', 'DESCENDING column'], 'correct' => 0],
        ['question' => 'How do you limit results?', 'options' => ['TOP 10', 'LIMIT 10', 'FETCH 10', 'MAX 10'], 'correct' => 1],
        ['question' => 'How do you update data?', 'options' => ['UPDATE table SET column = value', 'CHANGE table column = value', 'MODIFY table column = value', 'ALTER table column = value'], 'correct' => 0],
        ['question' => 'How do you delete data?', 'options' => ['REMOVE FROM table', 'DELETE FROM table', 'DROP FROM table', 'CLEAR table'], 'correct' => 1],
        ['question' => 'How do you delete a table?', 'options' => ['DELETE TABLE table', 'DROP TABLE table', 'REMOVE TABLE table', 'CLEAR TABLE table'], 'correct' => 1],
        ['question' => 'How do you delete a database?', 'options' => ['DELETE DATABASE db', 'DROP DATABASE db', 'REMOVE DATABASE db', 'CLEAR DATABASE db'], 'correct' => 1],
        ['question' => 'What defines a primary key?', 'options' => ['UNIQUE KEY', 'PRIMARY KEY', 'MAIN KEY', 'ID KEY'], 'correct' => 1],
        ['question' => 'What makes a column auto-increment?', 'options' => ['AUTO_INCREMENT', 'INCREMENT', 'AUTO_ID', 'SERIAL'], 'correct' => 0],
        ['question' => 'What constraint prevents NULL values?', 'options' => ['NO NULL', 'NOT NULL', 'REQUIRED', 'MANDATORY'], 'correct' => 1],
        ['question' => 'How do you set a default value?', 'options' => ['VALUE default', 'DEFAULT value', 'SET value', 'INITIAL value'], 'correct' => 1],
        ['question' => 'What is the default MySQL port?', 'options' => ['8080', '3306', '5432', '3000'], 'correct' => 1],
        ['question' => 'What is the MySQL root user?', 'options' => ['Admin user', 'Default superuser', 'Regular user', 'Guest user'], 'correct' => 1],
    ]],
    ['label' => 'Beginner', 'questions' => [
        ['question' => 'What is TINYINT range?', 'options' => ['-127 to 127', '-128 to 127', '0 to 255', 'Both signed and unsigned'], 'correct' => 3],
        ['question' => 'What is the largest integer type?', 'options' => ['INT', 'MEDIUMINT', 'BIGINT', 'LARGEINT'], 'correct' => 2],
        ['question' => 'What is the difference between FLOAT and DOUBLE?', 'options' => ['No difference', 'DOUBLE has more precision', 'FLOAT is faster', 'DOUBLE is deprecated'], 'correct' => 1],
        ['question' => 'What is the difference between CHAR and VARCHAR?', 'options' => ['No difference', 'CHAR is fixed-length, VARCHAR is variable', 'VARCHAR is faster', 'CHAR is deprecated'], 'correct' => 1],
        ['question' => 'What is TEXT used for?', 'options' => ['Small strings', 'Large text data', 'Numbers', 'Dates'], 'correct' => 1],
        ['question' => 'What is BLOB used for?', 'options' => ['Text', 'Binary data', 'Numbers', 'Dates'], 'correct' => 1],
        ['question' => 'What does DATETIME store?', 'options' => ['Date only', 'Date and time', 'Time only', 'Timestamp'], 'correct' => 1],
        ['question' => 'What does TIMESTAMP store?', 'options' => ['Date only', 'Unix timestamp', 'Time only', 'Year only'], 'correct' => 1],
        ['question' => 'What is ENUM?', 'options' => ['Number type', 'String with predefined values', 'Date type', 'Boolean'], 'correct' => 1],
        ['question' => 'What is SET type?', 'options' => ['Single value', 'Multiple values from list', 'Unique values', 'Array'], 'correct' => 1],
        ['question' => 'What is an INNER JOIN?', 'options' => ['All rows', 'Matching rows from both tables', 'Left table rows', 'Right table rows'], 'correct' => 1],
        ['question' => 'What is a LEFT JOIN?', 'options' => ['Right table rows', 'All left table rows + matches', 'Matching rows', 'All rows'], 'correct' => 1],
        ['question' => 'What is a RIGHT JOIN?', 'options' => ['Left table rows', 'All right table rows + matches', 'Matching rows', 'All rows'], 'correct' => 1],
        ['question' => 'What does UNION do?', 'options' => ['Joins tables', 'Combines result sets', 'Merges columns', 'Groups rows'], 'correct' => 1],
        ['question' => 'What is the difference between UNION and UNION ALL?', 'options' => ['No difference', 'UNION removes duplicates', 'UNION ALL is slower', 'UNION is deprecated'], 'correct' => 1],
        ['question' => 'What is a subquery?', 'options' => ['Main query', 'Query inside another query', 'Fast query', 'Optimized query'], 'correct' => 1],
        ['question' => 'What does GROUP BY do?', 'options' => ['Sorts rows', 'Groups rows by column', 'Filters rows', 'Joins tables'], 'correct' => 1],
        ['question' => 'What does HAVING do?', 'options' => ['Filters rows', 'Filters groups', 'Sorts groups', 'Creates groups'], 'correct' => 1],
        ['question' => 'What does COUNT() do?', 'options' => ['Sums values', 'Counts rows', 'Averages values', 'Finds max'], 'correct' => 1],
        ['question' => 'What does SUM() do?', 'options' => ['Counts rows', 'Sums values', 'Averages values', 'Multiplies values'], 'correct' => 1],
        ['question' => 'What does AVG() do?', 'options' => ['Sums values', 'Averages values', 'Counts values', 'Finds median'], 'correct' => 1],
        ['question' => 'What does MIN() do?', 'options' => ['Maximum value', 'Minimum value', 'Average value', 'Sum of values'], 'correct' => 1],
        ['question' => 'What does MAX() do?', 'options' => ['Minimum value', 'Maximum value', 'Average value', 'Sum of values'], 'correct' => 1],
        ['question' => 'What does DISTINCT do?', 'options' => ['Sorts rows', 'Removes duplicates', 'Groups rows', 'Counts rows'], 'correct' => 1],
        ['question' => 'How do you use column aliases?', 'options' => ['column NAME alias', 'column AS alias', 'column : alias', 'column => alias'], 'correct' => 1],
        ['question' => 'How do you check for NULL?', 'options' => ['column = NULL', 'column IS NULL', 'column == NULL', 'NULL(column)'], 'correct' => 1],
        ['question' => 'How do you check for NOT NULL?', 'options' => ['column != NULL', 'column IS NOT NULL', 'column <> NULL', 'NOT NULL(column)'], 'correct' => 1],
        ['question' => 'What does IFNULL() do?', 'options' => ['Checks NULL', 'Returns alternative if NULL', 'Removes NULL', 'Creates NULL'], 'correct' => 1],
        ['question' => 'What does COALESCE() do?', 'options' => ['Checks NULL', 'Returns first non-NULL value', 'Removes NULL', 'Counts NULL'], 'correct' => 1],
        ['question' => 'What does CONCAT() do?', 'options' => ['Splits strings', 'Joins strings', 'Trims strings', 'Converts strings'], 'correct' => 1],
        ['question' => 'What does SUBSTRING() do?', 'options' => ['Joins strings', 'Extracts part of string', 'Trims string', 'Converts string'], 'correct' => 1],
        ['question' => 'What does LENGTH() do?', 'options' => ['Counts words', 'Returns string length', 'Trims string', 'Converts string'], 'correct' => 1],
        ['question' => 'What does UPPER() do?', 'options' => ['Lowercase', 'Uppercase', 'Title case', 'Reverse'], 'correct' => 1],
        ['question' => 'What does NOW() return?', 'options' => ['Date', 'Current date and time', 'Time', 'Timestamp'], 'correct' => 1],
        ['question' => 'What does CURDATE() return?', 'options' => ['Current date', 'Current time', 'Current datetime', 'Current timestamp'], 'correct' => 0],
    ]],
    ['label' => 'Intermediate', 'questions' => [
        ['question' => 'What is InnoDB?', 'options' => ['MySQL version', 'Default storage engine', 'Tool', 'Database'], 'correct' => 1],
        ['question' => 'What is MyISAM?', 'options' => ['Default engine', 'Older storage engine', 'Tool', 'Language'], 'correct' => 1],
        ['question' => 'Does InnoDB support transactions?', 'options' => ['No', 'Yes', 'Only in new versions', 'Deprecated'], 'correct' => 1],
        ['question' => 'Does MyISAM support transactions?', 'options' => ['Yes', 'No', 'Only in old versions', 'With plugin'], 'correct' => 1],
        ['question' => 'Does InnoDB support foreign keys?', 'options' => ['No', 'Yes', 'Only primary keys', 'Deprecated'], 'correct' => 1],
        ['question' => 'What locking does InnoDB use?', 'options' => ['Table-level', 'Row-level', 'Database-level', 'No locking'], 'correct' => 1],
        ['question' => 'What locking does MyISAM use?', 'options' => ['Row-level', 'Table-level', 'Database-level', 'No locking'], 'correct' => 1],
        ['question' => 'What is an index?', 'options' => ['Table', 'Data structure for fast lookups', 'Column', 'Row'], 'correct' => 1],
        ['question' => 'What is a PRIMARY KEY index?', 'options' => ['Regular index', 'Unique identifier index', 'Foreign key', 'Composite index'], 'correct' => 1],
        ['question' => 'What is a UNIQUE index?', 'options' => ['Primary key', 'Ensures unique values', 'Fast index', 'No duplicates index'], 'correct' => 1],
        ['question' => 'What is a FULLTEXT index?', 'options' => ['Regular index', 'Text search index', 'Number index', 'Date index'], 'correct' => 1],
        ['question' => 'What does EXPLAIN do?', 'options' => ['Executes query', 'Shows query execution plan', 'Optimizes query', 'Indexes query'], 'correct' => 1],
        ['question' => 'What does the type column in EXPLAIN mean?', 'options' => ['Data type', 'Join type/access method', 'Table type', 'Index type'], 'correct' => 1],
        ['question' => 'What is the best EXPLAIN type?', 'options' => ['ALL', 'const/eq_ref', 'range', 'index'], 'correct' => 1],
        ['question' => 'What does rows in EXPLAIN show?', 'options' => ['Total rows', 'Estimated rows examined', 'Returned rows', 'Index rows'], 'correct' => 1],
        ['question' => 'What is a transaction?', 'options' => ['Single query', 'Group of queries as unit', 'Fast query', 'Index operation'], 'correct' => 1],
        ['question' => 'How do you start a transaction?', 'options' => ['BEGIN TRANSACTION', 'START TRANSACTION', 'NEW TRANSACTION', 'INIT TRANSACTION'], 'correct' => 1],
        ['question' => 'How do you save a transaction?', 'options' => ['SAVE', 'COMMIT', 'END', 'FINISH'], 'correct' => 1],
        ['question' => 'How do you cancel a transaction?', 'options' => ['CANCEL', 'ROLLBACK', 'UNDO', 'REVERT'], 'correct' => 1],
        ['question' => 'What is a SAVEPOINT?', 'options' => ['Checkpoint in transaction', 'Transaction point', 'Backup point', 'Rollback point'], 'correct' => 0],
        ['question' => 'What is READ UNCOMMITTED isolation?', 'options' => ['Strictest', 'Lowest, dirty reads allowed', 'Default', 'Highest'], 'correct' => 1],
        ['question' => 'What is READ COMMITTED isolation?', 'options' => ['Prevents dirty reads', 'Allows dirty reads', 'Default MySQL', 'Strictest'], 'correct' => 0],
        ['question' => 'What is REPEATABLE READ isolation?', 'options' => ['Lowest', 'Default MySQL, prevents non-repeatable reads', 'Highest', 'No isolation'], 'correct' => 1],
        ['question' => 'What is SERIALIZABLE isolation?', 'options' => ['Lowest', 'Highest, full isolation', 'Default', 'Fast'], 'correct' => 1],
        ['question' => 'What is MVCC?', 'options' => ['Locking', 'Multi-Version Concurrency Control', 'Index type', 'Storage engine'], 'correct' => 1],
        ['question' => 'What is a view?', 'options' => ['Table', 'Virtual table from query', 'Index', 'Backup'], 'correct' => 1],
        ['question' => 'Can views be updated?', 'options' => ['Never', 'Sometimes, if simple', 'Always', 'Only with InnoDB'], 'correct' => 1],
        ['question' => 'What is a stored procedure?', 'options' => ['View', 'Stored SQL code', 'Index', 'Table'], 'correct' => 1],
        ['question' => 'How do you call a procedure?', 'options' => ['EXECUTE proc', 'CALL proc', 'RUN proc', 'START proc'], 'correct' => 1],
        ['question' => 'What is an IN parameter?', 'options' => ['Output', 'Input parameter', 'Both', 'Neither'], 'correct' => 1],
        ['question' => 'What is an OUT parameter?', 'options' => ['Input', 'Output parameter', 'Both', 'Neither'], 'correct' => 1],
        ['question' => 'What is a trigger?', 'options' => ['Procedure', 'Auto-executed on event', 'View', 'Index'], 'correct' => 1],
        ['question' => 'When can triggers fire?', 'options' => ['BEFORE/AFTER INSERT/UPDATE/DELETE', 'Only on SELECT', 'Only on INSERT', 'Anytime'], 'correct' => 0],
        ['question' => 'What are OLD and NEW in triggers?', 'options' => ['Variables', 'Old and new row values', 'Tables', 'Columns'], 'correct' => 1],
        ['question' => 'What is an event?', 'options' => ['Trigger', 'Scheduled task', 'View', 'Procedure'], 'correct' => 1],
    ]],
    ['label' => 'Advanced', 'questions' => [
        ['question' => 'What is the InnoDB buffer pool?', 'options' => ['Disk cache', 'Memory cache for data/indexes', 'Log buffer', 'Query cache'], 'correct' => 1],
        ['question' => 'What is the redo log?', 'options' => ['Error log', 'Transaction durability log', 'Slow query log', 'Binary log'], 'correct' => 1],
        ['question' => 'What is the undo log?', 'options' => ['Redo log', 'Transaction rollback log', 'Error log', 'Binary log'], 'correct' => 1],
        ['question' => 'What is the doublewrite buffer?', 'options' => ['Write cache', 'Partial page write protection', 'Log buffer', 'Query cache'], 'correct' => 1],
        ['question' => 'What is the change buffer?', 'options' => ['Redo log', 'Buffers secondary index changes', 'Undo log', 'Query cache'], 'correct' => 1],
        ['question' => 'What is the adaptive hash index?', 'options' => ['Regular index', 'Automatic in-memory hash index', 'User index', 'Primary index'], 'correct' => 1],
        ['question' => 'What is the binary log?', 'options' => ['Error log', 'Replication and recovery log', 'Slow query log', 'General log'], 'correct' => 1],
        ['question' => 'What are binary log formats?', 'options' => ['STATEMENT/ROW/MIXED', 'TEXT/BINARY', 'SQL/JSON', 'XML/JSON'], 'correct' => 0],
        ['question' => 'What is GTID?', 'options' => ['Table ID', 'Global Transaction ID', 'Group ID', 'General ID'], 'correct' => 1],
        ['question' => 'What is the slow query log?', 'options' => ['All queries', 'Slow queries log', 'Error log', 'Binary log'], 'correct' => 1],
        ['question' => 'What is performance_schema?', 'options' => ['Storage engine', 'Performance monitoring database', 'Tool', 'Table'], 'correct' => 1],
        ['question' => 'What is information_schema?', 'options' => ['User database', 'Metadata database', 'System database', 'Temp database'], 'correct' => 1],
        ['question' => 'What does SHOW STATUS show?', 'options' => ['Tables', 'Server status variables', 'Users', 'Databases'], 'correct' => 1],
        ['question' => 'What does SHOW VARIABLES show?', 'options' => ['Tables', 'Server configuration variables', 'Users', 'Status'], 'correct' => 1],
        ['question' => 'What is key_buffer_size for?', 'options' => ['InnoDB', 'MyISAM index cache', 'Query cache', 'Table cache'], 'correct' => 1],
        ['question' => 'What is innodb_buffer_pool_size for?', 'options' => ['MyISAM', 'InnoDB memory cache', 'Query cache', 'Log size'], 'correct' => 1],
        ['question' => 'Was query cache removed in MySQL 8?', 'options' => ['No, improved', 'Yes, removed', 'No, default', 'Renamed'], 'correct' => 1],
        ['question' => 'What is FORCE INDEX hint?', 'options' => ['Prevents index', 'Forces specific index', 'Suggests index', 'Disables index'], 'correct' => 1],
        ['question' => 'What does USE INDEX do?', 'options' => ['Forces index', 'Suggests index', 'Prevents index', 'Creates index'], 'correct' => 1],
        ['question' => 'What does STRAIGHT_JOIN do?', 'options' => ['Left join', 'Forces join order', 'Right join', 'Inner join'], 'correct' => 1],
        ['question' => 'What is JSON_OBJECT()?', 'options' => ['Parses JSON', 'Creates JSON object', 'Queries JSON', 'Validates JSON'], 'correct' => 1],
        ['question' => 'What is JSON_EXTRACT()?', 'options' => ['Creates JSON', 'Extracts JSON value', 'Validates JSON', 'Updates JSON'], 'correct' => 1],
        ['question' => 'What is JSON_TABLE()?', 'options' => ['Creates table', 'Converts JSON to table', 'Saves JSON', 'Deletes JSON'], 'correct' => 1],
        ['question' => 'What is ROW_NUMBER() window function?', 'options' => ['Counts rows', 'Assigns row number', 'Ranks rows', 'Groups rows'], 'correct' => 1],
        ['question' => 'What is RANK() window function?', 'options' => ['Row number', 'Ranks with gaps', 'Dense rank', 'Partition'], 'correct' => 1],
        ['question' => 'What is DENSE_RANK()?', 'options' => ['Row number', 'Ranks without gaps', 'Regular rank', 'Partition'], 'correct' => 1],
        ['question' => 'What does LAG() do?', 'options' => ['Next row', 'Previous row value', 'Current row', 'Last row'], 'correct' => 1],
        ['question' => 'What does LEAD() do?', 'options' => ['Previous row', 'Next row value', 'Current row', 'First row'], 'correct' => 1],
        ['question' => 'What is a CTE (Common Table Expression)?', 'options' => ['Table', 'Temporary named result set', 'View', 'Procedure'], 'correct' => 1],
        ['question' => 'What keyword starts a CTE?', 'options' => ['CREATE', 'WITH', 'DECLARE', 'DEFINE'], 'correct' => 1],
        ['question' => 'What is table partitioning?', 'options' => ['Joining tables', 'Splitting table into parts', 'Indexing', 'Sharding'], 'correct' => 1],
        ['question' => 'What is replication?', 'options' => ['Backup', 'Copying data to replicas', 'Partitioning', 'Sharding'], 'correct' => 1],
        ['question' => 'What is primary-replica replication?', 'options' => ['Peer replication', 'Master-slave replication', 'Multi-master', 'No replication'], 'correct' => 1],
        ['question' => 'What is group replication?', 'options' => ['Single master', 'Multi-master replication', 'No replication', 'Async replication'], 'correct' => 1],
        ['question' => 'What is semi-sync replication?', 'options' => ['Fully async', 'Waits for one replica', 'Fully sync', 'No wait'], 'correct' => 1],
    ]],
    ['label' => 'Expert', 'questions' => [
        ['question' => 'What structure does InnoDB use?', 'options' => ['Hash table', 'B+ tree', 'B-tree', 'AVL tree'], 'correct' => 1],
        ['question' => 'What is a clustered index?', 'options' => ['Secondary index', 'Data stored in index order', 'External index', 'Separate index'], 'correct' => 1],
        ['question' => 'What is a secondary index?', 'options' => ['Primary key', 'Non-clustered index', 'Clustered index', 'Data index'], 'correct' => 1],
        ['question' => 'What is index selectivity?', 'options' => ['Index speed', 'Uniqueness of values', 'Index size', 'Index type'], 'correct' => 1],
        ['question' => 'What is cardinality?', 'options' => ['Index speed', 'Number of unique values', 'Index size', 'Row count'], 'correct' => 1],
        ['question' => 'What is a covering index?', 'options' => ['Primary key', 'Index containing all query columns', 'Full index', 'Complete index'], 'correct' => 1],
        ['question' => 'What is index merge optimization?', 'options' => ['Single index', 'Using multiple indexes', 'No indexes', 'Primary key only'], 'correct' => 1],
        ['question' => 'What is Multi-Range Read (MRR)?', 'options' => ['Single read', 'Optimizes range scans', 'Full scan', 'Index scan'], 'correct' => 1],
        ['question' => 'What is Block Nested Loop?', 'options' => ['Index join', 'Join algorithm', 'Hash join', 'Merge join'], 'correct' => 1],
        ['question' => 'Does MySQL 8.0.18+ support hash joins?', 'options' => ['No', 'Yes', 'Only InnoDB', 'Only MyISAM'], 'correct' => 1],
        ['question' => 'What is the optimizer cost model?', 'options' => ['Price model', 'Query cost estimation', 'Index cost', 'Memory cost'], 'correct' => 1],
        ['question' => 'Where are optimizer statistics stored?', 'options' => ['Memory', 'mysql.innodb_table_stats/innodb_index_stats', 'Disk', 'Binary log'], 'correct' => 1],
        ['question' => 'What is redo log group commit?', 'options' => ['Single commit', 'Batching commits', 'No commit', 'Async commit'], 'correct' => 1],
        ['question' => 'What is IO scheduling in InnoDB?', 'options' => ['No scheduling', 'Prioritizing IO operations', 'Disk scheduling', 'CPU scheduling'], 'correct' => 1],
        ['question' => 'Why does doublewrite buffer exist?', 'options' => ['Speed', 'Prevents partial page writes', 'Backup', 'Caching'], 'correct' => 1],
        ['question' => 'What is a record lock?', 'options' => ['Table lock', 'Lock on index record', 'Row lock', 'Page lock'], 'correct' => 1],
        ['question' => 'What is a gap lock?', 'options' => ['Record lock', 'Lock on gap between records', 'Table lock', 'Range lock'], 'correct' => 1],
        ['question' => 'What is a next-key lock?', 'options' => ['Record lock', 'Record + gap lock', 'Gap lock', 'Table lock'], 'correct' => 1],
        ['question' => 'What is an intention lock?', 'options' => ['Row lock', 'Table-level lock for compatibility', 'Page lock', 'Record lock'], 'correct' => 1],
        ['question' => 'How does deadlock detection work?', 'options' => ['Prevention', 'Wait-for graph algorithm', 'Timeout', 'Manual'], 'correct' => 1],
        ['question' => 'What are XA transactions?', 'options' => ['Single DB', 'Distributed transactions', 'Fast transactions', 'Local transactions'], 'correct' => 1],
        ['question' => 'What are resource groups in MySQL 8?', 'options' => ['Table groups', 'Thread CPU/memory allocation', 'User groups', 'Index groups'], 'correct' => 1],
        ['question' => 'What is the thread pool plugin?', 'options' => ['One thread per connection', 'Reuses threads', 'No threads', 'Unlimited threads'], 'correct' => 1],
        ['question' => 'What is one-thread-per-connection?', 'options' => ['Thread pool', 'Each connection gets thread', 'Shared threads', 'No threads'], 'correct' => 1],
        ['question' => 'What is MySQL Router?', 'options' => ['Database', 'Connection router', 'Replication tool', 'Backup tool'], 'correct' => 1],
        ['question' => 'What is InnoDB Cluster?', 'options' => ['Single server', 'HA cluster solution', 'Backup solution', 'Monitoring tool'], 'correct' => 1],
        ['question' => 'What is ProxySQL?', 'options' => ['Database', 'SQL proxy/load balancer', 'Backup tool', 'Monitor'], 'correct' => 1],
        ['question' => 'What is MySQL audit plugin?', 'options' => ['Performance tool', 'Activity logging plugin', 'Backup tool', 'Replication tool'], 'correct' => 1],
        ['question' => 'What is TDE (Transparent Data Encryption)?', 'options' => ['Compression', 'At-rest encryption', 'In-transit encryption', 'Backup encryption'], 'correct' => 1],
        ['question' => 'What is pt-online-schema-change?', 'options' => ['Backup tool', 'Online DDL tool', 'Monitor', 'Replication tool'], 'correct' => 1],
        ['question' => 'What is gh-ost?', 'options' => ['Backup tool', 'GitHub online schema migration', 'Monitor', 'Router'], 'correct' => 1],
        ['question' => 'What are statistics tables used for?', 'options' => ['Backups', 'Query optimization', 'Replication', 'Monitoring'], 'correct' => 1],
        ['question' => 'What does ANALYZE TABLE do?', 'options' => ['Repairs table', 'Updates statistics', 'Backs up table', 'Locks table'], 'correct' => 1],
        ['question' => 'What does OPTIMIZE TABLE do?', 'options' => ['Updates stats', 'Defragments table', 'Backs up', 'Locks'], 'correct' => 1],
        ['question' => 'What is the InnoDB page size?', 'options' => ['4KB', '16KB default', '32KB', '64KB'], 'correct' => 1],
    ]],
];
require_once __DIR__ . '/quiz-engine.php';
