<?php
$page_title = 'Node.js Quiz – 100 Levels – CodeFoundry';
$active_page = 'training';
$quiz_title  = 'Node.js';
$quiz_slug   = 'nodejs';
$quiz_tiers  = [
    [
        'label' => 'Introduction',
        'questions' => [
            ['question' => 'What is Node.js?', 'options' => ['A web browser', 'A JavaScript runtime built on Chrome\'s V8 engine', 'A JavaScript framework', 'A database'], 'correct' => 1],
            ['question' => 'Which JavaScript engine powers Node.js?', 'options' => ['SpiderMonkey', 'JavaScriptCore', 'V8', 'Chakra'], 'correct' => 2],
            ['question' => 'What is npm?', 'options' => ['Node Programming Module', 'Node Package Manager', 'New Project Manager', 'Network Package Manager'], 'correct' => 1],
            ['question' => 'What file holds Node.js project metadata and dependencies?', 'options' => ['node.json', 'package.json', 'project.json', 'config.json'], 'correct' => 1],
            ['question' => 'Which command initializes a new Node.js project?', 'options' => ['node init', 'npm start', 'npm init', 'node create'], 'correct' => 2],
            ['question' => 'How do you include a module in Node.js (CommonJS)?', 'options' => ['import module', 'require("module")', 'include("module")', 'use("module")'], 'correct' => 1],
            ['question' => 'What does the `http` module let you do?', 'options' => ['Make HTTP requests only', 'Create HTTP servers and make requests', 'Parse HTTP headers', 'Manage HTTP caching'], 'correct' => 1],
            ['question' => 'What does the `fs` module provide?', 'options' => ['File system operations', 'Function system utilities', 'Framework services', 'Fast streaming'], 'correct' => 0],
            ['question' => 'What does the `path` module help with?', 'options' => ['HTTP paths', 'File and directory path manipulations', 'URL paths', 'Import paths'], 'correct' => 1],
            ['question' => 'What is the event loop in Node.js?', 'options' => ['A loop that runs events in sequence', 'The mechanism that handles async I/O operations non-blockingly', 'A loop for DOM events', 'An infinite loop'], 'correct' => 1],
            ['question' => 'What does "non-blocking I/O" mean in Node.js?', 'options' => ['I/O operations are blocked', 'I/O operations don\'t block the main thread; callbacks are used', 'I/O is done synchronously', 'I/O is blocked until complete'], 'correct' => 1],
            ['question' => 'Which global object provides information about the current process?', 'options' => ['global', 'process', 'system', 'runtime'], 'correct' => 1],
            ['question' => 'What does `process.argv` contain?', 'options' => ['Environment variables', 'Command-line arguments passed to the process', 'Process ID', 'Process flags'], 'correct' => 1],
            ['question' => 'What is `__dirname` in Node.js?', 'options' => ['The current working directory', 'The directory name of the current module file', 'The root directory', 'The home directory'], 'correct' => 1],
            ['question' => 'What is `__filename` in Node.js?', 'options' => ['The entry file', 'The full path of the current module file', 'The package name', 'The script name'], 'correct' => 1],
            ['question' => 'What does `module.exports` do?', 'options' => ['Imports a module', 'Defines what a module exposes when required', 'Exports global variables', 'Exports a class'], 'correct' => 1],
            ['question' => 'Which command runs a Node.js script?', 'options' => ['npm script.js', 'node script.js', 'run script.js', 'js script.js'], 'correct' => 1],
            ['question' => 'What does the `os` module provide?', 'options' => ['Operating system utilities', 'Object storage', 'Output stream', 'Object system'], 'correct' => 0],
            ['question' => 'What is `package-lock.json`?', 'options' => ['A lock to prevent package changes', 'A file that records exact versions of all installed dependencies', 'A backup of package.json', 'A list of locked packages'], 'correct' => 1],
            ['question' => 'What does `npm install` do?', 'options' => ['Updates all packages', 'Installs dependencies listed in package.json', 'Installs Node.js', 'Creates package.json'], 'correct' => 1],
            ['question' => 'What is an EventEmitter in Node.js?', 'options' => ['A DOM event handler', 'A class that implements the observer pattern for emitting and listening to events', 'A timer function', 'An event queue'], 'correct' => 1],
            ['question' => 'What does `http.createServer()` return?', 'options' => ['A URL', 'An HTTP server instance', 'A request object', 'A response object'], 'correct' => 1],
            ['question' => 'Which method starts an HTTP server listening on a port?', 'options' => ['server.open()', 'server.start()', 'server.listen()', 'server.run()'], 'correct' => 2],
            ['question' => 'What is the default module system in Node.js?', 'options' => ['ES Modules', 'CommonJS', 'AMD', 'UMD'], 'correct' => 1],
            ['question' => 'What does `REPL` stand for in Node.js context?', 'options' => ['Run Execute Print Loop', 'Read-Eval-Print Loop', 'Runtime Environment Program Loop', 'Read Execute Process Log'], 'correct' => 1],
        ],
    ],
    [
        'label' => 'Beginner',
        'questions' => [
            ['question' => 'What is Express.js?', 'options' => ['A Node.js database', 'A minimal web framework for Node.js', 'A task runner', 'A testing library'], 'correct' => 1],
            ['question' => 'How do you create an Express application?', 'options' => ['new Express()', 'express()', 'Express.create()', 'createApp()'], 'correct' => 1],
            ['question' => 'What is middleware in Express?', 'options' => ['Middleware software', 'Functions that have access to req, res, and next in the request-response cycle', 'Route handlers', 'Error handlers only'], 'correct' => 1],
            ['question' => 'What does `next()` do in Express middleware?', 'options' => ['Goes to the next route', 'Passes control to the next middleware or route handler', 'Sends the response', 'Skips the current request'], 'correct' => 1],
            ['question' => 'Which method defines a GET route in Express?', 'options' => ['app.route("GET", "/path")', 'app.get("/path", handler)', 'app.get("/path")', 'router.GET("/path", handler)'], 'correct' => 1],
            ['question' => 'What does `res.json()` do in Express?', 'options' => ['Parses JSON body', 'Sends a JSON response with appropriate Content-Type header', 'Returns JSON from database', 'Converts res to JSON'], 'correct' => 1],
            ['question' => 'What is a callback in Node.js?', 'options' => ['A return value', 'A function passed as an argument to be called when an async operation completes', 'A recursive function', 'A callback URL'], 'correct' => 1],
            ['question' => 'What is "callback hell"?', 'options' => ['Too many callbacks', 'Deeply nested callbacks that make code hard to read and maintain', 'Callback errors', 'Slow callbacks'], 'correct' => 1],
            ['question' => 'What does a Promise represent?', 'options' => ['A guaranteed value', 'A proxy for a value not yet known, representing an async operation\'s eventual result', 'A future variable', 'An async function'], 'correct' => 1],
            ['question' => 'What states can a Promise be in?', 'options' => ['Open, closed, error', 'Pending, fulfilled, rejected', 'Active, inactive, failed', 'Running, done, failed'], 'correct' => 1],
            ['question' => 'What does `async/await` do?', 'options' => ['Creates parallel functions', 'Provides syntactic sugar over Promises for writing async code synchronously', 'Enables multithreading', 'Makes functions faster'], 'correct' => 1],
            ['question' => 'What does `await` do?', 'options' => ['Blocks the entire process', 'Pauses execution of an async function until a Promise resolves', 'Waits for a timeout', 'Queues a microtask'], 'correct' => 1],
            ['question' => 'How do you handle errors in async/await?', 'options' => ['Using .catch()', 'Using try/catch blocks', 'Using error callbacks', 'Both A and B work'], 'correct' => 3],
            ['question' => 'What does `npm install express --save` do?', 'options' => ['Installs Express globally', 'Installs Express and adds it to package.json dependencies', 'Saves Express config', 'Installs Express as devDependency'], 'correct' => 1],
            ['question' => 'What is `--save-dev` flag for in npm?', 'options' => ['Saves as a production dependency', 'Saves package as a development-only dependency', 'Saves configuration', 'Saves to a dev folder'], 'correct' => 1],
            ['question' => 'What is `nodemon` used for?', 'options' => ['Node.js monitoring', 'Automatically restarting Node.js server on file changes', 'Node performance tool', 'Node module manager'], 'correct' => 1],
            ['question' => 'What does `express.json()` middleware do?', 'options' => ['Converts responses to JSON', 'Parses incoming JSON request bodies', 'Validates JSON', 'Formats JSON output'], 'correct' => 1],
            ['question' => 'What does `req.params` contain in Express?', 'options' => ['Query string parameters', 'Route parameters from the URL path', 'Request body parameters', 'Header parameters'], 'correct' => 1],
            ['question' => 'What does `req.query` contain?', 'options' => ['Route parameters', 'URL query string parameters', 'POST body data', 'Cookie data'], 'correct' => 1],
            ['question' => 'What does `req.body` contain?', 'options' => ['URL parameters', 'The parsed request body (requires body-parser middleware)', 'Response headers', 'Query strings'], 'correct' => 1],
            ['question' => 'What is a router in Express?', 'options' => ['A network router', 'A mini-application for handling routes in a modular way', 'A request redirector', 'A URL parser'], 'correct' => 1],
            ['question' => 'What HTTP status code indicates a successful resource creation?', 'options' => ['200', '201', '204', '202'], 'correct' => 1],
            ['question' => 'What does `res.status(404).send("Not Found")` do?', 'options' => ['Sets a 404 header only', 'Sends a 404 response with body "Not Found"', 'Redirects to 404 page', 'Throws a 404 error'], 'correct' => 1],
            ['question' => 'What does `Promise.all()` do?', 'options' => ['Runs promises sequentially', 'Runs all promises in parallel and resolves when all complete', 'Resolves the first promise', 'Merges promises'], 'correct' => 1],
            ['question' => 'What does `Promise.race()` do?', 'options' => ['Runs promises competitively', 'Resolves or rejects as soon as the first promise settles', 'Races to the fastest resolve', 'Runs promises in parallel'], 'correct' => 1],
        ],
    ],
    [
        'label' => 'Intermediate',
        'questions' => [
            ['question' => 'What is a stream in Node.js?', 'options' => ['A continuous data connection', 'An abstract interface for working with streaming data', 'A live HTTP connection', 'A data buffer'], 'correct' => 1],
            ['question' => 'What are the four types of streams in Node.js?', 'options' => ['Read, Write, Buffer, Pipe', 'Readable, Writable, Duplex, Transform', 'Input, Output, Bidirectional, Filter', 'Sync, Async, Buffer, Stream'], 'correct' => 1],
            ['question' => 'What does `pipe()` do on a stream?', 'options' => ['Creates a new stream', 'Connects a readable stream to a writable stream', 'Buffers the data', 'Filters stream data'], 'correct' => 1],
            ['question' => 'What is a Buffer in Node.js?', 'options' => ['A memory cache', 'A fixed-size chunk of memory for handling binary data', 'A stream buffer', 'A string holder'], 'correct' => 1],
            ['question' => 'What module is used to spawn child processes?', 'options' => ['process', 'child_process', 'subprocess', 'fork'], 'correct' => 1],
            ['question' => 'What is the difference between `spawn` and `exec` in child_process?', 'options' => ['No difference', 'spawn streams I/O; exec buffers output and runs in a shell', 'exec is faster', 'spawn uses more memory'], 'correct' => 1],
            ['question' => 'What does the `cluster` module do?', 'options' => ['Groups modules', 'Allows creating child processes that share the same server port to utilize multiple CPU cores', 'Creates server clusters', 'Manages process groups'], 'correct' => 1],
            ['question' => 'What are Worker Threads in Node.js?', 'options' => ['Background HTTP workers', 'Threads that allow CPU-intensive JavaScript execution without blocking the event loop', 'Web Workers for Node', 'Thread pool workers'], 'correct' => 1],
            ['question' => 'How do you access environment variables in Node.js?', 'options' => ['env.VARIABLE', 'process.env.VARIABLE', 'os.env.VARIABLE', 'system.env.VARIABLE'], 'correct' => 1],
            ['question' => 'What is the `.env` file used for?', 'options' => ['Environment configuration', 'Storing environment variables for local development (loaded via dotenv)', 'Node.js environment settings', 'npm environment config'], 'correct' => 1],
            ['question' => 'What does `dotenv` package do?', 'options' => ['Manages env files', 'Loads variables from a .env file into process.env', 'Validates env variables', 'Encrypts env variables'], 'correct' => 1],
            ['question' => 'What is error-first callback convention?', 'options' => ['Errors come last', 'The first argument of a callback is an error object (null if no error)', 'Errors are returned', 'Error handling first'], 'correct' => 1],
            ['question' => 'What does `fs.readFile()` do?', 'options' => ['Reads synchronously', 'Reads a file asynchronously and calls a callback with the result', 'Reads and streams a file', 'Reads the file system'], 'correct' => 1],
            ['question' => 'What is the difference between `fs.readFile` and `fs.readFileSync`?', 'options' => ['No difference', 'readFile is async with callback; readFileSync blocks the event loop', 'readFileSync is faster', 'readFile returns a promise'], 'correct' => 1],
            ['question' => 'What is a REST API?', 'options' => ['A database API', 'An architectural style using HTTP methods for stateless client-server communication', 'A JavaScript API', 'A REST framework'], 'correct' => 1],
            ['question' => 'What HTTP method is used for creating resources in REST?', 'options' => ['GET', 'PUT', 'POST', 'PATCH'], 'correct' => 2],
            ['question' => 'What HTTP method is used for full updates in REST?', 'options' => ['POST', 'PATCH', 'PUT', 'UPDATE'], 'correct' => 2],
            ['question' => 'What HTTP method is used for partial updates in REST?', 'options' => ['PUT', 'PATCH', 'POST', 'UPDATE'], 'correct' => 1],
            ['question' => 'What is CORS in Node.js context?', 'options' => ['Cross-Origin Resource Sharing – controls which origins can access the server', 'Cross-Origin Request Security', 'A Node.js module', 'Certificate-based security'], 'correct' => 0],
            ['question' => 'What does the `cors` npm package do?', 'options' => ['Encrypts requests', 'Enables CORS headers in Express', 'Validates origins', 'Proxies requests'], 'correct' => 1],
            ['question' => 'What is middleware error handling in Express?', 'options' => ['Using try/catch', 'A middleware with 4 arguments (err, req, res, next) for handling errors', 'Error event listeners', 'Domain-based error handling'], 'correct' => 1],
            ['question' => 'What does `util.promisify()` do?', 'options' => ['Converts a Promise to a callback', 'Converts a callback-style function to return a Promise', 'Creates a utility Promise', 'Wraps functions in try/catch'], 'correct' => 1],
            ['question' => 'What is `libuv`?', 'options' => ['A Node.js library', 'The C library that provides Node.js its event loop and async I/O capabilities', 'A UV light module', 'A Linux utility'], 'correct' => 1],
            ['question' => 'What does `setImmediate()` do?', 'options' => ['Runs immediately synchronously', 'Schedules a callback to execute in the check phase of the next event loop iteration', 'Runs before I/O', 'Immediate timeout'], 'correct' => 1],
            ['question' => 'What is the difference between `process.nextTick()` and `setImmediate()`?', 'options' => ['No difference', 'nextTick runs before I/O in the current iteration; setImmediate runs in the next check phase', 'setImmediate is faster', 'nextTick runs after I/O'], 'correct' => 1],
        ],
    ],
    [
        'label' => 'Advanced',
        'questions' => [
            ['question' => 'What is the V8 engine?', 'options' => ['A Node.js module', 'Google\'s high-performance JavaScript and WebAssembly engine used by Node.js', 'An 8-core virtual machine', 'A V8 JavaScript parser'], 'correct' => 1],
            ['question' => 'What is JIT compilation in V8?', 'options' => ['Just-In-Time compilation: compiles JS to machine code at runtime for performance', 'Java Integration Technique', 'JavaScript Interpreter Translation', 'Just Inline Transpilation'], 'correct' => 0],
            ['question' => 'What is the Node.js thread pool used for?', 'options' => ['Running event loop tasks', 'Handling CPU-intensive operations and some I/O tasks that cannot be done async by the OS', 'Managing HTTP connections', 'Running child processes'], 'correct' => 1],
            ['question' => 'What is `UV_THREADPOOL_SIZE` environment variable?', 'options' => ['Sets thread pool count for libuv (default 4)', 'UV light size', 'Upload thread size', 'CPU affinity setting'], 'correct' => 0],
            ['question' => 'What causes a memory leak in Node.js?', 'options' => ['Using async/await', 'Retaining references to objects that are no longer needed, preventing garbage collection', 'Large files', 'Too many routes'], 'correct' => 1],
            ['question' => 'What tool can profile Node.js performance?', 'options' => ['npm audit', 'node --prof to generate V8 profiler output', 'node --inspect only', 'node --debug'], 'correct' => 1],
            ['question' => 'What is `node --inspect` used for?', 'options' => ['Inspecting source files', 'Enabling Chrome DevTools debugging protocol for Node.js', 'Listing installed modules', 'Validating code'], 'correct' => 1],
            ['question' => 'What are native addons in Node.js?', 'options' => ['Built-in modules', 'Dynamically linked shared objects written in C/C++ that can be required like modules', 'Native iOS addons', 'Native language features'], 'correct' => 1],
            ['question' => 'What is N-API?', 'options' => ['Node API', 'A stable C API for building native addons independent of V8 version', 'Network API', 'Node Package API'], 'correct' => 1],
            ['question' => 'What is a microservice architecture?', 'options' => ['Small servers', 'An approach where an application is composed of small, independent services communicating via APIs', 'Micro-sized APIs', 'Minimal Node.js servers'], 'correct' => 1],
            ['question' => 'What is PM2?', 'options' => ['Package Manager 2', 'A production process manager for Node.js with load balancing and monitoring', 'A Node.js framework', 'A performance monitor'], 'correct' => 1],
            ['question' => 'What does PM2 cluster mode do?', 'options' => ['Clusters database connections', 'Spawns multiple Node.js instances across CPU cores to handle more traffic', 'Groups processes', 'Creates process clusters'], 'correct' => 1],
            ['question' => 'What is `heap snapshot` used for?', 'options' => ['Taking code snapshots', 'Capturing V8 heap memory state for memory leak analysis', 'Snapshot testing', 'Database snapshots'], 'correct' => 1],
            ['question' => 'What does `--max-old-space-size` Node.js flag do?', 'options' => ['Sets disk space limit', 'Sets the maximum heap size for old generation in V8', 'Limits old modules', 'Sets memory page size'], 'correct' => 1],
            ['question' => 'What is backpressure in Node.js streams?', 'options' => ['Reverse data flow', 'The mechanism that prevents a writable stream from being overwhelmed by a faster readable stream', 'Back-channel pressure', 'Write pressure'], 'correct' => 1],
            ['question' => 'What is `node:` prefix in imports (e.g., `require("node:fs")`)?', 'options' => ['A namespace alias', 'An explicit way to import core Node.js modules, bypassing any local module with the same name', 'A Node version prefix', 'A module format'], 'correct' => 1],
            ['question' => 'What does `AbortController` do in Node.js?', 'options' => ['Aborts scripts', 'Provides an object to abort async operations like fetch or streams', 'Cancels HTTP requests only', 'Stops child processes'], 'correct' => 1],
            ['question' => 'What is the purpose of `AsyncLocalStorage`?', 'options' => ['Storing async data on disk', 'Propagating context (like request IDs) through async operations without passing it explicitly', 'Local async queue', 'Async storage API'], 'correct' => 1],
            ['question' => 'What is structured cloning in Node.js?', 'options' => ['Object copying', 'A deep clone algorithm used to transfer data between workers, supporting complex types', 'Module cloning', 'Code cloning'], 'correct' => 1],
            ['question' => 'What is `SharedArrayBuffer` used for in Node.js?', 'options' => ['Shared database buffer', 'Sharing memory between worker threads without copying', 'Buffering shared streams', 'Shared request buffer'], 'correct' => 1],
            ['question' => 'What is `Atomics` in Node.js?', 'options' => ['Atomic npm packages', 'A global object providing atomic operations on SharedArrayBuffer for thread-safe access', 'Atomic file operations', 'Atomic promises'], 'correct' => 1],
            ['question' => 'What does `node:perf_hooks` module provide?', 'options' => ['Performance hooks for monitoring event loop, timing, and measuring code performance', 'HTTP performance hooks', 'Package hooks', 'Process performance'], 'correct' => 0],
            ['question' => 'What is connection pooling in Node.js database usage?', 'options' => ['Collecting database connections', 'Reusing a pool of database connections to reduce overhead of creating new connections', 'Pooling queries', 'Database clustering'], 'correct' => 1],
            ['question' => 'What does `--experimental-vm-modules` enable?', 'options' => ['Virtual machine features', 'Support for ES modules in the vm module for testing', 'VM process isolation', 'Virtual memory modules'], 'correct' => 1],
            ['question' => 'What is the `diagnostics_channel` module?', 'options' => ['Error reporting channel', 'A publish/subscribe channel for diagnostic information in libraries and applications', 'Debug logging channel', 'Network diagnostics'], 'correct' => 1],
        ],
    ],
    [
        'label' => 'Expert',
        'questions' => [
            ['question' => 'What is the OWASP Top 10 most relevant to Node.js APIs?', 'options' => ['CSS injection', 'Injection, broken auth, IDOR, security misconfiguration, and more', 'Only XSS', 'Only SQL injection'], 'correct' => 1],
            ['question' => 'What is rate limiting?', 'options' => ['Limiting data rates', 'Controlling how many requests a client can make in a time window to prevent abuse', 'Limiting file sizes', 'Speed throttling'], 'correct' => 1],
            ['question' => 'What npm package is commonly used for rate limiting in Express?', 'options' => ['express-throttle', 'express-rate-limit', 'rate-limiter', 'limiter-express'], 'correct' => 1],
            ['question' => 'What is helmet.js?', 'options' => ['A Node.js framework', 'An Express middleware that sets security-related HTTP headers', 'A testing tool', 'A logging library'], 'correct' => 1],
            ['question' => 'What is a JWT?', 'options' => ['JavaScript Web Token', 'JSON Web Token – a compact, URL-safe way to represent claims between two parties', 'Java Web Token', 'JSON Wrapper Type'], 'correct' => 1],
            ['question' => 'What are the three parts of a JWT?', 'options' => ['Header, claims, signature', 'Header, payload, signature', 'Token, body, hash', 'Type, data, key'], 'correct' => 1],
            ['question' => 'What is a refresh token pattern?', 'options' => ['Refreshing the page token', 'Using a long-lived refresh token to obtain new short-lived access tokens', 'Token rotation', 'Cache token refresh'], 'correct' => 1],
            ['question' => 'What is Redis commonly used for in Node.js applications?', 'options' => ['SQL database replacement', 'In-memory caching, session storage, and pub/sub messaging', 'File storage', 'Static content serving'], 'correct' => 1],
            ['question' => 'What is a pub/sub pattern?', 'options' => ['Public/subscriber pattern', 'A messaging pattern where publishers send messages to channels that subscribers listen to', 'Publish-subscribe database', 'Push notification pattern'], 'correct' => 1],
            ['question' => 'What is a message queue?', 'options' => ['A request queue', 'A component that stores messages between producers and consumers for async processing', 'An email queue', 'A database queue'], 'correct' => 1],
            ['question' => 'What is RabbitMQ used for with Node.js?', 'options' => ['Caching', 'Message broker for handling asynchronous communication between services', 'Database management', 'HTTP routing'], 'correct' => 1],
            ['question' => 'What is load balancing?', 'options' => ['Balancing server load', 'Distributing incoming requests across multiple server instances for scalability', 'Balancing databases', 'Load testing'], 'correct' => 1],
            ['question' => 'What is a reverse proxy and why is it used with Node.js?', 'options' => ['A proxy that reverses requests', 'A server (like Nginx) that forwards requests to Node.js, handling TLS, caching, and load balancing', 'A Node.js proxy module', 'An HTTP redirect'], 'correct' => 1],
            ['question' => 'What is horizontal scaling?', 'options' => ['Scaling database tables', 'Adding more server instances to handle increased load', 'Scaling CPU cores', 'Increasing server RAM'], 'correct' => 1],
            ['question' => 'What is a serverless function in Node.js context?', 'options' => ['A function with no server', 'A function deployed to a managed cloud environment that scales automatically and charges per execution', 'A lambda function', 'An anonymous function'], 'correct' => 1],
            ['question' => 'What is OpenTelemetry?', 'options' => ['A telescope API', 'A vendor-neutral observability framework for collecting metrics, logs, and traces', 'A network monitoring tool', 'An open-source telemetry library'], 'correct' => 1],
            ['question' => 'What is distributed tracing?', 'options' => ['Debugging distributed code', 'Tracking a request\'s journey across multiple microservices to diagnose latency and errors', 'Distributed logging', 'Trace file analysis'], 'correct' => 1],
            ['question' => 'What is SQL injection and how do you prevent it in Node.js?', 'options' => ['A slow SQL query; use indexes', 'Malicious SQL via user input; prevent with parameterized queries/prepared statements', 'An SQL error; use try/catch', 'A SQL syntax error; use linting'], 'correct' => 1],
            ['question' => 'What is input sanitization?', 'options' => ['Cleaning database inputs', 'Validating and cleaning user-provided data to prevent injection attacks', 'Sanitizing file names', 'Input formatting'], 'correct' => 1],
            ['question' => 'What is `Content Security Policy` (CSP)?', 'options' => ['A content management policy', 'An HTTP header that controls what resources the browser is allowed to load', 'A security middleware', 'A content filter'], 'correct' => 1],
            ['question' => 'What is a Docker container and why is it used with Node.js?', 'options' => ['A storage container', 'A lightweight, portable environment that packages the app and its dependencies for consistent deployment', 'A Node.js runtime container', 'A virtual machine'], 'correct' => 1],
            ['question' => 'What is a Kubernetes pod?', 'options' => ['A group of containers', 'The smallest deployable unit in Kubernetes, containing one or more containers that share resources', 'A server node', 'A service group'], 'correct' => 1],
            ['question' => 'What is circuit breaking in microservices?', 'options' => ['Electrical circuit protection', 'A pattern that stops sending requests to a failing service and provides a fallback', 'Breaking service connections', 'Circuit-level monitoring'], 'correct' => 1],
            ['question' => 'What is a graceful shutdown in Node.js?', 'options' => ['A polite exit message', 'Stopping the server by finishing in-flight requests before exiting, preventing data loss', 'Shutdown logging', 'A clean process exit'], 'correct' => 1],
            ['question' => 'What is the `SIGTERM` signal in Node.js?', 'options' => ['A terminate error', 'A signal sent to a process requesting graceful termination, used by orchestrators like Kubernetes', 'A system signal', 'A fatal error signal'], 'correct' => 1],
        ],
    ],
];
require_once __DIR__ . '/quiz-engine.php';
