<?php
$page_title = 'NumPy Quiz – 100 Levels – CodeFoundry';
$active_page = 'training';
$quiz_title  = 'NumPy';
$quiz_slug   = 'numpy';
$quiz_tiers  = [
    ['label' => 'Introduction', 'questions' => [
        ['question' => 'What is NumPy?', 'options' => ['Number Python', 'Numerical Python library', 'New Python', 'Python numbers'], 'correct' => 1],
        ['question' => 'How do you import NumPy?', 'options' => ['import numpy', 'import numpy as np', 'from numpy import *', 'import np'], 'correct' => 1],
        ['question' => 'How do you create array?', 'options' => ['np.array()', 'np.create()', 'np.new()', 'numpy.array()'], 'correct' => 0],
        ['question' => 'What is ndarray?', 'options' => ['Array type', 'N-dimensional array', 'NumPy array', 'Data array'], 'correct' => 1],
        ['question' => 'What advantage does ndarray have?', 'options' => ['Easier syntax', 'Faster than Python list', 'More features', 'Better display'], 'correct' => 1],
        ['question' => 'What is 0D array?', 'options' => ['Empty', 'Scalar', 'Zero array', 'Null'], 'correct' => 1],
        ['question' => 'What is 1D array?', 'options' => ['Single dimension', 'Vector', 'Line array', 'Row'], 'correct' => 1],
        ['question' => 'What is 2D array?', 'options' => ['Two dimension', 'Matrix', 'Table', 'Grid'], 'correct' => 1],
        ['question' => 'What attribute shows shape?', 'options' => ['.size', '.shape', '.dimensions', '.form'], 'correct' => 1],
        ['question' => 'What attribute shows data type?', 'options' => ['.type', '.dtype', '.datatype', '.kind'], 'correct' => 1],
        ['question' => 'What is int32?', 'options' => ['32 integers', '32-bit integer type', 'Integer 32', 'Int type'], 'correct' => 1],
        ['question' => 'What is float64?', 'options' => ['64 floats', '64-bit float type', 'Float 64', 'Double'], 'correct' => 1],
        ['question' => 'What attribute shows dimensions?', 'options' => ['.dims', '.ndim', '.dimensions', '.dim'], 'correct' => 1],
        ['question' => 'What attribute shows total elements?', 'options' => ['.length', '.size', '.count', '.total'], 'correct' => 1],
        ['question' => 'How do you index 2D array?', 'options' => ['[i][j]', '[i,j]', 'Both A and B', '[i][j] only'], 'correct' => 2],
        ['question' => 'What does [start:stop] do?', 'options' => ['Range', 'Slices array', 'Subset', 'Extract'], 'correct' => 1],
        ['question' => 'What does np.zeros() create?', 'options' => ['Empty array', 'Array of zeros', 'Zero array', 'Null array'], 'correct' => 1],
        ['question' => 'What does np.ones() create?', 'options' => ['Single array', 'Array of ones', 'One array', 'Unit array'], 'correct' => 1],
        ['question' => 'What does np.full() create?', 'options' => ['Full array', 'Array with constant value', 'Filled array', 'Complete array'], 'correct' => 1],
        ['question' => 'What does np.arange() do?', 'options' => ['Arranges', 'Creates range of values', 'Array range', 'Sequence'], 'correct' => 1],
        ['question' => 'What does np.linspace() create?', 'options' => ['Linear space', 'Evenly spaced values', 'Line space', 'Linear array'], 'correct' => 1],
        ['question' => 'Can you add arrays?', 'options' => ['No', 'Yes, element-wise', 'Only same size', 'With function'], 'correct' => 1],
        ['question' => 'What does array * 2 do?', 'options' => ['Doubles size', 'Multiplies each element by 2', 'Repeats array', 'Error'], 'correct' => 1],
        ['question' => 'What does array > 5 return?', 'options' => ['Error', 'Boolean array', 'Filtered array', 'True/False'], 'correct' => 1],
        ['question' => 'Can you compare arrays?', 'options' => ['No', 'Yes, element-wise', 'Only equal', 'With function'], 'correct' => 1],
    ]],
    ['label' => 'Beginner', 'questions' => [
        ['question' => 'How do you specify dtype?', 'options' => ['type=', 'dtype=', 'datatype=', 'as_type='], 'correct' => 1],
        ['question' => 'How do you convert dtype?', 'options' => ['.convert()', '.astype()', '.cast()', '.to_type()'], 'correct' => 1],
        ['question' => 'What does np.eye() create?', 'options' => ['I array', 'Identity matrix', 'Eye matrix', 'Diagonal ones'], 'correct' => 1],
        ['question' => 'What does np.random.rand() create?', 'options' => ['Random integers', 'Random floats [0,1)', 'Random array', 'Random values'], 'correct' => 1],
        ['question' => 'What does np.random.randn() create?', 'options' => ['Random integers', 'Standard normal distribution', 'Random negative', 'Normal random'], 'correct' => 1],
        ['question' => 'What does np.random.randint() create?', 'options' => ['Random integers', 'Random integer values', 'Integer random', 'Int array'], 'correct' => 1],
        ['question' => 'What does np.random.seed() do?', 'options' => ['Plants seed', 'Sets random seed', 'Initializes random', 'Random start'], 'correct' => 1],
        ['question' => 'What does reshape() do?', 'options' => ['Changes shape', 'Reshapes array', 'Modifies dimensions', 'Transforms'], 'correct' => 1],
        ['question' => 'What does flatten() do?', 'options' => ['Makes flat', 'Converts to 1D', 'Flattens array', 'Reduces dimensions'], 'correct' => 1],
        ['question' => 'What does ravel() do?', 'options' => ['Unravels', 'Returns flattened view', 'Flattens', '1D view'], 'correct' => 1],
        ['question' => 'What does np.hstack() do?', 'options' => ['Horizontal stack', 'Stacks horizontally', 'Stacks columns', 'H-stack'], 'correct' => 1],
        ['question' => 'What does np.vstack() do?', 'options' => ['Vertical stack', 'Stacks vertically', 'Stacks rows', 'V-stack'], 'correct' => 1],
        ['question' => 'What does np.concatenate() do?', 'options' => ['Combines', 'Joins arrays', 'Concatenates', 'Merges'], 'correct' => 1],
        ['question' => 'What does np.hsplit() do?', 'options' => ['Horizontal split', 'Splits horizontally', 'Splits columns', 'H-split'], 'correct' => 1],
        ['question' => 'What is broadcasting?', 'options' => ['Sending data', 'Operating on different shapes', 'Array expansion', 'Auto-sizing'], 'correct' => 1],
        ['question' => 'What is ufunc?', 'options' => ['User function', 'Universal function', 'Utility function', 'Unary function'], 'correct' => 1],
        ['question' => 'What does np.sqrt() do?', 'options' => ['Square root', 'Element-wise square root', 'Root function', 'Sqrt calc'], 'correct' => 1],
        ['question' => 'What does np.exp() do?', 'options' => ['Exponential', 'e^x for each element', 'Exponent', 'Power e'], 'correct' => 1],
        ['question' => 'What does np.sum() do?', 'options' => ['Adds all', 'Sum of elements', 'Total', 'Addition'], 'correct' => 1],
        ['question' => 'What does np.mean() do?', 'options' => ['Average', 'Mean value', 'Middle value', 'Avg'], 'correct' => 1],
        ['question' => 'What does np.std() do?', 'options' => ['Standard', 'Standard deviation', 'Deviation', 'Std value'], 'correct' => 1],
        ['question' => 'What does axis parameter do?', 'options' => ['Sets axis', 'Specifies dimension', 'Direction', 'Axis selection'], 'correct' => 1],
        ['question' => 'What does axis=0 mean?', 'options' => ['Zero axis', 'Along rows', 'First dimension', 'Vertical'], 'correct' => 1],
        ['question' => 'What does axis=1 mean?', 'options' => ['One axis', 'Along columns', 'Second dimension', 'Horizontal'], 'correct' => 1],
        ['question' => 'What does np.sort() do?', 'options' => ['Sorts array', 'Returns sorted array', 'Orders elements', 'Arranges'], 'correct' => 1],
    ]],
    ['label' => 'Intermediate', 'questions' => [
        ['question' => 'What is fancy indexing?', 'options' => ['Nice indexing', 'Indexing with arrays', 'Advanced indexing', 'Array indexing'], 'correct' => 1],
        ['question' => 'What is boolean indexing?', 'options' => ['True/false index', 'Indexing with boolean array', 'Conditional indexing', 'Bool index'], 'correct' => 1],
        ['question' => 'What does np.where() do?', 'options' => ['Finds location', 'Conditional selection', 'Where condition', 'Location finder'], 'correct' => 1],
        ['question' => 'What does np.einsum() do?', 'options' => ['Einstein sum', 'Einstein summation convention', 'Tensor operation', 'Sum notation'], 'correct' => 1],
        ['question' => 'What does np.dot() do?', 'options' => ['Dot product', 'Dot product of arrays', 'Vector dot', 'Multiply dot'], 'correct' => 1],
        ['question' => 'What does @ operator do?', 'options' => ['At operator', 'Matrix multiplication', 'Matmul', 'Multiply operator'], 'correct' => 1],
        ['question' => 'What does np.linalg.inv() do?', 'options' => ['Inverts', 'Matrix inverse', 'Inverse matrix', 'Inversion'], 'correct' => 1],
        ['question' => 'What does np.linalg.det() do?', 'options' => ['Determines', 'Determinant', 'Matrix determinant', 'Det value'], 'correct' => 1],
        ['question' => 'What does np.linalg.solve() do?', 'options' => ['Solves equation', 'Solves linear system', 'System solver', 'Linear solve'], 'correct' => 1],
        ['question' => 'What does np.linalg.eig() do?', 'options' => ['Eight function', 'Eigenvalues and eigenvectors', 'Eigen calc', 'Eig values'], 'correct' => 1],
        ['question' => 'What does np.fft.fft() do?', 'options' => ['Fast function', 'Fast Fourier Transform', 'Frequency transform', 'FFT calc'], 'correct' => 1],
        ['question' => 'What is structured array?', 'options' => ['Organized array', 'Array with named fields', 'Struct array', 'Field array'], 'correct' => 1],
        ['question' => 'What is masked array?', 'options' => ['Hidden array', 'Array with invalid/missing data', 'Mask array', 'Filtered array'], 'correct' => 1],
        ['question' => 'What is C-order?', 'options' => ['C style', 'Row-major order', 'C layout', 'Row order'], 'correct' => 1],
        ['question' => 'What is F-order?', 'options' => ['F style', 'Column-major order', 'Fortran layout', 'Column order'], 'correct' => 1],
        ['question' => 'What is view?', 'options' => ['Look at', 'Array sharing memory', 'Reference', 'Alias'], 'correct' => 1],
        ['question' => 'What is copy?', 'options' => ['Duplicate', 'Independent array copy', 'Clone', 'New array'], 'correct' => 1],
        ['question' => 'What does .copy() do?', 'options' => ['Copies data', 'Creates independent copy', 'Duplicates', 'Clones array'], 'correct' => 1],
        ['question' => 'What does np.memmap() create?', 'options' => ['Memory map', 'Memory-mapped file array', 'Mapped array', 'File array'], 'correct' => 1],
        ['question' => 'What does np.save() do?', 'options' => ['Saves file', 'Saves array to file', 'Export array', 'Store array'], 'correct' => 1],
        ['question' => 'What does np.load() do?', 'options' => ['Loads file', 'Loads array from file', 'Import array', 'Read array'], 'correct' => 1],
        ['question' => 'What does np.savez() do?', 'options' => ['Saves z', 'Saves multiple arrays', 'Archive arrays', 'Save zip'], 'correct' => 1],
        ['question' => 'What does np.vectorize() do?', 'options' => ['Makes vector', 'Vectorizes function', 'Vector function', 'Apply function'], 'correct' => 1],
        ['question' => 'What does np.apply_along_axis() do?', 'options' => ['Applies function', 'Applies function along axis', 'Axis function', 'Apply axis'], 'correct' => 1],
        ['question' => 'What is broadcasting rule?', 'options' => ['Send rule', 'Arrays aligned from trailing dimensions', 'Auto-size rule', 'Broadcast method'], 'correct' => 1],
    ]],
    ['label' => 'Advanced', 'questions' => [
        ['question' => 'What is ndarray structure?', 'options' => ['Array structure', 'Data pointer, shape, strides', 'Internal layout', 'Array internals'], 'correct' => 1],
        ['question' => 'What are strides?', 'options' => ['Steps', 'Bytes to jump for each dimension', 'Memory steps', 'Jump sizes'], 'correct' => 1],
        ['question' => 'What is as_strided()?', 'options' => ['Stride function', 'Creates view with custom strides', 'Stride manipulation', 'Custom view'], 'correct' => 1],
        ['question' => 'What is buffer protocol?', 'options' => ['Buffer interface', 'Python buffer interface', 'Memory protocol', 'Data protocol'], 'correct' => 1],
        ['question' => 'What is BLAS?', 'options' => ['Blast library', 'Basic Linear Algebra Subprograms', 'Math library', 'Linear library'], 'correct' => 1],
        ['question' => 'What is LAPACK?', 'options' => ['LA package', 'Linear Algebra Package', 'Math package', 'Linear library'], 'correct' => 1],
        ['question' => 'What is SIMD?', 'options' => ['Simple instruction', 'Single Instruction Multiple Data', 'Parallel instruction', 'Vector instruction'], 'correct' => 1],
        ['question' => 'What is generalized ufunc?', 'options' => ['General function', 'Ufunc operating on arrays', 'Generic ufunc', 'Gufunc'], 'correct' => 1],
        ['question' => 'How to create custom ufunc?', 'options' => ['Define function', 'Use Cython or C', 'Python decorator', 'Vectorize'], 'correct' => 1],
        ['question' => 'What does np.polynomial contain?', 'options' => ['Polynomial functions', 'Polynomial operations', 'Poly module', 'Polynomial tools'], 'correct' => 1],
        ['question' => 'What does np.interp() do?', 'options' => ['Interprets', 'Linear interpolation', 'Interpolates', 'Estimates values'], 'correct' => 1],
        ['question' => 'What does np.gradient() do?', 'options' => ['Calculates gradient', 'Numerical gradient', 'Derivative', 'Gradient calc'], 'correct' => 1],
        ['question' => 'What does np.diff() do?', 'options' => ['Difference', 'Discrete difference', 'Diff calc', 'Differences'], 'correct' => 1],
        ['question' => 'What does np.histogram() do?', 'options' => ['Creates histogram', 'Computes histogram', 'Histogram data', 'Bins data'], 'correct' => 1],
        ['question' => 'What is Generator API?', 'options' => ['Generate API', 'New random number API', 'Random generator', 'RNG API'], 'correct' => 1],
        ['question' => 'What is np.random.default_rng()?', 'options' => ['Default random', 'Creates Generator instance', 'Random generator', 'Default generator'], 'correct' => 1],
        ['question' => 'What advantage does Generator have?', 'options' => ['Generates better', 'Better performance and quality', 'New features', 'Modern API'], 'correct' => 1],
        ['question' => 'What is PyArray_Type?', 'options' => ['Array type', 'C API array type', 'Type object', 'Array class'], 'correct' => 1],
        ['question' => 'What is contiguous array?', 'options' => ['Continuous array', 'Memory in single block', 'Unbroken array', 'Sequential memory'], 'correct' => 1],
        ['question' => 'Why are strides important?', 'options' => ['For speed', 'Define memory layout', 'For indexing', 'Memory efficiency'], 'correct' => 1],
        ['question' => 'What is ufunc.outer()?', 'options' => ['Outer function', 'Outer product', 'All pairs operation', 'Cartesian product'], 'correct' => 1],
        ['question' => 'What is ufunc.reduce()?', 'options' => ['Reduces array', 'Applies along axis repeatedly', 'Reduction', 'Aggregate'], 'correct' => 1],
        ['question' => 'What is ufunc.accumulate()?', 'options' => ['Accumulates', 'Cumulative operation', 'Running operation', 'Accumulate result'], 'correct' => 1],
        ['question' => 'What does .flags show?', 'options' => ['Array flags', 'Memory layout information', 'Array properties', 'Status flags'], 'correct' => 1],
        ['question' => 'What is np.may_share_memory()?', 'options' => ['Share check', 'Tests if arrays share memory', 'Memory check', 'Shared test'], 'correct' => 1],
    ]],
    ['label' => 'Expert', 'questions' => [
        ['question' => 'What is PyArrayObject?', 'options' => ['Array object', 'C struct for ndarray', 'Array structure', 'C array'], 'correct' => 1],
        ['question' => 'What is npy_intp?', 'options' => ['NumPy int', 'Integer type for indexing', 'Index type', 'Pointer int'], 'correct' => 1],
        ['question' => 'What is __array_function__?', 'options' => ['Array function', 'Override NumPy functions', 'Function protocol', 'Dispatch method'], 'correct' => 1],
        ['question' => 'What is __array_ufunc__?', 'options' => ['Array ufunc', 'Override ufunc behavior', 'Ufunc protocol', 'Ufunc dispatch'], 'correct' => 1],
        ['question' => 'What is __array_priority__?', 'options' => ['Array priority', 'Determines operation precedence', 'Priority value', 'Precedence'], 'correct' => 1],
        ['question' => 'What is duck array?', 'options' => ['Duck typing', 'Array-like interface', 'Compatible array', 'Array protocol'], 'correct' => 1],
        ['question' => 'What is CuPy?', 'options' => ['Copy library', 'GPU NumPy', 'CUDA arrays', 'GPU library'], 'correct' => 1],
        ['question' => 'What is JAX?', 'options' => ['JAX library', 'Autograd and XLA library', 'ML library', 'Gradient library'], 'correct' => 1],
        ['question' => 'How does NumPy dispatch work?', 'options' => ['Sends arrays', '__array_function__ protocol', 'Function routing', 'Dispatch system'], 'correct' => 1],
        ['question' => 'What is memory alignment?', 'options' => ['Aligned memory', 'Memory address boundaries', 'Memory layout', 'Byte alignment'], 'correct' => 1],
        ['question' => 'Why is alignment important?', 'options' => ['For organization', 'For SIMD performance', 'For speed', 'For compatibility'], 'correct' => 1],
        ['question' => 'What is Meson?', 'options' => ['Build tool', 'NumPy build system', 'Compiler', 'Build framework'], 'correct' => 1],
        ['question' => 'What is IEEE 754?', 'options' => ['Standard', 'Floating-point standard', 'Float format', 'Number standard'], 'correct' => 1],
        ['question' => 'What is np.finfo?', 'options' => ['Float info', 'Floating-point type info', 'Float limits', 'Type information'], 'correct' => 1],
        ['question' => 'What is machine epsilon?', 'options' => ['Small number', 'Smallest representable difference', 'Float precision', 'Tiny value'], 'correct' => 1],
        ['question' => 'What is Kahan summation?', 'options' => ['Special sum', 'Compensated summation algorithm', 'Accurate sum', 'Precise addition'], 'correct' => 1],
        ['question' => 'What is pairwise summation?', 'options' => ['Pair sum', 'Hierarchical summation', 'Tree sum', 'Divide sum'], 'correct' => 1],
        ['question' => 'What is numerical stability?', 'options' => ['Stable numbers', 'Resistance to rounding errors', 'Accuracy', 'Precision'], 'correct' => 1],
        ['question' => 'What is scipy.sparse?', 'options' => ['Sparse library', 'Sparse matrix library', 'Sparse arrays', 'Sparse data'], 'correct' => 1],
        ['question' => 'What is Dask array?', 'options' => ['Dask library', 'Distributed NumPy arrays', 'Parallel arrays', 'Big arrays'], 'correct' => 1],
        ['question' => 'When to use Dask?', 'options' => ['Always', 'When data exceeds memory', 'For speed', 'For parallel'], 'correct' => 1],
        ['question' => 'What is NEP 18?', 'options' => ['NEP document', 'Array function protocol', 'Enhancement proposal', 'Protocol NEP'], 'correct' => 1],
        ['question' => 'What is NEP 13?', 'options' => ['NEP document', 'Ufunc override protocol', 'Enhancement proposal', 'Ufunc NEP'], 'correct' => 1],
        ['question' => 'What does spin do?', 'options' => ['Spins around', 'Developer workflow tool', 'Build tool', 'Test runner'], 'correct' => 1],
        ['question' => 'How to write C extension?', 'options' => ['C code', 'Use NumPy C API', 'Cython', 'Python C'], 'correct' => 1],
    ]],
];
require_once __DIR__ . '/quiz-engine.php';
