<?php
$page_title = 'Pandas Quiz – 100 Levels – CodeFoundry';
$active_page = 'training';
$quiz_title  = 'Pandas';
$quiz_slug   = 'pandas';
$quiz_tiers  = [
    ['label' => 'Introduction', 'questions' => [
        ['question' => 'What is Pandas?', 'options' => ['Panda library', 'Data analysis library', 'Animal library', 'Python library'], 'correct' => 1],
        ['question' => 'How do you import Pandas?', 'options' => ['import pandas', 'import pandas as pd', 'from pandas import *', 'import pd'], 'correct' => 1],
        ['question' => 'What is Series?', 'options' => ['Data series', '1D labeled array', 'List type', 'Data type'], 'correct' => 1],
        ['question' => 'What is DataFrame?', 'options' => ['Frame of data', '2D labeled data structure', 'Table', 'Data frame'], 'correct' => 1],
        ['question' => 'How to create DataFrame from dict?', 'options' => ['pd.DataFrame(dict)', 'pd.from_dict()', 'DataFrame(dict)', 'pd.dict()'], 'correct' => 0],
        ['question' => 'What does .shape return?', 'options' => ['Shape string', 'Tuple of dimensions', 'Size', 'Dimensions'], 'correct' => 1],
        ['question' => 'What does .dtypes show?', 'options' => ['Data types', 'Column data types', 'Type info', 'Types list'], 'correct' => 1],
        ['question' => 'What does .info() show?', 'options' => ['Information', 'DataFrame summary', 'Info data', 'Overview'], 'correct' => 1],
        ['question' => 'What does .describe() do?', 'options' => ['Describes data', 'Statistical summary', 'Description', 'Stats'], 'correct' => 1],
        ['question' => 'What does .head() show?', 'options' => ['Header', 'First 5 rows', 'Top rows', 'Beginning'], 'correct' => 1],
        ['question' => 'What does .tail() show?', 'options' => ['End', 'Last 5 rows', 'Bottom rows', 'Tail rows'], 'correct' => 1],
        ['question' => 'How to select column?', 'options' => ['df.column', 'df["column"]', 'Both A and B', 'df.get()'], 'correct' => 2],
        ['question' => 'What does .iloc[] do?', 'options' => ['Integer location', 'Integer-based indexing', 'Index location', 'Int loc'], 'correct' => 1],
        ['question' => 'What does .loc[] do?', 'options' => ['Location', 'Label-based indexing', 'Locate rows', 'Location index'], 'correct' => 1],
        ['question' => 'How to read CSV?', 'options' => ['pd.csv()', 'pd.read_csv()', 'pd.load_csv()', 'read_csv()'], 'correct' => 1],
        ['question' => 'How to write CSV?', 'options' => ['df.csv()', 'df.to_csv()', 'df.save_csv()', 'to_csv()'], 'correct' => 1],
        ['question' => 'How to read Excel?', 'options' => ['pd.excel()', 'pd.read_excel()', 'pd.load_excel()', 'read_excel()'], 'correct' => 1],
        ['question' => 'How to filter rows?', 'options' => ['df.filter()', 'df[df["col"] > 5]', 'df.where()', 'filter()'], 'correct' => 1],
        ['question' => 'How to add column?', 'options' => ['df.add()', 'df["new"] = values', 'df.append_col()', 'add_column()'], 'correct' => 1],
        ['question' => 'How to remove column?', 'options' => ['df.remove()', 'df.drop("col", axis=1)', 'df.delete()', 'remove()'], 'correct' => 1],
        ['question' => 'What is .columns?', 'options' => ['Column list', 'Column names Index', 'Columns array', 'Column index'], 'correct' => 1],
        ['question' => 'What is .index?', 'options' => ['Index list', 'Row labels Index', 'Row index', 'Index array'], 'correct' => 1],
        ['question' => 'What is NaN?', 'options' => ['Not a Name', 'Not a Number', 'Null value', 'Missing'], 'correct' => 1],
        ['question' => 'How to check for NaN?', 'options' => ['pd.isnan()', 'pd.isnull()', 'pd.na()', 'isnan()'], 'correct' => 1],
        ['question' => 'What does pd.notnull() do?', 'options' => ['Checks not null', 'Returns non-null boolean', 'Not null check', 'Valid check'], 'correct' => 1],
    ]],
    ['label' => 'Beginner', 'questions' => [
        ['question' => 'What does .dropna() do?', 'options' => ['Drops column', 'Removes missing values', 'Drop nulls', 'Remove NaN'], 'correct' => 1],
        ['question' => 'What does .fillna() do?', 'options' => ['Fills array', 'Fills missing values', 'Fill nulls', 'Replace NaN'], 'correct' => 1],
        ['question' => 'What does .isna() return?', 'options' => ['NA values', 'Boolean mask of NaN', 'Missing check', 'NA mask'], 'correct' => 1],
        ['question' => 'What does .interpolate() do?', 'options' => ['Interprets', 'Fills NaN with interpolated values', 'Estimates', 'Interpolates'], 'correct' => 1],
        ['question' => 'What does .sort_values() do?', 'options' => ['Sorts by value', 'Sorts by column values', 'Orders values', 'Sort data'], 'correct' => 1],
        ['question' => 'What does .sort_index() do?', 'options' => ['Sorts index', 'Sorts by index', 'Orders index', 'Index sort'], 'correct' => 1],
        ['question' => 'What does .groupby() do?', 'options' => ['Groups data', 'Groups rows by column', 'Group by', 'Grouping'], 'correct' => 1],
        ['question' => 'What can you do after groupby?', 'options' => ['Nothing', 'Aggregate functions', 'Only count', 'Only sum'], 'correct' => 1],
        ['question' => 'What does .agg() do?', 'options' => ['Aggregates', 'Applies aggregation functions', 'Aggregate data', 'Agg functions'], 'correct' => 1],
        ['question' => 'What does .apply() do?', 'options' => ['Applies value', 'Applies function', 'Apply function', 'Function apply'], 'correct' => 1],
        ['question' => 'What does .value_counts() do?', 'options' => ['Counts values', 'Counts unique values', 'Value count', 'Unique counts'], 'correct' => 1],
        ['question' => 'What does .merge() do?', 'options' => ['Merges data', 'Joins DataFrames', 'Merge frames', 'Join data'], 'correct' => 1],
        ['question' => 'What is how parameter in merge?', 'options' => ['Method', 'Join type', 'How to merge', 'Join method'], 'correct' => 1],
        ['question' => 'What does how="inner" do?', 'options' => ['Inner join', 'Intersection of keys', 'Inner merge', 'Common keys'], 'correct' => 1],
        ['question' => 'What does how="left" do?', 'options' => ['Left join', 'All left keys', 'Left merge', 'Keep left'], 'correct' => 1],
        ['question' => 'What does pd.concat() do?', 'options' => ['Connects', 'Concatenates DataFrames', 'Concat frames', 'Combine'], 'correct' => 1],
        ['question' => 'What is axis in concat?', 'options' => ['Direction', 'Concatenation axis', 'Join axis', 'Axis direction'], 'correct' => 1],
        ['question' => 'What does .join() do?', 'options' => ['Joins data', 'Joins on index', 'Join frames', 'Index join'], 'correct' => 1],
        ['question' => 'What does .astype() do?', 'options' => ['Assigns type', 'Converts data type', 'Cast type', 'Type convert'], 'correct' => 1],
        ['question' => 'What is category dtype?', 'options' => ['Category type', 'Categorical data type', 'Cat type', 'Categorical'], 'correct' => 1],
        ['question' => 'What does pd.to_datetime() do?', 'options' => ['To date', 'Converts to datetime', 'Date convert', 'DateTime parse'], 'correct' => 1],
        ['question' => 'What is str accessor?', 'options' => ['String access', 'String methods', 'Text methods', 'String ops'], 'correct' => 1],
        ['question' => 'What does .str.lower() do?', 'options' => ['Lowers', 'Converts to lowercase', 'Lower case', 'Make lower'], 'correct' => 1],
        ['question' => 'What does .str.contains() do?', 'options' => ['Contains check', 'Tests if string contains substring', 'Check contains', 'String search'], 'correct' => 1],
        ['question' => 'What does .query() do?', 'options' => ['Queries data', 'Filters with string expression', 'Query filter', 'String filter'], 'correct' => 1],
    ]],
    ['label' => 'Intermediate', 'questions' => [
        ['question' => 'What does .transform() do in groupby?', 'options' => ['Transforms data', 'Returns transformed values', 'Group transform', 'Apply transform'], 'correct' => 1],
        ['question' => 'What does .filter() do in groupby?', 'options' => ['Filters groups', 'Filters groups by condition', 'Group filter', 'Filter condition'], 'correct' => 1],
        ['question' => 'What is named aggregation?', 'options' => ['Named agg', 'Aggregation with custom names', 'Agg naming', 'Custom agg names'], 'correct' => 1],
        ['question' => 'What does .pivot_table() do?', 'options' => ['Pivots data', 'Creates pivot table', 'Pivot frame', 'Table pivot'], 'correct' => 1],
        ['question' => 'What does .melt() do?', 'options' => ['Melts data', 'Unpivots DataFrame', 'Wide to long', 'Melt frame'], 'correct' => 1],
        ['question' => 'What does .stack() do?', 'options' => ['Stacks data', 'Pivots columns to rows', 'Stack columns', 'Column to row'], 'correct' => 1],
        ['question' => 'What does .unstack() do?', 'options' => ['Unstacks', 'Pivots rows to columns', 'Row to column', 'Unstack rows'], 'correct' => 1],
        ['question' => 'What does .explode() do?', 'options' => ['Explodes data', 'Transforms lists to rows', 'List to rows', 'Expand lists'], 'correct' => 1],
        ['question' => 'What does .rolling() do?', 'options' => ['Rolls data', 'Creates rolling window', 'Window function', 'Rolling calc'], 'correct' => 1],
        ['question' => 'What does .expanding() do?', 'options' => ['Expands data', 'Creates expanding window', 'Expanding window', 'Cumulative window'], 'correct' => 1],
        ['question' => 'What does .ewm() do?', 'options' => ['EW mean', 'Exponentially weighted window', 'Weighted window', 'Exponential window'], 'correct' => 1],
        ['question' => 'What is pd.Categorical?', 'options' => ['Category type', 'Categorical data type', 'Categorical class', 'Cat type'], 'correct' => 1],
        ['question' => 'What is dt accessor?', 'options' => ['Date access', 'Datetime properties', 'Time methods', 'DateTime accessor'], 'correct' => 1],
        ['question' => 'What does .resample() do?', 'options' => ['Resamples', 'Time series resampling', 'Resample time', 'Time grouping'], 'correct' => 1],
        ['question' => 'What is MultiIndex?', 'options' => ['Multiple index', 'Hierarchical index', 'Multi-level index', 'Nested index'], 'correct' => 1],
        ['question' => 'How to create MultiIndex?', 'options' => ['pd.MultiIndex()', 'pd.MultiIndex.from_tuples()', 'multi_index()', 'create_multi()'], 'correct' => 1],
        ['question' => 'What is pd.IndexSlice?', 'options' => ['Index slice', 'Helper for slicing MultiIndex', 'Slice helper', 'Multi slice'], 'correct' => 1],
        ['question' => 'What is better: apply or vectorization?', 'options' => ['Apply', 'Vectorization', 'Same speed', 'Depends'], 'correct' => 1],
        ['question' => 'What does pd.eval() do?', 'options' => ['Evaluates', 'Evaluates expression efficiently', 'Fast eval', 'Eval expression'], 'correct' => 1],
        ['question' => 'What is df.style?', 'options' => ['DataFrame style', 'Styling interface', 'Style object', 'Format helper'], 'correct' => 1],
        ['question' => 'What does .style.highlight_max() do?', 'options' => ['Highlights', 'Highlights maximum values', 'Max highlight', 'Highlight max'], 'correct' => 1],
        ['question' => 'How to read from SQL?', 'options' => ['pd.sql()', 'pd.read_sql()', 'pd.load_sql()', 'read_sql()'], 'correct' => 1],
        ['question' => 'What is chunksize parameter?', 'options' => ['Chunk size', 'Reads data in chunks', 'Chunk read', 'Batch size'], 'correct' => 1],
        ['question' => 'Why use category dtype?', 'options' => ['Categories', 'Saves memory for repeated values', 'Faster', 'Better display'], 'correct' => 1],
        ['question' => 'What does .memory_usage() show?', 'options' => ['Memory use', 'Memory consumption', 'Usage stats', 'Memory info'], 'correct' => 1],
    ]],
    ['label' => 'Advanced', 'questions' => [
        ['question' => 'What is BlockManager?', 'options' => ['Block manager', 'Internal storage structure', 'Manager class', 'Data manager'], 'correct' => 1],
        ['question' => 'What is copy-on-write?', 'options' => ['Copy method', 'Defers copy until modification', 'Write copy', 'CoW semantics'], 'correct' => 1],
        ['question' => 'When was CoW introduced?', 'options' => ['Pandas 1.0', 'Pandas 2.0', 'Pandas 1.5', 'Pandas 3.0'], 'correct' => 1],
        ['question' => 'What is ExtensionArray?', 'options' => ['Array extension', 'Custom array type', 'Extended array', 'Custom dtype'], 'correct' => 1],
        ['question' => 'What is ExtensionDtype?', 'options' => ['Extended type', 'Custom dtype interface', 'Extension type', 'Custom type'], 'correct' => 1],
        ['question' => 'What is custom accessor?', 'options' => ['Custom access', 'Custom namespace like .str', 'Access method', 'Custom namespace'], 'correct' => 1],
        ['question' => 'What is Polars?', 'options' => ['Polar library', 'Fast DataFrame alternative', 'Data library', 'Pandas competitor'], 'correct' => 1],
        ['question' => 'What does .pipe() do?', 'options' => ['Pipes data', 'Chains function calls', 'Pipeline', 'Chaining helper'], 'correct' => 1],
        ['question' => 'What is Dask DataFrame?', 'options' => ['Dask frame', 'Parallel/larger-than-memory DataFrame', 'Big data frame', 'Distributed frame'], 'correct' => 1],
        ['question' => 'What is Vaex?', 'options' => ['Vaex library', 'Out-of-core DataFrame library', 'Large data', 'Data library'], 'correct' => 1],
        ['question' => 'What is modin?', 'options' => ['Modern pandas', 'Parallel pandas', 'Modified pandas', 'Fast pandas'], 'correct' => 1],
        ['question' => 'What is pd.testing.assert_frame_equal()?', 'options' => ['Tests equal', 'Asserts DataFrames equal', 'Frame test', 'Equality test'], 'correct' => 1],
        ['question' => 'What is pd.Int64Dtype()?', 'options' => ['Int64 type', 'Nullable integer type', 'Integer dtype', 'Int type'], 'correct' => 1],
        ['question' => 'What is pd.NA?', 'options' => ['NA value', 'Nullable missing value', 'New NaN', 'Missing marker'], 'correct' => 1],
        ['question' => 'How does pd.NA differ from np.nan?', 'options' => ['No difference', 'Works with nullable dtypes', 'Better NA', 'Propagates differently'], 'correct' => 1],
        ['question' => 'What is pd.ArrowDtype?', 'options' => ['Arrow type', 'PyArrow-backed dtype', 'Arrow dtype', 'Arrow data'], 'correct' => 1],
        ['question' => 'What is advantage of ArrowDtype?', 'options' => ['Newer', 'Better performance/memory', 'Faster', 'More features'], 'correct' => 1],
        ['question' => 'What is method chaining?', 'options' => ['Chain methods', 'Calling methods sequentially', 'Method sequence', 'Chaining calls'], 'correct' => 1],
        ['question' => 'What is pandas-stubs?', 'options' => ['Pandas stubs', 'Type hints for pandas', 'Type stubs', 'Typing support'], 'correct' => 1],
        ['question' => 'How to profile pandas code?', 'options' => ['Profile tool', 'Use profiling tools', 'Profiler', 'Performance tools'], 'correct' => 1],
        ['question' => 'When to use chunking?', 'options' => ['Always', 'When data too large for memory', 'For speed', 'For parallel'], 'correct' => 1],
        ['question' => 'What changed in Pandas 2.0?', 'options' => ['Everything', 'CoW, PyArrow, improved dtypes', 'Performance', 'New features'], 'correct' => 1],
        ['question' => 'What is ArrayManager?', 'options' => ['Array manager', 'Alternative to BlockManager', 'Manager type', 'Array storage'], 'correct' => 1],
        ['question' => 'What is zero-copy?', 'options' => ['No copy', 'Operations without copying', 'Copy-free', 'No duplication'], 'correct' => 1],
        ['question' => 'What is pandas-profiling?', 'options' => ['Profiling tool', 'Generates data profile reports', 'Profile library', 'Data profiler'], 'correct' => 1],
    ]],
    ['label' => 'Expert', 'questions' => [
        ['question' => 'What is BlockManager internals?', 'options' => ['Block storage', 'Stores data in typed blocks', 'Internal structure', 'Block system'], 'correct' => 1],
        ['question' => 'Why transition to ArrayManager?', 'options' => ['Newer', 'Simpler, better CoW support', 'Faster', 'Better memory'], 'correct' => 1],
        ['question' => 'What is PyArrow backend?', 'options' => ['Backend', 'Uses PyArrow for storage', 'Arrow storage', 'PyArrow engine'], 'correct' => 1],
        ['question' => 'What is zero-copy with PyArrow?', 'options' => ['No copy', 'Share memory without copying', 'Arrow zero-copy', 'Shared memory'], 'correct' => 1],
        ['question' => 'How to create custom ExtensionArray?', 'options' => ['Subclass', 'Subclass ExtensionArray', 'Custom class', 'Extend array'], 'correct' => 1],
        ['question' => 'What is Index hierarchy?', 'options' => ['Index levels', 'Index inheritance structure', 'Index classes', 'Index types'], 'correct' => 1],
        ['question' => 'How does Index enable fast lookup?', 'options' => ['Sorting', 'Hashtable/B-tree', 'Indexing', 'Fast search'], 'correct' => 1],
        ['question' => 'What is hash aggregation?', 'options' => ['Hash method', 'Groupby using hashtable', 'Hash grouping', 'Hashtable agg'], 'correct' => 1],
        ['question' => 'What is sort aggregation?', 'options' => ['Sort method', 'Groupby using sorting', 'Sort grouping', 'Sort agg'], 'correct' => 1],
        ['question' => 'What is merge algorithm?', 'options' => ['Merge method', 'Hash join or sort merge', 'Join algorithm', 'Merge technique'], 'correct' => 1],
        ['question' => 'What is index alignment?', 'options' => ['Align index', 'Auto-aligns by index in operations', 'Index match', 'Alignment'], 'correct' => 1],
        ['question' => 'Why is pandas not thread-safe?', 'options' => ['Old design', 'Python GIL limitations', 'Not parallel', 'Single thread'], 'correct' => 1],
        ['question' => 'What is pandarallel?', 'options' => ['Parallel library', 'Parallelizes pandas operations', 'Parallel pandas', 'Threading tool'], 'correct' => 1],
        ['question' => 'What is swifter?', 'options' => ['Faster library', 'Auto-parallelizes apply', 'Speed library', 'Fast apply'], 'correct' => 1],
        ['question' => 'What DST issues exist?', 'options' => ['Time changes', 'Daylight saving time ambiguity', 'DST bugs', 'Time problems'], 'correct' => 1],
        ['question' => 'What is ambiguous time?', 'options' => ['Unclear time', 'Time during DST transition', 'DST time', 'Ambiguous DST'], 'correct' => 1],
        ['question' => 'What is fold parameter?', 'options' => ['Fold time', 'Disambiguates DST times', 'DST parameter', 'Time fold'], 'correct' => 1],
        ['question' => 'What floating-point issues exist?', 'options' => ['Float errors', 'Rounding in groupby/merge', 'Precision loss', 'Float problems'], 'correct' => 1],
        ['question' => 'What is ydata-profiling?', 'options' => ['Profile tool', 'Renamed pandas-profiling', 'Data profiler', 'Profile library'], 'correct' => 1],
        ['question' => 'How to benchmark pandas?', 'options' => ['Time code', 'Use timeit or profilers', 'Benchmark tool', 'Measure performance'], 'correct' => 1],
        ['question' => 'What is pandas internal cache?', 'options' => ['Cache system', 'Caches computed properties', 'Internal cache', 'Property cache'], 'correct' => 1],
        ['question' => 'What is SparseArray?', 'options' => ['Sparse data', 'Memory-efficient sparse data', 'Sparse type', 'Sparse storage'], 'correct' => 1],
        ['question' => 'When to use SparseArray?', 'options' => ['Always', 'Data mostly one value', 'Sparse data', 'Missing data'], 'correct' => 1],
        ['question' => 'What is categorical memory savings?', 'options' => ['Saves memory', 'Stores categories once', 'Less memory', 'Efficient storage'], 'correct' => 1],
        ['question' => 'What is pandas deprecation process?', 'options' => ['Removes features', 'Warnings then removal', 'Deprecation policy', 'Feature removal'], 'correct' => 1],
    ]],
];
require_once __DIR__ . '/quiz-engine.php';
