<?php
$page_title = 'PHP Quiz – 100 Levels – CodeFoundry';
$active_page = 'training';
$quiz_title  = 'PHP';
$quiz_slug   = 'php-quiz';
$quiz_tiers  = [
    ['label' => 'Introduction', 'questions' => [
        ['question' => 'What does PHP stand for?', 'options' => ['Personal Home Page', 'PHP: Hypertext Preprocessor', 'Private Hosting Platform', 'Program Hypertext Parser'], 'correct' => 1],
        ['question' => 'Which is the correct way to start a PHP code block?', 'options' => ['<php>', '<?php', '<script>', '<%'], 'correct' => 1],
        ['question' => 'Which function outputs text in PHP?', 'options' => ['echo', 'output', 'display', 'show'], 'correct' => 0],
        ['question' => 'How do you declare a variable in PHP?', 'options' => ['var name', 'variable name', '$name', '@name'], 'correct' => 2],
        ['question' => 'Which operator concatenates strings in PHP?', 'options' => ['+', '.', '&', ','], 'correct' => 1],
        ['question' => 'Which is NOT a PHP data type?', 'options' => ['integer', 'string', 'float', 'character'], 'correct' => 3],
        ['question' => 'How do you start a single-line comment in PHP?', 'options' => ['//', '<!--', '#!', '/*'], 'correct' => 0],
        ['question' => 'Which statement checks a condition in PHP?', 'options' => ['check', 'if', 'when', 'test'], 'correct' => 1],
        ['question' => 'What keyword is used for multiple condition branches?', 'options' => ['switch', 'select', 'case', 'choose'], 'correct' => 0],
        ['question' => 'Which loop executes at least once?', 'options' => ['for', 'while', 'do-while', 'foreach'], 'correct' => 2],
        ['question' => 'How do you create an indexed array?', 'options' => ['array(1, 2, 3)', 'array[1, 2, 3]', '{1, 2, 3}', 'list(1, 2, 3)'], 'correct' => 0],
        ['question' => 'Which function returns the number of elements in an array?', 'options' => ['length()', 'size()', 'count()', 'num()'], 'correct' => 2],
        ['question' => 'Which function adds an element to the end of an array?', 'options' => ['array_add()', 'array_push()', 'array_append()', 'push()'], 'correct' => 1],
        ['question' => 'Which function removes the last element from an array?', 'options' => ['array_pop()', 'array_remove()', 'array_delete()', 'pop()'], 'correct' => 0],
        ['question' => 'Which function merges two arrays?', 'options' => ['array_combine()', 'array_merge()', 'array_join()', 'merge()'], 'correct' => 1],
        ['question' => 'Which function checks if a value exists in an array?', 'options' => ['in_array()', 'array_exists()', 'array_has()', 'exists()'], 'correct' => 0],
        ['question' => 'Which function returns the length of a string?', 'options' => ['length()', 'strlen()', 'size()', 'str_length()'], 'correct' => 1],
        ['question' => 'Which function converts a string to uppercase?', 'options' => ['uppercase()', 'strtoupper()', 'to_upper()', 'upper()'], 'correct' => 1],
        ['question' => 'Which function replaces text in a string?', 'options' => ['str_replace()', 'replace()', 'string_replace()', 'str_change()'], 'correct' => 0],
        ['question' => 'Which superglobal holds URL parameters?', 'options' => ['$_POST', '$_GET', '$_REQUEST', '$_URL'], 'correct' => 1],
        ['question' => 'Which function prevents XSS attacks?', 'options' => ['htmlspecialchars()', 'escape()', 'sanitize()', 'clean()'], 'correct' => 0],
        ['question' => 'Which function checks if a variable is set?', 'options' => ['is_set()', 'isset()', 'defined()', 'exists()'], 'correct' => 1],
        ['question' => 'Which keyword includes a file and requires it?', 'options' => ['import', 'include', 'require', 'load'], 'correct' => 2],
        ['question' => 'Which function defines a constant?', 'options' => ['const()', 'define()', 'constant()', 'set_const()'], 'correct' => 1],
        ['question' => 'Which comment style is multi-line in PHP?', 'options' => ['//', '#', '/* */', '<!-- -->'], 'correct' => 2],
        ['question' => 'Which superglobal contains server information?', 'options' => ['$_ENV', '$_SERVER', '$_SYSTEM', '$_INFO'], 'correct' => 1],
        ['question' => 'Which function checks if a variable is empty?', 'options' => ['is_empty()', 'empty()', 'null()', 'blank()'], 'correct' => 1],
        ['question' => 'Which function destroys a variable?', 'options' => ['delete()', 'remove()', 'unset()', 'destroy()'], 'correct' => 2],
    ]],
    ['label' => 'Beginner', 'questions' => [
        ['question' => 'How do you define a default parameter in a function?', 'options' => ['function test(default $x = 5)', 'function test($x = 5)', 'function test($x default 5)', 'function test($x := 5)'], 'correct' => 1],
        ['question' => 'Which keyword makes a variable available inside a function?', 'options' => ['extern', 'global', 'public', 'shared'], 'correct' => 1],
        ['question' => 'What does the static keyword do in a function variable?', 'options' => ['Makes it constant', 'Preserves value between calls', 'Makes it private', 'Makes it global'], 'correct' => 1],
        ['question' => 'How do you pass a variable by reference?', 'options' => ['function test(*$var)', 'function test(&$var)', 'function test(ref $var)', 'function test(@$var)'], 'correct' => 1],
        ['question' => 'What is the result of "5" + 3 in PHP?', 'options' => ['53', '8', 'Error', '5'], 'correct' => 1],
        ['question' => 'Which comparison operator checks type as well?', 'options' => ['==', '===', '=', '!='], 'correct' => 1],
        ['question' => 'What does the ?? operator do?', 'options' => ['Null check', 'Null coalescing', 'Not null', 'Null assignment'], 'correct' => 1],
        ['question' => 'What is the syntax for the ternary operator?', 'options' => ['condition ? true : false', 'if condition then true else false', 'condition then true else false', 'true if condition else false'], 'correct' => 0],
        ['question' => 'Which PHP version introduced the match expression?', 'options' => ['PHP 7.4', 'PHP 8.0', 'PHP 8.1', 'PHP 7.3'], 'correct' => 1],
        ['question' => 'What is heredoc in PHP?', 'options' => ['A comment style', 'A multi-line string syntax', 'A loop type', 'An array type'], 'correct' => 1],
        ['question' => 'Which function formats a string with placeholders?', 'options' => ['format()', 'sprintf()', 'string_format()', 'fmt()'], 'correct' => 1],
        ['question' => 'Which function returns the current Unix timestamp?', 'options' => ['now()', 'time()', 'timestamp()', 'current_time()'], 'correct' => 1],
        ['question' => 'Which function reads an entire file into a string?', 'options' => ['file_read()', 'read_file()', 'file_get_contents()', 'get_file()'], 'correct' => 2],
        ['question' => 'Which function writes a string to a file?', 'options' => ['file_write()', 'write_file()', 'file_put_contents()', 'put_file()'], 'correct' => 2],
        ['question' => 'How do you open a file for reading?', 'options' => ['fopen($file, "r")', 'open($file, "read")', 'file_open($file)', 'read($file)'], 'correct' => 0],
        ['question' => 'Which function sets the error reporting level?', 'options' => ['set_errors()', 'error_level()', 'error_reporting()', 'set_error_level()'], 'correct' => 2],
        ['question' => 'Which block catches exceptions?', 'options' => ['catch', 'except', 'error', 'handle'], 'correct' => 0],
        ['question' => 'Which keyword throws an exception?', 'options' => ['raise', 'throw', 'error', 'exception'], 'correct' => 1],
        ['question' => 'Which function tests a regular expression match?', 'options' => ['regex_match()', 'preg_match()', 'match()', 'regex()'], 'correct' => 1],
        ['question' => 'Which function starts a session?', 'options' => ['start_session()', 'session_begin()', 'session_start()', 'begin_session()'], 'correct' => 2],
        ['question' => 'Which superglobal stores session data?', 'options' => ['$_SESSION', '$_COOKIE', '$_DATA', '$_STATE'], 'correct' => 0],
        ['question' => 'Which function sets a cookie?', 'options' => ['set_cookie()', 'setcookie()', 'cookie()', 'create_cookie()'], 'correct' => 1],
        ['question' => 'Which function encodes data to JSON?', 'options' => ['to_json()', 'json_encode()', 'encode_json()', 'jsonify()'], 'correct' => 1],
        ['question' => 'Which function decodes JSON to PHP?', 'options' => ['from_json()', 'json_decode()', 'decode_json()', 'parse_json()'], 'correct' => 1],
        ['question' => 'What does the finally block do?', 'options' => ['Catches all errors', 'Always executes after try/catch', 'Ends the script', 'Logs errors'], 'correct' => 1],
        ['question' => 'Which function replaces using regex?', 'options' => ['preg_replace()', 'regex_replace()', 'str_replace_regex()', 'replace_regex()'], 'correct' => 0],
        ['question' => 'Which function splits a string by regex?', 'options' => ['split()', 'preg_split()', 'regex_split()', 'str_split_regex()'], 'correct' => 1],
    ]],
    ['label' => 'Intermediate', 'questions' => [
        ['question' => 'Which keyword defines a class in PHP?', 'options' => ['object', 'class', 'define', 'type'], 'correct' => 1],
        ['question' => 'What is the constructor method name in PHP?', 'options' => ['__init()', '__construct()', 'constructor()', '__new()'], 'correct' => 1],
        ['question' => 'Which visibility modifier is most restrictive?', 'options' => ['public', 'protected', 'private', 'internal'], 'correct' => 2],
        ['question' => 'What does the static keyword mean for a method?', 'options' => ['Cannot change', 'Called without object instance', 'Cannot be inherited', 'Always returns same value'], 'correct' => 1],
        ['question' => 'Which keyword prevents a class from being extended?', 'options' => ['sealed', 'final', 'static', 'const'], 'correct' => 1],
        ['question' => 'Which keyword defines a method that must be implemented?', 'options' => ['virtual', 'abstract', 'pure', 'required'], 'correct' => 1],
        ['question' => 'What is an interface in PHP?', 'options' => ['A base class', 'A contract for methods', 'A namespace', 'A module'], 'correct' => 1],
        ['question' => 'What is a trait in PHP?', 'options' => ['A type of variable', 'A reusable code block', 'An interface', 'A namespace'], 'correct' => 1],
        ['question' => 'Which keyword extends a class?', 'options' => ['inherits', 'extends', 'from', 'derives'], 'correct' => 1],
        ['question' => 'Which keyword implements an interface?', 'options' => ['uses', 'implements', 'applies', 'adopts'], 'correct' => 1],
        ['question' => 'What does __toString() do?', 'options' => ['Converts object to string', 'Gets class name', 'Serializes object', 'Prints object'], 'correct' => 0],
        ['question' => 'When is __get() called?', 'options' => ['Accessing public property', 'Accessing inaccessible property', 'Setting a property', 'Deleting a property'], 'correct' => 1],
        ['question' => 'What does static:: refer to?', 'options' => ['Parent class', 'Current class', 'Called class (late static binding)', 'Base class'], 'correct' => 2],
        ['question' => 'How do you create an anonymous class?', 'options' => ['new class { }', 'anonymous class { }', 'class() { }', 'new anonymous { }'], 'correct' => 0],
        ['question' => 'What is a closure in PHP?', 'options' => ['A private method', 'An anonymous function', 'A sealed class', 'A final method'], 'correct' => 1],
        ['question' => 'Which keyword imports variables into a closure?', 'options' => ['import', 'use', 'include', 'with'], 'correct' => 1],
        ['question' => 'What does yield do in a function?', 'options' => ['Returns a value', 'Creates a generator', 'Throws an error', 'Ends the function'], 'correct' => 1],
        ['question' => 'Which PHP version introduced scalar type declarations?', 'options' => ['PHP 5.6', 'PHP 7.0', 'PHP 7.4', 'PHP 8.0'], 'correct' => 1],
        ['question' => 'What syntax denotes a nullable type?', 'options' => ['?int', 'int?', 'null|int', 'int|null'], 'correct' => 0],
        ['question' => 'Which PHP version introduced named arguments?', 'options' => ['PHP 7.4', 'PHP 8.0', 'PHP 8.1', 'PHP 7.3'], 'correct' => 1],
        ['question' => 'What are attributes in PHP 8?', 'options' => ['Class properties', 'Metadata annotations', 'Method parameters', 'Constants'], 'correct' => 1],
        ['question' => 'What is constructor property promotion?', 'options' => ['Making constructor public', 'Declaring properties in constructor params', 'Promoting methods to static', 'Inheriting constructors'], 'correct' => 1],
        ['question' => 'Which function applies a callback to array elements?', 'options' => ['array_apply()', 'array_map()', 'array_each()', 'array_callback()'], 'correct' => 1],
        ['question' => 'Which function filters array elements?', 'options' => ['array_select()', 'array_filter()', 'array_where()', 'array_find()'], 'correct' => 1],
        ['question' => 'Which function reduces array to single value?', 'options' => ['array_fold()', 'array_reduce()', 'array_combine()', 'array_merge()'], 'correct' => 1],
        ['question' => 'What is PDO in PHP?', 'options' => ['PHP Data Objects', 'Persistent Data Output', 'Portable Database Operations', 'PHP Database Output'], 'correct' => 0],
        ['question' => 'What does Composer do?', 'options' => ['Compiles PHP', 'Manages dependencies', 'Tests code', 'Optimizes code'], 'correct' => 1],
        ['question' => 'What is PSR-4?', 'options' => ['Coding standard', 'Autoloading standard', 'Testing standard', 'Security standard'], 'correct' => 1],
    ]],
    ['label' => 'Advanced', 'questions' => [
        ['question' => 'What is the Zend Engine?', 'options' => ['A web server', 'PHP runtime engine', 'A database', 'A framework'], 'correct' => 1],
        ['question' => 'What is a zval?', 'options' => ['A function', 'A variable container structure', 'A class', 'An operator'], 'correct' => 1],
        ['question' => 'What is reference counting in PHP?', 'options' => ['Counting variables', 'Memory management technique', 'Performance metric', 'Error counting'], 'correct' => 1],
        ['question' => 'What is copy-on-write in PHP?', 'options' => ['File operation', 'Memory optimization technique', 'Array function', 'String operation'], 'correct' => 1],
        ['question' => 'What does OPcache do?', 'options' => ['Caches database queries', 'Caches compiled opcode', 'Caches files', 'Caches sessions'], 'correct' => 1],
        ['question' => 'How does OPcache improve performance?', 'options' => ['Faster database', 'Skips compilation step', 'Compresses files', 'Optimizes loops'], 'correct' => 1],
        ['question' => 'Which PHP version introduced JIT?', 'options' => ['PHP 7.4', 'PHP 8.0', 'PHP 8.1', 'PHP 8.2'], 'correct' => 1],
        ['question' => 'What does JIT stand for?', 'options' => ['Jump In Time', 'Just In Time', 'Join In Thread', 'Jump Instruction Table'], 'correct' => 1],
        ['question' => 'What are Fibers in PHP 8.1?', 'options' => ['String operations', 'Low-level concurrency primitives', 'Network protocols', 'File types'], 'correct' => 1],
        ['question' => 'Which PHP version introduced Enums?', 'options' => ['PHP 8.0', 'PHP 8.1', 'PHP 8.2', 'PHP 7.4'], 'correct' => 1],
        ['question' => 'What is a backed enum?', 'options' => ['An abstract enum', 'Enum with scalar values', 'Enum with methods', 'Private enum'], 'correct' => 1],
        ['question' => 'Which PHP version introduced readonly properties?', 'options' => ['PHP 8.0', 'PHP 8.1', 'PHP 8.2', 'PHP 7.4'], 'correct' => 1],
        ['question' => 'Which PHP version introduced readonly classes?', 'options' => ['PHP 8.0', 'PHP 8.1', 'PHP 8.2', 'PHP 8.3'], 'correct' => 2],
        ['question' => 'What is an intersection type?', 'options' => ['Type A or B', 'Type A and B', 'Type not A', 'Any type'], 'correct' => 1],
        ['question' => 'What does the never return type indicate?', 'options' => ['Returns null', 'Never returns normally', 'Returns void', 'Returns false'], 'correct' => 1],
        ['question' => 'What is first-class callable syntax?', 'options' => ['Best function', 'Callable reference syntax', 'Static function', 'Private function'], 'correct' => 1],
        ['question' => 'What is the Repository pattern?', 'options' => ['Git pattern', 'Data access abstraction', 'File storage', 'Caching strategy'], 'correct' => 1],
        ['question' => 'What is dependency injection?', 'options' => ['Installing packages', 'Passing dependencies to objects', 'Extending classes', 'Using traits'], 'correct' => 1],
        ['question' => 'What is middleware in PHP?', 'options' => ['Database layer', 'Request/response filter layer', 'Template engine', 'Router'], 'correct' => 1],
        ['question' => 'What is PSR-15?', 'options' => ['Logging standard', 'HTTP request handler standard', 'Autoloading', 'Caching'], 'correct' => 1],
        ['question' => 'What is ReactPHP?', 'options' => ['JavaScript library', 'Async event-driven PHP library', 'Template engine', 'ORM'], 'correct' => 1],
        ['question' => 'How do you prevent SQL injection?', 'options' => ['Escaping strings', 'Prepared statements', 'Both A and B', 'Validating input'], 'correct' => 2],
        ['question' => 'Which function hashes passwords securely?', 'options' => ['md5()', 'sha1()', 'password_hash()', 'hash()'], 'correct' => 2],
        ['question' => 'Which function verifies a password hash?', 'options' => ['password_check()', 'password_verify()', 'verify_password()', 'check_password()'], 'correct' => 1],
        ['question' => 'What does random_bytes() generate?', 'options' => ['Random string', 'Cryptographically secure random bytes', 'Random number', 'UUID'], 'correct' => 1],
        ['question' => 'What is APCu?', 'options' => ['Database', 'User cache for PHP', 'Web server', 'Framework'], 'correct' => 1],
        ['question' => 'What is the purpose of Redis in PHP?', 'options' => ['Web server', 'In-memory data store/cache', 'Database', 'Template engine'], 'correct' => 1],
        ['question' => 'What does Xdebug provide?', 'options' => ['Production optimization', 'Debugging and profiling', 'Caching', 'Encryption'], 'correct' => 1],
    ]],
    ['label' => 'Expert', 'questions' => [
        ['question' => 'What is PHP-FPM?', 'options' => ['PHP Framework', 'FastCGI Process Manager', 'PHP File Manager', 'PHP Frontend Module'], 'correct' => 1],
        ['question' => 'What are PHP-FPM pools?', 'options' => ['Database pools', 'Separate worker process groups', 'Memory pools', 'Thread pools'], 'correct' => 1],
        ['question' => 'What is a Zend Extension?', 'options' => ['PHP library', 'Low-level PHP extension type', 'Framework', 'IDE plugin'], 'correct' => 1],
        ['question' => 'What is ZEND_FUNCTION used for?', 'options' => ['Creating PHP functions', 'Defining C functions for PHP', 'Calling functions', 'Testing functions'], 'correct' => 1],
        ['question' => 'What is zend_string?', 'options' => ['String class', 'Internal string structure', 'String function', 'String type'], 'correct' => 1],
        ['question' => 'How does PHP implement HashTable?', 'options' => ['Binary tree', 'Hash array with collision handling', 'Linked list', 'Skip list'], 'correct' => 1],
        ['question' => 'What is zend_executor_globals?', 'options' => ['Global variables', 'Executor state structure', 'Global functions', 'Configuration'], 'correct' => 1],
        ['question' => 'What does zend_vm_execute() do?', 'options' => ['Executes shell commands', 'Dispatches opcodes', 'Runs tests', 'Compiles code'], 'correct' => 1],
        ['question' => 'What is the first compilation phase?', 'options' => ['Parsing', 'Lexing/tokenization', 'Optimization', 'Execution'], 'correct' => 1],
        ['question' => 'What is AST in PHP compilation?', 'options' => ['A string type', 'Abstract Syntax Tree', 'Array structure', 'Async task'], 'correct' => 1],
        ['question' => 'Where does OPcache store compiled code?', 'options' => ['Disk', 'Shared memory (SHM)', 'Database', 'RAM only'], 'correct' => 1],
        ['question' => 'What does JIT IR stand for?', 'options' => ['Intermediate Representation', 'Internal Register', 'Instruction Rate', 'Index Reference'], 'correct' => 0],
        ['question' => 'What is opcache.preload?', 'options' => ['Cache warmup', 'Loading files at startup', 'Precompiling templates', 'Database preload'], 'correct' => 1],
        ['question' => 'What is FFI in PHP?', 'options' => ['Fast File I/O', 'Foreign Function Interface', 'Full Feature Index', 'Framework Factory Interface'], 'correct' => 1],
        ['question' => 'What overhead do named arguments have?', 'options' => ['None', 'Slight runtime overhead for resolution', 'Memory leak', 'Compilation error'], 'correct' => 1],
        ['question' => 'How is match different from switch performance-wise?', 'options' => ['Slower always', 'Returns value, strict comparison', 'No difference', 'Faster always'], 'correct' => 1],
        ['question' => 'How do typed properties affect memory?', 'options' => ['No effect', 'More efficient memory layout', 'Use more memory', 'Slower access'], 'correct' => 1],
        ['question' => 'What algorithm does PHP garbage collection use?', 'options' => ['Mark and sweep', 'Cycle detection with color marking', 'Reference counting only', 'Generational GC'], 'correct' => 1],
        ['question' => 'What are purple nodes in PHP GC?', 'options' => ['Deleted objects', 'Possible cycle roots', 'Active objects', 'Constants'], 'correct' => 1],
        ['question' => 'What is the parallel extension?', 'options' => ['Database extension', 'Multi-threading extension', 'Network extension', 'File extension'], 'correct' => 1],
        ['question' => 'What is RoadRunner?', 'options' => ['Testing tool', 'Application server for PHP', 'Database', 'Framework'], 'correct' => 1],
        ['question' => 'What are Swoole co-routines?', 'options' => ['Functions', 'Cooperative multitasking primitives', 'Classes', 'Arrays'], 'correct' => 1],
        ['question' => 'What is a stream wrapper?', 'options' => ['File function', 'Custom protocol handler', 'String function', 'Array wrapper'], 'correct' => 1],
        ['question' => 'How do you register a custom stream wrapper?', 'options' => ['register_wrapper()', 'stream_wrapper_register()', 'add_stream()', 'create_wrapper()'], 'correct' => 1],
        ['question' => 'What is event-driven architecture in PHP?', 'options' => ['MVC pattern', 'Async I/O with event loop', 'Event sourcing', 'Observer pattern'], 'correct' => 1],
        ['question' => 'What does stream context provide?', 'options' => ['File content', 'Configuration for streams', 'Database context', 'Session context'], 'correct' => 1],
        ['question' => 'What is socket programming in PHP?', 'options' => ['Database sockets', 'Low-level network communication', 'File sockets', 'Web sockets only'], 'correct' => 1],
        ['question' => 'What does php_ini_entry define?', 'options' => ['INI file', 'Extension configuration option', 'Function', 'Class'], 'correct' => 1],
    ]],
];
require_once __DIR__ . '/quiz-engine.php';
