<?php
$page_title = 'Python Quiz – 100 Levels – CodeFoundry';
$active_page = 'training';
$quiz_title  = 'Python';
$quiz_slug   = 'python';
$quiz_tiers  = [
    ['label' => 'Introduction', 'questions' => [
        ['question' => 'Which function is used to display output in Python?', 'options' => ['echo()', 'print()', 'output()', 'display()'], 'correct' => 1],
        ['question' => 'Which of these is an integer type in Python?', 'options' => ['int', 'integer', 'num', 'number'], 'correct' => 0],
        ['question' => 'Which function returns the type of a variable?', 'options' => ['typeof()', 'type()', 'gettype()', 'vartype()'], 'correct' => 1],
        ['question' => 'Which symbol is used for addition in Python?', 'options' => ['+', 'add', 'plus', '&'], 'correct' => 0],
        ['question' => 'How do you create a string in Python?', 'options' => ['Using quotes (single or double)', 'Using brackets', 'Using parentheses', 'Using braces'], 'correct' => 0],
        ['question' => 'What is an f-string used for?', 'options' => ['Defining functions', 'String formatting with embedded expressions', 'File operations', 'Floating point numbers'], 'correct' => 1],
        ['question' => 'Which function reads user input?', 'options' => ['read()', 'input()', 'get()', 'scan()'], 'correct' => 1],
        ['question' => 'What keyword starts a conditional statement?', 'options' => ['when', 'if', 'condition', 'check'], 'correct' => 1],
        ['question' => 'What keyword is used for "else if" in Python?', 'options' => ['elseif', 'else if', 'elif', 'ei'], 'correct' => 2],
        ['question' => 'Which function generates a sequence of numbers?', 'options' => ['sequence()', 'range()', 'numbers()', 'seq()'], 'correct' => 1],
        ['question' => 'What keyword starts a while loop?', 'options' => ['loop', 'while', 'repeat', 'do'], 'correct' => 1],
        ['question' => 'Which function returns the length of a list?', 'options' => ['length()', 'len()', 'size()', 'count()'], 'correct' => 1],
        ['question' => 'How do you access the first element of a list?', 'options' => ['list[0]', 'list[1]', 'list.first()', 'list.get(0)'], 'correct' => 0],
        ['question' => 'Which method adds an item to the end of a list?', 'options' => ['add()', 'append()', 'insert()', 'push()'], 'correct' => 1],
        ['question' => 'Which method removes and returns the last item from a list?', 'options' => ['remove()', 'pop()', 'delete()', 'pull()'], 'correct' => 1],
        ['question' => 'What data type uses curly braces with key-value pairs?', 'options' => ['list', 'tuple', 'dict', 'set'], 'correct' => 2],
        ['question' => 'What symbol starts a comment in Python?', 'options' => ['//', '#', '/*', '--'], 'correct' => 1],
        ['question' => 'How do you create a multiline string?', 'options' => ['Using triple quotes', 'Using backslashes', 'Using brackets', 'Not possible'], 'correct' => 0],
        ['question' => 'Which operator checks for equality?', 'options' => ['=', '==', '===', 'equals'], 'correct' => 1],
        ['question' => 'Which logical operator returns True if both conditions are True?', 'options' => ['&&', 'and', 'AND', '&'], 'correct' => 1],
        ['question' => 'Which logical operator returns True if at least one condition is True?', 'options' => ['||', 'or', 'OR', '|'], 'correct' => 1],
        ['question' => 'Which logical operator reverses a boolean value?', 'options' => ['!', 'not', 'NOT', 'reverse'], 'correct' => 1],
        ['question' => 'What does None represent in Python?', 'options' => ['Zero', 'Empty string', 'Null/absence of value', 'False'], 'correct' => 2],
        ['question' => 'Which function converts a string to an integer?', 'options' => ['int()', 'toInt()', 'parseInt()', 'convert()'], 'correct' => 0],
        ['question' => 'How do you import the math module?', 'options' => ['include math', 'import math', 'require math', 'using math'], 'correct' => 1],
        ['question' => 'Which module provides random number functions?', 'options' => ['rand', 'random', 'rng', 'numbers'], 'correct' => 1],
        ['question' => 'What is the correct syntax for print in Python 3?', 'options' => ['print x', 'print(x)', 'echo x', 'console.log(x)'], 'correct' => 1],
        ['question' => 'Which data type is immutable and ordered?', 'options' => ['list', 'tuple', 'set', 'dict'], 'correct' => 1],
        ['question' => 'Which data type stores unique values?', 'options' => ['list', 'tuple', 'set', 'array'], 'correct' => 2],
        ['question' => 'What type is the value True in Python?', 'options' => ['int', 'str', 'bool', 'boolean'], 'correct' => 2],
    ]],
    ['label' => 'Beginner', 'questions' => [
        ['question' => 'Which keyword defines a function?', 'options' => ['function', 'def', 'func', 'define'], 'correct' => 1],
        ['question' => 'Which keyword returns a value from a function?', 'options' => ['return', 'output', 'yield', 'give'], 'correct' => 0],
        ['question' => 'What are default parameters?', 'options' => ['Required parameters', 'Parameters with predefined values', 'First parameters', 'Named parameters'], 'correct' => 1],
        ['question' => 'What does *args allow in a function?', 'options' => ['Keyword arguments', 'Variable number of positional arguments', 'Default arguments', 'No arguments'], 'correct' => 1],
        ['question' => 'What does **kwargs allow in a function?', 'options' => ['Positional arguments', 'Variable number of keyword arguments', 'Required arguments', 'Default arguments'], 'correct' => 1],
        ['question' => 'What is a list comprehension?', 'options' => ['A list method', 'Concise syntax to create lists', 'List documentation', 'List comparison'], 'correct' => 1],
        ['question' => 'Can you create dict comprehensions in Python?', 'options' => ['No', 'Yes', 'Only in Python 3', 'Only with special syntax'], 'correct' => 1],
        ['question' => 'Can you create set comprehensions in Python?', 'options' => ['No', 'Yes', 'Only in Python 3', 'Only with imports'], 'correct' => 1],
        ['question' => 'What is a lambda function?', 'options' => ['A regular function', 'An anonymous inline function', 'A Greek function', 'A mathematical function'], 'correct' => 1],
        ['question' => 'What does map() do?', 'options' => ['Creates dictionaries', 'Applies a function to all items in an iterable', 'Finds locations', 'Maps keys to values'], 'correct' => 1],
        ['question' => 'What does filter() do?', 'options' => ['Cleans data', 'Filters items based on a condition', 'Removes duplicates', 'Sorts items'], 'correct' => 1],
        ['question' => 'What does zip() do?', 'options' => ['Compresses files', 'Combines multiple iterables element-wise', 'Archives data', 'Encrypts data'], 'correct' => 1],
        ['question' => 'What does enumerate() return?', 'options' => ['Count of items', 'Index-value pairs', 'Sorted items', 'Unique items'], 'correct' => 1],
        ['question' => 'What does sorted() return?', 'options' => ['Original list sorted in-place', 'A new sorted list', 'A sort object', 'True or False'], 'correct' => 1],
        ['question' => 'Which method splits a string into a list?', 'options' => ['split()', 'divide()', 'separate()', 'break()'], 'correct' => 0],
        ['question' => 'Which method joins list elements into a string?', 'options' => ['join()', 'concat()', 'merge()', 'combine()'], 'correct' => 0],
        ['question' => 'Which method removes whitespace from both ends?', 'options' => ['trim()', 'strip()', 'clean()', 'remove()'], 'correct' => 1],
        ['question' => 'Which method replaces substrings?', 'options' => ['replace()', 'substitute()', 'change()', 'swap()'], 'correct' => 0],
        ['question' => 'What is slicing syntax?', 'options' => ['list.slice()', '[start:stop:step]', 'slice(list)', 'list[start, stop]'], 'correct' => 1],
        ['question' => 'What is tuple unpacking?', 'options' => ['Removing tuples', 'Assigning tuple elements to variables', 'Converting to list', 'Tuple iteration'], 'correct' => 1],
        ['question' => 'What is multiple assignment?', 'options' => ['Assigning one value', 'Assigning multiple variables in one statement', 'Multiple functions', 'Assignment operators'], 'correct' => 1],
        ['question' => 'What is the difference between global and local scope?', 'options' => ['No difference', 'Global is module-wide, local is function-wide', 'Global is faster', 'Local is permanent'], 'correct' => 1],
        ['question' => 'What does try-except do?', 'options' => ['Tests code', 'Handles exceptions/errors', 'Tries functions', 'Optimizes code'], 'correct' => 1],
        ['question' => 'What does finally do in exception handling?', 'options' => ['Ends the program', 'Executes code regardless of exception', 'Catches errors', 'Returns final value'], 'correct' => 1],
        ['question' => 'How do you open a file for reading?', 'options' => ['open(file, "r")', 'read(file)', 'file.open("r")', 'openfile(file)'], 'correct' => 0],
        ['question' => 'What does the "with" statement do with files?', 'options' => ['Opens multiple files', 'Ensures proper resource cleanup', 'Writes files', 'Reads files'], 'correct' => 1],
        ['question' => 'Which module provides operating system functions?', 'options' => ['sys', 'os', 'system', 'operating'], 'correct' => 1],
        ['question' => 'Which module provides system-specific parameters?', 'options' => ['system', 'sys', 'os', 'config'], 'correct' => 1],
        ['question' => 'Which module handles dates and times?', 'options' => ['time', 'datetime', 'date', 'calendar'], 'correct' => 1],
        ['question' => 'What is Counter in collections module?', 'options' => ['A timer', 'A dict subclass for counting hashable objects', 'A number generator', 'A loop counter'], 'correct' => 1],
        ['question' => 'What is defaultdict?', 'options' => ['A default dictionary', 'A dict that provides default values for missing keys', 'A preset dict', 'A standard dict'], 'correct' => 1],
        ['question' => 'What is the difference between shallow and deep copy?', 'options' => ['No difference', 'Shallow copies references, deep copies nested objects', 'Shallow is faster only', 'Deep is larger only'], 'correct' => 1],
    ]],
    ['label' => 'Intermediate', 'questions' => [
        ['question' => 'What keyword defines a class?', 'options' => ['class', 'object', 'struct', 'type'], 'correct' => 0],
        ['question' => 'What is "self" in a class method?', 'options' => ['A keyword', 'Reference to the instance', 'The class itself', 'A variable'], 'correct' => 1],
        ['question' => 'What is __init__?', 'options' => ['Initialization method/constructor', 'Destructor', 'Class method', 'Static method'], 'correct' => 0],
        ['question' => 'What does __str__ define?', 'options' => ['String conversion', 'String representation for end users', 'String comparison', 'String length'], 'correct' => 1],
        ['question' => 'What does __repr__ define?', 'options' => ['Representation for debugging/developers', 'String conversion', 'Reproduction', 'Replacement'], 'correct' => 0],
        ['question' => 'What keyword is used for inheritance?', 'options' => ['inherits', 'extends', 'Class definition with parent in parentheses', 'implements'], 'correct' => 2],
        ['question' => 'What does super() do?', 'options' => ['Creates superclass', 'Calls parent class methods', 'Makes class superior', 'Elevates permissions'], 'correct' => 1],
        ['question' => 'What is method resolution order (MRO)?', 'options' => ['Method ranking', 'Order in which base classes are searched', 'Method sorting', 'Resolution algorithm'], 'correct' => 1],
        ['question' => 'What are dunder methods?', 'options' => ['Deleted methods', 'Special methods with double underscores', 'Duplicate methods', 'Dynamic methods'], 'correct' => 1],
        ['question' => 'What does __len__ do?', 'options' => ['Returns length when len() is called', 'Checks length', 'Sets length', 'Measures object'], 'correct' => 0],
        ['question' => 'What does __getitem__ allow?', 'options' => ['Getting items from store', 'Indexing with [] operator', 'Getting methods', 'Retrieving attributes'], 'correct' => 1],
        ['question' => 'What does __iter__ do?', 'options' => ['Iterates automatically', 'Makes object iterable, returns iterator', 'Counts iterations', 'Repeats object'], 'correct' => 1],
        ['question' => 'What is a decorator?', 'options' => ['A design pattern', 'A function that modifies another function', 'A decoration', 'A class method'], 'correct' => 1],
        ['question' => 'What does @property do?', 'options' => ['Defines a property', 'Makes method accessible like an attribute', 'Sets ownership', 'Creates constant'], 'correct' => 1],
        ['question' => 'What does @staticmethod do?', 'options' => ['Makes method static like in Java', 'Defines method that doesn\'t access instance/class', 'Freezes method', 'Makes method unchangeable'], 'correct' => 1],
        ['question' => 'What does @classmethod do?', 'options' => ['Creates class', 'Defines method that receives class as first argument', 'Makes method public', 'Documents class'], 'correct' => 1],
        ['question' => 'What is a generator?', 'options' => ['A function that generates code', 'A function that yields values lazily', 'A creation pattern', 'A random generator'], 'correct' => 1],
        ['question' => 'What does yield do?', 'options' => ['Returns permanently', 'Returns value and pauses function state', 'Gives up', 'Produces output'], 'correct' => 1],
        ['question' => 'What is yield from?', 'options' => ['Source of yield', 'Delegates to another generator', 'Imports yield', 'Yield origin'], 'correct' => 1],
        ['question' => 'What is a context manager?', 'options' => ['Memory manager', 'Object that defines __enter__ and __exit__ for resource management', 'Context provider', 'Configuration manager'], 'correct' => 1],
        ['question' => 'What does __enter__ do?', 'options' => ['Enters function', 'Executes when entering "with" block', 'Provides input', 'Opens resources'], 'correct' => 1],
        ['question' => 'What does __exit__ do?', 'options' => ['Exits program', 'Executes when leaving "with" block', 'Closes resources', 'Ends function'], 'correct' => 1],
        ['question' => 'Are list comprehensions generally faster than loops?', 'options' => ['No', 'Yes, often faster due to optimization', 'Same speed', 'Depends on list size only'], 'correct' => 1],
        ['question' => 'What is the re module used for?', 'options' => ['Returning values', 'Regular expressions', 'Recursion', 'Repetition'], 'correct' => 1],
        ['question' => 'What does re.search() do?', 'options' => ['Searches files', 'Searches for pattern anywhere in string', 'Web search', 'Binary search'], 'correct' => 1],
        ['question' => 'What does re.match() do?', 'options' => ['Matches anything', 'Matches pattern at start of string', 'Compares strings', 'Finds duplicates'], 'correct' => 1],
        ['question' => 'What does functools.lru_cache do?', 'options' => ['Clears cache', 'Caches function results (memoization)', 'Least recently used algorithm', 'Both caches results and uses LRU algorithm'], 'correct' => 3],
        ['question' => 'What is itertools.chain?', 'options' => ['Links functions', 'Chains iterables together', 'Creates chains', 'Dependency chain'], 'correct' => 1],
        ['question' => 'What does typing module provide?', 'options' => ['Type conversion', 'Type hints/annotations', 'Text typing', 'Type checking at runtime'], 'correct' => 1],
        ['question' => 'What is a dataclass?', 'options' => ['A data container', 'A decorator that auto-generates special methods for data storage', 'A database class', 'A class for data only'], 'correct' => 1],
        ['question' => 'What is an abstract base class?', 'options' => ['A theoretical class', 'A class that defines interface without implementation', 'A base class', 'An advanced class'], 'correct' => 1],
        ['question' => 'What is the difference between threading and multiprocessing?', 'options' => ['No difference', 'Threading uses threads, multiprocessing uses processes', 'Threading is faster', 'Multiprocessing is older'], 'correct' => 1],
        ['question' => 'What is asyncio used for?', 'options' => ['Synchronous I/O', 'Asynchronous I/O and concurrency', 'File I/O', 'Network I/O only'], 'correct' => 1],
        ['question' => 'What does async keyword do?', 'options' => ['Makes function asynchronous', 'Defines a coroutine', 'Runs in background', 'Both makes function asynchronous and defines a coroutine'], 'correct' => 3],
        ['question' => 'What does await keyword do?', 'options' => ['Waits forever', 'Pauses coroutine until awaited task completes', 'Delays execution', 'Waits for input'], 'correct' => 1],
    ]],
    ['label' => 'Advanced', 'questions' => [
        ['question' => 'What is a metaclass?', 'options' => ['A parent class', 'A class of a class', 'A metadata class', 'An abstract class'], 'correct' => 1],
        ['question' => 'What is __new__?', 'options' => ['Creates new objects', 'Called before __init__ to create instance', 'Updates objects', 'Newest method'], 'correct' => 1],
        ['question' => 'What is __init_subclass__?', 'options' => ['Initializes subclass', 'Called when class is subclassed', 'Creates subclass', 'Inherits from subclass'], 'correct' => 1],
        ['question' => 'What is the descriptor protocol?', 'options' => ['Describes objects', 'Defines __get__, __set__, __delete__ for attribute access', 'Documentation protocol', 'Description methods'], 'correct' => 1],
        ['question' => 'What does __get__ do in a descriptor?', 'options' => ['Gets values', 'Defines behavior when attribute is accessed', 'Retrieves descriptor', 'Fetches data'], 'correct' => 1],
        ['question' => 'What does __set__ do in a descriptor?', 'options' => ['Sets values', 'Defines behavior when attribute is assigned', 'Configures descriptor', 'Stores data'], 'correct' => 1],
        ['question' => 'What is __slots__?', 'options' => ['Reserved spaces', 'Restricts instance attributes for memory optimization', 'Storage slots', 'Variable containers'], 'correct' => 1],
        ['question' => 'What is the GIL?', 'options' => ['Global Interface Layer', 'Global Interpreter Lock', 'General Integration Library', 'Graphical Interaction Layer'], 'correct' => 1],
        ['question' => 'What does the GIL prevent?', 'options' => ['Errors', 'Multiple threads executing Python bytecode simultaneously', 'Memory leaks', 'Crashes'], 'correct' => 1],
        ['question' => 'What is threading.Lock?', 'options' => ['A locked thread', 'A mutual exclusion lock', 'Thread security', 'Thread barrier'], 'correct' => 1],
        ['question' => 'What is threading.RLock?', 'options' => ['Reverse lock', 'Reentrant lock (can be acquired multiple times by same thread)', 'Remote lock', 'Real lock'], 'correct' => 1],
        ['question' => 'What is a Semaphore?', 'options' => ['A signal', 'A counter controlling access to shared resource', 'A flag', 'A message'], 'correct' => 1],
        ['question' => 'What is multiprocessing.Pool?', 'options' => ['Process storage', 'A pool of worker processes', 'Resource pool', 'Thread pool'], 'correct' => 1],
        ['question' => 'What is asyncio.gather?', 'options' => ['Collects data', 'Runs multiple coroutines concurrently', 'Gathers results', 'Groups functions'], 'correct' => 1],
        ['question' => 'What is asyncio.create_task?', 'options' => ['Creates functions', 'Schedules coroutine as Task', 'Makes new task', 'Defines task'], 'correct' => 1],
        ['question' => 'What is an async generator?', 'options' => ['Fast generator', 'Generator that yields values asynchronously', 'Async function', 'Background generator'], 'correct' => 1],
        ['question' => 'What is an async context manager?', 'options' => ['Async manager', 'Context manager with __aenter__ and __aexit__', 'Background manager', 'Fast context manager'], 'correct' => 1],
        ['question' => 'How does Python manage memory?', 'options' => ['Manual allocation', 'Automatic with reference counting and garbage collection', 'Static allocation', 'Stack-based'], 'correct' => 1],
        ['question' => 'What is reference counting?', 'options' => ['Counting variables', 'Tracking number of references to an object', 'Reference checking', 'Count validation'], 'correct' => 1],
        ['question' => 'What is cycle detection in garbage collection?', 'options' => ['Finding loops', 'Detecting circular references for cleanup', 'Loop detection', 'Cycle counting'], 'correct' => 1],
        ['question' => 'What is weakref?', 'options' => ['Weak reference that doesn\'t prevent garbage collection', 'Broken reference', 'Soft reference', 'Temporary reference'], 'correct' => 0],
        ['question' => 'What is cProfile?', 'options' => ['C compiler', 'A profiler for performance analysis', 'Profile viewer', 'Configuration profile'], 'correct' => 1],
        ['question' => 'What is ctypes?', 'options' => ['C data types', 'Foreign function library for calling C functions', 'Type conversion', 'Custom types'], 'correct' => 1],
        ['question' => 'What is Cython?', 'options' => ['C version of Python', 'Superset of Python that compiles to C', 'Python in C', 'C library'], 'correct' => 1],
        ['question' => 'What is PyPy?', 'options' => ['Python package', 'Alternative Python implementation with JIT compiler', 'Python 2', 'Python preprocessor'], 'correct' => 1],
        ['question' => 'What is importlib?', 'options' => ['Import library', 'Module for programmatic importing', 'Library importer', 'Import tool'], 'correct' => 1],
        ['question' => 'What are .pyc files?', 'options' => ['Python config', 'Compiled bytecode files', 'Python cache', 'Python compiled'], 'correct' => 1],
        ['question' => 'What does dis module do?', 'options' => ['Disables features', 'Disassembles Python bytecode', 'Displays code', 'Distributes code'], 'correct' => 1],
        ['question' => 'What is a code object?', 'options' => ['Coded object', 'Internal representation of compiled Python code', 'Object code', 'Source object'], 'correct' => 1],
        ['question' => 'What is a frame object?', 'options' => ['Picture frame', 'Execution frame containing local variables and state', 'Data frame', 'Object container'], 'correct' => 1],
        ['question' => 'What is pdb?', 'options' => ['Python database', 'Python debugger', 'Performance debugger', 'Process debugger'], 'correct' => 1],
        ['question' => 'What does sys.settrace do?', 'options' => ['Sets tracing mode', 'Sets a trace function for debugging/coverage', 'Enables tracing', 'Configures traces'], 'correct' => 1],
        ['question' => 'What is sys.getframe?', 'options' => ['Gets window frame', 'Gets current stack frame', 'Retrieves frame object', 'Gets execution frame'], 'correct' => 1],
        ['question' => 'Why are exec and eval dangerous?', 'options' => ['They are slow', 'They can execute arbitrary code (security risk)', 'They crash programs', 'They are deprecated'], 'correct' => 1],
        ['question' => 'What is the AST module?', 'options' => ['Abstract Syntax Tree module', 'Automatic Syntax Tool', 'Advanced String Tool', 'Array Structure Tool'], 'correct' => 0],
    ]],
    ['label' => 'Expert', 'questions' => [
        ['question' => 'What is PyObject?', 'options' => ['Python object', 'C structure representing Python objects in CPython', 'Object type', 'Base object'], 'correct' => 1],
        ['question' => 'How does CPython implement objects internally?', 'options' => ['As pure Python', 'As C structures with reference count and type pointer', 'As bytecode', 'As assembly'], 'correct' => 1],
        ['question' => 'What is the garbage collector\'s generation concept?', 'options' => ['Age of objects', 'Objects grouped by age for efficient collection', 'Object versions', 'Collection rounds'], 'correct' => 1],
        ['question' => 'How many generations does Python\'s GC use?', 'options' => ['1', '2', '3', '5'], 'correct' => 2],
        ['question' => 'What is pymalloc?', 'options' => ['Python memory library', 'CPython\'s memory allocator for small objects', 'Memory allocation function', 'Malloc wrapper'], 'correct' => 1],
        ['question' => 'What are arenas in pymalloc?', 'options' => ['Memory regions', 'Large blocks of memory (256KB) from system', 'Virtual memory', 'Heap areas'], 'correct' => 1],
        ['question' => 'What are pools in pymalloc?', 'options' => ['Memory pools', '4KB chunks within arenas', 'Object pools', 'Thread pools'], 'correct' => 1],
        ['question' => 'What is the CPython bytecode?', 'options' => ['Binary code', 'Platform-independent instructions executed by Python VM', 'Byte-sized code', 'Compiled code'], 'correct' => 1],
        ['question' => 'What is LOAD_FAST?', 'options' => ['Loads quickly', 'Bytecode instruction to load local variable', 'Fast loading', 'Speed optimization'], 'correct' => 1],
        ['question' => 'Why is LOAD_FAST faster than LOAD_NAME?', 'options' => ['Better algorithm', 'Accesses local array directly vs dictionary lookup', 'Optimized code', 'Shorter instruction'], 'correct' => 1],
        ['question' => 'What is LOAD_GLOBAL?', 'options' => ['Loads all globals', 'Bytecode instruction to load global variable', 'Global loading', 'Worldwide load'], 'correct' => 1],
        ['question' => 'What is string interning?', 'options' => ['String internship', 'Reusing string objects for identical values', 'String storage', 'String caching'], 'correct' => 1],
        ['question' => 'Which integers are cached in CPython?', 'options' => ['All integers', 'Integers from -5 to 256', 'Positive integers', 'Small integers'], 'correct' => 1],
        ['question' => 'What are co_* attributes?', 'options' => ['Collaborative attributes', 'Code object attributes', 'Constant attributes', 'Core attributes'], 'correct' => 1],
        ['question' => 'What is co_code?', 'options' => ['Code copy', 'Raw bytecode of a code object', 'Code constant', 'Compiled code'], 'correct' => 1],
        ['question' => 'What does sys.settrace enable?', 'options' => ['System tracing', 'Line-by-line execution monitoring', 'Stack tracing', 'Error tracing'], 'correct' => 1],
        ['question' => 'What is ast.NodeTransformer?', 'options' => ['Node converter', 'Class for modifying AST nodes', 'AST transformer', 'Syntax transformer'], 'correct' => 1],
        ['question' => 'What is the purpose of compile()?', 'options' => ['Compiles Python', 'Compiles source to code object', 'Creates bytecode', 'Builds executables'], 'correct' => 1],
        ['question' => 'What is a meta path finder?', 'options' => ['Path searcher', 'Object that finds modules during import', 'Metadata finder', 'Import hook'], 'correct' => 1],
        ['question' => 'What is a loader in import system?', 'options' => ['Data loader', 'Object that loads and executes modules', 'Module importer', 'File loader'], 'correct' => 1],
        ['question' => 'What are namespace packages?', 'options' => ['Named packages', 'Packages without __init__.py spanning multiple directories', 'Virtual packages', 'Package namespaces'], 'correct' => 1],
        ['question' => 'What is zipimport?', 'options' => ['Zip file import', 'Importing modules from ZIP archives', 'Compressed import', 'Archive loader'], 'correct' => 1],
        ['question' => 'What are frozen modules?', 'options' => ['Immutable modules', 'Modules compiled into Python interpreter', 'Locked modules', 'Static modules'], 'correct' => 1],
        ['question' => 'What is PyFrameObject?', 'options' => ['Frame object in Python', 'C structure representing execution frame', 'Python frame', 'Object frame'], 'correct' => 1],
        ['question' => 'What is generator frame reuse?', 'options' => ['Reusing generators', 'Optimization where generator frames are reused', 'Frame recycling', 'Generator optimization'], 'correct' => 1],
        ['question' => 'What is PyArg_ParseTuple?', 'options' => ['Python argument parser', 'C API function to parse function arguments', 'Tuple parser', 'Argument extractor'], 'correct' => 1],
        ['question' => 'What is Py_RETURN_NONE?', 'options' => ['Returns nothing', 'C macro to return None safely', 'None return', 'Empty return'], 'correct' => 1],
        ['question' => 'What is Py_INCREF?', 'options' => ['Increases reference', 'Increments reference count', 'Reference increment', 'Count increase'], 'correct' => 1],
        ['question' => 'What is Py_DECREF?', 'options' => ['Decreases reference', 'Decrements reference count', 'Reference decrement', 'Count decrease'], 'correct' => 1],
        ['question' => 'Why is manual reference counting needed in C extensions?', 'options' => ['For speed', 'Python\'s memory management relies on reference counts', 'For safety', 'For compatibility'], 'correct' => 1],
        ['question' => 'What is the buffer protocol?', 'options' => ['Buffer management', 'Protocol for sharing memory buffers between objects', 'Data buffering', 'Memory protocol'], 'correct' => 1],
        ['question' => 'What is PEP 703?', 'options' => ['Python Enhancement Proposal 703', 'Proposal for making GIL optional/removing it', 'Python 703', 'Performance enhancement'], 'correct' => 1],
        ['question' => 'What would removing the GIL enable?', 'options' => ['Faster code', 'True multi-core parallelism in Python threads', 'Better performance', 'Less complexity'], 'correct' => 1],
        ['question' => 'What challenge does GIL removal face?', 'options' => ['Performance loss', 'Maintaining thread safety and backward compatibility', 'Complexity', 'All existing code breaks'], 'correct' => 1],
        ['question' => 'What is the purpose of the gc module?', 'options' => ['General computing', 'Controlling garbage collection', 'Global cache', 'Code generation'], 'correct' => 1],
        ['question' => 'Can you disable garbage collection in Python?', 'options' => ['No', 'Yes, with gc.disable()', 'Only partially', 'Only for testing'], 'correct' => 1],
        ['question' => 'Why might you temporarily disable GC?', 'options' => ['Save memory', 'Performance during critical sections', 'Prevent errors', 'Debug code'], 'correct' => 1],
        ['question' => 'What is the trade-off of using __slots__?', 'options' => ['No trade-off', 'Saves memory but prevents dynamic attribute addition', 'Slower access', 'Complex syntax'], 'correct' => 1],
        ['question' => 'How much memory does __slots__ typically save?', 'options' => ['None', 'Can reduce memory per instance significantly', 'Minimal', 'Doubles memory'], 'correct' => 1],
        ['question' => 'What is eval\'s typical use case?', 'options' => ['Evaluating expressions', 'Evaluating single expressions from strings', 'Running code', 'Testing code'], 'correct' => 1],
    ]],
];
require_once __DIR__ . '/quiz-engine.php';
