<?php
$page_title = 'R Quiz – 100 Levels – CodeFoundry';
$active_page = 'training';
$quiz_title  = 'R';
$quiz_slug   = 'r-lang';
$quiz_tiers  = [
    ['label' => 'Introduction', 'questions' => [
        ['question' => 'What is R primarily used for?', 'options' => ['Web development', 'Statistical computing and data analysis', 'Operating system development', 'Mobile app development'], 'correct' => 1],
        ['question' => 'Which operator is the most idiomatic assignment operator in R?', 'options' => ['=', '&lt;-', ':=', '-&gt;'], 'correct' => 1],
        ['question' => 'What does the c() function do in R?', 'options' => ['Creates a matrix', 'Combines values into a vector', 'Counts elements in a list', 'Converts data types'], 'correct' => 1],
        ['question' => 'What is CRAN in the R ecosystem?', 'options' => ['A type of R data structure', 'The Comprehensive R Archive Network, the main repository for R packages', 'An R IDE', 'A statistical testing framework'], 'correct' => 1],
        ['question' => 'Which IDE is most commonly used for R programming?', 'options' => ['Eclipse', 'RStudio', 'NetBeans', 'Atom'], 'correct' => 1],
        ['question' => 'How do you start a comment in R?', 'options' => ['//', '#', '/*', '--'], 'correct' => 1],
        ['question' => 'What does the class() function return?', 'options' => ['The number of elements in an object', 'The data type or class of an R object', 'The length of a string', 'The memory address of an object'], 'correct' => 1],
        ['question' => 'What is the result of class(TRUE) in R?', 'options' => ['integer', 'character', 'logical', 'boolean'], 'correct' => 2],
        ['question' => 'Which function prints output to the console in R?', 'options' => ['echo()', 'print()', 'console.log()', 'write()'], 'correct' => 1],
        ['question' => 'What does sqrt(16) return in R?', 'options' => ['2', '8', '4', '256'], 'correct' => 2],
        ['question' => 'Which of these creates a numeric vector in R?', 'options' => ['vector(1,2,3)', 'c(1, 2, 3)', 'list(1, 2, 3)', 'array(1, 2, 3)'], 'correct' => 1],
        ['question' => 'What operator is used for exponentiation in R?', 'options' => ['**', '^', 'exp', '^^'], 'correct' => 1],
        ['question' => 'What does length() return for a vector in R?', 'options' => ['The sum of elements', 'The number of elements in the vector', 'The data type', 'The maximum value'], 'correct' => 1],
        ['question' => 'How do you install a package in R?', 'options' => ['import("packagename")', 'install.packages("packagename")', 'library.install("packagename")', 'get.package("packagename")'], 'correct' => 1],
        ['question' => 'How do you load an installed package in R?', 'options' => ['import(packagename)', 'library(packagename)', 'require.package(packagename)', 'load(packagename)'], 'correct' => 1],
        ['question' => 'What is the result of 5 %% 3 in R?', 'options' => ['1', '2', '1.67', '0'], 'correct' => 1],
        ['question' => 'What does mean(c(2, 4, 6)) return?', 'options' => ['6', '12', '4', '2'], 'correct' => 2],
        ['question' => 'What data type is "Hello" in R?', 'options' => ['factor', 'logical', 'character', 'string'], 'correct' => 2],
        ['question' => 'What does sum(c(1, 2, 3, 4)) return?', 'options' => ['4', '24', '10', '1234'], 'correct' => 2],
        ['question' => 'Which function converts a number to a character in R?', 'options' => ['to.char()', 'as.character()', 'str()', 'convert()'], 'correct' => 1],
        ['question' => 'What is R\'s special value for "Not a Number"?', 'options' => ['NULL', 'NA', 'NaN', 'Inf'], 'correct' => 2],
        ['question' => 'What does abs(-5) return in R?', 'options' => ['-5', '25', '5', '0'], 'correct' => 2],
        ['question' => 'Which of these is a valid variable name in R?', 'options' => ['2var', 'my.var', 'my-var', 'my var'], 'correct' => 1],
        ['question' => 'What does cat() do differently from print() in R?', 'options' => ['cat() adds quotes; print() does not', 'cat() outputs without automatic newline and formatting; print() formats output with type info', 'cat() only works with numbers', 'They are identical'], 'correct' => 1],
        ['question' => 'What does R stand for in the context of the R programming language?', 'options' => ['Rapid', 'R is named after its creators Ross Ihaka and Robert Gentleman', 'Recursive', 'Regression'], 'correct' => 1],
    ]],
    ['label' => 'Beginner', 'questions' => [
        ['question' => 'How do you access the second element of a vector v in R?', 'options' => ['v[0]', 'v[2]', 'v{2}', 'v.get(2)'], 'correct' => 1],
        ['question' => 'R vectors are 1-indexed. What does v[1] return for v = c(10,20,30)?', 'options' => ['20', '30', '10', 'NULL'], 'correct' => 2],
        ['question' => 'What function creates a data frame in R?', 'options' => ['matrix()', 'list()', 'data.frame()', 'frame()'], 'correct' => 2],
        ['question' => 'What does head(df) show by default?', 'options' => ['The last 6 rows', 'The first 6 rows of the data frame', 'The column names only', 'Summary statistics'], 'correct' => 1],
        ['question' => 'How do you read a CSV file into R?', 'options' => ['open.csv()', 'read.csv()', 'import.csv()', 'load.csv()'], 'correct' => 1],
        ['question' => 'What does str() do in R?', 'options' => ['Returns string length', 'Displays the structure of an R object', 'Converts to string', 'Removes whitespace'], 'correct' => 1],
        ['question' => 'How do you create a matrix with 2 rows and 3 columns in R?', 'options' => ['matrix(1:6, rows=2, cols=3)', 'matrix(1:6, nrow=2, ncol=3)', 'create.matrix(2, 3)', 'array(1:6, dim=c(3,2))'], 'correct' => 1],
        ['question' => 'What does rbind() do in R?', 'options' => ['Binds columns together', 'Binds rows together (adds rows)', 'Creates a binding variable', 'Applies a function to rows'], 'correct' => 1],
        ['question' => 'How do you create a list in R?', 'options' => ['c()', 'list()', 'vector()', 'array()'], 'correct' => 1],
        ['question' => 'How do you access a named element "age" from a list my_list in R?', 'options' => ['my_list["age"]', 'my_list$age', 'my_list[age]', 'get(my_list, "age")'], 'correct' => 1],
        ['question' => 'What does the for loop syntax look like in R?', 'options' => ['for i in 1:5 { }', 'for (i in 1:5) { }', 'foreach (i in 1:5) { }', 'loop(i, 1, 5) { }'], 'correct' => 1],
        ['question' => 'What does is.na(NA) return in R?', 'options' => ['FALSE', 'NULL', 'TRUE', 'NA'], 'correct' => 2],
        ['question' => 'What does na.omit() do?', 'options' => ['Replaces NA with zero', 'Removes rows with NA values from a data frame or vector', 'Counts the number of NAs', 'Converts NAs to FALSE'], 'correct' => 1],
        ['question' => 'What is a factor in R?', 'options' => ['A numeric multiplier', 'A categorical variable with a fixed set of levels', 'A type of matrix', 'A statistical model component'], 'correct' => 1],
        ['question' => 'Which function creates a sequence from 1 to 10 in steps of 2?', 'options' => ['range(1, 10, 2)', 'seq(1, 10, by=2)', 'sequence(1:10, 2)', 'step(1, 10, 2)'], 'correct' => 1],
        ['question' => 'What does rep(1:3, times=2) return?', 'options' => ['1 2 3', '1 1 1 2 2 2', '1 2 3 1 2 3', '1 2 3 2 1'], 'correct' => 2],
        ['question' => 'What does the plot() function do in R?', 'options' => ['Creates only bar charts', 'Creates a generic scatter plot or line chart from data', 'Plots only time series data', 'Creates only histograms'], 'correct' => 1],
        ['question' => 'What does hist() create?', 'options' => ['A historical data table', 'A histogram showing frequency distribution', 'A heat map', 'A horizontal bar chart'], 'correct' => 1],
        ['question' => 'How do you define a function in R?', 'options' => ['def myFunc(x) { }', 'myFunc &lt;- function(x) { }', 'function myFunc(x) { }', 'create.function(myFunc, x)'], 'correct' => 1],
        ['question' => 'What does nrow() return for a data frame?', 'options' => ['Number of columns', 'Number of rows', 'Total number of cells', 'Names of rows'], 'correct' => 1],
        ['question' => 'What does which(c(FALSE, TRUE, FALSE, TRUE)) return?', 'options' => ['c(FALSE, TRUE)', 'c(1, 3)', 'c(2, 4)', 'c(TRUE, TRUE)'], 'correct' => 2],
        ['question' => 'How do you access the "name" column of a data frame df?', 'options' => ['df["name"]', 'df$name', 'df.name', 'df-&gt;name'], 'correct' => 1],
        ['question' => 'What does the while loop do in R?', 'options' => ['Loops a fixed number of times', 'Repeats a block of code while a condition is TRUE', 'Loops through each element of a vector', 'Executes code once if condition is met'], 'correct' => 1],
        ['question' => 'What does summary() do for a data frame?', 'options' => ['Returns only the dimensions', 'Provides descriptive statistics for each column', 'Plots the data', 'Returns the first few rows'], 'correct' => 1],
        ['question' => 'What does cbind() do?', 'options' => ['Combines rows', 'Combines objects by columns', 'Creates a new binding class', 'Counts bindings in a data frame'], 'correct' => 1],
    ]],
    ['label' => 'Intermediate', 'questions' => [
        ['question' => 'Which ggplot2 function initializes a plot?', 'options' => ['geom_point()', 'ggplot()', 'aes()', 'theme()'], 'correct' => 1],
        ['question' => 'What does aes() do in ggplot2?', 'options' => ['Adds a geometric layer', 'Defines aesthetic mappings (x, y, color, size, etc.) from data columns', 'Applies a theme', 'Scales axes'], 'correct' => 1],
        ['question' => 'Which dplyr function keeps only rows matching a condition?', 'options' => ['select()', 'filter()', 'arrange()', 'mutate()'], 'correct' => 1],
        ['question' => 'What does dplyr\'s mutate() do?', 'options' => ['Removes columns', 'Adds new columns or modifies existing ones', 'Filters rows', 'Sorts the data frame'], 'correct' => 1],
        ['question' => 'What does group_by() followed by summarise() do in dplyr?', 'options' => ['Sorts groups alphabetically', 'Computes summary statistics for each group', 'Filters groups below a threshold', 'Removes group structure'], 'correct' => 1],
        ['question' => 'What is the pipe operator in magrittr/dplyr?', 'options' => ['|&gt;', '|', '%&gt;%', '-&gt;'], 'correct' => 2],
        ['question' => 'What does select() do in dplyr?', 'options' => ['Filters rows by condition', 'Chooses specific columns from a data frame', 'Selects rows by index', 'Groups data'], 'correct' => 1],
        ['question' => 'What does lapply() return?', 'options' => ['A vector', 'A list of results from applying a function to each element of a list/vector', 'A data frame', 'A matrix'], 'correct' => 1],
        ['question' => 'What does sapply() do differently from lapply()?', 'options' => ['It works only on matrices', 'It simplifies the result to a vector or matrix when possible, instead of always returning a list', 'It applies a function in parallel', 'It requires a named list input'], 'correct' => 1],
        ['question' => 'What does grepl() return in R?', 'options' => ['The matched substrings', 'A logical vector indicating which elements match a regex pattern', 'The positions of matches', 'A replaced string'], 'correct' => 1],
        ['question' => 'What does gsub() do?', 'options' => ['Finds all occurrences of a pattern', 'Replaces all occurrences of a pattern in a string with a replacement', 'Splits a string by a pattern', 'Checks if a pattern exists'], 'correct' => 1],
        ['question' => 'What does paste0("Hello", "World") return?', 'options' => ['"Hello World"', '"HelloWorld"', '"Hello,World"', 'c("Hello","World")'], 'correct' => 1],
        ['question' => 'What does pivot_longer() in tidyr do?', 'options' => ['Increases the number of columns', 'Converts wide-format data to long format by collapsing multiple columns into rows', 'Sorts data from shortest to longest', 'Pivots data around a central column'], 'correct' => 1],
        ['question' => 'What does pivot_wider() do?', 'options' => ['Converts long-format data to wide format by expanding rows into columns', 'Makes columns wider visually', 'Reduces the number of rows by grouping', 'Applies a pivot table calculation'], 'correct' => 0],
        ['question' => 'What does tapply() do?', 'options' => ['Applies a function to all elements of a vector', 'Applies a function to subsets of a vector grouped by a factor', 'Applies a function across table rows', 'Applies a function to columns of a matrix'], 'correct' => 1],
        ['question' => 'What does arrange() do in dplyr?', 'options' => ['Reorders columns', 'Sorts rows of a data frame by one or more columns', 'Groups rows together', 'Applies a function to each row'], 'correct' => 1],
        ['question' => 'What does geom_point() add to a ggplot?', 'options' => ['Bar chart bars', 'Scatter plot points', 'Line segments', 'Box plot boxes'], 'correct' => 1],
        ['question' => 'What does apply(matrix, 1, sum) do?', 'options' => ['Sums all elements', 'Applies sum to each row (margin=1) of the matrix', 'Applies sum to each column', 'Sums every other element'], 'correct' => 1],
        ['question' => 'What does substr("Hello World", 1, 5) return?', 'options' => ['"World"', '" World"', '"Hello"', '"Hello "'], 'correct' => 2],
        ['question' => 'What does the table() function do?', 'options' => ['Creates a data frame', 'Creates a frequency table of a categorical variable', 'Creates an HTML table', 'Formats data as a table'], 'correct' => 1],
        ['question' => 'What does separate() do in tidyr?', 'options' => ['Splits a data frame into two', 'Splits a single column into multiple columns based on a separator', 'Separates numeric from character columns', 'Separates training and test data'], 'correct' => 1],
        ['question' => 'What does nchar("Hello") return?', 'options' => ['4', '6', '5', '1'], 'correct' => 2],
        ['question' => 'In ggplot2, what does labs() do?', 'options' => ['Creates a lab report', 'Sets axis labels, title, subtitle, and caption', 'Filters data labels', 'Adds data labels to points'], 'correct' => 1],
        ['question' => 'What does merge(df1, df2, by="id") do?', 'options' => ['Appends df2 rows to df1', 'Joins two data frames on the "id" column (default inner join)', 'Merges all columns regardless of matching', 'Creates a union of all rows from both frames'], 'correct' => 1],
        ['question' => 'What does toupper("hello") return?', 'options' => ['"hello"', '"Hello"', '"HELLO"', '"hELLO"'], 'correct' => 2],
    ]],
    ['label' => 'Advanced', 'questions' => [
        ['question' => 'What does t.test() perform?', 'options' => ['A chi-squared test', 'Student\'s t-test to compare means between one or two groups', 'An ANOVA test', 'A correlation test'], 'correct' => 1],
        ['question' => 'What does lm() fit in R?', 'options' => ['A logistic model', 'A linear model (linear regression)', 'A mixed-effects model', 'A latent model'], 'correct' => 1],
        ['question' => 'In summary(lm_model), what is the R-squared value?', 'options' => ['The correlation coefficient', 'The proportion of variance in the dependent variable explained by the model', 'The p-value of the intercept', 'The residual standard error'], 'correct' => 1],
        ['question' => 'What family argument is used for logistic regression in glm()?', 'options' => ['gaussian', 'poisson', 'binomial', 'gamma'], 'correct' => 2],
        ['question' => 'What does cor() compute?', 'options' => ['Linear regression coefficients', 'The correlation coefficient(s) between variables', 'Covariance matrix', 'Principal components'], 'correct' => 1],
        ['question' => 'What does chisq.test() test?', 'options' => ['Difference in means between groups', 'Independence between two categorical variables', 'Normality of a distribution', 'Equality of variances'], 'correct' => 1],
        ['question' => 'What does anova() test?', 'options' => ['Correlation between variables', 'Differences in means across three or more groups', 'Association in a contingency table', 'Regression coefficients'], 'correct' => 1],
        ['question' => 'What does ts() create in R?', 'options' => ['A test set', 'A time series object', 'A transpose of a matrix', 'A TypeScript integration'], 'correct' => 1],
        ['question' => 'What does the decompose() function do for time series?', 'options' => ['Breaks a time series into rows', 'Decomposes a time series into trend, seasonal, and residual components', 'Removes outliers from a series', 'Converts a series to a data frame'], 'correct' => 1],
        ['question' => 'What does acf() compute?', 'options' => ['Auto-Correlation Function showing correlations between time series values at different lags', 'Average Correlation Factor', 'Adjusted Coefficients Fit', 'Autoregressive Computed Factors'], 'correct' => 0],
        ['question' => 'What is R Markdown used for?', 'options' => ['Writing R packages', 'Creating dynamic documents that combine R code, output, and narrative text', 'Styling R console output', 'Generating unit tests'], 'correct' => 1],
        ['question' => 'What does tryCatch() do in R?', 'options' => ['Catches fish with R', 'Handles errors and exceptions gracefully, allowing code to continue after an error', 'Retries failed computations', 'Validates function arguments'], 'correct' => 1],
        ['question' => 'What is lexical scoping in R?', 'options' => ['Scoping based on runtime call stack', 'R looks up variables in the environment where a function was defined, not where it was called', 'Scoping based on alphabetical order of variable names', 'A scoping rule specific to for loops'], 'correct' => 1],
        ['question' => 'What is a closure in R?', 'options' => ['A way to close a database connection', 'A function that retains access to its enclosing environment\'s variables', 'A sealed data frame', 'A completed for loop'], 'correct' => 1],
        ['question' => 'What does Reduce("+", c(1,2,3,4)) return?', 'options' => ['c(1,3,6,10)', '24', '10', 'c(1,2,3,4)'], 'correct' => 2],
        ['question' => 'What does Filter(function(x) x &gt; 2, c(1,2,3,4)) return?', 'options' => ['c(1, 2)', 'c(3, 4)', 'c(TRUE, TRUE)', 'c(2, 3, 4)'], 'correct' => 1],
        ['question' => 'What does sprintf("%.2f", 3.14159) return?', 'options' => ['"3.1"', '"3.141"', '"3.14"', '"3.1416"'], 'correct' => 2],
        ['question' => 'What does as.Date("2024-01-15") create?', 'options' => ['A character string', 'A Date object', 'A numeric timestamp', 'A POSIXct object'], 'correct' => 1],
        ['question' => 'What does the wilcox.test() perform?', 'options' => ['Parametric comparison of means', 'Wilcoxon rank-sum test (non-parametric alternative to t-test)', 'F-test for variance equality', 'Shapiro-Wilk normality test'], 'correct' => 1],
        ['question' => 'What does environment() return in R?', 'options' => ['The system environment variables', 'The environment associated with a function or the current environment', 'The R session info', 'The global variables list'], 'correct' => 1],
        ['question' => 'In multiple regression with lm(y ~ x1 + x2), what does the + mean?', 'options' => ['Add the values of x1 and x2', 'Include both x1 and x2 as independent predictors', 'Interaction between x1 and x2', 'Sum x1 and x2 into one predictor'], 'correct' => 1],
        ['question' => 'What does the Map() function do in R?', 'options' => ['Maps geographic data', 'Applies a function to corresponding elements of multiple lists/vectors simultaneously', 'Creates a named list', 'Maps factor levels to integers'], 'correct' => 1],
        ['question' => 'What does options(stringsAsFactors = FALSE) do?', 'options' => ['Converts all factors to strings globally', 'Prevents R from automatically converting character columns to factors when reading data', 'Disables string comparison', 'Turns off factor level ordering'], 'correct' => 1],
        ['question' => 'What does the &lt;&lt;- operator do in R?', 'options' => ['Less than comparison', 'Assigns to a variable in the parent/enclosing environment (global assignment)', 'Creates a deep copy', 'Appends to a vector'], 'correct' => 1],
        ['question' => 'What is the difference between == and identical() in R?', 'options' => ['They are identical', '== is vectorized and may return NA for missing values; identical() checks exact equality and returns a single TRUE/FALSE', 'identical() only works for numbers', '== checks class while identical() checks value'], 'correct' => 1],
    ]],
    ['label' => 'Expert', 'questions' => [
        ['question' => 'What are the two main files in a Shiny application?', 'options' => ['main.R and helper.R', 'ui.R and server.R (or combined in app.R)', 'front.R and back.R', 'interface.R and logic.R'], 'correct' => 1],
        ['question' => 'What does reactive() do in Shiny?', 'options' => ['Creates a static output', 'Creates a reactive expression that automatically re-executes when its inputs change', 'Renders a plot', 'Initializes the UI components'], 'correct' => 1],
        ['question' => 'What does observeEvent() do in Shiny?', 'options' => ['Creates a reactive output', 'Runs code in response to a specific reactive event (like a button click)', 'Observes all input changes', 'Creates an event log'], 'correct' => 1],
        ['question' => 'What package is used for R package development scaffolding?', 'options' => ['pkgtools', 'devtools', 'packageR', 'rtools'], 'correct' => 1],
        ['question' => 'What does roxygen2 do in R package development?', 'options' => ['Compiles R code to C++', 'Generates documentation from specially formatted comments (#\') in source code', 'Creates package vignettes', 'Runs unit tests'], 'correct' => 1],
        ['question' => 'In data.table, what does DT[i, j, by] stand for?', 'options' => ['index, join, bind', 'row filter (i), column expression (j), grouping (by)', 'iteration, join, batch', 'input, jobs, bytes'], 'correct' => 1],
        ['question' => 'What does the := operator do in data.table?', 'options' => ['Tests equality', 'Assigns columns by reference (in-place modification without copying)', 'Creates a formula', 'Declares a type'], 'correct' => 1],
        ['question' => 'What does fread() in data.table do?', 'options' => ['Reads a single row', 'Fast file reading for large delimited files, much faster than read.csv()', 'Reads R binary files', 'Reads data from a database'], 'correct' => 1],
        ['question' => 'What is the S3 object system in R?', 'options' => ['A formal class system with strict type checking', 'An informal OOP system using generic functions and class attributes on regular R objects', 'A system for S3 storage integration', 'A system with explicit method dispatch tables'], 'correct' => 1],
        ['question' => 'What distinguishes S4 classes from S3 in R?', 'options' => ['S4 is faster than S3', 'S4 has formal class definitions with typed slots, validity checking, and explicit setClass()/setMethod()', 'S4 only works with numeric data', 'S4 classes are defined with &lt;-'], 'correct' => 1],
        ['question' => 'What does makeCluster() in the parallel package create?', 'options' => ['A cluster of data points', 'A cluster of R worker processes for parallel computation', 'A Kubernetes cluster', 'A hierarchical cluster from data'], 'correct' => 1],
        ['question' => 'What does mclapply() do in the parallel package?', 'options' => ['Applies a function in a for loop', 'Applies a function in parallel using forking (Unix/Mac only)', 'Applies a Markov chain to each element', 'Creates a multi-core cluster'], 'correct' => 1],
        ['question' => 'What does facet_wrap() do in ggplot2?', 'options' => ['Wraps long axis labels', 'Creates small multiple plots (facets) split by one variable', 'Applies a theme wrapper', 'Wraps geoms in a container'], 'correct' => 1],
        ['question' => 'What is the purpose of the NAMESPACE file in an R package?', 'options' => ['Stores package metadata like version and author', 'Specifies which functions are exported and which external functions are imported', 'Defines the package namespace variable', 'Lists package dependencies'], 'correct' => 1],
        ['question' => 'What does scale_color_manual() do in ggplot2?', 'options' => ['Scales axis ranges manually', 'Manually defines the color scale mapping for a color aesthetic', 'Creates a manual color picker', 'Applies color to all geoms at once'], 'correct' => 1],
        ['question' => 'What is the arrow package used for in R?', 'options' => ['Creating arrow annotations in plots', 'Reading and writing Apache Arrow and Parquet files, enabling work with large datasets', 'Creating directed graph structures', 'Building sequential pipelines'], 'correct' => 1],
        ['question' => 'What does Rcpp allow you to do?', 'options' => ['Run Python code in R', 'Integrate and call C++ code from R for performance-critical operations', 'Compile R to C++', 'Interface R with Java'], 'correct' => 1],
        ['question' => 'In Shiny, what does renderPlot() do?', 'options' => ['Plots data to PDF', 'Creates a reactive plot output that re-renders when reactive dependencies change', 'Renders a ggplot2 object only', 'Saves a plot to disk'], 'correct' => 1],
        ['question' => 'What does the .SD special variable mean in data.table?', 'options' => ['Standard Deviation', 'Subset of Data — a data.table containing all columns for each group when using by=', 'Sorted Data', 'Summary Data'], 'correct' => 1],
        ['question' => 'What is the 7-1 architecture pattern in Sass (relevant in the R theming context via custom CSS)?', 'options' => ['7 components, 1 output file', '7 folders of partials plus 1 main file that imports them all', '7 themes with 1 override', 'Not applicable to R'], 'correct' => 1],
        ['question' => 'What does bench::mark() do in R?', 'options' => ['Marks important code sections', 'Benchmarks and compares the performance (speed and memory) of R expressions', 'Sets a benchmark variable', 'Creates a performance report'], 'correct' => 1],
        ['question' => 'What does the .Call() interface do in R?', 'options' => ['Makes HTTP API calls', 'Calls a compiled C/C++ function registered in an R package using R\'s internal SEXP types', 'Calls a function with error handling', 'Makes asynchronous function calls'], 'correct' => 1],
        ['question' => 'In ggplot2, what does theme_minimal() do?', 'options' => ['Reduces plot file size', 'Applies a clean, minimal theme with white background and light gridlines', 'Removes all theme elements', 'Creates a minimal color palette'], 'correct' => 1],
        ['question' => 'What does sparklyr allow R users to do?', 'options' => ['Connect R to the Spark web framework', 'Interface with Apache Spark for distributed big data processing from R', 'Write R code in Jupyter sparkles', 'Run R in spark-based hardware'], 'correct' => 1],
        ['question' => 'What does the vctrs package provide in R?', 'options' => ['Vector graphics rendering', 'A toolkit for creating new S3 vector types with correct behavior for size, type, and coercion', 'Vectorized math operations', 'Version control for R scripts'], 'correct' => 1],
    ]],
];
require_once __DIR__ . '/quiz-engine.php';
