<?php
$page_title = 'React Quiz – 100 Levels – CodeFoundry';
$active_page = 'training';
$quiz_title  = 'React';
$quiz_slug   = 'react';
$quiz_tiers  = [
    ['label' => 'Introduction', 'questions' => [
        ['question' => 'What is React?', 'options' => ['A framework', 'A JavaScript library for building UIs', 'A database', 'A server'], 'correct' => 1],
        ['question' => 'Who created React?', 'options' => ['Google', 'Facebook/Meta', 'Twitter', 'Microsoft'], 'correct' => 1],
        ['question' => 'What is JSX?', 'options' => ['Java extension', 'JavaScript XML syntax', 'JSON extension', 'CSS syntax'], 'correct' => 1],
        ['question' => 'What method renders React in React 17?', 'options' => ['render()', 'ReactDOM.render()', 'display()', 'mount()'], 'correct' => 1],
        ['question' => 'What method renders React in React 18?', 'options' => ['ReactDOM.render()', 'createRoot().render()', 'mount()', 'display()'], 'correct' => 1],
        ['question' => 'What is a React component?', 'options' => ['A CSS file', 'A reusable piece of UI', 'A database', 'A server'], 'correct' => 1],
        ['question' => 'How do you create a function component?', 'options' => ['class Component', 'function Component()', 'component()', 'new Component()'], 'correct' => 1],
        ['question' => 'How do you pass data to components?', 'options' => ['state', 'props', 'arguments', 'parameters'], 'correct' => 1],
        ['question' => 'How do you read props in a function component?', 'options' => ['this.props', 'props parameter', 'getProps()', 'readProps()'], 'correct' => 1],
        ['question' => 'What hook manages component state?', 'options' => ['useEffect', 'useState', 'useContext', 'useReducer'], 'correct' => 1],
        ['question' => 'How do you render a list in React?', 'options' => ['for loop', 'map()', 'forEach()', 'filter()'], 'correct' => 1],
        ['question' => 'What is required when rendering lists?', 'options' => ['id attribute', 'key prop', 'index', 'name'], 'correct' => 1],
        ['question' => 'How do you conditionally render with AND?', 'options' => ['if statement', '&&', 'condition ? :', 'switch'], 'correct' => 1],
        ['question' => 'How do you conditionally render with if-else?', 'options' => ['if statement', '&&', 'ternary ? :', 'switch'], 'correct' => 2],
        ['question' => 'How do you attach click handlers?', 'options' => ['onclick', 'onClick', 'click', 'onPress'], 'correct' => 1],
        ['question' => 'How do you attach change handlers?', 'options' => ['onchange', 'onChange', 'change', 'onInput'], 'correct' => 1],
        ['question' => 'What is a controlled input?', 'options' => ['Uncontrolled', 'Input with value from state', 'Auto input', 'Read-only input'], 'correct' => 1],
        ['question' => 'What is component composition?', 'options' => ['Inheritance', 'Combining components', 'State management', 'Props passing'], 'correct' => 1],
        ['question' => 'What is one-way data flow?', 'options' => ['Bidirectional', 'Data flows down via props', 'Data flows up', 'No data flow'], 'correct' => 1],
        ['question' => 'What tool helps debug React?', 'options' => ['Chrome DevTools', 'React Developer Tools', 'Console', 'Debugger'], 'correct' => 1],
        ['question' => 'What creates a React app quickly?', 'options' => ['npm init', 'Create React App', 'React CLI', 'npx react'], 'correct' => 1],
        ['question' => 'What JSX rule requires one root element?', 'options' => ['Multiple roots allowed', 'Must have single root', 'No elements needed', 'Unlimited roots'], 'correct' => 1],
        ['question' => 'What attribute replaces "class" in JSX?', 'options' => ['class', 'className', 'htmlClass', 'cssClass'], 'correct' => 1],
        ['question' => 'What attribute replaces "for" in JSX?', 'options' => ['for', 'htmlFor', 'forLabel', 'labelFor'], 'correct' => 1],
        ['question' => 'Are JSX events camelCase?', 'options' => ['No, lowercase', 'Yes, camelCase', 'UPPERCASE', 'snake_case'], 'correct' => 1],
        ['question' => 'What is a fragment in React?', 'options' => ['Component', 'Empty wrapper <></>', 'State', 'Props'], 'correct' => 1],
        ['question' => 'What is React.Fragment?', 'options' => ['Component type', 'Explicit fragment syntax', 'Hook', 'State manager'], 'correct' => 1],
        ['question' => 'What is default export?', 'options' => ['export { }', 'export default Component', 'export *', 'module.exports'], 'correct' => 1],
        ['question' => 'What is named export?', 'options' => ['export default', 'export { Component }', 'export *', 'module.exports'], 'correct' => 1],
        ['question' => 'How do you import default export?', 'options' => ['import { Component }', 'import Component', 'import * as', 'require()'], 'correct' => 1],
    ]],
    ['label' => 'Beginner', 'questions' => [
        ['question' => 'What hook runs after render?', 'options' => ['useState', 'useEffect', 'useContext', 'useRef'], 'correct' => 1],
        ['question' => 'What is the dependency array in useEffect?', 'options' => ['State list', 'Controls when effect runs', 'Props list', 'Component list'], 'correct' => 1],
        ['question' => 'What does empty dependency array mean?', 'options' => ['Run always', 'Run once on mount', 'Never run', 'Run on unmount'], 'correct' => 1],
        ['question' => 'What does useEffect cleanup function do?', 'options' => ['Setup', 'Cleanup on unmount or re-run', 'Initialize', 'Render'], 'correct' => 1],
        ['question' => 'What hook accesses DOM elements?', 'options' => ['useState', 'useContext', 'useRef', 'useEffect'], 'correct' => 2],
        ['question' => 'Can useRef store mutable values?', 'options' => ['No', 'Yes', 'Only DOM refs', 'Only numbers'], 'correct' => 1],
        ['question' => 'What hook accesses Context?', 'options' => ['useState', 'useEffect', 'useContext', 'useReducer'], 'correct' => 2],
        ['question' => 'How do you create Context?', 'options' => ['useState()', 'createContext()', 'newContext()', 'useContext()'], 'correct' => 1],
        ['question' => 'What is a Context Provider?', 'options' => ['Consumer', 'Supplies context values', 'Hook', 'Component'], 'correct' => 1],
        ['question' => 'What is lifting state up?', 'options' => ['Lower state', 'Move state to common ancestor', 'Remove state', 'Copy state'], 'correct' => 1],
        ['question' => 'What is prop drilling?', 'options' => ['Good pattern', 'Passing props through many levels', 'State management', 'Context'], 'correct' => 1],
        ['question' => 'What does useReducer do?', 'options' => ['Context', 'Complex state logic', 'DOM access', 'Effect handling'], 'correct' => 1],
        ['question' => 'What is a reducer function?', 'options' => ['Hook', '(state, action) => newState', 'Component', 'Effect'], 'correct' => 1],
        ['question' => 'What does dispatch do in useReducer?', 'options' => ['Gets state', 'Sends actions', 'Updates DOM', 'Renders'], 'correct' => 1],
        ['question' => 'What are custom hooks?', 'options' => ['Built-in hooks', 'Reusable hook logic', 'Components', 'Props'], 'correct' => 1],
        ['question' => 'What must custom hooks start with?', 'options' => ['get', 'use', 'hook', 'custom'], 'correct' => 1],
        ['question' => 'What are the Rules of Hooks?', 'options' => ['No rules', 'Call at top level, only in React functions', 'Call anywhere', 'Call in loops'], 'correct' => 1],
        ['question' => 'What does React.memo do?', 'options' => ['State', 'Memoizes component', 'Effect', 'Context'], 'correct' => 1],
        ['question' => 'What does useMemo do?', 'options' => ['Memoizes components', 'Memoizes values', 'Memoizes effects', 'Nothing'], 'correct' => 1],
        ['question' => 'What does useCallback do?', 'options' => ['Memoizes values', 'Memoizes functions', 'Calls functions', 'Creates callbacks'], 'correct' => 1],
        ['question' => 'What is React Router?', 'options' => ['Built-in routing', 'Third-party routing library', 'HTTP client', 'State manager'], 'correct' => 1],
        ['question' => 'What component wraps routes in React Router v6?', 'options' => ['Router', 'BrowserRouter', 'Routes', 'Switch'], 'correct' => 1],
        ['question' => 'What component defines routes in v6?', 'options' => ['Switch', 'Routes', 'Router', 'Route'], 'correct' => 1],
        ['question' => 'What component defines individual route?', 'options' => ['Path', 'Route', 'Link', 'Navigate'], 'correct' => 1],
        ['question' => 'What component creates links?', 'options' => ['<a>', 'Link', 'Navigate', 'Redirect'], 'correct' => 1],
        ['question' => 'What is NavLink?', 'options' => ['Regular link', 'Link with active styling', 'Navigation bar', 'Menu'], 'correct' => 1],
        ['question' => 'What hook navigates programmatically?', 'options' => ['useRouter', 'useNavigate', 'useHistory', 'useLocation'], 'correct' => 1],
        ['question' => 'What hook accesses route params?', 'options' => ['useNavigate', 'useParams', 'useRoute', 'useMatch'], 'correct' => 1],
        ['question' => 'What is a controlled component?', 'options' => ['Uncontrolled', 'Form input controlled by state', 'DOM controlled', 'Auto controlled'], 'correct' => 1],
        ['question' => 'What is an uncontrolled component?', 'options' => ['Controlled by state', 'Form input controlled by DOM', 'Auto controlled', 'No control'], 'correct' => 1],
        ['question' => 'What is React.StrictMode?', 'options' => ['Production mode', 'Development checks', 'Error boundary', 'Context'], 'correct' => 1],
        ['question' => 'What are error boundaries?', 'options' => ['Hooks', 'Components catching errors', 'Context', 'Props'], 'correct' => 1],
        ['question' => 'What lifecycle method catches errors?', 'options' => ['componentDidMount', 'componentDidCatch', 'useEffect', 'useState'], 'correct' => 1],
        ['question' => 'What method gets error state?', 'options' => ['componentDidCatch', 'getDerivedStateFromError', 'useError', 'catchError'], 'correct' => 1],
        ['question' => 'What hook accesses location?', 'options' => ['useParams', 'useLocation', 'useNavigate', 'useRoute'], 'correct' => 1],
    ]],
    ['label' => 'Intermediate', 'questions' => [
        ['question' => 'What is concurrent rendering in React 18?', 'options' => ['Synchronous', 'Interruptible rendering', 'Serial rendering', 'Blocking'], 'correct' => 1],
        ['question' => 'What is Suspense used for?', 'options' => ['State', 'Loading states', 'Errors', 'Effects'], 'correct' => 1],
        ['question' => 'What does startTransition do?', 'options' => ['Starts app', 'Marks updates as non-urgent', 'Transitions pages', 'Animates'], 'correct' => 1],
        ['question' => 'What does useDeferredValue do?', 'options' => ['Defers rendering', 'Defers value update', 'Delays effects', 'Cancels updates'], 'correct' => 1],
        ['question' => 'What does useTransition return?', 'options' => ['Value', 'isPending flag and startTransition', 'State', 'Effect'], 'correct' => 1],
        ['question' => 'What does useId do?', 'options' => ['Gets component ID', 'Generates unique IDs', 'Gets element ID', 'Creates keys'], 'correct' => 1],
        ['question' => 'What is useSyncExternalStore for?', 'options' => ['Context', 'Subscribing to external stores', 'Effects', 'State'], 'correct' => 1],
        ['question' => 'Can Suspense be used for data fetching?', 'options' => ['No', 'Yes, with compatible libraries', 'Only code splitting', 'Only in React 19'], 'correct' => 1],
        ['question' => 'What does React.lazy do?', 'options' => ['Lazy state', 'Lazy loads components', 'Lazy effects', 'Delays rendering'], 'correct' => 1],
        ['question' => 'What is code splitting?', 'options' => ['Code review', 'Splitting bundles for performance', 'Code formatting', 'Code analysis'], 'correct' => 1],
        ['question' => 'How do you optimize Context performance?', 'options' => ['Use one context', 'Split contexts', 'Avoid context', 'Merge contexts'], 'correct' => 1],
        ['question' => 'What is Redux Toolkit?', 'options' => ['Redux alternative', 'Official Redux toolset', 'State library', 'Effect manager'], 'correct' => 1],
        ['question' => 'What does configureStore do?', 'options' => ['Creates component', 'Creates Redux store', 'Configures React', 'Sets up router'], 'correct' => 1],
        ['question' => 'What does createSlice do?', 'options' => ['Splits code', 'Creates Redux slice', 'Creates component', 'Slices array'], 'correct' => 1],
        ['question' => 'What does createAsyncThunk do?', 'options' => ['Sync action', 'Async action creator', 'Effect', 'Promise'], 'correct' => 1],
        ['question' => 'What hook selects Redux state?', 'options' => ['useState', 'useSelector', 'useContext', 'useRedux'], 'correct' => 1],
        ['question' => 'What hook dispatches Redux actions?', 'options' => ['useAction', 'useDispatch', 'useRedux', 'useStore'], 'correct' => 1],
        ['question' => 'What is React Query (TanStack Query)?', 'options' => ['Built-in', 'Data fetching library', 'State manager', 'Router'], 'correct' => 1],
        ['question' => 'What does useQuery do?', 'options' => ['Queries DOM', 'Fetches and caches data', 'Queries state', 'Searches'], 'correct' => 1],
        ['question' => 'What does useMutation do?', 'options' => ['Reads data', 'Mutates data', 'Changes state', 'Updates DOM'], 'correct' => 1],
        ['question' => 'What is Zustand?', 'options' => ['Context', 'Lightweight state manager', 'Router', 'Effect manager'], 'correct' => 1],
        ['question' => 'What is React Hook Form?', 'options' => ['Form component', 'Form management library', 'Hook', 'Validator'], 'correct' => 1],
        ['question' => 'What is Yup?', 'options' => ['State manager', 'Validation schema library', 'Form library', 'Router'], 'correct' => 1],
        ['question' => 'What is Zod?', 'options' => ['State manager', 'TypeScript-first validation', 'Form library', 'Router'], 'correct' => 1],
        ['question' => 'What are portals?', 'options' => ['Routing', 'Render outside parent DOM', 'Context', 'State'], 'correct' => 1],
        ['question' => 'How do you create a portal?', 'options' => ['usePortal', 'ReactDOM.createPortal', 'Portal component', 'createPortal hook'], 'correct' => 1],
        ['question' => 'What is a render prop?', 'options' => ['Rendered prop', 'Prop that is a function', 'State prop', 'Effect prop'], 'correct' => 1],
        ['question' => 'What is a Higher-Order Component (HOC)?', 'options' => ['High priority', 'Function returning component', 'Parent component', 'Root component'], 'correct' => 1],
        ['question' => 'What is the compound component pattern?', 'options' => ['Single component', 'Components working together', 'Complex component', 'Composed props'], 'correct' => 1],
        ['question' => 'What is the controlled component pattern?', 'options' => ['Uncontrolled', 'Parent controls state', 'Self-controlled', 'No control'], 'correct' => 1],
        ['question' => 'What is React Testing Library?', 'options' => ['Unit tester', 'User-centric testing library', 'E2E tester', 'Performance tester'], 'correct' => 1],
        ['question' => 'What does render() do in RTL?', 'options' => ['Renders to DOM', 'Renders to test environment', 'Renders to browser', 'Compiles JSX'], 'correct' => 1],
        ['question' => 'What is the screen object?', 'options' => ['Display', 'Query helpers', 'DOM reference', 'Browser window'], 'correct' => 1],
        ['question' => 'What is userEvent in testing?', 'options' => ['User object', 'User interaction simulation', 'Event handler', 'Custom event'], 'correct' => 1],
        ['question' => 'What does waitFor do?', 'options' => ['Waits time', 'Waits for async updates', 'Waits for user', 'Delays test'], 'correct' => 1],
    ]],
    ['label' => 'Advanced', 'questions' => [
        ['question' => 'What is React Fiber?', 'options' => ['CSS framework', 'React reconciliation engine', 'State manager', 'Router'], 'correct' => 1],
        ['question' => 'What is a work unit in Fiber?', 'options' => ['Component', 'Fiber node', 'Element', 'Hook'], 'correct' => 1],
        ['question' => 'What is reconciliation?', 'options' => ['Rendering', 'Diffing algorithm', 'Compilation', 'Optimization'], 'correct' => 1],
        ['question' => 'How does React\'s diffing work?', 'options' => ['Compares all', 'Heuristic O(n) algorithm', 'O(n^3) algorithm', 'No diffing'], 'correct' => 1],
        ['question' => 'Why are keys important in lists?', 'options' => ['Style', 'Helps reconciliation', 'Required syntax', 'Accessibility'], 'correct' => 1],
        ['question' => 'What is automatic batching in React 18?', 'options' => ['No batching', 'Batches all updates', 'Manual batching', 'Sync updates'], 'correct' => 1],
        ['question' => 'What are React Server Components?', 'options' => ['Client components', 'Server-rendered components', 'SSR', 'Static components'], 'correct' => 1],
        ['question' => 'What are server actions?', 'options' => ['Client actions', 'Server-side mutations', 'API calls', 'Effects'], 'correct' => 1],
        ['question' => 'What is streaming SSR?', 'options' => ['Static SSR', 'Progressive HTML streaming', 'Client rendering', 'Full SSR'], 'correct' => 1],
        ['question' => 'What is Suspense streaming?', 'options' => ['No streaming', 'Progressive component loading', 'Video streaming', 'Data streaming'], 'correct' => 1],
        ['question' => 'What is hydration?', 'options' => ['Rendering', 'Attaching events to SSR HTML', 'Loading data', 'Caching'], 'correct' => 1],
        ['question' => 'What is partial hydration?', 'options' => ['Full hydration', 'Selective hydration', 'No hydration', 'Lazy hydration'], 'correct' => 1],
        ['question' => 'What is React\'s event system?', 'options' => ['Native events', 'Synthetic event system', 'Custom events', 'DOM events'], 'correct' => 1],
        ['question' => 'What is event delegation in React?', 'options' => ['No delegation', 'Events attached to root', 'Individual listeners', 'Inline events'], 'correct' => 1],
        ['question' => 'What is the React DevTools Profiler?', 'options' => ['Code editor', 'Performance profiling tool', 'Debugger', 'Linter'], 'correct' => 1],
        ['question' => 'How do you prevent unnecessary renders?', 'options' => ['Always render', 'React.memo, useMemo, useCallback', 'Disable updates', 'forceUpdate'], 'correct' => 1],
        ['question' => 'When should you use useMemo?', 'options' => ['Always', 'Expensive calculations', 'All values', 'Never'], 'correct' => 1],
        ['question' => 'When should you use useCallback?', 'options' => ['Always', 'When passing callbacks to optimized children', 'All functions', 'Never'], 'correct' => 1],
        ['question' => 'What is ComponentProps<T> in TypeScript?', 'options' => ['Component type', 'Extracts component props', 'Props interface', 'Type helper'], 'correct' => 1],
        ['question' => 'What is FC in TypeScript?', 'options' => ['Function Call', 'FunctionComponent type', 'Functional Class', 'Fixed Component'], 'correct' => 1],
        ['question' => 'What is ReactNode type?', 'options' => ['DOM node', 'Any renderable content', 'Element', 'Component'], 'correct' => 1],
        ['question' => 'What is PropsWithChildren?', 'options' => ['All props', 'Props with children prop', 'Parent props', 'Child props'], 'correct' => 1],
        ['question' => 'What does forwardRef do?', 'options' => ['Forwards props', 'Forwards refs', 'Forwards state', 'Forwards events'], 'correct' => 1],
        ['question' => 'What does useImperativeHandle do?', 'options' => ['Handles events', 'Customizes ref exposure', 'Handles effects', 'Manages state'], 'correct' => 1],
        ['question' => 'What is a custom renderer?', 'options' => ['React DOM', 'Custom target renderer', 'Component', 'Hook'], 'correct' => 1],
        ['question' => 'What package creates custom renderers?', 'options' => ['react', 'react-reconciler', 'react-dom', 'react-native'], 'correct' => 1],
        ['question' => 'What are some custom renderer examples?', 'options' => ['React DOM only', 'React Native, React Three Fiber', 'None', 'Angular'], 'correct' => 1],
        ['question' => 'What is selector optimization?', 'options' => ['No optimization', 'Optimizing Redux selectors', 'CSS selectors', 'DOM selectors'], 'correct' => 1],
        ['question' => 'Should you use index as key?', 'options' => ['Always', 'Avoid if list changes', 'Always best', 'Never'], 'correct' => 1],
        ['question' => 'What causes unnecessary re-renders?', 'options' => ['Nothing', 'New object/function references', 'Props', 'State'], 'correct' => 1],
        ['question' => 'What is the use() hook in React 19?', 'options' => ['Old hook', 'Reads promises/context', 'Custom hook', 'Deprecated'], 'correct' => 1],
        ['question' => 'What are actions in React 19?', 'options' => ['Redux actions', 'Async transitions with pending states', 'Server actions', 'Events'], 'correct' => 1],
        ['question' => 'What is asset loading in React 19?', 'options' => ['Manual loading', 'Automatic resource loading', 'Lazy loading', 'Code splitting'], 'correct' => 1],
        ['question' => 'What is the document metadata API in React 19?', 'options' => ['DOM API', 'Built-in title/meta management', 'SEO library', 'Router feature'], 'correct' => 1],
        ['question' => 'What does useOptimistic do?', 'options' => ['Optimizes code', 'Optimistic UI updates', 'Performance', 'Caching'], 'correct' => 1],
    ]],
    ['label' => 'Expert', 'questions' => [
        ['question' => 'What is a FiberNode?', 'options' => ['DOM node', 'Internal React node', 'Component', 'Element'], 'correct' => 1],
        ['question' => 'What fields does FiberNode have?', 'options' => ['None', 'type, key, props, alternate, child, sibling, return', 'Only props', 'Only type'], 'correct' => 1],
        ['question' => 'What is the alternate field?', 'options' => ['Backup', 'Current/workInProgress pair', 'Alternative prop', 'Fallback'], 'correct' => 1],
        ['question' => 'What is pendingProps?', 'options' => ['Old props', 'Props for next render', 'All props', 'No props'], 'correct' => 1],
        ['question' => 'What is memoizedState?', 'options' => ['Current state', 'Committed state', 'Old state', 'No state'], 'correct' => 1],
        ['question' => 'What is performUnitOfWork?', 'options' => ['Renders', 'Processes fiber work', 'Commits', 'Mounts'], 'correct' => 1],
        ['question' => 'What is beginWork?', 'options' => ['Ends work', 'Starts fiber processing', 'Commits work', 'Finishes work'], 'correct' => 1],
        ['question' => 'What is completeWork?', 'options' => ['Starts work', 'Finishes fiber processing', 'Begins work', 'Cancels work'], 'correct' => 1],
        ['question' => 'What is the commit phase?', 'options' => ['Render phase', 'DOM mutation phase', 'Reconciliation', 'Diffing'], 'correct' => 1],
        ['question' => 'What is commitMutationEffects?', 'options' => ['Reads DOM', 'Mutates DOM', 'Renders', 'Calculates'], 'correct' => 1],
        ['question' => 'What is commitLayoutEffects?', 'options' => ['Before DOM', 'After DOM mutations', 'During render', 'Before render'], 'correct' => 1],
        ['question' => 'What is the effect list?', 'options' => ['All effects', 'List of fibers with effects', 'Effect hooks', 'Side effects'], 'correct' => 1],
        ['question' => 'What is React\'s scheduler?', 'options' => ['Browser scheduler', 'Priority-based task scheduler', 'Time scheduler', 'No scheduler'], 'correct' => 1],
        ['question' => 'What does the scheduler use?', 'options' => ['setTimeout', 'MessageChannel', 'requestIdleCallback', 'setInterval'], 'correct' => 1],
        ['question' => 'What are task priority levels?', 'options' => ['One level', 'Immediate, UserBlocking, Normal, Low, Idle', 'Two levels', 'No priority'], 'correct' => 1],
        ['question' => 'What is the lane model?', 'options' => ['Old model', 'Priority representation with 31 lanes', 'Single lane', 'No model'], 'correct' => 1],
        ['question' => 'How are lanes used?', 'options' => ['Not used', 'Bitwise operations for priority', 'Array index', 'Numbers'], 'correct' => 1],
        ['question' => 'What is dispatcher switching?', 'options' => ['No switching', 'Different hook implementations per phase', 'Component switching', 'State switching'], 'correct' => 1],
        ['question' => 'How are hooks stored?', 'options' => ['Array', 'Linked list', 'Object', 'Map'], 'correct' => 1],
        ['question' => 'What is the useState queue?', 'options' => ['No queue', 'Update queue for state', 'Component queue', 'Render queue'], 'correct' => 1],
        ['question' => 'What is baseQueue in useState?', 'options' => ['New updates', 'Skipped updates', 'All updates', 'No updates'], 'correct' => 1],
        ['question' => 'What is pending in useState?', 'options' => ['Old updates', 'New unprocessed updates', 'All updates', 'No updates'], 'correct' => 1],
        ['question' => 'When are effects scheduled?', 'options' => ['Immediately', 'After commit phase', 'Before render', 'During render'], 'correct' => 1],
        ['question' => 'What are passive effects?', 'options' => ['Sync effects', 'Async effects (useEffect)', 'Layout effects', 'No effects'], 'correct' => 1],
        ['question' => 'What is the use() hook?', 'options' => ['Custom hook', 'Primitive for reading resources', 'Effect hook', 'State hook'], 'correct' => 1],
        ['question' => 'What is the RSC payload?', 'options' => ['HTML', 'Serialized component tree', 'JSON', 'XML'], 'correct' => 1],
        ['question' => 'How is RSC payload formatted?', 'options' => ['HTML', 'Custom wire format', 'JSON', 'XML'], 'correct' => 1],
        ['question' => 'What is the edge runtime?', 'options' => ['Node.js', 'Lightweight serverless runtime', 'Browser', 'Deno'], 'correct' => 1],
        ['question' => 'What are edge runtime limitations?', 'options' => ['None', 'Limited Node APIs', 'Full Node.js', 'No limits'], 'correct' => 1],
        ['question' => 'What is React Native Fabric?', 'options' => ['Old renderer', 'New React Native renderer', 'Web renderer', 'Game engine'], 'correct' => 1],
        ['question' => 'What is a reconciler use case?', 'options' => ['None', 'Custom rendering targets', 'Debugging', 'Testing'], 'correct' => 1],
        ['question' => 'What is the work loop?', 'options' => ['Event loop', 'Fiber processing loop', 'Animation loop', 'Request loop'], 'correct' => 1],
        ['question' => 'What is interruptible rendering?', 'options' => ['Blocking render', 'Render can pause/resume', 'Fast render', 'No render'], 'correct' => 1],
        ['question' => 'What is time slicing?', 'options' => ['No slicing', 'Breaking work into chunks', 'Fast rendering', 'Slow rendering'], 'correct' => 1],
        ['question' => 'What triggers re-render?', 'options' => ['Nothing', 'State/props change, forceUpdate', 'Time', 'User action'], 'correct' => 1],
    ]],
];
require_once __DIR__ . '/quiz-engine.php';
