<?php
$page_title = 'SciPy Quiz – 100 Levels – CodeFoundry';
$active_page = 'training';
$quiz_title  = 'SciPy';
$quiz_slug   = 'scipy';
$quiz_tiers  = [
    ['label' => 'Introduction', 'questions' => [
        ['question' => 'What is SciPy?', 'options' => ['A web framework', 'A scientific computing library for Python', 'A database library', 'A machine learning framework'], 'correct' => 1],
        ['question' => 'Which library is SciPy built on top of?', 'options' => ['Pandas', 'Matplotlib', 'NumPy', 'TensorFlow'], 'correct' => 2],
        ['question' => 'How do you import SciPy?', 'options' => ['import scipy', 'from scipy import *', 'import sci as sp', 'load scipy'], 'correct' => 0],
        ['question' => 'What command installs SciPy?', 'options' => ['pip install scipy', 'conda install sci', 'pip get scipy', 'install scipy'], 'correct' => 0],
        ['question' => 'Which module provides linear algebra functions?', 'options' => ['scipy.math', 'scipy.linalg', 'scipy.algebra', 'scipy.matrix'], 'correct' => 1],
        ['question' => 'Which module provides integration routines?', 'options' => ['scipy.calc', 'scipy.integrate', 'scipy.integral', 'scipy.math'], 'correct' => 1],
        ['question' => 'Which module handles signal processing?', 'options' => ['scipy.signals', 'scipy.signal', 'scipy.proc', 'scipy.fft'], 'correct' => 1],
        ['question' => 'Which module provides optimization algorithms?', 'options' => ['scipy.optimize', 'scipy.minimise', 'scipy.solver', 'scipy.fit'], 'correct' => 0],
        ['question' => 'Which module handles statistical functions?', 'options' => ['scipy.math', 'scipy.stats', 'scipy.stat', 'scipy.probability'], 'correct' => 1],
        ['question' => 'Which module provides spatial data structures?', 'options' => ['scipy.geo', 'scipy.space', 'scipy.spatial', 'scipy.geometry'], 'correct' => 2],
        ['question' => 'Which module handles sparse matrices?', 'options' => ['scipy.sparse', 'scipy.matrix', 'scipy.compress', 'scipy.csr'], 'correct' => 0],
        ['question' => 'Which module provides interpolation functions?', 'options' => ['scipy.interp', 'scipy.interpolate', 'scipy.approx', 'scipy.fit'], 'correct' => 1],
        ['question' => 'What does scipy.constants provide?', 'options' => ['Math constants only', 'Physical and mathematical constants', 'String constants', 'Configuration values'], 'correct' => 1],
        ['question' => 'What is the value of scipy.constants.pi?', 'options' => ['3.14', '3.14159265358979', 'Same as math.pi', 'Both B and C'], 'correct' => 3],
        ['question' => 'How do you import just the optimize module?', 'options' => ['import scipy.optimize', 'from scipy import optimize', 'Both A and B', 'import optimize from scipy'], 'correct' => 2],
        ['question' => 'What does scipy.special provide?', 'options' => ['Utility functions', 'Special mathematical functions', 'Custom algorithms', 'Special arrays'], 'correct' => 1],
        ['question' => 'Which function numerically integrates a callable?', 'options' => ['scipy.integrate.quad', 'scipy.integrate.sum', 'scipy.integrate.calc', 'scipy.integrate.run'], 'correct' => 0],
        ['question' => 'What is the primary data structure used by SciPy?', 'options' => ['Python list', 'Pandas DataFrame', 'NumPy ndarray', 'SciPy array'], 'correct' => 2],
        ['question' => 'Which function solves a system of linear equations?', 'options' => ['scipy.linalg.solve', 'scipy.linalg.answer', 'scipy.linalg.find', 'scipy.linalg.compute'], 'correct' => 0],
        ['question' => 'What does scipy.io provide?', 'options' => ['Input/output utilities', 'Image operations', 'Integer operations', 'Iterative optimizers'], 'correct' => 0],
        ['question' => 'Which function computes the Fast Fourier Transform?', 'options' => ['scipy.fft.fft', 'scipy.signal.fft', 'scipy.transform.fft', 'scipy.fft.compute'], 'correct' => 0],
        ['question' => 'What does the ndimage submodule handle?', 'options' => ['N-dimensional image processing', 'New data images', 'Node images', 'Numerical digit images'], 'correct' => 0],
        ['question' => 'Which function finds roots of an equation?', 'options' => ['scipy.optimize.root', 'scipy.math.root', 'scipy.solve.root', 'scipy.linalg.root'], 'correct' => 0],
        ['question' => 'What is scipy.constants.c?', 'options' => ['Speed of sound', 'Speed of light', 'Coulomb constant', 'Circumference constant'], 'correct' => 1],
        ['question' => 'Which module provides cluster analysis tools?', 'options' => ['scipy.cluster', 'scipy.group', 'scipy.kmeans', 'scipy.analysis'], 'correct' => 0],
        ['question' => 'What does scipy.linalg.inv() compute?', 'options' => ['Inverse of a matrix', 'Inverse of a scalar', 'Integral value', 'Index values'], 'correct' => 0],
    ]],
    ['label' => 'Beginner', 'questions' => [
        ['question' => 'What does scipy.integrate.quad() return?', 'options' => ['Only the integral value', 'Integral value and error estimate', 'An array', 'A plot'], 'correct' => 1],
        ['question' => 'What is the signature of scipy.optimize.minimize()?', 'options' => ['minimize(fun, x0)', 'minimize(x0, fun)', 'minimize(fun)', 'minimize(fun, bounds)'], 'correct' => 0],
        ['question' => 'Which method in scipy.optimize finds a scalar minimum on an interval?', 'options' => ['minimize_scalar', 'scalar_min', 'find_min', 'bound_min'], 'correct' => 0],
        ['question' => 'What does scipy.stats.norm represent?', 'options' => ['Normal distribution', 'Normalized array', 'Norm function', 'Numerical range'], 'correct' => 0],
        ['question' => 'How do you compute the PDF of a normal distribution at x=0?', 'options' => ['scipy.stats.norm.pdf(0)', 'scipy.stats.norm.cdf(0)', 'scipy.stats.norm.ppf(0)', 'scipy.stats.norm.rvs(0)'], 'correct' => 0],
        ['question' => 'What does .cdf() compute?', 'options' => ['Probability density function', 'Cumulative distribution function', 'Coefficient of determination', 'Conditional distribution function'], 'correct' => 1],
        ['question' => 'What does .ppf() compute?', 'options' => ['Probability density', 'Percent point function (inverse CDF)', 'Peak probability function', 'Partial probability factor'], 'correct' => 1],
        ['question' => 'What does scipy.linalg.det() compute?', 'options' => ['Determinant of a matrix', 'Detection function', 'Detailed output', 'Derivative'], 'correct' => 0],
        ['question' => 'What does scipy.linalg.eig() return?', 'options' => ['Eigenvalues only', 'Eigenvectors only', 'Eigenvalues and eigenvectors', 'Eigenvector matrix only'], 'correct' => 2],
        ['question' => 'Which function computes the dot product in scipy.linalg?', 'options' => ['linalg.dot', 'linalg.multiply', 'Use numpy.dot instead', 'linalg.inner'], 'correct' => 2],
        ['question' => 'What does scipy.interpolate.interp1d() create?', 'options' => ['1D interpolating function', '1D integration', 'Inverse data', 'Indexed data'], 'correct' => 0],
        ['question' => 'Which argument sets the interpolation kind in interp1d?', 'options' => ['method', 'kind', 'type', 'mode'], 'correct' => 1],
        ['question' => 'What interpolation kind uses cubic polynomials?', 'options' => ['cubic', 'spline3', 'poly', 'c3'], 'correct' => 0],
        ['question' => 'What does scipy.signal.convolve() do?', 'options' => ['Convolves two signals', 'Converts signals', 'Computes spectrum', 'Connects signals'], 'correct' => 0],
        ['question' => 'Which function designs a Butterworth filter?', 'options' => ['scipy.signal.butterworth', 'scipy.signal.butter', 'scipy.signal.bfilter', 'scipy.signal.bworth'], 'correct' => 1],
        ['question' => 'What does scipy.spatial.distance.euclidean() compute?', 'options' => ['Euclidean distance', 'Euclidean norm', 'Manhattan distance', 'Cosine similarity'], 'correct' => 0],
        ['question' => 'Which class builds a KD-tree for spatial lookup?', 'options' => ['scipy.spatial.Tree', 'scipy.spatial.KDTree', 'scipy.spatial.NNTree', 'scipy.spatial.SpaceTree'], 'correct' => 1],
        ['question' => 'What does scipy.stats.ttest_ind() perform?', 'options' => ['Paired t-test', 'Independent two-sample t-test', 'One-sample t-test', 'Chi-squared test'], 'correct' => 1],
        ['question' => 'What does scipy.stats.chisquare() test?', 'options' => ['Independence of variables', 'Goodness of fit', 'Normality', 'Variance'], 'correct' => 1],
        ['question' => 'Which function finds a zero of a scalar function?', 'options' => ['scipy.optimize.zero', 'scipy.optimize.brentq', 'scipy.optimize.bisect_zero', 'scipy.optimize.find_zero'], 'correct' => 1],
        ['question' => 'What does scipy.fft.ifft() compute?', 'options' => ['Inverse Fast Fourier Transform', 'Integer FFT', 'Image FFT', 'Indexed FFT'], 'correct' => 0],
        ['question' => 'Which function loads a MATLAB .mat file?', 'options' => ['scipy.io.loadmat', 'scipy.io.read_mat', 'scipy.io.open_mat', 'scipy.io.import_mat'], 'correct' => 0],
        ['question' => 'What sparse matrix format is CSR?', 'options' => ['Column Sparse Row', 'Compressed Sparse Row', 'Compact Sparse Row', 'Common Sparse Row'], 'correct' => 1],
        ['question' => 'How do you create a CSR sparse matrix?', 'options' => ['scipy.sparse.csr()', 'scipy.sparse.csr_matrix()', 'scipy.sparse.create_csr()', 'scipy.sparse.CSR()'], 'correct' => 1],
        ['question' => 'Which function performs curve fitting in SciPy?', 'options' => ['scipy.optimize.curve_fit', 'scipy.stats.curve_fit', 'scipy.fit.curve', 'scipy.interpolate.curve_fit'], 'correct' => 0],
        ['question' => 'What does scipy.ndimage.gaussian_filter() apply?', 'options' => ['Gaussian blur to an n-dimensional array', 'Gaussian noise', 'Gradient filter', 'Grid filter'], 'correct' => 0],
    ]],
    ['label' => 'Intermediate', 'questions' => [
        ['question' => 'What does scipy.integrate.dblquad() compute?', 'options' => ['Double integral', 'Double precision integral', 'Derivative of integral', 'Discrete integral'], 'correct' => 0],
        ['question' => 'What does scipy.integrate.odeint() solve?', 'options' => ['Ordinary differential equations', 'Partial differential equations', 'Optimal integrals', 'Ordered data integrals'], 'correct' => 0],
        ['question' => 'Which newer ODE solver replaces odeint for flexibility?', 'options' => ['solve_ode', 'solve_ivp', 'ode_solve', 'diff_solve'], 'correct' => 1],
        ['question' => 'What does the method parameter in solve_ivp specify?', 'options' => ['Integration method (e.g., RK45)', 'Method of problem statement', 'Memory method', 'Minimum error method'], 'correct' => 0],
        ['question' => 'What does scipy.optimize.linprog() solve?', 'options' => ['Linear programs (LP)', 'Linear regression', 'Linear interpolation', 'Linear ODEs'], 'correct' => 0],
        ['question' => 'What does scipy.linalg.svd() compute?', 'options' => ['Singular value decomposition', 'Sparse vector decomposition', 'Standard vector decomposition', 'Sorted values decomposition'], 'correct' => 0],
        ['question' => 'What does scipy.linalg.qr() compute?', 'options' => ['QR decomposition', 'Quadratic regression', 'Quick reduction', 'Quantile regression'], 'correct' => 0],
        ['question' => 'What does scipy.linalg.cholesky() compute?', 'options' => ['Cholesky decomposition', 'Chi-squared values', 'Column hierarchy', 'Correlation hierarchy'], 'correct' => 0],
        ['question' => 'Which function computes the pseudo-inverse of a matrix?', 'options' => ['scipy.linalg.pinv', 'scipy.linalg.inv_pseudo', 'scipy.linalg.pseudo', 'scipy.linalg.mp_inv'], 'correct' => 0],
        ['question' => 'What does scipy.stats.pearsonr() return?', 'options' => ['Pearson correlation coefficient and p-value', 'Only correlation coefficient', 'Spearman correlation', 'Regression coefficients'], 'correct' => 0],
        ['question' => 'What does scipy.stats.ks_2samp() test?', 'options' => ['Whether two samples come from the same distribution', 'Kolmogorov-Smirnov one-sample test', 'Kruskal-Wallis test', 'K-S normality test'], 'correct' => 0],
        ['question' => 'What is a p-value threshold commonly used for statistical significance?', 'options' => ['0.10', '0.05', '0.01', '0.001'], 'correct' => 1],
        ['question' => 'What does scipy.interpolate.CubicSpline() create?', 'options' => ['A piecewise cubic interpolant with smooth derivatives', 'A cubic equation solver', 'A cubic array', 'A 3D interpolator'], 'correct' => 0],
        ['question' => 'What does scipy.interpolate.RectBivariateSpline() handle?', 'options' => ['2D interpolation on a rectangular grid', '1D bivariate data', 'Rectangle geometry', 'Bivariate regression'], 'correct' => 0],
        ['question' => 'Which function computes the convex hull of a set of points?', 'options' => ['scipy.spatial.ConvexHull', 'scipy.spatial.convex_hull', 'scipy.spatial.CHull', 'scipy.spatial.hull'], 'correct' => 0],
        ['question' => 'What does scipy.spatial.Voronoi() compute?', 'options' => ['Voronoi diagram of points', 'Volume of region', 'Vectorized operations', 'Variance of points'], 'correct' => 0],
        ['question' => 'What does scipy.signal.find_peaks() return?', 'options' => ['Indices of peaks in a 1D array', 'Peak values', 'Peak frequencies', 'Peak widths only'], 'correct' => 0],
        ['question' => 'Which function applies a Savitzky-Golay filter?', 'options' => ['scipy.signal.savgol_filter', 'scipy.signal.sg_filter', 'scipy.signal.smooth', 'scipy.signal.golay'], 'correct' => 0],
        ['question' => 'What does scipy.fft.fftfreq() return?', 'options' => ['DFT sample frequencies', 'FFT values', 'Frequency counts', 'Frame frequencies'], 'correct' => 0],
        ['question' => 'What does scipy.fft.rfft() compute?', 'options' => ['FFT for real-valued input', 'Reverse FFT', 'Recursive FFT', 'Row-based FFT'], 'correct' => 0],
        ['question' => 'What does scipy.sparse.linalg.spsolve() do?', 'options' => ['Solves a sparse linear system', 'Splits a sparse matrix', 'Computes sparse eigenvalues', 'Sorts sparse data'], 'correct' => 0],
        ['question' => 'Which scipy.cluster module implements k-means?', 'options' => ['scipy.cluster.vq', 'scipy.cluster.kmeans', 'scipy.cluster.hierarchy', 'scipy.cluster.flat'], 'correct' => 0],
        ['question' => 'What does scipy.cluster.hierarchy.linkage() compute?', 'options' => ['Hierarchical clustering linkage matrix', 'Data links', 'Linear linkage', 'Label linkage'], 'correct' => 0],
        ['question' => 'What does scipy.stats.mannwhitneyu() perform?', 'options' => ['Mann-Whitney U test (nonparametric)', 'Paired t-test', 'ANOVA', 'Mann-Kendall trend test'], 'correct' => 0],
        ['question' => 'What does scipy.ndimage.label() do?', 'options' => ['Labels connected features in an array', 'Labels array indices', 'Assigns class labels', 'Labels frequency bands'], 'correct' => 0],
        ['question' => 'Which method argument in scipy.optimize.minimize uses gradient-based BFGS?', 'options' => ["method='BFGS'", "method='gradient'", "method='gradient_descent'", "method='GD'"], 'correct' => 0],
    ]],
    ['label' => 'Advanced', 'questions' => [
        ['question' => 'What does scipy.linalg.expm() compute?', 'options' => ['Matrix exponential', 'Element-wise exponential', 'Exponential regression', 'Expanded matrix'], 'correct' => 0],
        ['question' => 'What is the difference between scipy.linalg.eig() and eigh()?', 'options' => ['eigh() is for real symmetric/Hermitian matrices', 'eig() is faster', 'eigh() returns only real eigenvalues always', 'eigh() works on non-square matrices'], 'correct' => 0],
        ['question' => 'What does scipy.linalg.lu() compute?', 'options' => ['LU decomposition', 'Lower-upper sort', 'Logical union', 'Linear update'], 'correct' => 0],
        ['question' => 'What does the full_matrices argument in svd() control?', 'options' => ['Whether to return full or economy-size matrices', 'Floating-point precision', 'Full data output', 'Full index mode'], 'correct' => 0],
        ['question' => 'What does scipy.optimize.differential_evolution() implement?', 'options' => ['Differential evolution global optimizer', 'Differential equation solver', 'Derivative-based evolution', 'Discrete optimization'], 'correct' => 0],
        ['question' => 'What does scipy.optimize.dual_annealing() implement?', 'options' => ['Dual annealing global optimization', 'Dual gradient descent', 'Two-phase annealing for discrete problems', 'Deterministic annealing'], 'correct' => 0],
        ['question' => 'What does scipy.optimize.shgo() stand for?', 'options' => ['Simplicial Homology Global Optimization', 'Stochastic Hill-climbing Global Optimization', 'Sequential Hessian Global Optimization', 'Sparse Heuristic Global Optimization'], 'correct' => 0],
        ['question' => 'What does scipy.stats.gaussian_kde() estimate?', 'options' => ['Kernel density estimate of a dataset', 'Gaussian mixture model', 'Gaussian regression', 'Kernel regression'], 'correct' => 0],
        ['question' => 'What does scipy.stats.boxcox() do?', 'options' => ['Applies Box-Cox power transformation', 'Creates box plots', 'Computes box statistics', 'Applies Cox regression'], 'correct' => 0],
        ['question' => 'What does scipy.stats.anderson() test for?', 'options' => ['Anderson-Darling normality test', 'Autocorrelation', 'Distribution independence', 'Anderson-Darling uniformity'], 'correct' => 0],
        ['question' => 'What does scipy.signal.welch() estimate?', 'options' => ["Power spectral density using Welch's method", 'Waveform length', 'Signal entropy', 'Windowed energy'], 'correct' => 0],
        ['question' => 'What does scipy.signal.spectrogram() compute?', 'options' => ['Time-frequency spectrogram', 'Spectral gradient', 'Speech recognition output', 'Spectral components'], 'correct' => 0],
        ['question' => 'What does scipy.signal.lfilter() do?', 'options' => ['Applies a digital filter to a signal', 'Finds local filters', 'Limits filter size', 'Linear fitting'], 'correct' => 0],
        ['question' => 'What is the difference between lfilter and sosfilt?', 'options' => ['sosfilt uses second-order sections for numerical stability', 'lfilter is more accurate', 'sosfilt is slower', 'lfilter uses second-order sections'], 'correct' => 0],
        ['question' => 'What does scipy.interpolate.RegularGridInterpolator() support?', 'options' => ['Interpolation on regular N-dimensional grids', 'Irregular grid interpolation', 'Regression on grids', 'Recursive grid interpolation'], 'correct' => 0],
        ['question' => 'What does scipy.interpolate.BSpline() represent?', 'options' => ['A B-spline basis function', 'Binary spline', 'Bounded spline', 'Bivariate spline'], 'correct' => 0],
        ['question' => 'What does scipy.sparse.linalg.eigs() compute?', 'options' => ['Eigenvalues of large sparse matrices', 'Exact eigenvalues', 'Edge indices', 'Even index sampling'], 'correct' => 0],
        ['question' => 'What does scipy.sparse.linalg.svds() compute?', 'options' => ['Truncated SVD of sparse matrices', 'Standard sparse decomposition', 'Sparse vector decomposition', 'Sorted value distribution'], 'correct' => 0],
        ['question' => 'What does scipy.spatial.cKDTree offer over KDTree?', 'options' => ['Faster C-based implementation', 'More query methods', 'Higher accuracy', 'Complex number support'], 'correct' => 0],
        ['question' => 'What does scipy.stats.multivariate_normal.pdf() compute?', 'options' => ['PDF of multivariate normal distribution', 'Multiple variable PDF', 'Mean vector estimation', 'Covariance matrix PDF'], 'correct' => 0],
        ['question' => 'What does scipy.integrate.solve_bvp() solve?', 'options' => ['Boundary value problems', 'Bivariate problems', 'Bounded variable problems', 'Binary value problems'], 'correct' => 0],
        ['question' => 'What method does solve_ivp use by default?', 'options' => ['RK45', 'Euler', 'Adams', 'BDF'], 'correct' => 0],
        ['question' => 'What does scipy.optimize.minimize with method=\'trust-constr\' support?', 'options' => ['Constrained optimization with equality and inequality constraints', 'Trust region unconstrained optimization', 'Constrained linear programming', 'Truncated conjugate gradient'], 'correct' => 0],
        ['question' => 'What does scipy.signal.stft() compute?', 'options' => ['Short-Time Fourier Transform', 'Stationary Transform', 'Signal Time Function Transform', 'Statistical Fourier Transform'], 'correct' => 0],
        ['question' => 'What does scipy.ndimage.binary_dilation() do?', 'options' => ['Dilates a binary image', 'Reduces binary noise', 'Divides binary arrays', 'Detects binary edges'], 'correct' => 0],
    ]],
    ['label' => 'Expert', 'questions' => [
        ['question' => 'What does scipy.linalg.solve_triangular() do versus linalg.solve()?', 'options' => ['Exploits triangular structure for better performance', 'Solves non-square systems', 'Computes tridiagonal systems', 'Solves trilinear systems'], 'correct' => 0],
        ['question' => 'What does scipy.linalg.lstsq() compute?', 'options' => ['Least-squares solution to a linear matrix equation', 'Linear step-size query', 'Last-sample statistics', 'Largest eigenvalue'], 'correct' => 0],
        ['question' => 'In scipy.linalg.svd, what is the relationship between singular values and matrix rank?', 'options' => ['Number of non-zero singular values equals matrix rank', 'Singular values equal rank directly', 'Singular values are always equal to rank', 'Rank equals max singular value'], 'correct' => 0],
        ['question' => 'What does scipy.optimize.NonlinearConstraint() define?', 'options' => ['A nonlinear constraint for constrained optimization', 'A nonlinear solver', 'A nonlinear regression model', 'A neural network layer'], 'correct' => 0],
        ['question' => 'What distinguishes scipy.optimize.basinhopping() from simulated annealing?', 'options' => ['Uses local minimization combined with random jumps', 'Uses temperature schedule', 'Only for convex problems', 'Uses basin splitting'], 'correct' => 0],
        ['question' => 'What is the Jacobian used for in scipy.optimize.minimize?', 'options' => ['Provides gradient information to speed up gradient-based methods', 'Computes Jacobi polynomials', 'Defines Jacobian constraints', 'Adjusts learning rate'], 'correct' => 0],
        ['question' => 'What does scipy.linalg.block_diag() construct?', 'options' => ['A block diagonal matrix from smaller matrices', 'A diagonal block matrix', 'Block sparse matrix', 'Blocked determinant matrix'], 'correct' => 0],
        ['question' => 'What does scipy.stats.rv_continuous allow you to do?', 'options' => ['Define custom continuous probability distributions', 'Compute continuous random variables', 'Compute continuous variance', 'Define continuous regression'], 'correct' => 0],
        ['question' => 'What does scipy.stats.entropy() compute?', 'options' => ['Shannon entropy (or KL divergence if two distributions given)', 'Information entropy only', 'Spectral entropy', 'Boltzmann entropy'], 'correct' => 0],
        ['question' => 'What does scipy.linalg.kron() compute?', 'options' => ['Kronecker product of two matrices', 'Kernel function', 'Kronecker delta array', 'Kernel regression output'], 'correct' => 0],
        ['question' => 'What does scipy.sparse.linalg.LinearOperator allow?', 'options' => ['Defining matrix-vector products without storing the full matrix', 'Creating linear regression operators', 'Linearizing sparse data', 'Defining linear ODE operators'], 'correct' => 0],
        ['question' => 'What does scipy.signal.hilbert() compute?', 'options' => ['Analytic signal via Hilbert transform', 'Hilbert space projection', 'High-pass filter', 'Harmonic interpolation'], 'correct' => 0],
        ['question' => 'What does the density argument in scipy.signal.periodogram() control?', 'options' => ["Whether to return power spectral density or power spectrum ('density' vs 'spectrum')", 'Sampling density', 'Signal density', 'Frame density'], 'correct' => 0],
        ['question' => 'What does scipy.fft.next_fast_len() do?', 'options' => ['Returns the optimal FFT size for given input length', 'Computes the next power of 2', 'Finds the next prime', 'Calculates next sampling length'], 'correct' => 0],
        ['question' => 'What does scipy.interpolate.make_interp_spline() return?', 'options' => ['A BSpline object fitting given data', 'An interpolated array', 'A spline degree selector', 'A make-shift interpolator'], 'correct' => 0],
        ['question' => 'What does scipy.integrate.quad_vec() do?', 'options' => ['Integrates vector-valued functions efficiently', 'Computes quadrature vectors', 'Quantizes vector data', 'Integrates discrete vectors'], 'correct' => 0],
        ['question' => 'What does scipy.stats.wasserstein_distance() measure?', 'options' => ["Earth mover's distance between two 1D distributions", 'Wasserstein norm', 'Water flow distance', 'Weighted sampling distance'], 'correct' => 0],
        ['question' => 'What does the workers argument in scipy.fft.fft() enable?', 'options' => ['Parallel computation using multiple CPU workers', 'Worker thread limits', 'Work distribution over GPUs', 'Worker memory allocation'], 'correct' => 0],
        ['question' => 'What does scipy.linalg.solve with assume_a=\'pos\' do?', 'options' => ['Uses Cholesky decomposition for positive definite matrices', 'Assumes positive solutions', 'Uses positive-definite Gauss elimination', 'Checks positivity before solving'], 'correct' => 0],
        ['question' => 'What does scipy.ndimage.distance_transform_edt() compute?', 'options' => ['Euclidean distance transform of a binary image', 'Edge detection transform', 'Euclidean data transform', 'Discrete edge transform'], 'correct' => 0],
        ['question' => 'What does scipy.optimize.milp() solve?', 'options' => ['Mixed-integer linear programs', 'Minimum integer linear programs', 'Multi-index linear programs', 'Minimum iteration linear programs'], 'correct' => 0],
        ['question' => 'What is the advantage of using scipy.sparse.csc_matrix over csr_matrix for column slicing?', 'options' => ['CSC (Compressed Sparse Column) is optimized for column operations', 'CSC uses less memory', 'CSC is faster for row operations', 'CSC supports complex numbers only'], 'correct' => 0],
        ['question' => 'What does scipy.stats.permutation_test() compute?', 'options' => ['A permutation-based hypothesis test p-value', 'Permutation importance', 'Permutation of test statistics', 'Random permutation sampling'], 'correct' => 0],
        ['question' => 'What does scipy.integrate.fixed_quad() use?', 'options' => ['Fixed-order Gaussian quadrature', 'Fixed-point iteration', 'Fixed-step Runge-Kutta', 'Fixed-interval Simpson rule'], 'correct' => 0],
        ['question' => 'What does scipy.linalg.funm() compute?', 'options' => ['Matrix function evaluation for general functions', 'Functional matrix inversion', 'Fundamental matrix', 'Function minimization'], 'correct' => 0],
        ['question' => 'What does scipy.sparse.linalg.lobpcg() compute?', 'options' => ['Locally optimal block preconditioned conjugate gradient for eigenvalues', 'Local basis partial conjugate gradient', 'Large-order block PCG', 'Localized optimization by PCG'], 'correct' => 0],
    ]],
];
require_once __DIR__ . '/quiz-engine.php';
