<?php
$page_title = 'SQL Quiz – 100 Levels – CodeFoundry';
$active_page = 'training';
$quiz_title  = 'SQL';
$quiz_slug   = 'sql';
$quiz_tiers  = [
    ['label' => 'Introduction', 'questions' => [
        ['question' => 'What does SQL stand for?', 'options' => ['Structured Query Language', 'Simple Question Language', 'Sequential Query Language', 'System Query Language'], 'correct' => 0],
        ['question' => 'Which SQL statement is used to retrieve data from a database?', 'options' => ['SELECT', 'GET', 'RETRIEVE', 'FETCH'], 'correct' => 0],
        ['question' => 'Which clause is used to filter rows in a SELECT statement?', 'options' => ['FILTER', 'WHERE', 'HAVING', 'IF'], 'correct' => 1],
        ['question' => 'Which keyword is used to sort the result set?', 'options' => ['SORT', 'ORDER BY', 'SORT BY', 'ARRANGE'], 'correct' => 1],
        ['question' => 'Which SQL statement is used to insert new data into a database?', 'options' => ['ADD', 'INSERT INTO', 'CREATE', 'PUT'], 'correct' => 1],
        ['question' => 'Which SQL statement is used to update existing data?', 'options' => ['MODIFY', 'CHANGE', 'UPDATE', 'ALTER'], 'correct' => 2],
        ['question' => 'Which SQL statement is used to delete data from a database?', 'options' => ['REMOVE', 'DELETE', 'DROP', 'CLEAR'], 'correct' => 1],
        ['question' => 'Which SQL statement is used to create a new table?', 'options' => ['CREATE TABLE', 'NEW TABLE', 'MAKE TABLE', 'BUILD TABLE'], 'correct' => 0],
        ['question' => 'Which SQL statement is used to remove a table?', 'options' => ['REMOVE TABLE', 'DELETE TABLE', 'DROP TABLE', 'CLEAR TABLE'], 'correct' => 2],
        ['question' => 'Which data type is used to store whole numbers?', 'options' => ['INT', 'NUMBER', 'DECIMAL', 'FLOAT'], 'correct' => 0],
        ['question' => 'Which data type is used to store text of variable length?', 'options' => ['TEXT', 'VARCHAR', 'STRING', 'CHAR'], 'correct' => 1],
        ['question' => 'Which data type is used to store dates?', 'options' => ['DATETIME', 'DATE', 'TIME', 'CALENDAR'], 'correct' => 1],
        ['question' => 'Which data type is used to store true/false values?', 'options' => ['BIT', 'BOOLEAN', 'BINARY', 'BOOL'], 'correct' => 1],
        ['question' => 'What does NULL represent in SQL?', 'options' => ['Zero', 'Empty string', 'Missing or unknown value', 'False'], 'correct' => 2],
        ['question' => 'What is a primary key?', 'options' => ['The first column in a table', 'A unique identifier for each record', 'The most important data', 'A required field'], 'correct' => 1],
        ['question' => 'What is a foreign key?', 'options' => ['A key from another database', 'A field that references a primary key in another table', 'An external identifier', 'A backup key'], 'correct' => 1],
        ['question' => 'What does SELECT * do?', 'options' => ['Selects all databases', 'Selects all tables', 'Selects all columns', 'Selects all rows'], 'correct' => 2],
        ['question' => 'Which keyword is used to create a column alias?', 'options' => ['AS', 'ALIAS', 'NAME', 'RENAME'], 'correct' => 0],
        ['question' => 'Which keyword limits the number of rows returned?', 'options' => ['LIMIT', 'TOP', 'MAX', 'Both LIMIT and TOP'], 'correct' => 3],
        ['question' => 'Which symbol starts a single-line comment in SQL?', 'options' => ['//', '#', '--', '/*'], 'correct' => 2],
        ['question' => 'Which symbols are used for multi-line comments?', 'options' => ['/* */', '// //', '<!-- -->', '{ }'], 'correct' => 0],
        ['question' => 'Which operator checks for equality?', 'options' => ['==', '=', 'EQUALS', 'IS'], 'correct' => 1],
        ['question' => 'Which operator means "not equal to"?', 'options' => ['!', '<>', '!=', 'Both != and <>'], 'correct' => 3],
        ['question' => 'Which logical operator returns TRUE if both conditions are TRUE?', 'options' => ['AND', 'OR', 'BOTH', 'ALSO'], 'correct' => 0],
        ['question' => 'Which logical operator returns TRUE if at least one condition is TRUE?', 'options' => ['AND', 'OR', 'EITHER', 'ANY'], 'correct' => 1],
        ['question' => 'Which logical operator reverses the result of a condition?', 'options' => ['REVERSE', 'NOT', 'OPPOSITE', 'NEGATE'], 'correct' => 1],
        ['question' => 'Which operator checks if a value is within a range?', 'options' => ['IN RANGE', 'BETWEEN', 'WITHIN', 'RANGE'], 'correct' => 1],
        ['question' => 'Which operator checks if a value matches any value in a list?', 'options' => ['IN', 'ANY', 'MATCHES', 'CONTAINS'], 'correct' => 0],
        ['question' => 'Which operator is used for pattern matching?', 'options' => ['MATCH', 'LIKE', 'PATTERN', 'REGEX'], 'correct' => 1],
        ['question' => 'What does the % wildcard represent in LIKE patterns?', 'options' => ['One character', 'Zero or more characters', 'Any digit', 'Any letter'], 'correct' => 1],
        ['question' => 'Which keyword removes duplicate rows from the result set?', 'options' => ['UNIQUE', 'DISTINCT', 'DIFFERENT', 'NODUPE'], 'correct' => 1],
        ['question' => 'Which aggregate function counts the number of rows?', 'options' => ['COUNT(*)', 'ROWS()', 'NUMBER()', 'TOTAL()'], 'correct' => 0],
        ['question' => 'Which clause specifies the table to query?', 'options' => ['TABLE', 'FROM', 'IN', 'SOURCE'], 'correct' => 1],
    ]],
    ['label' => 'Beginner', 'questions' => [
        ['question' => 'Which clause groups rows that have the same values?', 'options' => ['GROUP BY', 'COLLECT', 'GATHER', 'BUNCH'], 'correct' => 0],
        ['question' => 'Which clause filters groups (used with GROUP BY)?', 'options' => ['WHERE', 'HAVING', 'FILTER', 'GROUP WHERE'], 'correct' => 1],
        ['question' => 'Which function returns the sum of a numeric column?', 'options' => ['TOTAL()', 'SUM()', 'ADD()', 'PLUS()'], 'correct' => 1],
        ['question' => 'Which function returns the average value of a numeric column?', 'options' => ['AVG()', 'AVERAGE()', 'MEAN()', 'MEDIAN()'], 'correct' => 0],
        ['question' => 'Which function returns the smallest value?', 'options' => ['LEAST()', 'MIN()', 'SMALL()', 'LOWEST()'], 'correct' => 1],
        ['question' => 'Which function returns the largest value?', 'options' => ['GREATEST()', 'MAX()', 'LARGE()', 'HIGHEST()'], 'correct' => 1],
        ['question' => 'Which JOIN returns only matching rows from both tables?', 'options' => ['INNER JOIN', 'OUTER JOIN', 'CROSS JOIN', 'FULL JOIN'], 'correct' => 0],
        ['question' => 'Which JOIN returns all rows from the left table and matching rows from the right?', 'options' => ['LEFT JOIN', 'RIGHT JOIN', 'FULL JOIN', 'OUTER JOIN'], 'correct' => 0],
        ['question' => 'Which JOIN returns all rows from the right table and matching rows from the left?', 'options' => ['LEFT JOIN', 'RIGHT JOIN', 'FULL JOIN', 'INNER JOIN'], 'correct' => 1],
        ['question' => 'Which JOIN returns all rows when there is a match in either table?', 'options' => ['INNER JOIN', 'LEFT JOIN', 'FULL OUTER JOIN', 'CROSS JOIN'], 'correct' => 2],
        ['question' => 'Which JOIN returns the Cartesian product of both tables?', 'options' => ['INNER JOIN', 'OUTER JOIN', 'CROSS JOIN', 'FULL JOIN'], 'correct' => 2],
        ['question' => 'What is the purpose of table aliases?', 'options' => ['To rename tables permanently', 'To provide temporary names for easier reference', 'To hide table names', 'To create backups'], 'correct' => 1],
        ['question' => 'Where can subqueries be used?', 'options' => ['Only in WHERE clause', 'Only in FROM clause', 'In WHERE, FROM, SELECT, and HAVING clauses', 'Only in SELECT clause'], 'correct' => 2],
        ['question' => 'What does UNION do?', 'options' => ['Joins tables horizontally', 'Combines result sets vertically and removes duplicates', 'Combines result sets with duplicates', 'Merges tables'], 'correct' => 1],
        ['question' => 'What is the difference between UNION and UNION ALL?', 'options' => ['No difference', 'UNION ALL keeps duplicates', 'UNION ALL is faster but same result', 'UNION ALL sorts results'], 'correct' => 1],
        ['question' => 'What does COALESCE() do?', 'options' => ['Combines strings', 'Returns the first non-NULL value', 'Merges columns', 'Removes NULL values'], 'correct' => 1],
        ['question' => 'What does NULLIF(a, b) return?', 'options' => ['NULL if a equals b, else a', 'NULL if a or b is NULL', 'a if b is NULL', 'b if a is NULL'], 'correct' => 0],
        ['question' => 'Which operator checks if a value is NULL?', 'options' => ['= NULL', 'IS NULL', 'NULL', 'EQUALS NULL'], 'correct' => 1],
        ['question' => 'Which operator checks if a value is not NULL?', 'options' => ['!= NULL', '<> NULL', 'IS NOT NULL', 'NOT NULL'], 'correct' => 2],
        ['question' => 'What does CASE WHEN THEN ELSE END do?', 'options' => ['Creates conditional logic', 'Defines table structure', 'Handles errors', 'Converts data types'], 'correct' => 0],
        ['question' => 'What does CAST() do?', 'options' => ['Creates a copy', 'Converts a value to a different data type', 'Validates data', 'Formats output'], 'correct' => 1],
        ['question' => 'Which function converts text to uppercase?', 'options' => ['UPPER()', 'UCASE()', 'CAPS()', 'Both UPPER() and UCASE()'], 'correct' => 3],
        ['question' => 'Which function converts text to lowercase?', 'options' => ['LOWER()', 'LCASE()', 'SMALL()', 'Both LOWER() and LCASE()'], 'correct' => 3],
        ['question' => 'Which function removes leading and trailing spaces?', 'options' => ['STRIP()', 'TRIM()', 'CLEAN()', 'REMOVE()'], 'correct' => 1],
        ['question' => 'Which function returns the length of a string?', 'options' => ['LENGTH()', 'LEN()', 'SIZE()', 'Both LENGTH() and LEN()'], 'correct' => 3],
        ['question' => 'Which function extracts a substring?', 'options' => ['SUBSTR()', 'SUBSTRING()', 'EXTRACT()', 'Both SUBSTR() and SUBSTRING()'], 'correct' => 3],
        ['question' => 'Which function concatenates strings?', 'options' => ['JOIN()', 'CONCAT()', 'MERGE()', 'APPEND()'], 'correct' => 1],
        ['question' => 'Which function returns the current date and time in MySQL?', 'options' => ['CURRENT()', 'NOW()', 'TODAY()', 'DATETIME()'], 'correct' => 1],
        ['question' => 'Which function returns the current date and time in SQL Server?', 'options' => ['NOW()', 'GETDATE()', 'CURRENT()', 'DATETIME()'], 'correct' => 1],
        ['question' => 'Can you use INSERT with a SELECT statement?', 'options' => ['No', 'Yes, to copy data from one table to another', 'Only with temporary tables', 'Only with views'], 'correct' => 1],
        ['question' => 'Can you use UPDATE with a JOIN?', 'options' => ['No', 'Yes, in some databases', 'Only with INNER JOIN', 'Only with LEFT JOIN'], 'correct' => 1],
        ['question' => 'Can you use DELETE with a JOIN?', 'options' => ['No', 'Yes, in some databases', 'Only with subqueries', 'Only with WHERE'], 'correct' => 1],
        ['question' => 'What is an index?', 'options' => ['A table of contents for a database', 'A structure that improves query performance', 'A backup of data', 'A type of constraint'], 'correct' => 1],
        ['question' => 'What does the UNIQUE constraint do?', 'options' => ['Creates an index', 'Ensures all values in a column are different', 'Prevents NULL values', 'Makes a column required'], 'correct' => 1],
        ['question' => 'What does the NOT NULL constraint do?', 'options' => ['Removes NULL values', 'Prevents NULL values in a column', 'Converts NULL to zero', 'Replaces NULL with default'], 'correct' => 1],
        ['question' => 'What does the DEFAULT constraint do?', 'options' => ['Prevents NULL values', 'Sets a default value for a column', 'Validates data', 'Creates an index'], 'correct' => 1],
        ['question' => 'What does the CHECK constraint do?', 'options' => ['Validates foreign keys', 'Ensures values meet a condition', 'Checks for duplicates', 'Verifies data types'], 'correct' => 1],
    ]],
    ['label' => 'Intermediate', 'questions' => [
        ['question' => 'What does ROW_NUMBER() do?', 'options' => ['Counts rows', 'Assigns a unique sequential number to each row', 'Numbers groups', 'Counts duplicates'], 'correct' => 1],
        ['question' => 'What is the difference between RANK() and DENSE_RANK()?', 'options' => ['No difference', 'DENSE_RANK() has no gaps in ranking', 'RANK() is faster', 'DENSE_RANK() counts from 0'], 'correct' => 1],
        ['question' => 'What does NTILE(n) do?', 'options' => ['Returns top n rows', 'Divides rows into n groups', 'Skips n rows', 'Ranks in groups of n'], 'correct' => 1],
        ['question' => 'What does LAG() do?', 'options' => ['Gets the next row value', 'Gets the previous row value', 'Delays execution', 'Finds slowest query'], 'correct' => 1],
        ['question' => 'What does LEAD() do?', 'options' => ['Gets the previous row value', 'Gets the next row value', 'Advances execution', 'Finds fastest query'], 'correct' => 1],
        ['question' => 'What does FIRST_VALUE() return?', 'options' => ['The minimum value', 'The first value in a window frame', 'The first row in the table', 'The primary key'], 'correct' => 1],
        ['question' => 'What does LAST_VALUE() return?', 'options' => ['The maximum value', 'The last value in a window frame', 'The last row in the table', 'The most recent insert'], 'correct' => 1],
        ['question' => 'What does PARTITION BY do in window functions?', 'options' => ['Splits tables', 'Divides the result set into partitions', 'Creates table partitions', 'Separates databases'], 'correct' => 1],
        ['question' => 'What is a CTE (Common Table Expression)?', 'options' => ['A temporary table', 'A named temporary result set defined with WITH', 'A view', 'A stored procedure'], 'correct' => 1],
        ['question' => 'What makes a CTE recursive?', 'options' => ['Using RECURSIVE keyword', 'Referencing itself in its definition', 'Having multiple WITH clauses', 'Using GROUP BY'], 'correct' => 1],
        ['question' => 'What does EXPLAIN do?', 'options' => ['Describes table structure', 'Shows query execution plan', 'Documents code', 'Validates syntax'], 'correct' => 1],
        ['question' => 'What is EXPLAIN ANALYZE?', 'options' => ['Same as EXPLAIN', 'Executes the query and shows actual performance', 'Validates the query', 'Optimizes the query'], 'correct' => 1],
        ['question' => 'What is a covering index?', 'options' => ['An index on all columns', 'An index that contains all columns needed for a query', 'A full-text index', 'A unique index'], 'correct' => 1],
        ['question' => 'What is a composite index?', 'options' => ['An index on multiple columns', 'An index with compression', 'A combined unique and non-unique index', 'An index on complex data types'], 'correct' => 0],
        ['question' => 'What does ON DELETE CASCADE do?', 'options' => ['Deletes all records', 'Automatically deletes child records when parent is deleted', 'Prevents deletion', 'Archives deleted data'], 'correct' => 1],
        ['question' => 'What does ON UPDATE CASCADE do?', 'options' => ['Updates all records', 'Automatically updates child records when parent is updated', 'Prevents updates', 'Logs updates'], 'correct' => 1],
        ['question' => 'What is a view?', 'options' => ['A copy of a table', 'A virtual table based on a query', 'A table snapshot', 'A cached result'], 'correct' => 1],
        ['question' => 'Are all views updatable?', 'options' => ['Yes', 'No, depends on the view definition', 'Only simple views', 'Only with triggers'], 'correct' => 1],
        ['question' => 'What is a stored procedure?', 'options' => ['A saved query', 'A set of SQL statements stored and executed on the server', 'A function', 'A trigger'], 'correct' => 1],
        ['question' => 'What is a trigger?', 'options' => ['A scheduled task', 'Code that executes automatically in response to events', 'A stored procedure', 'A constraint'], 'correct' => 1],
        ['question' => 'What does BEGIN TRANSACTION do?', 'options' => ['Starts the database', 'Marks the start of a transaction', 'Begins a procedure', 'Initiates a connection'], 'correct' => 1],
        ['question' => 'What does COMMIT do?', 'options' => ['Saves changes permanently', 'Undoes changes', 'Closes connection', 'Validates data'], 'correct' => 0],
        ['question' => 'What does ROLLBACK do?', 'options' => ['Saves changes', 'Undoes changes since BEGIN TRANSACTION', 'Restores from backup', 'Returns to previous version'], 'correct' => 1],
        ['question' => 'Which isolation level allows dirty reads?', 'options' => ['READ COMMITTED', 'READ UNCOMMITTED', 'REPEATABLE READ', 'SERIALIZABLE'], 'correct' => 1],
        ['question' => 'Which isolation level prevents dirty reads but allows non-repeatable reads?', 'options' => ['READ UNCOMMITTED', 'READ COMMITTED', 'REPEATABLE READ', 'SERIALIZABLE'], 'correct' => 1],
        ['question' => 'Which isolation level prevents dirty and non-repeatable reads but allows phantom reads?', 'options' => ['READ UNCOMMITTED', 'READ COMMITTED', 'REPEATABLE READ', 'SERIALIZABLE'], 'correct' => 2],
        ['question' => 'Which isolation level is the most strict?', 'options' => ['READ UNCOMMITTED', 'READ COMMITTED', 'REPEATABLE READ', 'SERIALIZABLE'], 'correct' => 3],
        ['question' => 'What is a SAVEPOINT?', 'options' => ['A backup', 'A point within a transaction to rollback to', 'A checkpoint', 'A commit point'], 'correct' => 1],
        ['question' => 'What is a MERGE statement used for?', 'options' => ['Combining tables', 'INSERT, UPDATE, or DELETE based on conditions (UPSERT)', 'Joining data', 'Merging databases'], 'correct' => 1],
        ['question' => 'What does PIVOT do?', 'options' => ['Rotates a table', 'Converts rows to columns', 'Sorts data', 'Filters data'], 'correct' => 1],
        ['question' => 'What does UNPIVOT do?', 'options' => ['Reverses PIVOT', 'Converts columns to rows', 'Normalizes data', 'Both converts columns to rows and reverses PIVOT'], 'correct' => 3],
        ['question' => 'Which databases support JSON functions natively?', 'options' => ['Only MongoDB', 'MySQL and PostgreSQL', 'None', 'All databases'], 'correct' => 1],
        ['question' => 'What is full-text search?', 'options' => ['Searching all tables', 'Searching text content using specialized indexing', 'Using LIKE operator', 'Regular expression search'], 'correct' => 1],
        ['question' => 'What is the main advantage of CTEs over subqueries?', 'options' => ['Faster execution', 'Better readability and reusability', 'Less memory usage', 'More features'], 'correct' => 1],
        ['question' => 'When should you use a temp table instead of a CTE?', 'options' => ['Always', 'When you need to reference the result multiple times', 'Never', 'For simple queries'], 'correct' => 1],
    ]],
    ['label' => 'Advanced', 'questions' => [
        ['question' => 'What is the primary goal of query optimization?', 'options' => ['Reduce code size', 'Minimize execution time and resource usage', 'Simplify queries', 'Reduce storage'], 'correct' => 1],
        ['question' => 'What is a B-tree index best suited for?', 'options' => ['Full-text search', 'Range queries and equality comparisons', 'Spatial data', 'JSON data'], 'correct' => 1],
        ['question' => 'What is a hash index best suited for?', 'options' => ['Range queries', 'Equality comparisons only', 'Sorting', 'Full-text search'], 'correct' => 1],
        ['question' => 'What is a GiST index used for in PostgreSQL?', 'options' => ['Integers only', 'General-purpose indexing including geometric and full-text', 'Primary keys', 'Foreign keys'], 'correct' => 1],
        ['question' => 'What is a GIN index used for in PostgreSQL?', 'options' => ['Simple data types', 'Composite values like arrays and JSONB', 'Dates', 'Numbers'], 'correct' => 1],
        ['question' => 'What is index selectivity?', 'options' => ['Number of indexes', 'The ratio of distinct values to total rows', 'Index size', 'Index type'], 'correct' => 1],
        ['question' => 'Why are statistics important for query optimization?', 'options' => ['They track usage', 'They help the optimizer estimate query costs', 'They validate data', 'They enforce constraints'], 'correct' => 1],
        ['question' => 'What is cardinality in database terms?', 'options' => ['Table size', 'Number of unique values in a column', 'Number of columns', 'Number of indexes'], 'correct' => 1],
        ['question' => 'What are query planner hints?', 'options' => ['Suggestions for developers', 'Directives to influence query execution plans', 'Comments in queries', 'Error messages'], 'correct' => 1],
        ['question' => 'What is a materialized view?', 'options' => ['A regular view', 'A view with stored, pre-computed results', 'A temporary view', 'An indexed view'], 'correct' => 1],
        ['question' => 'What is table partitioning?', 'options' => ['Splitting a table across databases', 'Dividing a table into smaller, manageable pieces', 'Creating table copies', 'Archiving old data'], 'correct' => 1],
        ['question' => 'What is range partitioning?', 'options' => ['Random distribution', 'Partitioning based on value ranges', 'Partitioning by hash', 'Partitioning by list'], 'correct' => 1],
        ['question' => 'What is list partitioning?', 'options' => ['Partitioning by range', 'Partitioning by specific values', 'Partitioning by hash', 'Alphabetical partitioning'], 'correct' => 1],
        ['question' => 'What is hash partitioning?', 'options' => ['Partitioning by range', 'Partitioning using a hash function', 'Partitioning by list', 'Random partitioning'], 'correct' => 1],
        ['question' => 'What is table inheritance in PostgreSQL?', 'options' => ['Copying tables', 'Creating child tables that inherit columns from parent tables', 'Table relationships', 'Foreign keys'], 'correct' => 1],
        ['question' => 'What is a LATERAL join?', 'options' => ['A horizontal join', 'A join where the right side can reference the left side', 'A side join', 'A perpendicular join'], 'correct' => 1],
        ['question' => 'What does STRING_AGG() do in PostgreSQL?', 'options' => ['Counts strings', 'Concatenates values from multiple rows into a single string', 'Aggregates numbers', 'Groups strings'], 'correct' => 1],
        ['question' => 'What is the MySQL equivalent of STRING_AGG()?', 'options' => ['CONCAT()', 'GROUP_CONCAT()', 'STRING_JOIN()', 'AGGREGATE()'], 'correct' => 1],
        ['question' => 'What is a window frame?', 'options' => ['A time window', 'The subset of rows used in window function calculations', 'A partition', 'A view'], 'correct' => 1],
        ['question' => 'What does ROWS BETWEEN specify?', 'options' => ['Row count', 'Physical rows in the window frame', 'Logical range', 'Partition boundaries'], 'correct' => 1],
        ['question' => 'What does RANGE BETWEEN specify?', 'options' => ['Physical rows', 'Logical range based on values', 'Row numbers', 'Partition size'], 'correct' => 1],
        ['question' => 'What is a scalar user-defined function?', 'options' => ['A system function', 'A function that returns a single value', 'A function that returns a table', 'An aggregate function'], 'correct' => 1],
        ['question' => 'What is a table-valued function?', 'options' => ['A function that modifies tables', 'A function that returns a table', 'A function that creates tables', 'A stored procedure'], 'correct' => 1],
        ['question' => 'What is a cursor?', 'options' => ['A pointer', 'A database object for iterating over result sets row by row', 'A mouse pointer', 'An index'], 'correct' => 1],
        ['question' => 'What is dynamic SQL?', 'options' => ['Fast SQL', 'SQL constructed and executed at runtime', 'Changing SQL', 'Interactive SQL'], 'correct' => 1],
        ['question' => 'What is SQL injection?', 'options' => ['Adding SQL to a database', 'A security vulnerability where malicious SQL is inserted into queries', 'Importing data', 'A join type'], 'correct' => 1],
        ['question' => 'How can you prevent SQL injection?', 'options' => ['Using dynamic SQL', 'Using parameterized queries/prepared statements', 'Encrypting data', 'Using views'], 'correct' => 1],
        ['question' => 'What does GRANT do?', 'options' => ['Approves queries', 'Gives permissions to users', 'Commits transactions', 'Validates access'], 'correct' => 1],
        ['question' => 'What does REVOKE do?', 'options' => ['Cancels queries', 'Removes permissions from users', 'Rolls back transactions', 'Deletes users'], 'correct' => 1],
        ['question' => 'What is normalization?', 'options' => ['Making data normal', 'Organizing data to reduce redundancy', 'Standardizing formats', 'Validating data'], 'correct' => 1],
        ['question' => 'What is 1NF (First Normal Form)?', 'options' => ['Single table', 'Atomic values in each column, no repeating groups', 'One row per table', 'One column per table'], 'correct' => 1],
        ['question' => 'What is 2NF (Second Normal Form)?', 'options' => ['Two tables', 'In 1NF and all non-key attributes depend on the entire primary key', 'Two columns', 'Two rows'], 'correct' => 1],
        ['question' => 'What is 3NF (Third Normal Form)?', 'options' => ['Three tables', 'In 2NF and no transitive dependencies', 'Three columns', 'Three primary keys'], 'correct' => 1],
        ['question' => 'What is BCNF (Boyce-Codd Normal Form)?', 'options' => ['Fourth normal form', 'A stricter version of 3NF', 'Before normalization', 'Basic normalization'], 'correct' => 1],
        ['question' => 'What is denormalization?', 'options' => ['Removing normalization', 'Intentionally adding redundancy for performance', 'Breaking normal forms', 'Error in design'], 'correct' => 1],
        ['question' => 'What is a star schema?', 'options' => ['A schema with five tables', 'A dimensional model with fact and dimension tables', 'A circular schema', 'A hierarchical schema'], 'correct' => 1],
        ['question' => 'What is a snowflake schema?', 'options' => ['A winter database', 'A normalized star schema with dimension hierarchies', 'A six-pointed schema', 'A cold storage schema'], 'correct' => 1],
        ['question' => 'What are slowly changing dimensions (SCD)?', 'options' => ['Dimensions that rarely change', 'Techniques for tracking historical changes in dimension tables', 'Slow queries', 'Archived dimensions'], 'correct' => 1],
        ['question' => 'What are temporal tables?', 'options' => ['Temporary tables', 'Tables that track changes over time automatically', 'Time-based tables', 'Scheduled tables'], 'correct' => 1],
        ['question' => 'What is a foreign data wrapper?', 'options' => ['A foreign key wrapper', 'A mechanism to access external data sources', 'An encryption method', 'A data converter'], 'correct' => 1],
    ]],
    ['label' => 'Expert', 'questions' => [
        ['question' => 'What is MVCC?', 'options' => ['Multi-Value Column Control', 'Multi-Version Concurrency Control', 'Multiple Virtual Concurrent Connections', 'Managed Version Control Cache'], 'correct' => 1],
        ['question' => 'What is the purpose of MVCC?', 'options' => ['Faster queries', 'Allow concurrent transactions without blocking reads', 'Save disk space', 'Improve security'], 'correct' => 1],
        ['question' => 'What is WAL?', 'options' => ['Write-Ahead Log', 'Write-After-Load', 'Wide Area Link', 'Work Allocation List'], 'correct' => 0],
        ['question' => 'Why is WAL important?', 'options' => ['Faster writes', 'Ensures durability and enables crash recovery', 'Reduces storage', 'Improves reads'], 'correct' => 1],
        ['question' => 'What does VACUUM do in PostgreSQL?', 'options' => ['Deletes data', 'Reclaims storage from dead tuples', 'Compresses tables', 'Backs up data'], 'correct' => 1],
        ['question' => 'When should you run VACUUM?', 'options' => ['Never', 'Regularly after many updates/deletes to reclaim space', 'Only on errors', 'During backups'], 'correct' => 1],
        ['question' => 'What is the buffer pool?', 'options' => ['A backup area', 'Memory cache for frequently accessed data pages', 'A connection pool', 'A query queue'], 'correct' => 1],
        ['question' => 'What are the common types of locks in databases?', 'options' => ['Only exclusive locks', 'Shared (read) and Exclusive (write) locks', 'Only read locks', 'Physical locks'], 'correct' => 1],
        ['question' => 'What is a deadlock?', 'options' => ['A crashed database', 'Two or more transactions waiting for each other to release locks', 'A slow query', 'A locked table'], 'correct' => 1],
        ['question' => 'How can deadlocks be prevented?', 'options' => ['Using more locks', 'Lock ordering, timeouts, and deadlock detection', 'Disabling transactions', 'Using only reads'], 'correct' => 1],
        ['question' => 'What are query rewrite rules?', 'options' => ['Manual query editing', 'Automatic transformations to optimize queries', 'Syntax corrections', 'Query formatting'], 'correct' => 1],
        ['question' => 'What is parallel query execution?', 'options' => ['Running queries simultaneously', 'Splitting a single query across multiple CPU cores', 'Using multiple connections', 'Distributed queries'], 'correct' => 1],
        ['question' => 'What is JIT compilation in PostgreSQL?', 'options' => ['Java Integration Tool', 'Just-In-Time compilation of query expressions', 'Quick compilation', 'Interpreted execution'], 'correct' => 1],
        ['question' => 'What is a cost-based optimizer?', 'options' => ['Cheapest queries', 'Chooses execution plans based on estimated costs', 'Budget optimizer', 'Rule-based optimizer'], 'correct' => 1],
        ['question' => 'What is a rule-based optimizer?', 'options' => ['Follows regulations', 'Chooses execution plans based on predefined rules', 'Cost-based optimizer', 'AI optimizer'], 'correct' => 1],
        ['question' => 'Why are table statistics important?', 'options' => ['For reporting', 'Help the optimizer make accurate cost estimates', 'For auditing', 'For documentation'], 'correct' => 1],
        ['question' => 'What are extended statistics in PostgreSQL?', 'options' => ['Longer statistics', 'Multi-column statistics for better estimates', 'Detailed statistics', 'Historical statistics'], 'correct' => 1],
        ['question' => 'What is a bloom filter?', 'options' => ['A data type', 'A probabilistic data structure for membership testing', 'A flower database', 'An index type'], 'correct' => 1],
        ['question' => 'What is a BRIN index?', 'options' => ['Binary Index', 'Block Range Index for large sequential tables', 'Basic Relational Index', 'Backup Reference Index'], 'correct' => 1],
        ['question' => 'What is a partial index?', 'options' => ['An incomplete index', 'An index on a subset of rows matching a condition', 'A half-built index', 'An index on some columns'], 'correct' => 1],
        ['question' => 'What is an expression index?', 'options' => ['An index on expressions/functions rather than columns', 'A fast index', 'A calculated index', 'A dynamic index'], 'correct' => 0],
        ['question' => 'What is an index-only scan?', 'options' => ['Scanning without index', 'Query satisfied entirely from index without accessing table', 'Index creation', 'Index verification'], 'correct' => 1],
        ['question' => 'What is a bitmap index scan?', 'options' => ['Scanning images', 'Using bitmaps to combine multiple indexes', 'Fast scan', 'Memory scan'], 'correct' => 1],
        ['question' => 'What is a merge join?', 'options' => ['Merging tables', 'Join algorithm that merges sorted inputs', 'Combining joins', 'MERGE statement'], 'correct' => 1],
        ['question' => 'What is a hash join?', 'options' => ['Random join', 'Join using a hash table built from one input', 'Encrypted join', 'Fast join'], 'correct' => 1],
        ['question' => 'What is a nested loop join?', 'options' => ['Circular join', 'Join that iterates through one table for each row of another', 'Loop in query', 'Recursive join'], 'correct' => 1],
        ['question' => 'When do hash joins spill to disk?', 'options' => ['Always', 'When the hash table exceeds available memory', 'Never', 'On errors'], 'correct' => 1],
        ['question' => 'What is adaptive query execution?', 'options' => ['Self-learning queries', 'Adjusting execution plans during runtime based on actual data', 'Flexible queries', 'Dynamic SQL'], 'correct' => 1],
        ['question' => 'What is a columnstore index?', 'options' => ['Index on columns', 'A columnar storage format for analytical queries', 'Vertical index', 'Compressed index'], 'correct' => 1],
        ['question' => 'What is in-memory OLTP?', 'options' => ['Fast OLTP', 'Transaction processing using memory-optimized tables', 'Cached OLTP', 'RAM database'], 'correct' => 1],
        ['question' => 'What is CDC (Change Data Capture)?', 'options' => ['Central Data Control', 'Tracking and capturing changes to data', 'Change Detection Code', 'Continuous Data Collection'], 'correct' => 1],
        ['question' => 'What is logical replication?', 'options' => ['Reasonable replication', 'Replication based on logical changes (INSERT/UPDATE/DELETE)', 'Logical database copy', 'Smart replication'], 'correct' => 1],
        ['question' => 'What is streaming replication?', 'options' => ['Video streaming', 'Continuous replication of WAL records to replicas', 'Data streaming', 'Live replication'], 'correct' => 1],
        ['question' => 'What is point-in-time recovery?', 'options' => ['Recovery to current time', 'Restoring database to a specific moment in time', 'Fast recovery', 'Partial recovery'], 'correct' => 1],
        ['question' => 'What do pg_stat_* views provide in PostgreSQL?', 'options' => ['Statistics about state', 'Runtime statistics about database activity', 'Static data', 'Configuration info'], 'correct' => 1],
        ['question' => 'What are wait events?', 'options' => ['Scheduled events', 'Reasons why a session is waiting/blocked', 'Event logs', 'User events'], 'correct' => 1],
        ['question' => 'Why is wait event analysis important?', 'options' => ['For scheduling', 'Identifies performance bottlenecks', 'For logging', 'For auditing'], 'correct' => 1],
        ['question' => 'How do you identify blocking queries?', 'options' => ['Guessing', 'Using system views like pg_locks and pg_stat_activity', 'Random checks', 'User reports'], 'correct' => 1],
        ['question' => 'What is the visibility map in PostgreSQL?', 'options' => ['Visual display', 'Tracks which pages have only visible tuples', 'Access control', 'Schema diagram'], 'correct' => 1],
        ['question' => 'What is the purpose of autovacuum?', 'options' => ['Automatic cleaning', 'Automatically runs VACUUM to prevent table bloat', 'Auto-delete', 'Self-optimization'], 'correct' => 1],
    ]],
];
require_once __DIR__ . '/quiz-engine.php';
