<?php
$page_title = 'TypeScript Quiz – 100 Levels – CodeFoundry';
$active_page = 'training';
$quiz_title  = 'TypeScript';
$quiz_slug   = 'typescript';
$quiz_tiers  = [
    [
        'label' => 'Introduction',
        'questions' => [
            ['question' => 'What is TypeScript?', 'options' => ['A database language', 'A typed superset of JavaScript', 'A CSS preprocessor', 'A build tool'], 'correct' => 1],
            ['question' => 'What file extension do TypeScript files use?', 'options' => ['.js', '.tsx', '.ts', '.tsc'], 'correct' => 2],
            ['question' => 'Which command compiles a TypeScript file?', 'options' => ['node', 'tsc', 'ts-run', 'compile'], 'correct' => 1],
            ['question' => 'What is a type annotation in TypeScript?', 'options' => ['A comment in code', 'Explicitly specifying a variable\'s type', 'A type import', 'A runtime check'], 'correct' => 1],
            ['question' => 'Which type represents a whole number in TypeScript?', 'options' => ['int', 'integer', 'number', 'float'], 'correct' => 2],
            ['question' => 'Which type represents true/false values?', 'options' => ['bit', 'bool', 'boolean', 'flag'], 'correct' => 2],
            ['question' => 'What does the `string` type hold?', 'options' => ['Numbers', 'Boolean values', 'Text values', 'Arrays'], 'correct' => 2],
            ['question' => 'What is type inference in TypeScript?', 'options' => ['Manually assigning types', 'TypeScript automatically determining types from values', 'Importing types', 'Type casting'], 'correct' => 1],
            ['question' => 'What does `let x: any` mean?', 'options' => ['x can only be a number', 'x can hold any type of value', 'x is undefined', 'x is an object'], 'correct' => 1],
            ['question' => 'What is the `void` type used for?', 'options' => ['Empty arrays', 'Null values', 'Functions that return nothing', 'Undefined variables'], 'correct' => 2],
            ['question' => 'What is the `never` type?', 'options' => ['A type for null', 'A type for values that never occur', 'An empty type alias', 'A type for 0'], 'correct' => 1],
            ['question' => 'What does `unknown` mean in TypeScript?', 'options' => ['Same as any', 'A type-safe counterpart to any', 'An undefined variable', 'A null value'], 'correct' => 1],
            ['question' => 'How do you define an array of strings in TypeScript?', 'options' => ['string[]', 'Array(string)', 'strings[]', '{string}'], 'correct' => 0],
            ['question' => 'What is a tuple in TypeScript?', 'options' => ['A set type', 'An array with fixed types per index', 'A map type', 'A pair of numbers'], 'correct' => 1],
            ['question' => 'What does `interface` define in TypeScript?', 'options' => ['A class', 'A contract describing object shape', 'A function', 'A module'], 'correct' => 1],
            ['question' => 'Which keyword is used to define a type alias?', 'options' => ['alias', 'type', 'typedef', 'define'], 'correct' => 1],
            ['question' => 'What is the TypeScript compiler configuration file called?', 'options' => ['package.json', 'tsconfig.json', 'ts.config.js', 'typescript.json'], 'correct' => 1],
            ['question' => 'How do you annotate a function parameter as a number?', 'options' => ['function f(x: number)', 'function f(number x)', 'function f(x as number)', 'function f[x: number]'], 'correct' => 0],
            ['question' => 'What does `null` represent in TypeScript?', 'options' => ['An empty string', 'The absence of a value', 'Zero', 'An empty array'], 'correct' => 1],
            ['question' => 'What does `undefined` represent?', 'options' => ['A variable not yet declared', 'A variable declared but not assigned a value', 'An empty object', 'A null pointer'], 'correct' => 1],
            ['question' => 'What is the `typeof` operator used for?', 'options' => ['Declaring types', 'Getting the runtime type of a value as a string', 'Importing types', 'Type casting'], 'correct' => 1],
            ['question' => 'Which of these is a valid TypeScript basic type?', 'options' => ['char', 'float', 'symbol', 'byte'], 'correct' => 2],
            ['question' => 'How does TypeScript differ from JavaScript at runtime?', 'options' => ['TypeScript is faster', 'TypeScript compiles to JavaScript; types are erased', 'TypeScript runs natively in browsers', 'TypeScript adds runtime type checks'], 'correct' => 1],
            ['question' => 'What does `const x = 5` infer in TypeScript?', 'options' => ['type any', 'type number', 'type 5 (literal type)', 'type int'], 'correct' => 2],
            ['question' => 'Which option in tsconfig enables strict type checking?', 'options' => ['checkTypes: true', 'strict: true', 'noAny: true', 'typeCheck: true'], 'correct' => 1],
        ],
    ],
    [
        'label' => 'Beginner',
        'questions' => [
            ['question' => 'What is a union type in TypeScript?', 'options' => ['A type that combines two interfaces', 'A type that can be one of several types', 'A type for SQL unions', 'A merged type'], 'correct' => 1],
            ['question' => 'How do you write a union type for string or number?', 'options' => ['string & number', 'string | number', 'string + number', 'string or number'], 'correct' => 1],
            ['question' => 'What is an intersection type?', 'options' => ['A type that must satisfy all constituent types', 'A type that is one of several types', 'A subset type', 'A common type'], 'correct' => 0],
            ['question' => 'What does `type Point = { x: number; y: number }` define?', 'options' => ['A class', 'An interface', 'A type alias', 'A module'], 'correct' => 2],
            ['question' => 'What is a literal type?', 'options' => ['A string type', 'A type representing a specific value', 'A primitive type', 'A template type'], 'correct' => 1],
            ['question' => 'What does the `?` mean in `interface User { name?: string }`?', 'options' => ['name is required', 'name is optional', 'name is nullable', 'name is readonly'], 'correct' => 1],
            ['question' => 'What does `readonly` do on an interface property?', 'options' => ['Makes it optional', 'Prevents reassignment after initialization', 'Makes it public', 'Makes it a getter'], 'correct' => 1],
            ['question' => 'What is an enum in TypeScript?', 'options' => ['An enumerable array', 'A named set of constants', 'A list type', 'A numeric range'], 'correct' => 1],
            ['question' => 'What is the default first value of a numeric enum?', 'options' => ['1', '0', '-1', 'undefined'], 'correct' => 1],
            ['question' => 'What is a string enum?', 'options' => ['An enum with string keys', 'An enum where each member has a string value', 'A string array', 'A template literal'], 'correct' => 1],
            ['question' => 'How do you type a function that takes a number and returns a string?', 'options' => ['(n: number) => string', '(number) => string', 'function(n: number): string', 'fn<number, string>'], 'correct' => 0],
            ['question' => 'What does `as` do in TypeScript?', 'options' => ['Creates an alias', 'Performs a type assertion', 'Imports a module', 'Casts at runtime'], 'correct' => 1],
            ['question' => 'What is the non-null assertion operator?', 'options' => ['??', '!', '?.', '!!'], 'correct' => 1],
            ['question' => 'What does `interface A extends B` mean?', 'options' => ['A replaces B', 'A inherits all properties of B', 'A imports B', 'A merges with B'], 'correct' => 1],
            ['question' => 'Can a class implement multiple interfaces in TypeScript?', 'options' => ['No', 'Yes', 'Only two', 'Only with generics'], 'correct' => 1],
            ['question' => 'What is the difference between `interface` and `type` in TypeScript?', 'options' => ['No difference', 'Interfaces can be extended/merged; type aliases are more flexible for unions', 'Types are faster', 'Interfaces support generics, types do not'], 'correct' => 1],
            ['question' => 'What does `keyof` do?', 'options' => ['Gets values of an object', 'Produces a union of keys of a type', 'Accesses a key', 'Creates a key-value map'], 'correct' => 1],
            ['question' => 'What is the `in` operator used for in TypeScript narrowing?', 'options' => ['Looping', 'Checking if a property exists in an object', 'Importing modules', 'Template literals'], 'correct' => 1],
            ['question' => 'What is `typeof` narrowing?', 'options' => ['Getting a type at compile time', 'Using typeof in a condition to narrow types', 'Type inference', 'Type assertion'], 'correct' => 1],
            ['question' => 'What does `instanceof` check in TypeScript?', 'options' => ['Interface membership', 'Whether an object is an instance of a class', 'Type equality', 'Module instance'], 'correct' => 1],
            ['question' => 'What is a type guard?', 'options' => ['A protected property', 'A function that narrows a type at runtime', 'A private method', 'A guard clause'], 'correct' => 1],
            ['question' => 'What return type should a user-defined type guard use?', 'options' => ['boolean', 'void', 'param is Type', 'Type'], 'correct' => 2],
            ['question' => 'What does `Partial<T>` do?', 'options' => ['Removes all properties', 'Makes all properties optional', 'Makes all properties required', 'Picks some properties'], 'correct' => 1],
            ['question' => 'What does `Required<T>` do?', 'options' => ['Makes all properties optional', 'Makes all properties required', 'Removes optional marker', 'Both B and C'], 'correct' => 3],
            ['question' => 'What does `Readonly<T>` do?', 'options' => ['Makes properties optional', 'Makes all properties readonly', 'Freezes the object at runtime', 'Prevents type widening'], 'correct' => 1],
        ],
    ],
    [
        'label' => 'Intermediate',
        'questions' => [
            ['question' => 'What are generics in TypeScript?', 'options' => ['Universal imports', 'Type parameters that make components reusable', 'Generic programming', 'Default types'], 'correct' => 1],
            ['question' => 'How do you declare a generic function?', 'options' => ['function f<T>(arg: T): T', 'function f[T](arg: T): T', 'function f(arg: generic): generic', 'function<T> f(arg): T'], 'correct' => 0],
            ['question' => 'What does `T extends string` in a generic mean?', 'options' => ['T inherits from string', 'T is constrained to be assignable to string', 'T is a subclass of string', 'T equals string'], 'correct' => 1],
            ['question' => 'What does `Pick<T, K>` do?', 'options' => ['Removes keys K from T', 'Creates a type with only keys K from T', 'Picks random keys', 'Merges T with K'], 'correct' => 1],
            ['question' => 'What does `Omit<T, K>` do?', 'options' => ['Picks keys K from T', 'Creates a type with all keys of T except K', 'Removes the type', 'Optional K in T'], 'correct' => 1],
            ['question' => 'What does `Record<K, V>` do?', 'options' => ['Creates a tuple', 'Creates an object type with keys K and values V', 'Records runtime values', 'Creates a Map'], 'correct' => 1],
            ['question' => 'What is a mapped type?', 'options' => ['A type using Map', 'A type that transforms properties of another type using iteration', 'A dictionary type', 'A mapped array'], 'correct' => 1],
            ['question' => 'What is the syntax for a mapped type?', 'options' => ['{ K in keyof T: T[K] }', '{ [K in keyof T]: T[K] }', '{ K: keyof T => T[K] }', '{ map K of T to T[K] }'], 'correct' => 1],
            ['question' => 'What is a conditional type?', 'options' => ['An if-else type expression', 'A type that depends on a condition: T extends U ? X : Y', 'A type with optional properties', 'A nullable type'], 'correct' => 1],
            ['question' => 'What does `infer` do in conditional types?', 'options' => ['Infers types at runtime', 'Captures a type within the true branch of a conditional type', 'Imports type inference', 'Declares a local variable'], 'correct' => 1],
            ['question' => 'What are template literal types?', 'options' => ['Template strings in types', 'Types built by combining string literals with template syntax', 'Template class types', 'Literal template patterns'], 'correct' => 1],
            ['question' => 'What does `ReturnType<T>` extract?', 'options' => ['The parameter type', 'The return type of a function type T', 'The generic type', 'The this type'], 'correct' => 1],
            ['question' => 'What does `Parameters<T>` extract?', 'options' => ['The return type', 'A tuple of parameter types of function type T', 'The generic constraints', 'The class constructor parameters'], 'correct' => 1],
            ['question' => 'What is declaration merging?', 'options' => ['Combining two JS files', 'When two declarations with the same name are merged by TypeScript', 'Merging imports', 'Merging modules at runtime'], 'correct' => 1],
            ['question' => 'Which of these supports declaration merging?', 'options' => ['type aliases', 'interfaces', 'classes only', 'enums only'], 'correct' => 1],
            ['question' => 'What is a discriminated union?', 'options' => ['A union with different value counts', 'A union where each member has a shared literal type property used as a discriminant', 'A union of classes', 'A union with generics'], 'correct' => 1],
            ['question' => 'What does `Extract<T, U>` do?', 'options' => ['Removes U from T', 'Extracts types from T that are assignable to U', 'Intersects T and U', 'Merges T and U'], 'correct' => 1],
            ['question' => 'What does `Exclude<T, U>` do?', 'options' => ['Extracts types from T assignable to U', 'Removes types from T that are assignable to U', 'Removes U from all types', 'Excludes optional properties'], 'correct' => 1],
            ['question' => 'What does `NonNullable<T>` do?', 'options' => ['Adds null to T', 'Removes null and undefined from T', 'Makes T non-optional', 'Removes readonly from T'], 'correct' => 1],
            ['question' => 'What is the purpose of `ConstructorParameters<T>`?', 'options' => ['Gets return type of constructor', 'Gets parameter types of a constructor function type', 'Gets class properties', 'Gets class methods'], 'correct' => 1],
            ['question' => 'What does `InstanceType<T>` return?', 'options' => ['The constructor type', 'The instance type of a constructor type T', 'The prototype', 'The class methods'], 'correct' => 1],
            ['question' => 'What is a recursive type?', 'options' => ['A type that calls a function', 'A type that references itself', 'A type in a loop', 'A circular import'], 'correct' => 1],
            ['question' => 'What is module augmentation in TypeScript?', 'options' => ['Importing extra modules', 'Adding new declarations to an existing module', 'Augmenting runtime behavior', 'Module aliasing'], 'correct' => 1],
            ['question' => 'What is the `satisfies` operator (TypeScript 4.9)?', 'options' => ['A strict equality check', 'Validates a value matches a type without widening it', 'A runtime assertion', 'A null-check operator'], 'correct' => 1],
            ['question' => 'What does `as const` do?', 'options' => ['Casts to a constant type', 'Makes all values their literal types and readonly', 'Freezes the object at runtime', 'Marks as immutable at runtime'], 'correct' => 1],
        ],
    ],
    [
        'label' => 'Advanced',
        'questions' => [
            ['question' => 'What are decorators in TypeScript?', 'options' => ['CSS-like annotations', 'Special declarations attached to class/method/property/parameter declarations', 'Runtime middleware', 'Import aliases'], 'correct' => 1],
            ['question' => 'What decorator target does `@Component` typically annotate?', 'options' => ['Method', 'Property', 'Class', 'Parameter'], 'correct' => 2],
            ['question' => 'Which tsconfig option must be enabled to use decorators?', 'options' => ['allowDecorators', 'experimentalDecorators', 'enableDecorators', 'useDecorators'], 'correct' => 1],
            ['question' => 'What is a namespace in TypeScript?', 'options' => ['A module alias', 'A way to organize code in a named scope', 'A global variable', 'An import path'], 'correct' => 1],
            ['question' => 'What keyword declares a namespace?', 'options' => ['module', 'namespace', 'scope', 'package'], 'correct' => 1],
            ['question' => 'What is the difference between a namespace and a module?', 'options' => ['No difference', 'Namespaces use global scope; modules use file scope with imports/exports', 'Modules use global scope', 'Namespaces require tsconfig'], 'correct' => 1],
            ['question' => 'What is a type predicate?', 'options' => ['A type that filters', 'A return type like `x is T` used in type guard functions', 'A predicate logic type', 'A conditional type'], 'correct' => 1],
            ['question' => 'What is the `infer` keyword used for?', 'options' => ['Runtime inference', 'Declaring a type variable to be inferred within a conditional type', 'Inferring generics', 'Importing inferred types'], 'correct' => 1],
            ['question' => 'What is a recursive conditional type example?', 'options' => ['T extends T', 'type Flatten<T> = T extends Array<infer U> ? Flatten<U> : T', 'type T = T | null', 'infer T extends T'], 'correct' => 1],
            ['question' => 'What does `unique symbol` do?', 'options' => ['Creates a named symbol', 'Creates a type-level unique symbol that cannot be unified with other symbols', 'Creates a runtime symbol', 'Declares a symbol enum'], 'correct' => 1],
            ['question' => 'What is a branded type?', 'options' => ['A type with a logo', 'A type intersected with a unique tag to prevent structural equivalence', 'A tagged union', 'A type alias with branding'], 'correct' => 1],
            ['question' => 'What is the `asserts` keyword used for?', 'options' => ['Assertion errors', 'Assertion functions that narrow types as a side effect', 'Unit test assertions', 'Assert imports'], 'correct' => 1],
            ['question' => 'What does `ThisType<T>` do?', 'options' => ['Gets the class type', 'Provides the type of `this` in object literals', 'Gets the method type', 'Gets the prototype type'], 'correct' => 1],
            ['question' => 'What is a function overload in TypeScript?', 'options' => ['Overriding a parent function', 'Multiple function signatures for one implementation', 'A higher-order function', 'Function currying'], 'correct' => 1],
            ['question' => 'What is a discriminant property?', 'options' => ['A required property', 'A shared literal-typed property used to differentiate union members', 'A private property', 'A unique property'], 'correct' => 1],
            ['question' => 'What does `declare` do in TypeScript?', 'options' => ['Declares a variable at runtime', 'Declares a type-only declaration without emitting JavaScript', 'Imports a type', 'Creates a constant'], 'correct' => 1],
            ['question' => 'What is an ambient declaration?', 'options' => ['A global variable', 'A declaration that describes the shape of code without implementation, often in .d.ts files', 'An environment variable', 'A module declaration'], 'correct' => 1],
            ['question' => 'What does `export type` ensure?', 'options' => ['Exports types faster', 'The export is erased at runtime (type-only export)', 'Exports only interfaces', 'Exports are always types'], 'correct' => 1],
            ['question' => 'What is `import type` used for?', 'options' => ['Importing faster', 'Importing type-only declarations that are erased at runtime', 'Importing .d.ts files', 'Importing default types'], 'correct' => 1],
            ['question' => 'What is the `Awaited<T>` utility type?', 'options' => ['Turns T into a Promise', 'Recursively unwraps Promise types to get the resolved value type', 'Awaits async functions', 'Gets the awaited state'], 'correct' => 1],
            ['question' => 'What is variance in TypeScript?', 'options' => ['Type variability', 'How subtype relationships relate between composed types', 'Value variation', 'Generic variance keyword'], 'correct' => 1],
            ['question' => 'What is covariance?', 'options' => ['A type that varies with subtypes in the same direction', 'A type that varies in the opposite direction', 'A constant type', 'A union type'], 'correct' => 0],
            ['question' => 'What is contravariance?', 'options' => ['Same-direction subtyping', 'Opposite-direction subtyping (subtype inputs are supertypes)', 'No subtyping', 'Invariant typing'], 'correct' => 1],
            ['question' => 'Which TypeScript 4.7 feature explicitly annotates variance?', 'options' => ['variance keyword', 'in/out modifiers on generic type parameters', 'covariant keyword', 'extends variance'], 'correct' => 1],
            ['question' => 'What does the `NoInfer<T>` utility type do (TypeScript 5.4)?', 'options' => ['Prevents generics', 'Blocks inference at a specific type position to avoid unwanted widening', 'Removes inference rules', 'Stops type inference globally'], 'correct' => 1],
        ],
    ],
    [
        'label' => 'Expert',
        'questions' => [
            ['question' => 'What is a `.d.ts` file?', 'options' => ['A TypeScript source file', 'A declaration file that provides type information without implementation', 'A compiled JS file', 'A type definition archive'], 'correct' => 1],
            ['question' => 'Where are community-maintained type definitions published?', 'options' => ['@types scope on npm', 'types.io', 'typedefs npm package', 'typings.json'], 'correct' => 0],
            ['question' => 'What does `skipLibCheck: true` in tsconfig do?', 'options' => ['Skips checking your own code', 'Skips type checking of declaration files', 'Speeds up compilation globally', 'Skips unused variable checks'], 'correct' => 1],
            ['question' => 'What is `paths` in tsconfig used for?', 'options' => ['Setting the output directory', 'Configuring module path aliases', 'Including files', 'Defining type roots'], 'correct' => 1],
            ['question' => 'What does `isolatedModules: true` enforce?', 'options' => ['Each file must be a module compilable in isolation without type info from other files', 'Files cannot import each other', 'Modules are isolated at runtime', 'Prevents circular imports'], 'correct' => 0],
            ['question' => 'What is the `composite` tsconfig option used for?', 'options' => ['Composing types', 'Enabling incremental builds with project references', 'Composing modules', 'Building composite types'], 'correct' => 1],
            ['question' => 'What are TypeScript project references?', 'options' => ['References to npm packages', 'A way to structure large TypeScript codebases into smaller subprojects with explicit dependencies', 'Cross-file type imports', 'Reference counting for types'], 'correct' => 1],
            ['question' => 'What does `strictNullChecks` do?', 'options' => ['Disallows null entirely', 'Makes null and undefined distinct types that must be handled explicitly', 'Enables null coalescing', 'Checks for null at runtime'], 'correct' => 1],
            ['question' => 'What is `noUncheckedIndexedAccess`?', 'options' => ['Prevents array access', 'Adds undefined to array/object index access types to prevent unsafe assumptions', 'Requires null checks on arrays', 'Disallows index signatures'], 'correct' => 1],
            ['question' => 'What does `exactOptionalPropertyTypes` do?', 'options' => ['Makes optional properties required', 'Distinguishes between a missing property and a property set to undefined', 'Removes optional properties', 'Adds exact matching'], 'correct' => 1],
            ['question' => 'What is higher-kinded type simulation in TypeScript?', 'options' => ['Using higher-order functions', 'Encoding type constructors with interface maps to approximate HKTs', 'Using higher generic bounds', 'Advanced class inheritance'], 'correct' => 1],
            ['question' => 'What is a type-level programming technique in TypeScript?', 'options' => ['Writing programs in type syntax', 'Performing computation purely in the type system (e.g., string parsing, arithmetic)', 'Type generation scripts', 'Codegen tooling'], 'correct' => 1],
            ['question' => 'What is the `tsc --noEmit` flag used for?', 'options' => ['Prevents output JS', 'Type-checks without emitting compiled files', 'Skips emit phase', 'Both A and B'], 'correct' => 3],
            ['question' => 'What is the performance implication of deep recursive types?', 'options' => ['Faster compilation', 'Can slow compilation significantly or hit recursion limits', 'Better type safety', 'No performance impact'], 'correct' => 1],
            ['question' => 'What does `importsNotUsedAsValues` control?', 'options' => ['Unused import warnings', 'How imports used only as types are handled during emit', 'Importing values from types', 'Type-only import rules'], 'correct' => 1],
            ['question' => 'What is module augmentation used for?', 'options' => ['Extending module size', 'Adding declarations to an external module\'s types without modifying the original', 'Augmenting runtime modules', 'Merging build outputs'], 'correct' => 1],
            ['question' => 'What does `useUnknownInCatchVariables` do?', 'options' => ['Disallows catch blocks', 'Makes catch clause variables typed as unknown instead of any', 'Enables unknown type globally', 'Catches unknown errors'], 'correct' => 1],
            ['question' => 'What is the `satisfies` operator\'s advantage over type assertions?', 'options' => ['It is faster', 'It validates the type without losing the original inferred type information', 'It is stricter', 'It enables runtime checks'], 'correct' => 1],
            ['question' => 'What is a type-safe builder pattern in TypeScript?', 'options' => ['A class builder', 'Using generics and method chaining to accumulate type state safely', 'A factory pattern', 'A mixin pattern'], 'correct' => 1],
            ['question' => 'What does `emitDecoratorMetadata` enable?', 'options' => ['Emitting types as metadata', 'Emitting type metadata for decorators using Reflect.metadata', 'Metadata in comments', 'Runtime type reflection'], 'correct' => 1],
            ['question' => 'What is structural typing?', 'options' => ['Duck typing enforced by structure', 'Type compatibility based on shape/structure rather than name', 'Nominal typing', 'Strict typing'], 'correct' => 1],
            ['question' => 'What is nominal typing and how is it simulated in TypeScript?', 'options' => ['It is built-in', 'Types are compatible by name; simulated with branded/opaque types', 'Using type aliases', 'Using class names'], 'correct' => 1],
            ['question' => 'What does `tsBuildInfoFile` in tsconfig control?', 'options' => ['The output .js file', 'The path to the incremental compilation cache file', 'The build log', 'The declaration output'], 'correct' => 1],
            ['question' => 'What is the `verbatimModuleSyntax` tsconfig option?', 'options' => ['Verbose output mode', 'Enforces that import/export syntax is preserved verbatim without transformation', 'Module naming convention', 'Syntax validation'], 'correct' => 1],
            ['question' => 'What does `TypeScript Language Service` provide?', 'options' => ['Runtime type checking', 'IDE features like autocomplete, go-to-definition, and refactoring via the LS protocol', 'A Node.js server', 'TypeScript runtime'], 'correct' => 1],
        ],
    ],
];
require_once __DIR__ . '/quiz-engine.php';
