<?php
$page_title = 'Vue.js Quiz – 100 Levels – CodeFoundry';
$active_page = 'training';
$quiz_title  = 'Vue.js';
$quiz_slug   = 'vuejs';
$quiz_tiers  = [
    [
        'label' => 'Introduction',
        'questions' => [
            ['question' => 'What is Vue.js?', 'options' => ['A CSS preprocessor', 'A server-side MVC framework', 'A progressive JavaScript framework for building user interfaces', 'A relational database ORM'], 'correct' => 2],
            ['question' => 'Who created Vue.js?', 'options' => ['Ryan Dahl', 'Jordan Walke', 'Evan You', 'Anders Hejlsberg'], 'correct' => 2],
            ['question' => 'What directive dynamically binds an HTML attribute to an expression?', 'options' => ['v-on', 'v-model', 'v-if', 'v-bind'], 'correct' => 3],
            ['question' => 'What is the shorthand syntax for v-bind?', 'options' => ['@', '#', ':', '!'], 'correct' => 2],
            ['question' => 'What directive creates two-way data binding on form elements?', 'options' => ['v-bind', 'v-on', 'v-if', 'v-model'], 'correct' => 3],
            ['question' => 'What directive conditionally renders an element by adding or removing it from the DOM?', 'options' => ['v-show', 'v-for', 'v-if', 'v-bind'], 'correct' => 2],
            ['question' => 'What directive hides an element by toggling display:none without removing it from the DOM?', 'options' => ['v-if', 'v-hide', 'v-show', 'v-invisible'], 'correct' => 2],
            ['question' => 'What directive renders a list of items from an array?', 'options' => ['v-each', 'v-list', 'v-repeat', 'v-for'], 'correct' => 3],
            ['question' => 'What directive attaches a DOM event listener?', 'options' => ['v-bind', 'v-event', 'v-on', 'v-listen'], 'correct' => 2],
            ['question' => 'What is the shorthand for v-on?', 'options' => ['#', '@', ':', '!'], 'correct' => 1],
            ['question' => 'What option in the Options API holds component reactive data?', 'options' => ['state', 'props', 'computed', 'data'], 'correct' => 3],
            ['question' => 'What option holds computed properties in the Options API?', 'options' => ['watch', 'data', 'computed', 'methods'], 'correct' => 2],
            ['question' => 'What option holds component methods in the Options API?', 'options' => ['computed', 'methods', 'actions', 'handlers'], 'correct' => 1],
            ['question' => 'Why must the data option be a function in Vue components (not a plain object)?', 'options' => ['Functions are faster', 'Vue requires it for template parsing', 'So each component instance gets its own independent data copy', 'Functions support async data'], 'correct' => 2],
            ['question' => 'How do you create a Vue 3 application instance?', 'options' => ['new Vue()', 'Vue.init()', 'createApp()', 'bootstrapApp()'], 'correct' => 2],
            ['question' => 'What is text interpolation in Vue?', 'options' => ['v-bind on text nodes', 'Using {{ expression }} to output data in templates', 'A text animation directive', 'String concatenation in methods'], 'correct' => 1],
            ['question' => 'What does the v-once directive do?', 'options' => ['Renders the element only on first user interaction', 'Applies a one-time animation', 'Renders the element once with no subsequent reactivity updates', 'Loads data once on mount'], 'correct' => 2],
            ['question' => 'What does the v-html directive do?', 'options' => ['Imports an HTML file', 'Renders raw HTML content inside an element', 'Escapes HTML entities', 'Defines an HTML template'], 'correct' => 1],
            ['question' => 'What attribute should be used on elements inside v-for for optimal performance?', 'options' => ['id', 'ref', 'key', 'index'], 'correct' => 2],
            ['question' => 'What is a computed property in Vue?', 'options' => ['A method called on every render', 'A cached value derived from reactive data, recalculated only when dependencies change', 'A prop with a default value', 'An asynchronous data fetcher'], 'correct' => 1],
            ['question' => 'What is the v-else-if directive used for?', 'options' => ['A CSS fallback', 'Chaining conditions after v-if', 'Looping with an else branch', 'Defining an else block in a script'], 'correct' => 1],
            ['question' => 'What does the v-pre directive do?', 'options' => ['Pre-renders on the server', 'Prefetches data', 'Skips Vue compilation for the element and its children', 'Preloads images'], 'correct' => 2],
            ['question' => 'What does v-cloak do?', 'options' => ['Hides sensitive data permanently', 'Keeps an element hidden until Vue finishes compiling, preventing flash of uncompiled template', 'Applies a cloak animation', 'Blocks event listeners'], 'correct' => 1],
            ['question' => 'What method is used to mount a Vue app to a DOM element?', 'options' => ['render()', 'attach()', 'init()', 'mount()'], 'correct' => 3],
            ['question' => 'What is the Vue devtools browser extension used for?', 'options' => ['Building Vue projects', 'Inspecting component trees, state, and events in the browser', 'Linting Vue files', 'Running unit tests'], 'correct' => 1],
        ]
    ],
    [
        'label' => 'Beginner',
        'questions' => [
            ['question' => 'What is a Vue Single File Component (SFC)?', 'options' => ['A .js file with Vue exports', 'A .vue file combining <template>, <script>, and <style> sections', 'A global Vue mixin', 'A component registered in main.js'], 'correct' => 1],
            ['question' => 'What file extension do Vue Single File Components use?', 'options' => ['.html', '.jsx', '.ts', '.vue'], 'correct' => 3],
            ['question' => 'What are props in Vue?', 'options' => ['Internal reactive data properties', 'Properties passed from a parent component to a child component', 'Event emitters', 'Computed property shortcuts'], 'correct' => 1],
            ['question' => 'How does a child component emit a custom event to its parent?', 'options' => ['By calling this.dispatch()', 'By mutating the parent\'s state directly', 'By calling this.$emit(\'eventName\', payload)', 'By calling parent.$on()'], 'correct' => 2],
            ['question' => 'What is a slot in Vue?', 'options' => ['A timed data update', 'A placeholder in a component template that accepts content from the parent', 'A scoped CSS block', 'An async data loader'], 'correct' => 1],
            ['question' => 'What is a scoped slot?', 'options' => ['A slot with scoped CSS', 'A slot that passes data from the child back to the parent\'s slot content', 'A slot only accessible within the component', 'A slot that limits re-renders'], 'correct' => 1],
            ['question' => 'What lifecycle hook runs after the component is mounted to the DOM?', 'options' => ['created', 'beforeMount', 'mounted', 'updated'], 'correct' => 2],
            ['question' => 'What lifecycle hook runs synchronously after the Vue instance is created but before mounting?', 'options' => ['beforeCreate', 'mounted', 'updated', 'created'], 'correct' => 3],
            ['question' => 'What lifecycle hook runs just before the component is unmounted in Vue 3?', 'options' => ['destroyed', 'beforeDestroy', 'beforeUnmount', 'unmounted'], 'correct' => 2],
            ['question' => 'What lifecycle hook runs after the component\'s reactive data changes and the DOM has been updated?', 'options' => ['beforeUpdate', 'updated', 'changed', 'watch'], 'correct' => 1],
            ['question' => 'What is a watcher in Vue?', 'options' => ['A component observer pattern', 'A function in the watch option that reacts to changes in a specific reactive data property', 'A performance monitor', 'An event listener directive'], 'correct' => 1],
            ['question' => 'What does the Vue CLI do?', 'options' => ['Manages CSS styles', 'A command-line tool for scaffolding, developing, and building Vue projects', 'Runs Vue on the server', 'Manages Vue state'], 'correct' => 1],
            ['question' => 'What does the <style scoped> attribute do in an SFC?', 'options' => ['Imports global styles', 'Limits the styles to only affect elements in the current component', 'Enables CSS modules', 'Applies styles to all child components'], 'correct' => 1],
            ['question' => 'What is Vite in the Vue ecosystem?', 'options' => ['A Vue state management library', 'A fast frontend build tool and dev server, the default for new Vue 3 projects', 'A Vue testing framework', 'A Vue UI component library'], 'correct' => 1],
            ['question' => 'What does the :class binding allow you to do?', 'options' => ['Import a CSS file', 'Dynamically add or remove CSS classes based on expressions', 'Bind a class constructor', 'Apply CSS animations'], 'correct' => 1],
            ['question' => 'What does the :style binding allow you to do?', 'options' => ['Link an external stylesheet', 'Dynamically apply inline styles using an object or array expression', 'Scope styles to child components', 'Enable CSS transitions'], 'correct' => 1],
            ['question' => 'How do you wrap v-if on multiple elements without adding an extra DOM node?', 'options' => ['Use a <div> with v-if', 'Use a <section> wrapper', 'Use <template v-if="...">', 'Use v-if on each element'], 'correct' => 2],
            ['question' => 'What does Vue.nextTick() do?', 'options' => ['Delays an API call', 'Runs a callback after the next DOM update cycle', 'Triggers a watcher', 'Emits a lifecycle event'], 'correct' => 1],
            ['question' => 'What is the key difference between computed properties and methods?', 'options' => ['Methods can be async, computed cannot', 'Computed properties are cached based on dependencies; methods re-execute on every render', 'Computed cannot return values', 'Methods only handle events'], 'correct' => 1],
            ['question' => 'What does the .prevent event modifier do?', 'options' => ['Stops event propagation', 'Prevents the default browser action for the event', 'Allows only one invocation', 'Prevents reactivity updates'], 'correct' => 1],
            ['question' => 'What does the .stop event modifier do?', 'options' => ['Stops all watchers', 'Stops reactivity', 'Calls event.stopPropagation()', 'Prevents the default action'], 'correct' => 2],
            ['question' => 'What does the .lazy modifier do when used with v-model?', 'options' => ['Lazy-loads the component', 'Defers syncing until the change event instead of input', 'Adds a debounce', 'Caches the value'], 'correct' => 1],
            ['question' => 'What does the .number modifier do with v-model?', 'options' => ['Formats numbers as currency', 'Automatically casts the input value to a number', 'Validates numeric input', 'Allows only integer input'], 'correct' => 1],
            ['question' => 'What does the .trim modifier do with v-model?', 'options' => ['Limits input length', 'Removes whitespace characters from the string', 'Automatically trims whitespace from the input value', 'Converts to lowercase'], 'correct' => 2],
            ['question' => 'How do you define a prop with a required type in the Options API?', 'options' => ['props: { name: String }', 'props: { name: { type: String, required: true } }', 'props: [\'name: String\']', 'props: required([String])'], 'correct' => 1],
        ]
    ],
    [
        'label' => 'Intermediate',
        'questions' => [
            ['question' => 'What is Vue Router?', 'options' => ['A Vuex plugin', 'The official client-side routing library for Vue.js', 'A server-side router', 'A navigation component library'], 'correct' => 1],
            ['question' => 'What component renders the component matched by the current route?', 'options' => ['<router-link>', '<route-view>', '<router-view>', '<navigation-outlet>'], 'correct' => 2],
            ['question' => 'What component creates a declarative navigation link in Vue Router?', 'options' => ['<a>', '<nav-link>', '<router-view>', '<router-link>'], 'correct' => 3],
            ['question' => 'What is a navigation guard in Vue Router?', 'options' => ['A CSS overlay on navigation menus', 'A function that intercepts and controls navigation (can allow, redirect, or cancel)', 'A component that guards child routes', 'A Vuex action for routing'], 'correct' => 1],
            ['question' => 'What global navigation guard runs before every route change?', 'options' => ['router.afterEach', 'router.beforeResolve', 'router.beforeEach', 'router.onError'], 'correct' => 2],
            ['question' => 'What is Vuex?', 'options' => ['A Vue 3 reactivity API', 'The official state management library for Vue 2 (and 3)', 'A Vue routing library', 'A Vue component testing tool'], 'correct' => 1],
            ['question' => 'What is Pinia?', 'options' => ['A Vue CSS framework', 'A Vue animation library', 'A Vue testing framework', 'The official state management library for Vue 3, successor to Vuex'], 'correct' => 3],
            ['question' => 'In Vuex, what is the correct way to change state?', 'options' => ['Directly via store.state.x = y', 'Through actions only', 'Through mutations via commit()', 'Through getters'], 'correct' => 2],
            ['question' => 'What is the provide / inject API used for?', 'options' => ['Providing HTTP services', 'Allowing an ancestor component to provide data that any descendant can inject', 'Configuring Vuex', 'Providing CSS variables'], 'correct' => 1],
            ['question' => 'What is a Vue mixin?', 'options' => ['A Sass mixin used in SFCs', 'A reusable object containing component options that can be merged into components', 'A Vuex plugin', 'A custom directive factory'], 'correct' => 1],
            ['question' => 'How do you register a custom directive locally in a component?', 'options' => ['In the plugins option', 'In the directives option of the component', 'Using Vue.directive() globally', 'Through the router'], 'correct' => 1],
            ['question' => 'What component wraps a single element or component to apply enter/leave transitions?', 'options' => ['<Animate>', '<Motion>', '<Transition>', '<Fade>'], 'correct' => 2],
            ['question' => 'What component wraps a list rendered by v-for to apply move and enter/leave transitions?', 'options' => ['<TransitionList>', '<AnimateGroup>', '<TransitionGroup>', '<MoveGroup>'], 'correct' => 2],
            ['question' => 'How do you define an async (lazy-loaded) component in Vue 3?', 'options' => ['Using async: true in component options', 'Using defineAsyncComponent(() => import(...))', 'Using v-async directive', 'Using import.lazy()'], 'correct' => 1],
            ['question' => 'What is a dynamic component in Vue?', 'options' => ['A component that animates automatically', 'A component rendered using <component :is="...">', 'A component with dynamic props', 'A server-rendered component'], 'correct' => 1],
            ['question' => 'What is the difference between v-if and v-show?', 'options' => ['v-if is faster', 'v-show supports expressions, v-if does not', 'v-if removes the element from the DOM; v-show uses CSS display:none', 'v-show requires a key attribute'], 'correct' => 2],
            ['question' => 'What does the <KeepAlive> component do?', 'options' => ['Keeps the Vue app alive after navigation', 'Caches component instances so their state is preserved when toggled', 'Prevents components from unmounting on error', 'Keeps reactive data after hot reload'], 'correct' => 1],
            ['question' => 'What is the difference between mixins and composables (Composition API)?', 'options' => ['Mixins are async, composables are sync', 'Mixins merge component options; composables are functions that use the Composition API for logic reuse', 'Mixins work only in Vue 3', 'Composables are deprecated'], 'correct' => 1],
            ['question' => 'What does router.push() do?', 'options' => ['Adds a new route definition', 'Programmatically navigates to a new route and adds it to the history stack', 'Pushes state to Vuex', 'Adds a navigation guard'], 'correct' => 1],
            ['question' => 'What does router.replace() do?', 'options' => ['Replaces the route configuration', 'Navigates to a new route, replacing the current history entry', 'Replaces a navigation guard', 'Reloads the current route'], 'correct' => 1],
            ['question' => 'What is a named route in Vue Router?', 'options' => ['A route with a name property used for programmatic navigation', 'A route with a unique URL segment', 'A route that requires authentication', 'A named export from the router file'], 'correct' => 0],
            ['question' => 'What are Vuex getters?', 'options' => ['Methods that commit mutations', 'Computed properties derived from the store state', 'Actions that return values', 'Properties mapped from components'], 'correct' => 1],
            ['question' => 'What is a renderless component pattern?', 'options' => ['A component with an empty template', 'A component that provides logic via scoped slots with no markup of its own', 'A component rendered server-side only', 'A component lazy-loaded at runtime'], 'correct' => 1],
            ['question' => 'What does the useRoute() composable return in Vue Router 4?', 'options' => ['The router instance', 'The current active route object', 'All registered routes', 'Navigation guards'], 'correct' => 1],
            ['question' => 'What does the useRouter() composable return in Vue Router 4?', 'options' => ['The current route', 'All route components', 'The router instance for programmatic navigation', 'Route meta information'], 'correct' => 2],
        ]
    ],
    [
        'label' => 'Advanced',
        'questions' => [
            ['question' => 'What is the Vue 3 Composition API?', 'options' => ['A plugin for composing Vue apps', 'A function-based API for organising component logic by feature rather than option type', 'A replacement for Vue Router', 'A CSS composition utility'], 'correct' => 1],
            ['question' => 'What is the setup() function?', 'options' => ['A global Vue configuration function', 'An npm setup script', 'The entry point of the Composition API executed before the component is created', 'A function that initialises Vuex'], 'correct' => 2],
            ['question' => 'What does ref() create?', 'options' => ['A DOM element reference', 'A reactive reference wrapping a value (accessed via .value)', 'A non-reactive constant', 'A computed property'], 'correct' => 1],
            ['question' => 'What does reactive() create?', 'options' => ['A readonly object', 'A reactive proxy of a plain object', 'A ref wrapping an object', 'A computed wrapper'], 'correct' => 1],
            ['question' => 'What is the key difference between ref() and reactive()?', 'options' => ['ref() is async, reactive() is sync', 'ref() is for templates only', 'ref() wraps any value type (accessed via .value); reactive() wraps objects without .value', 'reactive() works only in Vue 2'], 'correct' => 2],
            ['question' => 'How do you access a ref\'s value inside setup()?', 'options' => ['ref.get()', 'ref.val', 'ref.current', 'ref.value'], 'correct' => 3],
            ['question' => 'What does computed() return in the Composition API?', 'options' => ['A regular JavaScript function', 'A readonly reactive ref that auto-tracks its dependencies', 'A Vuex getter', 'A plain value'], 'correct' => 1],
            ['question' => 'What is the difference between watch() and watchEffect()?', 'options' => ['watchEffect is synchronous', 'watch requires explicit sources; watchEffect automatically tracks all reactive dependencies accessed inside it', 'watch is deprecated in Vue 3', 'watchEffect only runs once'], 'correct' => 1],
            ['question' => 'What is a Vue composable?', 'options' => ['A mixin for Vue 2', 'A function using the Composition API to encapsulate and reuse stateful logic', 'A Pinia store factory', 'A Vue Router plugin'], 'correct' => 1],
            ['question' => 'How do you define a Pinia store?', 'options' => ['createStore()', 'new PiniaStore()', 'defineStore(id, options)', 'Vue.use(PiniaStore)'], 'correct' => 2],
            ['question' => 'What is storeToRefs() used for in Pinia?', 'options' => ['Converting refs to a store', 'Extracting reactive refs from a Pinia store while preserving reactivity', 'Converting a store to Vuex', 'Making store actions reactive'], 'correct' => 1],
            ['question' => 'What is the Teleport component?', 'options' => ['An animation component', 'A component that renders its slot content into a different part of the DOM specified by a target selector', 'A lazy-load wrapper', 'A portal for micro-frontends'], 'correct' => 1],
            ['question' => 'What is the Suspense component?', 'options' => ['A component for handling route transitions', 'A built-in component that shows fallback content while async components or async setup() are pending', 'An error boundary component', 'A loading spinner component'], 'correct' => 1],
            ['question' => 'What are render functions in Vue?', 'options' => ['Functions that pre-render HTML on the server', 'JavaScript functions that return virtual DOM nodes (vnodes) as an alternative to templates', 'Functions that render CSS', 'Lifecycle functions that trigger re-renders'], 'correct' => 1],
            ['question' => 'What is the h() function?', 'options' => ['A CSS helper', 'A shorthand for height in styles', 'A hyperscript function that creates virtual DOM nodes', 'A HTTP utility'], 'correct' => 2],
            ['question' => 'What does onMounted() do in the Composition API?', 'options' => ['Mounts the application', 'Registers a callback to run after the component is mounted to the DOM', 'Creates a mounted ref', 'Attaches event listeners globally'], 'correct' => 1],
            ['question' => 'What does toRefs() do?', 'options' => ['Converts refs to a reactive object', 'Converts each property of a reactive object into a separate ref, preserving reactivity when destructuring', 'Creates a ref array', 'Converts computed to refs'], 'correct' => 1],
            ['question' => 'What does toRef() do?', 'options' => ['Converts any value to a ref', 'Creates a ref linked to a specific property on a reactive object', 'Converts a ref to a reactive object', 'Marks a ref as readonly'], 'correct' => 1],
            ['question' => 'What does shallowRef() do?', 'options' => ['Creates a ref with no reactivity', 'Creates a ref where only the .value swap is tracked, not deep changes inside the value', 'Creates a ref for DOM elements only', 'Creates a ref that expires'], 'correct' => 1],
            ['question' => 'What does provide() do in the Composition API?', 'options' => ['Provides a Vuex store', 'Makes a value available to all descendant components via inject()', 'Provides HTTP configuration', 'Provides global event bus'], 'correct' => 1],
            ['question' => 'What does inject() do in the Composition API?', 'options' => ['Injects a CSS class', 'Retrieves a value provided by an ancestor component via provide()', 'Injects a Vuex module', 'Injects a router instance'], 'correct' => 1],
            ['question' => 'What does defineComponent() do?', 'options' => ['Registers a component globally', 'A type-helper function that provides TypeScript inference for component options', 'Defines a standalone component', 'Creates a Pinia store component'], 'correct' => 1],
            ['question' => 'What does defineProps() do in <script setup>?', 'options' => ['Defines reactive data', 'Declares the props accepted by the component with compile-time type inference', 'Defines prop watchers', 'Creates prop validators'], 'correct' => 1],
            ['question' => 'What does defineEmits() do in <script setup>?', 'options' => ['Declares the events the component can emit for type checking and documentation', 'Attaches DOM event listeners', 'Emits all events automatically', 'Defines Vuex mutations'], 'correct' => 0],
            ['question' => 'What does <script setup> provide over the standard <script> + setup()?', 'options' => ['It runs server-side', 'Compile-time macros, less boilerplate, and better TypeScript performance for SFCs', 'It supports Vue 2 syntax', 'It enables async components by default'], 'correct' => 1],
        ]
    ],
    [
        'label' => 'Expert',
        'questions' => [
            ['question' => 'What JavaScript feature underpins Vue 3\'s reactivity system?', 'options' => ['WeakMap', 'Object.defineProperty', 'ES6 Proxy', 'Symbol'], 'correct' => 2],
            ['question' => 'How does Vue 3 reactivity differ from Vue 2 reactivity?', 'options' => ['Vue 3 uses a compiler, Vue 2 does not', 'Vue 3 uses ES6 Proxy enabling reactivity on new properties; Vue 2 used Object.defineProperty requiring explicit $set', 'Vue 3 is synchronous, Vue 2 is async', 'Vue 2 had Proxy support'], 'correct' => 1],
            ['question' => 'What is the virtual DOM in Vue?', 'options' => ['A virtual machine running Vue', 'A JavaScript representation of the real DOM that Vue diffs to compute minimal real DOM updates', 'A cached copy of the real DOM', 'A DOM running in a Web Worker'], 'correct' => 1],
            ['question' => 'What is the patch algorithm (diffing) responsible for?', 'options' => ['Applying CSS patches', 'Comparing new and old virtual DOM trees to determine the minimal set of real DOM changes', 'Patching npm packages', 'Syncing server and client DOM'], 'correct' => 1],
            ['question' => 'What is Vue\'s custom renderer API used for?', 'options' => ['Customising the Vue CLI output', 'Creating Vue renderers targeting non-DOM environments like Canvas, WebGL, or native mobile', 'Customising server responses', 'Overriding the virtual DOM algorithm'], 'correct' => 1],
            ['question' => 'What function creates a custom Vue renderer?', 'options' => ['defineRenderer()', 'createRenderer()', 'buildRenderer()', 'makeRenderer()'], 'correct' => 1],
            ['question' => 'What is hydration in the context of Vue SSR?', 'options' => ['Adding water animations to Vue apps', 'Attaching Vue\'s reactivity and event listeners to server-rendered HTML on the client', 'Injecting CSS styles post-render', 'Loading data into the Vuex store'], 'correct' => 1],
            ['question' => 'What is Nuxt.js?', 'options' => ['A Vue CSS framework', 'A Vue UI component library', 'A Vue plugin manager', 'A Vue meta-framework providing SSR, SSG, file-based routing, and full-stack capabilities'], 'correct' => 3],
            ['question' => 'What does SSG (Static Site Generation) mean in Nuxt?', 'options' => ['Server-side GraphQL', 'Style Sheet Generator', 'Generating all pages as static HTML files at build time', 'Structured Script Generation'], 'correct' => 2],
            ['question' => 'What is the useFetch composable in Nuxt 3?', 'options' => ['A Nuxt alias for fetch()', 'A universal data-fetching composable that works on both server and client with SSR support', 'A Pinia action helper', 'A Vue Router fetch hook'], 'correct' => 1],
            ['question' => 'What does code splitting do for Vue application performance?', 'options' => ['Splits the CSS from the JS', 'Divides the bundle into smaller chunks loaded on demand, reducing initial load time', 'Splits components across multiple files', 'Separates test code from production code'], 'correct' => 1],
            ['question' => 'What does the v-memo directive do?', 'options' => ['Memoises a method', 'Caches a template sub-tree and skips updates until listed dependencies change', 'Adds a memo comment to the DOM', 'Creates a Pinia memo getter'], 'correct' => 1],
            ['question' => 'What is the recommended testing framework for Vue 3 unit tests?', 'options' => ['Jasmine', 'Karma', 'Jest with Enzyme', 'Vitest'], 'correct' => 3],
            ['question' => 'What is Vue Test Utils?', 'options' => ['A Vue CLI plugin for testing', 'The official utility library for unit testing Vue components, providing mount and shallowMount', 'A Vitest extension', 'A browser automation tool for Vue'], 'correct' => 1],
            ['question' => 'What does shallowMount() do in Vue Test Utils?', 'options' => ['Mounts without the DOM', 'Mounts the component with all child components stubbed out', 'Partially mounts the component', 'Mounts on a shallow clone of the DOM'], 'correct' => 1],
            ['question' => 'What does markRaw() do?', 'options' => ['Marks a ref as readonly', 'Marks an object so it is never converted to a reactive proxy', 'Marks template nodes as raw HTML', 'Disables prop validation'], 'correct' => 1],
            ['question' => 'What does effectScope() provide?', 'options' => ['Scopes CSS effects to a component', 'A scope to create reactive effects that can all be stopped together with a single stop() call', 'A scoped event bus', 'A Pinia store scope'], 'correct' => 1],
            ['question' => 'What does triggerRef() do?', 'options' => ['Triggers a DOM ref', 'Forces watchers of a shallowRef to run even when .value hasn\'t been replaced', 'Triggers all watchers in the app', 'Re-renders a component'], 'correct' => 1],
            ['question' => 'What is Module Federation in the context of Vue micro-frontends?', 'options' => ['Vue Router\'s module loader', 'A Webpack 5 feature for sharing code and components between separately deployed applications at runtime', 'Vuex module loading', 'A Vite plugin for code splitting'], 'correct' => 1],
            ['question' => 'How does Vue 3 achieve better tree shaking compared to Vue 2?', 'options' => ['Vue 3 uses a smaller runtime', 'Vue 3 exposes all APIs as named exports so bundlers can eliminate unused code', 'Vue 3 compresses its bundle', 'Vue 3 splits the runtime automatically'], 'correct' => 1],
            ['question' => 'What is the purpose of the @vue/compiler-sfc package?', 'options' => ['Compiles Vue apps for server-side rendering', 'Parses and compiles Vue Single File Components (.vue files) used by build tools', 'Provides TypeScript support', 'Optimises CSS in SFCs'], 'correct' => 1],
            ['question' => 'What does defineExpose() do in <script setup>?', 'options' => ['Exposes private data globally', 'Explicitly exposes selected properties so parent components can access them via template refs', 'Exports the component as a module', 'Exposes Vuex mutations'], 'correct' => 1],
            ['question' => 'What is the onServerPrefetch() composable used for in SSR?', 'options' => ['Prefetching assets on the server', 'Registering an async function that must resolve before the component is server-rendered', 'Prefetching routes on the server', 'Caching server responses'], 'correct' => 1],
            ['question' => 'What does customRef() allow you to do?', 'options' => ['Create a ref with a custom DOM element', 'Create a ref with explicit control over its dependency tracking and update triggering', 'Define a ref alias', 'Create a persistent ref that survives hot reload'], 'correct' => 1],
            ['question' => 'What Vue 3 compiler optimisation emits static tree hoisting?', 'options' => ['Dynamic node patching', 'Moving static vnodes outside the render function so they are created once and reused', 'Inlining all computed values', 'Removing event listeners from static nodes'], 'correct' => 1],
        ]
    ],
];
require_once __DIR__ . '/quiz-engine.php';
