<?php
$page_title = 'XML Quiz – 100 Levels – CodeFoundry';
$active_page = 'training';
$quiz_title  = 'XML';
$quiz_slug   = 'xml';
$quiz_tiers  = [
    [
        'label' => 'Introduction',
        'questions' => [
            ['question' => 'What does XML stand for?', 'options' => ['eXtreme Markup Language', 'Extensible Markup Language', 'eXtra Modern Language', 'eXecutable Markup Language'], 'correct' => 1],
            ['question' => 'What is the primary purpose of XML?', 'options' => ['Styling web pages', 'Storing and transporting data', 'Programming logic', 'Creating animations'], 'correct' => 1],
            ['question' => 'How does XML differ from HTML?', 'options' => ['No difference', 'XML is for data, HTML for display', 'XML is faster', 'XML is older'], 'correct' => 1],
            ['question' => 'What is the correct XML declaration?', 'options' => ['<xml version="1.0">', '<?xml version="1.0"?>', '<!xml version="1.0">', '<xml>'], 'correct' => 1],
            ['question' => 'What encoding is default in XML?', 'options' => ['ASCII', 'UTF-8', 'ISO-8859-1', 'UTF-16'], 'correct' => 1],
            ['question' => 'What is an XML element?', 'options' => ['Attribute', 'Content between opening and closing tags', 'Comment', 'Declaration'], 'correct' => 1],
            ['question' => 'What is an XML attribute?', 'options' => ['Element content', 'Name-value pair in opening tag', 'Comment', 'Namespace'], 'correct' => 1],
            ['question' => 'Are XML tags case-sensitive?', 'options' => ['No', 'Yes', 'Only attributes', 'Only elements'], 'correct' => 1],
            ['question' => 'Must all XML tags be closed?', 'options' => ['No', 'Yes', 'Only parent tags', 'Optional'], 'correct' => 1],
            ['question' => 'What is proper XML nesting?', 'options' => ['Any order', 'Inner elements close before outer', 'Outer before inner', 'No nesting'], 'correct' => 1],
            ['question' => 'How many root elements can XML have?', 'options' => ['Multiple', 'Exactly one', 'Zero', 'Unlimited'], 'correct' => 1],
            ['question' => 'Must XML attributes be quoted?', 'options' => ['No', 'Yes', 'Optional', 'Only strings'], 'correct' => 1],
            ['question' => 'How do you write XML comments?', 'options' => ['// comment', '/* comment */', '<!-- comment -->', '# comment'], 'correct' => 2],
            ['question' => 'What is a CDATA section?', 'options' => ['Character data', 'Section where content not parsed', 'Comment block', 'Data type'], 'correct' => 1],
            ['question' => 'How do you write CDATA?', 'options' => ['<CDATA>...</CDATA>', '<![CDATA[...]]>', '<!--CDATA...-->', '{CDATA...}'], 'correct' => 1],
            ['question' => 'What is XML tree structure?', 'options' => ['Forest', 'Hierarchical parent-child relationships', 'Linear list', 'Network graph'], 'correct' => 1],
            ['question' => 'What is a parent element?', 'options' => ['First element', 'Element containing other elements', 'Root element', 'Last element'], 'correct' => 1],
            ['question' => 'What is a child element?', 'options' => ['Small element', 'Element contained within another', 'Last element', 'Leaf element'], 'correct' => 1],
            ['question' => 'What are sibling elements?', 'options' => ['Related elements', 'Elements at same level with same parent', 'Adjacent elements', 'Nested elements'], 'correct' => 1],
            ['question' => 'What is xmlns attribute for?', 'options' => ['XML name', 'Declaring namespace', 'Naming element', 'XML source'], 'correct' => 1],
            ['question' => 'What is well-formed XML?', 'options' => ['Valid XML', 'XML following syntax rules', 'Formatted XML', 'Complete XML'], 'correct' => 1],
            ['question' => 'What is valid XML?', 'options' => ['Same as well-formed', 'Well-formed and conforms to schema', 'Correct syntax', 'Has declaration'], 'correct' => 1],
            ['question' => 'What is XML prolog?', 'options' => ['Introduction', 'Declaration and optional processing instructions', 'First element', 'Comment'], 'correct' => 1],
            ['question' => 'What does &amp; represent?', 'options' => ['@', '&', 'and', 'ampersand symbol'], 'correct' => 1],
            ['question' => 'What does &lt; represent?', 'options' => ['>', '<', 'less than', 'left'], 'correct' => 1],
            ['question' => 'What does &gt; represent?', 'options' => ['<', '>', 'greater than', 'right'], 'correct' => 1],
            ['question' => 'What does &apos; represent?', 'options' => ['Apostrophe', 'Single quote', 'Both A and B', 'Double quote'], 'correct' => 2],
            ['question' => 'What does &quot; represent?', 'options' => ['Single quote', 'Double quote', 'Quotation', 'Question mark'], 'correct' => 1],
            ['question' => 'How is whitespace handled in XML?', 'options' => ['Ignored', 'Preserved', 'Trimmed', 'Collapsed'], 'correct' => 1],
            ['question' => 'What is a processing instruction?', 'options' => ['Instruction for application', 'Command for XML processor', 'Comment type', 'Element type'], 'correct' => 1],
            ['question' => 'How are processing instructions written?', 'options' => ['<? ... ?>', '<!-- ... -->', '<! ... >', '{ ... }'], 'correct' => 0],
            ['question' => 'Can XML contain empty elements?', 'options' => ['No', 'Yes', 'Only with content', 'Not recommended'], 'correct' => 1],
            ['question' => 'What is self-closing tag syntax?', 'options' => ['<element>', '<element/>', '<element><element/>', '</element>'], 'correct' => 1],
        ]
    ],
    [
        'label' => 'Beginner',
        'questions' => [
            ['question' => 'What is a default namespace?', 'options' => ['Built-in namespace', 'Namespace without prefix', 'Primary namespace', 'Root namespace'], 'correct' => 1],
            ['question' => 'How do you declare prefixed namespace?', 'options' => ['xmlns:prefix="URI"', 'prefix:xmlns="URI"', 'namespace:prefix="URI"', 'ns:prefix="URI"'], 'correct' => 0],
            ['question' => 'What is namespace scope?', 'options' => ['All document', 'Element and descendants where declared', 'Current element only', 'Root only'], 'correct' => 1],
            ['question' => 'What does DTD stand for?', 'options' => ['Data Type Definition', 'Document Type Definition', 'Dynamic Type Declaration', 'Document Template Design'], 'correct' => 1],
            ['question' => 'Where can DTD be declared?', 'options' => ['Only internal', 'Only external', 'Internal, external, or both', 'Separate file only'], 'correct' => 2],
            ['question' => 'What is <!DOCTYPE> for?', 'options' => ['Declaring document type', 'Defining document type and DTD reference', 'Document comment', 'Type validation'], 'correct' => 1],
            ['question' => 'What is <!ELEMENT> in DTD?', 'options' => ['Creates element', 'Declares element structure', 'Validates element', 'Element type'], 'correct' => 1],
            ['question' => 'What is <!ATTLIST> in DTD?', 'options' => ['Attribute array', 'Declares attributes for element', 'Lists elements', 'Attribute values'], 'correct' => 1],
            ['question' => 'What is <!ENTITY> in DTD?', 'options' => ['Entity object', 'Defines reusable content', 'Creates entity', 'Entity type'], 'correct' => 1],
            ['question' => 'What does EMPTY mean in DTD?', 'options' => ['No value', 'Element has no content', 'Empty string', 'Null value'], 'correct' => 1],
            ['question' => 'What does ANY mean in DTD?', 'options' => ['Any value', 'Element can contain any content', 'Any type', 'Optional'], 'correct' => 1],
            ['question' => 'What does #PCDATA mean in DTD?', 'options' => ['Parsed character data', 'Plain character data', 'Primary content data', 'Protected character data'], 'correct' => 0],
            ['question' => 'What does (element1,element2) mean in DTD?', 'options' => ['Either element', 'Sequence: element1 then element2', 'Both elements', 'Choice'], 'correct' => 1],
            ['question' => 'What does (element1|element2) mean in DTD?', 'options' => ['Both elements', 'Choice: element1 or element2', 'Sequence', 'Neither'], 'correct' => 1],
            ['question' => 'What does ? mean in DTD?', 'options' => ['Question', 'Zero or one occurrence', 'Optional', 'Unknown'], 'correct' => 1],
            ['question' => 'What does * mean in DTD?', 'options' => ['Required', 'Zero or more occurrences', 'Any', 'Wildcard'], 'correct' => 1],
            ['question' => 'What does + mean in DTD?', 'options' => ['Optional', 'One or more occurrences', 'Addition', 'Multiple'], 'correct' => 1],
            ['question' => 'What is CDATA attribute type?', 'options' => ['CDATA section', 'Character data', 'Complex data', 'Content data'], 'correct' => 1],
            ['question' => 'What is ID attribute type?', 'options' => ['Identifier', 'Unique identifier', 'ID number', 'Element ID'], 'correct' => 1],
            ['question' => 'What is IDREF attribute type?', 'options' => ['ID reference', 'Reference to ID value', 'Referenced ID', 'ID pointer'], 'correct' => 1],
            ['question' => 'What is REQUIRED in DTD?', 'options' => ['Must exist', 'Attribute must be present', 'Mandatory element', 'Not optional'], 'correct' => 1],
            ['question' => 'What is IMPLIED in DTD?', 'options' => ['Suggested', 'Attribute is optional', 'Default behavior', 'Implied value'], 'correct' => 1],
            ['question' => 'What is FIXED in DTD?', 'options' => ['Cannot change', 'Attribute has fixed value', 'Constant', 'Immutable'], 'correct' => 1],
            ['question' => 'What is XML Schema (XSD)?', 'options' => ['XML structure', 'More powerful alternative to DTD', 'XML format', 'Schema language'], 'correct' => 1],
            ['question' => 'What is xs:schema root element?', 'options' => ['Schema element', 'Root element of XSD document', 'Schema type', 'XML root'], 'correct' => 1],
            ['question' => 'What is xs:element?', 'options' => ['Element type', 'Declares element in schema', 'XML element', 'Schema component'], 'correct' => 1],
            ['question' => 'What is xs:complexType?', 'options' => ['Complex element', 'Element containing children/attributes', 'Advanced type', 'Nested structure'], 'correct' => 1],
            ['question' => 'What is xs:simpleType?', 'options' => ['Simple element', 'Element with only text content', 'Basic type', 'Plain text'], 'correct' => 1],
            ['question' => 'What is xs:sequence?', 'options' => ['Order', 'Child elements in specific order', 'Sequential', 'Array'], 'correct' => 1],
            ['question' => 'What is xs:string?', 'options' => ['Text type', 'String data type', 'Character sequence', 'Text content'], 'correct' => 1],
            ['question' => 'What is xs:integer?', 'options' => ['Number type', 'Integer data type', 'Whole number', 'Numeric value'], 'correct' => 1],
            ['question' => 'What is XPath?', 'options' => ['XML path', 'Language for navigating XML', 'Path expression', 'Query language'], 'correct' => 1],
            ['question' => 'What does // select in XPath?', 'options' => ['Root', 'Descendants anywhere', 'All elements', 'Comments'], 'correct' => 1],
            ['question' => 'What does . mean in XPath?', 'options' => ['Root', 'Current node', 'Any node', 'Separator'], 'correct' => 1],
            ['question' => 'What does .. mean in XPath?', 'options' => ['Root', 'Parent node', 'Previous node', 'Ancestor'], 'correct' => 1],
            ['question' => 'What does @ mean in XPath?', 'options' => ['At', 'Attribute', 'Any', 'All'], 'correct' => 1],
            ['question' => 'What is XSLT?', 'options' => ['XML style', 'Language for transforming XML', 'Template language', 'Styling tool'], 'correct' => 1],
            ['question' => 'What is xsl:stylesheet?', 'options' => ['Style sheet', 'Root element of XSLT', 'CSS for XML', 'Styling element'], 'correct' => 1],
            ['question' => 'What is xsl:template?', 'options' => ['Template element', 'Defines transformation rule', 'Pattern match', 'Output template'], 'correct' => 1],
            ['question' => 'What is xsl:value-of?', 'options' => ['Gets value', 'Extracts and outputs node value', 'Value selector', 'Output value'], 'correct' => 1],
            ['question' => 'What is xsl:for-each?', 'options' => ['Loop', 'Iterates over node set', 'For loop', 'Repetition'], 'correct' => 1],
            ['question' => 'How do browsers parse XML?', 'options' => ['Like HTML', 'Using XML parser', 'Same as text', 'As DOM tree'], 'correct' => 3],
            ['question' => 'What is DOMParser in JavaScript?', 'options' => ['DOM builder', 'Parses XML string into DOM', 'XML converter', 'Parser object'], 'correct' => 1],
            ['question' => 'What is XMLSerializer?', 'options' => ['Saves XML', 'Converts DOM to XML string', 'Serializes data', 'XML converter'], 'correct' => 1],
            ['question' => 'Can XML be used for configuration files?', 'options' => ['No', 'Yes', 'Only simple configs', 'Not recommended'], 'correct' => 1],
        ]
    ],
    [
        'label' => 'Intermediate',
        'questions' => [
            ['question' => 'What is xs:restriction?', 'options' => ['Access control', 'Restricts base type values', 'Validation rule', 'Limited type'], 'correct' => 1],
            ['question' => 'What is xs:extension?', 'options' => ['File extension', 'Extends base type', 'Add-on', 'Enhanced type'], 'correct' => 1],
            ['question' => 'What is xs:complexContent?', 'options' => ['Complex element', 'Contains extensions/restrictions of complex type', 'Nested content', 'Advanced structure'], 'correct' => 1],
            ['question' => 'What is xs:simpleContent?', 'options' => ['Simple element', 'Complex type with only text and attributes', 'Plain text', 'Basic content'], 'correct' => 1],
            ['question' => 'What is xs:attribute in schema?', 'options' => ['Element attribute', 'Declares attribute', 'Attribute type', 'Property'], 'correct' => 1],
            ['question' => 'What is xs:attributeGroup?', 'options' => ['Grouped attributes', 'Reusable set of attributes', 'Attribute collection', 'Attribute set'], 'correct' => 1],
            ['question' => 'What is xs:choice?', 'options' => ['Selection', 'One of several elements', 'Option', 'Alternative'], 'correct' => 1],
            ['question' => 'What is xs:all?', 'options' => ['All elements', 'Elements in any order', 'Everything', 'Complete set'], 'correct' => 1],
            ['question' => 'What is xs:group?', 'options' => ['Element group', 'Reusable group of elements', 'Collection', 'Element set'], 'correct' => 1],
            ['question' => 'What is xs:import?', 'options' => ['Import file', 'Imports schema from different namespace', 'Include schema', 'External reference'], 'correct' => 1],
            ['question' => 'What is xs:include?', 'options' => ['Include file', 'Includes schema from same namespace', 'Import', 'Schema reference'], 'correct' => 1],
            ['question' => 'What is xs:minOccurs?', 'options' => ['Minimum value', 'Minimum number of occurrences', 'Lower bound', 'Min count'], 'correct' => 1],
            ['question' => 'What is xs:maxOccurs?', 'options' => ['Maximum value', 'Maximum number of occurrences', 'Upper bound', 'Max count'], 'correct' => 1],
            ['question' => 'What is xs:key?', 'options' => ['Key attribute', 'Defines unique key', 'Primary key', 'Identifier'], 'correct' => 1],
            ['question' => 'What is xs:unique?', 'options' => ['Unique element', 'Defines unique constraint', 'Distinct values', 'No duplicates'], 'correct' => 1],
            ['question' => 'What is xs:keyref?', 'options' => ['Key reference', 'References key constraint', 'Foreign key', 'Key pointer'], 'correct' => 1],
            ['question' => 'What is string-length() in XPath 2.0?', 'options' => ['String size', 'Returns string length', 'Count characters', 'Length function'], 'correct' => 1],
            ['question' => 'What does concat() do in XPath?', 'options' => ['Combines', 'Concatenates strings', 'Joins', 'Merges strings'], 'correct' => 1],
            ['question' => 'What does substring() do in XPath?', 'options' => ['Extracts substring', 'Returns part of string', 'String portion', 'Sub string'], 'correct' => 1],
            ['question' => 'What does contains() do in XPath?', 'options' => ['Includes', 'Tests if string contains substring', 'Has content', 'String search'], 'correct' => 1],
            ['question' => 'What does starts-with() do in XPath?', 'options' => ['Begins', 'Tests if string starts with substring', 'Prefix check', 'Starting string'], 'correct' => 1],
            ['question' => 'What does upper-case() do in XPath 2.0?', 'options' => ['Capitalizes', 'Converts to uppercase', 'Makes upper', 'Capital letters'], 'correct' => 1],
            ['question' => 'What does count() do in XPath?', 'options' => ['Counts elements', 'Returns number of nodes', 'Node count', 'Total nodes'], 'correct' => 1],
            ['question' => 'What does sum() do in XPath?', 'options' => ['Adds values', 'Returns sum of node values', 'Total', 'Addition'], 'correct' => 1],
            ['question' => 'What is xsl:function in XSLT 2.0?', 'options' => ['Function call', 'Defines user function', 'Custom function', 'Function declaration'], 'correct' => 1],
            ['question' => 'What is xsl:variable?', 'options' => ['Variable element', 'Declares variable', 'Data storage', 'Variable binding'], 'correct' => 1],
            ['question' => 'What is xsl:param?', 'options' => ['Parameter', 'Declares parameter', 'Input value', 'Function argument'], 'correct' => 1],
            ['question' => 'What is xsl:sort?', 'options' => ['Sorts data', 'Sorts output', 'Orders nodes', 'Arranges elements'], 'correct' => 1],
            ['question' => 'What is xsl:copy?', 'options' => ['Copies all', 'Copies current node', 'Duplicates', 'Clones node'], 'correct' => 1],
            ['question' => 'What is xsl:copy-of?', 'options' => ['Copies content', 'Copies node and descendants', 'Deep copy', 'Full copy'], 'correct' => 1],
            ['question' => 'What is XQuery?', 'options' => ['XML query', 'Query language for XML', 'Search language', 'XML SQL'], 'correct' => 1],
            ['question' => 'What is Canonical XML?', 'options' => ['Standard XML', 'Normalized form of XML', 'Official XML', 'Regular XML'], 'correct' => 1],
            ['question' => 'What is XML Signature?', 'options' => ['Author name', 'Digital signature for XML', 'XML footer', 'Authentication'], 'correct' => 1],
            ['question' => 'What is XML Encryption?', 'options' => ['Secure XML', 'Encrypting XML content', 'Protected XML', 'Secure data'], 'correct' => 1],
            ['question' => 'What is SVG?', 'options' => ['Super Vector Graphics', 'Scalable Vector Graphics (XML-based)', 'Saved Vector Graphics', 'Simple Vector Graphics'], 'correct' => 1],
            ['question' => 'Is SVG based on XML?', 'options' => ['No', 'Yes', 'Partially', 'Similar format'], 'correct' => 1],
            ['question' => 'What is MathML?', 'options' => ['Math Markup Language (XML-based)', 'Mathematical Logic', 'Math Library', 'Math Module'], 'correct' => 0],
            ['question' => 'What is XHTML?', 'options' => ['Extended HTML', 'HTML as XML', 'New HTML', 'XML HTML'], 'correct' => 1],
            ['question' => 'How does XHTML differ from HTML?', 'options' => ['No difference', 'XHTML follows XML rules', 'XHTML is older', 'XHTML is simpler'], 'correct' => 1],
            ['question' => 'Can you mix namespaces in XML?', 'options' => ['No', 'Yes', 'Only two', 'Not recommended'], 'correct' => 1],
            ['question' => 'What happens with namespace conflicts?', 'options' => ['Error', 'Resolved by prefix', 'Ignored', 'Warning'], 'correct' => 1],
            ['question' => 'What is default namespace scope?', 'options' => ['Global', 'Element and descendants', 'Document', 'Root only'], 'correct' => 1],
            ['question' => 'Can attributes have namespaces?', 'options' => ['No', 'Yes', 'Only elements', 'Optional'], 'correct' => 1],
            ['question' => 'What is xmlns attribute type?', 'options' => ['String', 'Special attribute', 'Namespace', 'Reserved'], 'correct' => 3],
            ['question' => 'Is XML widely used today?', 'options' => ['No', 'Yes, in enterprise and legacy systems', 'Obsolete', 'Replaced by JSON'], 'correct' => 1],
        ]
    ],
    [
        'label' => 'Advanced',
        'questions' => [
            ['question' => 'What is XML infoset?', 'options' => ['Information set', 'Abstract description of XML information', 'XML structure', 'Data model'], 'correct' => 1],
            ['question' => 'What is XML data model?', 'options' => ['Schema', 'Abstract representation of XML structure', 'Data structure', 'XML format'], 'correct' => 1],
            ['question' => 'What is DOM Level 2?', 'options' => ['Version 2', 'DOM specification version', 'Second level', 'DOM update'], 'correct' => 1],
            ['question' => 'What is Document interface in DOM?', 'options' => ['Document type', 'Represents entire XML document', 'Document object', 'Root interface'], 'correct' => 1],
            ['question' => 'What is Element interface in DOM?', 'options' => ['Element type', 'Represents XML element', 'Element object', 'Node type'], 'correct' => 1],
            ['question' => 'What is NodeList in DOM?', 'options' => ['List of nodes', 'Collection of nodes', 'Node array', 'Node set'], 'correct' => 1],
            ['question' => 'What is TreeWalker?', 'options' => ['Tree navigator', 'Traverses document tree', 'Tree iterator', 'Node walker'], 'correct' => 1],
            ['question' => 'What is SAX parser?', 'options' => ['Fast parser', 'Event-based streaming parser', 'Simple parser', 'Sequential parser'], 'correct' => 1],
            ['question' => 'What is startElement event in SAX?', 'options' => ['Element start', 'Fired when element starts', 'Open tag', 'Begin element'], 'correct' => 1],
            ['question' => 'What is endElement event in SAX?', 'options' => ['Element end', 'Fired when element ends', 'Close tag', 'Finish element'], 'correct' => 1],
            ['question' => 'What is characters event in SAX?', 'options' => ['Text content', 'Fired for character data', 'Text event', 'Content event'], 'correct' => 1],
            ['question' => 'What is advantage of SAX over DOM?', 'options' => ['Faster', 'Less memory for large files', 'Simpler', 'Better API'], 'correct' => 1],
            ['question' => 'What is StAX?', 'options' => ['Streaming API', 'Streaming API for XML', 'Stack parser', 'State parser'], 'correct' => 1],
            ['question' => 'What is XMLStreamReader?', 'options' => ['Stream reader', 'Pull parser for reading XML', 'Reader object', 'Input stream'], 'correct' => 1],
            ['question' => 'What is XMLStreamWriter?', 'options' => ['Stream writer', 'Writes XML stream', 'Writer object', 'Output stream'], 'correct' => 1],
            ['question' => 'What is JAXB?', 'options' => ['Java API', 'Java Architecture for XML Binding', 'Java XML library', 'Binding framework'], 'correct' => 1],
            ['question' => 'What is @XmlRootElement?', 'options' => ['Root annotation', 'Maps class to XML root element', 'Element marker', 'Root tag'], 'correct' => 1],
            ['question' => 'What does JAXB marshal() do?', 'options' => ['Parses XML', 'Converts object to XML', 'Serializes', 'Exports'], 'correct' => 1],
            ['question' => 'What does JAXB unmarshal() do?', 'options' => ['Converts XML to object', 'Parses XML', 'Deserializes', 'Imports'], 'correct' => 0],
            ['question' => 'What is XML Pull Parsing?', 'options' => ['Pull method', 'Application controls parsing flow', 'Extract parsing', 'Pull API'], 'correct' => 1],
            ['question' => 'What is START_ELEMENT event?', 'options' => ['Element start', 'Indicates element opening', 'Begin tag', 'Open element'], 'correct' => 1],
            ['question' => 'What is END_ELEMENT event?', 'options' => ['Element end', 'Indicates element closing', 'End tag', 'Close element'], 'correct' => 1],
            ['question' => 'What is CHARACTERS event?', 'options' => ['Text data', 'Indicates character content', 'Text event', 'Content data'], 'correct' => 1],
            ['question' => 'What is derivation by restriction in XSD?', 'options' => ['Limiting type', 'Restricting base type values', 'Validation', 'Constraint'], 'correct' => 1],
            ['question' => 'What is derivation by extension in XSD?', 'options' => ['Adding to type', 'Extending base type', 'Enhancement', 'Augmentation'], 'correct' => 1],
            ['question' => 'What is Schematron?', 'options' => ['Schema type', 'Rule-based validation language', 'Schema tool', 'Validation framework'], 'correct' => 1],
            ['question' => 'What is Relax NG?', 'options' => ['Relaxed schema', 'Alternative schema language', 'Schema format', 'NG schema'], 'correct' => 1],
            ['question' => 'What is XML Catalog?', 'options' => ['XML list', 'Maps public IDs to local resources', 'Registry', 'Reference system'], 'correct' => 1],
            ['question' => 'What is SOAP?', 'options' => ['Protocol', 'XML-based messaging protocol', 'Web service', 'Communication format'], 'correct' => 1],
            ['question' => 'What is SOAP Envelope?', 'options' => ['Container', 'Root element of SOAP message', 'Wrapper', 'Message structure'], 'correct' => 1],
            ['question' => 'What is SOAP Body?', 'options' => ['Content', 'Contains actual message', 'Payload', 'Message data'], 'correct' => 1],
            ['question' => 'What is SOAP Fault?', 'options' => ['Error', 'Error information element', 'Exception', 'Failure message'], 'correct' => 1],
            ['question' => 'What is WSDL?', 'options' => ['Web Service Description Language', 'XML format describing web service', 'Service definition', 'Interface description'], 'correct' => 1],
            ['question' => 'What is XML Digital Signature?', 'options' => ['Signature', 'XMLDSig standard', 'Authentication', 'Signing method'], 'correct' => 1],
            ['question' => 'What is XML Encryption standard?', 'options' => ['Encryption', 'XMLEnc standard', 'Security', 'Encryption method'], 'correct' => 1],
            ['question' => 'When to use DOM vs SAX?', 'options' => ['Always DOM', 'DOM for small files, SAX for large', 'Always SAX', 'No difference'], 'correct' => 1],
            ['question' => 'When to use StAX?', 'options' => ['Never', 'When you need pull parsing control', 'Always', 'Small files only'], 'correct' => 1],
            ['question' => 'What is advantage of StAX over SAX?', 'options' => ['Faster', 'More control over parsing', 'Simpler', 'Less memory'], 'correct' => 1],
            ['question' => 'Can you modify XML with SAX?', 'options' => ['Yes', 'No, read-only', 'With extensions', 'Only attributes'], 'correct' => 1],
            ['question' => 'Can you modify XML with DOM?', 'options' => ['No', 'Yes', 'Only read', 'Only create'], 'correct' => 1],
            ['question' => 'What is namespace-aware parsing?', 'options' => ['Aware of namespaces', 'Parser processes namespaces', 'Namespace validation', 'NS support'], 'correct' => 1],
            ['question' => 'What happens if parser not namespace-aware?', 'options' => ['Error', 'Namespaces treated as regular attributes', 'Ignored', 'Warning'], 'correct' => 1],
            ['question' => 'What is XML external entity?', 'options' => ['External file', 'Entity referencing external resource', 'Remote data', 'Outside entity'], 'correct' => 1],
            ['question' => 'What are processing instructions used for?', 'options' => ['Instructions', 'Passing info to applications', 'Commands', 'Configuration'], 'correct' => 1],
            ['question' => 'Can XML have multiple encoding declarations?', 'options' => ['Yes', 'No, only one in prolog', 'Multiple times', 'Per element'], 'correct' => 1],
        ]
    ],
    [
        'label' => 'Expert',
        'questions' => [
            ['question' => 'What is VTD-XML?', 'options' => ['Virtual Tree', 'Virtual Token Descriptor for XML', 'Vector XML', 'Variable Tree Data'], 'correct' => 1],
            ['question' => 'What is advantage of VTD-XML?', 'options' => ['Faster parsing', 'Memory efficient without full tree', 'Better API', 'Simpler code'], 'correct' => 1],
            ['question' => 'What is XML Bomb attack?', 'options' => ['Malware', 'Billion laughs DoS attack', 'Virus', 'Exploit'], 'correct' => 1],
            ['question' => 'How does billion laughs attack work?', 'options' => ['Many entities', 'Nested entity expansions causing exponential growth', 'Large file', 'Recursive data'], 'correct' => 1],
            ['question' => 'How to prevent XML Bomb?', 'options' => ['Validation', 'Limit entity expansion depth/size', 'Strong parser', 'Firewall'], 'correct' => 1],
            ['question' => 'What is XXE vulnerability?', 'options' => ['XML exploit', 'XML External Entity injection', 'XML error', 'External attack'], 'correct' => 1],
            ['question' => 'How does XXE attack work?', 'options' => ['Inject code', 'Reference malicious external entities', 'Break parser', 'Overflow'], 'correct' => 1],
            ['question' => 'How to prevent XXE?', 'options' => ['Validation', 'Disable external entity processing', 'Strong schema', 'Encryption'], 'correct' => 1],
            ['question' => 'What is difference between namespace-aware and non-aware?', 'options' => ['Speed', 'How namespaces are processed', 'Features', 'API'], 'correct' => 1],
            ['question' => 'What is schema-aware XSLT?', 'options' => ['Has schema', 'XSLT with schema type information', 'Validates', 'Schema support'], 'correct' => 1],
            ['question' => 'What is xsl:stream in XSLT 3.0?', 'options' => ['Stream data', 'Streaming transformation', 'Output stream', 'Data flow'], 'correct' => 1],
            ['question' => 'What is xsl:accumulator?', 'options' => ['Accumulates values', 'Maintains state during streaming', 'Counter', 'Variable storage'], 'correct' => 1],
            ['question' => 'What is XQuery Update Facility?', 'options' => ['Update tool', 'Extension for modifying XML', 'Update syntax', 'Modification API'], 'correct' => 1],
            ['question' => 'What is BaseX?', 'options' => ['Base library', 'Native XML database', 'XML tool', 'Query engine'], 'correct' => 1],
            ['question' => 'What is eXist-db?', 'options' => ['Existing database', 'Native XML database', 'XML store', 'Database system'], 'correct' => 1],
            ['question' => 'What is native XML storage?', 'options' => ['Original storage', 'Database stores XML natively', 'XML format', 'Direct storage'], 'correct' => 1],
            ['question' => 'What is XMLType in Oracle?', 'options' => ['XML data type', 'Native XML type in Oracle', 'Type definition', 'XML column'], 'correct' => 1],
            ['question' => 'What is xml type in PostgreSQL?', 'options' => ['XML type', 'Native XML data type', 'XML column', 'Type definition'], 'correct' => 1],
            ['question' => 'What are XML indexing strategies?', 'options' => ['Index types', 'Path indexes, value indexes, full-text', 'XML index', 'Search optimization'], 'correct' => 1],
            ['question' => 'What XPath axes are most expensive?', 'options' => ['All same', 'descendant, following', 'parent, child', 'attribute'], 'correct' => 1],
            ['question' => 'What is XML diff?', 'options' => ['Difference', 'Algorithm to find changes between XML', 'Comparison', 'Change detection'], 'correct' => 1],
            ['question' => 'What is XML merge?', 'options' => ['Combining', 'Combining XML documents', 'Integration', 'Union'], 'correct' => 1],
            ['question' => 'What is EXI?', 'options' => ['Exit format', 'Efficient XML Interchange', 'Extended XML', 'External Interface'], 'correct' => 1],
            ['question' => 'What is advantage of EXI?', 'options' => ['More features', 'Compact binary format', 'Better performance', 'Easier parsing'], 'correct' => 1],
            ['question' => 'When to use XML vs JSON?', 'options' => ['Always XML', 'XML for complex schemas/validation, JSON for APIs', 'Always JSON', 'No difference'], 'correct' => 1],
            ['question' => 'What is advantage of XML over JSON?', 'options' => ['Simpler', 'Better validation/schemas', 'Smaller', 'Faster'], 'correct' => 1],
            ['question' => 'What is advantage of JSON over XML?', 'options' => ['Validation', 'Simpler, more compact', 'More features', 'Better tools'], 'correct' => 1],
            ['question' => 'What is XML signing implementation?', 'options' => ['Signature', 'XMLDSig with digest and signature', 'Crypto', 'Authentication'], 'correct' => 1],
            ['question' => 'What is XML encryption implementation?', 'options' => ['Encryption', 'XMLEnc with encrypted data elements', 'Security', 'Protection'], 'correct' => 1],
            ['question' => 'What hashing algorithms used in XMLDSig?', 'options' => ['MD5', 'SHA-256, SHA-512', 'Custom', 'Any hash'], 'correct' => 1],
            ['question' => 'What is lazy parsing?', 'options' => ['Slow parsing', 'Parsing on demand', 'Delayed parsing', 'Partial parsing'], 'correct' => 1],
            ['question' => 'What is streaming XML processing?', 'options' => ['Fast processing', 'Processing without loading entire document', 'Stream API', 'Continuous processing'], 'correct' => 1],
            ['question' => 'What is chunk-based XML processing?', 'options' => ['Breaking into parts', 'Processing XML in chunks', 'Partial processing', 'Segmented parsing'], 'correct' => 1],
            ['question' => 'What is XPath ancestor axis?', 'options' => ['Ancestors', 'All ancestors of node', 'Parent chain', 'Hierarchy'], 'correct' => 1],
            ['question' => 'What is XPath descendant axis?', 'options' => ['Descendants', 'All descendants of node', 'Children tree', 'Sub-tree'], 'correct' => 1],
            ['question' => 'What is XPath following axis?', 'options' => ['Next nodes', 'All nodes after current in document order', 'Following siblings', 'After nodes'], 'correct' => 1],
            ['question' => 'What is XPath preceding axis?', 'options' => ['Previous nodes', 'All nodes before current in document order', 'Previous siblings', 'Before nodes'], 'correct' => 1],
            ['question' => 'What is document order in XPath?', 'options' => ['Sorted order', 'Order nodes appear in document', 'Alphabetical', 'Tree order'], 'correct' => 1],
            ['question' => 'What is reverse document order?', 'options' => ['Reversed', 'Opposite of document order', 'Backward', 'Reverse traversal'], 'correct' => 1],
            ['question' => 'What is XPath position()?', 'options' => ['Location', 'Current node position in context', 'Index', 'Order number'], 'correct' => 1],
            ['question' => 'What is XPath last()?', 'options' => ['Final node', 'Size of context node set', 'Last position', 'End number'], 'correct' => 1],
            ['question' => 'Can XSLT 3.0 process JSON?', 'options' => ['No', 'Yes, with JSON support', 'Only XML', 'With extension'], 'correct' => 1],
            ['question' => 'What is XPath 3.1 used for?', 'options' => ['XML only', 'XML and JSON', 'Enhanced features', 'Latest version'], 'correct' => 1],
            ['question' => 'What is XSLT streaming advantage?', 'options' => ['Faster', 'Processes large documents with low memory', 'Better output', 'Parallel processing'], 'correct' => 1],
            ['question' => 'When should you use XML database?', 'options' => ['Always', 'When data is naturally hierarchical/semi-structured', 'Never', 'Small data only'], 'correct' => 1],
            ['question' => 'What is XML well-formedness constraint?', 'options' => ['Validation', 'Syntax rules that must be followed', 'Structure', 'Format rules'], 'correct' => 1],
            ['question' => 'What is XML validity constraint?', 'options' => ['Syntax', 'Schema/DTD rules that must be followed', 'Validation', 'Correctness'], 'correct' => 1],
            ['question' => 'Can you have comments in XML prolog?', 'options' => ['No', 'After XML declaration, yes', 'Anywhere', 'Not allowed'], 'correct' => 1],
            ['question' => 'What is best practice for XML performance?', 'options' => ['Large files', 'Use appropriate parser, avoid deep nesting', 'Complex structure', 'Many attributes'], 'correct' => 1],
        ]
    ],
];
require_once __DIR__ . '/quiz-engine.php';
